### ISSUE TITLE
Scenario outlines/Examples support

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#10]
Add support for scenario outlines and examples.

https://github.com/cucumber/cucumber/wiki/Scenario-outlines

**Comment by samvloeberghs** [comment]
@jbpros do you have an example of implementation somewhere?

**Comment by JimTheMan** [comment]
I interested in seeing the right way to implement Scenario Outlines, describe the table with Examples, and then especially how to access those variables in the step definition methods (given/when/then).

**Comment by charlierudolph** [comment]
Scenario outlines are just a way to shorten the amount of gherkin you write and don't have an effect on running. The scenario outline gets expended into scenarios with the variables replaced.
