### ISSUE TITLE
Microsoft jscript compilation error

### ISSUE THREAD

**Issue by Gruudu** [cucumber/cucumber-js#1000]
Hello,
I've tried to run cucumber in windows with "npm run cucumber" but I have this issue :
Script :
C:\git\folder\node_modules\.bin\cucumber.js
line:1
char:1
error:invalid character
code:800a03f6
source: miscrosoft jscript compilation error

How can i fix this ? My package.json look like :
{
"scripts": {
"cucumber": "cucumber.js ./Features -r ./Steps"
}

}

**Comment by Gruudu** [comment]
Ok it's just me.
In my package.json I just add .cmd like this :
"scripts": {
"cucumber": "cucumber.js.cmd ./Features -r ./Steps"
}

**Comment by Gruudu** [comment]
Ok I fix this with adding a ".cmd" to my package.json, like this : 
{
"scripts": {
"cucumber": "cucumber.js.cmd ./Features -r ./Steps"
}

**Comment by charlierudolph** [comment]
In the cli docs here: https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#cli there is a note for windows users that you should not use `cucumber.js`. We don't need three commands, so I'll create an issue for removing the other exposed binaries
