### ISSUE TITLE
deprecate JSON formatter

### ISSUE THREAD

**Issue by kevinkuszyk** [cucumber/cucumber-js#1007]
@charlierudolph to continue the conversation on #999 and raise awareness of this for others:

> The JSON formatter is essentially deprecated in favor of the event protocol formatter

Is this the case?  If so, a couple of questions:

1. Can this be mentioned in the docs somewhere?
2. Is there a recommended alternative to get json output so that it can still be exported / piped into other libs that consume it? 

Thanks!

/cc @oledid @wswebcreation

**Comment by charlierudolph** [comment]
Has not been mentioned / deprecated in the code but we can add that. As mentioned the event protocol formatter is the replacement. See https://github.com/cucumber/cucumber/issues/187

**Comment by kevinkuszyk** [comment]
Thanks, after doing some more reading yesterday and looking at cucumber/cucumber#187 this morning I understand where you are going now.

Would you be interested in a PR to update the docs?

**Comment by KyleFairns** [comment]
Just to re-iterate the question above, will there be an alternative to get the JSON output we currently have from a new source? Or will we have to go through the event formatter ourselves in order to do this?

**Comment by aslakhellesoy** [comment]
The JSON formatter will be removed in a future release - from all Cucumber implementations (JavaScript, Java, Ruby) - see https://github.com/cucumber/cucumber/issues/415 for more details.

As a replacement there will be a message protocol based on [protocol buffers](https://developers.google.com/protocol-buffers/). We have already started this work - see https://github.com/cucumber/cucumber/pull/416. The current message definitions are [here](https://github.com/cucumber/cucumber/tree/messages_gherkin-rule-keyword-protobuf/messages), and we'll be adding more messages to represent results.

We will not remove the JSON formatter until the new message protocol is complete enough to replace it. They'll probably coexist during one version, and then the JSON formatter will be removed.

This means 3rd party tools like XRay will have to be upgraded to use the new message protocol.

The JSON formatter is inconsistent between the various implementations, and it doesn't have a schema. With the message protocol, there will be a strict schema that all implementations will adhere to.

We don't have a deadline for when this will happen, but there will be ample time to prepare for it. I plan to publish a blog post with more details, allowing 3rd party tool vendors to prepare for the change.

**Comment by KyleFairns** [comment]
There's also the question of whether to keep this functionality until native support has been added for JS on Cucumber Pro.

According to the site, the only native support comes from Java. The others are being worked on, but currently require JSON to be uploaded.

**Comment by charlierudolph** [comment]
Closing as not planning on deprecating anymore but there will be some big changes coming as part of the implementation of retry. We'll start fresh and build up requirements. It will essentially be a collated version of the event protocol formatter
