### ISSUE TITLE
cucumber version 3..10.10 s

### ISSUE THREAD

**Issue by munna73** [cucumber/cucumber-js#1009]
>npm cucumber --version
3.10.10
I have feature file and stepdefination files, test times out for some reason. It umable to move on from Given to Then.

  at Timeout.<anonymous> (src\user_code_runner.js:61:18)
           at ontimeout (timers.js:386:14)
           at tryOnTimeout (timers.js:250:5)
           at Timer.listOnTimeout (timers.js:214:5)

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
1m00.013s
I/launcher - 0 instance(s) of WebDriver still running
] I/launcher - chrome #01 failed 1 test(s)
 I/launcher - overall: 1 failed spec(s)
E/launcher - Process exited with error code 1

Sample step definition file  Please advise

 var {defineSupportCode} = require('cucumber');
 var baseTest = require('../../testspec/BaseTest.js')
 var homepage = require("../../pages/HomePage.js")

defineSupportCode(function({setDefaultTimeout}) {
  setDefaultTimeout(60 * 1000);
});

defineSupportCode(function ({Given, Then, When}) {

	
	 Given('User Logged in with to  Utility', function (callback) {
		 baseTest.uApplaunch();
       });

 

       Then('Application is accessible', function (callback) {
        homepage.navigateToUapp();
       });
});

**Comment by charlierudolph** [comment]
See the docs about step definitions: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md 

It appears you are using the async callback interface but not calling the callback.

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if necessary
