### ISSUE TITLE
Function timeout issue

### ISSUE THREAD

**Issue by vinodkpasi** [cucumber/cucumber-js#1012]
Hello, cucumber-js is new for me. I’m trying to do the nodejs example, I get following error:
Scenario: Tabs Functionality - Test_Modules\LCC\Features\tabs.feature:2
   Step: Given Using Tab functionality - Test_Modules\LCC\Features\tabs.feature:3
   Step Definition: Test_Modules\LCC\step_definitions\tabs.js:2
   Message:
     **function timed out after 100000 milliseconds**

**Comment by charlierudolph** [comment]
That is the general error you get if cucumber doesn't think the step has finished running. See [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md) for the different style of step interfaces. I'll create an issue to update the error message to try and be more clear.
