### ISSUE TITLE
Anchor characters ^ and $ do not perform an exact match

### ISSUE THREAD

**Issue by shailysingh** [cucumber/cucumber-js#1013]
The anchor characters do not function as expected in Cucumber(serenity.cucumber.version=1.6.9). This has worsened since the upgrade to latest IntelliJ (2017.3.2 Community version) and Serenity(1.8.19). 

^ and $ are supposed to find an exact match of the regular expression, but we have been getting a lot of ambiguous step definition exceptions, since they do not find an exact match.

For e.g. 
cucumber.runtime.AmbiguousStepDefinitionsException: "the user creates a new Item List NewItemList" matches more than one step definition:
  "^(?:I|the user) creates? a new Item (.+)$" in ItemManagementSteps.createANewItem(String)
  "^(?:I|the user) creates? a new Item List (.+)$" in ItemManagementSteps.createANewItemList(String)

**Comment by aslakhellesoy** [comment]
What do you mean by "The anchor characters do not function as expected"?

Try this in a JavaScript console:

```javascript
"the user creates a new Item List NewItemList".match(/^(?:I|the user) creates? a new Item (.+)$/)
"the user creates a new Item List NewItemList".match(/^(?:I|the user) creates? a new Item List (.+)$/)
```

The string matches both regular expressions (and is therefore ambiguous). I don't see how this has anything to do with Cucumber, Serenity or IntelliJ.

**Comment by shailysingh** [comment]
Thanks, I see it now. If I use single quotes around the arguments, I do not get an exception.
However, after an upgrade to the latest Serenity version, we cannot use single quotes to pass the arguments.  Thus, we had to remove the single quotes, and all our feature files are full of ambiguity now.
=======================================
As per Serenity 1.8, something has changed in the way Serenity handles scenarios with variables. The 'old' way of including variables executes the code, but the test result is not displayed in the test runner tab. As a consequence, scenarios with failed test steps are displayed as if they're passed. To fix, follow steps below.

As a reminder, including a variable in a scenario was done like this:

Scenario: my scenario

When I do ‘Something’

~ Gherkin script~ 

which in turn was included in the steps.java class as

 @When(“^I do ‘(.+)’$”)

java code

Instead, the same scenario should now be implemented like this:

(Scenario: myscenario

  When I do Something 

implemented in myscenarioSteps.class:

@When(“^I do (.+)$”) .

Serenity recognizes Something as a variable without quotation marks and subsequently the When annotation doesn't need them either. 
=======================================
Maybe I will close this one, and add another one with the issues on using single quotes.
