### ISSUE TITLE
Can't call a function from another function in the world module

### ISSUE THREAD

**Issue by kappa10j** [cucumber/cucumber-js#1015]
I get SwitchWindow does not exist when I call switchWindowByTitle from one of my steps.  

ReferenceError: switchWindow is not defined

const { setWorldConstructor } = require('cucumber')

class CustomWorld {
  constructor() {
    this.variable = 0
    this.hub
    this.node
  }

  setTo(number) {
    this.variable = number
  }

  incrementBy(number) {
    this.variable += number
  }

  switchWindow(windowHandle, callback) {
    this.client.switchTo().window(windowHandle).then(function () {
        // known issue:  getTitle may hang if the window closed
        // https://bugs.chromium.org/p/chromedriver/issues/detail?id=1132
        this.client.getTitle().then(function (title) {
            callback(title);
        });
    }).then(null, function(e) {
                    // some windows get opened and closed during startup, so not really an error
                    callback("no such window");
                });
    }

/**
 * Select the window with specified title.
 *
 * @param windowTitle window title
 * @param done done callback for Mocha
 */
/**
 * Select the window with specified title.
 *
 * @param windowTitle window title
 * @param done done callback for Mocha
 */
switchWindowByTitle(windowTitle, done) {
  this.client.getAllWindowHandles().then(function (handles) {
      var handleIndex = 0,
          checkTitle = function (title) {
          if (title === windowTitle) {
                  done();
          } else {
              handleIndex += 1;
              if (handleIndex < handles.length) {
                  switchWindow(handles[handleIndex], checkTitle);
              } else {
                  // the window may not be loaded yet, so call itself again
                  switchWindowByTitle(windowTitle, done);
              }
          }
      };
      switchWindow(handles[handleIndex], checkTitle);
  });

}
}

setWorldConstructor(CustomWorld)

**Comment by charlierudolph** [comment]
Within `switchWindowByTitle`, you would call it via `this.switchWindow`. The custom world is a javascript class and this is the same way you access other instance methods in any other javascript class
