### ISSUE TITLE
Runtime.start() always return success.

### ISSUE THREAD

**Issue by Izhaki** [cucumber/cucumber-js#1017]
We are using cucumber programmatically, just as the [browser example](https://github.com/cucumber/cucumber-js/tree/b28de6f2cd8bd47e486ed0d755ca7ad441f77185/example).

Although not conventional, we are actually wrapping cucumber with jasmine `it` blocks. In order not to clutter the output, we don't log anything:

```javascript
  const formatterOptions = {
    colorsEnabled: true,
    cwd: '/',
    eventBroadcaster,
    eventDataCollector,
    log(data) {
      // console.log(data);
    },
    supportCodeLibrary
  };

```
Problem is, that if there is an exception or any other issue when running a feature, there is no indication of it whatsoever.

Looking at the [/src/runtime/index.js](https://github.com/cucumber/cucumber-js/blob/b28de6f2cd8bd47e486ed0d755ca7ad441f77185/src/runtime/index.js):

```javascript
  async start() {
    if (this.options.filterStacktraces) {
      this.stackTraceFilter.filter()
    }
    this.eventBroadcaster.emit('test-run-started')
    await this.runTestRunHooks('beforeTestRunHookDefinitions', 'a BeforeAll')
    await Promise.each(this.testCases, ::this.runTestCase)
    await this.runTestRunHooks('afterTestRunHookDefinitions', 'an AfterAll')
    this.eventBroadcaster.emit('test-run-finished', { result: this.result })
    if (this.options.filterStacktraces) {
      this.stackTraceFilter.unfilter()
    }
    return this.result.success
  }
```
You can see that it always returns success (actually, I thought `success` was a const, but turns out it's a boolean).

I'm not sure this is the desired behaviour? In case there's a failure, shouldn't `start` return a rejected promise (ie, throw)?

----

We ended up buffering the output then show it if `success === false` and throw. Yet, given it returns a promise shouldn't `start()` throw on error?

**Comment by charlierudolph** [comment]
> I'm not sure this is the desired behaviour? In case there's a failure, shouldn't start return a rejected promise (ie, throw)?

This is the desired behavior (at least currently). It only rejects if there is an internal cucumber error or a before all / after all hook fails. A failed scenario is not an error to cucumber and is instead something it needs to handle and report. I understand a failed scenario being an error to a user of cucumber, but not to the tool itself

**Comment by Izhaki** [comment]
Makes sense, and as I said - were can easily work around it. Thanks!
