### ISSUE TITLE
improve timeout message

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#1019]
Currently when a step times out, it only says "function timed out after x milliseconds". Lets try and make this more informative. Maybe something like:

- with callback interface
  - function timed out, ensure the callback is executed within x milliseconds
- with promise interface
  - function timed out, ensure the promise resolves within x milliseconds

**Comment by stevecooperorg** [comment]
It would be really useful if this message could be updated by the user. I'm doing a lot of Selenium testing, and Selenium uses a 'wait until' model - 'wait for the dialog to appear' or 'wait until the server has responded'. If I could call something `setTimeoutMessage('waiting for ' + dialogTitle + ' dialog to appear')` and see `The function timed out after 30,012 milliseconds: waiting for save dialog to appear` that would really help us find out what exactly is going wrong in a test.

**Comment by charlierudolph** [comment]
@stevecooperorg for that instance, I would update your code so selenium throws a timeout error before the step times out. Then you can control the error message there. Ideally, I don't think anyone should hit the step timeout error message regularly

We can add something about that to the new error message.

**Comment by charlierudolph** [comment]
resolved in #1028
