### ISSUE TITLE
remove generators

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#1021]
Remove generator snippet interface in favor of async-await and remove `setDefinitionFunctionWrapper` since that was used to turn generator functions into promises. Appears `setDefinitionFunctionWrapper` has been used for other things so need to ensure #997 can address the use case of being able to wrap a step with custom logic.

**Comment by davidjgoss** [comment]
@charlierudolph looping back to this now `BeforeStep` and `AfterStep` are a thing. Maybe a PR now to mark `setDefinitionFunctionWrapper` as deprecated, and then we remove for v8.0.0 when the time comes?

**Comment by charlierudolph** [comment]
Sounds good to me

**Comment by davidjgoss** [comment]
Note to self that we should be able to finish removing `bluebird` as part of this, see #1566
