### ISSUE TITLE
How to Find the ParameterCount in cucumberjs-Basically Iteration Count from Examples Table

### ISSUE THREAD

**Issue by narayanasamyramaiah** [cucumber/cucumber-js#1025]
I have 2 Functions
Expand The User Section
Collapse User Section

When User input Value <Name>
Verify User input with <Name>

Examples:
|Name|
|   A    |
|   B    |
|   C    |

Now I wanna call Expand User Section only for  1st Iteration with value 'A' and call Collapse User Section only When I am in Last Iteration when i Read value 'C'

How to do in Cucumberjs.

I am using Protractor+cucumber+TypeScript

Thanks

**Comment by narayanasamyramaiah** [comment]
I have 2 Functions
Expand The User Section
Collapse User Section

When User input Value <Name>
Verify User input with <Name>

Examples:
|Name|
|   A    |
|   B    |
|   C    |

Now I wanna call Expand User Section only for  1st Iteration with value 'A' and call Collapse User Section only When I am in Last Iteration when i Read value 'C'

How to do in Cucumberjs.

I am using Protractor+cucumber+TypeScript

Thanks

**Comment by narayanasamyramaiah** [comment]
I have 2 Functions
Expand The User Section
Collapse User Section

When User input Value  With Name <<Name>>
Verify User input with Name <<Name>>

Examples:
|Name|
|   A    |
|   B    |
|   C    |

Now I wanna call Expand User Section only for  1st Iteration with value 'A' and call Collapse User Section only When I am in Last Iteration when i Read value 'C'

How to do in Cucumberjs.

I am using Protractor+cucumber+TypeScript

Thanks

**Comment by charlierudolph** [comment]
Cucumber isn't built to handle such a situation and discourages sharing state between scenarios. You can do all three in the same scenario be using a step table instead of a scenario outline, of you should expand / collapse the user section for each example.

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed
