### ISSUE TITLE
Step duration stored in the wrong format in JSON reports

### ISSUE THREAD

**Issue by achingbrain** [cucumber/cucumber-js#1026]
We run our cucumber js reports through the [cucumber-reports-plugin](https://github.com/jenkinsci/cucumber-reports-plugin) as part of CI - I'm trying to work out why all of our steps are being reported as taking 000ms.

It looks like `cucumber-jvm` and `cucumber-ruby-core` reports step times in ns.  `cucumber-js` [appeared to do so once](https://github.com/ldegen/cucumber-js/commit/5506474eb694fbd2c1b51d8e5572fc747f2e325b#diff-32f4d08dd02a810f0dc5dbadb6b66cebR41) but it now looks like it [reports it in ms](https://github.com/cucumber/cucumber-js/blob/master/src/time.js#L23).

Ideally `cucumber-js` would bring it's output in line with other cucumber implementations.

I'm happy to submit a PR if there's a chance of it being merged?

**Comment by charlierudolph** [comment]
This has been fixed in 4.0.0. We can backport to 3.x if needed.

**Comment by achingbrain** [comment]
I'll give that a go.  Backporting it might help other people though.

**Comment by charlierudolph** [comment]
Closing due to age. Still open to a PR that backports to 3.x if anyone needs it
