### ISSUE TITLE
Provide @types for version 4

### ISSUE THREAD

**Issue by fredgate** [cucumber/cucumber-js#1029]
I am developing an angular 5 application.
I added cucumber to the e2e. In my package.json, I got the last version of cucumber : 4.0.0.
When I executed my code, I have error message saying that defineSupportCode is deprecated, and that I should import individual methods instead.
Problem : I can not import When, Given, Then because they are not present in the typing file for typescript : the last version of @types/cucumber is only 3.2.1.
It is not useful to develop with typescript, so could you provide the typescript definition, either directly in the package or in the @types/cucumber package.

**Comment by bruce-lindsay** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23241

This just was merged a few hours ago. I ran into the same issue and submitted a pr to definitely typed yesterday. 

Try the new typings for 4.0 https://www.npmjs.com/package/@types/cucumber

**Comment by fredgate** [comment]
I tried the new typings and it looks good !
I have not tested everything but the new functions Given, Then, When are now available to replace defineSupportCode.

**Comment by charlierudolph** [comment]
Closing as this appears to be resolved
