### ISSUE TITLE
UnableToDebug-Protractor-CucumberJS-Typescript

### ISSUE THREAD

**Issue by narayanasamyramaiah** [cucumber/cucumber-js#1034]
Hi Team,

I am unable to debug my Scripts and whenever i try to do, I am getting cucumber not present al though its there in my working directory.
Please help me.
<img width="805" alt="inkeduntitled_li" src="https://user-images.githubusercontent.com/23472748/35620953-c8bd3d76-06a8-11e8-9ac4-7f1cc300e2ec.png">

**Comment by charlierudolph** [comment]
Based on the error message it appears you need to install cucumber as a dependency. Other than that I don't know what could be wrong. For protractor related errors please first create an issue on https://github.com/protractor-cucumber-framework/protractor-cucumber-framework.
