### ISSUE TITLE
isFailed() method doesn't working

### ISSUE THREAD

**Issue by ezwanharun** [cucumber/cucumber-js#1057]
cucumber version :4.0.0
`    
afterScenario: function afterScenario(scenarioResult) {
        if (scenarioResult.status != "passed") {
            browser.saveScreenshot("./allure-results/");
        }
    }

`

also tried with 

`

    afterScenario: function afterScenario(scenarioResult) {
        if (scenarioResult.isFailed()) {
            browser.saveScreenshot("./allure-results/");
        }
    },

`

I noticed that that if condition can't been executed at all. I tried with afterStep() method, it work as expected. However, i don't want to screenshot in steps level.

**Comment by charlierudolph** [comment]
`scenarioResult` and `isFailed` are old APIs. Please see [here](https://github.com/cucumber/cucumber-js/blob/v4.1.0/docs/support_files/attachments.md) for the v4 docs about attachments in hooks for failed scenarios. 

AfterStep is not something built into cucumber. Are you using another program to execute cucumber?

**Comment by ezwanharun** [comment]
yeah. i tried to used `testCase.result.status === Status.FAILED` method. It doesnt execute that specific method at all. Think that this is due to other dependencies that I used `wdio-cucumber-frameowrk`

**Comment by ezwanharun** [comment]
ljust raised in wdio-cucumber-framework repo.   https://github.com/webdriverio/wdio-cucumber-framework/issues/108
