### ISSUE TITLE
Running specific scenario of feature file

### ISSUE THREAD

**Issue by vinodkpasi** [cucumber/cucumber-js#1062]
I am using protractor/cucumber.js/protractor-cucumber-framework.

How to run specific scenario in a feature file?

**Comment by charlierudolph** [comment]
If you are using the cucumber cli, there are [docs](https://github.com/cucumber/cucumber-js/blob/v4.1.0/docs/cli.md#running-specific-features) for this. Otherwise, please open an issue on protractor-cucumber-framework as it wraps cucumber and thus the api may be different.

**Comment by charlierudolph** [comment]
Closing as appears resolved. Please reopen if needed
