### ISSUE TITLE
How to pass the data from JSON file to the feature file of cucumber-nodejs framework

### ISSUE THREAD

**Issue by mandy8055** [cucumber/cucumber-js#1063]
Hello All
I was thinking is there any way to pass the data from JSON file to the .feature file of cucumber-nodejs.
I found a  couple of links([**1**](https://stackoverflow.com/questions/37680463/how-to-pass-a-csv-file-in-examples-in-feature-file-and-read-values-from-csv-fi) and [**2**](https://shvets.github.io/blog/2014/10/19/adding_source_to_gherkin_script.html)) which tells how to do the same using a .csv file but I cannot find the same for the json file.

Please do let me know if there is any workaround for the same.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
