### ISSUE TITLE
Expose outputTo in formatter's options

### ISSUE THREAD

**Issue by kozhevnikov** [cucumber/cucumber-js#1066]
Would it be possible to expose `outputTo` to formatter's constructor's `options`? I can access file descriptor via `options.stream.fd` (`options.stream.path` is null) but getting path out it and pid requires `lsof` and doesn't seem to work on Windows where fd is always 1. Repasring `process.argv` with `ConfigurationBuilder` is an option but messy as it is async and `type` can take many forms (with and without `./`, etc).

https://github.com/cucumber/cucumber-js/blob/master/src/cli/index.js#L39

**Comment by charlierudolph** [comment]
What is the use case for this?

**Comment by kozhevnikov** [comment]
When a formatter outputs more than 1 file, e.g. I'm writing an HTML formatter and due to [Jenkins' Content Security Policy](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy) incline CSS is not allowed so I need to write out a .css file in the same folder as the .html.

**Comment by kozhevnikov** [comment]
Yes, if the output is stdout then the additional files will not be written (or in case of HTML formatter an  inlined template used). Some formatters do not lend themselves to stdout and are meant to be used only with file streams, e.g. a .docx or other binary-like streams.

The separate binary route sounds overly complicated for no benefit. I would rather reparse the args again or monkeypatch. I wouldn't say it muddles the simplicity of formatters, I imagine many use cases of multifile formatters, i.e. outputting .xml with corresponding .xslt, a curl shellscript with json file payload, an extracting-attachments-for-archiving-to-S3 formatter,  any number of formats that are basically zip files with multifile content inside, etc.

**Comment by davidjgoss** [comment]
Closing as it's been quiet for a long time. We now have the standard messages output which is intended to be used to create standalone formatters similar to what's described above.
