### ISSUE TITLE
Allow configurable file extensions for step files

### ISSUE THREAD

**Issue by mattgibson** [cucumber/cucumber-js#1068]
I want to use Cucumber to test a React single page app by rendering it using [Enzyme](https://github.com/airbnb/enzyme) without a browser within the scenarios. However, this requires me to be able to run the step definition and support files through Babel in order to process the JSX to set up and test the app. This in turn ideally needs the files in question to have the `.jsx` extension so that they can be clearly separated from the other project files which don't need compiling. At the moment, support files are only recognised if they end in `.js`, leading to step defnitions not being found. It would be better to be able to override this extension with a glob pattern if necessary.

**Comment by charlierudolph** [comment]
Closing since I don't believe this is needed and lack of response. Please reopen if you want to discuss more
