### ISSUE TITLE
protractor-cucumber-bdd-tests-show-pass-before-execution

### ISSUE THREAD

**Issue by arjun1092** [cucumber/cucumber-js#1072]
Hi team,
By cucumber tests are passing without the test scripts being executed.  I have Page object model design pattern and I had integrated cucumber-js along with that. 

Sample snippet

```
 Scenario: Profile page should have various links for interest,Goals, Badges and stats
        Given  the user has successfully completed login and is present in homepage
        When the user click on menu icon on the upper right corner on the screen
        And he clicks on profile link 
        Then the employee should be displayed the profile section
        And there should be links corresponding to interests
        And there should be links corresponding to Goals
        And there should be links corresponding to Badges
        And there should be links corresponding to stats
`
```
Step_definition
```
const path = require('path');
const {Given,Then,When} = require('cucumber');
const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
const expect = chai.expect;

//Page object related
var testdata = require('../../configurationFiles/ConfigValues.json');
var LexLandingPage = require('../../page_objects/LandingPage.js');

var LexlandPage=new LexLandingPage();
var LexLoginpage = new lexLogin();
var MSLoginpage=new MSLogin();

		 Given('the user has successfully completed login and is present in homepage', function () {
     LexLoginpage.goTo(testdata.testsiteurl);

    //****Test script Excution starts****
    
     LexlandPage.clickOnLogin();
     MSLoginpage.EnterEmail("XXX@xxx.com");  
     MSLoginpage.ClickonNext();
  }
```);

Where The page object method looks like below
```
  
  this.clickOnLogin = function() {
		browser.sleep(6000);
		LoginLink.click();
	};
	
		this.EnterEmail = function(email) {
		EmailId.sendKeys(email);
	};
```

Console is displaying all the test steps as passed. 

package.json file

```
 "dependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "cucumber-pretty": "^1.4.1",
    "jasmine": "^3.1.0",
    "jasmine-data-provider": "^2.2.0",
    "protractor": "^5.3.1",
    "protractor-dev": "^0.23.6",
    "report": "^0.1.1"
  },
  "devDependencies": {
    "cucumber": "^4.2.1",
    "cucumber-html-report": "^0.6.5",
    "cucumber-html-reporter": "^4.0.2",
    "eslint": "^4.19.1",
    "eslint-config-google": "^0.9.1",
    "eslint-plugin-protractor": "^1.40.0",
    "gulp": "^4.0.0",
    "gulp-protractor-cucumber-html-report": "^0.1.3",
    "log4js": "^2.5.3",
    "log4js-protractor-appender": "^1.1.2",
    "protractor-cucumber-framework": "^5.0.0"
  },
```

**Comment by charlierudolph** [comment]
@arjun1092 there isn't enough info here for me to guide and or for me to think its a possible bug. Please seek help first through `protractor-cucumber-framework` as that is something I have no experience in
