### ISSUE TITLE
Gerkin and Cucumber: Enter the card number in the box

### ISSUE THREAD

**Issue by rickymuvel** [cucumber/cucumber-js#1075]
I have the following error:

     Undefined. Implement with the following snippet:
    
             When('Enter the card number in the box', function () {
               // Write code here that turns the phrase above into concrete actions
               return 'pending';
             });

// login.step.ts

    import { expect } from 'chai';
    const { Given, When, Then, Before } = require('cucumber');
    
    import { browser, by, element } from 'protractor';
    import { LoginPage } from './login.po';
    
      let login: LoginPage;
    
      Before(() => {
        login = new LoginPage();
      });
    
      Given(/^Entering in Login$/, { timeout: 10 * 5000 }, async () => {
        await browser.get('http://localhost:49152/login');
      });
    
      When(/^Enter the card number in the box"$/, () => {
        // login.setCardNumber('1234').then((txt) => {
        //   return 'ready!?';
        // })
        login.setCardNumber('1234');
      });

// login.po.ts

    import { browser, by, element, until } from 'protractor';
    
    export class LoginPage {
      navigateTo() {
        return browser.get('/login');
      }
    
      setCardNumber(cardNumber) {
        const input = element(by.css('#box'));
        return input.sendKeys(cardNumber);
      }
    
    }

**Comment by charlierudolph** [comment]
Your step definition `When(/^Enter the card number in the box"$/, ...)` has an extra double quote at the end.
