### ISSUE TITLE
How to use EventProtocolFormatter to call the beforeStep and afterStep in Cucumber v4?

### ISSUE THREAD

**Issue by vignesh-paramasivam** [cucumber/cucumber-js#1076]
We need to log the step level info, so going through the hooks, where for the cucumber(v4.2.1) uses EventProtocolFormatter, i have tried to invoke it, but its not successful.

```
// support/hooks.js
const {Before, After} = require('cucumber');
const {setDefaultTimeout} = require('cucumber');

setDefaultTimeout(60000);

Before(function (scenario) {

});

// How to invoke the EventProtocolFormatter here to call the beforeStep and afterStep?
// Do we need to require and call the events in this way?
let local_event_formatter = require('../../node_modules/cucumber/lib/formatter/event_protocol_formatter.js');

After(function (scenario) {
    browser.close();
    return browser.quit();
});
```

Same has been asked here.. [stackoverflow](https://stackoverflow.com/questions/50019227/how-to-use-eventprotocolformatter-to-call-the-beforestep-and-afterstep-in-cucumb)

**Comment by charlierudolph** [comment]
Those hooks were removed and you should not use event protocol formatter directly. You can write your own formatter if you want to log something specific otherwise will need to wait for #997

**Comment by vignesh-paramasivam** [comment]
Hello @charlierudolph, Yes, I have created my own formatter using the event listeners to log step level information. Thank you!
