### ISSUE TITLE
In Scenario Outline Example the character "$" is not escaped correctly

### ISSUE THREAD

**Issue by imzengyang** [cucumber/cucumber-js#1077]
When using Example in Scenario Outline, when I type "P@$$$0wod" in the table, one of "$" is missing during execution, the actual value I got during execution is "P@$$0wod",

this is my scenario outline:

```gherkin
Scenario Outline: userLoggin
    Given go to the login page
    When input"<username>"
    When input"<password>"
    When click login btn
    Then i should "<status>"，and get message"<checkpoint>"
    Examples: 
      | username   | password | status | checkpoint |
      | P$$w0rd | 123456   | fail | username or password error   |
```

When i run this Scenario Outline, the step definition get `P$w0rd` instead of `P$$w0rd`. Note that one "$" is missing.

Can you help fix the Cucumber code so that $ character is escaped correctly and the exact string be passed to the step definition code. Thanks.

**Comment by charlierudolph** [comment]
To update, the issue was in a dependency and has been fixed. Waiting on the dependency to release a new version with the fix

**Comment by charlierudolph** [comment]
Should be fixed with an upgrade to gherkin 5.1.0 which should by pulled in on any new install. I'll make a release with that being the minimum version this weekend

**Comment by VivekLande** [comment]
Is this issue been fixed? I am still getting the same issue with version 6.0.5, could you please help us to resolve this?

**Comment by aslakhellesoy** [comment]
It's been fixed on the master branch, but hasn't yet been released. The next release will fix it.

**Comment by VivekLande** [comment]
> It's been fixed on the master branch, but hasn't yet been released. The next release will fix it.

Thanks for the confirmation. Could you please help us to know when we can expect the next release with this fix?

**Comment by aslakhellesoy** [comment]
Cucumber is mostly developed by volunteers in their spare time, so that's impossible to say. "Soon" is my best estimate.

**Comment by VivekLande** [comment]
Thank you so much for quick res

> Cucumber is mostly developed by volunteers in their spare time, so that's impossible to say. "Soon" is my best estimate
Hey @aslakhellesoy, Thank you so much for your quick response, much appreciated

**Comment by VivekLande** [comment]
Hi @aslakhellesoy, could you please suggest any other way to handle this issue at our end? till the time you guys give fixed eg. overriding any cucumber lifecycle method, I need to handle this on priority, this issue totally blocking me to migrate from V5 to V6 of cucumber.

**Comment by aslakhellesoy** [comment]
Sorry, I don't have a workaround other than not using `$`.

**Comment by code4muktesh** [comment]
@aslakhellesoy  As per [this](https://github.com/cucumber/cucumber/commit/bb8579420125eb2a655e7a693bef653f544b2313 )  issue is fixed. 
But, Cucumber-js v6.0.5 is still pointing to [gherkin version 5.0.0](https://github.com/cucumber/cucumber-js/blob/v6.0.5/package.json#L168)

Is there any plan to release the Cucumber-js v6.x with this fix?

**Comment by davidjgoss** [comment]
7.0.0 is now released, see [the changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) for migration instructions. This includes the latest Gherkin which includes a fix for this issue. Thanks!
