### ISSUE TITLE
nested features are breaking availability of support files

### ISSUE THREAD

**Issue by sdepold** [cucumber/cucumber-js#108]
When features are located in a deeper nested folder than `./features`, all the lovely support files aren't available anymore.

My folder structures is available here: https://gist.github.com/46b9d58332ab13c89ff1

When I move the feature definition (originally located at `./features/session/new`) to `./features/new.feature` my support files are perfectly available.

The current workaround is `node_modules/.bin/cucumber.js -r feature`.

**Comment by tommysullivan** [comment]
I just had this bug. If you have features only in subfolders it doesn't load support or step definitions. Very frustrating!!!!!!!

**Comment by charlierudolph** [comment]
This is mitigated with profiles, as you can add a require to your default profile. This is consistent with the ruby implementation.
