### ISSUE TITLE
World.attach doesn't log a long value properly as JSON

### ISSUE THREAD

**Issue by kappa10j** [cucumber/cucumber-js#1086]
this.logText(jsontext, 'application/json');

The attachment works correctly when json text is:
jsontext ="[{"key":"476007500100000067","request time":"2018-05-03T12:47:39.115Z","response time":"2018-05-03T12:47:39.221Z"}]"
OR
jsontext = "[{"key":4760075,"request time":"2018-05-03T12:47:39.115Z","response time":"2018-05-03T12:47:39.221Z"}]"

{
  "key": "476007500100000067",
  "request time": "2018-05-03T12:47:39.115Z",
  "response time": "2018-05-03T12:47:39.221Z"
}
OR
{
  "key": 4760075,
  "request time": "2018-05-03T12:47:39.115Z",
  "response time": "2018-05-03T12:47:39.221Z"
}

but fails when it's something like
jsontext = "[{"key":476007500100000067,"request time":"2018-05-03T12:47:39.115Z","response time":"2018-05-03T12:47:39.221Z"}]"

The resulting JSON ends up with a rounded value like 476007500200000100

{
  "key": 476007500200000100,
  "request time": "2018-05-03T12:47:39.115Z",
  "response time": "2018-05-03T12:47:39.221Z"
}

I see the correct value when attaching as text.
"[{\"key\":476007500100000067,\"request time\":\"2018-05-03T12:47:39.115Z\",\"response time\":\"2018-05-03T12:47:39.221Z\"}]"

Is there a way to make attach support longs?

**Comment by charlierudolph** [comment]
I don't believe this a cucumber issue. `JSON.parse` with your sample text gives the rounding issue and thus this is an issue with how well node / browser can accurately represent large numbers.

**Comment by kappa10j** [comment]
Does world.attach use JSON.parse under the hood?  If so, then yes.  I
convert to string whenever I need to do a json.parse but I didn't realize
attach parses.

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed
