### ISSUE TITLE
Slack signup not working

### ISSUE THREAD

**Issue by joscha** [cucumber/cucumber-js#1089]
https://cucumberbdd-slack-invite.herokuapp.com/ fails with:

![join_the_cucumberbdd_community_on_slack_](https://user-images.githubusercontent.com/188038/39739005-ef94e802-52d1-11e8-902e-fc9ac17dfbb3.png)

Does that mean it is acceptable to use the issue tracker for questions? :)

**Comment by mattwynne** [comment]
Yikes. I'll fix that ASAP.

**Comment by mattwynne** [comment]
Thanks for letting us know!

**Comment by mattwynne** [comment]
OK @joscha I think that's fixed. Can you give it a whirl?

**Comment by joscha** [comment]
Looks good, got an invite!
