### ISSUE TITLE
cucumber-js unable of retrieving a parameter ending before a specific string .(?!test) in step definition

### ISSUE THREAD

**Issue by Mouad-B** [cucumber/cucumber-js#1096]
Hello,
I tried to set this regex for an authentication Given step with two optional parameters: 
`Given(/^I log in as ([A-Za-z\-]+)(?: with the contract ((?:.(?!for the protal))+))?(?: for the protal (.*))?$/, function(user, contract, portal, callback) {
  console.log({user, contract, portal});
}`
Cucumber-js fails to detect the second optional parameter even if it successfully matches the expressions to the Given sentence with one, two or three parameters.
I put `.(?!for the protal)` in the second parameter to end it when the third one (portal) eventually begins as the list of contracts isn't exhaustive.

Here's the output I get for the three cases:

`Given I log in as tester1`

> user: tester1,
> contract: undefined,
> portal: undefined

 :+1: 

`Given I log in as tester1 with the contract contract1`

> user: tester1,
> contract: undefined,
> portal: undefined

 :-1: 

`Given I log in as tester1 with the contract contract1 for the protal portal1`

> user: tester1,
> contract: portal1,
> portal: undefined

 :-1: 

I think there is an issue with detecting this part of the regex .(?!for the protal) in cucumber-js as exactly the same expression works in Java but not in JS. In addition to that, Cucumber in Java successfully sets to second parameter as undefined when only the first and the third are mentioned (but this is another issue).

Thanks !

**Comment by charlierudolph** [comment]
Confirmed this is a bug in cucumber-expressions. In the meantime, I think your regular expression is more  complex than need be. I would suggest the following:

```js
Given(/^I log in as ([A-Za-z\-]+)$/ /* ... */)
Given(/^I log in as ([A-Za-z\-]+) with the contract "(.*)"$/ /* ... */)
Given(/^I log in as ([A-Za-z\-]+) with the contract "(.*)" for for the protal "(.*)"$/ /* ... */)
```
I added quotes around whats captured to avoid multiple step definitions matching the same thing.
You can have keep the step implementation dry by extracting the common logic into a helper function. You can also switch to cucumber-expressions which I think are much nicer:
```js
Given('I log in as {string}' /* ... */)
Given('I log in as {string} with the contract {string}' /* ... */)
Given('I log in as {string} with the contract {string} for the protal {string}' /* ... */)
```
Where `{string}` is a single or double quoted string. See here for more info on cucumber expressions: https://docs.cucumber.io/cucumber/cucumber-expressions/

**Comment by Mouad-B** [comment]
thanks @charlierudolph 
I finnaly found another expression that works with one mandatory and two optional parameters:
`/^I log in as ([\w-]+)(?: with the contract "([^"]+)")?(?: for the portal (.+))?$/`
this way I'm able to handle the three parameters once, but that would be even better to remove the quotes around the contract

**Comment by charlierudolph** [comment]
You can't currently remove the quotes around the contract as otherwise the contract could match as `contract1 for the portal portal1`. If you switch the capture group to `([\w-]+)` then you should be able to remove the quotes. For any capture that can have a space, I highly suggest wrapping it in quotes.

**Comment by charlierudolph** [comment]
Closing as appears resolves. Please reopen if needed
