### ISSUE TITLE
Tag Expressions link broken in Hook docs

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber-js#1097]
### Steps to reproduce

1. Visit https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md
2. Scroll to "Tagged Hooks" header
3. Follow the "tag expressions" documentation link
4. You should see a 404 page.

**Comment by KyleFairns** [comment]
I was look for a possible way of making a conditional hook based on what was in our configuration file, wherein if we configured the browser to restart after every scenario, that instead of closing the cookies message in the BeforeAll hook, we do it in the Before hook.

I was seeing if there was a possible way to do it with tag expressions by tagging a suite with "restart" (I am unsure whether that is even possible), and using tag expressions to achieve this as it seems like a very cucumber way of doing it.

Before locating an answer to it I found this issue.

Is there any chance that I could get some guidance on this alongside reporting the bug?

**Comment by KyleFairns** [comment]
I think I've got a plan for it. So, using the profiles, if I add a section in there where I set "restartAfterEveryScenario" is true, then inside an After hook, I can close, and in the Before hook I can start a new browser using a conditional statement within the hooks rather than making the hooks themselves conditional on a tag that the suite would have.

In effect:

I was thinking that suite tags would be a nice addition to cucumber that might have been implemented (tags that could be defined in the cucumber config file), and would be utilised like this in the hooks:
```
Before({tags: @restartAfterEveryScenario}, async ()=>{ 
    return await browser.start(); 
});

After({tags: @restartAfterEveryScenario}, async ()=>{ 
    return await browser.quit(); 
});
```

But I should be able to do generic hooks:
```
Before(async ()=>{
   if(profile.restartAfterEveryScenario){
       return await browser.start();
   }
});

After(async ()=>{
   if(profile.restartAfterEveryScenario){
       return await browser.quit();
   }
});
``` 
To achieve the same thing. It'll just be ran after every scenario when it doesn't necessarily need to be.

**Comment by charlierudolph** [comment]
I don't know about the idea of a suite tag as it appears you want it to be as if the tag is added to everything. This doesn't make sense to me as tags are used for filtering. Tags also can't be used on beforeAll / afterAll currently. I think you accomplish this today with the following:
 
```
BeforeAll(async ()=>{
  // always start the browser
});

Before(async () => {
  // if the browser isn't running, start it
});

After(async function(){
  // if this.restartAfterEveryScenario (property the world), then quit the browser
});

AfterAll(async ()=>{
   // if the browser is running, quit it
});
```
where the property on the world can be set with the [CLI](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#world-parameters)
