### ISSUE TITLE
Event Protocol Current Docs Link is Broken in Docs

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber-js#1098]
### Steps to Reproduce:
1. Visit https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md
2. Scroll down to the "Formats" Header
3. Follow "current docs" link for the event formatter
4. You should be on a 404 page

**Comment by KyleFairns** [comment]
Was just looking for the docs for the event formatter, after finding out that the JSON formatter is being deprecated (which we currently use with our own custom suite reporter and dashboard for the business).

**Comment by mlvandijk** [comment]
FYI: It links to https://docs.cucumber.io/event-protocol/ and there is currently no page about event protocol in the [docs](https://github.com/cucumber/docs.cucumber.io)

**Comment by davidjgoss** [comment]
7.0.0 is now released, see [the changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) for migration instructions. Thanks!

(The docs now point to the messages formatter and related content.)
