### ISSUE TITLE
Calling steps from step definitions

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#11]
Allow calling steps from step definitions.

https://github.com/cucumber/cucumber/wiki/Calling-Steps-from-Step-Definitions

**Comment by hackhat** [comment]
Hy! I've created a lib which does exactly what you are asking (call a step from another step), take a look here: https://github.com/hackhat/cucumber-pro 
Feedback is welcome!

**Comment by jlin412** [comment]
@hackhat It looks really cool.  I usually like sync portion of step definition.  Is cucumber-pro only a plugin for cucumber.js?

**Comment by hackhat** [comment]
@jlin412 I don't really know how to call, but is like a helper for cucumber. Thanks for feedback

**Comment by jlin412** [comment]
@hackhat In order to create sync step, I will need to use syntax: this.addStep(...)?  Will I need to use selenium-sync as well instead of protractor.js/webdriver.js?

**Comment by hackhat** [comment]
@jlin412 you can only use the sync plug-in, look at the docs how to do it. I'm on mobile so I can't give you the exact steps. If you can wait I will explain better around 23h30 Portugal hour.

**Comment by aslakhellesoy** [comment]
@hackhat please change the name of your project to something else. See hackhat/cucumber-pro#1

**Comment by hackhat** [comment]
@aslakhellesoy Changed the name to https://github.com/hackhat/cucumberry

**Comment by yunjia** [comment]
@aslakhellesoy Then how to chain the step calls? Like following?
```javascript
function x_is_something(x, cb) {
  console.log('x', x);
  this.x = x;
  cb();
}
function y_is_something(y, cb) {
  console.log('y', y);
  this.y = y;
  cb();
}

Given(/super z/, function(cb) {
  x_is_something(97, cb);
  y_is_something(8, cb);
});
```
That doesn't work very well since `x_is_something` would have called the callback before `y_is_something ` has chance to finish its work.

And also, if step stores variable in the world context, it will end up each time call the function, we need to bind it like:
```javascript
Given(/super z/, function(cb) {
  x_is_something.bind(this)(97, cb);
  y_is_something.bind(this)(8, cb);
});
```

Anyone had solutions to these issues?

**Comment by hackhat** [comment]
You need to use async and use the parallel function. In this way you call
the main cb only after both of the sub calls have finished.
About binding you can either use this with bind or use a closure variable.

**Comment by inf3rno** [comment]
+1, this should be part of the lib.

**Comment by jbpros** [comment]
@yunjia this is basic callback theory:

```javascript
Given(/super z/, function(cb) {
  x_is_something(97, function () {
    y_is_something(8, cb);
  });
});
```

As for the binding issue, you should define those functions as methods on your [World](https://github.com/cucumber/cucumber-js#world):

 ```javascript
function World(callback) {
    this.x_is_something = function (x, callback) {
      this.x = ...
    };

    this.y_is_something = function (y, callback) {
      this.y = ...
    };

    callback(); // tell Cucumber we're finished and to use 'this' as the world instance
  };
}
module.exports.World = World;
```

Then in your step definitions:

```javascript
Given(/super z/, function(cb) {
  var self = this;
  self.x_is_something(97, function () {
    self.y_is_something(8, cb);
  });
});
```

Also, please note that synchronous step definitions are supported by Cucumber.js 0.5+:

```javascript
Given(/super z/, function() {
  this.x_is_something(97);
  this.y_is_something(8);
});
```

**Comment by jbpros** [comment]
@inf3rno step definitions are a thin translation layer between plain english and JS code. By allowing calling steps from steps, we make that layer fatter. Steps become coupled between each other, rendering them extremely difficult to maintain.

It also encourages people to use Gherkin as a scripting language, which it is not at all.

**Comment by aslakhellesoy** [comment]
@inf3rno if you want to reuse code in stepdefs, move the body of the stepdef to a regular javascript function and reuse that.

**Comment by inf3rno** [comment]
@jbpros 
> It also encourages people to use Gherkin as a scripting language, which it is not at all.
Can you elaborate pls. I don't understand what is the connection, since step definitions are not in gherkin, only the text pattern what is similar.

**Comment by jbpros** [comment]
@inf3rno if you can call steps from steps, you're jumping back again into "Gherkinland": the step names need to be parsed, matched against step definitions which can be executed. You're basically writing gherkin scripts within gherkin (they're hidden within JS step definitions, but that's a detail that makes it even worse from a maintenance POV).

**Comment by AutoSponge** [comment]
@aslakhellesoy @jbpros The idea is that steps should be an algebraic, composable type, which it's not.

**Comment by JasonSmiley208** [comment]
@jbpros, I am going to use your solution since I am used to programming in Java and not worrying about promises :)

**Comment by stevecooperorg** [comment]
Did anyone ever come up with an extension to cucumber for defining steps in terms of other steps? Something like 

    Understand I log in to {site} as {user}, {pass}
        I visit {site}
        I log in as {user}, {pass}

Am pondering whether this is a useful extension to better describe long user journeys through the system and would prefer to work with any prior art.
