### ISSUE TITLE
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?

### ISSUE THREAD

**Issue by HMaheshwari** [cucumber/cucumber-js#1102]
While running scenario outline in cucumber, gettting exception and scenarios failed.

Note : As First scenario works fine the rest of scenarios were failed.

in cucumber After hooks i have called "quit()" method while launching browser again getting below exception

Selenium webdriver version : 3.12
Chrome version : 66
Cucumber version : 1.2.5 (from info.cukes sources)
 
++++++++++++++++++++++++++++++++++++++++++++++++++++
Exception:

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'XYS', ip: 'XYZ', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
  at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
  at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
  at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:273)
  at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:856)
  at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringNavigation.to(EventFiringWebDriver.java:509)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by charlierudolph** [comment]
That doesn't look like an issue with cucumber. Based on the error message, that appears to be in proper use of the web driver

**Comment by HMaheshwari** [comment]
Hi @charlierudolph  I think its realated to cucumber-java not to cucumber-js but looks like its issue to me as it was already reported previously but it is closed without resolution.
please refer link https://github.com/cucumber/cucumber-jvm/issues/1376 where i've shared my code as well. let me know if I'm missing anything. 
thanks

**Comment by KyleFairns** [comment]
Is there another before hook or after hook trying to interact with the browser after you close it or before the new one is open?

**Comment by aslakhellesoy** [comment]
Can we close this?
