### ISSUE TITLE
How know which steps are not running

### ISSUE THREAD

**Issue by djom20** [cucumber/cucumber-js#1107]
Hi team,

Currently I using protractor with cucumber and gherkin but I have 12350 scenarios and I would like to know if there is any way to know which steps are not running now? because it's difficult to maintain all of those scenarios at the same time.

Thanks

**Comment by charlierudolph** [comment]
Does the `usage` formatter give you what you want?  https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats You can use that with dry-run to get a quick snapshot of how many times each step is used

**Comment by djom20** [comment]
Yes the formatter gave me the correct output and I'm using dry-run option but I can't get the steps that are not running or are in not use.

**Comment by KyleFairns** [comment]
@djom20 Could you not use the output from the usage formatter and by process of elimination find out whether they are being used?

It would probably require a script when you're at the sheer number of scenarios you currently have, but if you were to crawl through your step definitions, pulling out every single one (possibly using regex)

[Example Regex:](https://regex101.com/r/TXnMxY/1)
`^(?:Given|When|Then)\s*\((.*),`

And then do a comparison to the usage one in a loop, to dish out the unused ones?

Something like this:

```js
  const allSteps = getAllSteps();
  let unusedSteps = [];

  allSteps.forEach((step)=>{ 
      let used = usedSteps[step.matcher] | "Not Used"
      if(used === "Not Used"){
           unusedSteps.push(step);
      }
  });
```

**Comment by charlierudolph** [comment]
The usage formatter reports the unused steps. See this [feature](https://github.com/cucumber/cucumber-js/blob/v4.2.1/features/usage_formatter.feature). If you need to parse the usage data more, I would suggest using the [usage-json formatter](https://github.com/cucumber/cucumber-js/blob/v4.2.1/features/usage_json_formatter.feature).
