### ISSUE TITLE
[Request] Update cucumber-js version in docs on release

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/cucumber-js#1108]
During review of PR on the [Cucumber docs](https://github.com/cucumber/docs.cucumber.io), I noticed that the cucumber-js version had changed from 4.0.0 to 4.2.1.
I have updated the version in the Cucumber docs, in the [versions.yaml](https://github.com/cucumber/docs.cucumber.io/blob/master/data/versions.yaml).

Request: Would it be possible to update the cucumber-js version in the Cucumber docs `versions.yaml` upon the release of a new version of cucumber-js? (And maybe add this to your release docs, if you have those?)

**Comment by charlierudolph** [comment]
Sure. We have a release process documented in our `CONTRIBUTING.md`. I'll add a note to update that as well

**Comment by charlierudolph** [comment]
Added a couple bullets to the bottom of the list

**Comment by mlvandijk** [comment]
Thnx @charlierudolph!
