### ISSUE TITLE
Installing Cucumber Error

### ISSUE THREAD

**Issue by BenRbtz** [cucumber/cucumber-js#1110]
Trying to install cucumber with node v8.11.3 and getting the following error: 

```
$ npm install cucumber

> cucumber-expressions@5.0.18 postinstall /usr/local/st_repos/PHP-DataWarehouse-Crons/acceptance/node_modules/cucumber-expressions
> node scripts/postinstall.js


/usr/local/st_repos/PHP-DataWarehouse-Crons/acceptance/node_modules/cucumber-expressions/scripts/postinstall.js:5
fs.access(path.join(__dirname, '..', 'dist'), function(err) {
   ^
TypeError: Object #<Object> has no method 'access'
    at Object.<anonymous> (/usr/local/st_repos/PHP-DataWarehouse-Crons/acceptance/node_modules/cucumber-expressions/scripts/postinstall.js:5:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

```

Any ideas what is causing this? Tried switching versions to 10.5 and 10.1 but to no avail.

**Comment by aslakhellesoy** [comment]
Are you getting the same error on 10.5 and 10.1?
What OS are you on?
How did you install Node.js?

The error message is essentially saying that the `fs` module doesn't have an `access` method, which it has had since [0.11.15](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_access_path_mode_callback).

**Comment by BenRbtz** [comment]
Yes, the same error for all three.
Amazon Linux EC2.
Tried to install using the ec2 provided one and tried with nvm.

I thought so, that's what I find confusing. To prove that it did exist I did this:

```
$ node
> fs.access
[Function]
```

**Comment by aslakhellesoy** [comment]
Could it be that you're actually running on an older version of `node` that doesn't have `fs.access`?

**Comment by BenRbtz** [comment]
Possibly, how would I check that? In the same node session did this:
```
> process.version
'v10.1.0'
```
which is the expected version

**Comment by aslakhellesoy** [comment]
Hm - that's really odd. I don't know how to reproduce this and I don't understand why it happens. Sounds like our best option is to prevent that script from running during install (and only make it run when we package a release).

**Comment by BenRbtz** [comment]
I feel like I'm doing something wrong on my end. What's the best way to clear and start from scratch?

**Comment by aslakhellesoy** [comment]
Can you install it locally (outside EC2)? It sounds like your node/npm environment is a bit hosed.

**Comment by aslakhellesoy** [comment]
Did you remove the command you ran as well as some of its output? Looks incomplete to me.

**Comment by BenRbtz** [comment]
Sorry, I reduced the amount of output earlier. 

Here is the full stack trace after a bit more attempts to fix it:

```
npm install cucumber

> cucumber-expressions@5.0.18 postinstall /root/node_modules/cucumber-expressions
> node scripts/postinstall.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/node_modules/cucumber-expressions/scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cucumber-expressions@5.0.18 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cucumber-expressions@5.0.18 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-27T16_19_07_473Z-debug.log
```

**Comment by aslakhellesoy** [comment]
Do you have a package.json?

**Comment by BenRbtz** [comment]
Not currently. That wouldn't matter, would it?

**Comment by aslakhellesoy** [comment]
It might. Try adding it to `package.json` and run `npm install`. Or `npm install cucumber --save-dev`

**Comment by BenRbtz** [comment]
No sadly, didn't make a difference.

**Comment by BenRbtz** [comment]
Done a few things:
- Installed node via https://nodejs.org/en/download/package-manager/
- Wiped Repo with node_modules
- Created a package.json and installed all packages from scratch

Seems to have fixed the problem. 

Thanks, @aslakhellesoy  for taking the time to look into this problem.

**Comment by aslakhellesoy** [comment]
I'm glad you found out @BenRbtz and thanks for posting the solution here in case other people have the same problem.
