### ISSUE TITLE
Cucumber-js integration with TestCafe

### ISSUE THREAD

**Issue by vvedachalam** [cucumber/cucumber-js#1116]
I am using Cucumber-js with the E2E testing tool, TestCafe. The error logs are not really useful and when i raised this with TestCafe team (https://github.com/DevExpress/testcafe/issues/2551) , they mentioned its due to poor integrity between TestCafe and Cucumber-js. Can this issue be addressed by Cucumber-js? 
I have forked a TestCafe-Cucumber project in Github for your reference.
https://github.com/vvedachalam/testcafe-cucumber

**Comment by charlierudolph** [comment]
Looking at the linked issue I don't see anything cucumber could be doing differently to better support TestCafe

**Comment by vvedachalam** [comment]
@charlierudolph Thanks for the response. So do you mean to say that its TestCafe who has to address the issue or do we need to handle this in a much better way in our hooks?

**Comment by loganvolkers** [comment]
That's right. There are [open issues on the TestCafe tracker](https://github.com/DevExpress/testcafe/issues/2835) for this, and their [team is aware and planning to implement better support.](https://github.com/DevExpress/testcafe/issues/1373#issuecomment-502581364)

In the meantime, there are some other projects that can help make this better: https://github.com/bhreinb/SYSTAC
