### ISSUE TITLE
Add support for `And` + `But` step definitions

### ISSUE THREAD

**Issue by DennisJaamann** [cucumber/cucumber-js#1118]
The official spec is supporting the `And` + `But` step definitions.
@see https://docs.cucumber.io/gherkin/reference/

However, cucumber.js is currently not supporting this.

**Comment by aslakhellesoy** [comment]
That’s intentional. `And` and `But` is just syntactic sugar in Gherkin for repeating the keyword on the previous line.

Doesn’t make sense to add to the API because step definitions are independent and don’t “follow” others.
