### ISSUE TITLE
Ability To Wrap Step Definitions & Hooks In A Class In CucumberJs

### ISSUE THREAD

**Issue by bhreinb** [cucumber/cucumber-js#1120]
Hi There,

I have been using cucumberjs version 1.3.3 up a few months ago. I have now upgraded to use v4.2.1 as the test automation project I'm currently working on has a dependency on v4.2.1. Previously when using 1.3.3 I was able to write my hooks file like this within a class

```
class CucumberJsAcaHooks {
  constructor(cucumberLifeCycle) {
    cucumberLifeCycle.Before({ tags: ['@auto_regression, @auto_smoke, @auto_new'] }, this.beforeTestScenarioExecution.bind(this));
    cucumberLifeCycle.After({ tags: ['@auto_regression, @auto_smoke, @auto_new'] }, this.afterTestScenarioExecution.bind(this));
    cucumberLifeCycle.After({ tags: ['@dev_config_wizard_reset_all'], timeout: 30 * 1000 }, this.devConfigWizardResetAll.bind(this));
  }

  beforeTestScenarioExecution(scenario) {
    console.log('Before test scenario for tags [@auto_regression, @auto_smoke, @auto_new]');
  }

  afterTestScenarioExecution(scenario) {
    console.log('After test scenario for tags [@auto_regression, @auto_smoke, @auto_new]');
  }

  devConfigWizardResetAll(scenario) {
    console.log('devConfigWizardResetAll for tags [@dev_config_wizard_reset_all]');
  }
}

module.exports = function () {
  this.cucumberJsAcaHooks = new CucumberJsAcaHooks(this);
};
```

Moving to version 4.2.1 I can't place this within a class context (https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md) or at least I don't know how to do this (as it doesn't seem to be documented).  If you look at different implementations of cucumber (something I'm doing frequently is context switching between different editions of cucumber) they generally support this (for example specflow & cucumber-jvm)

> https://www.automatetheplanet.com/extend-test-execution-workflow-specflow-hooks/
> https://specflow.org/documentation/scoped-bindings/
> https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-calculator/src/test/java/cucumber/examples/java/calculator/RpnCalculatorStepdefs.java
> 

As JavaScript does support classes perhaps we should have the ability to wrap hooks & step definitions within classes just like the other implementations. Thoughts? Thanks in advance re the above.

**Comment by bhreinb** [comment]
Hi there,

Can anybody help with this please or suggest an alternative. Thanks in advance.

**Comment by charlierudolph** [comment]
Hmm, I could see classes being nice when ES7 decorators become standard. I like the idea of injecting the world and think that could be left to a parent class so we could have something like:

```javascript
import { CucumberSteps, Before, Given } from 'cucumber'

export default class MySteps extends CucumberSteps {

  @Before
  initialize() {
    // this.world is the shared world instance between all steps
  }
  
  @Given("a user named (.*)")
  addUser(name) { 
    // ...
  }

}
```

I guess we could start with something like

```javascript
import { CucumberSteps } from 'cucumber/class'

export default class MySteps extends CucumberSteps {

  constructor({Before, Given}) {
    super() 
    Before({tags: '@a or @b'}, this.initialize.bind(this));
    Given("a user named (.*)", this.addUser);
  }

  initialize() {
    // this.world is the shared world instance between all steps
  }
  
  addUser = (name) => { 
    // other approach to binding
  }

}
```

**Comment by bhreinb** [comment]
I like the suggestion. I'm assuming CucumberSteps would be a new API right!?

**Comment by charlierudolph** [comment]
Yes it would be. I'm hesitant to implement it while we also have the old interface though as it gives multiple ways of defining steps. What is the benefit of classes other than being consistent with other implementations?

Given that the world is shared between them, the class is just a way to break up steps. But I don't see how that is better than just breaking them up by class.

Why do other implementations use classes versus the more global helpers of ruby and javascript? @aslakhellesoy can you answer that for JVM? And possibly tag others that could answer for other implementations

**Comment by bhreinb** [comment]
In terms of benefits, if it was to be implemented as you suggest

1. consistency with other implementations as you mention
2. ability to write step definitions with arrow syntax (something that was requested before by other users)
3. Eslint Airbnb compatible (namely I use async keyword along with the step definition implementation...because of current designs I have to use "async function" to get the this instance within steps...it would be preferable just to use async => as having "async function" with step definitions requires the function to be named...which is a bit of an annoyance...but that can be suppressed also)

**Comment by bhreinb** [comment]
Hello @aslakhellesoy & @charlierudolph 

Thoughts on this feature request? It would be great to have the ability to transpose cucumberjs steps & hooks in line with ES6 standards. Thanks in advance.

**Comment by aslakhellesoy** [comment]
I think the new `CucumberSteps` suggestion above sounds nice. Would you be interested in taking a stab at a PR @bhreinb?

**Comment by bhreinb** [comment]
I'm happy to help out albeit I'm very unfamiliar with the internals of cucumberjs so I probably would need a good bit of guidance :(

**Comment by Srutherford2407** [comment]
Is there not currently a way to "wrap" the steps? I am trying to use cucumber-js with another ui automation tool while creating clean code. I am trying to create the client running in another file so I don't have to declare with every given.

my .js file:
```
const {appium} = require('../support/init');
const {Given, Then, setDefinitionFunctionWrapper} = require('cucumber');
const {After, BeforeAll} = require('cucumber');
// I would like to declare the client here so it can be used through all steps

Given('I should have welcome screen', async () => {
  let client = await appium();
   await client.findElement('accessibility id', 'welcomeText');
   await client.findElement('accessibility id', 'helloButton');
   await client.findElement('accessibility id', 'helloButton');
  });
```
My init.js:
```
const driver = require('webdriverio');

const opts = {
  port: 4723,
  capabilities: {
      app: "/Users/steven.rutherford/Library/Developer/Xcode/DerivedData/NativeExample-fpzpyvvxfpyejqfuwviazyhxnkgy/Build/Products/Debug-iphonesimulator/NativeExample.app",
      platformName: "iOS",
      platformVersion: "12.2",
      deviceName: "iPhone Xʀ"
  }
};
async function appium() {
    return await driver.remote(opts);
};
module.exports = {appium};
```

**Comment by serge-shaldanov** [comment]
> Hmm, I could see classes being nice when ES7 decorators become standard. I like the idea of injecting the world and think that could be left to a parent class so we could have something like:
> 
> ```js
> import { CucumberSteps, Before, Given } from 'cucumber'
> 
> export default class MySteps extends CucumberSteps {
> 
>   @Before
>   initialize() {
>     // this.world is the shared world instance between all steps
>   }
>   
>   @Given("a user named (.*)")
>   addUser(name) { 
>     // ...
>   }
> 
> }
> ```
> 
> I guess we could start with something like
> 
> ```js
> import { CucumberSteps } from 'cucumber/class'
> 
> export default class MySteps extends CucumberSteps {
> 
>   constructor({Before, Given}) {
>     super() 
>     Before({tags: '@a or @b'}, this.initialize.bind(this));
>     Given("a user named (.*)", this.addUser);
>   }
> 
>   initialize() {
>     // this.world is the shared world instance between all steps
>   }
>   
>   addUser = (name) => { 
>     // other approach to binding
>   }
> 
> }
> ```

I believe it will be better to inject World instance via the constructor — to enable intellisense auto-completion for it.

**Comment by noopurporwal** [comment]
> Is there not currently a way to "wrap" the steps? I am trying to use cucumber-js with another ui automation tool while creating clean code. I am trying to create the client running in another file so I don't have to declare with every given.
> 
> my .js file:
> 
> ```
> const {appium} = require('../support/init');
> const {Given, Then, setDefinitionFunctionWrapper} = require('cucumber');
> const {After, BeforeAll} = require('cucumber');
> // I would like to declare the client here so it can be used through all steps
> 
> Given('I should have welcome screen', async () => {
>   let client = await appium();
>    await client.findElement('accessibility id', 'welcomeText');
>    await client.findElement('accessibility id', 'helloButton');
>    await client.findElement('accessibility id', 'helloButton');
>   });
> ```
> 
> My init.js:
> 
> ```
> const driver = require('webdriverio');
> 
> const opts = {
>   port: 4723,
>   capabilities: {
>       app: "/Users/steven.rutherford/Library/Developer/Xcode/DerivedData/NativeExample-fpzpyvvxfpyejqfuwviazyhxnkgy/Build/Products/Debug-iphonesimulator/NativeExample.app",
>       platformName: "iOS",
>       platformVersion: "12.2",
>       deviceName: "iPhone Xʀ"
>   }
> };
> async function appium() {
>     return await driver.remote(opts);
> };
> module.exports = {appium};
> ```

Were you able to find a solution to this? I am having the same issue and if i declare it outside any of the steps, it is not able to consider itself as a driver capability

**Comment by davidjgoss** [comment]
@noopurporwal I'd recommend you implement a custom [world](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/world.md) and provision your driver from within there so it's available to the steps.

Something like:

```js
const driver = require('webdriverio');
const { setWorldConstructor } = require('cucumber')

const opts = {
  port: 4723,
  capabilities: {
      app: "/Users/steven.rutherford/Library/Developer/Xcode/DerivedData/NativeExample-fpzpyvvxfpyejqfuwviazyhxnkgy/Build/Products/Debug-iphonesimulator/NativeExample.app",
      platformName: "iOS",
      platformVersion: "12.2",
      deviceName: "iPhone Xʀ"
  }
};

class MyWorld {
    constructor({ attach, parameters }) {
        this.attach = attach;
        this.parameters = parameters;
    }

    async init() {
        this.client = await driver.remote(opts);
    }
}

setWorldConstructor(MyWorld);
```

and

```js
const { Before, Given } = require('cucumber')

Before(async function() {
    await this.init();
});

Given('I should have welcome screen', async function () => {
   await this.client.findElement('accessibility id', 'welcomeText');
   await this.client.findElement('accessibility id', 'helloButton');
   await this.client.findElement('accessibility id', 'helloButton');
  });
```

Because you get a fresh instance of the World for each scenario, it also keeps any state of your driver from bleeding across scenarios (which should always be totally independent).

**Comment by noopurporwal** [comment]
@davidjgoss Thanks for your response, I will try this way as well. 
But I tried another way where I am not declaring the setter function as async and could initiate the driver once and for all to be used across all scenarios. Is this approach correct? Here is the sample

```
const webDriver = require('selenium-webdriver');
 
var chrome = require('selenium-webdriver/chrome');
const chromedriver = require('chromedriver');
const TIMEOUT = 300000000

function driverSettings() {

chrome.setDefaultService( new chrome.ServiceBuilder( 
chromedriver.path ).build() )

const chromeCapabilities = webDriver.Capabilities.chrome()

const chromeOptions = { 'args': [ 'user-data-dir=/Users/user/selenium/bp/' ] }
chromeCapabilities.set( 'chromeOptions', chromeOptions )

const driver = new webDriver.Builder()
.withCapabilities( chromeCapabilities )
.build()

driver.manage().setTimeouts( { implicit: TIMEOUT, pageLoad: 
TIMEOUT, script: TIMEOUT } )
    
return driver;
};

module.exports={driverSettings};`
```

and 

```
const { Given, When, Then, AfterAll, setDefaultTimeout,setTimeOut, After } = require('cucumber');
const webDriver = require('selenium-webdriver');
const {driverSettings} = require('../driverSettings');
const assert = require('assert');

setDefaultTimeout(60 * 1000);

 let By= webDriver.By;
 const until=webDriver.until;
 let driver= driverSettings();
 

Given('We are at home Page', async function () {
    await driver.get('http://blah.com/index.php');
});
```

**Comment by davidjgoss** [comment]
I'm not super familiar with webdriverjs - but I have seen quite a few issues raised here over time where state of the driver (cookies, appcache etc) was leaking between scenarios - which is why I suggested having it 1:1 with the World. Your approach may be fine but I think you need to understand what the side effects might be of sharing the driver across scenarios (especially if running in parallel).

**Comment by davidjgoss** [comment]
Closing this now, because:

- There are no current plans to address this from the core team
- Things have generally moved on towards a more functional style, which is enabled by https://github.com/jbpros/cucumber-fp
