### ISSUE TITLE
Avoid dependencies with licensing problems

### ISSUE THREAD

**Issue by honzajavorek** [cucumber/cucumber-js#1124]
Our company audit discovered some legal issues in Cucumber, which prevent us to use it:

- babel-runtime@6.26.0 (MIT) - missing full license text (waiting for https://github.com/babel/babel/pull/8524 to be released)
- cli-table@0.3.1 (UNKNOWN) - missing full license text (bdee948)
- colors@1.0.3 (MIT) - missing full license text (bdee948)
- duration@0.2.0 (UNKNOWN) - missing full license text (waiting for https://github.com/medikoo/duration/issues/5)
- regenerator-runtime@0.11.1 (MIT) - missing full license text (waiting for https://github.com/facebook/regenerator/issues/354)
- string-argv@0.0.2 (MIT) - missing full license text (64bc6b8)

I opened https://github.com/cucumber/cucumber-js/pull/1123 to fix some of them.

**Comment by charlierudolph** [comment]
Closing as everything appears to be merged. I'll make a release tonight
