### ISSUE TITLE
duration format

### ISSUE THREAD

**Issue by lh104** [cucumber/cucumber-js#1130]
https://github.com/cucumber/cucumber-js/blob/4b39f87d8dd5d07e74a4c9c70c1996ed86f8d6f8/src/formatter/json_formatter.js#L150

can we please have a configuration to have duration in milliseconds ?

Thank you.

**Comment by charlierudolph** [comment]
It is nanoseconds to be consistent with other implementations. Sorry I don't think a configuration option makes sense for that.

**Comment by Izhaki** [comment]
@charlierudolph Not opening a new issue as could be a slip of tongue.

But in `time.js` we get the time like this: `Date().getTime()`. This returns *milliseconds*.

milliseconds * 1000000 = picoseconds.

I've got a report where the execution time for a step is `4385000000`. If this is indeed in nanoseconds, that that's 4385 second, which is 73 minutes.

This `4385000000` figure is obviously pico seconds, yielding 4385 milliseconds.

**Comment by charlierudolph** [comment]
Just looked this up and:

Millisecond is 1/10^3
Microsecond is 1/10^6
Nanosecond is 1/10^9
Picosecond is 1/10^12

Thus millisecond * 10^6 is nanoseconds and 4385000000 in nanoseconds is 4.385 seconds

**Comment by Izhaki** [comment]
@charlierudolph That is only correct if you live on earth.

If you, like me, lives in La-La-Land, than we don't use microseconds here - we go straight from milliseconds to nanoseconds!

I have NO idea how this happened. But at least we're double-sure it's nanoseconds alright.
