### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by znevrly** [cucumber/cucumber-js#1140]
Hi,
I am running test with command
gherkin-lint && cucumber-js --format progress --require lib

I works OK in 4.2.1 but in 5.0.1 I am getting
build	02-Oct-2018 21:29:57	$ gherkin-lint && cucumber-js --format progress --require lib --profile=test-de 
error	02-Oct-2018 21:29:58	TypeError: Path must be a string. Received undefined 
error	02-Oct-2018 21:29:58	at assertPath (path.js:28:11) 
error	02-Oct-2018 21:29:58	at Object.relative (path.js:1251:5) 
error	02-Oct-2018 21:29:58	at getDefinitionLineAndUri (/home/app/node_modules/bdd-rest-core/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:150:28) 
error	02-Oct-2018 21:29:58	at buildTestRunHookDefinition (/home/app/node_modules/bdd-rest-core/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:88:32) 
error	02-Oct-2018 21:29:58	at /home/app/node_modules/bdd-rest-core/node_modules/cucumber/lib/support_code_library_builder/index.js:100:76 
error	02-Oct-2018 21:29:58	at Object.<anonymous> (/home/app/node_modules/bdd-rest-core/hook-general.js:6:1) 
error	02-Oct-2018 21:29:58	at Module._compile (module.js:652:30) 
error	02-Oct-2018 21:29:58	at Object.Module._extensions..js (module.js:663:10) 
error	02-Oct-2018 21:29:58	at Module.load (module.js:565:32) 
error	02-Oct-2018 21:29:58	at tryModuleLoad (module.js:505:12) 
error	02-Oct-2018 21:29:58	at Function.Module._load (module.js:497:3) 
error	02-Oct-2018 21:29:58	at Module.require (module.js:596:17) 
error	02-Oct-2018 21:29:58	at require (internal/module.js:11:18) 
error	02-Oct-2018 21:29:58	at Object.<anonymous> (/home/app/lib/hooks/setup.js:1:63) 
error	02-Oct-2018 21:29:58	at Module._compile (module.js:652:30) 
error	02-Oct-2018 21:29:58	at Object.Module._extensions..js (module.js:663:10) 
error	02-Oct-2018 21:29:58	error Command failed with exit code 1.

Is strange that only in some BDD project, on another it works OK.

**Comment by znevrly** [comment]
I will try to debug it when I will be free to play it with.

**Comment by TheLudd** [comment]
I also had this problem. Turned out I had duplicate versions of cucumber in my `node_modules` folder.
run `npm ls cucumber` or `yarn list cucumber` and make sure that there is only one version there. 
If there are several, see if you can dedupe and then check if the error remains.

**Comment by znevrly** [comment]
Yes, confirmed. Issue can be closed. Thanks!

**Comment by TheLudd** [comment]
@znevrly If you created this you should be able to close it yourself, right?
