### ISSUE TITLE
support FORCE_COLOR environment variable

### ISSUE THREAD

**Issue by travi** [cucumber/cucumber-js#1141]
with the recent change to [disable colors automatically when not supported](https://github.com/cucumber/cucumber-js/commit/0415ddef3af75781882c1e725d6b7d43c794e962), i've now lost colors in some legitimate situations where the tty check is misinformed, such as running through [npm-run-all](https://www.npmjs.com/package/npm-run-all). 

the [solution suggested by `npm-run-all`](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#known-limitations) has becoming a shared "standard" across a few tools at least. would you consider supporting `FORCE_COLOR`?

**Comment by travi** [comment]
the benefit of the environment variable is that it can be set differently in various environments. the cli option would be set consistently across environments, especially since i run the cucumber command as an npm script.

i set the `FORCE_COLOR` variable on my local machine that i know supports color as well as on travis that supports color but fails the tty check. however, i do prefer the ANSI characters not be output other contexts where color is not supported, which would be places where i have not set the environment variable.

does the difference make sense?

**Comment by travi** [comment]
just to provide a bit more detail, i've noticed that color is also lost for the same reason when piping through [bunyan](https://github.com/trentm/node-bunyan). i run the tests through npm scripts, so adding the cli option conditionally based on where i'm running things would be pretty inconvenient.

**Comment by charlierudolph** [comment]
Could you also use profiles so your default or ci profile has the color option set to true. I want to avoid environment variables, so the cli only has a single interface.

**Comment by travi** [comment]
the problem with profiles is the same as with npm scripts. anything that is committed to version control is shared with the entire team and therefore assumes the entire team is using an environment that is compatible with those specific settings. this isn't always the case and is the whole point of environment variables. different team members run in different environmental contexts and run into problems if the config is locked down.

i can certainly understand the desire to keep the interface complexity down, but comletely avoiding environment variables is a very limiting approach to take with a cli tool. 

i'm sure youre familiar with [chalk](https://www.npmjs.com/package/chalk). would leveraging a library like that allow you to keep the interface that you maintain simpler without avoiding variations in configuration between environmental contexts?

**Comment by travi** [comment]
> because its easier when running through npm scripts

yes and no. i'd clarify that the goal is to make it simpler to run cucumber tests in general. we attempt to simplify the command that has to be run repetitively for every iteration because we will forget to include flags if they are not encapsulated programmatically.

there are three ways of encapsulating those details that come to mind:
* npm scripts (versioned, so they are consistent across team members) some scripts can call other scripts, making it difficult to override lower-level config from the higher levels
* profiles (also versioned, so they are consistent across team members) i'm not as familiar with these since npm scripts have satisfied my needs, but i think they would have the same complications from what i understand
* environment variables (not shared with the team, but still encapsulated across runs for any reason within that environmental context) in addition to enabling config per environment, the config is applied across the entire environment, so lower-level scripts can access the overrides without the gymnastics of passing down multiple levels

> For running some directly you can pass arguments you can pass arguments: https://docs.npmjs.com/cli/run-script

i'm aware of the ability to pass arguments, and we do so in npm scripts that call other npm scripts. however, to use these for details that vary across environments would require each of us to retype them each time we run the command, which results in forgetting to do so and quickly leads to frustration. this is a clear example of breaking the encapsulation of details mentioned above.

> Sorry that's a cost/benefit of using a tool that gives you higher level workflows as it assumes you don't need to parameterize your lower level workflows

that doesnt have to be the case. environment variables are [explicitly recommended](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#known-limitations) as the way to parameterize the lower level workflows, but the lower level tools having support is a big piece of that puzzle.

> Can you change the default so that colors are enabled by default and users have to turn it off if they don't want them?

worst case, that's an option. it would basically get us back to the state before they were recently disabled based on tty, but it still makes it painful to debug in those environments. it also encounters the same problems that make it hard to override when one script calls another script because passing the config down gets a lot harder.

> TTY is misinformed

agreed that this is the root of the issue, but is one that can't really be resolved. this is usually a result of a tool using a subprocess, which removes the ability to detect the actual outer environment conditions. this is the reason these tools suggest using environment variables for things that need to change across environments, or hard code the options that don't need to change based on context.

> For some history on environment variables, we implemented the CLI option world-parameters exclusively to allow users to avoid using environment variables as setting them differs on platform and is cumbersome on windows.

understood and i respect what youve done to handle these situations. color seems different to me though, because it is so environment dependent. most of the other variables in question are consistent across environments.

### summary

i hope my additional detail doesnt come across as confrontational. i understand where youre coming from, but i do think color support is a slightly different beast because it is so environment dependent. hopefully some of the additional detail at least makes the use case more clear.

**Comment by lukaslewandowski-pearson** [comment]
Can I somehow pass: --format-options '{"colorsEnabled": true}' to the  cucumberOpts object?
(in this object I already have "format" array). I am using protractor-cucumber-framework.

**Comment by davidjgoss** [comment]
Closing this now after a long period of inactivity, as it's not something the core team has plans to address at the moment.

**Comment by davidjgoss** [comment]
Circling back here to note that as of 8.2.0 we have switched to using the `chalk` library for colored output, which has two effects:

- The auto detection is quite a bit better, making it less likely you have to override with the option
- `FORCE_COLOR` is now supported (by way of chalk supporting it) as well as the format option

See update docs: https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md#colored-output
