### ISSUE TITLE
Call methods from another class in hooks.js file

### ISSUE THREAD

**Issue by saipradeepcs** [cucumber/cucumber-js#1147]
I'm trying to call a method "clickLogout" in After section of my hooks file but "clickLogout" method is present in Navigation class file. I'm trying to import Navigation class and call Navigation.clickLogout but i'm getting an error saying
TypeError: Navigation.clickLogout is not a function

var {BeforeAll, After, setDefaultTimeout} = require('cucumber');
var navigation = require('../..dist/navigation.po');
After(function (scenario, callback){
        console.log("Clicking logout from Hooks");
        navigation.clickLogout();        
    });

cucumberVersion: 4.2.1
browser: chrome 70.0.3538.77
node version: 8.12
OS: windows

**Comment by Izhaki** [comment]
This doesn't seem to have anything to do with cucumber-js.

Your error suggests that your own code (`Navigation.clickLogout`) has an issue it's not a function. My guess is that you require a class and a class is not an object instance and thus you get this error.

I'm closing this issue, but happy to reopen if share the code in `../..dist/navigation.po`.

Sidenote: Please use backticks when sharing code - see the `<>` icon in write mode.
