### ISSUE TITLE
Moving to babel-*@7 ecosystem

### ISSUE THREAD

**Issue by char0n** [cucumber/cucumber-js#1149]
Is there is plan to move to babel-*@7 ? This project is using for example babel-runtime@6.26.0 which is in github repo licensed under MIT, but npm distribution package doesn't contain the license file. It is required by MIT license to have full license text and copyright notice with every code distribution. Thus  the MIT license  itself makes babel-runtime@6.26.0 a proprietary code and cucumber as a user of this code distributes babel-runtime@6.26.0 (proprietary code) as part of it's installation.

This makes cucumber unusable in any environment where people care about licensing.

Babel 7 fixes this problem, by introducing lerna 3 which correctly copy licenses to all monorepo packages.

**Comment by charlierudolph** [comment]
I'm good with moving to babel 7. Would you be able to help us upgrade?

**Comment by char0n** [comment]
I would be able to help, but I'll have to include Oracle copyright notice into my contributions. Are you OK with that ?

**Comment by char0n** [comment]
I understand, sorry I cannot help more

**Comment by charlierudolph** [comment]
Done in 31e51ff0a99c274151f8ef91ee96ff6d981b7ec5. Making a release now

**Comment by char0n** [comment]
Thanks
