### ISSUE TITLE
reverse() of After hooks is done prior to BeforeAll

### ISSUE THREAD

**Issue by HaKr** [cucumber/cucumber-js#1150]
I have made [Typescript annotations](https://github.com/HaKr/cucumber_annotations) to define the Cucumber steps and hooks directly in a class definition.

It was my idea to also provide various HookScenarioResult parts directly to those annotated classes, so that it would not be required to have Before and After hooks in those annotated classes for only registering the scenario name. 

Below is how I tried to implement this:
```
class CustomWorld {
	constructor( )	{  WorldsMap.create( this ) }

	dispatchScenario( scenario: CucumberJS.HookScenarioResult ) {
		WorldsMap.dispatchMetadata( new metadataConstructor!( this, scenario ) )
	}
}

function addHooks() {
	CucumberJS.Before( CustomWorld.prototype.dispatchScenario )
	CucumberJS.BeforeAll( () => CucumberJS.After( CustomWorld.prototype.dispatchScenario ) )
}

CucumberJS.setWorldConstructor( CustomWorld )

```

The Before hook works as desired, but the After hook executes at last, although I am sure I define this one after all After hooks in the classes were defined. 

I tried to figure out what went wrong and found as possible reason that the SupportCodeLibraryBuilder::finalize() is run before the BeforeAll hooks. that finalize reverts the After and AfterAll definitions.

When the After and After All definition are unshifted into their respective arrays, it wouldn't be necessary to revert them and would the execution order always be in reverse order.

**Comment by Izhaki** [comment]
It seems that the current library behaviour does not land itself to your intent.

I'm not quite clear on what do you suggest the issue with the library is...

Could you kindly elaborate?

**Comment by charlierudolph** [comment]
I also don't understand the benefit of 

> add a scenario hook that MUST be executed before all hooks that are annotated with @after

The point of having the after hooks be reversed is that you could create your hooks in pairs which allows the related code to stay closer together
* Before A
* After A
* Before B
* After B

These then get executed as
* Before A
* Before B
* After B
* After A

If hooks need to be run in a specific order they should be defined in a single file to easily control the order of definition and thus order of execution. Otherwise you can define them in separate files. I've generally seen very few hooks in a codebase (5 or less). Do you have an example where this is feature would be needed?

I also don't understand the benefit of having your step definitions in classes. Certainly step definitions have logical groupings but they can be separated by file instead of by class.

**Comment by HaKr** [comment]
Back to why I would like to define a hook in another hook:
 `CucumberJS.BeforeAll( () => CucumberJS.After( CustomWorld.prototype.dispatchScenario ) )`

I am absolutely aware that this is not common practice. I still follow the principle that test order should not be relevant, nor the order of before and after hooks. The users of the annotations are very much advised to keep that in mind.

In my annotation implementation, however, I want to dispatch the scenario results and some internal metadata to all registered Worlds. This **MUST** be done prior to all @After methods, as those methods could use that information (e.g. for naming a screenshot)

So, calling this hook inside another hook allows me to do some book keeping. It requires no change to the API, only a slightly different way to add the hooks to the collections.
It neither does use technology because "one can", it only allows for a simpler way to define step definitions with Typescript. A lot of people today use Typescript.

**Comment by Izhaki** [comment]
# World vs Step Definitions

The [NodeJS example you have linked](https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md) is... well... just an example. It should be glaringly obvious this is not a real-world test - it just shows you how things can be done.

It is a rather coincident that the class methods map 1:1 to step definitions. In concrete usage, World will most often host a set of utility functions that may well not map to a single step definition.

> A separate file is then necessary to bind the step templates to the class methods.

This is exactly the point! 

- You don't want your step definitions and World mixed.
- They each have their own purpose.
- **World** is a central context/utility construct, instance-based.
- **Step definitions** are to map between Gherkin and implementation.

I would find it all too confusing to look for a step definition and find it in World. I would expect to have a look at the `*.js` files under `features` and see it there.

**Anyhow**, all of this is just a discussion on how the library should be consumed, not working; so let's park this for now.

# Forward

My argument:

- This project has its own set of requirements, which are currently met.
- This is a request to modify internal implementation so a niche project can achieve its task.
- Neither there's a new requirement here, nor I think the time and added complexity are worth the outcome.
- **I therefore vote to close this issue.**

**Having said that**, if you submit a PR that shows minimal implementation impact and the tests still pass - you may get this through.

**Comment by Izhaki** [comment]
Closing this as Won't Do.

PR still welcome.
