### ISSUE TITLE
Error: Cannot find module 'pretty'

### ISSUE THREAD

**Issue by djom20** [cucumber/cucumber-js#1152]
Hi Cucumber Team,

I just update my cucumber version and I'm facing this bug, I don't know why cucumber is looking for the pretty module in my files, but obviously it's a bug and I'd like to know how I can fix it.

NodeJs: 6.9.1
Cucumber: 5.0.2

![image](https://user-images.githubusercontent.com/1834808/48136312-5b8bc780-e26d-11e8-980d-2adfd87a8782.png)

```
'use strict';

let path = require('path');

exports.config = {
    directConnect: true,
    ignoreUncaughtExceptions: true,
    baseUrl: `${baseUrl}`,
    capabilities: {
        'browserName': 'chrome',
        'name': 'Test',
        'chromeOptions': {
            'args': [],
            'prefs': {
                'profile.managed_default_content_settings.notifications': 1
            }
        }
    },

    specs: [path.join(__dirname, '..', '..', 'features', '**', '*.feature')],

    allScriptsTimeout: 500000,

    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: {
        require: [
            path.join(__dirname, '..', '..', 'step_definitions', '**', '*_steps.js')
        ],
        format: ['pretty'], // here is the bug
        tags: ['@complete'],
    },`

    onPrepare: function () {
        browser.driver.manage().window().setSize(2440, 900);
        browser.driver.manage().window().maximize();

        chai.use(require('sinon-chai'));
        chai.use(require('chai-as-promised'));
    }
};
```

**Comment by pradeepreddy305** [comment]
i am also facing same issue

**Comment by charlierudolph** [comment]
Yep. The pretty formatter was deprecated in version 3. See the [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#300-2017-08-08)

**Comment by djom20** [comment]
@charlierudolph Do you know any way to make the `pretty` format again? Because people says that pretty formatter was deprecated, but no one says how we can to put it again.

**Comment by djom20** [comment]
@charlierudolph My boss need to see each scenario and know which step of the feature is executing when the tests are running, obviously with the dots it's not possible. Also I see that we can create custom formatter but I didn't find any way to implement it without EMAC6 or Browserify. Do you know how I can implement it with only javascript?

**Comment by Marketionist** [comment]
@djom20 maybe this implementation of pretty formatter will fit your needs -
 https://github.com/kozhevnikov/cucumber-pretty

**Comment by salman-** [comment]
maybe it does not fix your problem but, at the end i decided to simply remove `pretty`:

` format: []`
