### ISSUE TITLE
anonymous async function does not parse functions from "this" parameter 

### ISSUE THREAD

**Issue by ovidijusr** [cucumber/cucumber-js#1154]
Using:
"cucumber": "^5.0.2",
"puppeteer": "^1.10.0",

For some reason I cannot use anonymous async functions inside steps.js

``` Before(async function () { return this.openPage() });  // works fine```

``` Before(async () => (this.openPage()));  //  TypeError: this.openPage is not a function```

openpage function
```
 async openPage() {
    this.browser = await puppeteer.launch({
      headless: false,
      slowMo: 15,
      args: [`--window-size=${this.width},${this.height}`],
    });
    this.page = await this.browser.newPage();
    await this.page.goto(PAGE);
  }
```
Any ideas how this could be fixed?

**Comment by znevrly** [comment]
https://github.com/cucumber/cucumber-js/blob/master/docs/faq.md
