### ISSUE TITLE
Can't make 'not' tag work in tags expression

### ISSUE THREAD

**Issue by xliiauo** [cucumber/cucumber-js#1163]
Hi, I came across the same issue like the following ticket:

https://github.com/cucumber/cucumber-js/issues/741
https://github.com/cucumber/cucumber-js/issues/136

To reproduce:
`npx cucumber-js --require-module @babel/register --tags ~@wip`, then I will end up with 
```
0 scenarios
0 steps
0m00.000s
```
Could you please help? Many thanks.

**Comment by mgonnet** [comment]
Try this:

`npx cucumber-js --require-module @babel/register --tags "not @wip"`

**Comment by xliiauo** [comment]
Thank you very much @mgonnet , the `\'not @TODO\'` works perfect in my case. Using `--tags ~@wip` will end up with no scenarios been run.
