### ISSUE TITLE
"Conflicting version of stack-chain found"

### ISSUE THREAD

**Issue by 75lb** [cucumber/cucumber-js#1166]
Could the cucumber project please move away from using the stack-chain module?

Take a look at [this code](https://github.com/AndreasMadsen/stack-chain/blob/master/index.js#L5) in stack-chain. This is the killer section:

```js
if (global._stackChain.version === require('./package.json').version) {
  // continue
} else {
  throw new Error('Conflicting version of stack-chain found');
}
```
So, if `global._stackChain.version` does not _exactly equal_ the installed stack-chain version, it throws (crashing cucumber). This issue is blocking me using cucumber to test a [loopback](https://loopback.io) project because [loopback-context](https://github.com/strongloop/loopback-context) and cucumber install non-equal versions of stack-chain, as you can see here:

```
$ npm ls stack-chain --depth 10
stack-chain-issue@1.0.0 /Users/llobrook/stack-chain-issue
├─┬ cucumber@5.1.0
│ └── stack-chain@2.0.0
└─┬ loopback-context@3.4.0
  └─┬ cls-hooked@4.2.2
    └─┬ async-hook-jl@1.7.6
      └── stack-chain@1.3.7
```

So, running cucumber against my loopback project (containing loopback-context) always crashes with output like this:

```
Failures:

1) Scenario: Something
   ✖ Before # step_definitions/defs.js:34
       Error: Conflicting version of stack-chain found
           at Object.<anonymous> (/Users/llobrook/stack-chain-issue/node_modules/stack-chain/index.js:10:11)
           at Module._compile (module.js:577:32)
           at Object.Module._extensions..js (module.js:586:10)
           at Module.load (module.js:494:32)
           at tryModuleLoad (module.js:453:12)
           at Function.Module._load (module.js:445:3)
           at Module.require (module.js:504:17)
           at require (internal/module.js:20:19)
           at Object.<anonymous> (/Users/llobrook/stack-chain-issue/node_modules/async-hook-jl/index.js:17:22)
           at Module._compile (module.js:577:32)
           at Object.Module._extensions..js (module.js:586:10)
           at Module.load (module.js:494:32)
           at tryModuleLoad (module.js:453:12)
           at Function.Module._load (module.js:445:3)
           at Module.require (module.js:504:17)
           at require (internal/module.js:20:19)

1 scenario (1 failed)
4 steps (4 skipped)
0m00.124s
```

I'm blocked, I can't work around this issue without ditching either cucumber or loopback-context. My env: 

```
$ node -v
v6.16.0
$ npm -v
3.10.10
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

**Comment by AndreasMadsen** [comment]
`stack-chain` is indeed a pain, although dealing with conflicts of `Error.prepareStackTrace` is an even greater pain. The only purpose of `stack-chain` is to deal with conflicting used of `Error.prepareStackTrace`, nothing else. So often there isn't much choice there.

As I see it, `cls-hooked` should use `async-hook-jl` but it should use the builtin `async_hooks` module. The documentation for `cls-hooked` says that given a "Nodejs version >= 8.2.1" it will use `async_hooks`. So I would suggest that you update your version of Node.js. The LTS End-Of-Life for 6.x is in April anyway. If that doesn't work, it is a bug in `cls-hooked`.

**Comment by 75lb** [comment]
Hi @AndreasMadsen , thanks for the input. Unfortunately, we can't simply update node (it's a corporate, IBM infrastructure thing). Node.js v6 is still maintained and cucumber advertises support for it.

I can confirm this is not an issue in node v8.15 and above.

If anyone else is blocked by this, the only way round it is to override the global `_stackChain` version with a nasty hack like this:

```js
global._stackChain.version = '1.3.7';
```

**Comment by charlierudolph** [comment]
Hi @75lb,

I'd say this is more an issue with stack-chain. I'd prefer we open an issue on that library and ask for a nicer way to workaround this. Maybe when it throws that error, it lets the user know of ways to tell the library "use the first version of stack chain that gets installed" or "allow this version to override previous installs" (if possible).

Since you currently have a workaround, I'd rather not change cucumber for this.

**Comment by 75lb** [comment]
Yes it's a huge issue with stack-chain but I'm not sure it's worth posting an issue there. The stack-chain maintainer (@AndreasMadsen) gave his feedback above - he suggested upgrading node which unfortunately I can't do.

This issue only seems to affect node v6 but you do support v6.

**Comment by charlierudolph** [comment]
We are only supporting node 6 for a few more months though. And again since you have a workaround (even though its a hack), I don't think its worth trying to find a better solution.

If you have a suggestion for how we can move away from stack-chain while still being able to filter stacktraces I'm all ears.

**Comment by AndreasMadsen** [comment]
@75lb Your other option is to ask `async-hook-jl` to update `stack-chain`. Yes, a nicer solution to `stack-chain` could be implemented. It would have to be some automatic share of settings when a newer version is used, but even so, that could never work across different major versions. It would also be mind-boggling difficult even within the same major version.

**Comment by AndreasMadsen** [comment]
@75lb You should also note, if IBM uses `async-hook-jl`, it depends on an internal API in nodecore called `async_wrap`. I'm one of the co authors of that nodecore API and the new public version `async_hooks` as well, and I can formally tell you that it is a bad idea to use `async_wrap`.

Besides that, using node 6.x for much longer will also be a bad idea as it won't get security updates.

Considering all this, I think the `stack-chain` module is the least of your issues.

**Comment by joniba** [comment]
> Hi @AndreasMadsen , thanks for the input. Unfortunately, we can't simply update node (it's a corporate, IBM infrastructure thing). Node.js v6 is still maintained and cucumber advertises support for it.
> 
> I can confirm this is not an issue in node v8.15 and above.
> 
> If anyone else is blocked by this, the only way round it is to override the global `_stackChain` version with a nasty hack like this:
> 
> ```js
> global._stackChain.version = '1.3.7';
> ```

Where do you put this line?

**Comment by muthukumarse** [comment]
> > Hi @AndreasMadsen , thanks for the input. Unfortunately, we can't simply update node (it's a corporate, IBM infrastructure thing). Node.js v6 is still maintained and cucumber advertises support for it.
> > I can confirm this is not an issue in node v8.15 and above.
> > If anyone else is blocked by this, the only way round it is to override the global `_stackChain` version with a nasty hack like this:
> > ```js
> > global._stackChain.version = '1.3.7';
> > ```
> 
> Where do you put this line?

Did you able to figure out? I am too wants to know that.

**Comment by charlierudolph** [comment]
Closing as this was specific to node 6 and that is no longer supported by cucumber-js.

**Comment by melibe23** [comment]
Hey, I am having the same issue and I have version 10 of node, the latest.... How can I fix? I would prefer not to touch cucumber, but if it is the only workaround, could you please, tell me exactly where should I change to ' global._stackChain.version = '1.3.7'; '

Thanks!
