### ISSUE TITLE
Not possible to use --require-module ts-node/register along with cucumber.js

### ISSUE THREAD

**Issue by ZescherW** [cucumber/cucumber-js#1168]
Hi,

I have a cucumber-js project written in Typescript and I'm calling an npm script for transpiling Typescript files with `tsc` before executing the project:

`node ./node_modules/cucumber/bin/cucumber-js`

js files are generated in a separate folder called ***transpiled***.
I also have a _**cucumber.js**_ for loading a profile which looks like this:

```
const { DefaultCucumberProfileBuilder } = require('./transpiled/acceptance/config/DefaultCucumberProfileBuilder');

module.exports = DefaultCucumberProfileBuilder.build();
```

This is working fine, but If I try to require **_ts-node_** module in order to avoid calling `tsc`:
`node ./node_modules/cucumber/bin/cucumber-js --require-module ts-node/register`

I'm getting the following error:
`Error: Cannot find module 'acceptance/config/DefaultCucumberProfileBuilder'`

DefaultCucumberProfileBuilder is a Typscript class.

**Comment by Izhaki** [comment]
I have just merged an [update to the transpilation cli instructions](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#transpilation), which include a typescript section.

It goes:

```
--require-module ts-node/register --require 'step-definitions/**/*.ts'
```

----

If you do this, and don't transpile before, than you won't have `./transpiled/...` so `cucumber.js` will fail.

If you still need to call `DefaultCucumberProfileBuilder` just reference the `.ts` file

**Comment by ZescherW** [comment]
Hi,

Maybe I didn’t explain myself clearly enough: I’d like to avoid having a transpiled folder by using —require-module ts-node/register and at the same time keeping the cucumber.js file in order to load a profile using a Typescript class.
Isn’t possible to have a cucumber.ts file to load profiles when —require-module ts-node/register is passed?

**Comment by Izhaki** [comment]
What your `cucumber.js` looks like right now?

In the original question it was:

```
const { DefaultCucumberProfileBuilder } = require('./transpiled/acceptance/config/DefaultCucumberProfileBuilder');

module.exports = DefaultCucumberProfileBuilder.build();
```

Which points to the `./transpiled` folder.

Is `DefaultCucumberProfileBuilder` a `.ts` file (under `src`)?

---

At any rate, be aware that instead of using `—require-module ts-node/register` you can put this as the first line of your `cucumber.js`:

```
require('ts-node').register({ /* options */ })
```

Thereafter anything `.ts` will work.

**Comment by ZescherW** [comment]
Hi,

When I used `--require-module ts-node/register` my **_cucumber.js_** looks like this:

```
import { DefaultCucumberProfileBuilder } = require('acceptance/config/DefaultCucumberProfileBuilder');

module.exports = DefaultCucumberProfileBuilder.build();
```

my project tree looks more or less like this:

├── acceptance
│   ├── config
│   │   ├── AgentMetaData.ts
│   │   ├── BaseMetaData.ts
│   │   ├── CucumberProfileBuilder.ts
│   │   ├── DefaultCucumberProfileBuilder.ts
│   │   ├── RunnerMetaData.ts
│   │   ├── TestRunTagStats.ts
│   │   └── json
│   │       ├── BaseUrls.module.json
│   │       ├── SauceLabs.file.json
│   │       ├── SuiteMap.module.json
│   │       └── TaskProfiles.module.json
│   ├── features  
│   ├── logger
│   │   └── Provider.ts
│   ├── page_objects
│   ├── step_definitions
├── cucumber.js
├── package-lock.json
├── package.json
├── tsconfig.json

DefaultCucumberProfileBuilder is invoking functionality from many ts files located in config folder.

I tried to add `require('ts-node').register();` to the **_cucumber.js_** file instead of using `--require-module ts-node/register` and it didn't work.

Is still someting I'm missing or doing wrong?

Maybe there is an incompatibility between using importing ts files from cucumber.js and using `--require-module ts-node/register`.

And yes, DefaultCucumberProfileBuilder is a ts file importing other ts files in order to build a cucumber profile.

I appreciate your help.

Regards,

**Comment by Izhaki** [comment]
> I tried to add require('ts-node').register(); to the cucumber.js file instead of using --require-module ts-node/register and it didn't work.

Which error do you get for each of these cases?

Also:

```
require('acceptance/config/DefaultCucumberProfileBuilder');
```

Try provide relative path instead (I suspect that `acceptance` will resolve to node modules.

**Comment by ZescherW** [comment]
cucumber.js, node_modules and acceptance folder are at the same level.

The error I get in all cases is: `Cannot find module 'acceptance/config/DefaultCucumberProfileBuilder'`

**Comment by ZescherW** [comment]
Sure!

```
require('ts-node').register();
const { DefaultCucumberProfileBuilder } = require('acceptance/config/DefaultCucumberProfileBuilder');

module.exports = DefaultCucumberProfileBuilder.build();
```

And I'm running using the following command:
`node ./node_modules/cucumber/bin/cucumber-js`

**Comment by Izhaki** [comment]
try:

```
require('./acceptance/config/DefaultCucumberProfileBuilder');
```
