### ISSUE TITLE
Bug: Terminates without any errors / stack trace

### ISSUE THREAD

**Issue by haikyuu** [cucumber/cucumber-js#1169]
When i pass a type that doesn't exist in a step definition, i don't get any error. As a newcomer, it's hard to debug.

Reproduction case
```diff
- When("i try running cucumber-js with {number} existing type", function(){}")
+ When("i try running cucumber-js with {int} existing type", function(){}")
```

**Comment by charlierudolph** [comment]
Believe this is fixed when we upgraded to cucumber-expressions v7 in 7dc2eff534716f1a86452e1c694ee2133bc065ef. Will comment back once this is released. May be worth adding a test for this

**Comment by charlierudolph** [comment]
Just released version 6. Please comment if this isn't resolved after updating
