### ISSUE TITLE
Calling one feature from another , best practices of using feature file for rest response validation

### ISSUE THREAD

**Issue by krishna01012002** [cucumber/cucumber-js#1170]
Hi Guys,
Please help me, understanding of best usage of BDD and feature files.
I have Rest calls and need to validate response data , Can I give expected response data from feature file as mentioned below?

  Then response includes the following in any order
    | data[*].username                                                         | 1111 |
    | data[*].phoneNumbers[*].phoneNumber                                      | 122-222-2222         |
    | data[*].retailLocationRoles[*].securityRoleId                            | 10                    |

Otherwise  should I keep expected response data in external files and read inside of code? is it best practice ? 
if expected response data changes in future , is it good idea to change inside feature files ? or we need to follow TDD process?
is it good idea to call one feature file from another ? 

Some one suggesting me to keep data in external files read inside of code , and saying not good idea to change feature file when response data changes? is it true?
Thanks for reading . Kindly help me.

Any link for best practice of using cucumber ?

**Comment by Izhaki** [comment]
Hi. There are 9 questions in this issue. But basically:

Gherkin features normally specify the desired behaviour of the system. As such, referencing external data is unwise, unless including it is 'unreasonable'. For example, you wouldn't include screenshots in your features files, instead, you'll have a step saying something like `Then it should match the snapshot "HomePage"`

In your case, the response data does not seem huge, so you have two options:

1. Use [data tables](https://github.com/cucumber/cucumber-js/blob/master/features/data_tables.feature)
2. Use [doc string](https://docs.cucumber.io/gherkin/reference/#doc-strings) where you can pass JSON.

Which one's better depends on the data needs asserting on.

----

I'm closing this issue as it's a question not an issue.

This is a much better place to ask these sorts of questions:
https://stackoverflow.com/questions/tagged/cucumberjs+cucumber+gherkin
