### ISSUE TITLE
Data transformation on table data

### ISSUE THREAD

**Issue by rayk47** [cucumber/cucumber-js#1175]
I am currently using data tables with cucumber-js + typescript.

One problem I am running into is that everything in the table is being read as a string instead of allowing types. I did review the ticket https://github.com/cucumber/cucumber-js/issues/45 but the solution implemented was data transformation for step parameters but the table passed in is still always an array of string instead of a generic array that has the data transformed.

An example of a use case is shown below:

`
```
 Scenario Outline: Adding items to our shopping cart should increase the number of items in the cart
    Given I add an item to my cart
    Then My cart totals should be updated:
      | json_field                   | new_value         |
      | number_of_items      | <total_items>   |

    Examples:
    |total_items|
    |1|
```
`
In this case, I want the total_items value to be passed in as an int/number and not a string

I was thinking there could be a way to set the data type as such

`
```
      | json_field:string                   | new_value         |
      | number_of_items                 | <total_items>:number                 |
```
`

**Comment by charlierudolph** [comment]
This seems related to cucumber/cucumber#210. We previously had #845 and #752 as well

**Comment by charlierudolph** [comment]
Going to close this in favor of the cucumber issue. Dealing with this in a generic way is pretty tough. This can also start out as a standalone library that takes in a 2D array of strings and does the type conversion. Once that gets some usage and we settle on the proper UI, it could be integrated into cucumber-js
