### ISSUE TITLE
Possible Get Current Implemented JavaScript Steps Within The Framework

### ISSUE THREAD

**Issue by bhreinb** [cucumber/cucumber-js#1178]
Hi there,

Is their a way to store in memory what JavaScript steps are already implemented? 

More details as to what I mean can be found here in the below stackoverflow post

`https://stackoverflow.com/questions/24426487/in-cucumber-js-is-it-possible-to-list-all-of-the-available-steps`

Up to version 1 this was possible as steps was exported via module.exports but the way steps have been implemented from version 2 onwards has changed.

The context is for this request is to develop a static analysis tool to manage the test steps within a framework as it scales. This may be solved via another means however using `usage` & `snippets` as detailed within 

https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md

From trying that I get returned the below:

```
{
    "line": 11,
    "matches": [
      {
        "line": 6,
        "text": "I am open GitHub page",
        "uri": "features/github.feature"
      },
      {
        "line": 12,
        "text": "I am open GitHub page",
        "uri": "features/github.feature"
      }
    ],
    "pattern": "I am open GitHub page",
    "uri": "features/step_definitions/github.js"
  },
  {
    "line": 32,
    "matches": [
      {
        "line": 7,
        "text": "I am typing my search request \"TestCafe\" on GitHub",
        "uri": "features/github.feature"
      }
    ],
    "pattern": {},
    "uri": "features/step_definitions/github.js"
  },
```

However the pattern on some occasions doesn't be returned plus it would be nice to have the accompanying function & parameters for the pattern. It's my intention to post all that information to the static analysis report. This was functionality I was able to do in version 1 of the cucumber js toolset albeit I did it all via custom code. Thoughts?

**Comment by charlierudolph** [comment]
The pattern not printing is something we need to fix. For giving the code associated with it, that should be possible and something we could add to the usage-json formatter.

**Comment by charlierudolph** [comment]
In 1079c0e39fc7be149010b01e660882e2c6970d25 merged in a fix for the missing pattern, and added in properties PatternType (CucumberExpression or RegularExpression) and Code (function that was supplied converted to a string). Planning to make a release soon with this change

**Comment by devniel** [comment]
Hi @charlierudolph,

What class or method of cucumber can be used to extract the steps from a `.steps.js` file?, it could help me on a generator that I'm building that will check a `.feature` file and only will generate steps that are missing or not yet implemented on the `step_definitions` folder.

Thanks!

**Comment by charlierudolph** [comment]
You can run `cucumber-js --dry-run --format usage-json` (--dry-run causes cucumber-js to not actually run steps) and that will output a json string of the definitions that exist and where they are used.

**Comment by charlierudolph** [comment]
Just released version 6. Please comment if this isn't resolved after updating
