### ISSUE TITLE
parallel doesn't improve overall duration

### ISSUE THREAD

**Issue by HemantaK** [cucumber/cucumber-js#1179]
I am running 3 scenarios with each scenario having setTimeout 5 sec, when running without parallel and with parallel (cucumber-js parallel 2) , the time is not improved , both taking same time .seems parallel is not working 
Result:

3 scenarios (3 passed)
9 steps (9 passed)
0m20.044s

Here is the feature .
Feature: Using calculator to calculate simple operators

  Scenario: Add two numbers
    Given I have calculator
    When I add 4 and 3
    Then I should see 7

 Scenario: Add multiply numbers
    Given I have two numbers
    When I multiply both
    Then I should get product

  Scenario: Add divide numbers
    Given I have two numbers
    When I divide both
    Then I should get division

Step_defn:

'use strict';

const {Given,When,Then} = require('cucumber');

  Given(/^I have calculator$/, function(callback){
    // do nothing
    setTimeout(function(){
      console.log("I am in Given- Calc")
      callback();
    },5000)
    
  });

  When(/^I add (\d+) and (\d+)$/, function(a, b, callback){
    console.log("Add")
    callback();
  });

  Then(/^I should see (\d+)$/, function(result, callback){
    // var r = this.getResult();
    // if(r == result){
    //   callback();
    // } else {
    //   callback(new Error("total number displayed wrongly, actual is " + r ));
    // }
    console.log("Result")
    callback();
  });

  Given(/^I have two numbers$/, function (callback) {
    // Write code here that turns the phrase above into concrete actions
    
    setTimeout(function(){
      console.log("in Gvien -- mul sc")
      callback()
    },5000)
    
  });

  When(/^I multiply both$/, function (callback) {
    // Write code here that turns the phrase above into concrete actions
    console.log("in When -- mul sc")
    callback();
  });

  Then(/^I should get product$/, function (callback) {
    // Write code here that turns the phrase above into concrete actions
    console.log("in Then  -- mul sc")
    callback();
  });

  When('I divide both', function (callback) {
    // Write code here that turns the phrase above into concrete actions
    console.log("Hi")
    callback();
  });

  Then('I should get division', function (callback) {
    // Write code here that turns the phrase above into concrete actions
    setTimeout(function(){
      console.log("in Gvien -- mul sc")
      callback()
    },5000)
    
  });

**Comment by rayk47** [comment]
That's a very small sample size and could be a result of creating node containers with the configuration for use. Try adding 10 or 20 more scenarios and see if you see an improvement.

**Comment by SONIKASUHANI** [comment]
@rayk47  you are right, I increased to 24 scenarios and run in parallel 5 , it has improvements , however notice , the console is printing the correct duration, it prints the non parallel duration. 

24 scenarios (24 passed)
72 steps (72 passed)
2m40.150s

**Comment by rayk47** [comment]
That is odd my guess is maybe the time calculator is adding all of the parallel instance times together instead of just taking the longest running instance value.

**Comment by charlierudolph** [comment]
Parallel will not yield benefits in every instance as it incurs a startup cost for each process. 

Yes currently the time printed in the sum of time used to run every step. I don't think its worth adding the actual runtime for the cucumber process as that can be done with other tools and would also report cucumber's overhead

For example on a mac running cucumber-js's tests suite
```
> time ./bin/cucumber-js
216 scenarios (216 passed)
1061 steps (1061 passed)
0m36.165s
       46.78 real        31.74 user         5.14 sys
```
```
> time ./bin/cucumber-js --parallel 4
216 scenarios (216 passed)
1061 steps (1061 passed)
0m40.467s
       16.05 real        45.62 user         6.82 sys
```
