### ISSUE TITLE
Unable to run Cucumberjs specs

### ISSUE THREAD

**Issue by skAutomation12** [cucumber/cucumber-js#1182]
Browser get stuck indifinitely after it completes executing onprepare(). 
Cucumber specs never get started. 

Below is the config:
var featsLocation = 'features/';
var stepsLocation = 'steps/';

exports.config = {
    rootElement: '[ng-app]',
    directConnect: true,
    
    params: {
        authURL: '',
        login: {
            email: '',
            passw: ''
        }
    },
    resultJsonOutputFile: '',
    getPageTimeout: 60000,
    allScriptsTimeout: 60000,
    framework: 'custom', // set to "custom" instead of cucumber.

    frameworkPath: require.resolve('protractor-cucumber-framework'), // path relative to the current config file
    ignoreUncaughtExceptions: true,
    capabilities: {
        shardTestFiles: true,
        maxInstances: 1,
        'browserName': '',
        'phantomjs.binary.path': '/srv/build/applications/phantomjs/bin/phantomjs.exe',
        chromeOptions: {
            args: [
                 'useAutomationExtension: false',
                 'show-fps-counter=true',
            '--disable-browser-side-navigation',]
             
            
        }
    },
    onPrepare: function () {

        global.EC = protractor.ExpectedConditions;
        browser.driver.get(browser.params.authURL);
        browser.driver.manage().window().maximize();
        browser.driver.findElement(by.id('Main_txtUserName')).sendKeys(browser.params.login.email);
        browser.driver.findElement(by.id('Main_txtPassword')).sendKeys(browser.params.login.passw);
        browser.driver.findElement(by.id('Main_btnSubmit')).click();
        browser.driver.sleep(3000);
        browser.driver.findElement(by.id('Main_lnkCancel')).click();
        return browser.driver.wait(function () {
            return browser.driver.getCurrentUrl().then(function (url) {
                var expectedurl = new RegExp("url");
                var until = protractor.ExpectedConditions;
                
                browser.waitForAngular();
                console.log('Validating components presence...')
                browser.wait(until.presenceOf(element(by.id("searchKeyword"))), 5000, 'ERROR: Element taking too long to appear in the DOM');
                return expectedurl.test(url);
            });
        }, 10000, 'ERROR: Angular did not load!');
    },
    baseUrl: '',
    // require feature files
    specs: [
              featsLocation+'locationSearch.feature'
                , featsLocation+'ediRejects.feature'
                
        ],
    logLevel: 'INFO',
    coloredLogs: true,

    cucumberOpts: {
        tags: '',

        require: [
             './support/*.js'
                        , stepsLocation+'locationSearch/locationSearch.spec.js'
                        , stepsLocation+'ediRejects/ediRejects.spec.js'
                        
                ],
        monochrome: true,
        strict: true, // <boolean> fail if there are any undefined or pending steps
        'no-colors': false,
            format: ['pretty', 'progress', 'pretty:Reports_Json/Log.txt', 'json:Report.json'], 
        plugin: "json",
        'dry-run': false,
        compiler: []            ,
        includeStackTrace: true,

    },
};

**Comment by rayk47** [comment]
What is the point in using a variable here for your path to the spec as you are not reusing it anywhere? 
 My recommendation is update the required and feature paths to

`
    require: [
         './support/*.js'
                    , './steps/*'                  
            ],
`

`
specs: [
          './features/*         
    ]
`

**Comment by Izhaki** [comment]
You have stated:

> Cucumber specs never get started.

So clearly this is not an issue with Cucumber, but with your setup.

I'd recommend you start with the basic example given in `protractor-cucumber-framework` and slowly flesh out the setup above.

If the basic config in protractor-cucumber-framework doesn't work, let it be know here.
