### ISSUE TITLE
SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by Hugale12** [cucumber/cucumber-js#1183]
Hi everyone ! 

Look my problem : 

```powershell
 > cucumber-js -r cucumber.conf.js -r tests/e2e/features/*  -r tests/e2e/step-definitions/* --format node_modules/cucumber-pretty

D:\Projets\****\*******\1_Dev\web\******-client\tests\e2e\features\google.feature:1
(function (exports, require, module, __filename, __dirname) { Feature: Google Search
                                                                              ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at supportCodePaths.forEach.codePath (D:\Projets\-----\****-*****\1_Dev\web\*****-client\node_modules\cucumber\lib\cli\index.js:142:42)
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (D:\Projets\****\1_Dev\web\****-client\node_modules\cucumber\lib\cli\index.js:142:22)
    at D:\Projets\****\****-****\1_Dev\web\*****-*****-client\node_modules\cucumber\lib\cli\index.js:169:41
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Projets\****\*****\1_Dev\web\*****-client\node_modules\cucumber\lib\cli\index.js:44:103)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! *****-client@0.1.0 e2e: `cucumber-js -r cucumber.conf.js -r tests/e2e/features/*  -r tests/e2e/step-definitions/* --format node_modules/cucumber-pretty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ****-****-client@0.1.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\Users\****\AppData\Roaming\npm-cache\_logs\2019-03-06T09_44_02_988Z-debug.log
PS D:\Projets\***\***-****\1_Dev\web\****-****-client>
```
Gherkin 
```gherkin
Feature: Command line interface

  Scenario: Some
    Given I have 48 cukes in my belly
```
I don't believe it's impossible to a add directory of features in requirement ...

![image](https://user-images.githubusercontent.com/38684050/53884910-da76ee00-401c-11e9-9520-01997c9fc6ac.png)

```json
  "e2e": "cucumber-js -r tests/e2e/features/* -r cucumber.conf.js --format node_modules/cucumber-pretty" 
```
If someOne have the solution for that ... 

Thx's a lot !

Hugo

**Comment by Izhaki** [comment]
The require flag (`-r`) is for javascript files.

`-r tests/e2e/features/*` Requires all files, including `.feature` files. So Node complains it cannot parse them.

Change to `-r tests/e2e/features/*.js`

See examples [in the cli docs](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md)

**Comment by Hugale12** [comment]
You did not understand my problem.

The problème is not for .js but for .feature    The directory of features is impossible to change ...

**Comment by Izhaki** [comment]
Node is clearly trying to load `D:\Projets\****\*******\1_Dev\web\******-client\tests\e2e\features\google.feature:1`

`Feature: Google` is valid javascript
`Feature: Google Search` is not.

Basically, by having `-r tests/e2e/features/*` You tell node to `require(x)` where `x` is any file under `tests/e2e/features/*`.

**Comment by Hugale12** [comment]
I have found the solution ....

You'r right @Izhaki my bad for --require ...
But i don't understand why if i writte : 

`cucumber-js path/to/features/*`  --->> WRONG

`cucumber-js path/to/features/**/*.feature` ---->> GOOD

Have you any explain before closed ?

**Comment by Izhaki** [comment]
That's the magical glob pattern, one of the hardest things to understand (after Regex).

I can tell you that `**/*.feature` pattern means search this folder and all its sub folders (and sub folders, and so on...), for a file with the extension `.feature`.

Not sure where your feature files are and why `/*` doesn't work.
