### ISSUE TITLE
How to add metadata on each Feature JSON output

### ISSUE THREAD

**Issue by muthukumarse** [cucumber/cucumber-js#1185]
I want to add metadata like this
`
{
      browser: {
        name: 'chrome',
        version: '68.0.3419.0'
      },
      device: 'Local Test Machine',
      platform: {
        name: 'linux',
        version: 'x86_64'
      }
    }

`

to every feature of JSON output, which will be used on HTML report.

is there way to do that through hook or something?

**Comment by andreasmarkussen** [comment]
The [code of the JSON Formater](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/json_formatter.js) does not support as I see it, this but I have done similar actions with the HTML Formatter. 

So this would need to be a pull request, and it would make sense and perhaps I would help out. Might have some time this week.

**Comment by muthukumarse** [comment]
Hi @andreasmarkussen 

Thanks, can you post here the code snippet to achieve through AfterAll

Again - waiting for that feature, please do that.

**Comment by rayk47** [comment]
@muthukumarse @andreasmarkussen gave you a possible workaround solution but I don't see why you can't come up with the AfterAll code functionality yourself rather than @andreasmarkussen having to write it for you..

**Comment by muthukumarse** [comment]
@rayk47 I have alternate solution to achieve what I want. 

@andreasmarkussen - I tried with AfterAll it's failed because of node process not over at the time After All function execution. 

I want to know that do able to do that if so share that here. It will benefit to everyone in community.

**Comment by muthukumarse** [comment]
@andreasmarkussen going with my own solution as post-process before generating the report.

It will be nice to have if cucumber-js support natively

Also - AfterAll doesn't work since the node process not over and the JSON file is empty at the moment.

**Comment by andreasmarkussen** [comment]
It is also possible to solve it by making separate text files called e.g. metadata.browser.json and then I made a simple js script, that joined it into the cucumber report json file.

**Comment by charlierudolph** [comment]
Sorry didn't respond to this. This should definitely be something that is done post-processing
