### ISSUE TITLE
Scenerios are failing but Git pipeline is passing.

### ISSUE THREAD

**Issue by burghategaurao** [cucumber/cucumber-js#1187]
Scenerios are failing but Git pipeline is passing. Let us know how to fail Git pipeline in case failuer.

Failures:

       AssertionError: object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given
           at CustomWorld.<anonymous> (C:\Users\\Desktop\gaurao-workspace\27-03-2019-CF-68192-IntegrationTestcasesforGZippedChanges\centralizedlogging-serviceconfigmanager\test\integration_tests\step_defination\gzip-steps.js:53:27)
           at <anonymous>
           at process._tickDomainCallback (internal/process/next_tick.js:228:7)

3 scenarios (1 failed, 2 passed)
11 steps (1 failed, 10 passed)
2m44.528s

**Comment by andreasmarkussen** [comment]
What pipeline are you using? Jenkins, VSTS, Gitlab, or? 
And it depends on the configuration of your pipeline?

Cucumber returns a return code, and this has to be picked up by the "Git pipeline"?

What does the console/log file say from your "git pipeline".

**Comment by aslakhellesoy** [comment]
Cucumber exits with a non-0 exit status (1 I think) when there are failing scenarios. If this doesn't cause your build to fail, then that is a problem with your build scripts and/or build server.

Please reopen if cucumber exits with 0 when there are failing scenarios.
