### ISSUE TITLE
Upgrade cucumber-expressions to 7.0.0

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-js#1188]
A new version of cucumber expressions was recently released. This version isn't used yet in `cucumber-js`.

**Comment by ofirmgr** [comment]
I'm getting "Authentication failed" where I try to publish my brunch.

**Comment by ofirmgr** [comment]
I created a pull request for it. https://github.com/cucumber/cucumber-js/pull/1189

**Comment by ofirmgr** [comment]
Could someone explain me why the travis-CI fails?
I tried to run it without my last commit and it fails too

**Comment by aslakhellesoy** [comment]
What does the error message say? What file does the error stack trace point to? See any errors there?

**Comment by mpkorstanje** [comment]
@aslakhellesoy 

The linter is complaining and I don't see anything wrong there and #1189 doesn't make any changes in that file. So that makes me think the build itself unstable.

**Comment by mpkorstanje** [comment]
Confirmed. Build is unstable. Rebuilding the last commit on master now fails while it previously passed:

https://travis-ci.org/cucumber/cucumber-js/builds/491126714

**Comment by ofirmgr** [comment]
Did the build fix?
Do i need to recreate a new pull request?

**Comment by mpkorstanje** [comment]
Looks like it. If you `git fetch`, followed by `git rebase origin/master` and force push that it should start a new build.

**Comment by charlierudolph** [comment]
Closed in 7dc2eff534716f1a86452e1c694ee2133bc065ef
