### ISSUE TITLE
Fix unstable build

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1190]
See details in #1188

**Comment by tooky** [comment]
I had a quick look at this.

The problem is in the `lint-dependencies` step.

I suspect there has been a change between `@babel/core` v7.2.2 and v7.2.3 and how `dependency-linter` uses the transpiler.

**Comment by tooky** [comment]
I think the babel/core version might be a red herring.

**Comment by tooky** [comment]
The build is failing on node 6.

**Comment by aslakhellesoy** [comment]
Node 6 reaches end of life on [30th April 2019](https://nodejs.org/en/about/releases/).

It's time for us to stop supporting it.
