### ISSUE TITLE
Adding a step or scenario name to a screenshot using Cucumber

### ISSUE THREAD

**Issue by zac11** [cucumber/cucumber-js#1191]
This is not a bug , rather than a question or a feature request.

I am using Cucumber with Protractor with Typescript ( I am using the framework provided by Ram Pasala here)

I have a lot of scenarios in my framework, and I taking a lot of screenshots is saved to a default `screenshots` folder. These screenshots used by the PTL/PM sometimes.

Since there are a lot of screenshots, I would like the screenshots are appended with the scenario name or step name with  the screenshot.

Let's say 

```
Scenario: Opening a webpage and validating an element
                   Given ABC opens a webpage
                   When ABC waits for page to load
                   Then x element is displayed on page
```

I'm taking screenshots in the `When` and `Then` steps.   I want to add screenshots which have name like `ABC waits for page to load_Step_Timestamp` ( for eg - `ABC waits for page to load_Step_2016-01-16T16:00:00`)

I have gone through this issue already posted - https://github.com/cucumber/cucumber-js/issues/719  but I couldn't understand the steps and I don't see any solution provided yet.

So, 

- Is there a way that this can be achieved.

**Comment by Izhaki** [comment]
```js
Before(function(scenario) {
  // Store scenario name on context.
  // We need this for auto-named snapshots.
  this.scenarioName = scenario.pickle.name;
});
```

This will allow you to access `this.scenarioName` within any step definition (note for `this` to work you shouldn't use arrow functions).

As for step name, I don't think there's a way to do it, just copy the string from the step definition.
