### ISSUE TITLE
Always retun true for cucumber datatable in typescript

### ISSUE THREAD

**Issue by vijayaragavang** [cucumber/cucumber-js#1194]
Following step definition always return true even for wrong data from dataTable. Could you help me to correct the syntax in typescript with chai assertions.

Then(/^Verify the following details in report$/, async (table: TableDefinition) => {

        table.rows().forEach(row => {
            return expect(homepage.getDamagedPartyName()).to.eventually.equal(row[0]);

        });
 
});

**Comment by Izhaki** [comment]
This is not an issue with cucumber.

Please use StackOverflow for these sort of questions.

But my guess is this:

```
expect(homepage.getDamagedPartyName()).to.eventually.equal(row[0])
```

per the [docs](https://github.com/domenic/chai-as-promised) returns a promise that is either resolved or rejected.

Now this:

```
    table.rows().forEach(row => {
        return expect(homepage.getDamagedPartyName()).to.eventually.equal(row[0]);

    });
```

Pretty much does nothing, you just return a promise and do nothing with it.

You probably need something like this instead:

```
    // promises will be an array of promises.
    const promises = table.rows().map(row => 
        expect(homepage.getDamagedPartyName()).to.eventually.equal(row[0]);
    );
    // Promise.all will be rejected if any of the promises is rejected.
    return Promise.all(promises);
```
