### ISSUE TITLE
cli trying to load files it's not supposed to

### ISSUE THREAD

**Issue by worc** [cucumber/cucumber-js#1199]
i'm trying to generate a step definitions file by using the CLI on a feature file. but when i run the command against the feature file, the CLI tries to load in a bunch of completely unrelated files and then fails when it tries to load files it was never told to load :/

for example, if i have a demo feature located somewhere like `/project/test/demo.feature` and i try to run the cli against that file to make it generate step definitions, the cli errors because it tries to load files located "nearby" at `/project/test/integration_tests/unrelated_test_written_with_es6_modules.js`.

so... what? why does this happen? and can it be stopped?

**Comment by rayk47** [comment]
You need to provide the command you are running and sample setup of your project.

**Comment by charlierudolph** [comment]
The logic for what files are automatically required lives [here](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#requiring-support-files)

**Comment by worc** [comment]
is this really closed? @charlierudolph  didn't answer either of my questions

**Comment by rayk47** [comment]
@worc He answered based on the information provided and pointed you to docs that show you how to declare what files should be used

**Comment by tooky** [comment]
@worc we try to keep the GitHub issues for bug reports / feature requests. Things that the team will actively work on.

For help with using Cucumber we have a couple of different support channels over here:

https://cucumber.io/support

By far the most active is the slack channel: https://cucumber.io/support#slack.
