### ISSUE TITLE
Lost stdout output when executed through child_process.spawn

### ISSUE THREAD

**Issue by simondean** [cucumber/cucumber-js#120]
Hi.  I'm writing a node module for executing cucumber-js features across multiple processes and multiple machines.  I've hit an issue when executing cucumber-js via child_proces.spawn.  5-15% of the time, cucumber-js exits without outputting anything to stdout (normally I'm using the JSON formatter).  

You can see the bug by running the following code (spawn_cucumber.js): 

```javascript
var ChildProcess = require('child_process');

var count = 1000;
var finishCount = 0;
var failCount = 0;

function test() {
  var child = ChildProcess.spawn('node', ['node_modules/cucumber/bin/cucumber.js', 'features'], {
    cwd: '.',
    stdio: ['ignore', 'pipe', process.stderr],
    env: process.env
  });

  var stdoutData = [];
  
  child.stdout.on('data', function(data) {
    stdoutData.push(data);
  });

  child.on('exit', function(code, signal) {
  });

  child.on('close', function(code, signal) {
    finishCount++;
    
    if (stdoutData.length == 0) {
      failCount++;
    }
    
    if (finishCount < count) {
      test();
    }
    else {
      console.log('Flush succeeded ' + (count - failCount) + ' times');
      console.log('Flush failed ' + failCount + ' times');
      console.log('Flush failed ' + (failCount / count * 100) + '% of the time');
    }
  });

  child.on('disconnect', function() {
    console.log('disconnect');
  });
}

test();
```

There's also a copy of the above code here: git://github.com/simondean/node-spawn-lost-output-bug.git

Here's some example ouput:

```shell
>node spawn_cucumber.js
Flush succeeded 929 times
Flush failed 71 times
Flush failed 7.1% of the time
```

The issue is in bin/cucumber.js: 

```javascript
  var code = succeeded ? 0 : 1;
  var exitFunction = function() {
    process.exit(code);
  };

  // --- exit after waiting for all pending output ---
  var waitingIO = false;
  process.stdout.on('drain', function() {
    if (waitingIO) {
      // the kernel buffer is now empty
      exitFunction();
    }
  });
  if (process.stdout.write("")) {
    // no buffer left, exit now:
    exitFunction();
  } else {
    // write() returned false, kernel buffer is not empty yet...
    waitingIO = true;
  }
```

If the above is replaced with the following it fixes the issue:

```javascript
  var code = succeeded ? 0 : 1;
  
  process.on('exit', function() {
    process.exit(code);
  });
```

Thanks
Simon

**Comment by zs-zs** [comment]
I also think that this 60 second exit timeout is very annoying, especially if you cannot tell what causes your resource leak.
Just for curiosity, why did you decide to use a timeout at all? You could simply call `process.exit(code)` without any timeout.
I mean by not subscribing to process exit as it was originally, but calling the `process.exit();` right from the CucumberJS CLI's finished callback.

Or this would trace back to the original stdout lost issue?

**Comment by simondean** [comment]
@zs-zs node.js does not finish processing the event loop or flush any output to STDOUT or STDERR when you call process.exit();

I can't remember whether this is a Windows specific issue or affects other OSs too

See https://github.com/joyent/node/issues/3737 for more info

**Comment by jbpros** [comment]
@zs-zs The timeout seemed to be the best compromise, I'm not so sure anymore as it made Cucumber responsible for user land leaked resource management and that arbitrary timeout is indeed annoying.

I've reverted back to a non-timeout approach on [master](https://github.com/cucumber/cucumber-js/commit/23ff8608417b542c8c775c2ac5914e232b8c5dfa). @simondean @zs-zs @kAworu please give it a try and tell us if it awakes old demons.

@simondean I've used your flush test script against that new code:

```
arwen:tmp jbpros$ time node flush-test.js 
Run #1000
Flush succeeded 1000 times
Flush failed 0 times (0%)

real	5m33.214s
user	5m4.271s
sys	0m34.389s
```

**Comment by kAworu** [comment]
hi @jbpros,

I've tested master using `npm install cucumber/cucumber-js` and everything is running fine here.

As far as I can see 23ff8608417b542c8c775c2ac5914e232b8c5dfa solved the timeout issue we have in some projects where it's hard to know what ressources is leaking and/or which library.

**Comment by jbpros** [comment]
Thanks @kAworu. That's one happy person, right.

Who's next? :)

**Comment by charlierudolph** [comment]
Closing as this issue moves through a few different solutions that span over a couple years. If you are still experiencing this issue with the latest versions, please open a new issue
