### ISSUE TITLE
It can't see scenarios on console log

### ISSUE THREAD

**Issue by DiogoMiranda** [cucumber/cucumber-js#1201]
Hello, I have a problem in my console log on terminal when I run my JS Cucumber project. The problem is it only show a greens dots, and I don't see the outputs (scenarios). Can you help me ?
Thanks.

Informations:
cucumberOpts: {
   require: ‘../features/step_definitions/*.js’,
   require: ‘../features/support/*.js’,
   format: [‘json:results.json’],
   profile: false,
   ‘no-source’: true
 },

conf.js 

{
 “name”: “protractor_project”,
 “version”: “1.0.0",
 “description”: “”,
 “devDependencies”: {
   “chai”: “^4.2.0”,
   “chai-as-promised”: “^7.1.1”,
   “cucumber”: “^5.1.0”,
   “cucumber-html-reporter”: “^4.0.4”,
   “eslint”: “^5.14.1”,
   “feature-express”: “^0.4.13”,
   “protractor”: “^5.4.2”,
   “protractor-cucumber-framework”: “^6.1.1”,
   “protractor-cucumber-steps”: “^1.3.2”
 },

<img width="948" alt="print1" src="https://user-images.githubusercontent.com/13684104/57167505-649cc200-6dd4-11e9-8de7-b84e9535a722.png">

**Comment by Izhaki** [comment]
https://www.npmjs.com/package/cucumber-pretty

**Comment by DiogoMiranda** [comment]
Thanks @Izhaki , I am go to verify.
