### ISSUE TITLE
Allow us to configure process arguments for parallel instances

### ISSUE THREAD

**Issue by Aaron-Pool** [cucumber/cucumber-js#1203]
I'm using [ESM](https://github.com/standard-things/esm) to avoid the hassle of babel transpilation and such. All I have to do is run the cucumber bin with `node -r esm` and everything works magically like a charm 👌 

_But_, when I enable parallel mode, everything breaks, because the parallel instances have not been spawned with the same argument. Is there any way I can configure this?

**Comment by Izhaki** [comment]
Urm... ESM is [just a wrapper for babel](https://github.com/standard-things/esm/blob/master/package.json#L36).

You could use @babel/register instead (it won't transpile anything, and to be frank it's 2 minutes to get it working so seriously doubt if the extra dependency on ESM worth it):

```
npm install @babel/core @babel/register --save-dev
```

You *might* also need [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env)

Then per [these instructions](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#simple-es6-support) just call cucumber with `--require-module @babel/register`?

Which makes me thing that instead of `node -r esm` run cucumber with `--require-module esm`. It *might* work.

**Comment by Aaron-Pool** [comment]
@Izhaki  I'm not sure what gives you that impression, and I don't think it's correct. Just because he uses `babel` to build his distributable doesn't mean it's just a wrapper around babel. If you peruse the source, you'll see that isn't the case at all (unless I'm just completely mistaken). [ESM is even proposed as an alternative to babel](https://dev.to/bennypowers/you-should-be-using-esm-kn3), and jdalton, the creator of ESM (and lodash, just in case that lends him extra credibility) specifically summarizes ESM as "The brilliantly simple, babel-less, bundle-less ECMAScript module loader."

Anyways, not trying to argue, just defending the assertion that `ESM` and `babel` are two different approaches.

The reason I initially abandoned Babel is because transpilation doesn't play well with [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#code-transpilation-issues), and I had a difficult time getting babel to just _stop_ transpiling things.  I believe I tried the `--require-module` approach as well, but I'll fiddle with it some more.

**Comment by Izhaki** [comment]
> and I don't think it's correct.

You're right! I was jumping to conclusions there.

Any luck with `--require-module`?

**Comment by Aaron-Pool** [comment]
@Izhaki Haven't had time to mess with it just yet. Right now priority #1 for my team was just getting our BDD testing tools running, not necessarily to optimize them. But I'll try to get around to experimenting with `--require-module` sometime in the next few days. Thanks for the suggestion!

**Comment by Aaron-Pool** [comment]
@Izhaki 

Ok, so I gave that a shot, and something still isn't working, but it wasn't what I was expecting.

Here's the command I'm running:

`cucumber-js --require-module esm --require setup/aliases.js --require 'features/**/*.js' --format json:output/cucumber_report.json`

And the result is that it doesn't find any of my features. I _think_ the imports and esm stuff it working. But it's difficult to tell, because for some reason my feature glob doesn't seem to be working.

**Comment by Izhaki** [comment]
> it doesn't find any of my features

That would normally give you:

```
0 scenarios
0 steps
```

> I get a ton of "not implemented" warnings

That means it finds the features but not the step definitions?

The two are conflicting, can you elaborate on the issue.

---

Shot in the dark, can you try:

```
cucumber-js --require-module esm --require setup/aliases.js --require 'features/**/*.js' --format json:output/cucumber_report.json features/**/*.features
```

**Comment by Aaron-Pool** [comment]
Oh, yeah, my bad. Yes, it's the implementation it's not finding. It is finding the feature file fine, it seems.

**Comment by Izhaki** [comment]
Not really sure how I can help further. 

Can you share a sample repo?

What happens if you put `console.log('whatever')` in `setup/aliases.js` (as the first line)? Do you see it?

**Comment by Aaron-Pool** [comment]
@Izhaki So, I fixed that issue, interestingly, it was the single quotes that was breaking the glob require. Looking over the docs, it looks like they're fairly inconsistent with their usage of quotes or no quotes on the glob. The "Requiring support files" doesn't use them, but all other references to a glob pattern with the `--require` flag _do_ use them. Might want to remove those. Or, if they're necessary in some shells, but not others, add a not about it?

In any case, it didn't fix my original issue. We're back where we started, which is that the slave processes don't _seem_ to be affected by the masters cli parameters.

Also, btw, thanks for your quick responses. I really appreciate the help 👍

**Comment by Izhaki** [comment]
> In any case, it didn't fix my original issue.

In this case, I'll do some digging...

**Comment by Aaron-Pool** [comment]
Appreciate it! Would a repro repo still help? I can set one up.

**Comment by Izhaki** [comment]
Thanks for offering, but it should be rather easy to reproduce.

**Comment by Izhaki** [comment]
Right then,

So I did a quick check, and it looks like this is actually supported: 

https://github.com/cucumber/cucumber-js/blob/31e51ff0a99c274151f8ef91ee96ff6d981b7ec5/src/runtime/parallel/slave.js#L54

I've also disable the auto insertion of @babel-register in the tests:

https://github.com/cucumber/cucumber-js/blob/31e51ff0a99c274151f8ef91ee96ff6d981b7ec5/features/support/hooks.js#L27-L28

made sure this test fails:

https://github.com/cucumber/cucumber-js/blob/31e51ff0a99c274151f8ef91ee96ff6d981b7ec5/features/parallel.feature#L24

then added `--require-module @babel/register` to the line above and it passes.

---

I will need a repo to investigate further.

**Comment by Aaron-Pool** [comment]
@Izhaki I apologize this took  me so long to setup. I got distracted.

[Here's](https://github.com/Aaron-Pool/cukeRepro) a minimal repro though!

**Comment by Aaron-Pool** [comment]
@Izhaki had any time to look at this? Obviously understand if you haven't, given that I took 12 days to make a reproduction repo, but just wanted to ping you to make sure it hadn't gotten lost in the clutter.

**Comment by Kieran91** [comment]
I'm also seeing this issue when passing `--require-module esm`. I'm happy to provide for info if needed.

**Comment by Kieran91** [comment]
I've replicated the issue using the steps below. I didn't pass the `--parralel <number>` flag in either of the two scenarios so maybe this issue has something to do with having one test runner executing another child test runner?

### Steps:
1. Checkout master and install:
    ```bash
    yarn install
    npm install @babel/core@latest --save          
    npm install @babel/preset-env --save
    npm install @babel/register@latest --save
    npm install esm --save
    npm install
    ```

2. Add the file:
    ```javascript
    // babel.config.js
    const presets = [
    [
        '@babel/env',
        {
        targets: {
            node: true,
        },
        },
    ],
    ]
    module.exports = { presets }

    ```

3. Add the feature file:
    ```gherkin
    # features/require_module_slave.feature
    Feature: Running slaves with required modules

    @debug
    Scenario: a slave test runner can use the esm required module 
        Given a file named "features/step_definitions/cucumber_steps_es6.js" with:
        """
        import {Given} from 'cucumber';
        import Promise from 'bluebird';

        Given(/^an es6 step$/, function(callback) {
            setTimeout(callback, 1000)
        })
        """
        And a file named "features/a.feature" with:
        """
        Feature: slow
            Scenario: b
            Given an es6 step
        """
        When I run cucumber-js with `--require-module esm`
        Then it passes

    @debug
    Scenario: a slave test runner can use the babel required module 
        Given a file named "features/step_definitions/cucumber_steps_es6.js" with:
        """
        import {Given} from 'cucumber';
        import Promise from 'bluebird';

        Given(/^an es6 step$/, function(callback) {
            setTimeout(callback, 1000)
        })
        """
        And a file named "features/a.feature" with:
        """
        Feature: slow
            Scenario: b
            Given an es6 step
        """
        When I run cucumber-js with `--require-module @babel/register`
        Then it passes

    ```
4. Run the tests:
   ```bash
   bin/cucumber-js -t @debug
   ```

### Expected Result
Both tests pass.
```javascript
➜  cucumber-js git:(master) ✗ bin/cucumber-js -t @debug
1/8 steps [========                                                          ].

1 scenario (1 passed)
1 step (1 passed)
0m01.008s

3/8 steps [=========================                                         ].

1 scenario (1 passed)
1 step (1 passed)
0m01.005s

2 scenarios (2 passed)
8 steps (8 passed)
0m02.065s
```



### Actual Result
The esm scenario fails.
The babel scenario passes.
```javascript
➜  cucumber-js git:(master) ✗ bin/cucumber-js -t @debug
1/8 steps [=============                                                                                         ]/Users/kieran/Documents/temp/cucumber-js/tmp/require_module_slave.feature_4/features/step_definitions/cucumber_steps_es6.js:1
(function (exports, require, module, __filename, __dirname) { import {Given} from 'cucumber';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:84:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
    at Module._compile (internal/modules/cjs/loader.js:693:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
1) Scenario: a slave test runner can use the esm required module # features/require_module_slave.feature:4
   ✔ Before # features/support/hooks.ts:14
   ✔ Before # features/support/hooks.ts:22
   ✔ Given a file named "features/step_definitions/cucumber_steps_es6.js" with: # features/step_definitions/file_steps.ts:10
       """
       import {Given} from 'cucumber';
       import Promise from 'bluebird';

       Given(/^an es6 step$/, function(callback) {
         setTimeout(callback, 1000)
       })
       """
   ✔ And a file named "features/a.feature" with: # features/step_definitions/file_steps.ts:10
       """
       Feature: slow
         Scenario: b
           Given an es6 step
       """
   ✔ When I run cucumber-js with `--require-module esm` # features/step_definitions/cli_steps.ts:13
   ✔ Then it passes # features/step_definitions/cli_steps.ts:50
   ✖ After # features/support/hooks.ts:83
       Error: Last run errored unexpectedly. Output:



       Error Output:

       /Users/kieran/Documents/temp/cucumber-js/tmp/require_module_slave.feature_4/features/step_definitions/cucumber_steps_es6.js:1
       (function (exports, require, module, __filename, __dirname) { import {Given} from 'cucumber';
                                                                            ^

       SyntaxError: Unexpected token {
           at new Script (vm.js:84:7)
           at createScript (vm.js:265:10)
           at Object.runInThisContext (vm.js:313:10)
           at Module._compile (internal/modules/cjs/loader.js:693:26)
           at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
           at Module.load (internal/modules/cjs/loader.js:628:32)
           at Function.Module._load (internal/modules/cjs/loader.js:555:12)
           at Module.require (internal/modules/cjs/loader.js:666:19)
           at require (internal/modules/cjs/helpers.js:16:16)
           at World.<anonymous> (/Users/kieran/Documents/temp/cucumber-js/features/support/hooks.ts:89:11)


5/8 steps [================================================================                                      ].

1 scenario (1 passed)
1 step (1 passed)
0m01.003s

2 scenarios (1 failed, 1 passed)
8 steps (8 passed)
1m40.125s
➜  cucumber-js git:(master) ✗ 
```

Hopefully someone smarter than me can take a look and figure out what exactly is going on here cos right now I'm stumped.

**Comment by charlierudolph** [comment]
Well, I went down a rabbit hole trying to understand `esm` and have so many questions. In the end, I thought the best thing would be if we had some way of passing through the node options specified. 

Turns out with the release of v6, I had switched how we start the slave from spawn to fork (which starts a node subprocess passing down the options). Thus if you upgrade to v6, you can use `node -r esm <path-to-cucumber>` and if you use parallel it still works.

**Comment by TillaTheHun0** [comment]
For anyone visiting this for Cucumber v7.

As of Cucumber v7, I was able to run `cucumber-js --require-module esm --require 'test/specifications/**/*.js' test/specifications/**/*.feature` and successfully execute my tests. 👍

**Comment by TillaTheHun0** [comment]
For anyone visiting this for Cucumber v7.

As of Cucumber v7, I was able to run cucumber-js --require-module esm --require 'test/specifications/**/*.js' test/specifications/**/*.feature and successfully execute my tests. 👍

`@cucumber/cucumber@7.0.0-rc.0`
`esm@3.2.25`
