### ISSUE TITLE
Allow users to send any argument using CLI

### ISSUE THREAD

**Issue by ranjprashant** [cucumber/cucumber-js#1206]
Right now only given options we can pass from CLI
-v, --version
-b, --backtrace
-d, --dry-run
--exit  
--fail-fast
-f, --format <TYPE[:PATH]>
--format-options <JSON>
--i18n-keywords <ISO 639-1>
--i18n-languages
--language <ISO 639-1>
--name <REGEXP> 
--no-strict 
--order <TYPE[:SEED]>
-p, --profile <NAME>
--parallel <NUMBER_OF_SLAVES>
-r, --require <GLOB|DIR|FILE>
--require-module <NODE_MODULE>
--world-parameters

It would be great if you reserve above options for cucumber only and allow user to send their own options ex (--environment, --operatingSysytem,, --browserVersion).
With current version of cucumber  getting error if executing command as
### **node cucumber.js --opratingSystem Windows10**
Error is error: unknown option `--opratingSystem'

It should not through any error like above

**Comment by charlierudolph** [comment]
What is the use case for needing those options? What would they be used for?

**Comment by troddyn** [comment]
It seems like using environment variables would be a better solution than allowing arbitrary CLI arguments. It would look like:

`OS=win10 ./cucumber-js features`

You can reference them in your tests like any other envvar:

`let operatingSystem = process.env.OS || defaultValue`

**Comment by Izhaki** [comment]
Programs can only handle arguments they expect and are meaningful to them. There is schema checks, validity checks etc. that the program needs to perform and it can only do so for its own arguments.

If you need to pass on arguments to the process being tests, either configure it explicitly in your tests, or use ENVIRONMENT variables.

That's how its done everywhere else.
