### ISSUE TITLE
Can we use with Mocha framework

### ISSUE THREAD

**Issue by schavaLogi** [cucumber/cucumber-js#1207]
Is there any way we can use with the mocha framework so that we can avoid complete re-write of existed test cases

**Comment by Izhaki** [comment]
The short answer is *no*.

Mocha is a test runner, and so is this project.

In cucumber there's a separation between the specs (everyday language used to describe how the system should behave) and the tests (executable code to ensure the specs are met). Whereas in Mocha the two are fused together in the form `it(spec, test)`.

Cucumber uses explicit Given/When/Then, where as in mocha the setup code (pre-condition), trigger condition, and post condition assertion are typically all part of the same code block.

Mocha is good for low level (implementation) testing where a Gherkin syntax will end up very implementation oriented - think of how would you go about stubbing a function, or even express calling a function in gherkin ("When the function 'X' is called"?).
Cucumber is good for high level behaviour testing - so the specs hardly reveal any implementation details.
This is not to say that one cannot be replaced by another - it's just there are two aspects of testing here and often one lends itself better than the other.

Anyhow, not an issue but a question so closing.
