### ISSUE TITLE
Is it possible to put the count for Manual test case inside scenarios tiles on the html report.

### ISSUE THREAD

**Issue by chnmdey1** [cucumber/cucumber-js#1208]
Describe your question with as much detail as possible
I want to post the count for manual test cases separately inside Scenario tiles. Currently, every test cases which are unable have an output is considered as skipped. My feature files contains certain features which I cannot automate. I want to put that count as under separate entity inside the tile Scenarios in our report.

I am aware I will be able to do that by modifying the created html by appending inside it. But, is it possible to do it before hand, so that we can get the count once we produce index.html

<img width="941" alt="Capture" src="https://user-images.githubusercontent.com/24960824/60175078-264ddd00-9830-11e9-8697-ad428522f983.PNG">

Environment (please complete the following information):

multiple-cucumber-html-reporter: 1.11.6
Node.js version: 10.15.3
NPM version: 6.4.1
Cucucmber version: 5.1.0

**Comment by chnmdey1** [comment]
This is possible in BDD Serenity report, by just adding a tag ----- @Manual on the manual scenarios. Can we do the same in this report too?

**Comment by charlierudolph** [comment]
It appears your issue should be opened here: https://github.com/wswebcreation/multiple-cucumber-html-reporter#readme

This repo is for cucumber-js only and not multiple-cucumber-html-reporter which is a different library that integrates with cucumber-js
