### ISSUE TITLE
An env variable that contains the path to the scenario that is being run?

### ISSUE THREAD

**Issue by CharlesW513** [cucumber/cucumber-js#1212]
I can't seem to find any environment variables that specify the path / uri of the scenario that is being run during the parallel test execution. Does this exist?

**Comment by charlierudolph** [comment]
No. Regardless of parallel / sequential you could access the current scenario as the argument passed to the before / after hook: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md. Again, please use the support forums for questions.
