### ISSUE TITLE
Multiple step definitions match Error

### ISSUE THREAD

**Issue by ramaaneel** [cucumber/cucumber-js#1218]
Hello,

I am having one feature file which is having a same step definition string text. During execution I got an error 
Multiple step definitions match:
         I'm on {string} - test\spec\amazon_spec.js:46
         I'm on {string} - test\spec\amazon_spec.js:86

I already worked on jasmine framework & it's handling this kind of things. So the same thing (Step with same name) possible here in cucumberjs?
![feature](https://user-images.githubusercontent.com/43242193/61704142-b7956e00-ad60-11e9-9098-603dc337e645.png)
![error](https://user-images.githubusercontent.com/43242193/61704149-bcf2b880-ad60-11e9-9017-2e10b416cb1d.png)

**Comment by Carmot** [comment]
No it isn't here in cucumberjs, you have to make them different in some way in order to differentiate them otherwise you'll get this error message. The same happened to me in the past when adding my own step and it was already defined.

**Comment by ramaaneel** [comment]
Ok mate. Thank you for the update. Cheers
