### ISSUE TITLE
Any way to get a list of all features and scenarios?

### ISSUE THREAD

**Issue by sebastianqdot** [cucumber/cucumber-js#1220]
I'm resorting to this channel as I'm not able to log in through slack (endless spinner when trying to connect to cucumber's slack)

Is there any way to get a nested list (or at least a list) of all features/scenarios and then pipe it into another process. Say, run `cucumber-js --get-scenarios` and that will return a JSON with the expected results.

I've tried with `--dry-run` but it's failing, I'm also not sure if that will suffice. Any ideas?

Sorry for using this channel for support purposes, but I can't seem to reach Slack. Cheers.

**Comment by rayk47** [comment]
Yes. Take a look at the helpers https://github.com/cucumber/cucumber-js/blob/master/src/cli/helpers.js I'm thinking getTestCasesFromFilesystem is what you are looking for.

**Comment by sebastianqdot** [comment]
> Yes. Take a look at the helpers https://github.com/cucumber/cucumber-js/blob/master/src/cli/helpers.js I'm thinking getTestCasesFromFilesystem is what you are looking for.

Quite a life saver, thanks!
