### ISSUE TITLE
defineParameterType fails with internal error

### ISSUE THREAD

**Issue by oshnix** [cucumber/cucumber-js#1221]
## Description
I am trying to use `defineParameterType` in my project with typescript and cypress-cucumber. It is being declared just before steps definition. However, I get the following error:

```
 this.options.parameterTypeRegistry.defineParameterType(parameterType);
                 ^

TypeError: Cannot read property 'parameterTypeRegistry' of undefined
    at SupportCodeLibraryBuilder.defineParameterType
``` 
I am able to reproduce it on a number of last versions and even with the simplest project and using defineSupportCode too.

## Steps to reproduce
* Create new project
* run `npm install cucumber`
* Create some js file: 
```
const { defineParameterType } = require('cucumber');

defineParameterType({
        name: 'customParam',
        regexp: /.*/,
        transformer: s => s.toString()
});
```
* Run it and get an error

OS: windows, linux
Node: 10, 11, 12
Cucumber version: 5.1.0, 4.2.1

**Comment by charlierudolph** [comment]
Cucumber support files are meant to be loaded by the cucumber CLI and not manually.

That is erroring because this [line](https://github.com/cucumber/cucumber-js/blob/7a5fdcbbb65c1160c5848a8b0aab3e48a31db40b/src/cli/index.js#L72) which gets called as part of the CLI execution has not been run.

How are you trying to execute your test suite?

**Comment by oshnix** [comment]
I am using [parser for cypress](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) and trying to call `defineParameterType` before definition of steps like given, when and then.
I do understand that the problem occurs somewhere in this library or it's just me calling this function from the unappropriate place. I am going to move my definitions and try one more time.
