### ISSUE TITLE
Cucumber + Babel = Syntax Error

### ISSUE THREAD

**Issue by fragsalat** [cucumber/cucumber-js#1222]
Hey there,

I've tried to use cucumber with babel 7 but were not successful. 
The command I've used (based from the docs and google) requires the module @babel/register but that seem to have not the effect I intended.
```
./node_modules/.bin/cucumber-js --require-module="@babel/register"  src/test/bdd
```

My application is for sure written in modern javascript and my tests as well. Like described in the docs I'm importing After, Before, Given etc from the cucumber package. Running it causes this exception:

```
import { After, Before, Given } from 'cucumber';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:694:28)
```

My cucumber version is 5.1.0.

Can you tell me what is the proper setup with cucumber and babel? The docs are not very clear about that.

**Comment by Izhaki** [comment]
What does your `.babelrc` look like?

Mine:
```

**Comment by fragsalat** [comment]
Meh ok looks like that's the issue. **Cucumber seem to require nodejs target** and my babelrc was by default on browsers. Now it seem to bootstrap properly even though I'm getting errors during bootstrap.
Thank you mate and sorry for disturbing :)
