### ISSUE TITLE
Upgrade to cucumber-expressions 8.0.0

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1224]
That should fix https://github.com/cucumber/cucumber/issues/685

**Comment by charlierudolph** [comment]
@aslakhellesoy tested this out and hit an error on node 8: 

<img width="998" alt="Screen Shot 2019-09-02 at 1 33 43 PM" src="https://user-images.githubusercontent.com/1676758/64132670-55c81b00-cd86-11e9-9e52-43a1a1abb26d.png">

No issues on node 10 / 12

**Comment by charlierudolph** [comment]
Going to close this and open an issue in cucumber that we need cucumber-expressions to support node 8
