### ISSUE TITLE
Warning when install cumber@^5.1.0

### ISSUE THREAD

**Issue by dylannnn** [cucumber/cucumber-js#1230]
When I install cucumber, I got these warning below:

[WARNING] npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
[WARNING] npm WARN deprecated package has been deprecated in favor of directly
[WARNING] npm WARN deprecated including core-js/stable (to polyfill ECMAScript
[WARNING] npm WARN deprecated features) and regenerator-runtime/runtime
[WARNING] npm WARN deprecated (needed to use transpiled generator functions):
[WARNING] npm WARN deprecated 
[WARNING] npm WARN deprecated   > import "core-js/stable";
[WARNING] npm WARN deprecated   > import "regenerator-runtime/runtime";

I would like to see no warning when install cucumber.

**Comment by charlierudolph** [comment]
Thanks for reporting.
Appears we can remove @babel/polyfill as its no longer needed for the versions of node we support. Will make a PR to remove it

**Comment by charlierudolph** [comment]
Fixed in c3bbfb5256f21150122105930ae6a6494f41807b. Will close once version 6 is released

**Comment by charlierudolph** [comment]
Just released version 6. Please comment if this isn't resolved after updating
