### ISSUE TITLE
New Feature: sub steps

### ISSUE THREAD

**Issue by fider** [cucumber/cucumber-js#1232]
**Feature description:**
Possibility to define substeps, eg:

**How it is currently:**
```js
// stepDefinition.ts
Then(/"(.*?)" register step 1/, ... );
Then(/"(.*?)" register step 2/, ... );
Then(/"(.*?)" register step 3/, ... );
// If I would like to group them I have to create new step and copy/paste implementation.
```
```js
// A.feature
Then "device_1" register step 1
Then "device_1" register step 2
Then "device_1" register step 3
```
```js
// B.feature
Then "device_2" register step 1
Then "device_2" register step 2
Then "device_2" register step 3
```

**How it may looks like:** 
```js
// stepDefinition.ts
const registerStep1 = Then(/"(.*?)" register step 1/, ... );
const registerStep2 = Then(/"(.*?)" register step 1/, ... );
const registerStep3 = Then(/"(.*?)" register step 1/, ... );
Then(/"(.*?)" complete register/, async (deviceName) => {
  return [registerStep1(deviceName) , registerStep2(deviceName) , registerStep3(deviceName) ]
});
```
```js
// A.feature
Then "device_1" complete register
```
```js
// B.feature
Then "device_2" complete register
```
We can also resue substeps in feature files
```js
// C.feature
Then "device_3" register step 3
// ...
Then "device_3" register step 1
```

**Example html report:**
Each step that contains substeps can contain folding/unfolding button (just like featrue and scenario).
![image](https://user-images.githubusercontent.com/1457742/65326406-aaa2c880-dbb1-11e9-8ab0-5d1dcf6314b3.png)

**Why this feature is important:**
- Wrapping cucumber steps into other steps allows me to keep granulation in test steps, reuse code and save a lot of time (eg. let's assume that I just added new steps to "complete register" sequence - I have to update it only in one place instead of 2 or even 50).
- Without this functionality writing code using cucumber is like programming in language that do not allows you to nest functions calls.
- I am aware of fact that I can wrap code of "step 1", "2" and "3" into "register complete" but then I will not be able to use each step as standalone fragment of code. Putting whole code into single step limits functionality and make reports less clear.

**Comment by marnen** [comment]
If I had to do something like this in cucumber-ruby, I might use the `steps` method, which allows running arbitrary Gherkin:

```ruby
Given 'complex step' do
  steps "step one\nstep two\nstep three"
end
```

I assume cucumber-js has something similar (but I can’t find the full API docs to confirm). Will that do the trick for you?

**Comment by aslakhellesoy** [comment]
This used to be implemented in Cucumber-JVM, and we removed it. We'll remove it from cucumber-ruby too. We will not be adding it to Cucumber-js.

All programming languages have a built-in mechanism for reusing code - _methods_ or _functions_. We should use this mechanism rather than inventing our own. Methods/functions have good stack traces (a homegrown solution does not). Methods/functions can be refactored with standard refactoring tools (a homegrown solution can not). Your editor/IDE can detect errors in bad function calls. It cannot do that for a homegrown "call steps" API.

Here is what you can do instead:

```javascript
Given('complex step', function() {
  stepOne()
  stepTwo()
  stepThree()
})

Given('step one', function() {
  stepOne()
})

Given('step two', function() {
  stepTwo()
})

Given('step three', function() {
  stepThree()
})

function stepOne() {
}

function stepTwo() {
}

function stepThree() {
}
```
