### ISSUE TITLE
Regular Expression/recursive wildcard /** in Step definition path not working

### ISSUE THREAD

**Issue by rajeshwarp** [cucumber/cucumber-js#1235]
Greetings !

We are using serenity-js 2.0 which uses  Cucumber as one of the dependencies.  /** is not resolved when used in path to step_definitions. 

Wondering if its an issues with Cucumber-JS  or we are missing something.  
We are using "cucumber": "^1.3.3" as dependency. 

Switched to this version as latest version was not generating Unimplemented Steps Definitions structure for us. Any directions in this regard would help.

**Details**:

The protractor.conf.js uses cucumberOptions like this:

cucumberOpts: {    
   require: [
     "features/step_definitions/**/*.ts",
     "core/common-util/hooks.ts",
     "core/persona.ts",
     "core/stage.ts",
   ],
   format: 'pretty',               // enable console output
   compiler: 'ts:ts-node/register'   // interpret step definitions as TypeScript
 },

dependencies :

"devDependencies": {
    "@types/chai": "^4.2.2",
    "@types/chai-as-promised": "^7.1.2",
    "@types/cucumber": "^4.0.7",
    "@types/node": "^11.13.20",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "chai-smoothie": "^0.3.2",
    _"cucumber": "^1.3.3",_
    "protractor": "^5.4.2",
    "ts-node": "^8.4.1",
    "typedoc": "^0.14.2",
    "typescript": "^3.6.3"
  },
  "dependencies": {
    "@serenity-js/assertions": "^2.0.1-alpha.81",
    "@serenity-js/core": "^2.0.1-alpha.81",
    "@serenity-js/cucumber": "^2.0.1-alpha.81",
    "@serenity-js/protractor": "^2.0.1-alpha.81",
    "@serenity-js/serenity-bdd": "^2.0.1-alpha.81",
    "@types/chromedriver": "^2.38.0",
    "@serenity-js/rest": "2.0.1-alpha.83",
    "axios": "^0.18.0",
    "chromedriver": "^77.0.0",
    "cpx": "^1.5.0",
    "express": "^4.16.4",
    "inversify": "^5.0.1",
    "merge": "^1.2.1",
    "msnodesqlv8": "^0.7.3",
    "mssql": "^5.1.0",
    "node-rsa": "^1.0.5",
    "npmrc": "^1.1.1",
    "reflect-metadata": "^0.1.13",
    "sg-protractor-tools": "^1.0.4",
    "tiny-types": "^1.12.1",
    "tslib": "^1.9.3",
    "webdriver": "^5.13.0",
    "npm-failsafe": "0.4.1"
  },

On execution, we learn that it is unable to find the location for step_definition files. The error reads:

[test:acceptance] [16:27:53] E/launcher - Error: Error: ENOENT: no such file or directory, lstat 'C:\gitrepo\WebFX\XXX\features\step_definitions\**'
[test:acceptance]     at Object.realpathSync (fs.js:1454:7)
[test:acceptance]     at Object.expandPathWithExtensions (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\cli\path_expander.js:14:23)
[test:acceptance]     at C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\cli\path_expander.js:8:27
[test:acceptance]     at Array.map (<anonymous>)
[test:acceptance]     at Object.expandPathsWithExtensions (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\cli\path_expander.js:7:31)
[test:acceptance]     at Object.expandPaths (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\cli\support_code_path_expander.js:6:38)
[test:acceptance]     at getSupportCodePaths (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\cli\configuration.js:73:49)
[test:acceptance]     at Object.getSupportCodeLibrary (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\cli\configuration.js:125:30)
[test:acceptance]     at Object.getSupportCodeLibrary (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\runtime.js:44:46)
[test:acceptance]     at Object.start (C:\gitrepo\WebFX\XXX\node_modules\cucumber\lib\cucumber\runtime.js:12:37)
[test:acceptance] [16:27:53] E/launcher - Process exited with error code 100
[test:acceptance] npm ERR! code ELIFECYCLE
[test:acceptance] npm ERR! errno 100
[test:acceptance] npm ERR! xxx-serenityjs-starter-kit@1.0.0 test:acceptance: `protractor ./protractor.conf.js`
[test:acceptance] npm ERR! Exit status 100
[test:acceptance] npm ERR!
[test:acceptance] npm ERR! Failed at the xxx-serenityjs-starter-kit@1.0.0 test:acceptance script.
[test:acceptance] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

P.S: It is able to find the feature files with /** . It also works when file path is an absolute path (without /**)

**Comment by charlierudolph** [comment]
v4.0 had a breaking change around how transpilers work. See the latest documentation [here]( https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#transpilation)

In the future please review the [chagelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) as it documents what breaking changes come with each major version
