### ISSUE TITLE
Release 6.0.0 has invalid entry for "main" in package.json.

### ISSUE THREAD

**Issue by bingnz** [cucumber/cucumber-js#1236]
Greenkeeper has highlighted that the latest release package seems to be invalid (see https://github.com/bingnz/cucumber-teamcity-formatter/pull/50).
In version 6.0.0, the "main" entry points to `./lib/index`, but the "lib" directory no longer exists in the package.

**Comment by charlierudolph** [comment]
Thanks for the report. Had a bad publish locally. Just published 6.0.1 and confirmed it has the lib folder
