### ISSUE TITLE
5->6 migration guide

### ISSUE THREAD

**Issue by oprogramador** [cucumber/cucumber-js#1237]
Could you publish a migration guide explaining how to upgrade `cucumber` from `v5` to `v6`?

My tests passed but I'd like to ensure everything is OK.

**Comment by yasserf** [comment]
There seems to be a big change where previously arguments undefined using a regex would be passed in as undefined but now it's null

Also running install twice breaks due to expressions being a git repo

```
npm ERR! path /node_modules/cucumber-expressions
npm ERR! git /node_modules/cucumber-expressions: Appears to be a git repo or submodule.
npm ERR! git     /node_modules/cucumber-expressions
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by charlierudolph** [comment]
As the [CHANGELOG.md](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) notes, there are very few breaking changes. The main one is dropping support for Node 6 and the others only effect custom parsing of json / event protocol formatters / custom formatters.

**Comment by oprogramador** [comment]
thanks @charlierudolph
