### ISSUE TITLE
Embedding screenshots in JSON and HTML reports

### ISSUE THREAD

**Issue by simondean** [cucumber/cucumber-js#124]
Hi. The Ruby version of cucucmber includes a really useful feature for embedding files in its JSON and HTML reports.  This is especially useful for including browser screenshots in the report (e.g. screenshots taken with Selenium WebDriver when a scenario fails) .  

Here's the page on cukes.info that describes the feature: http://cukes.info/reports.html#embedding_screenshots

Here's the test for the feature in Ruby cucumber: https://github.com/cucumber/cucumber/blob/master/fixtures/json/features/embed.feature

(If it helps) I think this is the test for it in cucumber-jvm: https://github.com/cucumber/cucumber-jvm/blob/master/core/src/test/java/cucumber/runtime/ScenarioResultTest.java

Thanks
Simon

**Comment by mathieujobin** [comment]
Simply because this issue is showing up high on google when I search for cucumber screenshots.

And I had a hardtime finding the updated link that correspond in this issue description

http://cukes.info/reports.html#embedding_screenshots

is now 

https://cucumber.io/docs/reference#screenshots
