### ISSUE TITLE
Restore old JSON format in 6.x

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1244]
The 6.0.0 release is not usable by teams using 3rd party tools to process the output from the JSON formatter.

I'm not sure what was the motivation behind the change, or what exactly changed.

Could we restore the behaviour of the 5.x JSON formatter in 6.1.0?

Ultimately we should drop the native JSON formatter, implement a `protobuf` formatter (like [the one in Cucumber-JVM](https://github.com/cucumber/cucumber-jvm/blob/prep-work-gherkin-8/gherkin8/src/main/java/io/cucumber/core/gherkin8/formatter/ProtobufFormatter.java) slated for 5.x). People who still need JSON can then use the [json-formatter](https://github.com/cucumber/cucumber/tree/master/json-formatter) command line tool for post-processing.

But since this is a bit far away I'd like to restore the old native JSON format first.

**Comment by charlierudolph** [comment]
A lot of changes were made (links to new format are in the changelog). The new version is meant to be essentially a json format for all the protobuf data that can be used to easily generate a pretty format. cucumber-js uses the same code that produces the objects in the json formatter for printing errors in pretty format.

The main reason for the changes was that I didn't see any good way to fit in the retry data into the previous json formatter. Should be easy enough to restore if we say we'll just ignore retry data (and take the final attempt). Given that if we bring it back I want to name it legacy-json as I think the new json should be much more useable.

**Comment by charlierudolph** [comment]
Okay. I'm fine removing the new version but think it will be useful to have a new json formatter down the road so that we can easily get people off the legacy json formatter without making them parse the protobuf formatter output

**Comment by aslakhellesoy** [comment]
People who rely on tools that parse the legacy JSON format will be able to do this:

```
cucumber --format protobuf:cucumber-results.bin
cat cucumber-results.bin | cucumber-json-formatter > cucumber-results.json
```

This way we only need to maintain a single JSON formatter (the Go one). It's already done:
* https://github.com/cucumber/cucumber/tree/master/json-formatter
* https://github.com/cucumber/cucumber/releases/tag/json-formatter%2Fv2.0.0

We just need to implement a `protobuf` formatter.

Do you still think we need a native (JavaScript) JSON formatter inside Cucumber(s)?

**Comment by charlierudolph** [comment]
No, I'm fine with a single json formatter but just think we probably want to have a non-legacy one too.

**Comment by aslakhellesoy** [comment]
What do you mean by non-legacy one?

**Comment by charlierudolph** [comment]
I understand us supporting the old JSON formatter but am curious if its worth building a new one at some point

Done in release 6.0.3.
