### ISSUE TITLE
Scenario result exception is not available in HookScenarioResult

### ISSUE THREAD

**Issue by Phonesis** [cucumber/cucumber-js#1245]
Not sure if this is by design (can't imagine it would be) but the exception for failing Scenarios is not currently available as part of the HookScenarioResult object.

I have tried this:

```
After({ timeout: cucumberTimeOut }, async function(scenario) {
  console.log('error: ' + scenario.result.exception);
});
```

The problem appears to be that the HookScenarioResult object the After hook HookCode object does not have the exception as part of the interface:

```
export interface ScenarioResult {
    duration: number;
    status: Status;
}
```

I have fixed it locally by simply adding it:

```
export interface ScenarioResult {
    duration: number;
    status: Status;
    exception: Error;
}

```
Can this be addressed?

**Comment by charlierudolph** [comment]
Are you saying the issue is with the type definitions? Those don't currently live in this repo

**Comment by Phonesis** [comment]
I see. Well I believe so. The fix seems to be adding  the exception line to the ScenarioResult interface

**Comment by aslakhellesoy** [comment]
How is your apetite for TyopeScript @charlierudolph? I've migrated all the JavaScript code in the cucumber/cucumber monorepo to TypeScript and I really like it. I'd love to port Cucumber.js over too - happy to do the heavy lifting.

**Comment by charlierudolph** [comment]
I was planning on updating cucumber-js to typescript as part of upgrading to the newest gherkin. However, would prefer to have this in first so have first class support for retry: https://github.com/cucumber/cucumber/pull/722 versus managing

**Comment by aslakhellesoy** [comment]
Glad to hear it!

**Comment by davidjgoss** [comment]
@charlierudolph I would be happy to help out with legwork here if you'd like - I've done a couple of migrations to TS recently

**Comment by davidjgoss** [comment]
@Phonesis if you install the latest `@types/cucumber` package from npm you should be all good now

**Comment by Phonesis** [comment]
> @Phonesis if you install the latest `@types/cucumber` package from npm you should be all good now

nice going thanks
