### ISSUE TITLE
Unable to generate report after upgrading to Cucumberjs 6.0.2

### ISSUE THREAD

**Issue by Larry100a** [cucumber/cucumber-js#1246]
Cucumberjs version: 6.0.2
Cucumber-html-reporter version: 5.0.2

I'm currently using this approach to generate html reports after a cucumber test run:

```
const options = {
    theme: "bootstrap",
    jsonFile: "./cucumber-json-report.json",
    output: "./cucumber-html-report.html",
    reportSuiteAsScenarios: true,
    launchReport: true
};
```

This used to work on cucumberjs 5.1.0. But when I upgraded to cucumberjs 6.0.2, the html reports are no longer generated. Is there a workaround?

**Comment by charlierudolph** [comment]
The JSON formatter had breaking changes but those were with reverted with 6.0.3 that was just released. Please try upgrading to that.

**Comment by Larry100a** [comment]
Thanks, that worked
