### ISSUE TITLE
Deprecate JSON formatter

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1249]
The JSON formatter is implemented in cucumber.js, cucumber-ruby and cucumber-jvm. It's become the defacto standard for machine-readable output from Cucumber, but it has several flaws:

* There is no schema for the output, so different platforms implement it inconsistently, causing problems for consumers
* It sometimes causes out of memory problems for large suites
* It does a poor job at representing results for background and scenario outlines
* Results cannot be consumed until Cucumber has finished

We should deprecate this in version 7 and encourage users and tool vendors to migrate to a new `protobuf` formatter outputting [cucumber-messages](https://github.com/cucumber/cucumber/tree/master/messages).

The `protobuf` formatter addresses all of the problems with the `json` formatter:
* There is a strict [schema](https://github.com/cucumber/cucumber/blob/master/cucumber-messages/messages.proto) documented [here](https://github.com/cucumber/cucumber/blob/master/cucumber-messages/messages.md).
* It's a streaming protocol, so large memory consumption is less likely to be a problem
* It separates results from the AST and does a better job at representing results for backgrounds and scenario outlines
* Results can be consumed before Cucumber finishes (useful for slow suites)

See https://github.com/cucumber/cucumber-js/commit/a89eae323fe2b6a76b7af0b42aadce555bf2c093 for more details.

**Comment by RusmanCool** [comment]
@aslakhellesoy "cucumber-messages." link is not working anymore. Also, how will the proposed solution work with a tool like "cucumber-html-reporter"?
