### ISSUE TITLE
Remove JSON formatter

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1250]
As described in #1249 the plan is to deprecate the `json` formatter in version 7. In version 8 we should remove it.

After the removal people can still generate JSON reports with the standalone [json formatter](https://github.com/cucumber/cucumber/tree/master/json-formatter). There are prebuilt [executables](https://github.com/cucumber/cucumber/releases/tag/json-formatter%2Fv2.0.0) that will convert output from the `protobuf` formatter to JSON. This is intended to be used only by people who have to use tools that still only support the old JSON format.

**Comment by gkushang** [comment]
I disagree with this change as it will break a lot of existing modules. I strongly feel cucumber should keep in-built support for JSON formatted as there are lot of existing Report Dashboards, HTML Reporters are dependent on it. 

The link https://github.com/cucumber/cucumber/tree/master/json-formatter is broken.
