### ISSUE TITLE
Retry scenario only if specified exception is thrown

### ISSUE THREAD

**Issue by ghost** [cucumber/cucumber-js#1255]
Cucumber version: 6.0.3

Is there a way to retry a scenario when a specified expection is thrown? Perhaps grabbing the exception from the testCase in after hooks and then triggering a retry. If so how can the exception be grabbed and subsequently how can the retry be triggered?

**Comment by charlierudolph** [comment]
Are you asking for more fine grained control over whether on not a scenario will be retried?
Currently any failure will be retried if a positive `retry` value is passed in, though you can limit which scenarios can be retried the `retryTagFilter`.

**Comment by Mike21002** [comment]
Yes, I was hoping to get more fine grained control and make a retry dependent on whether a specific exception is thrown or not

**Comment by davidjgoss** [comment]
Closing this now, because:

- It's been inactive for a long time
- There are no current plans to implement this particular functionality in the core team
