### ISSUE TITLE
Error: read ECONNRESET after close browser in parallel run

### ISSUE THREAD

**Issue by saladinProcrastinator** [cucumber/cucumber-js#1261]
Hi guys!
I'm using  Nightwatch 1.3.1 with cucumber 6.0.5 and got next error:
ERROR after browser closing in parallel mode after closing the first one.
DELETE /wd/hub/session/37ed4e6afe84c9f8a2a548bcdd5d7171 - ECONNRESET
Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Error while running .sessionAction() protocol action: An unknown error has occurred.

![500](https://user-images.githubusercontent.com/57943849/69734470-b1146a00-1137-11ea-9c9a-9dc939b0be72.jpg)
Can you help me with this case?

Env: 
Env:
Chrome 78.0.3904.108 (Official Build) (64-bit)
Firefox 70.0.1 (64-bit)

Windows 10
Linux 16.04
node v12.13.0

**Comment by charlierudolph** [comment]
This seems like an issue with nightwatch and nothing from the error message makes me think its an issue with cucumber. Please open an issue on the nightwatch repo
