### ISSUE TITLE
Adding property to Array.prototype causes an error

### ISSUE THREAD

**Issue by mastraub** [cucumber/cucumber-js#1264]
The currently closed issue [Adding property to Array.prototype in page object file causes error](https://github.com/cucumber/cucumber-js/issues/1111) still exists.

This error coerces us to put cucumber in an isolated environment (desired anyway) where we have to give up our handy array extensions (not desired).

Sadly, I have no patch ready yet.

Nevertheless, thank you for the great effort you put into cucumber-js so far.

**Comment by charlierudolph** [comment]
Dug into this and appears its an issue in our gherkin dependency, https://github.com/cucumber/cucumber/blob/gherkin-v5.1.0/gherkin/javascript/lib/gherkin/generate_events.js#L45

Thats on version 5 and I'm in the middle of updating to version 8 which appears to have switched to a better way to loop which appears to avoid this error.

https://github.com/cucumber/cucumber/blob/gherkin/v8.2.1/gherkin/javascript/src/stream/generateMessages.ts#L52

Thus this should be fixed once I merge in the gherkin upgrade.

**Comment by davidjgoss** [comment]
7.0.0 is now released, see [the changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) for migration instructions. Thanks!
