### ISSUE TITLE
Incomplete CHANGELOG

### ISSUE THREAD

**Issue by szikszail** [cucumber/cucumber-js#1275]
Could you please list the breaking changes in the formatter which are mentioned in CHANGELOG?

> Custom formatters: Formatter helpers and EventDataCollector had breaking changes to support retry

Currently, it is really hard to figure out what changed and what must be changed to support Cucumber 6 if we create a custom formatter. E.g. `getTestCaseData` has been removed and it is not clear, how [getTestCaseAttempt](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/helpers/event_data_collector.ts#L47) would replace it, or what other function does.

At the same time the link to `EventDataCollector` in the [documentation](https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md) is not valid.

**Comment by charlierudolph** [comment]
Sorry, yes the custom formatters have never been documented all that well.

Note there are a lot of unreleased changes in master right now so I suggest looking at documentation via the tag of the release you are using: https://github.com/cucumber/cucumber-js/blob/v6.0.5/src/formatter/helpers/event_data_collector.js

I think we can work on some better formatter documentation in Cucumber 7 (which will include the move to typescript and the use of a new internal structure for messages)
