### ISSUE TITLE
Retry BackOffPolicy

### ISSUE THREAD

**Issue by ermicioi** [cucumber/cucumber-js#1277]
Feature request for implementing some BackOffPolicy for retry feature.

Example scenario:
When running a suite of tests against a self recoverable environment and some test are failing, because the node goes down, then retry execution after N milliseconds, when the node is brought up.

In current solution the retry executes same test again without an configurable wait, which does not make sense as the node didn't come back yet.

As reference for BackOffPolicy can be spring-retry project, https://docs.spring.io/spring-retry/docs/api/current/org/springframework/retry/backoff/BackOffPolicy.html.

**Comment by davidjgoss** [comment]
I’m not sure how this could be added without either being very opinionated or adding lots more configurability (eg more CLI options).

Hypothetically if the attemptNumber was made available to hooks then users could implement this kind of thing themselves.

**Comment by ermicioi** [comment]
I will come with a PR, I hope soon :)

**Comment by charlierudolph** [comment]
This issue may be related where I had the idea that a custom work partitioning for parallel could be defined via a function so we can do things other than CLI to support this: #1044

**Comment by davidjgoss** [comment]
Closing this now, because:

- It's been inactive for a long time
- There are no current plans to implement this particular functionality in the core team
