### ISSUE TITLE
Dry Run

### ISSUE THREAD

**Issue by simondean** [cucumber/cucumber-js#128]
Hi.  The Ruby port of cucumber includes a --dry-run option.  It's really useful for discovering the scenarios in a codebase without having to execute them.  Here's the description of --dry-run from running `cucumber --help`: 

``` shell
    -d, --dry-run          Invokes formatters without executing the steps.
                           This also omits the loading of your support/env.rb file if it exists.
```

**Comment by jlin412** [comment]
+1

**Comment by zephyr-dev** [comment]
+1

**Comment by philipbeadle** [comment]
this is a really valuable feature, Im missing it not being in the js version of cucumber.

**Comment by samccone** [comment]
@jlin412 @zephyr-dev @philipbeadle any one have interest working on a PR?

**Comment by jlin412** [comment]
One of my colleague is doing a PR for this but waiting for approval from our company.

**Comment by philipbeadle** [comment]
@jlin412 any idea when that might happen?

**Comment by jlin412** [comment]
check it out:
https://github.com/cucumber/cucumber-js/pull/348

**Comment by charlierudolph** [comment]
#348 has been merged. This will be available in the next release
