### ISSUE TITLE
Full tagging support

### ISSUE THREAD

**Issue by RobertDiebels** [cucumber/cucumber-js#1284]
I would like to request that tagging is fully implemented according to the latest Gherkin specification [ [specification ](https://cucumber.io/docs/cucumber/api/#tag-expressions)].

Right now cumcumber-js implements tagging on a scenario level only. This is very restrictive. Having tags implemented according to the spec means that it we can avoid redundant tags for scenarios.

**Comment by davidjgoss** [comment]
Can you specify how exactly cucumber-js doesn’t meet the spec. Tags are supported on both features and scenarios, and as far as I know all the tag expressions in that documentation would work too

**Comment by RobertDiebels** [comment]
@davidjgoss Tag-inheritance is non-functional in version `6.0.2`.

**Comment by davidjgoss** [comment]
Per the [docs on hooks](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#tagged-hooks), the `tags` property is expected to be a tag expression, which means you need to prefix with the `@` symbol - this is what your example code above is missing, I think.

I've extended an existing test in the codebase that proves that tags from feature and scenario level are honoured (PR linked)

**Comment by RobertDiebels** [comment]
@davidjgoss Ah ok. I was under the impression that the @ was syntax only and superfluous for the hooks. My mistake.

Does this also apply to AfterAll and BeforeAll hooks? Or are they non-responsive to tags? 

Thanks for your replies so far.

**Comment by davidjgoss** [comment]
@RobertDiebels no problem. With `beforeAll` and `afterAll`, they are at the test run level and are always run, so they have no `World` and no tags.

**Comment by RobertDiebels** [comment]
@davidjgoss So, what would be the way to execute a hook after one feature specification file only? I'm asking because I want to wipe a database after a specific feature specification. 
Would I need to store the current context somewhere and check for it in an AfterAll hook? Or does Cucumber provide a method to execute some code after a specific feature?

**Comment by davidjgoss** [comment]
> So, what would be the way to execute a hook after one feature specification file only?

It's not really possible, I don't think - features are more of a logical grouping of scenarios at the feature level, but that doesn't translate to runtime where cucumber is just running a set of compiled scenarios

I've seen similar requirements before met by doing something like:

1. In a `before` hook matching on a tag, create the data you need - or skip on if the data's already created
2. In an `afterAll` hook, remove the data - or skip on if it never got created

**Comment by RobertDiebels** [comment]
@davidjgoss Yea, I ended up doing exactly that. Again, thank you for your help. Much appreciated.
