### ISSUE TITLE
How to consider a datatable as optional in selenium webdriver

### ISSUE THREAD

**Issue by bablukpik** [cucumber/cucumber-js#1287]
I have a step that sometimes needs to use a datatable but not all the time but how to do that.

Here is the step **When I create a 'basic' contract for 'marketplaceBuyer1'** but sometimes I need like this

```
When I create a 'basic' contract for 'marketplaceBuyer1'
      | specialSkill | true |
```

And step defination:

```
When(/^I create a '(.+)' contract for '(.+)'$/, async function (tier, userAlias) {
  if (tier === `basic`) {
    // do something
  }
});
```
Ref: https://stackoverflow.com/questions/60150709/how-to-consider-a-datatable-as-optional-in-selenium-webdriver

**Comment by davidjgoss** [comment]
Is the usage of the datatable limited to just whether `specialSkill` is true or false?

**Comment by bablukpik** [comment]
No @davidjgoss It can be any values like 
```
When I create a 'basic' contract for 'marketplaceBuyer1'
      | specialSkill | true  |
      | amount       | $50  |
```
And so on

**Comment by davidjgoss** [comment]
Okay - I don't see a reason why you couldn't define the step like this:

```javascript
When(/^I create a '(.+)' contract for '(.+)'$/, async function (tier, userAlias, optionsTable) {
  if (optionsTable) {
    // handle the table
  }
  if (tier === `basic`) {
    // do something
  }
});
```

So if you used that without a table or doc string, the third argument would just be `undefined` - try it out?

Alternatively you could look at a different flavour of the step worded more like `/^I create a '(.+)' contract for '(.+)' with options:$/`

**Comment by bablukpik** [comment]
Hey @davidjgoss it's fine when I use the data table but without data table it throwing the following error 
 When I create a 'basicSpecializedSkills' contract for 'marketplaceBuyer1' 
# features/step_definitions/rest/contract_steps.js:21
       Error: function uses multiple asynchronous interfaces: callback and promise
       to use the callback interface: do not return a promise
       to use the promise interface: remove the last argument to the function

**Comment by davidjgoss** [comment]
Ah I see - I think cucumber is seeing the third argument and thinking since a) it doesn’t form part of the expression and b) there’s no doc string or data table then it must be a callback function, but you are already using an async function hence the error message. Sorry, I had forgotten about that logic.

Going back to my earlier comment then I think you need two distinct steps

**Comment by charlierudolph** [comment]
Yep, please create two different steps. You can create a helper function to encompass the shared logic.
