### ISSUE TITLE
cli: --retryTagFilter case inconsistent with other args

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-js#1291]
To specify a tag filter for retry:

```
$ cucumber-js --retryTagFilter @flaky
```

It being in camel case is inconsistent with others like `format-options`, `world-parameters` and `require-module` which are kebab-case.

This is not just aesthetic, as it means if you are using something like dargs to create profile strings on the fly, you can't rely on a consistent rule.

Suggest we change it to `--retry-tag-filter` - we could potentially keep the camel cased one as an alias for one major release cycle and make it output a warning for now? cc @charlierudolph

**Comment by charlierudolph** [comment]
Sounds good to me
