### ISSUE TITLE
Navigating from feature file to step definition.

### ISSUE THREAD

**Issue by RajaAutomation** [cucumber/cucumber-js#1292]
Issue --> Unable to navigate from feature file to step definition by using CRTL+CLICK or F12.

Steps To Reproduce:-
1. Open a feature file and place cursor on any gherkin step.
2. Click on F12 or CRTL+CLICK and verify that you are able to navigate to Step definition file directly.

I have used specflow (i.e cucumber for C#) and the above steps help me navigate to the step definition file directly from feature file.

Is there any process in cucumber js to navigate from gherkin file to step definition file directly.

**Comment by davidjgoss** [comment]
This functionality exists in many editors and IDEs but it's not part of cucumber-js itself. It will depend on a few things:

1. You have the editor set up right (plugins installed etc)
2. It knows where your step code is (is it in your workspace? in node_modules or an ignored dir?)
3. It can understand the match (e.g. using custom parameter types would not work)

This isn't really the right place for this; I'd recommend pulling more detail together (tools you are using, feature file, step code, project structure) and posting on StackOverflow, the Cucumber Slack, or a forum relevant to the tool you're using.
