### ISSUE TITLE
Multiple formatters not working

### ISSUE THREAD

**Issue by averri** [cucumber/cucumber-js#1294]
The multiple formatter configuration is not working.
Example: when running Cucumber setting summary and progress bar at the same time
```bash
node ./node_modules/cucumber/bin/cucumber-js -f summary -f progress-bar
```
... then only the last option (the progress bar) is shown in the console.

Node version: 12.16.0
Cucumber-js: 6.0.5

**Comment by davidjgoss** [comment]
From the docs at https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats:

> If multiple formats are specified with the same output, only the last is used.

In this case, you have two formats defined but both to stdout, so the later one wins.

**Comment by averri** [comment]
Thanks @davidjgoss.
