### ISSUE TITLE
Allow sending message output to a HTTP(S) URL

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1296]
We want to make it easy for users to publish their results to external services. Allowing users to specify a URL to send results to should help.

I'm fully aware that this is a fragile solution - if the server is unavaible there is no way to resend the messages - cucumber would have to be run again.

We will also provide guidelines about alternative, more robust mechanisms to publish results, such as:

* Write messages to a file
  * Use cURL to publish after cucumber is done
  * Write messages to the CI server's "artifacts" directory and have a process somewhere else that can download them

I've implemented this for cucumber-ruby in https://github.com/cucumber/cucumber-ruby/pull/1395

Anyone wants to take a crack at this?

**Comment by charlierudolph** [comment]
Is this really something we should have built into the tool? Seems simple enough to create a tiny script that runs after the tests finish

**Comment by davidjgoss** [comment]
Okay I get this now I have seen Aslak's Smartbear talk. Could be a little tricky as it would be different implementations for Node vs browser. I'll take a look when I get past this messages/CCK stuff.

**Comment by davidjgoss** [comment]
Closing as dup of newer #1423
