### ISSUE TITLE
Step arguments transforms support

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#13]
Add support for step arguments transforms.

https://github.com/cucumber/cucumber/wiki/Step-Argument-Transforms

**Comment by totty90** [comment]
+1

**Comment by yaronassa** [comment]
Are transforms on the feature road-map for cucumberJS?

**Comment by hackhat** [comment]
Hey! @yaronassa take a look at https://github.com/hackhat/cucumberry/blob/prod/Readme.MD#parse-values-automatically you can have Javascript values parsed automatically. (numbers, decimals, objects, arrays, nested arrays and objects)

**Comment by yaronassa** [comment]
Thanks @hackhat ! 
I know it's possible, but I want to keep my customer's DSL simple and user-friendly, while performing all the necessary processing in the background.
Currently I "manually" parse the relevant values before calling my Word-helper functions, but I would be great skipping all those ugly calls with a behind-the-scenes automatic processing.

**Comment by totty90** [comment]
You could eventually make a plugin for cucuberry and add your own processing step there (don't know if you would have much of a benefit).

**Comment by scote** [comment]
Is there an alternative to transform step argument in the current version?

**Comment by jbpros** [comment]
@scote here is a little piece of code that implements transforms for you: https://gist.github.com/jbpros/8414fc60f4fd072c12f3

**Comment by robsquires** [comment]
hey @jbpros thanks for posting that code snippet 👍 I'm having a bit of trouble using it when I've attached something onto `World`..popped a comment in the gist. thanks

**Comment by charlierudolph** [comment]
Closing as will be using a different syntax as part of #622
