### ISSUE TITLE
rerun reruns all tests if @rerun.txt is empty

### ISSUE THREAD

**Issue by stefdelec** [cucumber/cucumber-js#1302]
If `@rerun.txt` exists and has not failing test in it (empty), it runs all features.

`cucumber-js @rerun.txt cucumber-js @rerun.txt`

If I had one failed test, it runs only the the specified test.

**Comment by charlierudolph** [comment]
I personally think this makes sense. After working your way through the failures, its good to run the whole suite again. 

Any empty rerun file is essentially the same to me as not providing any paths to features.

**Comment by ash8454** [comment]
Thanks for creating this bug @stefdelec . I am having the same issue where everything passes, the @rerun.txt is empty and is running all the features again which is not desired since all the tests passed.
