### ISSUE TITLE
Where is the attachment screenshot saved to?

### ISSUE THREAD

**Issue by chris-fran** [cucumber/cucumber-js#1303]
This might come off as a silly question, I added the code to attach a screenshot
```javascript
After(async function({ result: { status } }) {
  if (status === 'failed') {
    const screenshot = await this.page.screenshot({ type: 'jpeg', fullPage: true });
    this.attach(screenshot, 'image/png');
  }
});
```

And I see the following output on stdout:

```
   ✔ After # features/support/hooks.js:127
       Attachment (image/png)

1 scenario (1 failed)
2 steps (1 failed, 1 passed)
```

But I can't find the image on any directory. What am I missing?

**Comment by charlierudolph** [comment]
By default they aren't written to disk anywhere but content would be output in to the JSON / event protocol formatter. See here: https://github.com/cucumber/cucumber-js/blob/6.x/docs/support_files/attachments.md
