### ISSUE TITLE
TypeError: Cannot read property 'Builder' of undefined  at new CustomWorld

### ISSUE THREAD

**Issue by Soujanya2107** [cucumber/cucumber-js#1307]
const setWorldConstructor = require('cucumber');
const {seleniumWebdriver} = require('selenium-webdriver');
var {defineSupportCode} = require('cucumber');
var firefox = require('selenium-webdriver/firefox');

function CustomWorld() {
 let driver = new seleniumWebdriver.Builder()
      .forBrowser('chrome')
      .build();
      this.driver=driver
      
}
defineSupportCode(function({setWorldConstructor}){
    setWorldConstructor(CustomWorld)

});

Error:TypeError: Cannot read property 'Builder' of undefined
    at new CustomWorld (C:\Users\X

**Comment by davidjgoss** [comment]
That looks like your import of webdriver resolved to `undefined` - from this line:

```js
const {seleniumWebdriver} = require('selenium-webdriver');
```

I suspect what you want is on the default export - so try like this instead:

```js
const seleniumWebdriver = require('selenium-webdriver');
```

**Comment by Soujanya2107** [comment]
Thank you That worked for me.
