### ISSUE TITLE
--name does not recognize a scenario if special characters are used in the scenario name

### ISSUE THREAD

**Issue by abhinaba-ghosh** [cucumber/cucumber-js#1309]
Hi,
My scenario name is something like:

```
Scenario: (Hello) This is my first test
```
When I am trying to run the scenario with CLI  command as:
```
cucumber-js test/features --name='(Hello) This is my first test'
```
This is not able to recognize and run the scenario. I am using cucumber 6.x

If I just delete the braces, then it is able to recognize and run the scenario. 
Any guidance will help!

**Comment by kamolins** [comment]
@davidjgoss 

Not sure if this is a valid solution, but changing `match` to `includes` [here](https://github.com/cucumber/cucumber-js/blob/3e0c21174fc86603f452106543912e52935e9341/src/pickle_filter.ts#L120) should fix the issue. 
If this is an acceptable fix, I can make a PR!

**Comment by davidjgoss** [comment]
Hi @abhinaba-ghosh, the `--name` argument treats the input as a regular expression, so if you have characters like parentheses you should be able to escape them. For example:

```shell
--name='\(Hello\) This is my first test'
```

Does that work?

**Comment by abhinaba-ghosh** [comment]
It works! Thanks for the help.
