### ISSUE TITLE
Emit a Meta message at the beginning of the run.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1310]
See https://github.com/cucumber/cucumber/pull/976 for details.

It's been implemented in cucumber-ruby and cucumber-jvm:
* https://github.com/cucumber/cucumber-ruby/pull/1409
* https://github.com/cucumber/cucumber-jvm/pull/1952

**Comment by davidjgoss** [comment]
Will do as part of #1318
