### ISSUE TITLE
Question on example table

### ISSUE THREAD

**Issue by af6140** [cucumber/cucumber-js#1314]
Document said we can use transformer for data table.

But can we and how to use it for example table

**Comment by charlierudolph** [comment]
Are you referring to this kind of example table? 

https://github.com/cucumber/cucumber-js/blob/master/features/scenario_outlines.feature#L10 

That table is never exposed to the user and instead only used to reduce duplication in feature files.

**Comment by Izhaki** [comment]
No response from OP and question unclear. Happy to reopen upon response.

**Comment by Izhaki** [comment]
defineParameterType are part of cucumber expression, which apply to the pattern in a step definition.

You can transform you data table at will - you get the content of the table in your step definition and apply the transformation in the function body.

For example, we have a step like this:

```
When I type "project {uid}" into the "name" field
```

Then in the step definition we replace "{uid}" with some unique test id (in our case `testCase.pickle.id`, which is set in a Before block).

You can do exactly that with dataTables.

**Comment by Izhaki** [comment]
Aye.

`defineParameterType` is not going to help with data tables. You'll have to do the transformations yourself.

This is not even a decision at this repo level. There's a repo for cucumber expressions and `defineParameterType` API belongs there. It's a language independent API.

Takeaway: This API is not going to change.

You can keep `defineParameterType` to do the transformations for patterns. But for data tables you'll have to do the transformations yourself (take `tablerow`; iterate through its items; do the transformations).

**Comment by uzeyirqa** [comment]
Thank you
