### ISSUE TITLE
BeforeAll and AfterAll hooks don't fire events

### ISSUE THREAD

**Issue by pittgoose** [cucumber/cucumber-js#1321]
I'm writing a custom formatter and I've found that while `Before` and `After` hooks have a `test-step-finished` event, `BeforeAll` and `AfterAll` hooks do not. I have played around a bit with the code and have a nearly-working feature to add this functionality to cucumber, but before I put in the effort I wanted to just see if a PR for a feature like this even has a hope of being accepted.

I was thinking that these hooks could fire something like `test-run-hook-finished`.

**Comment by davidjgoss** [comment]
Hi @pittgoose, with v7.0.0 the events model is quite different, using the common standard [cucumber-messages](https://github.com/cucumber/cucumber/tree/master/messages).

`Before` and `After` hooks now emit both `testStepStarted` and `testStepFinished` events. `BeforeAll` and `AfterAll` hooks don't have a dedicated event though.

Could you elaborate on the use case for this?
