### ISSUE TITLE
Scenario Outline variable subsitution not working for variables that contain parenthesis

### ISSUE THREAD

**Issue by davidkoch-fwiot** [cucumber/cucumber-js#1322]
We often use phrases like "is triggered" and "is not triggered". In scenario outlines we phrase it as "the thing <is (not) triggered>". But when running the tests, the step is not found because the variable is not replaced due to its parenthesis. The other variables are replaced properly.

Here an example:
```gherkin
  Scenario Outline: Parenthesis
    Given the thing <is (not) triggered> and has <value>

    Examples: Thing
      | is (not) triggered | value |
      | is triggered       | foo   |
      | is not triggered   | bar   |
      | is triggered       | baz   |

``` 
 `value` gets replaced, but `is (not) triggered` is not. It then looks for steps like `Given the thing <is (not) triggered> and has foo`

Versions:
cucubmer-js: 6.0.5
node: v10.20.1

**Comment by Izhaki** [comment]
I don't really know why and where this is happening (and whether this should be happening).

But seems to me a bit odd to name a variable `is (not) triggered`. It is confusing, both in the step and in the examples table.

Why not:

```gherkin
  Scenario Outline: Parenthesis
    Given the thing is <triggered status> and has <value>

    Examples: Thing
      | triggered status | value |
      | triggered        | foo   |
      | not triggered    | bar   |
      | triggered        | baz   |
```
?

**Comment by davidkoch-fwiot** [comment]
A phrase like `Given the thing is (not) triggered and has value` can somewhat stand alone while     `Given the thing is triggered status and has value` may be a bit cryptic.

**Comment by Ulrikop** [comment]
The solution with `triggered status` is a possible solution. but the difference is that `triggered status` is more of a word by the developer, a variable like `is (not) triggered` sounds more natural.

we made the experience that non developer (like a project manager) read steps containing variables more easily if the variables are written like a part of the sentence.

**Comment by davidjgoss** [comment]
@davidkoch-fwiot I suspect that it doesn't work because the templated bits within `<>` are expected to be plain values and don't form part of the expression - I will have to dig into the code and check this though.

**Comment by charlierudolph** [comment]
This translation is done in gherkin: 

https://github.com/cucumber/cucumber/blob/master/gherkin/javascript/src/pickles/compile.ts#L218

Appears not currently escaping anything and thus if you use any regular expression special character that will cause an issue.

**Comment by Izhaki** [comment]
@davidkoch-fwiot I think you should close this issue and open a new one here: https://github.com/cucumber/cucumber/issues
