### ISSUE TITLE
cucumber_report.json file is not generated in vscode

### ISSUE THREAD

**Issue by ajithmoorthy** [cucumber/cucumber-js#1378]
I am working in cucumber-protractor-typescript project
I want to generate the cucumber report.json file for my testing project.
when I am executing the "cucumber-js features/ -f json:report/cucumber_report.json" command in vs code
that time I got error like below:-
Error: 
      You appear to be executing an install of cucumber (most likely a global install)
      that is different from your local install (the one required in your support files).
      For cucumber to work, you need to execute the same install that is required in your support files.
      Please execute the locally installed version to run your tests.

      Executed Path: C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\index.js
      Local Path:    C:\Users\ajith.periyasamy\Downloads\myproject\node_modules\cucumber\lib\index.js

    at validateInstall (C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\cli\install_validator.js:33:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Cli.run (C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\cli\index.js:124:5)    
    at async Object.run [as default] (C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\cli\run.js:30:14) 
 
please help me to get out of this problem

**Comment by ajithmoorthy** [comment]
I want to generate the HTML report for my project. so I need the .json  file for the test scripts.
so I am getting an error while generating the JSON file for Html Report. please help me.

**Comment by victoralvesf** [comment]
> I am working in cucumber-protractor-typescript project
> I want to generate the cucumber report.json file for my testing project.
> when I am executing the "cucumber-js features/ -f json:report/cucumber_report.json" command in vs code
> that time I got error like below:-
> Error:
> You appear to be executing an install of cucumber (most likely a global install)
> that is different from your local install (the one required in your support files).
> For cucumber to work, you need to execute the same install that is required in your support files.
> Please execute the locally installed version to run your tests.
> 
> ```
>   Executed Path: C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\index.js
>   Local Path:    C:\Users\ajith.periyasamy\Downloads\myproject\node_modules\cucumber\lib\index.js
> 
> at validateInstall (C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\cli\install_validator.js:33:11)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async Cli.run (C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\cli\index.js:124:5)    
> at async Object.run [as default] (C:\Users\ajith.periyasamy\AppData\Roaming\npm\node_modules\cucumber\lib\cli\run.js:30:14) 
> ```
> 
> please help me to get out of this problem

Try running ```node ./node_modules/.bin/cucumber-js features/ -f json:report/cucumber_report.json```

**Comment by davidjgoss** [comment]
@ajithmoorthy I don’t think this is anything to do with the formatter, I think the messaging is right here.

- Do you have cucumber installed globally? See @victoralvesf  comment re running specifically the local install l
- Less likely, but are some of your steps in a separate package that has cucumber as a dependency as well? This can cause issues too especially if using npm link

**Comment by ajithmoorthy** [comment]
yep, I installed the cucumber globally.
but still, the command is not working for me. 
I am working on the command which you suggested.
thanks for the reply my dear friend
