### ISSUE TITLE
The tagged hook is being executed, even if the scenario has not been executed

### ISSUE THREAD

**Issue by victoralvesf** [cucumber/cucumber-js#1387]
I have a hook that executes after all tagged scenarios.

Even if i don't execute this tagged scenarios, the hook is being executed. What can be happening?

I'm using -t @tag to run my tests.

```
AfterAll("@remove_contacts", async function () {
  await removeContacts();
});
```

**Comment by charlierudolph** [comment]
What cucumber version are you on?

BeforeAll / AfterAll hooks do not accept a tag as a first argument.
Before / After hooks accept a tag to conditionally run around only specific scenarios.

Hook documentation: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md

**Comment by victoralvesf** [comment]
> What cucumber version are you on?
> 
> BeforeAll / AfterAll hooks do not accept a tag as a first argument.
> Before / After hooks accept a tag to conditionally run around only specific scenarios.
> 
> Hook documentation: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md

I kinda learned how to deal with his behavior, it makes sense run after all scenarios and not only for the tagged ones. Sorry for the dumb question.
