### ISSUE TITLE
Custom formatter not logging 

### ISSUE THREAD

**Issue by csalgo70** [cucumber/cucumber-js#1396]
I am trying to learn how to write a simple custom formatter for Cucumber JS.

I have read https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md

I tried this sample below. But it is not outputting anything. The documentation talks about setting up the underlying stream for the log function. But I don't see any stream option to set nor do the custom formatter samples have them.

So my question is how do I get this simple sample below to log the output to stdout ?

I am running the tests the following way as mentioned in docs to use this new formatter

./node_modules/.bin/cucumber-js --format .\simple_formatter.js ./Features -r ./Steps

I have also tried --format=

```js
const { Formatter, formatterHelpers, Status } = require("cucumber");

class SimpleFormatter extends Formatter {
  constructor(options) {
    super(options);

    options.eventBroadcaster.on("envelope", (envelope) => {
      if (envelope.testCaseFinished) {
        this.logTestCaseFinished(envelope.testCaseFinished);
      } else if (envelope.testRunFinished) {
        this.logTestRunFinished(envelope.testRunFinished);
      }
    });
  }

  logTestCaseFinished(testCaseFinished) {
    const testCaseAttempt = this.eventDataCollector.getTestCaseAttempt(
      testCaseFinished.testCaseStartedId
    );
    this.log(
      testCaseAttempt.gherkinDocument.feature.name +
        " / " +
        testCaseAttempt.pickle.name +
        "\n"
    );
    const parsed = formatterHelpers.parseTestCaseAttempt({
      cwd: this.cwd,
      snippetBuilder: this.snippetBuilder,
      supportCodeLibrary: this.supportCodeLibrary,
      testCaseAttempt,
    });
    parsed.testSteps.forEach((testStep) => {
      this.log(
        "  " +
          testStep.keyword +
          (testStep.text || "") +
          " - " +
          Status[testStep.result.status] +
          "\n"
      );
    });
    this.log("\n");
  }
  logTestRunFinished(testRunFinished) {
    this.log(testRunFinished.success ? "SUCCESS" : "FAILURE");
  }
}
module.exports = SimpleFormatter;
```

There are no errors reported. The test does work and finish but no output from the formatter.

Browser for testing: Chrome Version 85.0.4182.0 (Developer Build) (64-bit)
OS: Windows 10
Nodejs: version v12.16.3

**Comment by charlierudolph** [comment]
What cucumber version are you running? Unfortunately we have a number of unreleased changes in master currently.

There are links to old version of docs in the README or you can try installing cucumber from source (by specifying the github url and the current commit at the tip of the master branch)

**Comment by csalgo70** [comment]
> What cucumber version are you running? Unfortunately we have a number of unreleased changes in master currently.
> 
> There are links to old version of docs in the README or you can try installing cucumber from source (by specifying the github url and the current commit at the tip of the master branch)

My current version is 6.0.5 which seems to be the latest version.

**Comment by csalgo70** [comment]
I even cloned the repo and built it locally & then used the new js file but still the customer formatter doesn't seem to work. Any ideas ?

**Comment by davidjgoss** [comment]
@csalgo70 yeah I think you'd be better using the feature from the current published version as your reference, see https://github.com/cucumber/cucumber-js/blob/6.x/features/custom_formatter.feature.

New release should be coming very soon though.

**Comment by csalgo70** [comment]
> @csalgo70 yeah I think you'd be better using the feature from the current published version as your reference, see https://github.com/cucumber/cucumber-js/blob/6.x/features/custom_formatter.feature.
> 
> New release should be coming very soon though.

Thanks @davidjgoss . Look forward to the release. Feel free to close the issue.
