### ISSUE TITLE
Cucumber/Protractor/Typescript (Syntax Error: Unexpected Identifier)

### ISSUE THREAD

**Issue by JamesAnderson982** [cucumber/cucumber-js#1402]
Hello, 

I am unable to generate the skeleton in the terminal for my first feature file by using protractor/typescript.
![image](https://user-images.githubusercontent.com/69161267/89204576-c3507d00-d5cf-11ea-9ad3-ef1fe152b362.png)

**Please anyone can guide me to resolve this error.**

**package.json**
{
  "name": "typescriptproject",
  "version": "1.0.0",
  "description": "Protractor  Framework",
  "main": "index.js",
  "scripts": {
    "test": "protractor JsFile/configuration.js",
    "pretest": "tsc",
    "protractor": "./node_modules/protractor/built/cli.js",
    "cucumbertest": "protractor JsFile/cucumberconfig.js",
    "webdriver-update": "./node_modules/.bin/webdriver-manager update"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/jasmine": "^3.5.11",
    "@types/jasminewd2": "^2.0.8",
    "jasmine": "^3.5.0",
    "protractor": "^7.0.0",
    "typescript": "3.9.7",
    "ts-node": "^8.10.2"
  },
  "devDependencies": {
    "@types/chai": "4.2.12",
    "@types/cucumber": "6.0.1",
    "@types/node": "14.0.27",
    "chai": "4.2.0",
    "cucumber": "6.0.5",
    "protractor-cucumber-framework": "6.2.1"
  }
}

**cucumberconfig.js**
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.config = void 0;
exports.config = {
   // directConnect: true,
   // seleniumAddress : 'http://localhost:4444/wd/hub',
    jasmineNodeOpts: {
        defaultTimeoutInterval: 300000
    },
    specs: ['../features/demo.feature'],
    cucumberOpts: {
        require: [
            './stepDefinations/steps.ts'
        ]
        
    },
    capabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
            w3c: false
        },
        framework: 'custom',
        frameworkPath: require.resolve('protractor-cucumber-framework'),
    }
};

**Comment by davidjgoss** [comment]
I think this would be best raised under https://github.com/protractor-cucumber-framework/protractor-cucumber-framework.

FWIW from the error and its stack trace, it looks very much like the protractor framework is trying to load/parse your feature file as though it's a JavaScript module, hence the syntax error. I think you're probably looking at a misconfiguration issue somewhere in that setup.
