### ISSUE TITLE
cucumber.js unknown option

### ISSUE THREAD

**Issue by Tallyb** [cucumber/cucumber-js#1405]
I am using a cucumber.js file for profiles. My goal is to be able to transfer params that build the relevant profile (we have multiple options for which creating profile can be very challenging). 

If I run `npx cucumber-js --a=a` I get an error : `error: unknown option '--abc'`
However, if I add some dummy param such as `npx cucumber-js dummy --a=a` the a parameter is available (using yargs.argv). 

Idealy - it would be great if cucumber could ignore any unknown option, so they can be used directly.

**Comment by Tallyb** [comment]
well, it boils down to the fact that I have 3 params, 2 with 3 possible values, and a boolean and any combination is valid. The profiles are cartesian multiplications. Then you had one more...

**Comment by aslakhellesoy** [comment]
I agree with @charlierudolph. Allowing any option to be passed to the command line interface makes it impossible to give good error messages when a use has a typo in a supported option. I'm not aware of any tools that allows passing arbitrary options, and see no reason for us to behave differently.

I recommend using environment variables for passing additional information to your code.
