### ISSUE TITLE
Browser runtime https://cucumber.github.io/cucumber-js/

### ISSUE THREAD

**Issue by wa-citadel** [cucumber/cucumber-js#1406]
Hi, 
Curious if there is an easy way for engineers to expose their tests, features, steps just like you do in https://cucumber.github.io/cucumber-js/ as a service.

**Comment by aslakhellesoy** [comment]
Hi @wa-citadel - we're planning on making an announcement of https://reports.cucumber.io next week. It will let you publish reports straight to the web. Initially only Cucumber-Ruby and Cucumber-JVM will be able to publish there, but as soon as https://github.com/cucumber/cucumber-js/pull/1318 lands, we can start implementing the new `--publish` option in Cucumber.js too.

**Comment by jbpros** [comment]
We're also in the process of [removing browser support](https://github.com/cucumber/cucumber-js/pull/1508). 

@wa-citadel can you tell us a bit more about your needs behind such a web interface to Cucumber.js? What problem are you trying to solve?

**Comment by wa-citadel** [comment]
yes, sure. 

Imagine a well-tested financial or trading system using cucumber and BDD with reusable test steps. 
It would be great if let's say a regulatory manager would be able to add new cases and scenarios using already established working steps. Similar to what I can do in WebStorm/IntelliJ with IntelliSense and autocomplete. How great it would be If anyone can write scenarios and reuse steps, not just engineers.
