### ISSUE TITLE
Custom formatters can only be loaded by relative path

### ISSUE THREAD

**Issue by dawn-minion** [cucumber/cucumber-js#1412]
In [builder.ts#L107](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/builder.ts#L107), we load custom formatters as relative to the current working directory. Unfortunately this means that if the package is not relative to the project we can't load it. In my particular case I'm trying to use Yarn PNP with the cucumber-pretty formatter, and with PNP the package will no longer be relative to the project, but can be included by name (It lives in the user's cache folder instead).

We could try loading by relative path first, and if that fails we could then try by name, which should cover both cases.

**Comment by charlierudolph** [comment]
Can you give a more detailed example of how to reproduce your issue? (ie exact steps of what you are trying to do)

**Comment by charlierudolph** [comment]
Hmm, okay so PNP definitely changes a lot of things here. I'd be okay with the following: 
* when loading a node module just use the name
* to load via local paths, you are required to have a leading `.` (similar to how general require works)

**Comment by dawn-minion** [comment]
Would the second requirement break existing users though? In the current setup I have (before the PNP switch) it was always `--format=node_modules/cucumber-pretty` since that just worked. Not that it's a big deal, but thought I'd ask

**Comment by bankimzededa** [comment]
Hi,

Is there any way I can disable all logs from cucumber, I need to show only details regarding failed test. Right now cucumber is printing all tests details including passed and failed.

Thanks
Bankim

**Comment by charlierudolph** [comment]
@bankimzededa please use the support channels listed on the readme or review the [formatter documentation](https://github.com/cucumber/cucumber-js/blob/v6.0.5/docs/cli.md#formats). I'd like to keep each issue as a targeted discussion.

@dawn-minion yep that would be a breaking change, though I think a pretty minor one since its super easy for someone to fix)

**Comment by dawn-minion** [comment]
Sounds good then, will update the PR to switch based on a leading `.`.
