### ISSUE TITLE
Add --publish option

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1423]
Cucumber-JVM and Cucumber-Ruby now have a --publish option. More details here:

- https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.5.0.md
- https://github.com/cucumber/cucumber-ruby/blob/master/release-notes/5.0.0.md

We should implement this for Cucumber-js too. I'm happy to start on that with @sebrose and anyone else who wants to help out.

It's always hard to estimate how long things take, but we might be able to get it done this week. What are the current plans for a release? Is master ready to go? /cc @davidjgoss @charlierudolph

**Comment by davidjgoss** [comment]
@aslakhellesoy I'm happy to help out with that as and when.

Regarding a 7.0.0, I think we just need to finish #1414, then merge #1411 and good to go - there may be something I'm missing though @charlierudolph?

**Comment by aslakhellesoy** [comment]
Excellent! I'd love to include #1423 / #1424 in the 7.0.0 release. I think I'll be spending most of the time this week working on that. I'll update the PR with TODOs - then we can discuss how to split up the work.
