### ISSUE TITLE
HTML Formatter

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1425]
Cucumber-JVM and Cucumber-Ruby now implement a `html` formatter based on the [standard html formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter).

The implementations are here:

Java:

* [MessagesToHtmlWriter.java](https://github.com/cucumber/cucumber/blob/master/html-formatter/java/src/main/java/io/cucumber/htmlformatter/MessagesToHtmlWriter.java) (library)
* [HtmlFormatter.java](https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/plugin/HtmlFormatter.java) (Cucumber-JVM formatter)

Ruby:

* [html_formatter.rb](https://github.com/cucumber/cucumber/blob/master/html-formatter/ruby/lib/cucumber/html_formatter.rb) (library)
* [html.rb](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/html.rb) (Cucumber-Ruby formatter)

TypeScript:
* [CucumberHtmlStream.ts](https://github.com/cucumber/cucumber/blob/master/html-formatter/javascript/src/CucumberHtmlStream.ts)
* Not yet integrated into Cucumber-js

Since the library is already ported to TypeScript, it should hopefully be easy to use it from within cucumber-js.

Related issue for godog: https://github.com/cucumber/godog/issues/339

**Comment by davidjgoss** [comment]
Yeah this should be fairly straightforward.

Should this be included by default in cucumber-js, or as an optional dependency?

**Comment by aslakhellesoy** [comment]
I don’t see any issues with making it a default dependency. We did that in Ruby and Java
