### ISSUE TITLE
DeAsync and Async-utility not working

### ISSUE THREAD

**Issue by deepziem** [cucumber/cucumber-js#1433]
DeAsync and Async utility are not working post cucumber 5.03 versions. Am not sure why ?
protractor 7+ cucumber 6 ..

It was working in lower versions of cucumber

**Comment by davidjgoss** [comment]
@deepziem could you expand a bit on exactly what you're trying to do, the expected result, and what you actually see? Please also include the version of cucumber-js you're using.
