### ISSUE TITLE
Is there a getTimeout function ?

### ISSUE THREAD

**Issue by wa-citadel** [cucumber/cucumber-js#1441]
If you use `{timeout: 60 * 1000}`  like mentioned here ==> https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md

is there a way to get this timeout value inside of the handler ?

``` javascript
Given(/^a slow step$/, {timeout: 60 * 1000}, function() {
  // Does some slow browser/filesystem/network actions
 const timeout = getTimeout();
 console.log( timeout); //<--------------- logs 60000
});
```

**Comment by davidjgoss** [comment]
I think something like this should work:

```js
const timeout = 60 * 1000;
Given(/^a slow step$/, {timeout}, function() {
  // Does some slow browser/filesystem/network actions
 console.log(timeout); //<--------------- logs 60000
});
```

**Comment by wa-citadel** [comment]
that's what I ended up doing, there isn't a way to access a step options/config within the step handler.

**Comment by aslakhellesoy** [comment]
What do you need it for?

**Comment by davidjgoss** [comment]
Closing as this went quiet.
