### ISSUE TITLE
Calling steps from step definitions 

### ISSUE THREAD

**Issue by lodizn** [cucumber/cucumber-js#1443]
How do I call a step from a step definition in Javascript?

See example:

Given('I open the app', async () => {
  console.log(`the app opens`);
});

Then('Calling step within', async () => {
  // call the step : "I open the app"
});

**Comment by aslakhellesoy** [comment]
You can't. This is better:

```javascript
Given('I open the app', async () => {
   openTheApp()
});

Then('Calling step within', async () => {
  openTheApp()
});

function openTheApp() {
  console.log('the app is open')
}
```

**Comment by TsayDev** [comment]
See the example here.
https://github.com/TsayDev/Advanced-Cucumber
