### ISSUE TITLE
BeforeAll executes without considering the tags provided

### ISSUE THREAD

**Issue by akbbhatt** [cucumber/cucumber-js#1447]
BeforeAll is getting executed even if my protractor.conf.js file contains another cucumber tag(say @apiTest) specified. I was thinking that this BeforeAll block will execute only before any feature/scenario with @testTag is executed. 

BeforeAll({ tags: '@testTag' }, () => {
  console.log(`from before all`);
});

**Comment by davidjgoss** [comment]
Per the docs at https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md BeforeAll does not support tags - it runs once at the start of the test run and it not linked to any specific scenario.

If you want to run some code before each scenario, and filter that based on tags, then you probably want to use Before instead

**Comment by akbbhatt** [comment]
Thanks for answering David. 
I need to execute setup scripts only once before executing some of my feature files or scenarios. But these setup scripts are not required for all the feature/scenarios mentioned. This is the reason I want the setup scripts to be executed only when it's really necessary based on the tags mentioned at the feature file level. 
I found a workaround for this by reading the tags specified from the config file from within the BeforeAll() method and then execute my setup script based on the tags mentioned in the config.
