### ISSUE TITLE
Deprecate cucumber in favour of @cucumber/cucumber

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1448]
I think both users and maintainers would benefit from more people upgrading to `@cucumber/cucumber`.

One thing we could do is to `npm deprecate` v6 and below. We've already trialled that with [7.0.0-rc.0](https://www.npmjs.com/package/cucumber/v/7.0.0-rc.0).

We should wait until `7.0.0` is released, but other than that, does anybody have any objections? /cc @charlierudolph @davidjgoss @vincent-psarga @cbliard @tooky @sebrose

**Comment by aslakhellesoy** [comment]
Current stats:

- [cucumber: 480k weekly downloads](https://www.npmjs.com/package/cucumber)
- [@cucumber/cucumber: 10k weekly downloads](https://www.npmjs.com/package/@cucumber/cucumber)

This is in large part due to it being a release candidate, but I would be surprised if the changed namespace wouldn't also be a barrier.

We could postpone the deprecation until a few weeks after `7.0.0` drops and gather some data before and after. It would be interesting to understand how effective it would be.

**Comment by davidjgoss** [comment]
I think this makes sense.

Not sure how much difference it will make but I think we should link to the new package in our deprecation readme so it's easy for users who land on https://www.npmjs.com/package/cucumber from a search. I've raised https://github.com/cucumber/cucumber-js-package-upgrade/pull/1 for this.

**Comment by davidjgoss** [comment]
Closing as the [old package](https://www.npmjs.com/package/cucumber) is now deprecated.

FWIW latest weekly download stats:

- old: 499k
- new: 19k
