### ISSUE TITLE
Allow to run arguments from other CLI in version 7

### ISSUE THREAD

**Issue by j320** [cucumber/cucumber-js#1474]
Since Cucumber is a test runner that's be used in test frameworks, it's very useful to be able to use command line arguments from the test framework being used. This is currently possible in Cucumber < 7 (except in parallel), in 7 the result is `unknown option --<argument>`

I know that other tools don't generally allow this but I think that for cucumber it does make sense since it's agnostic to the test tool being run with and enabling the use of command line arguments of the tool in question is an important part of using it. Being able to do it in parallel would be just as helpful.

**Comment by davidjgoss** [comment]
Hi @j320 

I just tried this with cucumber 6.0.5, without parallel (on [this example project](https://github.com/davidjgoss/cucumber-puppeteer-typescript-starter)), and still got the (expected) behaviour of an error for an unknown option:

```shell
$ npx cucumber-js --foo
error: unknown option '--foo'
```

Are you able to publish a minimal repro somewhere?

At any rate, I doubt supporting arbitrary command line options in order to have them picked up by other tools is something we would look to support. One of the good things about the current behaviour is that if someone does a typo with an option then they get immediate feedback, rather than potentially an issue that takes a while to track down.

If you need to pass extra stuff through the CLI, you could always [use world parameters](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#world-parameters). and then pass the values to the programmatic API of the other tool from [your world](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/world.md). Depending on the specifics, the tool may also support environment variable(s) for some stuff.

**Comment by j320** [comment]
Hi @davidjgoss,

Thanks for your reply.

Interesting, I can get you a small repo, however I'm using Detox for React Native mobile testing, therefore there'll be some time on your side to get an app built + simulator and stuff, if you're interested I'll happily get a repo for you. Here's a small documented example where you can see how the scripts look like.

So you're saying that using world parameters I can pass arguments from another CLI? I've had a read through the documentation available and I'm not sure how that would work, I've given it a quick try and once the JSON was correct, the argument had no effect, as if it wasn't added. Perhaps I'm misunderstanding something.

I understand what you're saying, it makes sense that you would rather get the user to know that they're adding something wrong rather than thinking that the argument is not working. Perhaps a way to ignore specific arguments could be a middle ground? Again, Cucumber is used with other frameworks and unless the test tool directly maintains a library of its own, there doesn't seem to be a way of using the tool's CLI which is an important toolbox.

**Comment by karlmarxlopez** [comment]
@davidjgoss I have the same use case as @j320. I think cucumber should only validate CLI arguments that it expects and allow others to pass through, just like `--configuration` for detox?

For example
```
yarn cucumber-js --require-module ts-node/register --coniguration ios.sim.debug
```
Or a more explicit way
```
yarn cucumber-js --require-module ts-node/register --pass-through-args="--configuration ios.sim.debug --foo-bar"
```

**Comment by karlmarxlopez** [comment]
NVM @davidjgoss, I did a workaround by dynamically selecting the configuration based on the environment variable. 

I came up with this solution.

You can run it by doing
`yarn DETOX_PLATFORM=android DETOX_BUILD_FLAVOR=debug cucumber-js`
or adding a command alias to your package.json
```
{
 "script": {
	"detox:buildAndroidDebug": "DETOX_PLATFORM=android DETOX_BUILD_FLAVOR=debug detox build",
    "detox:buildAndroidRelease": "DETOX_PLATFORM=android DETOX_BUILD_FLAVOR=release detox build",
    "detox:buildIosDebug": "DETOX_PLATFORM=ios DETOX_BUILD_FLAVOR=debug detox build",
    "detox:buildIosRelease": "DETOX_PLATFORM=ios DETOX_BUILD_FLAVOR=release detox build",
    "detox:testAndroidDebug": "DETOX_PLATFORM=android DETOX_BUILD_FLAVOR=debug cucumber-js",
    "detox:testAndroidRelease": "DETOX_PLATFORM=android DETOX_BUILD_FLAVOR=release cucumber-js",
    "detox:testIosDebug": "DETOX_PLATFORM=ios DETOX_BUILD_FLAVOR=debug cucumber-js",
    "detox:testIosRelease": "DETOX_PLATFORM=ios DETOX_BUILD_FLAVOR=release cucumber-js"
 }
}
```

```js
function setConfiguration() {
  const PLATFORM = process.env.DETOX_PLATFORM || 'ios'; //ios | android
  const FLAVOR = process.env.DETOX_BUILD_FLAVOR || 'release'; // debug | release

  const configurations = {
    ios_debug: {
      'ios.sim.debug': {
        type: 'ios.simulator',
        build: 'xcodebuild -workspace ios/rnsandbox.xcworkspace -scheme rnsandbox -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
        binaryPath: './ios/build/Build/Products/Debug-iphonesimulator/rnsandbox.app',
        device: {
          type: 'iPhone 8'
        }
      }
    },
    ios_release: {
      'ios.sim.release': {
        type: 'ios.simulator',
        build: 'xcodebuild -workspace ios/rnsandbox.xcworkspace -scheme rnsandbox -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
        binaryPath: './ios/build/Build/Products/Debug-iphonesimulator/rnsandbox.app',
        device: {
          type: 'iPhone 8'
        }
      }
    },
    android_debug: {
      'android.emu.debug': {
        type: 'android.emulator',
        binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
        build: 'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..',
        device: {
          'avdName': 'Pixel_API_29_AOSP'
        }
      },
    },
    android_release: {
      'android.emu.release': {
        type: 'android.emulator',
        build: 'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..',
        binaryPath: './android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
        device: {
          'avdName': 'Pixel_API_29_AOSP'
        }
      }
    }
  };

  return configurations[`${PLATFORM}_${FLAVOR}`];
}


module.exports = {
  testRunner: 'jest',
  runnerConfig: 'e2e/config.json',
  detox: {
    behavior: {
      init: {
        exposeGlobals: false
      }
    }
  },
  configurations: setConfiguration(),
}
```

**Comment by j320** [comment]
@karlmarxlopez That works for selecting configuration, however there's a broad Detox CLI, for example to set the log level or recording videos, headless and more. Therefore we still need to be able to pass the arguments for those.

**Comment by karlmarxlopez** [comment]
@j320 Yup, I agree. Hopefully, they will resolve this in the next release.

**Comment by davidjgoss** [comment]
> I think cucumber should only validate CLI arguments that it expects and allow others to pass through

Again, I think this is misguided. Another example of a problem that could arise, there's currently a piece of work ongoing under #1434 to add a `--config` option to the cucumber-js CLI. It's basically just luck that it's not a naming collision with the `--configuration` one that you want. And there could easily be a naming collision in future between cucumber-js and Detox or another tool.

Detox has a CLI but it also exposes a _programmatic_ API that you can call from your support code (e.g. `World`, or hooks like `Before`), having collected the bits you need via [world parameters](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#world-parameters). [Profiles](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#profiles) can make this easier and save a lot of hand-crafting JSON strings on the command line. Let me know if you want a more detailed example.

I can't quite tell from the docs but it looks like [`detox.init()`](https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxObjectAPI.md#detoxinit) could (should?) allow you to pass configuration:

> The setup phase happens inside `detox.init()`. This is the phase where detox reads its configuration, starts a server, loads its expection library and starts a simulator....By default `await detox.init([configOverride, userParams]);` will launch the installed app. If you wish to control when your app is launched, add `{launchApp: false}`Ê param to your init.

**Comment by karlmarxlopez** [comment]
@davidjgoss Yup, I'm (we) are using `detox.init()` method on the `hooks` of cucumber, but you can't pass a flag like `--headless` and other args/flags (as @j320 mentioned) on the configuration.

The workaround I posted above is to dynamically set a single configuration, which `Detox` automatically selects.

**Comment by davidjgoss** [comment]
Having seen https://github.com/wix/Detox/issues/2487#issuecomment-734929243 (thanks @karlmarxlopez for linking that up) I think we can close this, Detox's change seems like the right way to me.
