### ISSUE TITLE
Running Cucumber-js in a Kotlin multiplatform project

### ISSUE THREAD

**Issue by psa-anddev** [cucumber/cucumber-js#1475]
I'm working in a small Kotlin Multiplatform project and I want to use Gherkin to write my acceptance tests. I have been able to configure Cucumber in the JVM sources (one for the back-end and another for the Android app). I'm trying to configure Cucumber JS for the web front-end but I am unable to make it work. 

I have tried to use Karma (since it is the default framework that Kotlin JS uses) to integrate with Cucumber (in the same fashion that jUnit integrates with Cucumber-JVM). Every library I have used to try to integrate it has failed as it is not picking up the Feature files. Am I taking the right approach to get it working? Any help would be welcomed. Thank you in advance.

**Comment by davidjgoss** [comment]
Hey @psa-anddev, are you able to put a repo up where we can reproduce, or perhaps point me at an example/starter project with Kotlin and Karma so I can see how that hangs together?

Cucumber does the job of a test runner, so I would generally expect it to _replace_ Karma in doing this, but it could potentially work with it as well.

**Comment by psa-anddev** [comment]
I pushed what I have so far to a git repo. You can check it out here. https://github.com/psa-anddev/hotel

**Comment by davidjgoss** [comment]
Sorry for the very late follow up @psa-anddev. I can't see any particular issues with your project at a scan, although I'm not very well placed as the stack is a bit unfamiliar to me. It looks like you're using https://github.com/mitcoding/karma-cucumber-js-latest, so I would probably suggest raising something there. Thanks!
