### ISSUE TITLE
mixing Cucumber/Gherkin with Mocha

### ISSUE THREAD

**Issue by jradom** [cucumber/cucumber-js#1487]
Are there any ways to use Mocha related code besides the hooks?  We have a framework based on Mocha but want to extend it allowing to use of Cucumber/Gherkin.  Please, let me know

Thanks

Jeff

**Comment by davidjgoss** [comment]
What aspects of mocha are you looking to use within cucumber?

Mocha and cucumber are both test runners so wouldn't normally expect to mix.
