### ISSUE TITLE
getTestCasesFromFilesystem seems to be inaccessible

### ISSUE THREAD

**Issue by binarymist** [cucumber/cucumber-js#1489]
I've posted a message on the Slack, @Raymond also posted there on Feb 29.

I've searched for related issues and found #1220 which is how I used to do it.

I've just upgraded from 5.1.0 to 7.0.0-rc.0, I've read the Changelog. It appears that there is no longer a way to access `cucumber.getTestCasesFromFilesystem`, although the routine that does the work still appears to be in dist/cucumber.js.
Is there a new approach for getting the test cases from filesystem that makes `getTestCasesFromFilesystem` redundant?

Thanks.

**Comment by binarymist** [comment]
I've consolidated the needed code, although it's still tied to an old version of gherkin.

**Comment by davidjgoss** [comment]
Hi @binarymist, this area has been refactored, the loading of features from the file system is now handled by the Gherkin library.

Could you expand a little on your use case - e.g. is it some reporting you want to do as part of the run? There'll be a way, just want to understand your requirement.

**Comment by binarymist** [comment]
Hi @davidjgoss... Thanks for you response.

Yeah, so at this stage we (the back-end) send back the test plan (the concatenated feature file contents that comply with the tags) to the purpleteam CLI that will run, the plan is printed to screen. Does that make sense and is it enough information? Basically the `getTestCasesFromFilesystem` was exactly what we needed and were using... until we upgraded.

**Comment by binarymist** [comment]
Hi @davidjgoss ... Any update? Would love to be able to close this (https://gitlab.com/purpleteam-labs/purpleteam/-/issues/25) issue.
Thanks.

**Comment by aslakhellesoy** [comment]
@binarymist is there anything preventing you from using the `@cucumber/gherkin` module directly to parse Gherkin documents?

**Comment by binarymist** [comment]
HI @aslakhellesoy and thanks for your response. I only just read this, didn't get any notification. Let me investigate your response, I've added it to our backlog to do and report back. Thanks.

**Comment by binarymist** [comment]
Hi @aslakhellesoy .

Looking at the README, it's unclear if @cucumber/gherkin provides the same functionality that was removed?

The Usage example has an [options object](https://github.com/cucumber/gherkin-javascript#usage) but it doesn't appear to be used?

How do consumers of `fromPaths` from @cucumber/gherkin provide options `{ cwd, eventBroadcaster, featureDefaultLanguage, featurePaths, pickleFilter }` that are required to retreive only the specific test cases that match the options?

Thanks.

**Comment by binarymist** [comment]
Does the new:  [`gherkin.fromPaths(['features/hello.feature'])`](https://github.com/cucumber/gherkin-javascript/blob/master/README.md) provide the same functionality as the removed [`getTestCasesFromFilesystem`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/main/src/scripts/cucumber-redacted.js#L49). As I've mentioned, by the looks of the missing options with the newer approach, the answer is no. Is this correct?

**Comment by aslakhellesoy** [comment]
Hi @binarymist

As far as I can tell, the `getTestCasesFromFilesystem` function returns an array of `{ pickle, uri }` tuples.

The `gherkin.fromPaths` function will give you a readable stream of [cucumber messages](https://github.com/cucumber/cucumber/tree/master/messages#cucumber-messages). The messages in this stream will be either `Source`, `GherkinDocument` or `Pickle`. You can use options to get just pickles if you want.

To me it sounds like that should be a simple replacement.

BTW, you're using a deprecated version of `gherkin`. We've moved to `@cucumber/gherkin` now.

**Comment by binarymist** [comment]
TypeError: gherkin.fromPaths is not a function

**Comment by aslakhellesoy** [comment]
Sorry this is so hard to find. It moved to `@cucumber/gherkin-streams` in [version 17.0.0](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#1700---2021-02-07). More details in (https://github.com/cucumber/cucumber/issues/1331, https://github.com/cucumber/cucumber/pull/1332 and https://github.com/cucumber/cucumber/pull/1333) 

You should be able to use it like this:

```typescript
import GherkinStreams from '@cucumber/gherkin/dist/src/stream/GherkinStreams'
import { IdGenerator } from '@cucumber/messages'

const gherkinOptions = {
  defaultDialect: 'en',
  newId: IdGenerator.uuid(),
}
const gherkinEnvelopeStream = GherkinStreams.fromPaths(paths, gherkinOptions)
```

> The gherkin-javascript repo also appears to be missing a CHANGELOG,

We're maintaining multiple language versions of gherkin, and the changelog is [here](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md).

> there is no deprecation notice. Can you explain what's happening?

We moved all libraries to the `@cucumber` namespace last year, and [deprecated](https://www.npmjs.com/package/cucumber) `cucumber` at that time. We simply forgot to deprecate the other packages. I've created https://github.com/cucumber/cucumber/issues/1421 to track this.

> I'm also confused as to why the so called deprecated gherkin package refers to the same repository as the non deprecated @cucumber/gherkin package?

We're maintaining a lot of multi-platform libraries in the [cucumber/cucumber](https://github.com/cucumber/cucumber) monorepo, and the location of the source code didn't change when we started releasing modules under the `@cucumber` namespace.

**Comment by binarymist** [comment]
> Sorry this is so hard to find. It moved to @cucumber/gherkin-streams in version 17.0.0.

There is no package by the name of @cucumber/gherkin-streams in NPM.

The closest is @cucumber/gherkin which leads to repo: https://github.com/cucumber/gherkin-javascript which we've alredy been through and not found `fromPaths`

The only other place that looks like it may be is @cucumber/gherkin-utils or @cucumber/cucumber which both lead to the same repository https://github.com/cucumber/cucumber

In looking at the CHANGELOG.md it appears to be unreleased rather than in version 17.0.0?

Apon cloning of https://github.com/cucumber/cucumber-js I get a directory gherkin-streams which doesn't show in the github repository. Turns out `fromPaths` is actually in the cucumber/gherkin-streams directory of this repo. How does that work?

So I then npm install @cucumber/gherkin latest version (17.0.2) rather than 7.0.0-rc.0 and lo and behold, `fromPaths` is in there.

Am I correct in guessing that `fromPaths` will soon be turning up in a new NPM package called @cucumber/gherkin-streams when the next version 17.0.3 of @cucumber/gherkin is released/published?

So I can get the sources, pickles and gherkinDocuments but I don't see a way to filter the sources on `pickleFilter`?

**Comment by binarymist** [comment]
Almost there I think, I'll update this once coded and tested

**Comment by binarymist** [comment]
Hi @aslakhellesoy.

Can you please answer the outstanding questions from [here](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-803521785), specifically:

_Am I correct in guessing that fromPaths will soon be turning up in a new NPM package called @cucumber/gherkin-streams when the next version 17.0.3 of @cucumber/gherkin is released/published?_

I've done the [code changes](https://github.com/purpleteam-labs/purpleteam-app-scanner/pull/14), but I'm still struggling with:

> To me it sounds like that should be a simple replacement.

As I mentioned [here](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-803521785):

_I've worked out how to do the replecement, but it still appears as though the same functionality can not be replicated with fromPaths_

I've written some [tests and some additional scenarios](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/main/test/api/app/models/app.js#L59-L93) that should pass. The tests fail due to removed functionality (The algorithm from the removed `cucumber.getTestCasesFromFilesystem` that used to satisfy the tests I've written) and their isn't much point in implementing the additional test scenarios until we know we can make them pass.

**Comment by yopasa94** [comment]
I faced this issue some days ago and I replaced with 'parseGherkinMessageStream'

```
//This will return all the test id 
parseGherkinMessageStream({
      cwd: '',
      eventBroadcaster,
      eventDataCollector,
      gherkinMessageStream: gherkinMsgStream,
      order: 'defined',
      pickleFilter: new PickleFilter({
        cwd: '',
        tagExpression: cucumberTags,
      }),
    });
//returns list of scenarios as 'testsCases'
```

```
//Find all the information related to the scenario
      tests = testCases.map((result) => {
        const pickeTest = eventDataCollector.getPickle(result);
        const gherkinDoc = eventDataCollector.getGherkinDocument(pickeTest.uri);
        const lineNumber = formatterHelpers.PickleParser.getPickleLocation({
          gherkinDocument: gherkinDoc,
          pickle: pickeTest,
        }).line;
        return { uri: '../../' + pickeTest.uri, lineNumber };
      });
```

**Comment by binarymist** [comment]
Thanks @yopasa94 , I'm a bit tied up with some other work currently. I'll come back to this as soon as I get a gap.

**Comment by binarymist** [comment]
Thanks @yopasa94 . A few questions from your implementation if you would be so kind?

I assume the `parseGherkinMessageStream` is in @cucumber/cucumber/lib/cli/helper.js?

What are the following properties being passed as the object arguement to `parseGherkinMessageStream`, did you define them, if so how and where, as I'll need to replicate them:

* `eventDataCollector`
* `gherkinMessageStream`
* `formatterHelpers`

**Comment by binarymist** [comment]
Any feedback @yopasa94 ?

**Comment by aurelien-reeves** [comment]
As you have noticed, there have been a major refactoring of the internals of cucumber in the past few month.
Also, `@cucumber/gherkin-streams` has been released publicly and provide the `fromPaths` method that will help parsing given `.feature` documents.

This is not a transparent refactoring: the new API relies on [messages](https://github.com/cucumber/common/tree/main/messages).

@binarymist it would be easier for us to help with your issue with more explanation regarding your problem. Could you please give us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by binarymist** [comment]
There has been a lot of water under this bridge since I first posted this issue, so being concise may be difficult. I'll do my best though.

## Rephrasing

As per my very first message in this issue on 2 Dec 2020, `cucumber.getTestCasesFromFilesystem` did "exactly" what I and others needed it to do.

### What did I and others need it to do?

For us (purpleteam-labs) the main file involved (now and when it was doing what we needed it to do (last year)) in the Cucumber invocations is /src/api/app/models/app.js of the app-scanner.

In the past [`getActiveTestCases`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/92fca1c18c30805cea0acef3717945d6ff3eabcc/src/api/app/models/app.js#L141) did exactly what we needed it to do.

We needed it to [`getActiveTestCasesFromFilesystem`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/92fca1c18c30805cea0acef3717945d6ff3eabcc/src/api/app/models/app.js#L143). We still need this functionality.

We provide the paths to our feature files, actually the cucumber Cli did and still does this.

The [`pickleFilter`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/92fca1c18c30805cea0acef3717945d6ff3eabcc/src/api/app/models/app.js#L148) provided the details around what an active test case was, which I think was and is based on [`cucumber.tagExpression`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/92fca1c18c30805cea0acef3717945d6ff3eabcc/src/api/app/models/app.js#L131).

Simply put, we need the active test cases as a string based on the tags we initialise the Cucumber CLI with. Why? Because users of the system need a test plan, they need to know which feature files are going to be run when they start the test.

### Where are we now?

Currently [`getActiveFeatureFileUris`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/src/api/app/models/app.js#L141) passes [these tests](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/test/api/app/models/app.js#L27-L55).

Currently [`getActiveFeatureFileUris`](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/src/api/app/models/app.js#L141) does not pass [these tests](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/test/api/app/models/app.js#L59-L93) (I mentioned this in [this post](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-808828443)).

The names of the tests should explain what they are supposed to do, but currently do not.

All you need to do is compare the passing tests with the failing tests to see where the shortfall is.

### Thoughts, question, comments

So far I've setup everything as @aslakhellesoy has suggested. 

Do you recognise anything workable from @yopasa94 solution?

Basically what we're doing here is reimplementing functionality that has been removed but needed by myself and others.

**Comment by aurelien-reeves** [comment]
Did you explore `gherkinStream.fromPaths`? What is the situation with this?

Also, the suggestion from @yopasa94 was pretty interesting. Did you had the opportunity to take a look? `parseGherkinMessageStream` is a helper method in cucumber-js: https://github.com/cucumber/cucumber-js/blob/24ff9dc635ed25a32bdb6daf0028ecaf89569393/src/cli/helpers.ts#L46

You give too many references to your own code base. Please give minimum reproducible snippets here instead.

**Comment by binarymist** [comment]
> Did you explore gherkinStream.fromPaths? What is the situation with this?

Yes. I've just provided a link to it again. Here it is again https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/src/api/app/models/app.js#L160. This is what's under test.

> Also, the suggestion from @yopasa94 was pretty interesting. Did you had the opportunity to take a look?

Yes I thought so to, but sadly who knows where it is, and there are still unanswerd questions needed to take it further. Where is it? My comments on it [here](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-828158060), [here](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-849524710) and [here](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-852700148).

> parseGherkinMessageStream is a helper method in cucumber-js:

I thought it might be, as I mentioned [here](https://github.com/cucumber/cucumber-js/issues/1489#issuecomment-828158060).

@aurelien-reeves: Are you actually reading my comments, as you keep asking questions I've already answerd?

> You give too many references to your own code base. Please give minimum reproducible snippets here instead.

Ok, I can do this, but all I'll be doing is copy, pasting what I've already linked to. Then if you want to run it, you'll have to do even more work than simply clone the repo, `npm install` -> `npm test`

Thanks.

**Comment by aurelien-reeves** [comment]
> @aurelien-reeves: Are you actually reading my comments, as you keep asking questions I've already answerd?

I missed that one. But yes, I do read your responses.

You keep posting links to your code base. I won't go there. There is too many code. I won't take the time to understand how all your code base works.

Also I don't ask for you to copy paste your code here. I ask you for a minimal reproducible example of your issues / what you want to accomplish.

I do my best do keep helping you. Please try to simplify as much as possible your questions.

**Comment by binarymist** [comment]
* Clone: https://github.com/purpleteam-labs/purpleteam-app-scanner_cucumber-1489-repro
* `npm install`
* `npm test`

**Comment by aurelien-reeves** [comment]
Suggestion: https://github.com/purpleteam-labs/purpleteam-app-scanner_cucumber-1489-repro/pull/1

All test are passing now

**Comment by binarymist** [comment]
Thanks for that @aurelien-reeves.

This appears to asume that the `envelopes` array will always be in a specific order, that order being:

1. if there is a `gherkinDocument` `push` it. Then push the `gherkinDocument`s pickles in order from top down
2. if there is another `gherkinDocument` `push` it. Then push the `gherkinDocument`s pickles in order from top down
2. and so on

Is this assumption true?

If so great, it's so simple.

I also didn't know about the `pickleFilter.matches`, it seems very useful.

**Comment by binarymist** [comment]
Just looked into `fromPaths` and it appears that it's recursive `pipeSequentially` does exactly this.

**Comment by binarymist** [comment]
Big thanks @aurelien-reeves for getting this over the line!
