### ISSUE TITLE
API support to create step definition files.

### ISSUE THREAD

**Issue by Chris2011** [cucumber/cucumber-js#149]
Hi,

is it possible to implement such functionality, so some other can create plugins for IDEs as Netbeans or Eclipse so you can rightclick inside of your feature file and say generate step definition. This is very nice and I use SpecFlow with VS and this feature is great.

Regards

Chris

**Comment by jeremyrajan** [comment]
👍 
Yes, some sort of api function, which could create step definition funcs from feature files. That would idle, for creating and storing definition files. Unless, its not yet :)

**Comment by troublete** [comment]
Heya,
i'd actually welcome an API functionality to generate test snippets. Currently trying to implement cucumber in several services in our architecture and it would improve the workflow if there would be an functionality whereas based on JSON-formed scenarios, which are provided by the gherkin package API itself, It's possible to create code snippets for further use. 

I also debugged the code already a little bit. And found something like `StepDefinitionSnippetBuilder`. 

It would be enough, if somehow, the `StepDefinitionSnippetBuilder` would be made public/better accessible so it actually can be used in scripts or something like that. 

Best regards. :)
