### ISSUE TITLE
Regression introduced with commander update (v6)

### ISSUE THREAD

**Issue by kamarkiewicz** [cucumber/cucumber-js#1511]
https://github.com/cucumber/cucumber-js/pull/1472 seem to introduce regression for `--format-options` flag. It should handle JSON input, i.e. `--format-options {"scenarioAsStep": false}`, but after the version change I couldn't find a way to pass the custom options to CLI.

**Comment by davidjgoss** [comment]
@kamarkiewicz could you confirm which version of cucumber you're running? The change you mention isn't released yet.

**Comment by kamarkiewicz** [comment]
Sure, I just checked out `@cucumber/cucumber` 7.0.0-rc.0 today.
