### ISSUE TITLE
ci tooling change?

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-js#1513]
See:

- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://blog.travis-ci.com/oss-announcement

Travis is looking like slightly shaky ground now.

Is it worth giving GitHub Actions a try?

cc @charlierudolph @aslakhellesoy

**Comment by aslakhellesoy** [comment]
Yes - let’s move to GitHub Actions. We discussed this in the [weekly meeting](https://docs.google.com/document/d/1ewOKjaK5F17pwv7wtiaBFWCdzHQBXqQMCxqkwWKVmX8/edit) on 10th dec too

**Comment by davidjgoss** [comment]
Okay, [we have a workflow](https://github.com/cucumber/cucumber-js/blob/master/.github/workflows/test.yml) in now that tests with our supported Node versions on Linux and Windows. That covers most of what we were doing with Travis and Appveyor.

The only other thing is coverage. Right now we run with coverage on Node 14 but don't seem to do anything with the result.

**Comment by davidjgoss** [comment]
I see https://coveralls.io/ used a lot in other open source projects.

**Comment by davidjgoss** [comment]
@charlierudolph how do you feel about adding coveralls?

**Comment by charlierudolph** [comment]
Coverage is currently sent to coveralls but not reported on PRs. I'm good with adding coveralls and getting visibility for it on PRs

**Comment by charlierudolph** [comment]
Thanks for doing this @davidjgoss. I just disabled the appveyor project so that should stop triggering builds

**Comment by aslakhellesoy** [comment]
Thanks a lot for doing this @davidjgoss
