### ISSUE TITLE
new unsatisfied peer dependencies with latest verion

### ISSUE THREAD

**Issue by travi** [cucumber/cucumber-js#1516]
i've been receiving renovate PRs for the new v7 in some of my projects now that you've promoted it to latest. i had upgraded a few of my projects to the prerelease of v7 already without issue.

however, i'm now seeing some new failures due to unsatisfied peer dependencies with the new version. you can see an example of this in [this build output](https://github.com/form8ion/add-package-to-monorepo/pull/40/checks?check_run_id=1591286270#step:5:69). i use `npm ls` to ensure that peer dependencies are compatible (it will exit non-zero if there is a conflict).

the projects that i'm seeing these issues in are not react projects, so i have no reason to depend on the peer packages other than because of the use of cucumber, so i would prefer not to depend on them directly. could you please satisfy these peer dependencies on your end by making them prod dependencies of cucumber?

**Comment by davidjgoss** [comment]
Thanks for raising @travi 

These React-related dependencies come via our HTML formatter and some React libraries it uses.

```
peer dep missing: react@^16.3.2, required by react-accessible-accordion@3.3.3
peer dep missing: react-dom@^16.3.3, required by react-accessible-accordion@3.3.3
```

There's already a PR merged to allow React 17 for `react-accessible-accordion` here https://github.com/springload/react-accessible-accordion/pull/307 so hopefully that'll get released shortly and we can bring that in.

```
peer dep missing: @types/react@>=16, required by react-markdown@5.0.3
```

This seems like a mistake to me, I'll raise it with that project.

**Comment by travi** [comment]
sounds great. thanks a lot for digging in on this :)

**Comment by ericlanteigne-quest** [comment]
Has there been any update on this? We are also encountering this when installing @cucumber/cucumber version 7.0.0.
`npm ERR! peer dep missing: @types/react@>=16, required by react-markdown@5.0.3`

**Comment by davidjgoss** [comment]
Hey @ericlanteigne-quest - the fix is done and this should be released soon.

**Comment by davidjgoss** [comment]
7.1.0 was released today including the fix for this https://www.npmjs.com/package/@cucumber/cucumber/v/7.1.0
