### ISSUE TITLE
[bug] Incorrect type for messages.ITimestamp

### ISSUE THREAD

**Issue by jan-molak** [cucumber/cucumber-js#1519]
Hey team!

Cucumber Messages protocol requires `Duration.seconds` to be represented as [int64](https://github.com/cucumber/messages-javascript/blob/831d27f2bc0236d66bf243d9d72bed4f457f8207/messages.proto#L118). This means that when the type is serialised to JSON, it is represented as `string`. 

For example:
```
{'testStepStarted':{'timestamp':{'seconds':'1609258470','nanos':694000000},'testStepId':'7d5575a4-0720-4060-ba70-ce70e4bd4713','testCaseStartedId':'084517b4-0f9d-4043-a9af-b2799a911655'}}
{'testStepFinished':{'testStepResult':{'status':'PASSED','duration':{'seconds':'0','nanos':0}},'timestamp':{'seconds':'1609258470','nanos':696000000},'testStepId':'7d5575a4-0720-4060-ba70-ce70e4bd4713','testCaseStartedId':'084517b4-0f9d-4043-a9af-b2799a911655'}}
```

Note that `int32` `nanos` are represented as `number`, but `int64` `seconds` are represented as `string`. This behaviour is correct and compatible with the [specification](https://developers.google.com/protocol-buffers/docs/proto3#json).

However, type definitions generated for `@cucumber/messages` are incorrect and look as follows:

```
/** Properties of a Timestamp. */
interface ITimestamp {

    /** Timestamp seconds */
    seconds?: (number|Long|null);

    /** Timestamp nanos */
    nanos?: (number|null);
}
```

In the type definition above you'll notice that `seconds` are incorrectly typed as `(number|Long|null)` while they should've been typed as `(string|null)`.

I've also noticed that the Cucumber codebase contains examples of both types too. Check out:
- a [test fixture](https://github.com/cucumber/cucumber-js/blob/eaaca2d7063c34aa17e33d66fc386c46ec99dd25/features/fixtures/formatters/retried.message.json.ts#L81) representing `seconds` as `string`
- a [unit test](https://github.com/cucumber/cucumber-js/blob/eaaca2d7063c34aa17e33d66fc386c46ec99dd25/src/formatter/usage_json_formatter_spec.ts#L45) representing `seconds` as `number`
- another [unit test](https://github.com/cucumber/cucumber-js/blob/4e6a9ee53708f8ce17dd7d93687c67fa7ef6a97f/src/runtime/pickle_runner_spec.ts#L300) using `string`

Tagging @aslakhellesoy for visibility.

**Comment by davidjgoss** [comment]
So as I understand it there's a distinction between how the value is serialised to NDJSON (as a string, like you say) vs how protobufjs wants to realise that value in JavaScript (as a Long, if it can, and a plain number otherwise).

Worth checking with @aslakhellesoy about the broader direction here, because I know there was some discussion about switching to the "minimal" protobufjs library that doesn't have the normal runtime - I'd need to test that to see how it handles int64 values.

(Kinda related: https://github.com/protobufjs/protobuf.js/issues/1151)

**Comment by jan-molak** [comment]
Yeah, I think so. Also, the protobuf library used seems to generate other invalid types, like `Long`:

```typescript
// messages.d.ts
            interface ITimestamp {

                /** Timestamp seconds */
                seconds?: (number|Long|null);

                /** Timestamp nanos */
                nanos?: (number|null);
            }
```

This causes the following compilation issue:
```
node_modules/@cucumber/messages/dist/src/messages.d.ts(642,35): error TS2304: Cannot find name 'Long'.
```

A workaround (a.k.a. nasty hack ;-) ) is to enable `skipLibCheck` in any project that depends on `@cucumber/messages`.

**Comment by davidjgoss** [comment]
7.1.0 was released today including the fix for this https://www.npmjs.com/package/@cucumber/cucumber/v/7.1.0
