### ISSUE TITLE
Guidelines for upgrade to cucumber 7?

### ISSUE THREAD

**Issue by Iliev88** [cucumber/cucumber-js#1520]
Hello,

any guidelines how to upgrade from cucumber 5.1.0 to @cucumber/cucumber 7.0.0?

**Comment by davidjgoss** [comment]
Hi @Iliev88, we have a [migration guide in the changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#migration-guide), this should help with at least 6 -> 7. I'd recommend first doing 5 -> 6 and looking further back in the changelog for a steer on that. IIRC the main change there was around the introduction of the retry mechanism.

I'll keep this issue open as I think we should surface some migration info on the main readme - thanks.

**Comment by Iliev88** [comment]
Hi @davidjgoss Thanks for replying.
I'd read the migration guide once I opened the current ticket.
I've tried to migrate from  5 -> 6 and then to 7 but still I can see problems.

My issue is when I am declaring @cucumber/cucumber module then I can't use properties under world interface.

`declare module "@cucumber/cucumber" {
  interface World {
    loginPage: LoginPage;
   }
}`

![image](https://user-images.githubusercontent.com/25150497/103514708-e086c180-4e75-11eb-9da1-454c5754822f.png)


Maybe I am missing something obvious..

**Comment by davidjgoss** [comment]
`World` is a class not an interface - I think it was maybe an interface in the old DefinitelyTyped typings.

If you have a custom world you can just extend `World` like:

```typescript
export class CustomWorld extends World {
    constructor(options: IWorldOptions) {
        super(options);
        // your stuff
    }
}
```

I'll add this to the section about TypeScript, thanks for raising.
