### ISSUE TITLE
How to import 'pickle' and 'event' in Cucumber V7?

### ISSUE THREAD

**Issue by VivekLande** [cucumber/cucumber-js#1538]
Hi,

I am migrating cucumber from V6 to V7. In V7 you have removed @type/cucumber from where in V6 we were importing 'pickle' and 'event' object which is not a case in V7.  I can't find exports for these objects and many others.

Could you please suggest?

Thank you.

**Comment by VivekLande** [comment]
Hello,

Can someone please help and suggest?

**Comment by yopasa94** [comment]
Did you try with PickleFilter from @cucumber/cucumber ?

**Comment by davidjgoss** [comment]
Sorry for the late reply @VivekLande.

With "pickle", there is a new object structure for that which is part of the standardised messages schema now. This is the `pickle` that is part of the result object passed to your `After` hook function. I've described the change a bit in #1692 including a link to [its schema definition](https://github.com/cucumber/common/blob/main/messages/jsonschema/Pickle.json).

The model for events changed completely as part of 7.0.0, so the previous events described in the `@types/cucumber` package are no longer emitted, and now we emit [`envelope`](https://github.com/cucumber/common/blob/main/messages/jsonschema/Envelope.json) events, each containing a standardised message object. If you have any issues using the messages to e.g. build a formatter, please drop a question in the [Slack or forum](https://cucumber.io/docs/community/get-in-touch/) and you should get some help. The [built-in formatters](https://github.com/cucumber/cucumber-js/tree/main/src/formatter) are a good reference point for this also.
