### ISSUE TITLE
[docs] Custom Formatters doc mentions a deprecated formatter

### ISSUE THREAD

**Issue by hdorgeval** [cucumber/cucumber-js#1546]
Hello Cucumber team,

Unless I am wrong, it seems to me that the [Extending Built-Ins section](https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md#extending-built-ins) in `custom_formatters.md` mentions that `PrettyFormatter` inherits from `SummaryFormatter` , but I do not see any builtin `Pretty` formatter in the v7 code base.

**Comment by davidjgoss** [comment]
Good spot @hdorgeval, thanks for raising. I've fixed this under #1540.

In the meantime we do now have an [official pretty formatter](https://www.npmjs.com/package/@cucumber/pretty-formatter) available as a separate package, if you're interested in trying it out.

**Comment by hdorgeval** [comment]
Hi @davidjgoss , thank you for your feedback. I am very glad to know about this new official pretty formatter. 
I will try it asap.
