### ISSUE TITLE
HTML Formatter: Couldn't display image/png;base64 image because it wasn't base64 encoded

### ISSUE THREAD

**Issue by hdorgeval** [cucumber/cucumber-js#1550]
Given I am attaching a base64-encoded image with the following code:

```js
const screenshot: string = <a base64-encoded image generated by playwright>;
this.attach(screenshot, 'image/png');
```
When I am using the internal HTML Formatter in cucumber-js v7
And I display the generated html file
Then I see this message `Couldn't display image/png;base64 image because it wasn't base64 encoded` instead of seing the image.

My analysis:

The HTML formatter needs to have a content encoding set to `BASE64` in order to display images:

`Attachment.tsx`  (@cucumber/react):
```tsx
function image(attachment: messages.IAttachment) {
  if (
    attachment.contentEncoding !== messages.Attachment.ContentEncoding.BASE64
  ) {
    return (
      <ErrorMessage
        className="cucumber-attachment"
        message={`Couldn't display ${attachment.mediaType} image because it wasn't base64 encoded`}
      />
    )
  }
  return (
    <details>
      <summary>Attached Image</summary>
      <img
        alt="Embedded Image"
        src={`data:${attachment.mediaType};base64,${attachment.body}`}
        className="cucumber-attachment cucumber-attachment__image"
      />
    </details>
  )
}
```
But (unless I am wrong)`cucumber-js v7` sets the encoding to `IDENTITY` instead of `BASE64`:
`index.ts:54` (attachment_manager)
```ts
this.createStringAttachment(data, {
        encoding: messages.Attachment.ContentEncoding.IDENTITY,
        contentType: mediaType,
      })
``` 

Either the HTML formatter should remove the check to the content encoding (because by design attached images are always base64 encoded) or cucumber-js should handle it correctly when the media type is an image.

Thanks

**Comment by davidjgoss** [comment]
Thanks @hdorgeval, working on this.

**Comment by hdorgeval** [comment]
Hi @davidjgoss , thank you 👍
