### ISSUE TITLE
Incompatible with Node v15?

### ISSUE THREAD

**Issue by fogshot** [cucumber/cucumber-js#1569]
I just tried a basic install of a new cucumber project running Node v15.6 under MacOS.
running cucumber-js in this empty project resulted in the following error (see attached file for full output):

[Error: Cannot find module 'uuid'](https://github.com/cucumber/cucumber-js/files/5939436/error.log)

Downgrading to Node v12 and reinstalling helped. Is there a dependency on uuid that needs to be updated?

**Comment by davidjgoss** [comment]
@fogshot I'm not able to reproduce this on a Node 15 install locally (also on MacOS).

`uuid` is a dependency of `@cucumber/messages` and so after a successful install you should see it if you run `npm ls uuid`:

```
$ npm ls uuid

my-project@0.0.0 /Users/davidgoss/Projects/my-project
└─┬ @cucumber/cucumber@7.0.0
  └─┬ @cucumber/messages@13.2.1
    └── uuid@8.3.2
```

Could you check for any install errors? Also if you could post a repo (including package-lock.json) that would help.
