### ISSUE TITLE
Extreme stack traces

### ISSUE THREAD

**Issue by TheLudd** [cucumber/cucumber-js#157]
I am just trying out cucmber-js and I notice that when a test fails, an enormous stack trace is produced (160 lines). This makes it really hard to understand which test failed and why. Is there some kind of workaround or solution to this problem?

**Comment by cades** [comment]
Mocha encounter the [same problem](https://github.com/mochajs/mocha/issues/545), and there's a nice [solution](https://github.com/keyvanfatehi/js-simple-stacktrace) using pipe to shorten stack trace.

**Comment by dtinth** [comment]
I think I just found a gem. [clarify](https://www.npmjs.com/package/clarify) is a module that removes Node.js-related stack frames from the stack trace. Under the hood, it uses [stack-chain](https://www.npmjs.com/package/stack-chain) module, which allows stack frames to be extended, filtered, and replaced.

Therefore, I created a package `hide-stack-frames-from`, and you can use it like this:

```js
require('hide-stack-frames-from')('cucumber')
```

**Comment by jlin412** [comment]
Thai, How about submitting a PR using this code to give an option to hide
node.js stack trace?

**Comment by dtinth** [comment]
@jlin412 I am already happy putting that line of code in some `support` file. Therefore, although it doesn't hurt to do so, I don't see the need of it being in Cucumber's core.

I also use it to hide stack frames from Bluebird, and etc. That's why I prefer being able to configure all of them from a single supporting script.

**Comment by sebs** [comment]
```
require('hide-stack-frames-from')('cucumber')
```

Works like a charms and fixes my problem. thanks

**Comment by plato-cambrian** [comment]
thanks @pumbers !

**Comment by floribon** [comment]
Just a heads up, not sure if there is a better solution today on March 2016.

I tried using `hide-stack-frames-from` but it was failing on some scenario, and would leave some node related traces.

Instead I used @laurelnaiad with the addition of the error message. Indeed the snippet was removing any custom message sent by `throw new Error` or a failing promise. However some cucumber error messages were still ugly, such as:

```
UnknownError: unknown error: Element is not clickable at point (580, 60). Other element would receive the click: <div class="collapse navbar-collapse">...</div>
        (Session info: chrome=48.0.2564.116)
        (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.3 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 36 milliseconds
      Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
      System info: host: 'bookmac.local', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_05'
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/09/5x0xspyd11sd9lm1423fsrxw0000gn/T/.org.chromium.Chromium.EiV0Gx}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=48.0.2564.116, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
      Session ID: 8f132e9736404994a5d7c0610574d8e2
```

So at the end I ended up keeping only the first line of any error message:

```
var message = err.message.split('\n')[0];
return message + (results.length ? results.join('\n') : '');
```

**Comment by leegee** [comment]
FWIW, as a developer using Cucumber JS for BDD, I like to have a full stack trace.

As a developer creating BDD reports for the rest of the team, I like to use various reporter modules that hide the trace in an HTML report.
