### ISSUE TITLE
Couldn't display base64:image/png attachment because the media type is unsupported

### ISSUE THREAD

**Issue by saurabh-deep** [cucumber/cucumber-js#1574]
With Cucumber v7.0 built-in HTML reporter, I am able to attach the screenshots but the generated HTML fails to load the screenshots with the below mentioned errors.

If I provide the mime type as `image/png`, it shows error # 1 in the HTML output. 
```Couldn't display image/png image because it wasn't base64 encoded```

If I provide mime type asa `base64:image/png`, it shows error # 2 in the HTML output.
```Couldn't display base64:image/png attachment because the media type is unsupported.```

I am using Selenium Webdriver to capture the screenshot and it returns the screenshot with base64 encoding. Therefore, the second approach above should work correctly. I tried examples as shown in [this](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md) documentation page which was last updated a week ago, but it doesn't help at all.

Can someone please help me get past this blocker issue? 

Thanks in advance!
Saurabh

**Comment by davidjgoss** [comment]
The issue was fixed in https://github.com/cucumber/cucumber-js/pull/1552 and we should have a release out soon including that change - sorry for the delay.

As a temporary workaround, you could _decode_ your base64-encoded string into a buffer and pass that to the `attach` function, which should work correctly.

**Comment by saurabh-deep** [comment]
Thank you again @davidjgoss!

**Comment by davidjgoss** [comment]
7.1.0 was released today including the fix for this https://www.npmjs.com/package/@cucumber/cucumber/v/7.1.0

See https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md for more info.
