### ISSUE TITLE
error: unknown option '--defaultTimeoutInterval'  with Cucumber-7

### ISSUE THREAD

**Issue by VivekLande** [cucumber/cucumber-js#1576]
Hi, I am getting below error while executing tests it with Cucumber-7, it's working absolutely fine with Cucumber-6.
Could you please provide any resolution to it? it doesn't have clear stack trace as well so can understand from where it raising the issue.
Your help much appreciated!
![image](https://user-images.githubusercontent.com/16791810/107483742-7fa28580-6ba7-11eb-878d-27618cb96569.png)

**Comment by davidjgoss** [comment]
cucumber-js doesn't have a `--defaultTimeoutInterval` option on the CLI. But it looks like you're running a different tool there. Can you provide a full repro example via a github repo?
