### ISSUE TITLE
Error: function timed out, ensure the promise resolves within - Cucumber js

### ISSUE THREAD

**Issue by rindia** [cucumber/cucumber-js#1578]
I am using protractor with cucumber js i have all function with async and await and also set global timeout

`var {setDefaultTimeout} = require('cucumber'); setDefaultTimeout(60 * 1000);
`
```
Then('I click on tab', async ()=> {
  
    await organizationOperation.clickHeaderTab();

  });
```
Question - if i use wrong xpath/element is not located in UI, in that case getting below error

Error: function timed out, ensure the promise resolves within 60000 milliseconds

It should throw an error locator not found (locator text)

cucumber version - 6.0.5

**Comment by amerrit2** [comment]
You want the `clickHeaderTab` to timeout *before* the cucumber step times out.  If the step times out, it has no way of knowing where the currently waiting event-callback might be waiting.

**Comment by rindia** [comment]
@amerrit2  so what is the best way to handle this situation ..?

**Comment by davidjgoss** [comment]
(Going to close as this kind of thing is best posted the Slack or the smartbear forums, see https://cucumber.io/docs/community/get-in-touch/)

Consider setting the timeout thresholds for your instrumentation (webdriver etc) much lower than the one for cucumber. The cucumber one is then really a guard rail to ensure if there's an issue with your code it doesn't hang forever.

**Comment by eliezercazares** [comment]
> @amerrit2 so what is the best way to handle this situation ..?

amerrit2 already mentioned it. if you have a default timeout in playwright or selenium of 1 minute for all elements (implicit) or if you have even explicit timeouts that are lesser than the timeout for cucumber, it will behave as requested. If I understood correctly.
