### ISSUE TITLE
Getting error while migrating cucumberjs from version 6 to 7

### ISSUE THREAD

**Issue by code4muktesh** [cucumber/cucumber-js#1581]
TS2305: Module '/node_modules/@cucumber/cucumber/lib' has no exported member 'HookCode'.   
` import { HookCode } from "@cucumber/cucumber";`

Now the types are deprecated from version 7 as per https://www.npmjs.com/package/@types/cucumber

**Comment by code4muktesh** [comment]
Found it as:
`import { TestCaseHookFunction as HookCode } from "@cucumber/cucumber/lib/support_code_library_builder/types";`

**Comment by aslakhellesoy** [comment]
If the `TestCaseHookFunction` type is needed by client code we should expose it properly via `@cucumber/cucumber`, not some arbitrary path inside the library that might change in the future.

@code4muktesh can you give us an example how you use this type?

**Comment by code4muktesh** [comment]
@aslak_hellesoy we had written some custom formatter with v5/6. That time, HookCode was available under the @types/cucumber.

**Comment by davidjgoss** [comment]
@code4muktesh curious why you need to access the support code like hook functions when implementing a formatter - what problem are you solving?

**Comment by code4muktesh** [comment]
@davidjgoss  It is the old code that was developed with version v5/v6 and consuming by multiple modules that have own implementation top over them we are planning to upgrade it to v7 with minimum impact.
