### ISSUE TITLE
errorMessage and errorStack functions are not found

### ISSUE THREAD

**Issue by code4muktesh** [cucumber/cucumber-js#1582]
In the v5 and V6, errorMessage and errorStack was present as
https://github.com/cucumber/cucumber-js/blob/v6.0.5/src/formatter/get_color_fns.js#L22

With v7 unable to find the same.
https://github.com/cucumber/cucumber-js/blob/master/src/formatter/get_color_fns.ts#L32

**Comment by aslakhellesoy** [comment]
Why is this a problem?

**Comment by code4muktesh** [comment]
@aslakhellesoy  we had written some custom formatter with v5/6 and using errorMessage and errorStack functions to handle error logs. Now, migrating to v7 so trying to find the same.

**Comment by aurelien-reeves** [comment]
I think if you submit a PR to bring those back, and also the other missing ones, there are good chances that it would be accepted ☺

**Comment by davidjgoss** [comment]
You could also consider using `colors` directly, given that `errorMessage` just delegates to `colors.red`.

**Comment by aurelien-reeves** [comment]
@davidjgoss that was my first though too

Then I looked at custom formatters documentation, and we easily find the get_color_fns module, so it could be considered as public api. Thus, maybe @code4muktesh is not the only one facing that issue. That is why I suggested to bring those props back.
