### ISSUE TITLE
@types/cucumber@7.0.0 does not include index.d.ts 

### ISSUE THREAD

**Issue by DiV666** [cucumber/cucumber-js#1605]
Hi,

When i install @types for v7 this not include the type file index.d.ts
`npm i --save-dev @types/cucumber@7.0.0`

![image](https://user-images.githubusercontent.com/408546/109669253-39bb5a80-7b72-11eb-9d77-bfa5d657006b.png)

Regards

**Comment by davidjgoss** [comment]
You no longer need to use `@types/cucumber` since 7.0.0, we ship our own typings with the main package. See also:

- https://github.com/cucumber/cucumber-js/blob/master/docs/migration.md#typescript
- https://www.npmjs.com/package/@types/cucumber
