### ISSUE TITLE
Documentation not reflecting new node module set up

### ISSUE THREAD

**Issue by HuckleberryCarignan** [cucumber/cucumber-js#1606]
Hi, I'm trying to update to @cucumber/cucumber, but much of the documentation still seems to reflect the old node module set up.

Also, the @cucumber/cucumber npm page states that the 7.x.x. is (Not yet released).  
Is it released or not?

**Comment by davidjgoss** [comment]
@HuckleberryCarignan we have release 7.0.0 - I think unfortunately we missed that bit of the readme at the time we published to npm.

There's a migration guide here that might be helpful https://github.com/cucumber/cucumber-js/blob/master/docs/migration.md

Can you highlight any pieces of documentation that are outdated (besides the npm package page)?

**Comment by davidjgoss** [comment]
Closing but please open a new issue if you find issues with documentation at master. Thanks!
