### ISSUE TITLE
setDefaultTimeout is not working with @cucumber/cucumber 7.0.0

### ISSUE THREAD

**Issue by manramu22** [cucumber/cucumber-js#1610]
setDefaultTimeout is not working with @cucumber/cucumber 7.0.0
The same code is working with cucumber 6.0.5. 
But 7.0.0. is not respecting timeout set through setDefaultTimeout method. It always defaulted to 5000ms. 

I am using puppeteer with cucumber.

Any idea on the issue? Thanks in advance. Any help would be much appreciated.

**Comment by charlierudolph** [comment]
We have [feature tests](https://github.com/cucumber/cucumber-js/tree/v7.0.0/features) that validate this is working.

Given the rename of the module with the upgrade to version 7, puppeteer maybe isn't importing the old module?

Please open an issue with that library.

**Comment by manramu22** [comment]
> We have [feature tests](https://github.com/cucumber/cucumber-js/tree/v7.0.0/features) that validate this is working when cucumber standalone.
> 
> Given the rename of the module with the upgrade to version 7, puppeteer maybe is importing the old module?
> 
> Please open an issue with that library.

Followed the steps on document https://github.com/cucumber/cucumber-js/blob/master/docs/migration.md as is while migrating, not sure how puppeteer picks old cucumber library in this case

**Comment by aslakhellesoy** [comment]
Puppeteer does not depend on cucumber, so I don't understand what puppeteer has to do with this.

@manramu22 can you provide a MCVE to reproduce this?

**Comment by charlierudolph** [comment]
Sorry if I made a wrong assumption. I was thinking you were using some other tool that wrapped cucumber. But appears you can us puppeteer. We need more details to be able to determine the issue. A minimal repo that reproduces the issue would be great

**Comment by manramu22** [comment]
> Sorry if I made a wrong assumption. I was thinking you were using some other tool that wrapped cucumber. But appears you can us puppeteer. We need more details to be able to determine the issue. A minimal repo that reproduces the issue would be great

@charlierudolph Thanks for responding. I have placed the code to reproduce this issue in the following repos. They are exactly same except for cucumber version. Also, readme file has steps to run.
Cucumber 6 with puppeteer => https://github.com/manramu22/cucumber6-puppeteer.git
Cucumber 7 with puppeteer => https://github.com/manramu22/cucumber7-puppeteer.git

And following the tech stack
OS => macOS Big Sur (v11.2.3)
Browser => Google Chrome
node -v => v15.0.1
npm -v => 6.14.8

Appreciate your help. Thanks in advance

**Comment by davidjgoss** [comment]
@manramu22 thanks for posting the repos, that helped.

Here's how I was able to get it working on cucumber 7:
https://github.com/manramu22/cucumber7-puppeteer/pull/1

Basically I moved the call to `setDefaultTimeout` outside of the hook. I don't think it's designed to be called from the support code - we "finalise" certain things before we actually start the test run so it may be that in cucumber 7 the call from the hook is too late to be effected. I'll do a PR to update our documentation.

**Comment by manramu22** [comment]
> @manramu22 thanks for posting the repos, that helped.
> 
> Here's how I was able to get it working on cucumber 7:
> [manramu22/cucumber7-puppeteer#1](https://github.com/manramu22/cucumber7-puppeteer/pull/1)
> 
> Basically I moved the call to `setDefaultTimeout` outside of the hook. I don't think it's designed to be called from the support code - we "finalise" certain things before we actually start the test run so it may be that in cucumber 7 the call from the hook is too late to be effected. I'll do a PR to update our documentation.

Thanks for this @davidjgoss . Fix perfectly works

**Comment by plocket** [comment]
Do do this inside a hook (like when you define a "Step"), there is a way, though it's dangerous. You can use a custom timeout in this way in v8: https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/timeouts.md#disable-timeouts

> **DO NOT USE THIS UNLESS ABSOLUTELY NECESSARY**
> 
> Disable timeouts by setting it to -1.
> If you use this, you need to implement your own timeout protection.
> Otherwise the test suite may end prematurely or hang indefinitely.
> The helper `wrapPromiseWithTimeout`, which cucumber-js itself uses to enforce timeouts is available if needed.
> 
> ```javascript
> var {Before, Given, wrapPromiseWithTimeout} = require('@cucumber/cucumber');
> 
> Given('the operation completes within {n} minutes', {timeout: -1}, function(minutes) {
>   const milliseconds = (minutes + 1) * 60 * 1000
>   return wrapPromiseWithTimeout(this.verifyOperationComplete(), milliseconds);
> });
> ```

In v7, it's still dangerous and you'll also need to make your own `wrapPromiseWithTimeout`. See https://github.com/cucumber/cucumber-js/blob/main/src/time.ts#L42, though that's more complicated because of other things the cucumber library is doing with that stuff. This is how we wrote it:

```js
module.exports = async function wrapPromiseWithTimeout (
  promise,
  timeoutInMilliseconds,
  timeoutMessage
) {
  /** Race between a timeout and another function and clean up
  *    async afterwards.
  * 
  * Taken from https://github.com/cucumber/cucumber-js/blob/main/src/time.ts#L42-L59
  */
  if ( timeoutMessage === '' ) {
    timeoutMessage = `Action did not complete within ${ timeoutInMilliseconds } milliseconds`;
  }

  let timeoutId;
  const timeoutPromise = new Promise((resolve, reject) => {
    timeoutId = setTimeout(() => {
      reject(new Error( timeoutMessage ))
    }, timeoutInMilliseconds)
  });

  return await Promise.race([ promise, timeoutPromise ]).finally(() =>
    clearTimeout(timeoutId)
  );
};
```
