### ISSUE TITLE
And & But Steps

### ISSUE THREAD

**Issue by jose-dataka** [cucumber/cucumber-js#1615]
Hi there,

Have _And & But Steps_ been integrated or developed in the current version?
Will _And & But Steps_ be added like When & Then steps? 

Thanks for your time.

**Comment by aslakhellesoy** [comment]
You can use `Given`, `When`, `Then`, `And` and `But` in Gherkin documents. The latter two are syntactic sugar if you have multiple `Given`, `When` or `Then`:

```gherkin
Given the Kettle costs $99
And the Kettle is out of stock
``` 

In Step Definitions you can use `Given`, `When` and `Then`. You'd use `Given` to implement both of the step definitions alone.
