### ISSUE TITLE
Add step hooks

### ISSUE THREAD

**Issue by jmaxxz** [cucumber/cucumber-js#162]
I am trying to port a test suite from specflow to cucumber.js, and have found the hooking of steps very useful for snapshotting state changes which take place in the when block. This would be a really nice feature to have in cucumber.js.

https://github.com/techtalk/SpecFlow/wiki/Hooks

Cucumber has this feature as well:
https://github.com/cucumber/cucumber/wiki/Hooks

**Comment by tunovic** [comment]
Does this still work? I also see this issue https://github.com/cucumber/cucumber-js/issues/997
