### ISSUE TITLE
Request for junit formatter

### ISSUE THREAD

**Issue by mortelee** [cucumber/cucumber-js#1620]
Hi all

With cucumber v7 the cucumber-junit-formatter is not working anymore.
Q1: Has anyone already created a junit formatter (for Cucumber v7) that can be shared?
Q2: Can a junit formatter be added as default formatter in cucumber-js

Regards

Marco

**Comment by aurelien-reeves** [comment]
`cucumber-ruby` embed a junit formatter
`cucumber-jvm` too

I would say that your request seems legitimate actually

**Comment by aslakhellesoy** [comment]
Closing this as a dupe of https://github.com/cucumber/cucumber/issues/871
