### ISSUE TITLE
When AssertionError is called in another method cucumber report is empty

### ISSUE THREAD

**Issue by cvacalares** [cucumber/cucumber-js#1622]
Hi!
I just started learning JS and trying to be familiar with it.
I am currently using Nightwatchjs to try test automation.

I noticed that if the Assert is not in the step definition (in another method) and when the assert fails, the cucumber report json file is empty (0KB). Hence, I can't make a report.
//Empty cucumber report json
const { client } = require("nightwatch-api");
Then(/^Validate Assert is thrown from a method$/, async () => {
     await callAssert();
}

async function callAssert(){
   await client.expect("1").equal("2");
}

If the Assert is in the step definition and when assert fails, it generates a cucumber report json file with contents.
//Cucumber report json generated
Then(/^Validate Assert is thrown inside a step definition$/, async () => {
await client.expect("1").equal("2");
}

I'm using CucumberJS 6.0.5.

Thanks.

**Comment by aslakhellesoy** [comment]
Can you share a small repo that reproduces this please?

**Comment by cvacalares** [comment]
When the assert is in a method that is being called, it throws this error.
NightwatchAssertError: Error while running "equal" command: Failed [equal]: (Inside Method PDF) - expected "2" but got: "1" (0ms)
The After hook never gets called so the cucumber report json file is empty.
Is this a cucumberjs issue or Nightwatchjs issue?

**Comment by cvacalares** [comment]
I found out the reason. The assert is async.
I have to wrap my function in promise as I await the function to finish.
Closing this issue.
Thanks.

**Comment by cvacalares** [comment]
I found out the reason. The assert is async.
I have to wrap my function in promise as I await the function to finish.
Closing this issue.
Thanks.

**Comment by Golshy** [comment]
Hey @cvacalares can you show how you wrapped the function in a promise? I think I'm experiencing the same issue where my Cucumber Reports are not generating after a failed test step.

**Comment by cvacalares** [comment]
I wrapped the method with async. It solved my issue.

ValidateCartPriceSummaryPDF: async function (pdf, table) {
    const parseCartPDF = this.parseCartPriceSummaryPDF(pdf);

    for (column of table.raw()[0]) {
      for (i = 0; i < table.hashes().length; i++) {
        switch (column) {
          case "Currency":
            if (i == 0) {
              client.assert.equal(
                parseCartPDF["Currency"],
                table.hashes()[i][column],
                "Currency"
              );
            }
            break;

**Comment by Golshy** [comment]
Thanks so much! 

I'm currently encountering an issue with my NightWatch scripts in that, whenever there is a `NightwatchAssertError` it throws an unhandledRejection and as a result cucumber reports are not created. 

You wouldn't happen to have any clue why this occurs would you?

**Comment by cvacalares** [comment]
I am not sure why it is happening at your end.
Is the json report file still gets generated even after the test failures?
What I did was move the report generator to another script.
"test:chromeWeekly": "mkdirp report && cucumber-js --require cucumber.conf.js --require src/step_definitions src/features --format @cucumber/pretty-formatter --format json:report/cucumber_report.json && npm run report",
"report": "node reporter.js"
So as long as there is the json report, you can run the report generator at the end.

**Comment by rohankarkhanis** [comment]
Even I am facing the same issue. My function is already async howevwr if assert fails then the cucumber report does not capture it as a failure. Pls help !

**Comment by Golshy** [comment]
I think some of the async functions will interfere with cucumber so you need to be careful. I found that I was getting NightWatchAssertError after I made a particular step-def async, when I reverted it back to non-async, the reports were generated again.
