### ISSUE TITLE
Why there is no Before/After feature to be run once before specific feature file 

### ISSUE THREAD

**Issue by Amrkamel1** [cucumber/cucumber-js#1638]
I believe this is so useful and need for many cases, is there reason cucumber doesn't support this hooks

**Comment by davidjgoss** [comment]
Cucumber doesn't run features as such, it runs scenarios, and a feature is mostly a way to group those in the source.

You can make a `Before` or `After` hook run for each scenario in a feature by tagging the feature and then targeting hooks at the tag:

```gherkin
@my-tag
Feature: something
```

```js
Before({tags: '@my-tag'}, async function () {});
```

What's your use case for wanting to run the hook once per feature?

**Comment by Amrkamel1** [comment]
yes, I have implemented this approach, but was thinking of having some prerequisites to be run for each scenario it's kinda not the best thing.

so let's say i have one test suite related to login and forget the password, like shown below, i have one method running before all test for once which is loading the main page,
after that, i added one set of test cases wrapped in one context since they are related to the same feature 
and inside this context im  running before func to be run once and for all, in that way I'm avoiding the multiple time needed for running beforeEach = Before method in cucumber hence overall test execution time is dropping and still all test cases are isolated, this is just one scenario there are many other, it's always good to have flexibility on how you are managing you test execution 

```
describe('Login Test Suite', () => {

    before(() => {
        browser.url('/example/login');
        p.loginHeader.waitForDisplayed();
    });
    it('01. Should not be able to login with invalid cred', () => {
        p.loginWith('spaceframe', 'anything')
            .waitForErrorMsg();
        expect(p.errorMsg).toHaveText('Invalid credentials specified');
    });
    .
    .
    .
    it()
    
    ontext('05. Forget password Tests', () => {
        before(() => {
            p.forgetPassword.waitForDisplayed();
            p.forgetPassword.click();
        });

        it('05-1. should get an error when no email is provided', () => {
            p.forgetPasswordOfInvalid('');
            expect(p.emailError).toHaveText('The email you have entered does not exist in our system');
        });
})
```

**Comment by davidjgoss** [comment]
> and still all test cases are isolated

I would disagree with that - if you use the same browser/driver instance and rely on the same initial navigation from several tests, they aren't isolated - they can affect one another. It's worth pointing out the runtime order isn't guaranteed, especially with parallel running. In your feature files, you can use things like `Background` to reduce repetition and ease readability, but I would avoid trying to push back against the independent nature of scenarios for the sake of shaving a little time off.

Going to close this as an issue, but happy to continue discussing techniques on [the Slack](https://cucumber.io/tools/cucumber-open/support/#slack) if you'd like.

**Comment by asashour** [comment]
Sorry for hijacking the issue, but joining Slack gives an error of `certificate has expired`, and there is no reply from [contact us](https://cucumber.io/contact-us/).

The use case is to reduce the initialization time/effort needed, as clearing all database objects and creating the prerequisites may consume time, and this has a significant impact of the tests of big projects which run for multiple hours.
Another point is that the user should have the possibility to define that in the feature file, not in the code, as it would be hidden from the test case writer otherwise.

 The user could write something like:

```
Feature:
  Initialize: # before feature
   Given clear the database
   And create an initial admin
   And create other users and entities

  Background:
    Given clear possible side effects of other scenarios in this feature

  Scenario:
    When create a new company
    ...
```

This would require that the features are run in order, i.e. not a scenario from `feature1` then a scenario from `feature2` then a scenario from `feature1` again.
