### ISSUE TITLE
Load custom snippet syntax by relative path only if it begins with a dot

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#1640]
Want to implement something similar to #1413 for snippet syntax.

- - -

The above-mentioned change made referencing custom formatters a lot more logical. Before:

```shell
# an npm package
--format node_modules/some-formatter-package/index.js

# a project-local file
--format formatter.js
```

After:

```shell
# an npm package
--format some-formatter-package

# a project-local file
--format ./formatter.js
```

We want it to work the same way for [custom snippet syntaxes](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#undefined-step-snippets), but it's technically a breaking change so should probably wait for 8.0.0.

**Comment by aurelien-reeves** [comment]
@charlierudolph may I let you qualify that issue using labels?

Also if you could add some context and/or description, that would be great 😄

**Comment by davidjgoss** [comment]
@aurelien-reeves  updated!
