### ISSUE TITLE
this in beforestep hooks is not world

### ISSUE THREAD

**Issue by jmaxxz** [cucumber/cucumber-js#165]
`this` in beforestep hooks is not world. (It is `undefined`)

**Comment by benjamine** [comment]
@jbpros BeforeStep and StepResult events are useful. In my case I'm using them to log timings for each step (only when there's a failure or in a verbose mode), which sometimes helps sometimes debugging, or find slow steps.
I can see it also being useful to run certain checks after a step that has a tag, eg:

``` gherkin
Scenario: Log In
Given I visit homepage
When I enter my credentials
@screenshot-compare
Then I'm logged in
```
Then you can use that tag to take a screenshot after that step and use it for screenshot comparison checks, just an example.

**Comment by mk7upurz87** [comment]
@benjamine I am currently having the same findings where our build system creates screenshots after each step in some of our feature files.  It's sloppy to set outter closure `world = this` inside of an inner closure of indeterministic runtime order.  The only reason that works is because `before` is always running earlier than `after`.  Kinda ugly.  Strange to me that this library is so popular and we're not trying to satisfy the users in this thread.  Oh well, I'll document my own code a little heavier and move on.

**Comment by charlierudolph** [comment]
What exactly is your use case for needing access to the world instance in a beforeStep hook? All of the event handlers are not meant to be used for running tests. Event handlers are used internally with the formatters and I believe were initially exposed as an easy way to give a beforeFeatures / afterFeatures hook. This is still something I've debated removing for a long time.

**Comment by mk7upurz87** [comment]
When a failure occurs in a test we output a screenshot of the UI at each step of the scenario.

**Comment by charlierudolph** [comment]
I've done this exact thing in `After` hooks. It has the world instance. Since all the rest of the steps are skipped, this basically runs right after the failure.

**Comment by mk7upurz87** [comment]
Yes that would allow us to display the screenshots however we collect them after each step and then display them upon failure.  Our storage container is world.modules.context where context is the current state of the scenario thus far.

**Comment by mk7upurz87** [comment]
This is only one use case where I see BeforeStep having world being useful.  Ultimately the BeforeStep grants us more granularity for logging.  That's all I've got.  If at this point I'm the only one weighing in, it wouldn't matter the case I make anyways.  Thanks for the conversation!

**Comment by benjamine** [comment]
@charlierudolph 
> I'm using them to log timings for each step (only when there's a failure or in a verbose mode), which sometimes helps debugging, or find slow steps.

**Comment by charlierudolph** [comment]
@benjamine cucumber-js already keeps track of how long each step takes. That data is available in the json formatter and in the new usage formatters

**Comment by benjamine** [comment]
oh that's new? or maybe I missed it, I guess you need to wait for all tests to run to see that json? but that might be ok for my case.

**Comment by charlierudolph** [comment]
The output in the JSON formatter has never really been documented. Just created an issue for that. The usage formatters are new.
