### ISSUE TITLE
Cucumber js v.7 cli does not allow additional command line options anymore 

### ISSUE THREAD

**Issue by jaheikki** [cucumber/cucumber-js#1666]
Cucumber js version 6.x supports giving additional (non-cucumber) command line options, but it does not work anymore with Cucumber js 7.x!

Error message with Cucumber js v7.2.1:
node_modules/.bin/cucumber-js ./e2e/features --require-module @babel/register --configuration android.emu.release
error: unknown option '--configuration'

Tested with both Cucumber js v.6.x and v.7.x, node --version: v15.14.0, detox --version: 17.13.2, Mac OS Catalina 10.15.7

This is needed e.g. with Cucumber js & Detox (for React-native testing) where it is mandatory to use Detox command line options like "--configuration". "--configuration" is Detox command line option and not Cucumber js command line option.

For example this works with Cucumber 6.x but not with 7.x:
node_modules/.bin/cucumber-js ./e2e/features --require-module @babel/register --configuration android.emu.release

See:
https://github.com/mathanpec/react-native-detox-cucumber

**Comment by davidjgoss** [comment]
Thanks for raising @jaheikki 

Allowing arbitrary command line options is considered bad practise by many, and I tend to agree. Restricting to only known valid options helps guide users to avoid mistakes.

Does detox support a way to programattically set this configuration, or an environment variable - I'd be keen to help enable a way to avoid relying on cucumber-js CLI in this way.

**Comment by davidjgoss** [comment]
I knew this sounded familiar - see comments on #1474 where there is an alternate solution provided.
