### ISSUE TITLE
World is not properly typed in the latest wersion

### ISSUE THREAD

**Issue by MilanJimi** [cucumber/cucumber-js#1667]
Node v12.19.0, TypeScript v4.2.4, @cucumber/cucumber v7.2.1, Ubuntu v20.04

I can no longer use `World` in my tests, because `this` is no longer typed inside the `Given/When/Then` functions, instead defaulting to being typed as `any`. 

If I downgrade to version `cucumber v7.0.0-rc.0`, `this` is properly typed as `World`.
![image](https://user-images.githubusercontent.com/6137091/117426798-9cd7bd80-af24-11eb-9a38-671d5fbfcb97.png)

![image](https://user-images.githubusercontent.com/6137091/117426338-14591d00-af24-11eb-9e41-6aef83557184.png)

**Comment by davidjgoss** [comment]
Thanks for raising @MilanJimi, I can repo this and will fix.

In the meantime as a workaround, you can specify the type of `this` by prepending it to the function's arguments, e.g.:

```typescript
import {Then, World} from '@cucumber/cucumber';

Then('the test runs with string parameter {string}', async function(this: World, parameter: string) {
    this.driver.close()
})
```

**Comment by charlierudolph** [comment]
I'm surprised this worked `this` in step definitions was ever auto-typed as World. @davidjgoss do you know how this was supported before / what changed that broke it?

**Comment by davidjgoss** [comment]
@charlierudolph no I don’t think it ever worked since our refactor to TypeScript. The second screenshot above is from v6 with (presumably) the types from DefinitelyTyped, which did type `this` as `World` - which was just an alias for an object with arbitrary props.
