### ISSUE TITLE
Upgrade @cucumber/cucumber 7.0.0 -> 7.1.0

### ISSUE THREAD

**Issue by binarymist** [cucumber/cucumber-js#1689]
## Summary

In upgradeing from "@cucumber/cucumber": "7.0.0" to "@cucumber/cucumber": "7.2.1" as per [this issue](https://github.com/cucumber/common/issues/1585) I had problems at 7.1.0.
In looking at the [Changelog](https://github.com/cucumber/cucumber-js/blob/main/CHANGELOG.md#fixed-2), I see [pr 1608](https://github.com/cucumber/cucumber-js/pull/1608/files) introduced a `stream.on` (in a ts file (I'm using js)). Correct me if I'm wrong, but this seems to assume that the cucumber stdout has an `on` function. I haven't seen this documented anywhere, what is the purpose of this? Also the actual change doesn't seem to be in the Changelog. I also can't find it in the https://github.com/cucumber/cucumber-js repository. I can only see it when I npm install @cucumber/cucumber 7.1.0. Where is this code?

I've added [this](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/src/scripts/runCuc.js#L42-L45) to get around the problem, but I have no idea what the `on` function is supposed to do?

[This is where/how](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/src/scripts/runCuc.js#L63-L67) I've been instantiating the CLI for years.

[This is how](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/06c5148c9f080388164a74ccf990e8ae18f7316f/src/api/app/models/app.parallel.js#L502-L505) I've been handling the CLI erros for years. 

Is my empty `on` function the way to do this, I'm struggling to understand what's going on here?

**Comment by binarymist** [comment]
> I did not say that. I just said that we cannot guaranty the type of the data here as this is not specific to Cucumber. This is based on a Node API which gives any guaranty on the type of the incoming data.
> 
> That stream is passed to formatters, including custom formatters. We do not know what is going on in those custom formatters.

Ah, some more context/background. That helps. We're don't use any formatters other than what's in the Cucumber box. Does that mean it'll always be a string or is there still some uncertanty?

> That stream representing stdout, it is relatively safe to assume they'll receive strings or data easily convertible as strings.

Ok, that's helpful.

> But as it is passed to custom formatters and end users being able to easily implement their own custom formatters, you should not trust the data and implement proper checks and guards before publishing it to your system, or before processing it by your own services.

Our end users don't come anywhere near the backend (Cucumber). The only data we take in from users is a [_Job_](https://purpleteam-labs.com/doc/definitions/) file which looks a bit like [this one](https://github.com/purpleteam-labs/purpleteam/blob/main/testResources/jobs/job_0.1.0-alpha.1_local) and is passed through several forms of [validation, filtering and sanitisation](https://f1.holisticinfosecforwebdevelopers.com/chap06.html#leanpub-auto-generic). No user input is directly used with Cucumber.

**Comment by aurelien-reeves** [comment]
> Ah, some more context/background. That helps. We're don't use any formatters other than what's in the Cucumber box. Does that mean it'll always be a string or is there still some uncertanty?
> 

There cannot be any warranty. The stdout parameter for the Cucumber CLI constructor must be a IFormatterStream, which can be a fs.writeStream, a tty.writeStream, a stream.passThrough, or a cucumber http_stream. Those are Node streams. You should stick to that. Even if cucumber would use only strings, you should not trust such assumption. The only assumptions you may trust are the ones enforce by a strong type system.

> Which is sounding like we just check whether `chunk` is `string` or `buffer` if string, wer're good to log it, if `buffer` attempt conversion to string and... we're good to log it?

Looks good

**Comment by binarymist** [comment]
Thanks muchly for your help on this one @aurelien-reeves !
