### ISSUE TITLE
Timeouts in CucumberJS 7+ version not aligned with documentation

### ISSUE THREAD

**Issue by znevrly** [cucumber/cucumber-js#1691]
Hi,

looking on https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/timeouts.md but it seems does not work in CucumberJS 7+ version.

I have old code with setDefaultTimeout(timeoutInMilisec) in world and it worked for long time (version 6+). Now I got report that it does not work anymore with 7+ but not sure since because timeout is kind of edge case.

Getting this message when different global timeout via setDefaultTimeout is set up:

Error: function timed out, ensure the callback is executed within 30000 milliseconds

When('step definition', {timeout: 100000}, callback)
Setting timeout as step parameter works as expected but I have many steps and I want to set up globally.

Thanks.

**Comment by aslakhellesoy** [comment]
Thanks for reporting this! Can't promise anything, but we'll try to have that fixed for the next release.

**Comment by davidjgoss** [comment]
> I have old code with setDefaultTimeout(timeoutInMilisec) _in world_

It should be called globally, not from within any step, hook or world, see https://github.com/cucumber/cucumber-js/issues/1610

**Comment by davidjgoss** [comment]
Please reopen if you still have issues after calling `setDefaultTimeout` globally.

**Comment by znevrly** [comment]
OK, I can confirm it's working but still docs is misleading. Therefore I have this issue title. IMHO docs needs to be updated.

**Comment by davidjgoss** [comment]
@znevrly what edit would you propose to https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/timeouts.md? Could you raise a pull request?

**Comment by znevrly** [comment]
Very glad but my English is too bad for docs and I don't want to be misleading :(

**Comment by davidjgoss** [comment]
No problem - I have made this change, hopefully that covers it https://github.com/cucumber/cucumber-js/commit/097ef2670252b2480ceb8eb4f6a3e980aee40eb5

**Comment by znevrly** [comment]
IMHO this need to be changed as well
"By default, asynchronous hooks and steps timeout after 5000 milliseconds. This can be modified globally  with:"

1. now it's 30000 which is hardcoded
2. can be -> has to be
