### ISSUE TITLE
Cucumber-js unable to handle Given and When steps with same step text

### ISSUE THREAD

**Issue by evilC** [cucumber/cucumber-js#1696]
node 14.16.0
@wdio/cli: 7.3.0
@wdio/cucumber-framework: 7.3.0

With the following code:
```
Scenario: Foo
   Given Foo

Scenario Bar
   When Foo
```

```
Given ("Foo", () => {
   someFunc();
});

When ("Foo", () => {
   someFunc();
});

function someFunc(){

}
```
When I run my tests with wdio, it fails to hit the first step with no obvious error

In our project, we wish to re-use a step (ie same step can be used as a Given or a When step).
What I currently do is this:

```
Given, // SonarQube says "Unexpected use of comma operator" for this line
When("Foo", () => {
   // some code here
}); // SonarQube says "Expected an assignment or function call and instead saw an expression" for this line
```

However, when SonarQube runs, it flags the lines as mentioned in the comments as code smells, so I was hoping to use the syntax at the start of my post as a work-around. IMHO it really should work - there is no ambiguity there as to which step should be called at which point, and even if it does crash, it should give some kind of meaningful error

**Comment by davidjgoss** [comment]
On a technical level you can just do:

```js
Given("Foo", () => {
   someFunc();
});
```

At runtime cucumber doesn't care which keyword you used to define it, it will work with Given, When, Then, And, But. If you're still seeing issues please post some more detail e.g. an example repo we can look at.

On a philosophical level, it's generally encouraged to remove the ambiguity by having explicit wording for context vs action steps, even if they are mostly doing the same stuff underneath.

**Comment by evilC** [comment]
Ah, OK, that kind of confirms my suspicions oh how things work internally, but frankly, that's a bit shocking
It could result in all kinds of strangeness going on
IMHO this should be properly fixed

Also WRT "even if they are mostly doing the same stuff underneath" - surely if they are doing **exactly** the same underneath then there is no ambiguity ?

**Comment by davidjgoss** [comment]
> (ie someone wrote a step definition in a completely different file and did not realize that text had been used elsewhere)

That will error. You can't define it twice, but you can use it in multiple ways.

There are some long-running discussions around this issue, which is a broader cucumber thing and not specific to JS, so don't really want to get too into it here.

- https://github.com/cucumber/common/issues/768
- https://github.com/cucumber/common/issues/1392
