### ISSUE TITLE
Unable to use cucumber pretty formatter 

### ISSUE THREAD

**Issue by Phonesis** [cucumber/cucumber-js#1701]
I get the following error since upgrading to Cucumber 7.3.0 when I try to pass in the following formatter option 

```
-f @cucumber/pretty-formatter
```

Error:

```
TypeError: Cannot read property 'astNodeIds' of undefined
    at PrettyFormatter.onTestStepStarte
```

Any solutions? I am using latest version of the pretty formatter (1.0.0-alpha.0)

**Comment by davidjgoss** [comment]
Hi @Phonesis - I've raised https://github.com/jbpros/cucumber-pretty-formatter/pull/5 to fix the issue there, hopefully that will be release shortly.

**Comment by Phonesis** [comment]
That's great thanks @davidjgoss

**Comment by davidjgoss** [comment]
No problem - going to close this issue since we have the PR.

**Comment by davidjgoss** [comment]
`@cucumber/pretty-formatter` version `1.0.0-alpha.1` is now released with the fix.
