### ISSUE TITLE
IParameterTypeDefinition regexp

### ISSUE THREAD

**Issue by yasserf** [cucumber/cucumber-js#1702]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@cucumber/cucumber@7.3.0` for the project I'm working on.

The IParameterTypeDefinition<T> in code supported both RegExp and arrays of them.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@cucumber/cucumber/lib/support_code_library_builder/types.d.ts b/node_modules/@cucumber/cucumber/lib/support_code_library_builder/types.d.ts
index 27e0f51..13b4fbe 100644
--- a/node_modules/@cucumber/cucumber/lib/support_code_library_builder/types.d.ts
+++ b/node_modules/@cucumber/cucumber/lib/support_code_library_builder/types.d.ts
@@ -39,7 +39,7 @@ export interface IDefineTestRunHookOptions {
 }
 export interface IParameterTypeDefinition<T> {
     name: string;
-    regexp: RegExp;
+    regexp: RegExp | RegExp[];
     transformer: (...match: string[]) => T;
     useForSnippets?: boolean;
     preferForRegexpMatch?: boolean;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by aurelien-reeves** [comment]
Hi :)

Thanks for the report.

Could you please give more details regarding the original issue you were facing?

Did you consider creating a pull request with your changes?

**Comment by aslakhellesoy** [comment]
The `IParameterTypeDefinition` interface in Cucumber.js is a wrapper around this constructor signature in the cucumber-expressions library:

https://github.com/cucumber/common/blob/5391796cb49ebc93b83325fcce96af2f59e9a201/cucumber-expressions/javascript/src/ParameterType.ts#L44

I think an even better fix would be to adopt the same type:

```typescript
regexp: readonly RegExp[] | readonly string[] | RegExp | string
```

Note that the cucumber-expressions library uses the plural `regexps` while Cucumber.js uses the singular `regexp`. It's unfortunate that they are different, but for backwards compatibility reasons I think we should keep `regexp`.

**Comment by davidjgoss** [comment]
@yasserf do you mean you wanted to use an array of regexps but it yielded a TypeScript compilation error (even though it would work at runtime)?

**Comment by yasserf** [comment]
Yup, I just patched the type but the functionality itself worked as expected

This was a few months ago, so I can’t say for certain it’s still the case

**Comment by davidjgoss** [comment]
Thanks for confirming @yasserf.

I've pushed a test for the TypeScript typing [to this branch](https://github.com/cucumber/cucumber-js/commit/54ef15959448e6bce09b347fb7ecc77ffacd54d8), which fails as of now and should pass (along with all existing change) once the change @aslakhellesoy suggests is made.

If you or anyone interested would like to do a PR for this, that would be great.
