### ISSUE TITLE
Allow to uninclude features

### ISSUE THREAD

**Issue by nicojs** [cucumber/cucumber-js#1712]
**Is your feature request related to a problem? Please describe.**
Let's say you have this `cucumber.js` config:

```js
// cucumber.js
module.exports = { default: 'my-features/*.feature' }
```

And you now want to focus 1 feature in a feature file:

```shell
$ npx cucumber-js my-features/math.feature:7
```

In addition to the scenario on line 7 in math.feature, all other feature files will be executed. I've located the code that is responsible here:
https://github.com/cucumber/cucumber-js/blob/4ef971016858bcc3ad5aa3af57439dff5a158277/src/cli/configuration_builder.ts#L125-L141

**Describe the solution you'd like**
I would personally think that _command line positional arguments_ should **not** be merged together with the profile positional arguments, instead it should override them. Note: I do think properties should still be merged, just not positional arguments.

**Describe alternatives you've considered**
A way to "uninclude" files would be a valid alternative:

```shell
$ npx cucumber-js !**/*.feature my-feature/math.feature:7
```

**Additional context**
I've run into this while developing the cucumber plugin for StrykerJS. We want to be able to focus tests, regardless of positional arguments in the profile.

We can also think of another solution when defining the [programmable API](https://github.com/cucumber/cucumber-js/issues/1711)

**Comment by aurelien-reeves** [comment]
That makes sense to me

What do you think @cucumber/cucumber-js?

Another possibility could be also to have a `--no-profile` option to avoid loading any profile, including the default one.

**Comment by nicojs** [comment]
Thanks @aurelien-reeves .

A `--no-profile` would be useful as well for other use cases, but I also want to support profiles. For example:

```js
module.exports = {
  default: '--require-module tsnode/register --require my-features/**/*.ts my-features/*.feature'
}
```

In this case I still want the options, just not the positional arguments 🤷‍♂️

**Comment by davidjgoss** [comment]
Thanks for raising @nicojs.

I'd be supportive of changing the logic with the paths so they are considered together and negation is supported. Basically what [globby](https://www.npmjs.com/package/globby) does. I don't think this is a breaking change for any use case I can think of, but at any rate we're doing a major release soon. @charlierudolph WDYT?

Good point about the API as well, I'll follow up on that issue.

**Comment by charlierudolph** [comment]
Hmm, I'm uncertain about if profile positional arguments should be added to or overridden by cli positional arguments. Maybe could have a flag `--default-features <paths>` which is the features used only if no positional arguments exist. That would support the override case and allow us to keep the same positional arguments we have now. 

If we want to support a method of excluding feature, I think that should also be done via a flag as I would want it to apply to all feature paths passed in and that makes more sense to me as a flag than a positional argument

**Comment by davidjgoss** [comment]
Closing this now as it's been quiet, and I think (per above) the requirement can be solved using the new API.

**Comment by nicojs** [comment]
Yeah, I'm using the new API since Stryker V6.1 and it works great!
