### ISSUE TITLE
Dynamic Examples

### ISSUE THREAD

**Issue by fguidobaldi** [cucumber/cucumber-js#1728]
Is there any way to dynamically generate examples?

I would like to be able to execute the same scenario with different inputs (that share the same expected result) , not just hardcoding these inputs, but generating them programmatically. The current approach it isn't scalable, and it's very expensive to maintain.

I understand that maybe this isn't the typical UC for Cucumber, that's why I'm trying to find out some sort of workaround to this issue. The objective is to reuse when/then steps, without having to write different scenarios, but to execute them the number of times necessary according to the input.

Scenario Outline: User logging
  Given there is <user_id> user
  When the user tries to login
  Then I should receive 200 as status code
  * I verify some response value
  * I verify another response value

  Examples:
    | user_id |
    |    1         | 
    |    2        |
    |    3        |
    |    4        |
    |    5        |
    |    6        | 

---------------------------------

Scenario: User logging
  Given there are 6 users --> THIS STEP GENERATES 6 USER_ID
  When the user tries to login
  Then I should receive 200 as status code
  * I verify some response value
  * I verify another response value

WHEN and THEN should be executed 6 times (once for each user_id)
---------------------------------

**Comment by davidjgoss** [comment]
Hi @fguidobaldi, what you're describing there isn't possible with cucumber because scenarios are calculated into test cases upfront and can't be built as you go at runtime.

In your example with 6 users, what behaviour are you trying to describe and test there? Is there something different about each of the users?

**Comment by fguidobaldi** [comment]
Thanks for your answer @davidjgoss! In this oversimplified case, the 6 users should be 6 different, random users, but they all should behave the same way when they try to login.

In a real scenario, each scenario I'm trying to run involves different variables (like users, countries, destinations, etc.), but I expect the same output, no matter what the exact combination of these variables is. That's why I'm trying to generate dynamically these combinations, in order to get a different set of inputs every time I run this test, and not just harcoding the values.

As I said before, I really understand that it's not the typical UC for Cucumber, and if you know of any other tool that may fit this UC, I'll be very grateful.  Also, please feel free to close this issue if this is something that's not achievable using Cucumber.

**Comment by dambler** [comment]
@fguidobaldi if you need to programatically run a test with specific user parameters, I'd use something like rspec instead.

**Comment by jenisys** [comment]
Your usecase sounds like you want a pairwise combination of parameters with different value sets (using the pairwise algorithm). If the number of combinations becomes too large, you would use something like property-based testing to select a subset of the combinations that is used in a test run.

You basically have basically two possibilities, one that would work right now with cucumber and one if that functionality is provided in a cucumber implementation:

* SOLUTION 1: Feature files are text. Therefore, use a template and a template engine to generate the feature file with the examples before the test run.
* SOLUTION 2: Use tags to specify a generator mechanism on the Examples table. The tag injects the Example table generator algorithm and executes it before the test run (or similar: reads it from an external source, like Specflow with a CSV file or Excel spreadsheet)

Note that this no longer BDD but a mechanism that uses cucumber to achieve the desired goal.

SEE ALSO:
* https://github.com/behave/behave/issues/464

**Comment by davidjgoss** [comment]
Per earlier answers, I think the best way to achieve this today would be to use a templating tool (Handlebars, etc) outside of Cucumber to generate the feature files with your dynamic data, then run Cucumber to execute them.

You might also be interested in this [proposal to add a preprocessor standard](https://github.com/cucumber/common/issues/773), which (if added) might give you the mechanism to source your examples dynamically.
