### ISSUE TITLE
Parallel Testing with Cross Browser Functionality

### ISSUE THREAD

**Issue by teststack-git** [cucumber/cucumber-js#1729]
**Is your feature request related to a problem? Please describe.**
I am attempting to set up my teams CucumberJS implementation after we identified some short-comings within Jest-Cucumber (notably the lack of Cucumber json reporting).  The benefit of using Jest-Cucumber, however is that I can define browsers to use within the config file and the step definition files would know to run tests against those browsers.  This also meant that I could achieve parallelization using all tests with all browsers and have it reflected in a report.  

I'm having trouble finding a similar solution within CucumberJS as it seems to require a single browser instance at a time.  I can use the process.env.BROWSER to sort of dynamically pass in a browser via a nodejs CLI, however that means I would need a separate call for each browser, which then turns into 3 Cucumber reports. I've found the section within the docs that showcase parallel testing, however nothing in regards to browser management.  Is this something that is possible with CucumberJS?  If so, is there an example that I can look at with that sort of implementation or at the very least the usage of a config.js file that can achieve those goals?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by charlierudolph** [comment]
The parallel feature is currently meant as a means to speed up a single run through (ie each scenario runs once instead of running multiple times with different browsers). Cucumber doesn't have any opinions about browser management and its up to users to determine how they want to handle that.

Based on your use case, I think running cucumber 3 times makes the most sense to me and then you need to write your own process to merge the result files.

**Comment by davidjgoss** [comment]
Per previous comment, I agree one CI job per browser is the way to get this done. You could use environment variables or [Profiles](https://github.com/cucumber/cucumber-js/blob/main/docs/profiles.md) to keep it clean. Also you could parallelise the jobs at the CI level.
