### ISSUE TITLE
Unable to get StepName from ITestStepHookParameter in BeforeStep hook

### ISSUE THREAD

**Issue by mbrzozowski-merapar** [cucumber/cucumber-js#1740]
**Describe the bug**
I am trying to pull current step name out of ITestStepHookParameter in the BeforeStep hook:

```
BeforeStep(async function(testStep) {
     // Should be step name, is scenario name instead
     const stepName = testStep.pickle.name;

    // stepObj is undefined
    const stepObj = testStep.pickle.steps.filter(step => {
        return step.id === testStep.testStepId
    });
});
```

**Cucumber-js version: 7.3.1**

**Expected behavior**
I would expect the `testStep.testStepId` to be present in the array of steps in the `testStep.pickle.steps` object. However, that's not the case and the `testStepId` does not much any of the steps in the array.

Also, the `testStep.pickle.name` contains the name of the whole scenario, not the concrete step. 
As a result, it is not able to pull out the step name inside the BeforeStep hook.

**Comment by aurelien-reeves** [comment]
Indeed the pickle argument given to the callback of the `BeforeStep` seems to be related to the test case - maybe even the scenario actually - rather than the step.
In our documentation, it is simply explained that we give a pickle, we do not say which one it is 😅 

I think we could consider this as a bug. @davidjgoss @charlierudolph what do you think?

**Comment by mbrzozowski-merapar** [comment]
Is there any workaround to get step name in BeforeStep hook?

**Comment by aurelien-reeves** [comment]
I was not able to find a workaround yet for that.
@davidjgoss @charlierudolph any idea?

**Comment by aurelien-reeves** [comment]
> 
> 
> @aurelien-reeves Is there any workaround to get step name in BeforeStep hook?

May I ask: why do you need the step name in the BeforeStep hook? What are you trying to achieve?

We had the same kind of discussion with `cucumber-ruby` [recently](https://github.com/cucumber/cucumber-ruby/issues/1432#issuecomment-885147967). It appears that often, what is attempted to be done would be more related to `formatters`. Did you tried looking at [custom formatters](https://github.com/cucumber/cucumber-js/blob/main/docs/custom_formatters.md)?

**Comment by mbrzozowski-merapar** [comment]
So I am using custom logger (winston-js) within step definitions to produce JSON-structured logs that also contain metadata. So one of the metadata attached to every log message is scenario name. I wanted to extend it further - attach step name to every log message to give it more context.

So far I was configuring the logger instance in the Before hooks and assign it to the World object to make it accessible from step definitions. I'd also like to keep using my custom logger (winston-js) because it comes with a lot of stuff out of the box.

If there is any other better way to do this please by any mean suggest it - I am more than happy to do better :D

**Comment by aurelien-reeves** [comment]
I would suggest to use a custom formatter for this purpose. It seems totally appropriate for your use-case.
But as I was looking for something relatively easy to give you a basic example, I could not find any 😕

Do you feel comfortable to try writing your own? A good starting point could be to look at https://github.com/cucumber/cucumber-js/blob/main/src/formatter/progress_formatter.ts.

**Comment by davidjgoss** [comment]
Agree a formatter is probably the right thing for the general use case.

I do think it makes sense for the before/after step hooks to have the `pickleStep` available though, given the scenario-level hooks have `pickle`. I'd probably add it but leave `pickle` in place to avoid an unnecessary breaking change.

This seems a good first/early issue candidate. Some pointers:

- Where this hook parameter is constructed https://github.com/cucumber/cucumber-js/blob/main/src/runtime/test_case_runner.ts#L263

**Comment by mbrzozowski-merapar** [comment]
@aurelien-reeves @davidjgoss so in my case, you'd suggest that I:
- create a custom formatter
- instantiate winston longer inside formatter
- in appropriate event handlers, e.g.`TestStepStarted` configure the winston logger instance to include additional metadata?

For that to work, I would need to somehow provide the logger instance created inside my Custom Formatter to the step definition code. Is it possible to mutate the World object from inside the formatter? If yes, then how would I do it?

thank you in advance!

**Comment by davidjgoss** [comment]
@mbrzozowski-merapar I think it depends what type and granularity of stuff you want to log. If it's at a fairly generic level (e.g. a step starts, a step finishes with a result, a scenario starts etc) then a formatter is great. If you want to log stuff to do with specific details of events going on within your step, that might be more difficult. Would be interesting to see some examples if you're able.

At any rate, I've raised #1775 to make `pickleStep` available to the hooks, which at least solves the original ask.
