### ISSUE TITLE
Duplicated stepdefs do not throwing any error?!

### ISSUE THREAD

**Issue by chocstarfish** [cucumber/cucumber-js#176]
I made two step definitions with completely the same regex in 2 different javascript files under the step_definitions folder as following:
a.js
```
...
 this.When(/^I visit "([^"]*)"$/, function (url, next) {
        console.log('The first one!');
    });
...
```
b.js
```
...
 this.When(/^I visit "([^"]*)"$/, function (url, next) {
        console.log('The second one with totally different implementation~');
    });
...
```

When I ran the test, I figured out that cucumber-js load the 2 files in alphabetical order, so the working definition was actually in 'b.js'. 

I thought it would be unsafe not throwing any error(such as 'Duplicated step definitions') because when we deal with large amount of stepdefs, we cannot guarantee we will not accidentally override previous stepdefs and that would certainly cause lots of troubles.

Did I do it wrong or it is actually an issue with the cucumber-js?

**Comment by dmeehan1968** [comment]
This now seems to have missed its planned release milestone.  I'm still getting problems with this in 0.5.1.

**Comment by aslakhellesoy** [comment]
@dmeehan1968 would you be interested in sending a pull request to fix this?

**Comment by dmeehan1968** [comment]
Yes, happy to create a PR, but a bit short on time.

I had a bit of a look through the code to find the point where step defs are matched but couldn't find the relevant point. 

If you can point me to the relevant routine/module that would be very helpful.

**Comment by jbpros** [comment]
@dmeehan1968 thanks! Have a look here: https://github.com/cucumber/cucumber-js/blob/9500c7cc46765602dd9fb934b8304a9cde9e4478/lib/cucumber/support_code/library.js#L52
