### ISSUE TITLE
Exit status is 1 when running with --dry-run

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1768]
**Describe the bug**

Running `cucumber-js --dry-run` exits with `1`.

**Expected behavior**

I expected a `0` since nothing is run.

**Context**

I'm building an LSP language server which will spawn cucumber in dry-run mode (to capture step definitions and steps so we can build up an autocomplete index). Because it exits with `1` I'm unable to tell whether the command failed because of a *real* error or not.

**Comment by davidjgoss** [comment]
@aslakhellesoy do you have undefined/pending/ambiguous steps when you're seeing this?

**Comment by aslakhellesoy** [comment]
I don’t remember TBH - maybe some undefined ones. In any case, I think the exit status should always be 0 regardless of undefined/ambiguous steps.

**Comment by davidjgoss** [comment]
Agreed. This would be a change here https://github.com/cucumber/cucumber-js/blob/main/features/dryrun_mode.feature.
