### ISSUE TITLE
Cannot find cli config file if it has extension .cjs

### ISSUE THREAD

**Issue by JeremiePat** [cucumber/cucumber-js#1771]
**Describe the bug**
When configuring the CLI parameters with a config file, this file [must be called `cucumber.js`](https://github.com/cucumber/cucumber-js/blob/main/src/cli/profile_loader.ts#L14)

This is an issue when your Node.js project as [the type `module`](https://nodejs.org/api/packages.html#packages_package_json_and_file_extensions) because it expect JS file to be ESM module rather than CommonJS modules. In such case, `cucumber.js` must be an ESM module, but if so it is not understood and ends up with an error or it must be called `cucumber.cjs` and in such case the cucumber-js cli ignore the file.

**To Reproduce**
1. Set up a new project
2. do `npm init`
3. add the key `type` with the value `module` in the package.json file
4. set up cucumber-js
5. Add a cucumber.js file
6. run `npx cucumber-js`
7. See it fail
8. rename cucumber.js to cucumber.cjs
9. run `npx cucumber-js`
10. See the configuration not being loaded

**Expected behavior**
`cucumber.js` could be alternatively named `cucumber.cjs` or it could be written as a valid ESM module.

**Comment by davidjgoss** [comment]
Thanks for raising @JeremiePat , I will do something to address this under #1649.
