### ISSUE TITLE
Sharing Scenarios or Features Among Multiple Feature Definitions

### ISSUE THREAD

**Issue by princefishthrower** [cucumber/cucumber-js#1802]
**Is your feature request related to a problem? Please describe.**
I would like to learn how to share one or multiple scenario definitions (or even an entire feature definition) among multiple feature definitions. For example, we have a login feature definition that is defined by a series of scenarios. But the login screen itself can be approached and encountered in different ways. Because of this, we would like to keep our single set of login scenarios, and reuse all those scenarios whenever we may encounter the login (or need to log in) in our other feature definitions. Is this possible in `cucumber-js`?

**Describe the solution you'd like**
Syntax to be able to include one or more scenarios (or the entire feature definition) within the scenario list of another feature, i.e.

```
Feature: Some Feature

    Scenario: Some feature-specific scenario
    Given Something
    Then Something

    "include reusable scenario here"
    
    "maybe another reusable scenario here"

    Scenario: Another feature-specific scenario
    Given Something
    Then Something
```

OR

```
Feature: Some Feature

    Scenario: Some feature specific scenario
    Given Something
    Then Something

    "include entire feature definition here"

    Scenario: Another feature specific scenario
```

Maybe you would have to import the scenario or feature to get it to work, it doesn't really matter to me.

**Describe alternatives you've considered**
There is the [`reuse-cucumber-scenarios`](https://github.com/Virgomax/reuse-cucumber-scenarios) package, but this hasn't been updated in the last 3 years, and doesn't appear to be compatible with the newest version of `cucumber-js`

**Additional context**
I'm not really interested in claims of anti-pattern here - to me writing the same log in scenarios across multiple features is more anti-pattern than sharing scenarios or features - not being able to share scenarios or features would mean in our case that if we change how the login specification we have to hunt down the multiple places it is involved in our scenarios. Doesn't make much sense to me.

**Comment by aurelien-reeves** [comment]
> 
> 
> **Additional context** I'm not really interested in claims of anti-pattern here - to me writing the same log in scenarios across multiple features is more anti-pattern than sharing scenarios or features - not being able to share scenarios or features would mean in our case that if we change how the login specification we have to hunt down the multiple places it is involved in our scenarios. Doesn't make much sense to me.

The short answer without talking about anti-pattern is to do what you are requesting as part of your support code, your step definitions. Not as part of your features.

For example, let's say you have two ways to sign-in to your application: one with regular e-mail address and password, and another one with some SSO.

You can have detailed features and/or scenarios to describe and validate those two sign-in methods.

Then when you would have need to sign-in as part of other scenarios, you can have single steps "Given I am sign-in", then you can re-use all the code you want as part of that single step in your step definitions.

```gherkin
Feature:
  Scenario: sign-in using email address and password
    Given I am not sign-in
    When I browse to login-page
    And I enter email and password and validate
    Then I should be signed-in
    And I should be redirected to profile page

  Scenario: sign-in using SSO
    Given I am not sign-in
    When I browse to login-page
    And I click SSO button
    Then I should be signed-in
    And I should be redirected to profile page

  Scenario: sign-out from email and password
    Given I signed-in using email and password
    When I sign-out
    Then I am redirected to the home page

  Scenario: sign-out from SSO
    Given I signed-in using SSO
    When I sign-out
    Then I am redirected to somewhere else
```

With such approach, your scenarios are easy to read, the intention of your scenarios are clear and we could imagine the possibility to easily refactor your scenarios using datatables.

And yet you can, as part of your support code and step definitions, have proper re-usable and refactorable code.

**Comment by princefishthrower** [comment]
Fair enough. I suppose I was too tightly coupling my support (test) code with the feature and scenario definitions. I need to remember that these scenarios and feature definitions should be truly semantic and descriptive, while the actual test code behind them can be reusable 👍
