### ISSUE TITLE
Unable to generate allure report in case of playwright + cucumber combination

### ISSUE THREAD

**Issue by alikhanm86** [cucumber/cucumber-js#1822]
**Bug Description**
I'm unable to generate allure report in case of playwright + cucumber combination

I'm trying to generate allure reports for my automation framework which is on playwright + cucumber combination. But for me, "allure-results" folder is generated but its blank. Not sure if I'm doing something wrong. Could you anyone pls suggest?

GitHub Template that I used: https://github.com/Tallyb/cucumber-playwright
Cucumber Allure Integration link: https://github.com/allure-framework/allure-js/blob/master/packages/allure-cucumberjs/README.md

FYI, I don’t have any issues in case of playwright test runner. Above problem is only in case of cucumber playwright.

**Expected behavior**
Allure report has to be generated successfully

**Desktop (please complete the following information):**
 - OS: MAC Big Sur 11.3.1
 - Chrome, Firefox, Webkit

**Additional context**
I don’t have any issues in case of playwright test runner. Above problem is only in case of cucumber playwright.

**Comment by aurelien-reeves** [comment]
I do not know Allure, either playwright, and I do not have those tools at the moment that would help doing some tests.
Would you have the possibility to share a public repo with a minimal reproducible example and basic commands to reach the states you encounter?

Also, you may ask on https://github.com/Tallyb/cucumber-playwright or even https://github.com/allure-framework/allure-js. They may be helpful too.

**Comment by alikhanm86** [comment]
Thanks for the quick reply.

Below mentioned is a public repo, which can be cloned and executed directly without any changes. It consists 2 simple scenarios.

https://github.com/Tallyb/cucumber-playwright

**Comment by aurelien-reeves** [comment]
This is not related to cucumber, I close the issue. But we can still discuss here if you need to @alikhanm86
