### ISSUE TITLE
Combine Multiple Profile and run the different combined profile in parallel

### ISSUE THREAD

**Issue by UsmanGhani-Emumba** [cucumber/cucumber-js#1825]
I have 4 profiles in my cucumber.js

1. authFlow
2. unAuthFlow
3. broadcastPage
4. episodePage

I want to combine the 1st and 3rd profile and the 2nd and 4th. Then I want to run them in parallel, can we do it now in cucumber?

**Comment by davidjgoss** [comment]
Not in a single process. I think you'd need to instrument two separate runs:

```
cucumber-js -p authFlow -p broadCastPage
```

```
cucumber-js -p unAuthFlow -p episodePage
```

**Comment by UsmanGhani-Emumba** [comment]
would cucumber.js --parallel 2 -p authContent -p unAuthContent work

authContent includs authFlow and broadcastPage
unAuthContent includes unAuthFlow and episodePage

**Comment by UsmanGhani-Emumba** [comment]
> Not in a single process. I think you'd need to instrument two separate runs:
> 
> ```
> cucumber-js -p authFlow -p broadCastPage
> ```
> 
> ```
> cucumber-js -p unAuthFlow -p episodePage
> ```
Can we use --parallel for two different feature files?

**Comment by davidjgoss** [comment]
The parallel runtime collects all the scenarios to run and divides them across the available workers - which feature they come from is not really a factor.

Could you elaborate a little on what each of your profiles is doing? I’m sure there’ll be a way to achieve what you want.

**Comment by UsmanGhani-Emumba** [comment]
> The parallel runtime collects all the scenarios to run and divides them across the available workers - which feature they come from is not really a factor.
> 
> Could you elaborate a little on what each of your profiles is doing? I’m sure there’ll be a way to achieve what you want.

I want to run two feature files in parallel so will --parallel be helpful in this case?

**Comment by davidjgoss** [comment]
> I want to run two feature files in parallel so will --parallel be helpful in this case?

I assume you have multiple scenarios in each feature? Doing `--parallel 2` means you'd have two workers but there are no guarantees regarding which scenarios would run on which workers - the feature files are just a logical grouping.

**Comment by UsmanGhani-Emumba** [comment]
> > I want to run two feature files in parallel so will --parallel be helpful in this case?
> 
> I assume you have multiple scenarios in each feature? Doing `--parallel 2` means you'd have two workers but there are no guarantees regarding which scenarios would run on which workers - the feature files are just a logical grouping.

The number of workers we have set should be equal to the number of feature files or the number of scenarios. Example,
I have two feature files authFlow.feature and unAuthFlowFeature.feature

We have one scenario in authFlow.feature and four scenarios in unAuthFlow.feature, we want to run the feature files in parallel, 
I am using this command:
node node/modules/@cucumber/cucumber/bin/cucumber-js --parallel -p authFlow -p unAuthFlow

**Comment by davidjgoss** [comment]
> The number of workers we have set should be equal to the number of feature files or the number of scenarios.

That isn't how Parallel works - you need to specify a count of workers to be spun up, and then the scenarios are allocated across them as they run. So in the case you mentioned, depending on how long each scenario takes to run, doing `--parallel 2` would probably mean your auth scenario one or two unauth scenarios running on one worker, and the rest on another worker.

https://github.com/cucumber/cucumber-js/blob/main/docs/parallel.md

What makes you want to segregate on the basis of feature?

**Comment by UsmanGhani-Emumba** [comment]
> > The number of workers we have set should be equal to the number of feature files or the number of scenarios.
> 
> That isn't how Parallel works - you need to specify a count of workers to be spun up, and then the scenarios are allocated across them as they run. So in the case you mentioned, depending on how long each scenario takes to run, doing `--parallel 2` would probably mean your auth scenario one or two unauth scenarios running on one worker, and the rest on another worker.
> 
> https://github.com/cucumber/cucumber-js/blob/main/docs/parallel.md
> 
> What makes you want to segregate on the basis of feature?

In authFlow I am registering myself and in unAuthFlow I am performing different scenarios without registering

I want those two feature files must run in parallel -> but the scenarios of a feature file can run sequentially => so that is why I am using 2 workers to open two instances and then the scenarios of both feature files can run sequentially.

**Comment by UsmanGhani-Emumba** [comment]
> > The number of workers we have set should be equal to the number of feature files or the number of scenarios.
> 
> That isn't how Parallel works - you need to specify a count of workers to be spun up, and then the scenarios are allocated across them as they run. So in the case you mentioned, depending on how long each scenario takes to run, doing `--parallel 2` would probably mean your auth scenario one or two unauth scenarios running on one worker, and the rest on another worker.
> 
> https://github.com/cucumber/cucumber-js/blob/main/docs/parallel.md
> 
> What makes you want to segregate on the basis of feature?

I got your point thank you

**Comment by UsmanGhani-Emumba** [comment]
@davidjgoss I have used the page.content() function in my code, when I run two feature files in parallel it throws an error that content of undefined cannot be read but if i run the file individually, this error is not thrown?

**Comment by davidjgoss** [comment]
`page.content()` isn't something from cucumber, is it maybe something you are initialising from your own code. I'm happy to take a look but would need you to post a link to an example repo.

**Comment by UsmanGhani-Emumba** [comment]
> `page.content()` isn't something from cucumber, is it maybe something you are initialising from your own code. I'm happy to take a look but would need you to post a link to an example repo.

@davidjgoss 
Yes problem is resolved, there was something from my side. I just want to confirm one thing if we have 3 feature files the scenario will run in the order we have defined them in cli? right?

**Comment by davidjgoss** [comment]
@UsmanGhani-Emumba

> I just want to confirm one thing if we have 3 feature files the scenario will run in the order we have defined them in cli? right?

- In serial mode - the order is predictable, yes (unless you specifically use `--order` to make it random)
- In parallel mode - when a worker becomes free it picks up the next scenario to execute, so order is definitely not predictable

Ideally scenarios should be totally independent - if that's not the case I'd definitely advise spending time on solving that problem.
