### ISSUE TITLE
How we can customize CLI `--exit` or wait for our customize formatter finish before exit

### ISSUE THREAD

**Issue by vctqs1** [cucumber/cucumber-js#1841]
Hi all, I'm working on customize formatter. In that formatter, It will parse/map data and upsert to DB. 

So my problem is when event Broadcaster emit`finishTestCase` I'll check and upsert the result to my DB. But sometime, cucumber `exit` before `request update result`

![image](https://user-images.githubusercontent.com/30227910/140290902-25eb6315-5025-45e9-b0c9-5eaa1be6eb26.png)

It work well when I comment `--exit` arg
![image](https://user-images.githubusercontent.com/30227910/140291006-e5edc9dd-688f-4a19-b508-63595d8809cc.png)

**Comment by aurelien-reeves** [comment]
Well, that's the purpose of the `--exit` flag actually: https://github.com/cucumber/cucumber-js/blob/main/docs/cli.md#exiting
The solution is what you did: to remove it.

Why do you need `--exit` for?

**Comment by davidjgoss** [comment]
If your formatter has async work which the test run should wait for before closing, you should be able to override the `finished` method on your formatter class, something like:

```typescript
async finished() {
  await this.myCustomThingThatTakesTime()
  await super.finished()
}
```

Give that a try? It's not well documented tbh so I'll look at adding that.

**Comment by vctqs1** [comment]
> Why do you need `--exit` for?

Because I have an async job, that will receive message broadcast events. So I want this job finish before `exit` exec

**Comment by vctqs1** [comment]
> If your formatter has async work which the test run should wait for before closing, you should be able to override the `finished` method on your formatter class, something like:

Wow, thank you, I'll try and back after having result

**Comment by aurelien-reeves** [comment]
> 
> 
> > Why do you need `--exit` for?
> 
> Because I have an async job, that will receive message broadcast events. So I want this job finish before `exit` exec

That's the point

If you want your async job to finish before exiting, you have to remove the `--exit` flag.
The purpose of the `--exit` flag is to NOT wait for async job to be finished before exiting.

**Comment by vctqs1** [comment]
Yes, you are right, but for my cases, I have to wait for it before uploading the result in DB. So I must to customize it

But @davidjgoss 's solution work for me now. and I only `one-action I need, not all async join

@aurelien-reeves That's an anti-solution or any problem we should avoid? If I remove `--exit` flag how I can `exit` job?

**Comment by aurelien-reeves** [comment]
`--exit` job does not make the job to exit. `--exit` flag force the job to exit before it may have properly finished everything.

As explained in the documentation, `--exit` should be avoided. It is there only in cases where you may have stuck processes which prevent cucumber to exit.

If you have such stuck processes that prevent cucumber to properly exit, you may investigate to find what is responsible for such behavior and fix that rather than using `--exit` to ignore it.

Do you have any kind of issue if you remove the `--exit` flag?

**Comment by vctqs1** [comment]
```
Do you have any kind of issue if you remove the --exit flag?
```
Hum, so for example case, if I remove the `exit` flag by the way I don't want  `force the job to exit before it may have properly finished everything.`

I only want to `exit job` after everything is finished. So I still can `remove exit flag` and handle it manually?

My concern here is, if the job can not exit, our CI will follow up with it forever?

**Comment by aurelien-reeves** [comment]
> I only want to `exit job` after everything is finished. So I still can `remove exit flag` and handle it manually?
> 

What do you want to handle manually? There is nothing to worry about. Cucumber will exit properly by itself once everything is properly finished without the `--exit` flag. 

> My concern here is, if the job can not exit, our CI will follow up with it forever?

What are you so concerned about the job not being able to exit? Is there some risk? Do you have some specific tings that may prevent the job to finished properly? What is your test stack?

However, if you worry about your CI running forever, all major CI stack should have the possibility to configure timeouts. Check your existing jobs duration, and set a timeout that will let your job to finish properly, but that prevent too-long running ones. That way you are sure your CI do not have jobs which run forever.

**Comment by vctqs1** [comment]
Ok, I see, Thanks for your helping. So I think my problem was resolve I'll close ticket now
