### ISSUE TITLE
Running tests in browser UI mode

### ISSUE THREAD

**Issue by rveremeienko** [cucumber/cucumber-js#1842]
I'm using cucumber in combination with the playwright.
Using just playwright I can run tests as in headless as well as in UI mode.
For Cucumber JS seems like there is only one way to run tests only in headless mode.

Is there any way to run tests in UI mode as well? By using available browsers from Playwright?

Thanks in advance.

**Comment by aurelien-reeves** [comment]
I am not sure this is related to cucumber.
Which version are you using? Did you asked to playwright folks? Why do you think that may be related to cucumber?

**Comment by rveremeienko** [comment]
https://www.npmjs.com/package/cucumber-html-reporter I'm using this one version
And I'm thinking that issue is on the cucumber side because I'm using cucumber runner, like here:
https://github.com/ghoshasish99/Playwright-Cucumber

**Comment by aurelien-reeves** [comment]
Cucumber has nothing to do with the browser. You should consider opening an issue here: https://github.com/ghoshasish99/Playwright-Cucumber

**Comment by rveremeienko** [comment]
Thanks!

**Comment by aurelien-reeves** [comment]
You are welcome 

You can keep us informed here! That may help other users!
