### ISSUE TITLE
Screenshots for "cucumber-html-reporter"

### ISSUE THREAD

**Issue by rveremeienko** [cucumber/cucumber-js#1843]
I'm using cucumber in combination with the playwright. And also I'm using "cucumber-html-reporter" to report after the tests run.
Is there a way to attach screenshots to the report if the test fails?

Thanks in advance!

**Comment by aurelien-reeves** [comment]
Which version of cucumber are you using?
The cucumber-html-reporter: is it one from playwright? From cucumber? Another one?

From the cucumber side, attachments are documented here: https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/attachments.md

**Comment by rveremeienko** [comment]
"@cucumber/cucumber": "^8.0.0-rc.1" - version of cucumber
 "cucumber-html-reporter": "^5.5.0" - version of reporter
I'm using this one reporte: https://www.npmjs.com/package/cucumber-html-reporter

**Comment by aurelien-reeves** [comment]
Do you attach screenshots as explained in the documentation?

The reporter you are using is not maintained by cucumber. 

Did you look at their documentation? https://github.com/gkushang/cucumber-html-reporter#attach-screenshots-to-html-report

You may consider opening an issue there: https://github.com/gkushang/cucumber-html-reporter

**Comment by rveremeienko** [comment]
Thanks! Will do!

**Comment by aurelien-reeves** [comment]
You are welcome :)

As with your other issue, do not hesitate to keep us informed here. That may help other users.

**Comment by Nithyachava** [comment]
> Thanks! Will do!

Did you get any update on attaching screenshots for failed test cases?

**Comment by preethinaren** [comment]
I am facing same issue. attach function the screenshot and video files attaching  to the Cucumber report is not working.
can someone please help ?
const playwright = require('@playwright/test')
const { Before, After, Status, setDefaultTimeout,setWorldConstructor,attach} = require('@cucumber/cucumber')
//const { attach } = require('playwright/lib/helper');
const fs = require("fs-extra");
const url = require('../helper/util/test-data/environmentURL.json')

setDefaultTimeout(60000)

class CustomWorld {
  constructor() {
    this.screenshotPath = ''
    this.videoPath = ''
  }
}

setWorldConstructor(CustomWorld)

// Before every scenario, Create new context and page
Before(async () => {
  console.log('Launch Browser')
  // Giving browser- Chromium and headed mode
  global.browser = await playwright['chromium'].launch({ headless: false ,slowMo: 1000})

  console.log('Create new context and page')
  global.context = await global.browser.newContext({
    recordVideo: {
      dir: "test-results/videos",
    },
  });
  global.page = await global.context.newPage()
  await global.page.setViewportSize({ width: 1920, height: 1080 });
  await global.page.goto(url.defaultURL);
  await global.page.waitForTimeout(2000);
})

// After every scenario, Close context and page
After(async (scenario) => {
  //screenshots
  let img;
  let videoPath;
  const timestamp = new Date().toISOString().replace(/:/g, '-');
  const screenshotName = `${scenario.pickle.name}-${timestamp}.png`;
  const videoName = `${scenario.pickle.name}-${timestamp}.webm`;
  if(scenario.result.status === Status.FAILED){
    img = await global.page.screenshot({ path: `./test-results/screenshots/${screenshotName}`, type: "png", fullPage: true });
    this.screenshotPath = img
    videoPath = await global.page.video().path();
    this.videoPath = fs.readFileSync(videoPath)
  }

  console.log('Close context and page')
  await global.page.close()
  await global.context.close()

  console.log('Close Browser')
  await global.browser.close()
  if (this.screenshotPath) {
    attach(this.screenshotPath, "image/png");
  }
  if (this.videoPath) {
    attach(this.videoPath, 'video/webm',videoName);
  }
})
