### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED] when running ng e2e

### ISSUE THREAD

**Issue by dmdum** [cucumber/cucumber-js#1869]
Hello, trying to use cucumber with protractor in angular.
When running `ng e2e --port 4201` I get an error:

E/launcher - Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in C:\Users\dndum\Documents\Projects\angular-project\node_modules\@cucumber\cucumber\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at ModuleLoader.require (C:\Users\dndum\Documents\Projects\angular-project\node_modules\@serenity-js\core\src\io\ModuleLoader.ts:68:20)
    at ModuleLoader.versionOf (C:\Users\dndum\Documents\Projects\angular-project\node_modules\@serenity-js\core\src\io\ModuleLoader.ts:80:33)
[11:27:45] E/launcher - Process exited with error code 100
An unexpected error occurred: undefined

Please advise on how to proceed.
Thank you!

**Comment by aurelien-reeves** [comment]
Hi,

Thank you for your report.

With v8.0.0-rc.1 and the ESM support, indeed package.json is not exported anymore. I will take a look on that to see if we can add it to the exports.

This is actually related to that: https://github.com/cucumber/cucumber-js/issues/1853
serenity-js wants to check the version number from the package.json.
It is difficult to ask them to do otherwise as this is within a generic module loader: https://github.com/serenity-js/serenity-js/blob/master/packages/core/src/io/ModuleLoader.ts#L79

**Comment by dmdum** [comment]
Hello,

Thank you for responding.
Will be using 7.3.1 instead. 
Cheers!

**Comment by aurelien-reeves** [comment]
@dmdum would you have the possibility to test with the following branch: https://github.com/cucumber/cucumber-js/pull/1870?

You should be able to do that with the following:

    npm install https://github.com/cucumber/cucumber-js#export-package-json-again

Important: do not use that branch in production. This is just for testing purpose! 😅

**Comment by dmdum** [comment]
I might be able to after work hours. I'll post here whatever I find.

**Comment by dmdum** [comment]
Hey, sorry for the delay. Been busy the past couple of days. I tried installing today but I got this error.
![image](https://user-images.githubusercontent.com/95848438/145954842-41cafe38-7a33-45d0-b3e8-425bc195a7b5.png)

**Comment by aurelien-reeves** [comment]
Hey :)

Indeed, the branch has been merged on main.
Could you try `npm install https://github.com/cucumber/cucumber-js`?

**Comment by dmdum** [comment]
Got another error
![Capture](https://user-images.githubusercontent.com/95848438/145960995-f2f6f5bd-ddfc-4d14-a149-d455a780765c.PNG)

**Comment by aurelien-reeves** [comment]
Yes
I have suggested a totally wrong command 😑
It won't be as easy as I though because the package needs to be built. So, unfortunately you won't be able to test it before we release it.

Sorry for that 😓

**Comment by dmdum** [comment]
Oh, no worries. Btw, I'm actually still learning cucumber and I was wondering if I can use it on Angular alone without Protractor. Would that be possible? I've been looking for a setup guide on how to do that but Cucumber always seems to be paired with something...

**Comment by aurelien-reeves** [comment]
Actually I don't know Angular or Protractor.
Cucumber can work on its own, it does not need to be coupled with something else.

But maybe Angular itself requires Protractor?

**Comment by dmdum** [comment]
Hmmm, yeah maybe that's it, thanks.

**Comment by davidjgoss** [comment]
Protractor is (or was when I last used it) essentially a wrapper around WebDriver that had special handling for Angular's event loop etc.

You could definitely test an Angular app with Cucumber paired with [WebDriver](https://www.selenium.dev/documentation/webdriver/), [Puppeteer](https://pptr.dev/) or [Playwright](https://playwright.dev/).

There's an [example here with Puppeteer](https://github.com/davidjgoss/cucumber-puppeteer-typescript-starter) (not an endorsement of that over any of the other options, just something I've used).
