### ISSUE TITLE
Introduce sync support

### ISSUE THREAD

**Issue by amatiasq** [cucumber/cucumber-js#187]
As discussed on #27 and [this tweeter thread](https://twitter.com/amatiasq/status/470137821253369856) we should probably add default support for sync tests since async test can be implemented now with promises.

**Comment by aslakhellesoy** [comment]
I think it would be great to allow stepdefs that don't declare a callback. Mocha allows unit tests that don't take a callback.

Is this what you mean @amatiasq @samccone ?

**Comment by samccone** [comment]
"sync" would be nice, we would look at the return value and introspect if it is a Promise or undefined or a flat value.

We could lean on what mocha is doing 100%.

**Comment by amatiasq** [comment]
@aslakhellesoy Yep, that's exactly what I meant.

**Comment by jlin412** [comment]
+1

**Comment by jbpros** [comment]
Closed by cc8a44eab2368140c4ec8c3007dcee55e4dc34dc
