### ISSUE TITLE
false positives with install validator

### ISSUE THREAD

**Issue by cplshma** [cucumber/cucumber-js#1883]
**Describe the bug**
On windows 10 in git bash I execute cucumber the first time after npm install. An error is raised saying the executed install of cucumber is different from my local install, which is not correct. The trace shows that the validator compares my paths case sensitive:
`Error:
      You appear to be executing an install of cucumber (most likely a global install)
      that is different from your local install (the one required in your support files).
      For cucumber to work, you need to execute the same install that is required in your support files.
      Please execute the locally installed version to run your tests.

      Executed Path: C:\Development\web\it\analyse\src\e2e-xray\node_modules\@cucumber\cucumber\lib\index.js
      Local Path:    C:\development\web\it\analyse\src\e2e-xray\node_modules\@cucumber\cucumber\lib\index.js

    at Object.validateInstall (C:\Development\web\it\analyse\src\e2e-xray\node_modules\@cucumber\cucumber\lib\cli
\install_validator.js:28:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Cli.run (C:\Development\web\it\analyse\src\e2e-xray\node_modules\@cucumber\cucumber\lib\cli\index.js
:132:9)
    at async Object.run [as default] (C:\Development\web\it\analyse\src\e2e-xray\node_modules\@cucumber\cucumber\
lib\cli\run.js:25:18)
`

**To Reproduce**
1. Install cucumber via npm
2. Run cucumber: cucumber-js features/**/*.feature
3. Error is raised in console

**Expected behavior**
Cucumber's install_validator recognises paths "C:\Development" and "C:\development" as as equal OS paths

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: na
 - Version 10

**Additional context**

**Comment by davidjgoss** [comment]
Thanks for the detailed report @cplshma!

> Expected behavior
> Cucumber's install_validator recognises paths "C:\Development" and "C:\development" as as equal OS paths

To be clear this would only be the case on Windows - on other platforms, filenames _are_ case sensitive.

Anyway, I think the underlying issue here is that we use Node's `require.resolve` to get the current path, and [browserify's resolve library](https://github.com/browserify/resolve) to get the local path, and they seem to be doing something different regarding case.

I'll try and a test that fails on Windows and we can go from there - hopefully a simple fix.

**Comment by cplshma** [comment]
OK, thank you. I'm happy to check the fix when released.

**Comment by asdfsafd** [comment]
Hi, any news here yet? I have fallen into this trap again.

**Comment by davidjgoss** [comment]
@asdfsafd @cplshma I haven't been able to reproduce this so far in a test. Can you confirm if this only happens from git bash and not a regular windows cmd or powershell?

**Comment by davidjgoss** [comment]
We've just released [v8.5.0](https://github.com/cucumber/cucumber-js/releases/tag/v8.5.0) which includes the fix for this.
