### ISSUE TITLE
security vulnerability in colors@1.4.1 and colors@1.4.44-liberty

### ISSUE THREAD

**Issue by mannyluvstacos** [cucumber/cucumber-js#1884]
**Describe the bug**
A Security Vuln was identified in the Colors package for >1.4.0, offending packages being `1.4.1`, `1.4.44-liberty`
- [source1](https://twitter.com/snyksec/status/1480286811482206216?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)
- [source2](https://twitter.com/snyksec/status/1480286811482206216?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)
- [source3](https://security.snyk.io/vuln/SNYK-JS-COLORS-2331906)

**Comment by jan-molak** [comment]
I've added more details and suggested potential fixes in #1885
