### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by michaelm-rsi** [cucumber/cucumber-js#1896]
This issue is to track and discuss pull requests that I'm working on to help improve the documentation of Cucumber, including resolving some inaccuracies where the markdown files haven't been updated to reflect the current behavior of the application.

**Comment by michaelm-rsi** [comment]
First Pull request concerns the profile.md file.  I will be keeping the PR's focused on one file at a time.

https://github.com/cucumber/cucumber-js/compare/main...michaelm-rsi:patch-3

**Comment by michaelm-rsi** [comment]
First PR here: https://github.com/cucumber/cucumber-js/pull/1897

**Comment by davidjgoss** [comment]
Thanks for your contributions here, closing this now.
