### ISSUE TITLE
`PickleLineFilter` doesn't work with absolute paths

### ISSUE THREAD

**Issue by jan-molak** [cucumber/cucumber-js#1900]
**Describe the bug**

Cucumber ignores line filter when the feature file is described using an absolute path:

So this works:
```
cucumber-js ./features/example.feature:3
```

But this doesn't work and all scenarios from `example.feature` are executed, not just the one on line `3`:

```
cucumber-js /Users/jan/cucumber-demo/features/example.feature:3
```

Original issue reported at https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/238

Possibly related:
- #1783

**To Reproduce**

Please have a look at the repository where I'm [demonstrating the issue](https://github.com/jan-molak/cucumber-js-line-numbers-bug).

I think the issue comes down to this:
- given `featurePaths` are absolute, so `[ '/Users/jan/cucumber-demo/features/example.feature:3' ]`
- they're provided to [`PickleLineFilter`](https://github.com/cucumber/cucumber-js/blob/5498b126d0405cf6c13efe1f8ca56b9116dcbcc9/src/pickle_filter.ts#L58), which creates `featureUriToLinesMapping` as follows:
```
{
  "/Users/jan/cucumber-demo/features/example.feature": [
    3
  ]
}
```
- next, when [`PickleFilter` checks with `PickleLineFilter`](https://github.com/cucumber/cucumber-js/blob/a3aab754155c1c01730338979b586dc644899d23/src/pickle_filter.ts#L47) if a given `pickle` `matchesAnyLine`, it provides it with a **relative** `pickle.uri`
- this then means that the [following check](https://github.com/cucumber/cucumber-js/blob/a3aab754155c1c01730338979b586dc644899d23/src/pickle_filter.ts#L91-L92) can't work:
```typescript
const uri = path.normalize(pickle.uri)                  // relative path
const linesToMatch = this.featureUriToLinesMapping[uri] // a map of absolute paths -> line numbers
```
- and all scenarios from a given feature file are included

**Proposed solution**

I _think_ that since `PickleLineFilter` [has access to `cwd`](https://github.com/cucumber/cucumber-js/blob/a3aab754155c1c01730338979b586dc644899d23/src/pickle_filter.ts#L57) (which it seems to be ignoring at the moment) it might be useful to ensure that both the `featureUriToLinesMapping` and `matchesAnyLine` rely on absolute paths.

**Expected behaviour**
Line number filters should work for both relative and absolute paths.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Checked on Cucumber 5, 6 and 7

**Comment by mpkorstanje** [comment]
Mmh. I would expect Cucumber to identify pickles by the the argument provided and not turn absolute urls into relative ones.

Is there a reason feature paths in the current working would have to be made relative?

**Comment by jan-molak** [comment]
Not that I know of... Maybe @davidjgoss?

**Comment by davidjgoss** [comment]
Yeah the URIs on the Gherkin messages are relative to `cwd` since https://github.com/cucumber/cucumber-js/pull/1672. This happens whether or not you pass a relative or absolute URL in your initial args - the process of resolving the glob args always yeilds an array of absolute paths anyway.

I think providing absolute paths is an under-tested use case for us to date. I'm not sure how best to address this offhand but will take a look. And yeah I expect #1783 is at least somewhat related.
