### ISSUE TITLE
esm: some deep requires don't work

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-js#1902]
**Describe the bug**

Not exactly about ESM, but a symptom of the way we've made the package "hybrid".

Some `require` statements that work fine when everything's CommonJS don't work with new ESM-aware Node versions and our module config.

**To Reproduce**
1. Use `@cucumber/cucumber@8.0.0-rc.2` and `@cucumber/pretty-formatter`
2. Do a test run with `--format @cucumber/pretty-formatter`

**Expected behavior**

Normal test run with output from the formatter.

**Actual behaviour**

```
Error: Cannot find module '/Users/davidgoss/Projects/my-project/node_modules/@cucumber/cucumber/lib/formatter/helpers.js'
```

**Additional context**

The stack trace leads to this require statement in the pretty formatter's compiled code:

```js
const helpers_1 = require("@cucumber/cucumber/lib/formatter/helpers");
```

We have this mapping in our `package.json`:

```json
{
  "exports": {
    ".": {
      "import": "./lib/wrapper.mjs",
      "require": "./lib/index.js"
    },
    "./lib/*": {
      "require": "./lib/*.js"
    },
    "./package.json": "./package.json"
  },
}
```

The actual file it should be importing is:

```
node_modules/@cucumber/cucumber/lib/formatter/helpers/index.js
```

We'll need to either improve this exports mapping or rethink how we're accomodating ESM.

**Comment by davidjgoss** [comment]
I've spent some time experimenting with this (based on extending an existing test https://github.com/cucumber/cucumber-js/pull/1903/commits/d0a63b2c8eeadb33b50cf32e1b12ca7835e149e9), and I don't think we can do any better than what's there now unfortunately.

- We need the `exports` there in order to be compatible with ESM projects
- The [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) functionality that we are using to try to maintain compatibility with old deep `require`s is very limited. This issue https://github.com/jaydenseric/extract-files/issues/17#issuecomment-824528050 summarises it pretty well, but TLDR: it's not possible to have it cover all the permutations people might have written

So I think the least worst strategy is:

- Leave the `exports` config as it is
- Document in the release notes that deep import/requires will likely break
- Fix forward by adding stuff to the main entry point that people need

**Comment by mattwynne** [comment]
Sounds good to me. I always thought deep requires were a bit of a hack anyway, no?

**Comment by davidjgoss** [comment]
@mattwynne agreed - they're always a symptom of something else.

**Comment by davidjgoss** [comment]
Closing the loop on this, I went back over [this comment](https://github.com/cucumber/cucumber-js/issues/1646#issue-863352190) from @jan-molak regarding deep import usages in the wild:

- [ ] `package.json`
- [ ] `TestCaseHookDefinition` (via https://github.com/cucumber/cucumber-js/pull/1903)
- [ ] various issues in `@cucumber/pretty-formatter` (via https://github.com/cucumber/cucumber-js-pretty-formatter/pull/11)
- [ ] `IRuntimeOptions`
- [ ] `ITestCaseHookParameter`
- [ ] `EventDataCollector` - available on `formatterHelpers` from main export (along with tons of other stuff)

**Comment by jan-molak** [comment]
Thanks @davidjgoss - I'll give that a try soon
