### ISSUE TITLE
Is there any way to integrate cucumber.js with sauce labs?

### ISSUE THREAD

**Issue by goncalovarela** [cucumber/cucumber-js#1923]
Hi,
I'm running my tests in playwright using cucumber.js. 
I would like to know if there's a way to run them in sauce labs and how can I do it. 
Thank you

**Comment by aurelien-reeves** [comment]
Hi,

From what I can see in the sauce labs documentation here: https://docs.saucelabs.com/web-apps/automated-testing/selenium/

Specially on the following picture:
![image](https://user-images.githubusercontent.com/24386780/154020792-a3762b40-3ac0-49b6-b37b-1df6e043f135.png)

Sauce labs is after the browser automation tool - selenium here - in the test stages. Cucumber will be placed before it, at the "test" and "framework" stage. So, there is no issue into running cucumber tests on sauce labs environment.

Simply automate your tests as usual with selenium/testcafé/cypress/puppeteer/whatever saucelabs compatible tool. This is then that tool that you will have to integrate with saucelabs. Cucumber itself is not involved with this actually.

Does that help?
