### ISSUE TITLE
Alternate config file location option not found

### ISSUE THREAD

**Issue by lunchboxdc** [cucumber/cucumber-js#1935]
### 👓 What did you see?

There's a documented cli option to specify an alternate config file name/path other than ./cucumber.js here
https://github.com/cucumber/cucumber-js/blob/main/docs/profiles.md#using-another-file-than-cucumberjs

When I attempt to use either `-c` or `--config` I receive an error:
```
$ ./node_modules/.bin/cucumber-js -c cuc.js
error: unknown option '-c'

$ ./node_modules/.bin/cucumber-js --config cuc.js
error: unknown option '--config'
```

### ✅ What did you expect to see?

The options `-c` and `--config` should be valid and functionally find and use an alternate config file

### 📦 Which version are you using?

@cucumber/cucumber -> 7.3.2
node -> 16.4.2

### 🔬 How could we reproduce it?

Install cucumber-js and run the command above with a valid alternate config file.

**Comment by davidjgoss** [comment]
Hey @lunchboxdc, that option hasn't made it into a stable release yet, you can find the docs that reflect 7.3.2 here https://github.com/cucumber/cucumber-js/tree/7.x and meanwhile 8.0.0 will be out soon with that new option.

**Comment by lunchboxdc** [comment]
Got it, thanks!
