### ISSUE TITLE
[Docs] This argument as first parameter to step definition function

### ISSUE THREAD

**Issue by Izhaki** [cucumber/cucumber-js#1948]
In https://github.com/cucumber/cucumber-js/issues/1667#issuecomment-834306870 the proposed solution by @davidjgoss is:

```typescript
import {Then, World} from '@cucumber/cucumber';

Then('the test runs with string parameter {string}', async function(this: World, parameter: string) {
    this.driver.close()
})
```

I could not find any mention of this in the docs. Further, 20m of code surfing, and I couldn't even find where this is actually happening.

If this an official API? This changes things quite a bit as it unlocks the use of arrow functions.

We would like our world to be typed, and right now this is the only way to do this. So we need insurance this API is official.

**Comment by davidjgoss** [comment]
Hey @Izhaki, bit of a misunderstanding here. The context of that issue and my comment was TypeScript, which allows you to type `this` for a function by prepending it to the arguments - but it's not an actual argument and is compiled out. See https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function. A quick playground to demo:

![image](https://user-images.githubusercontent.com/3192745/156374830-07d431e6-a78c-4863-95eb-d0dee19e36b3.png)

Unfortunately the limitation of arrow functions is unchanged. You might consider trying https://github.com/jbpros/cucumber-fp for an approach that skirts the `this` issue.

**Comment by davidjgoss** [comment]
> We would like our world to be typed, and right now this is the only way to do this. So we need insurance this API is official.

To answer this specifically: yes if you're using TypeScript then whatever class you pass to `setWorldConstructor` you can type the step/hook functions with and you should get the type safety you need.

**Comment by Izhaki** [comment]
Awesome. Thanks!
