### ISSUE TITLE
Tag outline scenarios - it runs only one scenario

### ISSUE THREAD

**Issue by akania** [cucumber/cucumber-js#195]
Given a Feature with scenario:

```
Feature: test
    @sometag
    Scenario Outline: Scenario outline - run this scenario with different examples
                      To run one scenario with different set of values use scenario outlines

        Given There is initial <value>
        When I subsctract <subsctractValue>
        Then I should have <resultValue>

    Examples:
    | value | subsctractValue | resultValue |
    |  12   |  5              |  7          |
    |  20   |  5              |  15         |
```

And step definition

```
var testSteps = function() {
  var Given  = When = Then = this.defineStep;


  Given(/^There is initial (\d+)$/, function(value, callback) {
      this.value = value;
      callback();
  });
  When(/^I subsctract (\d+)$/, function(substractValue, callback) {
      this.result = this.value - substractValue;
      callback();
  });
  Then(/^I should have (\d+)$/, function(result, callback) {
      if (parseInt(result) === this.result) {
          callback();
      } else {
          callback.fail();    
      }
  });
};
module.exports = testSteps;
```

When i run 'cucumber-js --tags @sometag'

Scenario is executed only once with first row of examples

```
cucumber.js --tags @sometag
....

1 scenario (1 passed)
4 steps (4 passed)
```

Expected  - scenario should be executed for all examples

**Comment by XxJChavezxX** [comment]
I run into a similar issue, but in my case, only the last row on the table gets run. Any feedback of how to approach this would be great

**Comment by charlierudolph** [comment]
What version of cucumber-js are you running? This [feature](https://github.com/cucumber/cucumber-js/blob/6c0c4c94710f23607dfece6f58a1a91d97a04316/features/target_specific_scenarios_by_tag.feature) encompasses the current behavior and was added in 0.9.1.

**Comment by XxJChavezxX** [comment]
I'm using cucumberjs version: 0.9.2 with nightwatchjs and the cucumber plugin version - 0.6.7. Not sure if the latest help. 

Table looks like this:
 Examples:
    | extension    |
    | MLB            |
    | NASCAR    | 
    | SOCCER    |
    | NBA            |

and the step that uses it: 
When I click on link "<extension>"

I'm adding additional info just in case it helps.

**Comment by charlierudolph** [comment]
Based on the [cucumber plugin changelog](https://github.com/mucsi96/nightwatch-cucumber#120-february-6-2016) scenario outlines weren't supported until 1.2.0.

**Comment by XxJChavezxX** [comment]
Yeah, it works now, after updating to a newer version. Apologies I should have checked the changelog.
