### ISSUE TITLE
reportal portal is not supporting for @cucumber/cucumber

### ISSUE THREAD

**Issue by Rajkumar502** [cucumber/cucumber-js#1965]
i am trying to integrate report portal using @reportportal/agent-js-cucumber but i could not connect using @cucumber/cucumber when i try to connect it is throwing me error cucumber node module is not found 

let me know is there any workaround for this i trying with version as below  
"@reportportal/agent-js-cucumber": "5.0.2",
"@cucumber/cucumber": "7.3.2"

**Comment by davidjgoss** [comment]
Looks like the package you mention expects an older version of cucumber. You could change your cucumber dependency to

```
"cucumber": "6.0.5"
```

And/or raise an issue with the other package to upgrade their cucumber support https://github.com/reportportal/agent-js-cucumber
