### ISSUE TITLE
 I like cucumber and jest, Is there any way  to use jest.mock in steps?

### ISSUE THREAD

**Issue by pansinm** [cucumber/cucumber-js#1967]

**Comment by aurelien-reeves** [comment]
Well, I guess nothing would prevent to use jest.mock in your step definitions

Did you tried? If so, did you faced some issues?

**Comment by pansinm** [comment]
I tried run cucumber
```bash
yarn cucumber-js --require-module @babel/register --require 'features/step-definitions/**/*.js'
```
with babel.config.js
```js
module.exports = {
  presets: ["@babel/preset-env"],
  plugins: ["jest-hoist"],
};
```
then throw error:
```
Error: Do not import `@jest/globals` outside of the Jest test environment
```

**Comment by davidjgoss** [comment]
Yeah jest.mock is very much part of Jest as a test runner, affecting how modules are loaded etc, hence the message there, so I don’t think there’s a way to use it with Cucumber.

You might consider something like Sinon which is standalone https://sinonjs.org/

**Comment by pansinm** [comment]
https://github.com/pansinm/cucumber-jest-mock-sample

**Comment by bliu13** [comment]
@davidjgoss, Anything else you might recommend that is an alternative to Sinon?
https://stackoverflow.com/questions/50763323/stub-an-export-from-a-native-es-module-without-babel/50763914#50763914
