### ISSUE TITLE
Cucumber-js web-site cannot be opened in Belarus

### ISSUE THREAD

**Issue by drweb86** [cucumber/cucumber-js#1983]
### 👓 What did you see?

I cannot open cucumber-js web-site . It says **CloudFront distribution is configured to block access from your country**
![image](https://user-images.githubusercontent.com/4712173/161432145-d828b66b-88b0-4138-95a4-6403e9db1ceb.png)

I guess I found the reason. I found PR about Ukraine support. So, my guess it was done on purpose.

Personally, I'm against any war as anyone on a planet. However, I feel excluding me from usage of cucumber website as a form of racism. Especially it looks ugly for entire Belarus.

Can you comment on that?

Apart from that I'm a little bit puzzled. I wrote some time ago cucumber extension for VS code to format feature files. Since i'm not of a good race to use cucumber website, is it ok to have it still published?

And one more question, the company I'm working for is using cucumber. And I don't know what to do since I really like cucumber, but racism inside company is prohibited and should I schedule meeting about alternatives.

I feel sad.

**Comment by davidjgoss** [comment]
@drweb86 what’s the URL you’re trying to reach?

**Comment by drweb86** [comment]
@davidjgoss 
https://cucumber.io/docs/installation/javascript/

**Comment by mattwynne** [comment]
Thanks for letting us know about this problem @drweb86, for your words in support of peace and of course for the [Gherkin Beautifier](https://marketplace.visualstudio.com/items?itemName=siarheikuchuk.gherkin-beautifier-vs-code-plugin) VSCode plugin. ❤️

I'm not sure why the website cannot be accessed in Belarus. It has nothing to do with us adding the banner as requested in #1961. That simply put a message on our GitHub `README` files. It didn't do anything to change who can access the website.

The block could be happening at multiple layers of our infrastructure, not all of which I have immediate access to. We'll investigate and let you know.

In the mean time, you can read the docs from source, [here](https://github.com/cucumber/docs/blob/main/content/docs/installation/javascript.md).

**Comment by drweb86** [comment]
@mattwynne , @davidjgoss Thank you for so prompt response and good attitude. BTW I haven't thought doc is here in sources.

**Comment by aslakhellesoy** [comment]
We have decided to block traffic from Russia and Belarus to the cucumber.io domain until further notice. We're sorry for the inconvenience this causes for individuals residing in these countries. Because of the sensitivity of this topic this issue has been closed for further comments.
