### ISSUE TITLE
cucumber.github.io/cucumber-js/ is out of date

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-js#1984]
### 👓 What did you see?

Looks like `cucumber-js` has it's own github pages running on:

https://cucumber.github.io/cucumber-js/

It appears to be 2 years old now. Consider removing or updating it regularly again.

**Comment by davidjgoss** [comment]
Yeah this is defunct and should be switched off, thanks for raising.

**Comment by aurelien-reeves** [comment]
So, do we just switch-off pages for that project? Or would you prefer we announce it or something else?
Do we add a redirection to cucumber.io?

**Comment by davidjgoss** [comment]
Done via https://github.com/cucumber/cucumber-js/commit/b6a8cedf98daed159837f0ba31be12717d8dc762
