### ISSUE TITLE
Version 7.3.x documentation (mostly around config) includes details only released in Version 8

### ISSUE THREAD

**Issue by LukaHedt** [cucumber/cucumber-js#1986]
Hi!

Can we add some warnings in the Config documentation that the `cucumber.(js | mjs | cjs | json)` config option is only available in v8.x.x?

I spent about half a day trying to figure out why it wasn't working with v7.3.8 before I looked in the changelog and realised I needed to upgrade.

Thanks :D

**Comment by aurelien-reeves** [comment]
Do you have a link that point to the documentation you are referring to?

**Comment by LukaHedt** [comment]
https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md

Specifically this configuration page, but as far as I'm aware, there's references to this configuration style throughout the `/docs` folder

**Comment by aurelien-reeves** [comment]
Thanks :)

As explained in the [readme](https://github.com/cucumber/cucumber-js#documentation), the documentation on the main branch may contain documentation related to unreleased things.

There are dedicated branches for the documentation of previous versions, which should be accurate

**Comment by LukaHedt** [comment]
Hmmm okay.

That's very unintuitive, given it doesn't say exactly which unreleased things are documented.

Thanks anyway :)

**Comment by davidjgoss** [comment]
It's a fair point @LukaHedt! We'll likely release 8.0.0 in the next day or two and will aim to avoid this kind of thing in future - probably by just not leaving things unreleased and getting releases out more frequently.

**Comment by LukaHedt** [comment]
Thankyou!!

It's probably not a huge deal apart from anyone who's started learning the framework in the last 2-3 weeks (ie me :p )

**Comment by mattwynne** [comment]
@LukaHedt thanks for the feedback! Would #1989 have helped?

**Comment by LukaHedt** [comment]
Heya Matt!

Yeah I think so! At least when using 7.x's version.

Since v8.0 has been released, it's less of a weird disconnect, but I totally appreciate it!

Thanks :D
