### ISSUE TITLE
Typescript error TS1192: Module '"http"' has no default export

### ISSUE THREAD

**Issue by remss** [cucumber/cucumber-js#1988]
### 👓 What did you see?

When running typescript compilation I see this error 

    node_modules/@cucumber/cucumber/lib/formatter/http_stream.d.ts:3:8 - error TS1192: Module '"http"' has no default export.

### ✅ What did you expect to see?

No error

### 📦 Which tool/library version are you using?

  * CucumberJS 7.3.2
  * TypeScript 4.6.3
  * NodeJS 14.17

### 🔬 How could we reproduce it?

```
// package.json
{
    "private": true,
    "name": "test",
    "version": "1.0.0",
    "description": "",
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@cucumber/cucumber": "^7.3.2",
        "@types/node": "14.17",
        "typescript": "^4.6.3"
    },
    "scripts": {
        "build": "tsc",
        "test": "cucumber-js --require \"dist/**/*.js\" --publish-quiet ./test/features/"
    }
}
```

Create a file `tsconfig.json`
```
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es2021",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "strict": true,
        "resolveJsonModule": true,
    },
    "include": [
        "test/**/*"
    ],
}
```

Create a file `test\features\testme.feature`
```
Feature: Test My App

    Scenario: A first scenario

        When I do this
        Then i see that
```

Create a file `test\features\step_definitions\app.ts`
```
import { When, Then, World } from '@cucumber/cucumber'

When<World>('I do this', async function () {
    // Fake action
})

Then<World>('i see that', async function () {
    throw new Error('Failed assertion!')
})
```

Run command ``npm install`

Run command ``npm run build` and see the error

```
> test@1.0.0 build
> tsc

node_modules/@cucumber/cucumber/lib/formatter/http_stream.d.ts:3:8 - error TS1192: Module '"http"' has no default export.

3 import http from 'http';
         ~~~~


Found 1 error in node_modules/@cucumber/cucumber/lib/formatter/http_stream.d.ts:3
```

**Comment by davidjgoss** [comment]
Thanks for the detailed info @remss 

Could you try adding `"esModuleInterop": true,` to your compiler options as a workaround?

**Comment by davidjgoss** [comment]
@remss yes and no - I think this would be a breaking change for those currently using `"esModuleInterop": true`. I think `"allowSyntheticDefaultImports": true` should allow both styles to work, would you mind trying that?

**Comment by remss** [comment]
I confirm it works fine with `allowSyntheticDefaultImports: true`, thank you 👍
I think it should be mentioned in [transpiling documentation](https://github.com/cucumber/cucumber-js/blob/main/docs/transpiling.md).

**Comment by davidjgoss** [comment]
@remss agreed, done that just now 👍 

Longer term I'd like to look into slimming down the amount of declarations we include in the package so this can be avoided.
