### ISSUE TITLE
willBeRetried is not under result anymore after "@cucumber/cucumber": "^8.0.0",

### ISSUE THREAD

**Issue by Huseyinaltas1** [cucumber/cucumber-js#2010]
"willBeRetried" was a property of "result" before I upgraded to  "@cucumber/cucumber": "^8.0.0".
I see now it is "undefined" for below hook. I did not find willBeRetried in any other ITestCaseHookParameter Interface. Thank you in advance.

After(async function (scenario) {
   console.log(scenario.result.willBeRetried)
}

#######

I was expecting to make sure scenario will be retired or not.
Node: 16.14.2
npm:8.5.0
"dependencies": {
        "@cucumber/cucumber": "^8.0.0",
        "@ericblade/quagga2": "^1.4.2",
        "axios": "^0.26.0",
        "dotenv-flow": "^3.2.0",
        "googleapis": "^88.2.0",
        "pixelmatch": "^5.2.1",
        "puppeteer": "^13.5.0",
        "puppeteer-har": "^1.1.2",
        "sharp": "^0.29.3",
        "tesseract.js": "^2.1.5"
    }

#######

When you try this with above dependencies, It is reproduced. 

After(async function (scenario) {
   console.log(scenario.result.willBeRetried)
}
Output: undefined

**Comment by aurelien-reeves** [comment]
Hello, and thanks for reporting this.

[There have been some changes](https://github.com/cucumber/cucumber-js/pull/1776) with the `willBeRetried` property.

We have missed to document that change 😓

The `willBeRetried` info is now part of the `messages` and can be found in the `testCaseFinished` one.

May I ask: what is your need? What are you trying to achieve? Is it for reporting purpose or for something else?

**Comment by davidjgoss** [comment]
Yeah `willBeRetried` was kind of misplaced on the test step result message hence the move.

This feels somewhat related to #1851 - we expose the messages to the hooks but these can change and aren't very ergonomic to use on their own without the associated querying libraries.

> May I ask: what is your need? What are you trying to achieve? Is it for reporting purpose or for something else?

Definitely interested in this too! I see no issue with adding `willBeRetried` to that hook parameter, but would be good to really understand the need.

**Comment by Huseyinaltas1** [comment]
Thank you @aurelien-reeves  and @davidjgoss for response.

**_"The **willBeRetried** info is now part of the **messages** and can be found in the **testCaseFinished** one."_**

I don't see any **messages** interface there unfortunately. I checked types.d.ts and there is no **messages** parameter either. I see only **gherkinDocument**, **pickle**, **result**, **testCaseStartedId**.

`import * as messages from '@cucumber/messages';
import TestCaseHookDefinition from '../models/test_case_hook_definition';
import TestStepHookDefinition from '../models/test_step_hook_definition';
import TestRunHookDefinition from '../models/test_run_hook_definition';
import StepDefinition from '../models/step_definition';
import { ParameterTypeRegistry } from '@cucumber/cucumber-expressions';
import { IWorld } from './world';
export declare type DefineStepPattern = string | RegExp;
export declare type ParallelAssignmentValidator = (pickle: messages.Pickle, runningPickles: messages.Pickle[]) => boolean;
export interface ITestCaseHookParameter {
    gherkinDocument: messages.GherkinDocument;
    pickle: messages.Pickle;
    result?: messages.TestStepResult;
    testCaseStartedId: string;
}
export interface ITestStepHookParameter {
    gherkinDocument: messages.GherkinDocument;
    pickle: messages.Pickle;
    pickleStep: messages.PickleStep;
    result: messages.TestStepResult;
    testCaseStartedId: string;
    testStepId: string;
}`

**_May I ask: what is your need? What are you trying to achieve? Is it for reporting purpose or for something else?_**

I save screenshot of a e-commerce receipt barcode with scenario name but if it is failed and will be run secondly I am adding '-2nd' string as Suffix end of this screenshot name. Like:
`scenario.result.willBeRetried == true ? (scenarioScope.secondRun = '-2nd') : (scenarioScope.secondRun = '');`
`this.scenarioId = step.pickle.id + '' + secondRun;`

**Comment by Huseyinaltas1** [comment]
Actually I have another solution for that for now. I just wondered if it was a defect and I wanted to help cucumber family. 😅

**Comment by aurelien-reeves** [comment]
That is nice actually, thank you!

So, no, this is not a defect. This is an impact of something else done on purpose

So, if you find a workaround, that is great. Would you agree to close the issue? We could still easily reopen it if someone else report that "issue" and requires a more concrete fix!?
