### ISSUE TITLE
Cucumberjs parallel run - Error when tried to run with more than 2 instances

### ISSUE THREAD

**Issue by sumitsg004** [cucumber/cucumber-js#2013]
Hi Team, 

I have a playwright UI automation repo with cucumberjs framework. To run tests parallelly I provide the parallel parameter in cucumber.js file as a option to the command. 
With parameter value 2 - two browser instances open and run successfully, but when I run with parameter value 3 - the third instance timeout and gives error while two instances run successfully. 

Parameter provided in cucumber.js - 
let **runCucumber** = [
  `--parallel 3`, // Specify number of parallel workers
  tags,
  'xyz-features/**/*.feature', // Specify our feature files
  '--require-module ts-node/register', // Load TypeScript module
  '--require xyz-features/**/*.ts', // Load step definitions
  '--format progress-bar', // Load custom formatter
  '--format json:./reports/json/cucumber_report.json'
].join(' ');

run command in package.json
"test": "npm-run-all report-config **cucumber-execution** reports-generator --continue-on-error",

"cucumber-execution": ".\\node_modules\\.bin\\cucumber-js -p **runCucumber**",

Error for third browser instance - 
browserType.launch: Timeout 30000ms exceeded.

(launched) pid=45960
[pid=45960][err] [45960:50024:0430/125152.962:ERROR:tcp_socket_win.cc(356)] bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0x2740)
[pid=45960][err] [45960:50024:0430/125152.963:ERROR:tcp_socket_win.cc(356)] bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0x2740)
[pid=45960][err] [45960:50024:0430/125152.963:ERROR:devtools_http_handler.cc(297)] Cannot start http server for devtools.

Can someone please help with this issue, any suggestions on how to run with 3 or more instances, or should i use a different approach ?

**Comment by davidjgoss** [comment]
Cucumber has no problem with 3+ parallel workers, this is going to be down to your automation tools/setup.

The error there is coming from a Playwright function https://playwright.dev/docs/api/class-browsertype#browser-type-launch - I know they have closed your issue over there but I think it's going to be that or something deeper with Chromium. You could try without the devtools option.
