### ISSUE TITLE
Why are you poluting my work environment, my CI and my terminal with advertisement?

### ISSUE THREAD

**Issue by Aschen** [cucumber/cucumber-js#2036]
I've installed the latest version at `@cucumber/cucumber-js` because with the old one I had useless messages bloating my standard output while running my functional tests. Those messages asked my to upgrade to the new package version.

I've upgrade and now I have another advertisement message bloating my terminal each time I'm running my tests.

I would like you to consider the fact that developers are using your software to run tests so most of the time they will see you messages when they are fixing tests. Fixing tests is boring, annoying, confusing and I'm sure the last thing you want is associating your product with those feelings (at least for me you just did).

I'm using cucumber for years now and it was working like a charm

PS: I don't know where is the `cucumber.js` file where I'm supposed to opt out for advertisement. 

![image](https://user-images.githubusercontent.com/4447392/167285198-3dc5b236-7ab9-47e8-8abb-0d190ccaf8e6.png)

**Comment by mpkorstanje** [comment]
It seems that you are mostly looking to vent your frustration? A GitHub issue might not be the right place. I personally found [An Engineers Guide to happiness](https://anengineersguide.com/) quite useful though.

The documentation for configuration and several example projects are linked from the readme.
 - https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md
 - https://github.com/cucumber-examples/cucumber-js-examples

**Comment by Aschen** [comment]
It's actually a good guide, and you are right. Please accept apologize for this.

Still, I'm not sure advertising your product by default at every run of cucumber is a good idea
