### ISSUE TITLE
@cucumber/cucumber 8.1.1 Cannot use import statement outside a module

### ISSUE THREAD

**Issue by VictorVermeulen** [cucumber/cucumber-js#2060]
### 👓 What did you see?

When running Cucumber with TypeScript, I get the error `Cannot use import statement outside a module` from a subdependency.

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1117:16)
    at Module._compile (internal/modules/cjs/loader.js:1165:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (/myfolder/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at /myfolder/node_modules/@cucumber/cucumber/src/api/support.ts:24:30
    at Array.map (<anonymous>)

### ✅ What did you expect to see?

The code properly transpiling

### 📦 Which tool/library version are you using?

TypeScript 4.6.2, @cucumber/cucumber 8.1.1, ts-node 9.0.0

The error comes from this file https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/packages/ie11-detection/src/KeyOperation.ts, which is a subdependency from aws sdk-v3.

### 📚 Any additional context?

We tried all of the suggested things in this article https://bobbyhadz.com/blog/typescript-cannot-use-import-statement-outside-module, so changes in the tsconfig.json don't seem to work.

Right now we are using without success. 

"target": "ES2018",
"module": "commonjs",
"lib": [
        "es2018",
        "es2019",
        "es2020.Promise",
        "DOM",
      ],

**Comment by aurelien-reeves** [comment]
Could you take a look on the following doc and make sure it seems fine for your project?

- https://github.com/cucumber/cucumber-js/blob/main/docs/transpiling.md#typescript
- https://github.com/cucumber/cucumber-js/blob/main/docs/esm.md

If you are still facing the issue, would you have the possibility to set-up a repo with a minimal reproducible example? That would be really easier for us to investigate with actual and minimal code

**Comment by davidjgoss** [comment]
What does your cucumber config file look like?

**Comment by VictorVermeulen** [comment]
We removed it trying to fix the issue, and now we have it in the command as: 

```cucumber-js __test__/integration/**/*.feature --require-module ts-node/register --require __test__/integration/**/*.spec.ts```

**Comment by VictorVermeulen** [comment]
It looks like we solved this by:
- Removing package.json, package.lock and node_modules from cucumber/integration test folder and only using ''general'' package.json in project.
- using module: CommonJS in tsconfig.json
- using allowSyntheticDefaultImports true in tsconfig.json
- using noImplicitReturns true in tsconfig.json
- use TypeScript 4.6.4
- use ts-node 9.1.1
- use @cucumber/cucumber 7.3.2
