### ISSUE TITLE
Cannot read property 'CUCUMBER_PUBLISH_ENABLED' of undefined

### ISSUE THREAD

**Issue by nchetbani** [cucumber/cucumber-js#2079]
After migrating my cucumber version from `cucumber 7.0.0-rc.0` to `@cucumber/cucumber 8.4.0`, when i lunch my E2E test via protractor i get the following : 

`Cannot read property 'CUCUMBER_PUBLISH_ENABLED' of undefined`

Any help or idea please ?

**Comment by aurelien-reeves** [comment]
Do you have a more comprehensive stack trace?

How are you integrating protractor with cucumber? Do you rely on another package?

Can you make sure you have no more 'cucumber' package in your modules but only '@cucumber/*` ones?

Did you tried to remove your `node_modules` folder and your `package-lock.json`, and to run `npm install` again?

**Comment by aurelien-reeves** [comment]
Do you have the possibility to share a little bit of your project, your configuration, how cucumber is actually run?
Do you have answers to my other questions too? Mainly: how are you integrating protractor with cucumber? Do you rely on another package?

**Comment by nchetbani** [comment]
Even deleting the node_modules/package-lock.json and re-running npm install doesn't fix the problem.I get the same error

My tests are launched by running this command :` protractor e2e/protractor.conf.js`

project-root/e2e/protractor.conf.js

```
/**
 * @type { import("protractor").Config }
 *   { import("browser").protractor }
 */


exports.config = {

  allScriptsTimeout: 11000,

  specs: [
    "src/features/menu.feature",
    "src/features/dbridge.feature",
    "src/features/filtersSystem.feature"
  ],
  capabilities: {
    browserName: 'chrome',
    'chromeOptions': {
      'args': ['headless', 'no-sandbox', 'disable-dev-shm-usage']
    }
  },

  seleniumAddress: "http://localhost:4444/wd/hub",

  SELENIUM_PROMISE_MANAGER: false,
  baseUrl: 'http://localhost:4200/',

  framework: "custom",
  frameworkPath: require.resolve("protractor-cucumber-framework"),
  cucumberOpts: {
    require: ['./src/stepDefinitions/**/*.steps.ts'],
  },

  onPrepare() {

    require('ts-node').register({
      project: require('path').join(__dirname, './tsconfig.json')
    });
  }
};
```
project-root/e2e/tsconfig.json

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/e2e",
    "module": "commonjs",
    "target": "es2018",
    "types": ["chai","node"]
  }
}
```

My project structure look like this

```
project-root
------src
------e2e
---------protractor.conf.js
---------tsconfig.json
---------src
------------features
------------pageObjects
------------stepDefinitions
```

**Comment by nchetbani** [comment]
I remain at your disposal for any further details

**Comment by aurelien-reeves** [comment]
That depends on SerinityJS, then protractor.

You can open issues for those projects, or submit PRs to initiate the upgrade
