### ISSUE TITLE
Is there a support for Scenario Outline?

### ISSUE THREAD

**Issue by njagadee** [cucumber/cucumber-js#208]
Hi,

Do we have a support for Scenario Outline with Examples table? I tried and get this error: Error: Scenario outlines are not supported yet. See https://github.com/cucumber/cucumber-js/issues/10

I am seeing mixed comments. Some say it's added but I don't see it. Can you please help?

**Comment by rasjani** [comment]
For people who end up here from google: 

If you use grunt-cucumber to run your tests -  hasnt been updated in ages and it uses old cucumber that does not support Scenario Outlines. Use grunt-cucumber-sigma instead ..

**Comment by ciekawy** [comment]
also for UI test cucumber-js runs well with grunt-protractor-runner
