### ISSUE TITLE
cucumber js Parallel query

### ISSUE THREAD

**Issue by splurgeop** [cucumber/cucumber-js#2090]
I am trying to use parallel for running the all the scenarios in parallel.
I am using webdriver IO and cucumber as the runner
below is the part of wdio conf with cucumber options
export const config = {
.
.
.

 framework: 'cucumber',
    reporters: reporterList,
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./dist/**/*.js'],

        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: true,
        // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        format: ['pretty'],
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: featuresToAdd.features.tagsToInclude.join(" or "),
        // <number> timeout for step definitions
        timeout: 150 * 1000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false,
        //specify the parallel runs
        parallel: 2
    }
   }

To test this i am having just one feature file with 2 scenario and i am trying to run them in parallel.
I am expecting two chrome browsers will open up and they will be picking the 2 different  scenarios present in the feature file.
But it seems just one browser is picked up which executes both the tests. Have gone thru the below documentation as well 

https://github.com/cucumber/cucumber-js/blob/main/docs/parallel.md

**Comment by davidjgoss** [comment]
The wdio docs don’t list parallel as a supported option:
https://webdriver.io/docs/frameworks/

I think this would be best raised with them to find out why.
