### ISSUE TITLE
Parallel testing not working when scenarios are using steps from multiple step definition files

### ISSUE THREAD

**Issue by danieljonguitud** [cucumber/cucumber-js#2108]
### 👓 What did you see?

When running cucumber with `--parallel` the runner tries to run each scenario agains all step definitions files making the scenario to fail if it reuses multiple steps from different step definitions.

### ✅ What did you expect to see?

I was expecting the parallel test to run as usual when running each scenario one by one. Where is doesn't matter if the scenario has multiple steps from multiple step definition files

### 📦 Which tool/library version are you using?

Nightwatch: "^2.2.2"
Cucumber: "^8.4.0"

### 🔬 How could we reproduce it?

1. `npm install nightwatch @cucumber/cucumber`
2. Add a nightwatch.conf.js
3. Follow this setup https://nightwatchjs.org/guide/writing-tests/using-cucumberjs.html#using-cucumberjs-with-nightwatch
4. Create a feature file that reference steps in multiple step definitions files
5. Try to run the tests in parallel.
6. You should be getting errors like in the screenshot attached.

![Screen Shot 2022-08-08 at 11 48 22 AM](https://user-images.githubusercontent.com/16572481/183491651-4a9974de-c8c9-467d-b413-19e783850123.png)

### 📚 Any additional context?

Not for the moment.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
This seems like more of a nightwatch issue if anything. Are you able to produce an issue with just Cucumber?

**Comment by danieljonguitud** [comment]
Hey @davidjgoss thank you for anwering. You are right, this issue seems to be nightwatch specific and they seems to be working on it already. Here is the issue link for anyone interested: https://github.com/nightwatchjs/nightwatch/issues/3317
