### ISSUE TITLE
Same name feature file referring to different project feature if any

### ISSUE THREAD

**Issue by ChinmoyJana14** [cucumber/cucumber-js#2117]
Same name feature file referring to different project feature if any. 
I was expecting to have the message in the console 
You can implement missing steps with the snippets below:
instead it is reffering to some different project in my eclipse having same name feature file and executing those steps

	<dependency>
	    <groupId>io.cucumber</groupId>
	    <artifactId>cucumber-java</artifactId>
	    <version>7.4.1</version>
	</dependency>

### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
It looks like you’re using cucumber-jvm, you’ll need to raise this there https://github.com/cucumber/cucumber-jvm.

(it might be worth adding more about your project structure if possible)

**Comment by ChinmoyJana14** [comment]
ok. Thanks. I have raised #2601 with screenshot
