### ISSUE TITLE
Cucumber creating src folder under dist after npm run build

### ISSUE THREAD

**Issue by nitinmagdumvista** [cucumber/cucumber-js#2122]
Hello i am using cucumber with nestjs project

without cucumber when i used to build the app using  npm run build it used to create main.js under dist folder 
dist/main.js

but with cucumber when i build app it is creating main.js file under src folder 
dist/src/main.js 

so i had to adjust my start command from 
"start:prod": "node dist/main",     to     "start:prod": "node dist/src/main",

any idea why it is creating also is there a way we can avoid it.

below is the folder structure - cucumber.js, package.json, features 

![Screen Shot 2022-08-30 at 1 00 27 AM](https://user-images.githubusercontent.com/109283064/187283093-c06cb512-6686-4253-88be-8b6de58916ca.png)

**Comment by nitinmagdumvista** [comment]
"@cucumber/cucumber": "^8.5.2",

**Comment by nitinmagdumvista** [comment]
[davidjgoss](https://github.com/davidjgoss)

**Comment by davidjgoss** [comment]
It's hard to know without seeing your full config etc, but I'd suspect your tsconfig is a bit broad and it's now picking up stuff that's outside of `src`, hence giving you a root directory. If you look at what's directly inside of `dist` that might give you a clue.

**Comment by aslakhellesoy** [comment]
This doesn't sound related to Cucumber. It sounds related to how the `tsc` compiler is configured.
