### ISSUE TITLE
Missing type definition for `@sinon/fake-timers`

### ISSUE THREAD

**Issue by christian-bromann** [cucumber/cucumber-js#2141]
### 👓 What did you see?

[This commit](https://github.com/cucumber/cucumber-js/commit/0ac8f58c1da3bb4a14946d8c475a4a47edfbbead) introduces type usage from `@sinonjs/fake-timers` however these types are defined as [devDependencies](https://github.com/cucumber/cucumber-js/blob/main/package.json#L260). This causes 3rd party users like WebdriverIO to fail due to `Could not find a declaration file for module '@sinonjs/fake-timers'`.

### ✅ What did you expect to see?

Have `@types/sinonjs__fake-timers` as dependency now given their types are used and exposed.

### 📦 Which tool/library version are you using?

Latest CucumberJS

### 🔬 How could we reproduce it?

n/a

### 📚 Any additional context?

See failing builds for WebdriverIO: https://github.com/webdriverio/webdriverio/actions/runs/3090504859/jobs/4999391609

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
Thanks for raising @christian-bromann, will get something out for this shortly.

**Comment by davidjgoss** [comment]
I reworked this to avoid relying on the sinon types which should resolve the issue. Published [8.6.0](https://github.com/cucumber/cucumber-js/releases/tag/v8.6.0) including this - let me know if that does the trick.
