### ISSUE TITLE
Is it possible to run after hook with tags before after hook with no tab? 

### ISSUE THREAD

**Issue by ooo2003003v2** [cucumber/cucumber-js#2155]
Hello there.
I'm running into a problem that I need to run a process befter the shared after hook. I've tried using the after hook with tag and added the tab to the scenarios but the result was the after hook with no tab ran first instead of after hook with tab ran first. 
Is it possible to control which one to run first? 
Thank you.

**Comment by davidjgoss** [comment]
The order that hooks are run in is based purely on the order they were defined in, and tags don't have any bearing on that. If you have one hook running before another, it means it was defined first. If the hooks are in multiple files, the order the files are loaded in will influence it. It's pretty common for people to group all their hooks together in one file to remove ambiguity around ordering.

**Comment by ooo2003003v2** [comment]
I've tried something like this but the result is after print into the console first then createdTestContact comes next. 
Any idea why it happens?

```
@after('@createdTestContact')
public async createdTestContact() {
        console.log('createdTestContact')
}

@after()
public async afterEach() {
        console.log('after')
}
```

**Comment by davidjgoss** [comment]
That doesn’t look like cucumber code eg with decorated class methods - are you using a test framework that wraps cucumber?
