### ISSUE TITLE
Reporters could create sub-directory automatically instead of failing

### ISSUE THREAD

**Issue by x80486** [cucumber/cucumber-js#2159]
### 🤔 What's the problem you're trying to solve?

`Cucumber` is unable to create report(s) if a sub-directory structure is specified and the same it's not present; e.g.: `html:reports/cucumber-report.html` — if `${CWD}/reports/` does not exist, the execution fails.

### ✨ What's your proposed solution?

`Cucumber` should be able to create that path, something similar to `mkdir --parents ./reports/`.

### ⛏ Have you considered any alternatives or workarounds?

Currently I'm using `mkdirp` module to create this path beforehand, but that requires some "orchestration" between `npm` scripts.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
This seems reasonable to me, as long as we're fault-tolerant with it as we could hit e.g. permissions issues from the OS. @charlierudolph any thoughts?

**Comment by michaelm-rsi** [comment]
Looking into this. Having a little trouble tracking down the feature file for this to insert the scenario associated with this issue.

**Comment by michaelm-rsi** [comment]
Also, is it ok to add https://www.npmjs.com/package/mkdirp to the dependencies for this?

**Comment by michaelm-rsi** [comment]
Draft of the scenario - 
```
Scenario: Created relative path
    When I run cucumber-js with `-f summary:some/long/path/for/reports/summary.txt`
    Then the file "some/long/path/for/reports/summary.txt" has the text:
      """
      1 scenario (1 passed)
      1 step (1 passed)
      <duration-stat>
      """
```

That replaces the current invalid path scenario.

Also this to cover reaction to being blocked from creating the directory...

```
  Scenario: No permission to create relative path
    Given the OS does not allow cucumber to create directories
    When I run cucumber-js with `-f summary:some/long/path/for/reports/summary.txt`
```

How should we react to the failure to mkdir?  The consistent with previous versions pattern is to allow the error to stop the test, but we could cache it and issue a warning since an inability to write the summary file is a different issue from whether the tests have failed.

**Comment by davidjgoss** [comment]
> we could cache it and issue a warning since an inability to write the summary file is a different issue from whether the tests have failed

Yeah, I think this is the best approach to ensure backwards compatibility.

**Comment by michael-lloyd-morris** [comment]
Bumping this to note I'm working on this today and hope to have it ready by end of week.
