### ISSUE TITLE
Scenario Outlines with multiple Examples sections only executing the very last Examples

### ISSUE THREAD

**Issue by zsoldosp** [cucumber/cucumber-js#217]
Given the following feature file 

``` gherkin
      Feature: testing scenarios with multiple examples section
        Scenario Outline: outline
          When a table step:
            | first   | second   |
            | <first> | <second> |

        Examples: First set of examples
          | first   | second  |
          | 1       | 2       |

        Examples: Second set of examples
          | first   | second  |
          | 3       | 4       |
          | 5       | 6       |
```

when it's run with cucumber.js 0.4.1, it reports running only two tests (after inspection it's clear it has only run the "Second set of examples")

```
..

2 scenarios (2 passed)
2 steps (2 passed)
```

However, when running the same feature file  with the python [behave](https://pypi.python.org/pypi/behave/1.2.4) tool, it runs all examples - 3 scenarios

```
[...]
1 feature passed, 0 failed, 0 skipped
3 scenarios passed, 0 failed, 0 skipped
3 steps passed, 0 failed, 0 skipped, 0 undefined
```

I don't _know_ which one is the correct behavior. To me the behave version feels correct. But I haven't worked with the ruby based cucumber, so it might be the case that behave is wrong

Due to my lack of ruby experience, I wasn't able to verify this by adding this scenario to the [relevant feature file](https://github.com/cucumber/cucumber-js/blob/master/features/scenario_outlines.feature#L31) and run it locally. But I expect that adding the above example to it is straightforward

**Comment by sarikhapoovaiah** [comment]
what if the test data row and column varies ?

**Comment by mattwynne** [comment]
@sarikhapoovaiah are you looking for help using Cucumber or do you think you've found a bug? If it's help you need, please head over to http://cucumber.io/support and use one of the options there.

If you think you've found a bug, please create a separate issue.

**Comment by sarikhapoovaiah** [comment]
@mattwynne I was looking for help
