### ISSUE TITLE
Unable to generate a junit report by invoking a local formatter

### ISSUE THREAD

**Issue by testgitdl** [cucumber/cucumber-js#2173]
I need to generate also a JUNIT report after running the tests and saw that this is also achievable by calling my customer formatter.
The problem is that the expected JUNIT report is not generated.

This is my cucumber.js:
``
export default {
    import: ['e2e/support/*.ts', 'e2e/features/step_definitions/*.ts'],
    paths: ['e2e/features/*.feature'],
    requireModule: ['ts-node/register', 'tsconfig-paths/register'],
    format: [
        'json:testResults/report_bdd.json',
        'html:testResults/cucumber-html-report-bdd.html',
        './e2e/reporting/reportJUNIT.cjs',
        'summary',
        'progress - bar',
        '@cucumber/pretty-formatter'
    ],
    publishQuiet: true
}``

Content of ./e2e/reporting/reportJUNIT.cjs:
``
const cucumberJunitConvert = require('cucumber-junit-convert');
const options = {
  inputJsonFile: 'testResults/report_bdd.json',
  outputXmlFile: 'testResults/junit_bdd.xml',
  featureNameAsClassName: true // default: false
}
cucumberJunitConvert.convert(options);
``

@davidjgoss any idea how to proceed? Thank you very much!!
Before I was running this reportingJUNIT.cjs script after the tests executed but it is no longer an option and I need JUNIT output

**Comment by davidjgoss** [comment]
When you specify a formatter in the `formats` property there are two parts split by the `:` delimiter. The first part is the name or path of the formatter, which you have. The second part is the file path to be output, which is missing in your example and therefore the formatter would output to the terminal. See https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md

Your script for outputting JUnit XML would also need to be adapted to be a formatter i.e. a class that ingests Cucumber's events and writes to a stream. See https://github.com/cucumber/cucumber-js/blob/main/docs/custom_formatters.md

Given your logic is derived from the [JSON formatter](https://github.com/cucumber/cucumber-js/blob/main/src/formatter/json_formatter.ts) output, you might be able to extend that class to capture its output and do your transformation there.

Finally, it shouldn't be too long until we have a first-party JUnit formatter via #2121, which I'm going to working on shortly.

Hope this helps.

**Comment by testgitdl** [comment]
Thank you @davidjgoss ! I will give it a try. Looking forward to the Junit formatter. In the meantime I also thought about having this in the AfterAll. seems like a simpler solution
