### ISSUE TITLE
Getting error everytime, when i run cucumber nightwatch stepdef .js file

### ISSUE THREAD

**Issue by sriharircb** [cucumber/cucumber-js#2177]
Hi 

i am getting below error everytime if i try to run nightwatch cucumber js file.

Error: 
            You're calling functions (e.g. "Given") on an instance of Cucumber that isn't running.
            This means you have an invalid installation, mostly likely due to:
            - Cucumber being installed globally
            - A project structure where your support code is depending on a different instance of Cucumber
            Either way, you'll need to address this in order for Cucumber to work.
            See https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations
            
             You're calling functions (e.g. "Given") on an instance of Cucumber that isn't running.
             This means you have an invalid installation, mostly likely due to:
             - Cucumber being installed globally
             - A project structure where your support code is depending on a different instance of Cucumber
             Either way, you'll need to address this in order for Cucumber to work.
             See https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations
             
       at Object.<anonymous> (/Users/msh/Desktop/untitled folder/newsample/nightwatch/stepdef/jollyshop.js:4:1)
       at Module._compile (node:internal/modules/cjs/loader:1155:14)
       at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
       at Module.load (node:internal/modules/cjs/loader:1033:32)
       at Function.Module._load (node:internal/modules/cjs/loader:868:12)
       at Module.require (node:internal/modules/cjs/loader:1057:19)
       at require (node:internal/modules/cjs/helpers:103:18)
       
      

 **what i am trying use:** 
i am trying to automate by nightwatch with cucumber. every time i run the command   ex: [ npx nightwatch sample.js ] i am getting above command. i tried to remove node_modules , node js , npm reinstalled newly, and restarted the system , even i am getting same error.

**i tried un installing the the @cucumber/cucumber globally by the below command**
npm uninstall -g @cucumber/cucumber , but that is not working.

if someone resolved this please drop the solution , it helps.  Thank you

**Comment by davidjgoss** [comment]
Did you follow the sections on the linked documentation around e.g. duplicate dependency and deprecated package?

**Comment by sriharircb** [comment]
i followed https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations instructions , 

i hit [npm why @cucumber/cucumber] command , where i see only one version were there  is no other versions.

mac newsample % npm why @cucumber/cucumber
@cucumber/cucumber@8.8.0 dev
node_modules/@cucumber/cucumber
 dev @cucumber/cucumber@"^8.8.0" from the root project

**Comment by sriharircb** [comment]
issue got fixed , i am running in wrong way.

earlier running : npx nightwatch ****.js file

now i setted up one test under script in package.json. then started running npm run test. it works
