### ISSUE TITLE
format option splitter problems

### ISSUE THREAD

**Issue by yusuke-noda** [cucumber/cucumber-js#2178]
### 🤔 What's the problem you're trying to solve?
In version 8, to support file:// URLs, the regular expression splitting the format option changed from <code>/([^A-Z]):(?!\\\\)/</code> to <code>/((?:file){ 0}):(?!\\\\|\\/\\/)/</code>.
As a result, format option is split by ":" that not immediately followed by "\\" or "//"
This change causes the following problems in version 8:

1.  Cannot use Windows absolute path with "/" as the directory separator
Since the format option is split by ":" followed by a single "/", if you specify "C:/foo" in PATH, the actual output path will be "C".
And if you specify "C:/myformatter.js" in TYPE, the formatter name will be "C" and actual output path will be "/myformatter.js", and myformatter.js will be overwritten by empty file.

| format | expected TYPE | expected PATH | actual TYPE | actual PATH |
| ----- | ---- | ---- | ---- | ---- |
| json:C:/foo.json | json | C:/foo.json | json | C | 
| C:/myformatter.js:./foo.log | C:/myformatter.js | ./foo.log | C | /myformatter.js |

2.  Cannot use UNC path as output path
The format option is not split by ":" followed by "\\" or "//", so UNC paths cannot be used in PATH.
Note that in version 7, UNC path with '/' as the directory separator could be used.

| format | expected TYPE | expected PATH | actual TYPE | actual PATH |
| ----- | ---- | ---- | ---- | ---- |
|json:\\\\myhost\\foo\\bar.json | json | \\\\myhost\\foo\\bar.json | json:\\\\myhost\\foo\\bar.json | (empty) | 
| json://myhost/foo/bar.json | json | //myhost/foo/bar.json | json://myhost/foo/bar.json | (empty) |

3. There is no point in enclosing the format option with ""
Enclosing TYPE or PATH with " to avoid splitting the format option at unintended locations has no effect because the format option splitter first removes all " from the format option before splitting.

| format | expected TYPE | expected PATH | actual TYPE | actual PATH |
| ----- | ---- | ---- | ---- | ---- |
| "json":"C:/foo.json" | json | C:/foo.json | json | C | 

### ✨ What's your proposed solution?
I propose to make the option splitter specification as follows.

1. Do not split strings enclosed in ""

| format | TYPE | PATH |
| ----- | ---- | ---- |
| "foo:bar":"baz:qux" | foo:bar | baz:qux |
| "foo:bar":baz:qux | foo:bar | baz:qux |
| foo:bar:"baz:qux" | foo:bar | baz:qux |
| "foo:bar:baz:qux" | foo:bar:baz:qux | (empty) |

2. If the format starts with "file://" or "file:///", split at the second ":"

| format | TYPE | PATH |
| ----- | ---- | ---- |
| file://foo/bar:baz | file://foo/bar | baz |
| file:///foo/bar:baz | file:///foo/bar | baz |
| file://foo/bar | file://foo/bar | (empty) |
| file:///foo/bar | file:///foo/bar | (empty) |

3. If format starts with "file://[a-zA-Z]:/", "file://[a-zA-Z]:\\", "file:///[a-zA-Z]:/" or "file:///[a-zA-Z]:\\", split at the third ``:''

| format | TYPE | PATH |
| ----- | ---- | ---- |
| file://C:/foo/bar:baz | file://C:/foo/bar | baz |
| file://C:\\foo\\bar:baz | file://C:\\foo\\bar | baz |
| file:///C:/foo/bar:baz | file:///C:/foo/bar | baz |
| file:///C:\\foo\\bar:baz | file:///C:\\foo\\bar | baz |
| file://C:/foo/bar | file://C:/foo/bar | (empty) |
| file://C:\\foo\\bar | file://C:\\foo\\bar | (empty) |
| file:///C:/foo/bar | file:///C:/foo/bar | (empty) |
| file:///C:\\foo\\bar | file:///C:\\foo\\bar | (empty) |

4. If the format starts with "[a-zA-Z]:/" or "[a-zA-Z]:\\", split at the second ":"

| format | TYPE | PATH |
| ----- | ---- | ---- |
| C:/foo/bar:baz | C:/foo/bar | baz |
| C:\\foo\\bar:baz | C:\\foo\\bar | baz |
| C:/foo/bar | C:/foo/bar | (empty) |
| C:\\foo\\bar | C:\\foo\\bar | (empty) |

5. Do not split into 3 or more even if there is a ":" after the first split point.
 
| format | TYPE | PATH |
| ----- | ---- | ---- |
| json:C:/foo/bar | json | C:/foo/bar |
| json:C:\\foo\\bar | json | C:\\foo\\bar |

If this suggestion is accepted I will create a pull request.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
For an absolute path, it should work correctly if you include the file:// protocol prefix - this is needed for ES module compatibility now.

**Comment by yusuke-noda** [comment]
> For an absolute path, it should work correctly if you include the file:// protocol prefix - this is needed for ES module compatibility now.

It is true for TYPE, but not for PATH.
The following error happens when the file:// URL is specified in the PATH.
```
C:\work\myproject>npx cucumber-js --format json:file://C:\foo\bar.json
Error: ENOENT: no such file or directory, open 'C:\work\myproject\file:\C:\foo\bar.json'
```
This is because "file://C:\foo\bar.json" is treated as a relative path.
The following command works fine:
```
C:\work\myproject>npx cucumber-js --format json:C:\foo\result.json


0 scenarios
0 steps
0m00.000s (executing steps: 0m00.000s)
```

And also in fact, the following command works fine without specifying a file:// URL in the TYPE.
```
C:\work\myproject>npx cucumber-js --format C:\work\myproject\node_modules\@cucumber\cucumber\lib\formatter\json_formatter.js:.\result.json


0 scenarios
0 steps
0m00.000s (executing steps: 0m00.000s)
```

**Comment by yusuke-noda** [comment]
The thing that bothers me the most is that there is no way to specify a UNC path in PATH.

Also, for the problem that Windows absolute path with "/" as directory separator cannot be specified in PATH, serenity-js specifies Windows absolute path with "/" as directory separator in PATH, so I would like to fix either cucumber-js or serenity-js.

**Comment by davidjgoss** [comment]
Thanks for the extra detail @yusuke-noda  - I'll dig into this and get back to you.

FWIW I think [the change that added stripping the quotes](https://github.com/cucumber/cucumber-js/pull/1847/files) has a similar intent re wrapping one side and/or the other with quotes, it's just a slightly heavy-handed implementation, so we could possibly work with that a bit.
