### ISSUE TITLE
Switch default step snippet to string based non regex matcher

### ISSUE THREAD

**Issue by samccone** [cucumber/cucumber-js#218]
Just a thought :)

**Comment by charlierudolph** [comment]
The string based patterns aren't near as powerful and I believe regexps are the standard in the other cucumber implementations. Maybe a config option that lets you choose your default? This is also quite old, so I'm good with just closing for now and can reopen later if there is renewed interest.

**Comment by aslakhellesoy** [comment]
Please don't add this until we've agreed a common pattern language. See cucumber/cucumber#1

**Comment by jbpros** [comment]
Closing this for now.
