### ISSUE TITLE
ESM Error - support.js

### ISSUE THREAD

**Issue by rtomyj** [cucumber/cucumber-js#2181]
### 👓 What did you see?
```
require() of ES modules is not supported.
require() of **MY TYPESCRIPT DEFINITION FILE**from **path to node_modules**@cucumber/cucumber/lib/api/support.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from **my package.json**
```

### ✅ What did you expect to see?
Cucumber should work with ts feature files

### 📦 Which tool/library version are you using?

cucumber-js version 8.8.0

### 🔬 How could we reproduce it?

**Command used**

export NODE_OPTIONS="--loader ts-node/esm" && env-cmd -e test cucumber-js --config config/cucumber.mjs

**Config File**
```javascript
const config = {
	paths: ['integration-test'],
	requireModule: ['ts-node/register'],
	require: ['integration-test/step-definitions/**/*.ts'],
	import: ['integration-test/step-definitions/**/*.ts'],
	format: ['summary', 'progress-bar', 'html:integration-test-results.html'],
	publishQuiet: true,
}
export default config
```

1. Use above command
2. Use above config file
3. Use ESM with TS

### 📚 Any additional context?

I followed examples and added what is required: config file has module **ts-node**, I import my TS files, I use **NODE_OPTIONS="--loader ts-node/esm"** as was told in docs. It seems like the file **support.js** is the culprit.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
“require” and “requireModule” are not applicable for ESM projects - the former is superseded by “import” and the latter is handled by defining the loader externally as you’ve done.

Drop the “require” and “requireModules” from your config file and you should be set.

**Comment by rtomyj** [comment]
That did it. Thank you!
