### ISSUE TITLE
Help running test programmatically

### ISSUE THREAD

**Issue by mrsenzy** [cucumber/cucumber-js#2194]
Hi - I am using the cucumber api to run the test programmatically and below I use. 

```js
import {loadConfiguration, loadSupport, runCucumber} from "@cucumber/cucumber/api";
var shell = require("shelljs");

export async function runTests() { 
    const {runConfiguration} = await loadConfiguration({
        file: './cucumber.json'
    });
    // load the support code upfront
    const support = await loadSupport(runConfiguration)
    const {success} = await runCucumber({
        ...runConfiguration,
        support
    });
    return success;
}

runTests().then(() => {
    console.log("Test Run Complete");
    shell.exec(`node report.js`);
    process.exit(0);
}).catch((error) => {
    console.error(error);
    process.exit(1);
});
```

I am looking to pass arguments to runTests like browser name and devices to run the test multiple times for cross browser testing like 

```js
const capabilities = [
    {
          "browser": "chrome",
          "os": "osx",
          "os_version": "catalina"
      },
{
          "browser": "edge",
          "os": "Windows",
          "os_version": "Win10"
      }
]

capabilities .forEach( async () => {
    runTests().then(() => {
        console.log("Test Run Complete");
        shell.exec(`node report.js`);
        process.exit(0);
    }).catch((error) => {
        console.error(error);
        process.exit(1);
    });
})
```

any recommendation on how to achieve this better for passing these as args and making it run.

**Comment by davidjgoss** [comment]
Hey @mrsenzy, I would recommend using a combination of profiles and world parameters for this. It's [discussed a bit in this doc](https://github.com/cucumber/cucumber-js/blob/main/docs/profiles.md#using-profiles-for-arguments) but essentially something like this in your config file:

```js
{
  "default": {
    // whatever you have already...
  },
  "chrome-osx {
    "worldParameters": {
      "browser": "chrome",
      "os": "osx",
      "os_version": "catalina"
    }
  },
  "edge-windows": {
    "worldParameters": {
      "browser": "edge",
      "os": "Windows",
      "os_version": "Win10"
    }
  }
}
```

Then change your `runTests` function to something like:

```js
export async function runTests(profile) { 
    const {runConfiguration} = await loadConfiguration({
        file: './cucumber.json',
        profiles: [profile]
    });
```

Finally:

```js
['chrome-osx', 'edge-windows'].forEach( async (profile) => {
    runTests(profile).then(() => {
```

Hope this helps.

**Comment by mrsenzy** [comment]
Thank you very much David. This approach worked for me to run cross browser testing from world parameters and profile. But some how my code runs the scenario for one profile only. It doesn't run the second profile. Below is the updated code,

import {loadConfiguration, loadSupport, runCucumber} from "@cucumber/cucumber/api";
var shell = require("shelljs");

export async function runTests(profile) { 
    const {runConfiguration} = await loadConfiguration({
        file: './cucumber.json',
        profiles: [profile]
    });
    const {success} = await runCucumber({...runConfiguration});
    return success;
}

const runProfiles = ['chrome_osx', 'edge_windows']

runProfiles.forEach(async (profile) => {
    await runTests(profile)
})

cucumber.js (I removed cucumber.json because for cucumber.json for each profile I have to copy the default code + world params, cucumber.js was simpler to use)

let common = [
    './tests-examples/features/*.feature',
    '--require-module ts-node/register',
    '--require ./tests-examples/stepDefinitions/**/*.ts',
    '--require ./cucumber.config.ts',
    '--format html:./report/cucumberjs-report.html',
    '--format progress-bar',
    '--format ./node_modules/@cucumber/pretty-formatter',
    '--format json:./report/report.json',
    '--publish-quiet'
].join(' ');

module.exports = {
  default       : common + ' ' + `--world-parameters '{"driverName": "Buster"}'`,
  tagged        : common + ' --tags @data-modeling ',
  wParams       : common + ' --tags @wParams ' + `--world-parameters '{"driverName": "Buster"}'`,
  chrome_osx    : common + ' --tags @wParams ' + `--world-parameters '{"driverName": "Buster","browser": "chrome","os": "osx","os_version": "catalina"}'`,
  edge_windows  : common + ' --tags @wParams ' + `--world-parameters '{"driverName": "Buster","browser": "edge","os": "Windows","os_version": "Win10"}'`,
};

**Comment by mrsenzy** [comment]
I am now able to run both scenarios but first run for the scanerio return result as undefined steps and second run for same scenario on other browser runs successfully. 

I use below config only - but not aware why first run is unidentified and second run is successful for same scenario. any help on this.

```
let common = [
    './tests-examples/features/*.feature',
    '--require-module ts-node/register',
    '--require ./tests-examples/stepDefinitions/**/*.ts',
    '--require ./cucumber.config.ts',
    //'--format html:./report/cucumberjs-report.html',
    '--format progress-bar',
    '--format ./node_modules/@cucumber/pretty-formatter',
    '--format json:./report/report.json',
    '--publish-quiet',
    '--parallel 2'
].join(' ');

module.exports = {
  default       : common + ' ' + `--world-parameters '{"driverName": "Buster"}'`,
  tagged        : common + ' --tags @data-modeling ',
  wParams       : common + ' --tags @wParams ' + `--world-parameters '{"driverName": "Buster"}'`,
  chrome_osx    : common + ' --tags @wParams ' + `--world-parameters '{"driverName": "Buster","browser": "chrome","os": "osx","os_version": "catalina"}'`,
  edge_windows  : common + ' --tags @wParams ' + `--world-parameters '{"driverName": "Buster","browser": "edge","os": "osx","os_version": "catalina"}'`,
};
```
