### ISSUE TITLE
Crash when using parallel

### ISSUE THREAD

**Issue by mcheung-hbo** [cucumber/cucumber-js#2196]
Thanks for the awesome framework! 

I am trying to understand a crash that I see when I try to organize my `feature file` and `step definition` script into 2 separated folders and make use of `parallel`; this is my folder structures:
```
- index.js
- features
   - test.feature
- stepDefinition
   - step.js
```
and this is my code:
```javascript
// index.js

const {
  runCucumber,
  loadConfiguration,
  loadSupport,
} = require('@cucumber/cucumber/api');
  const { runConfiguration } = await loadConfiguration({
    provided: {
      paths: ['features'],
      require: ['stepDefinition'],
      parallel: 0,
      format: ['@cucumber/pretty-formatter']
    },
  });
  let support = await loadSupport(runConfiguration);
  const { success } = await runCucumber({ ...runConfiguration, support });
```
The above code runs fine but I hit a cucumber-js crash when I set parallel to be > 0:
```
1) Scenario: MyTest # features/test.feature:5
   ✖ Given a given function # stepDefinition/step.js:3
       TypeError: Cannot read properties of undefined (reading 'getInvocationParameters')
           at Object.run (cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/step_runner.js:40:47)
           at TestCaseRunner.invokeStep (cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/test_case_runner.js:94:44)
           at TestCaseRunner.runStep (cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/test_case_runner.js:243:37)
           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
           at async cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/test_case_runner.js:174:44
           at async TestCaseRunner.aroundTestStep /cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/test_case_runner.js:119:32)
           at async TestCaseRunner.runAttempt (/cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/test_case_runner.js:157:13)
           at async TestCaseRunner.run (/cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/test_case_runner.js:135:35)
           at async Worker.runTestCase (/cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/parallel/worker.js:79:9)
           at async Worker.receiveMessage (/cucumber-js-issue/node_modules/@cucumber/cucumber/lib/runtime/parallel/worker.js:60:13)
   - Then a then function # stepDefinition/step.js:4
```
I looked at the codes and it looks to be a script loading issue in the worker process (that comes in to the picture when parallel thread is used); so I hacked and had the follow workaround and with that I no longer saw the said crashes:
```
  let support = await loadSupport(runConfiguration);

  // add the support script to the support structure
  support.originalCoordinates.requirePaths.push(join(process.cwd(), 'stepDefinition', 'step.js'));

  const { success } = await runCucumber({ ...runConfiguration, support });
```
I thus have the questions:
1. is the crash due to incorrect configuration (feature files and support script folders are in 2 different folders)? 
2. is the crash a bug assuming above question 1 is a support config?

I made a sample repo that captured the issue: https://github.com/mcheung-hbo/cucumber-js-parallel-issue

Thank you!
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mrsenzy** [comment]
Hi @mcheung-hbo -

This issue is happening of a issue in cucumber-js itself, the support run configuration for modules, path are not getting loaded during parallel run, hence its crashing. workaround is add below lines after load Support, before calling runcucumber 

```
    support.originalCoordinates.requireModules = runConfiguration.support.requireModules;
    support.originalCoordinates.requirePaths = runConfiguration.support.requirePaths;
    support.originalCoordinates.importPaths = runConfiguration.support.importPaths;
```

**Comment by mcheung-hbo** [comment]
@mrsenzy, thx for commenting, and much appreciated! That's essentially what my workaround does as well to the require file.

Is this issue being tracked somewhere? This workaround just looks hack-y (messing around with cucumber-js internal structures that i guess is subjected to change?) and it will be ideal to address this issue in cucumber-js itself.

**Comment by mrsenzy** [comment]
yes it must be fixed in cucumber-js itself. I have raised this issue few days back and one of my colleague helped to fix this workaround. will do a PR for this to author (@davidjgoss )

**Comment by davidjgoss** [comment]
Thanks @mcheung-hbo and @mrsenzy for finding the source of this issue. I've raised a PR which fixes the issue in the right place internally and will get a patch release out soon.

**Comment by mcheung-hbo** [comment]
Awesome! Thanks for the quick turn around fix @davidjgoss! much appreciate for the quick support here!

**Comment by mcheung-hbo** [comment]
@davidjgoss I see that the fix for this issue is merged; i am just curious about the next release of `cucmber-js` (which ships this fix); what is the typical release cadence for the project? Thank you!

**Comment by davidjgoss** [comment]
Now released in https://github.com/cucumber/cucumber-js/releases/tag/v8.9.1
