### ISSUE TITLE
Target specific feature elements

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#22]
Only execute parts of a feature.

- FILE:LINE syntax
- --name
- --lines

Some existing step definitions depend on this (e.g. `When(/^Cucumber executes the scenario "([^"]*)"$/, ...);`). Update them as soon as this is finished.

**Comment by charlierudolph** [comment]
@jbpros whats left here `FILE:LINE` is already supported. Is `--name` and `--not-name` the things that are wanted out of this?

**Comment by jbpros** [comment]
@charlierudolph yep.

**Comment by jbpros** [comment]
We're also missing the multiple line numbers (used by rerun, among other things):

`features/hello_world.feature:21:34:46:88`

**Comment by charlierudolph** [comment]
cucumber-ruby has
```
-n, --name NAME
              
Only execute the feature elements which match part of the given name.
If this option is given more than once, it will match against all the
given names.
```

I don't think we need `--no-name` as least to start.

**Comment by jbpros** [comment]
Nah, don't bother with `--no-name`.
