### ISSUE TITLE
Implement please BeforeFeature and AfterFeature hooks

### ISSUE THREAD

**Issue by apetrenko-planeks** [cucumber/cucumber-js#2205]
### 🤔 What's the problem you're trying to solve?

Can not execute code before feature and after feature.

### ✨ What's your proposed solution?

Create BeforeFeature and AfterFeature hooks. It will allow to execute code which is required only before and after feature conditions.

### ⛏ Have you considered any alternatives or workarounds?

Nope

### 📚 Any additional context?

In my case I can not integrate with reportportal.io to create executions for feature reporting where should be reported scenarios.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mattwynne** [comment]
Can you say more about why you need this feature in order to be able to integrate with reportportal.io?

**Comment by davidjgoss** [comment]
Added a FAQ for this to explain it a bit:
https://github.com/cucumber/cucumber-js/blob/main/docs/faq.md#why-arent-there-beforefeature-and-afterfeature-hooks

But yeah, I'm also interested in what the particular issue is for reportportal.io
