### ISSUE TITLE
Cucumber tests for cucumber-js include a number of undefined steps

### ISSUE THREAD

**Issue by simondean** [cucumber/cucumber-js#221]
Hi.  cucumber-js uses Ruby Cucumber and cucumber-js to test itself.  The output from these two test runs include a number of undefined scenarios.  It's not possible to know if these undefined scenarios are masking regressions.  It would be good to use the --strict option with Ruby cucumber and cucumber-js when cucumber-js tests itself.  

Ruby Cucumber is executed from the Rakefile

``` ruby
  desc "Run the features through Cucumber (Ruby) and Aruba"
  task :rb do
    sh %{ cucumber -p quiet }
  end
```   

cucumber-js is executed from the package.json

``` json
  "scripts": {
    "test": "./bin/cucumber.js && jasmine-node spec"
  },
```

**Comment by charlierudolph** [comment]
Fixed in 8daf95b65557b85e74c4fa878cc8a6322b9855ca
