### ISSUE TITLE
How can I use playwright reporter in cucumber js

### ISSUE THREAD

**Issue by bodycombathuang** [cucumber/cucumber-js#2221]
How can I use playwright reporter in cucumber js
cucumber.js report does not contain the info for each line of code, but playwright report has

**Comment by davidjgoss** [comment]
> How can I use playwright reporter in cucumber js

You can't; Playwright Test is a different test runner to Cucumber.

> cucumber.js report does not contain the info for each line of code, but playwright report has

Could you elaborate a little on the functionality you'd like to get from the Cucumber report?

**Comment by bodycombathuang** [comment]
here is the report generated by playwright test runner, it shows whether each expression of code is executed successfully or not  (locator.click(internal:role=link[name="Get started"i]),  expect.toHaveTitle...)
[
![playwright](https://user-images.githubusercontent.com/20555274/213059220-df582f9e-6f07-4fd1-a15e-208e7e12067f.JPG)
](url)
here is the html report generated by cucumber js test runner, it only ontains words from feature file and exceptions in case of  error,   is it possible cucumber js report can show whether each expression of code is executed successfully or not

![cucumberreport](https://user-images.githubusercontent.com/20555274/213059483-cefb651e-776d-4e76-9118-1726f22ea258.JPG)

**Comment by HanLiu1976** [comment]
This is the one I also concern. For how the error indicator detail as playwright by cucumber report. any suggestions?

**Comment by davidjgoss** [comment]
Cucumber isn't going to do something that's specific to Playwright itself. But if you can get the information you want out of Playwright there are maybe things you can try:

- `this.log` from within a step will emit a plain text attachment that shows up in the report. Is there some logging from Playwright you could hook into and send to this?
- `setDefinitionFunctionWrapper` could be used to wrap the step and do something with the exception before it bubbles up to Cucumber. Maybe there's some detail you can pull out of there and log?

**Comment by bodycombathuang** [comment]
@davidjgoss thanks for your help. I have more question
which apis/method can return expressions (like page.goto ,expect.toHaveTitle expressions in the above picture), that each test run has called and return whether each expression succeeds or fails

**Comment by davidjgoss** [comment]
I don't know @bodycombathuang, you'd need to consult **Playwright's docs** for that, it's not in scope of Cucumber's support.

**Comment by davidjgoss** [comment]
Going to close this one because the unknowns are about Playwright not Cucumber.
