### ISSUE TITLE
Scenario Outline json output no longer indicates which example

### ISSUE THREAD

**Issue by kbfirebreather** [cucumber/cucumber-js#2223]
### 👓 What did you see?

I am upgrading from version 6 to version 8, and noticed that the json output for `Scenario Outline` based tests is different. The `line` property in the elements array, used to coincide with the line that each scenario outline example was on, but now it seems to always reference the line that the `Scenario Outline` is defined. There doesn't seem to be a unique identifier for elements that are part of a scenario outline anymore. 

### ✅ What did you expect to see?

`line` property to reference the line for each example in a scenario outline, or some other unique identifier in the elements array to indicate which example the scenario outline entry pertained to.

### 📦 Which tool/library version are you using?

Cucumber-js 8.10.0. 

### 🔬 How could we reproduce it?

Run a `Scenario Outline` on 6.0.5 with a flag to set the output to a json file, e.g., `-f json:/path/to/output.json`
Run the same `Scenario Outline` on 8.10.0 with the flag to set the output to a json file.

Notice the differences in the elements array between the two in regards to the `line` property. 

Example output from 6.0.5:

![image](https://user-images.githubusercontent.com/3360138/213456646-219c9b8e-a005-4431-b094-fe1ea1d8fccc.png)

Example output from 8.10.0:

![image](https://user-images.githubusercontent.com/3360138/213456675-c6de0565-1171-4feb-a1f4-bf9a166bd3a9.png)

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
Thanks for the detailed report @kbfirebreather! I'll take a proper look at this soon.

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v8.11.1
