### ISSUE TITLE
false negative return for broken feature file

### ISSUE THREAD

**Issue by triesztui** [cucumber/cucumber-js#2225]
### 👓 What did you see?

test executions returned 0 (left pipeline green) even though no test ran at all due to one broken feature file

### ✅ What did you expect to see?

cucumber-js should return nonzero in case of feature file parsing errors

### 📦 Which tool/library version are you using?

$ node -v
v19.4.0
$ npm -v
9.2.0
$ node_modules/\@cucumber/cucumber/bin/cucumber-js -v
This Node.js version (v19.4.0) has not been tested with this version of Cucumber; it should work normally, but please raise an issue if you see anything unexpected.
8.10.0

### 🔬 How could we reproduce it?

Steps:

1) put some >>>>> signs into a feature file

2) 
$ node_modules/\@cucumber/cucumber/bin/cucumber-js
This Node.js version (v19.4.0) has not been tested with this version of Cucumber; it should work normally, but please raise an issue if you see anything unexpected.
Parse error in "features/xxxxxx.feature" (4:5): expected: #TagLine, #RuleLine, #Comment, #Empty, got '>>>>>>>> Scenario Outline: xxxxxxx'
...

3) 
$ echo $?
0

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v8.11.1

**Comment by triesztui** [comment]
yes I do  use the html formatter. Thank you very much for looking into this David.

**Comment by triesztui** [comment]
fix works well, thank you.
