### ISSUE TITLE
Running cucumber-js programmatically using TS-Node 

### ISSUE THREAD

**Issue by abdulkalam1233** [cucumber/cucumber-js#2249]
# cucumber.js
`const common = {
  paths: ['test/automation/features/**/*.feature'],
  requireModule: ['ts-node/register', 'tsconfig-paths/register'],
  require: ['test/automation/step-definitions/**/*.ts'],
  format: [' progress-bar', '@cucumber/pretty-formatter'],
};

module.exports = {
  default: {
    ...common,
    format: ['progress-bar', 'html:test-results/cucumber-report.html'],
  },
  ci: {
    ...common,
    format: ['html:test-results/cucumber-report.html'],
    publish: true,
  },
};
`
# cucumber-runner.ts
`import {
  loadConfiguration,
  runCucumber,
  loadSupport,
} from '@cucumber/cucumber/api';

 (async () => {
  if (!existsSync('test-results')) {
    mkdirSync('test-results');
  }
  const { runConfiguration } = await loadConfiguration();
  const support = await loadSupport(runConfiguration);
  await runCucumber({ ...runConfiguration, support });
})();`

# script: ts-node cucumber-runner.ts

Getting failed to compile typescript error.

![Error](https://user-images.githubusercontent.com/39231568/221497465-a08c4c73-1b91-432e-8c47-f7b367917a55.png)

**Comment by davidjgoss** [comment]
It looks like you have some compilation errors in your step definition code. This is on you to fix, but if you post some code there might be something obvious to point out here.

**Comment by davidjgoss** [comment]
So again you seem to have some type errors. If you try to compile your step definition files with `tsc` do you get the same result?

Also out of interest, why are you using the API? It seems your usage is quite standard so you could just use the CLI instead of having your own script.

**Comment by michael-lloyd-morris** [comment]
I made a blog entry on my adventures in getting this to work here.

https://mmorris-sandbox.net/demos/cucumber-next

Subsequent to that I added some changes to the Cucumber documentation in PR #2244
 which has been approved and should be merged soon. Read over the files and if you're still having trouble direct message me on this, I'll be happy to help.
