### ISSUE TITLE
Cucumber fails with Yarn Berry on ESM only repos

### ISSUE THREAD

**Issue by halvardssm** [cucumber/cucumber-js#2252]
### 👓 What did you see?

When running cucumber in an Yarn Berry + ESM repo, it is failing with the following error:

```
(node:27346) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/project/home/halvardssm/workspace/.yarn/releases/yarn-3.4.1.cjs:24432
export {};
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Module.m._compile (/project/home/halvardssm/workspace/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/project/home/halvardssm/workspace/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

I am assuming this is due to cucumber not being fully ESM compatible, and therefore it fails. My suggestion would be to clearly separate ESM and CJS logic, and to also include an esm runner of the script (to be able to run it like `yarn cucumber-js-es ...`).

See [my branch](https://github.com/halvardssm/cucumber-js/pull/1/files) for an initiated change in how the package could be written and set up (although I haven't fully tested it yet).

### ✅ What did you expect to see?

I expected that cucumber would have the correct mapping of cjs and mjs, and successfully be able to run the test in a ESM only project.

### 📦 Which tool/library version are you using?

Node v16.18.1
Yarn v3.4.1

```
    "@cucumber/cucumber": "9.0.0",
    "typescript": "4.9.3",
    "vite": "4.1.1",
    "vitest": "0.29.2"
```

### 🔬 How could we reproduce it?

1. Setup a new Yarn Berry repo
2. Add Vite + TS + Cucumber
3. Add minimal Cucumber setup
4. run test

Here is a codesandbox where the issue is happening: [link](https://codesandbox.io/p/sandbox/exciting-golick-pzpe22). Simply open the terminal and do `yarn test`

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
What version of Node.js are you using?

**Comment by halvardssm** [comment]
Node v16.18.1

**Comment by Izhaki** [comment]
The stack trace doesn't even hit `cucumber`: You use `ts-node/esm` as the node loader, and soon as it gets to `yarn` it complains.

Your reproduction works if you change the test script to:

```
    "test": "NODE_OPTIONS=\"--loader ts-node/esm\" node_modules/.bin/cucumber-js --config test/cucumber.config.mjs"
```

**Comment by Izhaki** [comment]
@halvardssm [your branch](https://github.com/halvardssm/cucumber-js/pull/1/files) could actually be of _huge_ value.

Questions:

- Does my proposed change works (by passing yarn)?
- Did your branch helped?

Basically, I suspect cucumber toggles back to `cjs` which then breaks pure `esm` imports (that's where your branch can help), but your branch and my solution seem to be unrelated.

**Comment by davidjgoss** [comment]
Yeah, just removing `yarn` from that npm script value worked for me, although curiously it worked with that still in too although I could see the extra process being created. I think this may have been more to do with Yarn's interplay with ESM loaders, and some recent changes in Node.js may have fixed it for 16.19+ and 19+.

**Comment by halvardssm** [comment]
@Izhaki Answers:

> Does my proposed change work (bypassing yarn)?

The proposed change did actually work! Thanks for that! I would also recommend adding this to the docs, but with the node executable to the command:

```
node --loader ts-node/esm node_modules/.bin/cucumber-js --config test/cucumber.config.mjs
```

> Did your branch helped?

I didn't fully finish the branch as all the cjs code would need to be refactored away, but I would suspect this to solve it as I did something similar for an internal package at work. I would try my branch, and expand upon it by making it fully TS (no rouge cjs files to be manually copied), and then compile it to the two formats for publishing (CJS and ESM).

**Comment by halvardssm** [comment]
@Izhaki Small update: It does not work once you import anything in the step files (see [updated codesandbox](https://codesandbox.io/p/github/halvardssm/cucumber-test/main))

```
(node:10466) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Cannot find module '/project/home/halvardssm/workspace/test/veriables' imported from /project/home/halvardssm/workspace/test/steps/hello.ts
    at finalizeResolution (/project/home/halvardssm/workspace/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/project/home/halvardssm/workspace/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/project/home/halvardssm/workspace/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /project/home/halvardssm/workspace/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/project/home/halvardssm/workspace/node_modules/ts-node/src/esm.ts:168:34)
    at /project/home/halvardssm/workspace/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/project/home/halvardssm/workspace/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/project/home/halvardssm/workspace/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
```
