### ISSUE TITLE
rerun with parallel flag is running the tests multiple times

### ISSUE THREAD

**Issue by gmkumar08** [cucumber/cucumber-js#2255]
### 👓 What did you see?

I'm using the Rerun feature as specified [here](https://github.com/cucumber/cucumber-js/blob/HEAD/docs/rerun.md) I have a @rerun.txt file with a bunch of failures spanning multiple feature files. I'm trying to run this @rerun.txt file by passing "--parallel 4" but upon looking at the logs, I see that the tests are running multiple times.

### ✅ What did you expect to see?

Tests shouldn't run multiple times and instead each only run once.

### 📦 Which tool/library version are you using?

Cucumber - 6.0.7

### 🔬 How could we reproduce it?

Run a @rerun.txt file by passing '--parallel 4'
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
Could you say a little more about your setup? What's the content of your rerun file look like?

Also, I noticed this is quite an old version of cucumber-js. Could you try again with the latest (9.0.0)?
