### ISSUE TITLE
We should be able to manage Playwright's timeout properties.

### ISSUE THREAD

**Issue by curaserkan** [cucumber/cucumber-js#2256]
### 🤔 What's the problem you're trying to solve?

There are many different timeout uses that Playwright allows, especially separate timeout times for action, expect and navigation. It would be nice if we could set this possibility via cucumber-js.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by Izhaki** [comment]
Cucumber is completely decoupled from any browser driver.

You can set timeouts for each Cucumber step definition, to match the settings in Playwright.

To learn more on how configure Playwright timeouts: https://stackoverflow.com/a/69105810/1179377
