### ISSUE TITLE
Allow customization option for junit formatter

### ISSUE THREAD

**Issue by Tallyb** [cucumber/cucumber-js#2265]
### 🤔 What's the problem you're trying to solve?

currently all reports generated with cucumberjs junit formatter bear the name 'cucumber-js'. It would be great to be able to customize it via format options and cli param

### ✨ What's your proposed solution?
format option with test suite name. 

### ⛏ Have you considered any alternatives or workarounds?
open for suggestions...

### 📚 Any additional context?
On a side note, it is not really clear how to configure options in a cucumber.mjs file when there are multiple formtters defined. 
```
format: [
  'json:e2e/reports/cucumber-report.json',
  'junit:e2e/reports/cucumber-report.xml',
  'summary'
];

Adding options to the json formatter and to the junit in a single formatOptions: {} entry is cumbersome. Probably best to make each formatter an object. 

format: [
  {type: json, output: 'json:e2e/reports/cucumber-report.json', options: {x: 1, y: false}},
  { type: 'junit', output:  'e2e/reports/cucumber-report.xml', options: {x: 1, z: true}},
  'summary'
];

**Comment by davidjgoss** [comment]
> Adding options to the json formatter and to the junit in a single formatOptions: {} entry is cumbersome

I tend to agree, and I like your suggestion, though that would potentially end up being a significant change so let's make another issue for that.

**Comment by davidjgoss** [comment]
The line in question is here https://github.com/cucumber/cucumber-js/blob/main/src/formatter/junit_formatter.ts#L245. The `options` being passed into the constructor has a `parsedArgvOptions` prop which should be the format options from the user.

**Comment by Sam-ScottLogic** [comment]
May I work on this? This is my first time contributing so may have a few questions along the way!

**Comment by davidjgoss** [comment]
Sure @Sam-ScottLogic, go for it! Feel free to ask questions here, or join #committers-js in the Slack https://cucumber.io/docs/community/get-in-touch/

**Comment by astocker-scottlogic** [comment]
@Sam-ScottLogic  Hi am I okay to take a look into this?

**Comment by Sam-ScottLogic** [comment]
@astocker-scottlogic Yes!
