### ISSUE TITLE
Support for pdf attachments

### ISSUE THREAD

**Issue by maxjoehnk** [cucumber/cucumber-js#2277]
### 🤔 What's the problem you're trying to solve?

The test suite we've built is capable of downloading a pdf and checking for certain texts.
When the pdf generation or a step has failed though we don't really have an idea what might be the issue.

With the usual steps we can just check the attached screenshots but as the pdf is never rendered we can't create a screenshot of it. Instead of rendering the pdf (right now we're just parsing it with pdfjs) I would like to attach the pdf to the report so I can download it and check for any issues after the run has finished.

### ✨ What's your proposed solution?

Allow PDFs as an attachment media type. Don't display it in the html report but offer a way to download the file (probably just a link to the base64 encoded buffer).

### ⛏ Have you considered any alternatives or workarounds?

I could try to render the pdf and attach each page as a single image.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
Thanks for raising @maxjoehnk.

Attaching the PDF to the test run will itself work okay:

```js
await this.attach(buffer, 'application/pdf');
```

But this won't be rendered usably in our HTML report at the moment as you've hinted at. This is covered in https://github.com/cucumber/react-components/issues/80, so going to close this and continue tracking that issue (which overs all language implementations).

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v9.3.0

- You can now download PDF attachments from the HTML report as a file
- You can also optionally specify a filename when you attach
