### ISSUE TITLE
CVE because of dependency on yaml@2.2.1

### ISSUE THREAD

**Issue by aukevanleeuwen** [cucumber/cucumber-js#2280]
### 🤔 What's the problem you've observed?

I was alerted by dependabot of a vulnerability because of a transitive dependency on `yaml@2.2.1` (via `@cucumber/cucumber-js`).

### ✨ Do you have a proposal for making it better?

Update to `yaml@2.2.2`.

**Comment by bchew** [comment]
@davidjgoss is there a plan for a release to npm with this fix soon? Thanks

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v9.1.1 - sorry for the delay.
