### ISSUE TITLE
The type `ISupportCodeLibrary` is not exported, but should be.

### ISSUE THREAD

**Issue by nicojs** [cucumber/cucumber-js#2283]
### 👓 What did you see?

Importing `ISupportCodeLibrary` is not exported from `'@cucumber/cucumber/api'`

```ts
 // 💥 error
import type { ISupportCodeLibrary } from '@cucumber/cucumber/api';
```

### ✅ What did you expect to see?

I would export it to be exported, since it's siblings are also exported:

```ts
 // ✅ 
import type { ISupportCodeCoordinatesOrLibrary, ISourcesCoordinates } from '@cucumber/cucumber/api';
```

### 📚 Any additional context?

Current workaround I'm using:

```ts
type ISupportCodeLibrary = Exclude<
  ISupportCodeCoordinatesOrLibrary,
  ISourcesCoordinates
>;
```

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v9.1.2
