### ISSUE TITLE
Example showing how to test a web application

### ISSUE THREAD

**Issue by mikeymckay** [cucumber/cucumber-js#23]
I would like to be able to do something like this:

node cucumber.js features

This will load a web page and all the javascript that it depends on (defined in support/env.js?).

It will then execute all of the features against that loaded web page.

This is the sort of workflow I expected to be able to accomplish with node, but I can't see how to do it.

Any help?

Mike

**Comment by Vaishnavi-R** [comment]
@jbpros
Hello! I am doing an End-to-End API testing for my application with Electron. 
In one of the scenarios, I need to check the API which is called by front-end react button. Is there any way to check the click event in Cucumber? Appreciate any help. Thanks!

**Comment by charlierudolph** [comment]
There is nothing built into cucumber specifically to do that. Cucumber connects the gherkin in the feature files to JavaScript functions and outputs the results. Writing the functions that clicks and the function that verifies the API was called is up to you. There are plenty of other libraries out there that should be able to help.

From a testing standpoint, it might make sense to have your tests hit a local deployment or a mock version of your API. After you click the proper button, you can check that the API method was called (if using a mock) or the effect of calling the API method (if using a local deployment)

**Comment by Vaishnavi-R** [comment]
Thanks much @charlierudolph !
