### ISSUE TITLE
Add application/zip support

### ISSUE THREAD

**Issue by topolanekmartin** [cucumber/cucumber-js#2302]
### 🤔 What's the problem you're trying to solve?

I want to attach zip file to test results. In case my test case fails I want to see whole trace generated by `playwright`.

### ✨ What's your proposed solution?

Add support for `application/zip` in `attach` method.

### ⛏ Have you considered any alternatives or workarounds?

There is not workaround.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
You can specify any media type for the attach function. Is your issue more about the support in reports?

**Comment by davidjgoss** [comment]
It's worth noting that we [recently](https://github.com/cucumber/cucumber-js/releases/tag/v9.3.0) released support for downloading attachments from the HTML report - previously anything that wasn't text or an image would be inaccessible.
