### ISSUE TITLE
Failing tests exiting with code 0

### ISSUE THREAD

**Issue by joshtombs** [cucumber/cucumber-js#231]
![screen shot 2014-08-21 at 2 11 22 pm](https://cloud.githubusercontent.com/assets/7631670/4000926/a58ab28c-295e-11e4-94ce-c77022f8fcfb.png)

When running tests on Travis CI, failing tests are exiting with code 0.

Also, when I try to log before `process.exit` the logs are not being included. Not sure if this issue is related to #120 or if it is some kind of bug in my tests but that's certainly not normal

**Comment by yangit** [comment]
When I run `npm run cucumber.js` and I have some tests failing cucumber still exits with code 0.
Any setting to twak, or I might be using it wrong?
My version is 0.5.1
