### ISSUE TITLE
Can we have attachment class properties accessible from ITestStepHookParameter

### ISSUE THREAD

**Issue by mrsenzy** [cucumber/cucumber-js#2320]
### 🤔 What's the problem you're trying to solve?

I am building a custom real time report by capturing all events occuring at after step and after scenario hooks. I captured all information except the step log which user adds for each step definition for e.g this.attach("I am logged). I am unable to capture these details at after hooks 

### ✨ What's your proposed solution?

Can we add Attachment class properties to be accessible from ITestStepHookParameter interface

### ⛏ Have you considered any alternatives or workarounds?

Currently team is using third party reporting tools like cucumber-html-reporter but we are trying to minimize the third party dependency and have in house reporting tool enabled for maintenance and custom enhancements on organization needs. 

### 📚 Any additional context?

![image](https://github.com/cucumber/cucumber-js/assets/75691269/535bab85-e33d-455b-93e5-ddfa4120ad6e)
![image](https://github.com/cucumber/cucumber-js/assets/75691269/4cc77bbc-4050-4050-b999-e622e5a20c85)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by davidjgoss** [comment]
The way to access things like attachments, especially for a reporting use case, is to [write a formatter](https://github.com/cucumber/cucumber-js/blob/main/docs/custom_formatters.md).

That said, if you really want to get at attachments in an `After` hook, consider [implementing a custom world class](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/world.md) where you can provide your own `attach` method that wraps the normal one and adds to an array that you can access from the hook later.
