### ISSUE TITLE
Publish plugin's stream - not ended within runCucumber lifecycle

### ISSUE THREAD

**Issue by tamil777selvan** [cucumber/cucumber-js#2321]
### 👓 What did you see?

[Publish plugin](https://github.com/cucumber/cucumber-js/blob/main/src/publish/index.ts) stream is not ended within `runCucumber` lifecycle.

### ✅ What did you expect to see?

Before `runCucumber` lifecycle ends, plugin stream should end by uploading the results.

### 📦 Which tool/library version are you using?

`Cucumber JS` - v9.4.0

### 🔬 How could we reproduce it?

1. Console the status of [`runCucumber`](https://github.com/cucumber/cucumber-js/blob/85b1e5ed13d73d037d39641399f3fdff66faa023/src/cli/index.ts#L79)
2. Add a console above [`this.sendHttpRequest`](https://github.com/cucumber/cucumber-js/blob/85b1e5ed13d73d037d39641399f3fdff66faa023/src/publish/http_stream.ts#L53)
3. Run `npx cucumber-js --publish`

![Screenshot 2023-09-03 at 10 58 31 AM](https://github.com/cucumber/cucumber-js/assets/49207189/fc460e4e-02c8-4521-805d-e7684f741594)

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
Thanks @tamil777selvan, good catch. I can see the issue and will do something for this now.

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v9.5.0
