### ISSUE TITLE
OptionSplitter - Doesn't work as expected on windows OS

### ISSUE THREAD

**Issue by tamil777selvan** [cucumber/cucumber-js#2326]
### 👓 What did you see?

[OptionSplitter](https://github.com/cucumber/cucumber-js/blob/main/src/configuration/option_splitter.ts) is not working as expected in windows os.

### ✅ What did you expect to see?

When providing 'file:///c:/reporter.js' as input to the 'format' function, it splits the path into ['file:///c', '/reporter.js'], resulting in an error.

### 📦 Which tool/library version are you using?

- `Cucumber JS` - 9.5.1

### 🔬 How could we reproduce it?

Run cucumber JS by providing the custom formatter path created by the `pathToFileURL` method.

### 📚 Any additional context?

This is related to https://github.com/webdriverio/webdriverio/pull/11010#discussion_r1316999608

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
Hey @tamil777selvan. There is a change in the works to improve the parsing here.

But also, you should be able to wrap the value in an array and Cucumber will not attempt to split it. So like:

```js
format: [ [ 'file:///c:/reporter.js' ] ] 
```

**Comment by tamil777selvan** [comment]
Thank you, @davidjgoss. The solution provided above solved the issue. I will close this now.
