### ISSUE TITLE
cucumber-js reporting service with cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by s1mrankaur** [cucumber/cucumber-js#2328]
### 👓 What did you see?

 **cucumber-js publish

Cucumber report being published with 0 scenarios**

```
0 scenarios
0 steps
0m00.001s (executing steps: 0m00.000s) 
```

### ✅ What did you expect to see?

We are using Cypress with Cucumber and have following configuration:

 ```
 "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/e2e/",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  
```

There are JSON files in cypress/cucumber-json and I expected a report with the correct stats to be published on running 
cucumber-js publish

### 📦 Which tool/library version are you using?

"cypress": "12.12.0",
"cypress-cucumber-preprocessor": "^4.3.1",

### 📚 Any additional context?

My understanding was that cucumber-js will just publish the report based on JSON outputs. What additional steps may be needed to get this working?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/1100#issuecomment-1732050611

**Comment by davidjgoss** [comment]
As @badeball hinted in the other issue, the cucumber-js option is `--publish`, and positional arguments refer to features.
