### ISSUE TITLE
New custom type is not registered

### ISSUE THREAD

**Issue by jkalandarov** [cucumber/cucumber-js#2332]
### 👓 What did you see?
```
? And I click on "Create campaign button" on "Dashboard page"  
       Undefined. Implement with the following snippet:

         Given('I click on {string} on {string}', async function (string, string2) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });
```

### ✅ What did you expect to see?
I expected the step to be executed

### 📦 Which tool/library version are you using?
```
"@cucumber/cucumber": "^9.5.1",
"@playwright/test": "^1.38.0",
"@types/node": "^20.8.0",
"multiple-cucumber-html-reporter": "^3.5.0",
"ts-node": "^10.9.1"
```

### 🔬 How could we reproduce it?
campaignCreate.feature:
```
Feature: Campaign creation

  Scenario: [TC] Advertiser should be able to create campaign
    Given I am authenticated as "Advertiser"
    Then I am on "Dashboard page"
    And I click on "Create campaign button" on "Dashboard page"
```
commonActions.ts:
```
When('I click on {toCamelCase} on {string}', function (element: string, page: string) {
  //some code
});
```
defineParameterTypes.ts:
```
import { defineParameterType } from "@cucumber/cucumber";

defineParameterType({
  name: 'toCamelCase',
  regexp: /^[^"]*\sbutton|checkbox|radiobutton$/,
  transformer: function(match) {
    return match.toLowerCase()
      .replace(/(?:^\w|[A-Z]|\b\w)/g, function(word, index) {
        return index === 0 ? word.toLowerCase() : word.toUpperCase();
      })
      .replace(/\s+/g, '');
  },
  preferForRegexpMatch: true,
  useForSnippets: false
});
```

Screenshots:
![image](https://github.com/cucumber/cucumber-js/assets/62233209/ed38e569-041c-4525-9821-5dcc2e9f628c)

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
Closing as you got the right pointers on the Slack thread https://cucumberbdd.slack.com/archives/C60TKS3SL/p1696091351991659
