### ISSUE TITLE
Cucumber 10.0.0 changes execution order of the feature files when `paths` configuration is provided

### ISSUE THREAD

**Issue by pk** [cucumber/cucumber-js#2343]
### 👓 What did you see?

We use configuration profiles with `paths` attribute to enforce execution order in our E2E test suites:

```
export const ciexcludebugs = {
  ...JSON.parse(JSON.stringify(common)),
  tags: '(not @bug) and (not @ignore)',
  paths: [
    'fixtures/',
    'features/'
  ]
}
```

In 9.x.x all `fixtures` (subfolders, and respective *.feature files) have been executed first and the `features` after that.
Since 10.x.x the order is reversed and features are always the first.

We have `fixtures` and `features` (both Cucumber feature files). `fixtures` contains cucumber feature files which execute and each saves a state of our server into a json file - we generate re-usable state & we test our management features.

### ✅ What did you expect to see?

The Cucumber should execute the feature files in the specified order from the Profile `paths` (or command line) and then, within the folders alphabetically as in 9.x.x.

### 📦 Which tool/library version are you using?

Cucumber 10.0.0
Node.js 20.8.1

### 🔬 How could we reproduce it?

Use profile `paths` as above or `cucumber-js fixtures/ features/`

**Comment by pk** [comment]
I've been going through the open issues and I'm not sure if this one is relevant or not to my use case: #2253

**Comment by davidjgoss** [comment]
Thanks for raising @pk. I think this has come from the upgrade to the latest `glob` which we did before the 10.0.0 release and included some changes to ordering which we had to adapt. I'll take a look and see what we can do to fix.

**Comment by pk** [comment]
@davidjgoss I had to revert to @cucumber/cucumber@9.6.0 to have the (my) expected behaviour. Which I think is the latest 9x release, right?

**Comment by davidjgoss** [comment]
@pk that's right yes.

**Comment by davidjgoss** [comment]
Released in https://github.com/cucumber/cucumber-js/releases/tag/v10.0.1

**Comment by pk** [comment]
Hi @davidjgoss , thank you for the quick fix and release.
We confirm the fix works, at least for our scenario.
