### ISSUE TITLE
Attachments: Text attached is not saved as a real text

### ISSUE THREAD

**Issue by joao-motork** [cucumber/cucumber-js#2350]
### 👓 What did you see?

During a run with cucumberjs 10, I attach some text, like:
![image](https://github.com/cucumber/cucumber-js/assets/132624270/3eac6ad8-c52e-421a-ba26-deda287f97dd)

Checking the json report created, the attachment is not really saved as text, but as:
![image](https://github.com/cucumber/cucumber-js/assets/132624270/653bd1a6-a734-4732-bfc8-720b362054ba)

Generating an HTML report:
![image](https://github.com/cucumber/cucumber-js/assets/132624270/3ec3a418-3ec6-4974-9626-f36c2b9186ae)

### ✅ What did you expect to see?

The same result I get with cucumberjs 9

![image](https://github.com/cucumber/cucumber-js/assets/132624270/fc2e9d35-82e4-4605-bf36-5264d91a69b9)

![image](https://github.com/cucumber/cucumber-js/assets/132624270/bb2f3081-e391-45d2-9f50-19f50744ef61)

**Comment by davidjgoss** [comment]
From the 10.0.0 [release notes](https://github.com/cucumber/cucumber-js/blob/main/UPGRADING.md#attachments-in-json-formatter):

> Previously, string attachments were included as plain text in the JSON formatter output, where other attachments were Base64 encoded. This meant for consumers, it was ambiguous whether any attachment was Base64 encoded or not. Now, all attachments are Base64 encoded regardless of how they were initially attached.

(https://github.com/cucumber/cucumber-js/pull/2261)

The code that produces your HTML report from the JSON output will need to Base64 decode the attachment body.
