### ISSUE TITLE
The ability of running hooks in serial mode while config has parallel mode set

### ISSUE THREAD

**Issue by jkalandarov** [cucumber/cucumber-js#2354]
### 🤔 What's the problem you're trying to solve?
```Gherkin
Given I have a config with parallel: 5
And I need to perform an action only once before all (10) scenarios with a certain tag
And I want to create a Before hook where I can set serial mode only for this hook
Then this hook should ignore parallelism in config and be executed only once
```

### ✨ What's your proposed solution?
```Javascript
Before({ tag: '@certainTag', parallel: false }, async function() {
  // Do some action
});
```

### ⛏ Have you considered any alternatives or workarounds?

No workaround at the moment. Our tests run in parallel mode in ci/cd pipeline.
If set `parallel: 1` in config, it will increase test run time substantially.

### 📚 Any additional context?

**Comment by davidjgoss** [comment]
Before hooks always run once per scenario regardless of serial/parallel. Do you mean BeforeAll?

**Comment by jkalandarov** [comment]
I have 5 scenarios with @purchasing tag. In this case, how many times does the following hook run?
```JavaScript
Before({ tag: '@purchasing' }, async function() {
  await purchaseCampaign();
});
```
It's running (purchasing a campaign) 5 times in my case. 
I need an implementation to run it once no matter what mode is set in config.

**Comment by davidjgoss** [comment]
`Before` hooks run once per scenario, regardless of serial or parallel. They're designed that way, it's not something we're ever going to change.

`BeforeAll` hooks run once per test run or, for parallel, once per worker. There are workarounds described in https://github.com/cucumber/cucumber-js/issues/1153#issuecomment-1590875038 where you could conditionally run something on just the first worker.

For your case though I would recommend you make your `purchaseCampaign()` idempotent so it only does the expensive work once regardless of how many times called.
