### ISSUE TITLE
Can we call one scenario inside another scenario ??

### ISSUE THREAD

**Issue by ghost** [cucumber/cucumber-js#237]
Suppose I have 2 scenarios, Scenario 1 and Scenario 2.
I want to call scenario 1 in any step (i.e. Given, When or Then) of scenario 2.
Is it possible or is there any way to achieve this ?

**Comment by hackhat** [comment]
Hy! If anyone is still interested in this feature here is a library I've done which works with cucumber:
[cucumber-pro](https://github.com/hackhat/cucumber-pro) with sync, callable steps and parsed arguments.

Feedback is appreciated

**Comment by hackhat** [comment]
Hy! If anyone is still interested in this feature here is a library I've done which works with cucumber:
**[cucumber-pro](https://github.com/hackhat/cucumber-pro)** with sync, **callable steps** and parsed arguments.

Feedback is appreciated
