### ISSUE TITLE
can we use this with cypress and typescript

### ISSUE THREAD

**Issue by peacetrader** [cucumber/cucumber-js#2387]
Hi, I am using cypress and typescript. Would like to know if anyone has integrated this with cucumber-js. Thank you.

**Comment by davidjgoss** [comment]
Thanks for your interest @peacetrader 

You can’t use both of cucumber-js and cypress at the same time - they are both test runners, and you can really only have one of those in play.

I would recommend trying this package:
https://github.com/badeball/cypress-cucumber-preprocessor

It uses our official libraries for parsing feature files etc but then runs the tests in cypress. We’re working to be able to share reporting and plugins so a good one to bet on too.
