### ISSUE TITLE
Background steps are reported without keyword Background in json report

### ISSUE THREAD

**Issue by usertest2024** [cucumber/cucumber-js#2388]
### 👓 What did you see?

In json report, steps coming from Background section are not identified as background steps.
So, the tool we are using internally to generate custom report, is not working any more.(cannot find keyword: Background)
 I have in json report:
 
 ```
                "steps": [
             
                    {
                        "arguments": [],
                        "keyword": "Given ",
                        "line": 8,
                        "name": "this is a background step",
                        "match": {
                            "location": "src/impl/steps/stepDefinition.steps.ts:25"
                        },
                        "result": {
                            "status": "passed",
                            "duration": 1610877746
                        }
                    },
```

### ✅ What did you expect to see?

I expect to see something like: 
```
      "elements":[
         {
            "type":"background",
            "keyword":"Background",
            "steps":[
               {
                  "result":{
                     "duration":1390492,
                     "status":"passed"
                  },
                  "line":9,
                  "name":"this is a background step",
                  "keyword":"Given "
               }
            ]
         },
......
```
### 📦 Which tool/library version are you using?

  "@cucumber/cucumber": "^10.3.1"

**Comment by davidjgoss** [comment]
> So, the tool we are using internally to generate custom report, is not working any more.

This JSON output has been in maintenance mode for some time. Have you been using another version of cucumber-js that produces for format you expect from the JSON formatter? If so, can you say which version?

**Comment by usertest2024** [comment]
Hello,
we used our tool with java projects (cucumber-java 7.14.0). 
In Json outputs, background steps are correctly identified . 
 
          {
          "type":"background",
           "keyword":"Background",
            "steps":[
          {
            "result":{
            "duration":1390492,
            "status":"passed"
            },
            "line":9,
            "name":"this is a background step",
            "keyword":"Given "
            }
            ]
            } 

Now, we are automating front projects and we use   cucumber": "10.3.1".

In generated Json report, background steps are not flagged with keyword Background as per cucumber-java.

       {
                    "arguments": [],
                    "keyword": "Given ",
                    "line": 8,
                    "name": "this is a background step",
                    "match": {
                        "location": "src/impl/steps/stepDefinition.steps.ts:25"
                    },
                    "result": {
                        "status": "passed",
                        "duration": 1610877746
                    }
                }

Hope my explanation is clear for you
Thank you  for your help

**Comment by davidjgoss** [comment]
Thanks, that makes sense now. Let me come back to you shortly on this.

**Comment by mpkorstanje** [comment]
@usertest2024 unfortunately the JSON output was developed before things like the JSON Schema got popular and so different Cucumber implementations have come to differ over time.

It is worth looking at test data from cucumber-js and cucumber-jvm in the cucumber-json-converter:

 * https://github.com/cucumber/cucumber-json-converter/blob/main/testdata/cucumber-jvm/7.2.3/json/decaying-background.json
 * https://github.com/cucumber/cucumber-json-converter/blob/main/testdata/cucumber-js/7.3.2/json/decaying-background.json
 
For cucumber-jvm backgrounds are represented as their own unique element with `"type": "background"` in the `elements` array. Distinct from the scenario elements. Where as in cucumber-js, only elements of `"type": "scenario"` are used, and the background steps are folded into the scenario. Changing this seem like a breaking change of the cucumber-js flavor of the json to me, but I'll defer to @davidjgoss for judgement on that. 

While we are slowly working on [a common output format](https://github.com/cucumber/messages/) with a schema, you may be better of fixing your custom reporting tool to be lenient enough to accept both formats.

**Comment by usertest2024** [comment]
@mpkorstanje  thank you for the answer and the explanations
Unfortunately , for documentation purposes and regulatory compliance, we need to include the background in the generated  reports as  'initial conditions' seperate section and not in scenario  descriptions.
This is a mandatory  section required to pass the audit of our documents."

**Comment by mpkorstanje** [comment]
Then I am afraid you will have the unenviable task of reimplementing the json formatter from cucumber-jvm in javascript.

Or perhaps a less involved solution would be to try and post process the json report and convert it to the jvm flavour.  The `uri` field provides the file location. You can parse it with the [Gherkin parser](https://github.com/cucumber/gherkin). Then matching the steps in the report to the steps in backgrounds of the documents you can split them.

Finally, we are (and have been for a long time) planning to rewrite the json formatter used by cucumber-jvm to use the message protocol - similar to the [junit-xml-formatter](https://github.com/cucumber/junit-xml-formatter). This should allow you to consume the message protocol from cucumber-js and render that as a json report. But the timeline on this is indefinite, so I don't think this will meet your needs.
