### ISSUE TITLE
ESM mode with ts-node breaks TypeScript path alias resolution in cucumber-js

### ISSUE THREAD

**Issue by samydoesit** [cucumber/cucumber-js#2403]
### 👓 What did you see?

When using cucumber-js with `ts-node` as the loader in ESM mode, TypeScript path aliases specified in `tsconfig.json` fail to resolve.

Path aliases are not resolved, resulting in module resolution errors when attempting to execute tests.

Error:
```bash
Error: Cannot find package '@/index.js' imported from /cucumber-typescript-path-alias-reproduction/features/step_definitions/steps.ts
    at packageResolve (/cucumber-typescript-path-alias-reproduction/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (/cucumber-typescript-path-alias-reproduction/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (/cucumber-typescript-path-alias-reproduction/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /cucumber-typescript-path-alias-reproduction/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/cucumber-typescript-path-alias-reproduction/node_modules/ts-node/src/esm.ts:168:34)
    at /cucumber-typescript-path-alias-reproduction/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/cucumber-typescript-path-alias-reproduction/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/cucumber-typescript-path-alias-reproduction/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
```

### ✅ What did you expect to see?

TypeScript path aliases should resolve correctly when cucumber-js is run in ESM mode using `ts-node`.

### 📦 Which tool/library version are you using?

- Cucumber-js version: 10.6.0
- ts-node version: 10.9.2
- TypeScript version: 5.4.5
- Node.js version: 20.11.1

## Steps to Reproduce
1. Clone the provided repository from https://github.com/samydoesit/cucumber-typescript-path-alias-reproduction
2. Install dependencies using `npm install`
3. Attempt to run the tests using `npm test`
4. Notice the module resolution errors related to TypeScript path aliases

**Comment by GRmeB** [comment]
+1 Same issue here...

**Comment by samydoesit** [comment]
Thanks for your quick response. :)
I thought maybe there is another way. 

We will keep the CommonJS output for now.

**Comment by dnotes** [comment]
To clarify, is there no way to import from the local files when using ts-node/esm? I can't seem to import even if I use a relative path, even if the files are in the same directory, but perhaps that's a different issue.

**Comment by dnotes** [comment]
For anyone else who finds this issue, my workaround was to use `compilerOptions.moduleResolution: "node"` in the tsconfig.json, and then import modules using relative paths and the `.js` file extension even for `.ts` files. So in `tests/steps/search.ts`:

```
import searchRequest from '../../src/lib/searchRequest.js'; // imports $lib/searchRequest.ts
```

**Comment by hynding** [comment]
Adding my two cents as I got it to work without ts-node nor tsconfig-paths despite trying everything I could think of. I did try some custom loader scripts that worked but were a bit clunky for my taste and less than ideal from a maintenance standpoint.

I came across several others pointing out they replaced their configuration with the [tsx](https://www.npmjs.com/package/tsx) package but couldn't get it to work following the documented ESM principles. I wanted to use TypeScript for my step definitions and path aliases within those files, plus include `type: module` in my `package.json` and have the module and moduleResolution in tsconfig compilerOptions set to `ES2022` and `Bundler` respectively. I felt obligated to use `import` over `require` in my cucumber config file when trying out `tsx` but I wasn't having any success. 

If anyone else is having the same issue, here's what I did to get everything to run successfully:

- Node v22
- Cucumber v11
- `package.json` includes `"type": "module"`
- step definitions are all `.ts` files and use path aliases as defined in my tsconfig (in my case `"baseUrl": "./src", "paths": {"@/*": ["*"]}`)
- tsconfig file is configured to use `module` and `moduleResolution` (in my case `ES2022` and `Bundler` respectively)
- **Do not** use `import` in the cucumber config and instead use `requireModule` set to `tsx/cjs` (neither `loader` nor `import` set to `tsx` or `tsx/esm` did not work for me)

My `cucumber.yaml` file looks like this:

> default:
>   paths:
>     - "../../features/**/*.feature"
>   requireModule:
>     - tsx/cjs
>   require:
>     - "tests/**/*.ts"

Nit: I declare my step definitions outside of my `features` and `src` folders in my project root called `tests` (as I'm not using any other testing framework at the moment).

My tests also had a 4x performance improvement as well, which is always a plus.

**Comment by OctopusET** [comment]
@hynding thank you so much, this fixed my issue

**Comment by rishoo2019** [comment]
Thanks for the solution @hynding . It worked for me too.

**Comment by tbaroti** [comment]
For me @hynding's solution unfortunately didn't work, as it was complaining about top level await

> ERROR: Top-level await is currently not supported with the "cjs" output format

Instead, I managed to make it work this way:

cucumber config (I use .mjs config format, but it should work with other too I suppose)
```javascript
export default {
  paths: ['test-e2e/**/*.feature'],
  import: ['src/**/*.ts'],
};
``` 
`tsconfig.json` compilerOptions:

```json
"compilerOptions": {
    "module": "esnext",
    "moduleResolution": "bundler",
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"]
    },
   ...
};
``` 

Run with `NODE_OPTIONS='--import tsx'`
```shell
NODE_OPTIONS='--import tsx' yarn run cucumber-js
``` 

- Node: v22
- Cucumber: v12
- tsx v4.21
- Typescript step files work with ESM
- Import path resolutions work
- InverifyJS works (see https://github.com/jonaskello/tsconfig-paths/issues/243#issuecomment-2667830869)

**Comment by dnotes** [comment]
Huh... I haven't seen this in a while! ESM and TypeScript were such a hassle that I ended up creating a Vitest plugin to replace the CucumberJS test runner. I'd welcome feedback on QuickPickle if you've got the interest.
