### ISSUE TITLE
stepResult event triggered for hooks in 0.4.2

### ISSUE THREAD

**Issue by akania** [cucumber/cucumber-js#241]
I wanted to update to 0.4.2 in browser runner and i've noticed that 'stepResult' event is triggered now for before and after hooks which 'may' not be consistent?
Do we handle hooks as regular steps?
I can still filter it out by stepResult.getStep().isHidden();

**Comment by charlierudolph** [comment]
@jbpros whats wanted here? Should stepResult event not be triggered for hooks? Currently hooks get printed in the [JSON formatter](https://github.com/cucumber/cucumber-js/blob/master/features/json_formatter.feature#L1707).

**Comment by jbpros** [comment]
`isHidden` is sufficient to tell the difference between steps and hooks, so let's keep it simple and close this.
