### ISSUE TITLE
Support i18n in snippet generation

### ISSUE THREAD

**Issue by snorripall** [cucumber/cucumber-js#248]
Please consider supporting i18n in snippet generation. 

# Example
The Icelandic language is always generated to this.Given 

I'm using cucumber-js version 0.4.4 which uses gherkin 2.12.2
https://github.com/cucumber/cucumber-js/blob/v0.4.4/package.json

For this feature 
```gherkin
# language: is
Eiginleiki: Example feature
  My story

  Atburðarás: Should be scenario
    Ef should be given
    Þegar should be when
    Þá should be then
    Og should be then
    En should be then
```
I get the following output when I run cucumber-js.

```javascript
this.Given(/^should be given$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.Given(/^should be when$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.Given(/^should be then$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});
```

Expected output should be 

```javascript
this.Given(/^should be given$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.When(/^should be when$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.Then(/^should be then$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});
```

**Comment by mancvso** [comment]
It is marked as closed, but I don't get it; as of today i18n is not part of snippet generation, I cannot write a feature in Spanish and expect to have the this.Dado, this.Cuando and this.Entonces methods for steps generation replacing this.Given, this.When and this.Then.

**Comment by jbpros** [comment]
@mancvso It is not marked as closed and still needs to be done.

**Comment by charlierudolph** [comment]
@jbpros this feels like something Gherkin should be handling. Personally I'd prefer to just suggest using defineStep unless the keyword is actually Given/When/Then (or implied due to its previous keyword). 

As a stronger preference I thing we should remove Given/When/Then from step definitions and always have developers use defineStep in order to keep i18n out of code.

**Comment by charlierudolph** [comment]
@jbpros any thoughts here?

**Comment by thomasvanlankveld** [comment]
My preferred alternative spoken language style is actually to rename the functions to match the spoken language:

```javascript
var Stel = Als = Dan = this.defineStep;

Stel(/^de blog heeft de volgende vier posts:$/, function (table, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

Als(/^ik de blog bezoek$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

Dan(/^zie ik de volgende posts:$/, function (table, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});
```

because it the line looks really confusing with the function name in English; The following regex is not even a proper sentence with the function name in english:

```javascript
this.Given(/^de blog heeft de volgende vier posts:$/, function (table, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.When(/^ik de blog bezoek$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});

this.Then(/^zie ik de volgende posts:$/, function (table, callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});
```

Although, if the snippet generator produces `this.Stel`, `this.Als` and `this.Dan`, it might be even weirder...

Any thoughts?

**Comment by aslakhellesoy** [comment]
We won't be removing `Given/When/Then` from step definitions. Those words are an important part of how the sentence reads, and how the step definition is understood.

Besides - all other Cucumber implementations use them, and we want this to be consistent.
