### ISSUE TITLE
Cannot attach non string data to report

### ISSUE THREAD

**Issue by struankl** [cucumber/cucumber-js#249]
I think because of the fix for [#233](https://github.com/cucumber/cucumber-js/issues/233) the scenario.attach now only supports string data. If you try to pass it any other type it will have toString() called on it (previously toString('base64')) and if you try to pass data which is already base64 encoded then it gets it gets based64 encoded again at the formatting stage in the json formatter. @simondean mentioning you as instructed.

**Comment by struankl** [comment]
Thanks @jlin412 that worked for me.

**Comment by jbpros** [comment]
Seems to be ok now? Please reopen if needed.
