### ISSUE TITLE
Remove "npm install --dev" suggestion from Readme

### ISSUE THREAD

**Issue by djungowski** [cucumber/cucumber-js#259]
So I was trying to install cucumberjs. Not wanting to install it globally first I though to use the

    npm install --dev

way as defined in the README.md (including defining cucumber as devDependency). After 2 hours of downloading 1.7 GB (!) and heavy cpu usage (in this order) the installation quit with:

    Segmentation fault: 11

I strongly discourage installing cucumber this way. I suppose that --dev installs all the dev dependencies which is A LOT:

    # find . -name node_modules -type d -exec ls {} \; | uniq | wc -l
    22352

Installation via

    npm install -g cucumber

took seconds.

I'm not sure if I'm the only one experiencing this, but if not, I would suggest removing this installation suggestion from the readme.

**Comment by alwinmark** [comment]
I could install it locally. However I cant get it working properly as I only get the Feature description printed without steps, or he can't find the stepdefinitions.... :-(
