### ISSUE TITLE
console.log(scenario) gives me in two different projects different results

### ISSUE THREAD

**Issue by desmond8519** [cucumber/cucumber-js#260]
Hi I am using cucumber.js 0.4.4 with Appium and with Webdriver.
In both cases I want to see in the this.After if a scenario is failed.
I am ussing isFailed() but for Webdriver it tells me that there is no method isFailed.
I logged scenario in both cases and indeed I don't get it.

See the logs: 

The on where I am missing it: 

{ payloadType: 'scenario',
  setBackground: [Function: setBackground],
  buildScenarios: [Function: buildScenarios],
  getKeyword: [Function: getKeyword],
  getName: [Function: getName],
  getDescription: [Function: getDescription],
  getUri: [Function: getUri],
  getLine: [Function: getLine],
  getBackground: [Function: getBackground],
  addStep: [Function: addStep],
  getLastStep: [Function: getLastStep],
  getMaxStepLength: [Function],
  setSteps: [Function: setSteps],
  getSteps: [Function: getSteps],
  addTags: [Function: addTags],
  addInheritedtags: [Function: addInheritedtags],
  getTags: [Function: getTags],
  getOwnTags: [Function: getOwnTags],
  acceptVisitor: [Function: acceptVisitor],
  instructVisitorToVisitBackgroundSteps: [Function: instructVisitorToVisitBackgroundSteps],
  instructVisitorToVisitScenarioSteps: [Function: instructVisitorToVisitScenarioSteps],
  instructVisitorToVisitSteps: [Function: instructVisitorToVisitSteps] }

The one where it is in:

{ getKeyword: [Function: getKeyword],
  getName: [Function: getName],
  getDescription: [Function: getDescription],
  getUri: [Function: getUri],
  getLine: [Function: getLine],
  getTags: [Function: getTags],
  isSuccessful: [Function: isSuccessful],
  isFailed: [Function: isFailed],
  isPending: [Function: isPending],
  isUndefined: [Function: isUndefined],
  getAttachments: [Function: getAttachments],
  attach: [Function: attach] }

The code in both situations

this.After(function(scenario, done) {
console.log(scenario)
}

Please help me

**Comment by charlierudolph** [comment]
Looks like in one version you have a Cucumber.Ast.Scenario and in one you have Cucumber.Api.Scenario (introduced in 0.4.2). Thus I believe you were running two different versions of cucumber. Please reopen if this is still an issue.
