### ISSUE TITLE
Cucumber keeps running in the background

### ISSUE THREAD

**Issue by grofit** [cucumber/cucumber-js#262]
Hey,

I am running cucumber via webstorm's cucumber-js runner, and for some reason even after my `After` method has been run and the callback has been invoked the process keeps running. So as I keep testing I keep getting more and more node processes running in the background which I have to manually go and kill (task manager in windows).

My tests are using express (the app has a monogodb connection) which are started on before and closed on after, this worked fine in mocha, but the code looks like:

```
    this.After(function(callback){
        this.server.on('close', callback);
        this.server.close();
    });
```

I made the close event notification do a console.log to prove it is hitting it and that came back correctly. Also when the next tests spawn up there is no error implying the port is in use, so that implies to me that the express app is being ended correctly and mongodb shows the connections going. However the process seems to still be running, so is there anything I am missing on my closing down of cucumber?

**Comment by jbpros** [comment]
Should be fixed by 23ff8608417b542c8c775c2ac5914e232b8c5dfa (0.5.2+). Please reopen if necessary.
