### ISSUE TITLE
Using Before hook with Around

### ISSUE THREAD

**Issue by grofit** [cucumber/cucumber-js#263]
I have some tests where I want to ideally clean up the database before each test, however the database connection is initialized within the Before (which I want to move to a BeforeAll style approach which is in another question open #261) then the Around makes use of it.

However I keep getting an error saying that its not defined, so my assumption would be that `Before` would be called before `Around`, so is this right or does `runScenario` kick off the `Before` method?

**Comment by jbpros** [comment]
I'm closing this for now. Please reopen if it's still an issue.
