### ISSUE TITLE
Asynchronous Tests Don't Complete Properly

### ISSUE THREAD

**Issue by aslate** [cucumber/cucumber-js#264]
I've been using Cucumber to write integration tests for a client/server messaging framework. 

My Then step included waiting for a response from the server: 

    this.Then /^the "([^"]*)" eventually receives a message with a payload of "([^"]*)"$/, (name, payload, callback) ->
        serviceState = this[name]
        serviceState.wasCalledPromise.then(callback, callback.fail)

I was expecting the fake latency to eventually resolve a promise on the client side, at which point I would callback success / failure. I was happily coding away to green test suites until I realised that this final step wasn't being outputted on the console - the previous steps were all successful but this step didn't exist.

I had a defect in my code where the client wasn't actually subscribing to the server properly. I was expecting this to appear as a "pending" case, or something like that. But without a setTimeout keeping the test alive it just passes on / terminates without acknowledging the lack of a callback to this step.

I wouldn't expect a step that started executing, but never finished, to not appear in the output.

**Comment by jbpros** [comment]
We just introduced promise support. This might be irrelevant now. Please reopen if need be.
