### ISSUE TITLE
Unable to use new line in table step data

### ISSUE THREAD

**Issue by kayhadrin** [cucumber/cucumber-js#265]
Hi there,

I'm currently finding an issue when defining a step data table.

See below example:

``` gherkin
Feature: Use new line characters in step table data
    As a user of Cucumber

    Scenario: Test new line character in step table data
        Given I have a table:
            | body  | [HTTP 500]\n\nTry to refresh this page or report this issue to an admin. |
```

Expected: `"[HTTP 500]\n\nTry to refresh this page or report this issue to an admin."`
Actual: `"[HTTP 500]\n\\nTry to refresh this page or report this issue to an admin."`
(notice the double backslash)

Could someone have a look into it?

**Comment by Shilpi85** [comment]
Hi,

I am also getting this issue! Any solution or workaround for this issue?

**Comment by nnarhinen** [comment]
Yeah it seems cucumber is "double escaping" all but the first `\n`
