### ISSUE TITLE
Forgetting to call stepdef callback should fail

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#27]
* Go to http://cucumber-js.herokuapp.com/
* Comment out callback() in the Given stepdef
* Run
* Nothing happens

I would expect to see an error message saying "callback not called in /^a variable set to (\d+)$/"

**Comment by zs-zs** [comment]
Hi guys, 

I don't know when do you want to implement the timeout and the promise support, I just needed some quick & nice way to fix these, so I created a small cucumber-js extension called [cucumber-sweetener](https://github.com/zs-zs/cucumber-sweetener) from some of your ideas.

Timeouts can be configured both locally and globally.

It's far from perfect but you can use it as an inspiration.

**Comment by jbpros** [comment]
Thank you @zs-zs, this is a nice intermediate solution! I like small libs! Again, this should be fixed with #187, which is the thing I'm working on atm.

**Comment by jbpros** [comment]
This is somewhat mitigated by the introduction of synchronous stepdefs and promises.

Callback-based step definitions can still make Cucumber die if a callback is forgotten.

**Comment by jbpros** [comment]
Fixed in 2c5cd124724ba128d1d1c2b50ea80f75acef435c
