### ISSUE TITLE
I want to add some customized output in registerEvent('BeforeFeature') in JSON output

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-js#276]
I want to add browser info/host info into registerEvent('BeforeFeature') into json output.
Is there a way to do that?
Currently, I have
```
  this.registerHandler('BeforeFeatures', function (event, done) {
    console.log('ENV=' + env);
    console.log('HOST=' + host);
    console.log('BROWSER=' + browser);
    done();
  });
```
Console.log only goes to command line but not into json output.

**Comment by jbpros** [comment]
I can't see any straightforward way of doing this. Your best bet is probably to extend the JSON formatter and augment it. Please come and ask about this on the cukes group instead, as it is specific to your needs, this won't be added to Cucumber anyway.
