### ISSUE TITLE
Table fields are printed as undefined in stdout

### ISSUE THREAD

**Issue by h2non** [cucumber/cucumber-js#290]
Running cucumber 0.4.4

```gherkin
Given the following service options values:     
  | Key | Value |
  | undefined | undefined |
  | undefined | undefined |
```

**Comment by h2non** [comment]
Also running 0.4.7

**Comment by h2non** [comment]
Any plan to fix this? I guess it's an issue in the Gherkin parser. I can help fixing it, any suggestion about where to start reading code?

**Comment by h2non** [comment]
This issue is caused due to `table.rows()` returns a mutable array with side effects. 
I'm not sure if the table array provided should be exposed as a copy instead of the original array reference.

**Comment by jbpros** [comment]
A copy would be better indeed. See #399.
