### ISSUE TITLE
Calling other step from steps definition

### ISSUE THREAD

**Issue by h2non** [cucumber/cucumber-js#292]
I know that's possible in the Ruby implementation, but how is that programmatically possible in the JavaScript implementation?

Getting the Cucumber AST scenario/step instance is possible from step definitions or hooks?

**Comment by jbpros** [comment]
It's not possible in Cucumber.js. See #11.

This is an issue tracker. Please use the [cukes group](https://groups.google.com/forum/#!forum/cukes) for support.

**Comment by h2non** [comment]
And there is no plans to support it in the future? It's a really missing feature from Cucumber's Ruby.
Maybe exposing the AST instance in the World inherited scope in order to be also available from the steps would be a reasonable solution

**Comment by hackhat** [comment]
Hy! I've created a lib which does exactly what you are asking (call a step from another step), take a look here: https://github.com/hackhat/cucumber-pro 
Feedback is welcome!

**Comment by h2non** [comment]
Cool! Thanks for sharing. I'll take a look

**Comment by bmsoko** [comment]
@hackhat this seems to be awesome! can this be integrated or used with Protractor?
Thanks!

**Comment by hackhat** [comment]
@bmsoko I don't know much about Protractor.
