### ISSUE TITLE
How to run features from a custom folder?

### ISSUE THREAD

**Issue by bitplanets** [cucumber/cucumber-js#293]

**Comment by jbpros** [comment]
Please use the [cukes](https://groups.google.com/group/cukes) google group for support. This is an issue tracker.

Also: `cucumber.js --help`.

**Comment by mattdodge** [comment]
Well I'm having the same problem and this is what comes up in a Google search.... And then there's a handful of forum posts from maintainers that tell people to log issues here. 

I looked at `--help` and it looks like `-r` might be what I want but that's not working either? 

Is that not correct? Is there any response to this other than "RTFM"?

**Comment by mattdodge** [comment]
Aha, it seems obvious now but for anyone else that stumbles across this you don't use the `-r`, just provide the features folder as the file glob.

So like this:
```bash
npm run cucumber-js path/to/your/features
```
