### ISSUE TITLE
Can you add a complete API of the lib?

### ISSUE THREAD

**Issue by bitplanets** [cucumber/cucumber-js#294]
For example:

     node_modules/.bin/cucumber-js --format pretty

Is not included into the current documentation.

Maybe a big link named "Documenation API" to this: https://github.com/cucumber/cucumber/wiki

**Comment by jbpros** [comment]
The CLI options are all documented in `cucumber.js --help`. We are working on a comprehensive [documentation website](https://cukes.info/platforms) but it still needs a lot of work. Feel free to [contribute](https://github.com/cucumber/website/tree/master/apps/docs/jekyll-content) :)
