### ISSUE TITLE
Multiple results

### ISSUE THREAD

**Issue by cajoy** [cucumber/cucumber-js#298]
I have around 20 tests.

Some are successful - some are failure.

Also I have some code to reset database before each scenario/feature:

```

  this.BeforeScenario(function(feature, callback) {
    console.log('\nPreparing fixtures...', feature.getName());

    running = true;

    app.looptimeModule.resetAndLoadFixtures(app)
      .then(function (done) {
        console.log('\nRunning test...');

        callback(true);
      })
      .catch(function (err) {
        process.exit(0);
      })
  });
```

The issue becomes when couple of tests failure. 

1) So cucumber start running next test before hook finish execution.
2) I have many open chrome windows
3) Even more.. At the end of execution results shows on the page but not once.. It shows multiple times.

It seems like sometimes when step failures chrome window doesn't close and script start executing next step even without waiting for hook to finish. 

Very strange... Can record video if needed..

**Comment by jbpros** [comment]
Please use the regular hook API (i.e. `Before()`, not the event listener `BeforeScenario()`).

Closing as it is pretty old. Please reopen if you still experience any issues.
