### ISSUE TITLE
cucumber hangs after successful completion of tests

### ISSUE THREAD

**Issue by nareshbhatia** [cucumber/cucumber-js#300]
Can't figure out why cucumber.js is hanging after successful completion of tests:

    $ cucumber.js test/features/ --require test/step_definitions/
    Database initialized
    .....
    
    1 scenario (1 passed)
    4 steps (4 passed)
    <<< hangs here >>>

I thought that maybe I forgot to call `callback()`, but I checked and rechecked - callbacks are always being called. The entire project is on github [here](https://github.com/archfirst/node-rest-template), however the relevant portions are included below:

    /***** account.steps.js *****/
    module.exports = function() {
    
        this.World = require('./support/world').World;
    
        this.Given(/^my account holds the following assets$/, function (table, callback) {
            this.createAssets(table.hashes(), callback);
        });
    
        this.Given(/^my investment in the account is (\d+)$/, function (investment, callback) {
            this.setInvestment(investment);
            callback();
        });
    
        this.When(/^I calculate the account summary$/, function (callback) {
            this.getAccount(callback);
        });
    
        this.Then(/^I should get the following account summary$/, function (table, callback) {
            this.assertAccountSummary(table.hashes()[0]);
            callback();
        });
    };

    /***** world.js *****/
    var World = function World(callback) {
    
        this.account = undefined;
        this.investment = undefined;
        this.error = undefined;
    
        this.createAssets = function(assets, callback) {
            var tasks = [];
            _.each(assets, function(asset) {
                tasks.push(AssetService.createAsset(asset));
            });
    
            Promise.all(tasks)
                .then(function() {
                    callback();
                });
        };
    
        this.setInvestment = function(investment) {
            this.investment = investment;
        };
    
        this.getAccount = function(callback) {
            var self = this;
            AssetService.getAccount(this.investment)
                .then(function (account) {
                    self.account = account;
                    callback();
                });
        };
    
        // ----- Asserts -----
        this.assertAccountSummary = function(expectedAccountSummary) {
            expect(this.account.market_value).to.almost.equal(parseFloat(expectedAccountSummary.market_value), 0);
            expect(this.account.earnings).to.almost.equal(parseFloat(expectedAccountSummary.earnings), 0);
            expect(this.account.cash).to.almost.equal(parseFloat(expectedAccountSummary.cash), 0);
        };
    
        callback();
    };

**Comment by jbpros** [comment]
Have you tried waiting for more than 60 seconds? I'm asking this because Cucumber will wait for 60 seconds after the completion of your suite for the process to exit *by itself*. That means that if something is keeping the event loop busy (like open network connections, ports listening, etc...), Cucumber will wait and eventually timeout.

Also, as this is an issue tracking system, could you please head over to the [cukes group](https://groups.google.com/forum/#!forum/cukes) for support next time?

**Comment by nareshbhatia** [comment]
@jbpros, thanks for the tip. It is indeed the database connection that is holding up Cucumber. As per your suggestion, I will move the discussion to cukes group.
