### ISSUE TITLE
@ignore on Scenario still executes it

### ISSUE THREAD

**Issue by D0rmouse** [cucumber/cucumber-js#301]
When adding `@ignore` on a `Scenario` does not ignore the `Scenario`, but still executes it.

**Comment by jbpros** [comment]
@D0rmouse how do you invoke cucumber.js after tagging a scenario with `@ignore`?

**Comment by D0rmouse** [comment]
It's integrated in my Grunt build using grunt-protractor-runner, which reads a cucumber.conf.js.

**Comment by jbpros** [comment]
Sorry, I wasn't clear enough. What options are you passing to Cucumber?

**Comment by D0rmouse** [comment]
cucumberOpts: {
        require: 'cucumber/features/steps/*_steps.js',
        format: 'pretty'
      }

**Comment by jbpros** [comment]
You need to tell Cucumber to ignore scenarios based on your tag, it doesn't know the meaning of your `@ignore` tag.

Not tested:

    cucumberOpts: {
      require: 'cucumber/features/steps/*_steps.js',
      format: 'pretty',
      tags: '~@ignore'
    }

See `cucumber.js --help` for more info.

**Comment by D0rmouse** [comment]
Right, thank you. The way I read it in the readme, it seemed to should be working out of the box...

**Comment by jbpros** [comment]
Ha, which part of the README?

**Comment by D0rmouse** [comment]
OMG haha, silly me. That would be the https://github.com/cucumber/cucumber/wiki/Tags :(
Too many tabs opened I guess. Sorry to have bothered you...

**Comment by jbpros** [comment]
No worries!

**Comment by hbakhtiyor** [comment]
`--tags` option doesn't work for me

```js
    cucumber() {
        return gulp.src("*.js", { read: false })
            .pipe(shell("cucumber.js -r ./build/es5/test/cucumber/steps/CommonStepDefinitions.js --tags ~@skip test/cucumber/features"));
    }
```

also used `-t ~@skip` shortcut,

**Comment by jbpros** [comment]
@hbakhtiyor can you explain how it is not working for you exactly? What do you expect, what happens instead?

**Comment by hbakhtiyor** [comment]
just not skipping the scenarios which i marked `@skip`

also tried the command via terminal, not success
```
bash# cucumber.js -r ./build/es5/test/cucumber/steps/CommonStepDefinitions.js --tags ~@skip test/cucumber/features
```

**Comment by hbakhtiyor** [comment]
e.g. entity.feature

```feature
Feature: [GET /entities] Get list of entities
  # for success
  @skip
  Scenario: Request for all published entities
    Given collection of entities from entity/entities.json data file
    And request "filter" query param's property "published" set to true
    When I request GET /entities
    Then the response status code is 200
    And the response type is JSON
    And the response matches entity/all-entities-published-only.json
```

**Comment by jbpros** [comment]
@hbakhtiyor what's your version of cucumber?

**Comment by hbakhtiyor** [comment]
> cucumber's version: "0.10.2"

**Comment by hbakhtiyor** [comment]
before used `0.9.2` version, `--tags` option didn't work in the version and used the latest version which `0.10.2`, also didn't work too

**Comment by charlierudolph** [comment]
In 0.10, the tag interface [changed](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#0100-2016-04-01). Are you using the new interface?

**Comment by hbakhtiyor** [comment]
i only use tags on `.feature` files

**Comment by charlierudolph** [comment]
Well that is very odd. We don't appear to have any feature tests cases around negated tags, but we are using negated tags in our own tests. Does `--tags @skip` work for you? (running only the scenarios you would skip)

**Comment by hbakhtiyor** [comment]
opposite doesn't work too

**Comment by jbpros** [comment]
@charlierudolph I'm pretty sure we used to have scenarios testing tag exclusion. That must have been lost when we consolidated the test suite. I've just added one.

@hbakhtiyor I can't reproduce the problem. Can you share some code with us?

**Comment by hbakhtiyor** [comment]
np, but why is it depends from code (step definition, hook,..)?

**Comment by jbpros** [comment]
@hbakhtiyor I mean it'd be great to share some gulp/cucumber setup that doesn't work as you expect.

**Comment by hbakhtiyor** [comment]
[the gist link](https://gist.github.com/hbakhtiyor/e5c24db976b5b4a9491f8933ef57beeb)

**Comment by PeterAronZentai** [comment]
~@skip approach isn't working - at least on MacOS.

**Comment by likerRr** [comment]
The same problem I have with `cucumberjs@2.3.1` on ubuntu 16: tags exclusion don't work for me when I run `cucumberjs --tags ~@smth`, but `--tags @smth` works fine. 

Why the issue is closed? Will you @jbpros be able to investigate it more?

**Comment by aslakhellesoy** [comment]
> Why the issue is closed? 
@likerRr this issue is closed because [the explanation](https://github.com/cucumber/cucumber-js/issues/301#issuecomment-73222620) offered by @jbpros 2 years ago was sufficient for @D0rmouse, who closed the issue.

Please create a new ticket if you're facing problems.

**Comment by likerRr** [comment]
Sorry, ok
