### ISSUE TITLE
Cucumber tags for scenario outline examples

### ISSUE THREAD

**Issue by cades** [cucumber/cucumber-js#305]
Thanks everyone contribute to this project, I really appreciate your time and effort.

I need a missing feature in cucumber.js, which is exactly the same as [this SO answer](http://stackoverflow.com/a/18016685/1484674).

Are there anyone interested in this feature?

**Comment by jbpros** [comment]
I think you missed the SO link.

**Comment by cades** [comment]
So embarrassed :P

Question above updated.

**Comment by jbpros** [comment]
Ha-ha! Well spotted, this indeed is a missing feature. 

`s.feature`:

```javascript
Feature:
  Scenario Outline:
    Given <v>

  @a
  Examples:
    | v |
    | 1 |
    | 2 |

  @b
  Examples:
    | v |
    | 3 |
    | 4 |
```

Running it without tags is fine:

```
nerwen:f jbpros$ cucumber.js s.feature 
UUUU

4 scenarios (4 undefined)
4 steps (4 undefined)
```

With tags:

```
nerwen:f jbpros$ cucumber.js -t @a s.feature 


0 scenarios
0 steps
nerwen:f jbpros$ cucumber.js -t @b s.feature 


0 scenarios
0 steps
```

I'd expect 2 scenarios to run in each case.

**Comment by repko-artem** [comment]
This is very useful feature. Our team needs it so much.

**Comment by aslakhellesoy** [comment]
I was bitten by this today during a training.

**Comment by samccone** [comment]
After a bit of investigation

`applyCurrentFeatureTagsToElement`
https://github.com/cucumber/cucumber-js/blob/77ef896ad5ec3f878d9046a00dfaae28b3a8bffe/lib/cucumber/ast/assembler.js#L42-L46

Seems to be only called once, regardless of the number of examples. 

If for instance you tag the `Scenario Outline:` you can run that by a tag filter, however the examples are simply passed in and always run.

This presents an interesting question that need to be resolved before a solution can be put into place

1. If a user tags both an outline and an example with two different tags which takes precedence? when a tag filter is in place? should the example tag always win?

**Comment by stevenknieven** [comment]
would love to use this feature

**Comment by AuneK** [comment]
As many others here, I would aslo like to see this feature working in cucumber-js.

Being relatively new to Cucumber I don't know how this is handled in other implementaions, but here's my €0.02 on how samccone's question could be resolved:

As it doesn't make sense to run the scenario outline without data, specified in the examples, I would say, don't evaluate on the scenario outline level if tests should be run, but let the examples inherit the tags from scenario outline (and it's parents). Then evaluate each example if they should run.

Feature:
  @SO
  Scenario Outline:
    Given <v>

  @a
  Examples:
    | v |
    | 1 |

  @b
  Examples:
    | v |
    | 2 |

So
'-t @SO' would run both examples (and all other tests tagged @SO)
'-t @a'  would run example a (and all other tests tagged @a)
'-t @SO -t @a' would run example a (and all other tests tagged @SO AND @a), but not b

**Comment by matkruse** [comment]
I like @AuneK 's suggestion.

**Comment by eineving** [comment]
This feature would be so usefull as there would not have to be a copies of similar scenarios that only needs different tags

**Comment by deepaksinghvi** [comment]
Yes i agree, it would be very useful.

**Comment by jlin412** [comment]
Also,
abc.feauture:line_number does not work on scenario outline

**Comment by goreny** [comment]
Is it done yet?
