### ISSUE TITLE
npm Node Version Warning on Install

### ISSUE THREAD

**Issue by dschinkel** [cucumber/cucumber-js#307]
Just wondering if this is anything I need to worry about and what exactly this is saying with the version mismatch here.

Note: I'm using io.js if that helps...
![screen shot 2015-02-19 at 10 59 44 pm](https://cloud.githubusercontent.com/assets/338798/6281708/9262388a-b88b-11e4-87e9-6309a38ee9aa.png)

**Comment by samccone** [comment]
yes that would be the issue @dschinkel :)

**Comment by dschinkel** [comment]
What is, that Cucumber.js isn't compatible with io.js?

**Comment by samccone** [comment]
oh that cucumber-js simply has not been run on io.js yet
I see no reason why it would not be compatible, we simply need to update the package.json and update the test suite to test against io

**Comment by dschinkel** [comment]
What does "updating the test suite" specifically involve?

**Comment by dschinkel** [comment]
When can we get this updated then??

**Comment by aslakhellesoy** [comment]
Io.js is fairly new, but I'm sure there's people who are running Cucumber.js on it already. Has anyone experienced any errors? (I'm talking about errors, not warnings).

**Comment by dschinkel** [comment]
Yea sorry, just anxious to get started...:)

**Comment by dschinkel** [comment]
I'm running io.js 1.3 now just for more info...

**Comment by samccone** [comment]
@dschinkel @aslakhellesoy I have fixed the issue, as expected io works just fine

#308

**Comment by dschinkel** [comment]
That is awesome thanks lot for getting to this!!

- Dave

**Comment by dschinkel** [comment]
I ran the same exact command npm install -g cucumber.  Has your change been pushed to the npm registry or whatever?  Is this the command you tested for the fix?

**Comment by samccone** [comment]
it has not been merged, the PR is still open, waiting on @jbpros

**Comment by dschinkel** [comment]
I suppose duh I can just update my own package.json.

**Comment by samccone** [comment]
sure you can point your cucumber_js install at my commit

`npm i cucumber/cucumber-js#0f13417bfecfa0dcbdac16741816bfda84d7d536 --save`

https://docs.npmjs.com/cli/install

**Comment by eduardoinnorway** [comment]
Well the dependency jsdom is io.js only, so you should update your read me, because your getting started tuts don't work anymore with Node.
