### ISSUE TITLE
Support iojs --es_staging flag

### ISSUE THREAD

**Issue by cajoy** [cucumber/cucumber-js#311]
My API/project driven by iojs with --es_staging flag.

So I need to find the way how to run cucumber with --es_staging flag.

As for now I need to do manual modification to ./bin//cucumber-js  file

**Comment by dtinth** [comment]
It's possible to invoke `cucumber-js` manually.

    iojs --es_staging node_modules/.bin/cucumber.js Wow.feature

**Comment by jbpros** [comment]
@cajoy I think @dtinth's response is the answer to your problem? Agreed?
