### ISSUE TITLE
Accessing the step object.

### ISSUE THREAD

**Issue by jwoudenberg** [cucumber/cucumber-js#314]
I was wondering if there is any way to access the test step object from the step implementation or a hook. I'm referring to the object defined [here](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/ast/step.js).

The reason I'm trying to access the step is for logging purposes. I have a couple of common test steps which log what they're doing, which is a terrific help when writing testcases. To structure this log I want each step to log it's line ('Executing step: Given some condition is true'), so I would like to access the steps `.getLine()` method.

I assumed I could use the `beforeStep()` hook for this, similar how you can use `beforeScenario()` to get the scenario object. However, although it gives back a step object as its first argument, it is the step object of the hook itself.

I read in other issues that there is a bit of controversy around the `beforeStep()` hook, but I don't really see any alternatives in this case.

**Comment by jbpros** [comment]
The object you get is an event, not a step. You need to ask it its payload:

```javascript
this.BeforeStep(function (event, cb) {
  console.log('STEP', event.getPayloadItem('step'));
  cb();
});
