### ISSUE TITLE
How Hooks are Wired Up and Naming of Files

### ISSUE THREAD

**Issue by dschinkel** [cucumber/cucumber-js#319]
I am looking at the docs but still something is not clear to me.  

I get how to create hooks and all that but how are the hooks connected to World.  Meaning how does Cucumber look for your hooks file and .Before for example in your hooks.js and do you have to name it hooks.js or does it not matter as long as you have a .Before for a before hook for example?

Is it that because you do a module.exports of your hooks function that somehow Cucumber magically pics up your hooks function and calls it?

Right now it's not calling my hook (console.log("inside Before"); is not logging to the console).  

I'm running Cucumber 0.4.8

support/hooks.js
-----------------------

"use strict";

var phantom = require('phantom');

var beforeHooks = function () {
    this.Before(function(callback) {

        console.log("inside Before");

        phantom.create("--web-security=no", "--ignore-ssl-errors=yes", { port: 12345 }, function (ph) {
            var phantomProcess = ph;

            this.createBrowserPage = function(){

                phantomProcess.createPage(function(page) {
                    console.log("creating page");
                    this.headlessPage = page;
                });
            };
        });
        callback();
    });
};

module.exports = beforeHooks;

/support/world.js
--------------------

"use strict";

var hooks = require('./hooks.js');  // I've seen people set it here and set it to a variable but I have nothing to really call in my hooks so do I need this?

var World = function World(callback) {
    console.log("inside world");
    callback();
};

module.exports.World = World;

support/myStepDefinitions.js
-----------------------------
"use strict";

var viewingEpisodesList = function() {

    this.World = require("../../support/world.js").World;
    this.createBrowserPage;
    console.log("this.headlessPage: " + this.headlessPage);
    var page = this.headlessPage;

    this.Given(/^I visit the customers display page$/, function (callback) {

        console.log("page: " + page);
        page.open("/", function(status){

            status.should.equal("success");
            callback();
        });
    });
};

module.exports = viewingEpisodesList;

**Comment by dschinkel** [comment]
I don't get it.  I had my before_hooks.js in my support folder and after moving it to my features/step_definitions folder it started to finally hit the Before and my hook ran.  The docs are showing the hooks in your examples in your support folder, it shouldn't matter right?  but it did in my case and I'm not sure why.

**Comment by jrust** [comment]
I'm also confused about this.  Not sure if it's because I'm running cucumber with protractor, but the only way I was able to get the hooks to run was by putting them in the step_definitions folder as well.

**Comment by thompsnm** [comment]
@jrust , check your Protractor Config file. From your description, I'm betting your `cucumberOpts.require` array includes all contents of your step_definitions folder, but does not include the folder you previously had your hooks in. If your hooks file wasn't required before then your hooks wouldn't run. @dschinkel , your description sounds like a similar problem, but I don't know what the analogous solution would be if you're just using cucumberjs (I'm using it with Protractor myself). I'd say make sure to require your support folder wherever you're currently requiring your step_definitions folder.

**Comment by jrust** [comment]
@thompsnm thanks for the hint! That fixed the hooks issue and also solved a related issue I had where I had to manually import `world.js` into every step definition.

**Comment by charlierudolph** [comment]
All javascript files are required and if they export a function, that function is called. The README was just updated with a better World example as it doesn't need to be imported into every step definitions file. Please reopen if there are any further questions.
