### ISSUE TITLE
Wait for ajax finished

### ISSUE THREAD

**Issue by xiaoshao** [cucumber/cucumber-js#320]
I use cucumber to make end to end test for my site. But there is some components loaded by ajax in my index.html. So I have to check it until the ajax finished. 
Is there any way to wait the ajax finish and then execute checking.

**Comment by jbpros** [comment]
This is an issue tracking system, not a support forum. Please head over to the [cucumber google group](https://groups.google.com/forum/#!forum/cukes) instead.

Also the issue you're running into is not related to Cucumber but to whatever framework/system you use to automate your web page (Selenium/webdriver, phantomjs, etc.).
