### ISSUE TITLE
Performing multiple actions in one step definition, passes test without executing the step definition completely

### ISSUE THREAD

**Issue by shradds** [cucumber/cucumber-js#323]
I am using protractor and Cucumber  for my tests. 
I have a step definition which looks something like 
var FilterStepDefinitions = function () {
    this.When(/^I filter for the desired set of items from the following controls$/, function (table,callback) {
        var data = table.hashes()[0];
        var filterName = data['Filter'];
        var filterValue = data['Value'];
        var filterPanel= new FilterPanel();
          filterPanel.open(callback);
         filterPanel.findFilter(filterName);
        callback();
    });
   };
and the filterPanel.open is looks something like below:
FilterPanel.prototype.open = function() {
    var page = this;
    this.isOpen().then(function (isOpen) {
        if(!isOpen) {
            page.btnFilter.click()
        }
    });
};

When I run the test using protractor, the console shows that the step is executed but actually they don't get executed or gets executed sometime later.Is there any way to get this work?

**Comment by jlin412** [comment]
you will need to do for last async operation e.g. filterPanel.findFilter(filterName).then(callback);
calling callback() separately with other async calls will end callback without completing other async calls.  In fact, other async call will still execute but just not in sync with cucumber steps.

**Comment by samccone** [comment]
:+1: spot on @jlin412

**Comment by shradds** [comment]
Awesome!! It worked for me
