### ISSUE TITLE
scenario.attach(string) not working

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-js#328]
I couldn't get log text to display with scenario.attach(string);  Below is the my code.  I can get below code to work with an image not text.  When trying to attach text, it is still trying embed an image.
```
  this.After(function (scenario, done) {
    if (scenario.isFailed()) {
      browser.manage().logs().get('browser').then(function (browserLog) {
        if (browserLog.length) {
          console.log('log: ' + JSON.stringify(browserLog));
          scenario.attach(JSON.stringify(browserLog));
        }
      }).then(next);
    }
  });
```

**Comment by jbpros** [comment]
Can you elaborate on "it is still trying to embed an image"? What's the expected output and what do you get?

**Comment by jlin412** [comment]
Though I attach as text, it was interpreted as image in html report.  The expected behavior should be interpreted as text.

**Comment by karthiktv006** [comment]
```javascript
scenario.attach('random text', 'text/plain');
```
Works for me, this bug can be closed.

**Comment by jlin412** [comment]
Yeah, it is working now.  Maybe old html plugin does not support it.  I will close it.

**Comment by Rajazpandi** [comment]
can anyone pls give your entire code to attach screenshot in cucumber report because i'm not able to run the script it showing error like "this.after()  is not a function". below i have attached my hook.ts file

import { browser } from 'protractor/built';
import * as buffer from 'buffer';
import { JsonFormatter } from '../reporting/CucumberReportExtension';
import { defineSupportCode } from 'cucumber'

defineSupportCode(({ registerHandler, registerListener, setDefaultTimeout }) => {
    setDefaultTimeout(120 * 1000);
    registerHandler('BeforeFeature', async () => {
        console.log("Executing before feature !!");
    });

    registerHandler('AfterStep', async () => {
        this.After((scenario, callback) => {
            browser.takeScreenshot().then(stream => {
                let decodedImage = new Buffer(stream.replace(/^data:image\/(png|gif|jpeg);base64,/, ''), 'base64');
                scenario.attach(decodedImage, 'image/png');
                callback();
            }, function (err) {
                callback(err);
            });
        });
        console.log("Step executed");
    });

    registerHandler('AfterScenario', async () => {
        console.log("Scenario executed !!");
    });
    registerHandler('AfterFeature', async () => {
        console.log("Executing After feature !!");
    });
    registerListener(JsonFormatter);
});

**Comment by stevenraines** [comment]
@jlin412 I am experiencing the same issue you cited. You mentioned updating the html plug-in. What did you update it to?
<img width="543" alt="screen shot 2018-05-11 at 7 06 37 am" src="https://user-images.githubusercontent.com/2109987/39921739-03eccf8a-54ea-11e8-875c-56b49e11c7d1.png">
