### ISSUE TITLE
No compatible version found: JSONStream@'>=1.0.3-0 <2.0.0-0'

### ISSUE THREAD

**Issue by stefankutko** [cucumber/cucumber-js#330]
I can't figure out what dependency is requiring, but npm's version of JSONStream goes up to 0.10.0.  Any ideas?

npm ERR! notarget No compatible version found: JSONStream@'>=1.0.3-0 <2.0.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.7.0","0.7.1","0.8.0","0.7.2","0.7.3","0.7.4","0.8.1","0.8.2","0.8.3","0.8.4","0.9.0","0.10.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cucumber"
npm ERR! cwd /Users/stefankutko/electronifie/test-suite
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR! not ok code 0

**Comment by davemorrissey** [comment]
I'm also seeing this problem, only on OS X. On Centos and Ubuntu there's no problem. The first version of cucumber to have this problem is 0.4.4. Version 0.4.3 installs with no issues. I'm guessing it's caused by one of the dependencies but I'm not sure which.

**Comment by davemorrissey** [comment]
Following the chain of dependencies and bug reports led me to upgrade browserify to 10.1.3 and that seems to have solved the problem.

https://github.com/substack/deps-sort/issues/7
https://github.com/substack/node-browserify/pull/1247

**Comment by samccone** [comment]
yep this has been "resolved" upstream

https://github.com/dominictarr/JSONStream/issues/68
https://github.com/dominictarr/JSONStream/issues/68#issuecomment-99998749
