### ISSUE TITLE
Fail with clear error message if callbacks are called more than once

### ISSUE THREAD

**Issue by kevgo** [cucumber/cucumber-js#331]
__Problem:__ if a step calls `callback` multiple times, it is listed multiple times in the output, and the subsequent steps exit prematurely or fail. Although this is a user error, this mistake is so common that it makes cucumber.js feel brittle. 

__Solution:__ Fail with a clear error message "callback from step 'foo' was called multiple times" if a particular callback is called more than once. 

__How to reproduce__
* create two steps that do something asynchronously, like for example

  ```javascript
    this.Given(/^I have a file$/, (callback) ->
      createFile(function() {
        callback();
      });
      callback();
    );

    this.When(/^I delete that file$/, (callback) ->
      deleteFile(callback);
    );
  ```

* run these steps consecutively
  ```cucumber
  Given I have a file
  When I delete that file
  ```

__Expected result:__ the step `Given I have a file` fails with an error message telling me that I called the callback twice

__Actual result:__ the step `Given I have a file` is displayed twice in the output of Cucumber.js, and step "When I delete that file" doesn't wait until it is done.

**Comment by Sanjo** [comment]
This should also handle the case where you return a promise and call a callback. Happens to CoffeeScript users that use WebDriver.io. WebDriver.io commands return promises.

**Comment by jbpros** [comment]
Extra calls to callbacks are now ignored and not reported. I'm fine with this approach for now.
