### ISSUE TITLE
Make cucumber support a separate project

### ISSUE THREAD

**Issue by juliemr** [cucumber/cucumber-js#338]
Cucumber support has been sketchy and community-driven for a while. See the disclaimer at http://angular.github.io/protractor/#/frameworks#using-cucumber

Now that a custom framework can be used, we should just make it a separate project to clarify this separation, and unblock protractor releases when weird things are going on with cucumber.

**Comment by juliemr** [comment]
Ugh, wrong project.

**Comment by mattwynne** [comment]
Hey @juliemr! If there's anything we can do to help let us know.
