### ISSUE TITLE
Reusing different backgrounds

### ISSUE THREAD

**Issue by inf3rno** [cucumber/cucumber-js#339]
I am currently learning cucumber and I was checking some examples here: https://github.com/webjam/webjam/tree/master/features

Most of the scenarios contains

```cucumber
Given I am not logged in
```
or
```cucumber
Given I am logged in
```
so this is a clearly reusable part of the features.

According to the documentation it should be moved to a Background e.g. by https://github.com/webjam/webjam/blob/master/features/home.feature
```cucumber
Feature: Viewing the home page

  In order to see all the cool stuff
  I should be able to visit the home page

  Background:
    Given I am not logged in
  
  Scenario: not logged in
    When I view the home page
    Then I see the page

  Scenario: viewing / on a mobile
    When I view the home page from an iphone
    Then I am redirected to the mobile page
    
  Scenario: viewing / on a mobile with redirect-to-mobile=no
    When I view the home page from an iphone specifying redirect-to-mobile=no
    Then I am not redirected to the mobile page
    And I see the page

  Scenario: viewing the mobile version with an upcoming event, a past event and a post
    Given there is an upcoming event
      And there is a past event
      And there is a post
    When I view the mobile version of the home page
    Then I see the page

  Scenario: viewing the mobile version without any events or posts
    When I view the mobile version of the home page
    Then I see the page
```

The problem that sometimes not every scenario have the same background in a feature. So some of them need a logged in state, while some of the need a not logged in state. Afaik. there is no support to reuse such code. Probably split into multiple features, but I thought it would be better to use groups:

```cucumber
Feature: Viewing post pages

  In order to absorb Lachlan's deep insights into man and machine
  I should be able to visit pages and pages and pages of blog posts
  
  Group:
    Background:
      Given I am logged in
	  
    Scenario: viewing a post when logged in
      When I view the post page
      Then I see the page
	  
    Scenario: viewing a mobile post when logged in
      When I view the mobile post page
      Then I see the page
  
    Scenario: viewing a mobile post when not logged in
      When I view the mobile post page
      Then I see the page
	  

  Group:
    Background:
      Given I am not logged in
  
    Scenario: viewing a post when not logged in
      When I view the post page
      Then I see the page
```

By some of the cases this hierarchical grouping won't work, so this is not a perfect solution. Tagging would be perfect, but I am unsure whether I should use it in this cases. Any opinion?

Another possible solution to match the "when not logged in" part from the scenario text using a helper that adds the `Given I am not logged in`. So the code would be such simple:

```cucumber
Feature: Viewing post pages

  In order to absorb Lachlan's deep insights into man and machine
  I should be able to visit pages and pages and pages of blog posts

    Scenario: viewing a post when logged in
      When I view the post page
      Then I see the page
	  
    Scenario: viewing a mobile post when logged in
      When I view the mobile post page
      Then I see the page
  
    Scenario: viewing a mobile post when not logged in
      When I view the mobile post page
      Then I see the page
  
    Scenario: viewing a post when not logged in
      When I view the post page
      Then I see the page
```

I am not sure whether this is possible by the current test runner.

**Comment by jbpros** [comment]
This should be discussed on [cucumber/gherkin3](https://github.com/cucumber/gherkin3) instead.

I haven't put much thought in it but the `Group:` keyword is interesting and deserves some thoughts. Matching the scenario name seem too error-prone to me (but you can achieve that in a before hook in your own suite).

@inf3rno Can you reopen this on the gherkin3 repo please?
