### ISSUE TITLE
Reusing gherkin code with different step definitions

### ISSUE THREAD

**Issue by inf3rno** [cucumber/cucumber-js#340]
As you can see if the gherkin code is abstract enough, you can reuse it by testing the same behavior from different aspects. 

gherkin for changing password
```cucumber
Feature User
	Scenario change password
		Given I am a registered customer
		When I change the old password to the new password
		Then I can login with the new password
			But I cannot login with the old password any longer
```

step definitions on plain english

e2e tests with selenium for desktop browser
```
	I am a registered customer
		-> email = customer@example.com
		-> oldPassword = example
	I change the old password to the new password
		-> visit login page
		-> fill in credentials
		-> click on the login button
		-> must be redirected to profile page
		-> click on the change password link
		-> fill in old and new passwords to the form
		-> click on the change button
	I can login with the new password
		-> click on logout button if logged in
		-> visit login page
		-> fill in credentials
		-> click on the login button
		-> must be redirected to profile page
	I cannot login with the old password any longer
		-> click on logout button if logged in
		-> visit login page
		-> fill in credentials
		-> click on the login button
		-> must be redirected to the login page
		-> the login page must contain invalid email or password message
```

integration tests probably with mocked out database
```
	I am a registered customer
		-> email = customer@example.com
		-> oldPassword = example
	I change the old password to the new password
		-> newPassword = 12345
		-> UserRepository.findByEmail(email).changePassword(oldPassword, newPassword)
	I can login with the new password
		-> Security.authenticate(email, newPassword) -> must succeed
	I cannot login with the old password any longer
		-> Security.authenticate(email, newPassword) -> must fail
```

probably you can write other step definitions for mobile browser, for desktop client using websockets, for the data access layer if you have such a thing, etc...

Is this supported somehow by cucumber-js?

**Comment by jbpros** [comment]
This looks more like a support discussion than an issue, please use the [cukes group](https://groups.google.com/forum/#!forum/cukes) instead, next time.

That's a good way of writing scenarios, imo.

What I recommend is to push down the step implementation down into so-called [World](https://github.com/cucumber/cucumber-js#world) methods:

```javascript
function MobileWorld(callback) {
  this.registerMeAsCustomer = function () {
    // Mobile implementation of that behaviour
  };
}

function SeleniumWorld(callback) {
  this.registerMeAsCustomer = function () {
    // Selenium implementation of that behaviour
  };
}

// then based on configuration/environment vars:
this.World = MobileWorld;
// or
this.World = SeleniumWorld;

this.Given(/I am a registered customer/, function (callback) {
  this.registerMeAsCustomer();
  callback();
});
```

**Comment by inf3rno** [comment]
@jbpros Thanks!

**Comment by Virgomax** [comment]
In case you are using Javascript, I've created a package named [reuse-cucumber-scenarios](https://www.npmjs.com/package/reuse-cucumber-scenarios) for calling a scenario by doing:

```gherkin
Given the scenario "scenario_tag"
```
```gherkin
Given the scenario "scenario_tag" with parameters
"""
{
  "1": ["step1_param1", "step1_param2"],
  "2": ["step2_param1", "step2_param2", "step2_param3"],
  "3": ["step3_param1", "step3_param2", "step3_param3"],
}
"""
```

```gherkin
Given the variable "$variable_name" is equal to
"""
#JSON object
"""
```
```gherkin
Given the scenario "@$scenario_function_tag" where variable "$variable_name" is "value_to_replace"
```

and more...

**Comment by mattwynne** [comment]
@Virgomax I am going to try and not be a grumpy old man who's seen it all before and stay curious 🐱 

Can you tell me what specific use-cases motivated you to build this?

**Comment by Virgomax** [comment]
Hi @mattwynne !

Thanks for your interest in trying the library. It is new though, but I think that with time I'll improve it and make it grow. 
 
## The common use-case
What motivated me to build [reuse-cucumber-scenarios](https://www.npmjs.com/package/reuse-cucumber-scenarios) library was my desire to simply write:

```gherkin
Given the scenario "@scenario_tag"
```
... without the need to write a new step definition for the composite step as suggested [here](https://github.com/cucumber/cucumber-js/issues/473#issuecomment-165224938).

## The specific use-case
I'm developing a web app where many users interact in real time (like in a multiplayer game). 
So I wanted to use gherkin as a higher-level programming language (compared to javascript together with cucumber and my selenium framework), I wanted to keep it DRY, something like:

```gherkin
Feature: Many users log in and do more stuff later...

#Number of users as a variable (easy to change, only in this place) (This does not run, it's only a variable definition)
@set_numUsers
  Scenario: Set the global variable numUsers
    Given the variable "$numUsers" is equal to "3"

#Data of all users neatly defined(This does not run, it's only a variable definition)
@set_usersList
  Scenario: Set the global variable $usersList
    Given the variable "$usersList" is equal to
    """
    {
      "1":{
        "signupData":"dataEntry1_2",
        "loginData":"dataEntry1_1"
      },
      "2":{
        "signupData":"dataEntry2_1",
        "loginData":"dataEntry2_2"
      },
      "3":{
        "signupData":"dataEntry3_1",
        "loginData":"dataEntry3_2"
      }
    }
    """

#Defining a scenario function that uses the data (This does not run, it's only a function definition)
#     function @$login($userId){ }
@$login
 Scenario: Login
    Given the user "$userId" is on "IndexPage" page
    When the user "$userId" fills out "form2" using "$usersList[$userId].loginData"
    And the user "$userId" clicks on "submit2"
    Then the user "$userId" should be redirected to "HomePage"

#other scenario function that uses the data (This does not run, it's only a function definition)
#     function @$create_account($userId){ }
@$create_account
 Scenario: Create an account
    Given the user "$userId" is on "IndexPage" page
    When the user "$userId" fills out "form1" using "$usersList[$userId].signupData"
    And the user "$userId" clicks on "submit1"
    Then the user "$userId" should be redirected to "HomePage"

#Now we can use the scenario function and variables in this scenario (This does run.)
@login_multiple_users
  Scenario: Many people logs in
    Given there are "$numUsers" users
    And the scenario "@$login" for variable "$userId" from "1" to "$numUsers"
    #More steps here.

 #More scenarios here.
```
By doing this I don't need to care about combining multiple steps in cucumber.  

For developers, the fewer steps definitions you have, the easier to maintain the code.
For people without technical knowledge, I could manage to generate a text file where you have the composite steps(steps that call scenarios) expanded in their basic steps. That's my next task to improve the library.

**Comment by Virgomax** [comment]
I think readability won't be a problem once I improve the library to generate a text file with the composite step expanded in their basic steps. This is how it would look the text file generated from the example I mentioned in my previous comment.
```gherkin
Feature: Many users log in and do more stuff later...

@login_multiple_users
Scenario: Many people logs in
    Given there are "3" users
    And the Scenario: Login:
        Given the user "1" is on "IndexPage" page 
        When the user "1" fills out "form2" using "dataEntry1_1" 
        And the user "1" clicks on "submit2" 
        Then the user "1" should be redirected to "HomePage"
    And the Scenario: Login:
        Given the user "2" is on "IndexPage" page 
        When the user "2" fills out "form2" using "dataEntry2_2" 
        And the user "2" clicks on "submit2" 
        Then the user "2" should be redirected to "HomePage"
    And the Scenario: Login:
        Given the user "3" is on "IndexPage" page 
        When the user "3" fills out "form2" using "dataEntry3_2" 
        And the user "3" clicks on "submit2" 
        Then the user "3" should be redirected to "HomePage"
    #More steps here.

#More scenarios here.
```

This generated text file would be the one that is presented to the non-technical people. So developers don't need to repeat N times the same code in gherkin and non-technical people get what they need to understand the sequence. 

Thanks for your patience at reading this and giving your feedback which is always welcome.

**Comment by mattwynne** [comment]
A little bit of context I thought I'd share is that, a very long time ago, we had this feature in Cucumber, but we decided to remove it:

http://blog.josephwilk.net/ruby/cucumber-waves-goodbye-to-givenscenario.html

Thanks @josephwilk for writing that one up for posterity.
