### ISSUE TITLE
World is undefined in After hook?

### ISSUE THREAD

**Issue by bigattichouse** [cucumber/cucumber-js#341]
After upgrading recently to the most recent version of cucumber.js I noticed that the test was hanging even though it succeeded (all tests pass).  I'm using zombie within the world file similarly to the cucumber examples.

The eventual error:
Cucumber process timed out after waiting 60 seconds for the node.js event loop to empty.  There may be a resource leak.  Have all resources like database connections and network connections been closed properly?

So, I thought - well, I'll just stick an After hook to close the browser:

this.After(function(callback) {
    this.browser.close();
    callback();
  });

which fails ?!?

TypeError: undefined is not a function

BUT ... if I include the same call in the final step of my scenario - it works

this.Then(/^the user can see correct values in the output$/, function (callback) {
         //assertions go here
          this.browser.close();
          callback();
});

Then my tests pass, everything is fine, and execution completes normally

Am I missing something?

**Comment by jbpros** [comment]
I can't reproduce this. Can you share some more code to demonstrate this problem?

**Comment by bigattichouse** [comment]
I'll put together something to simulate it, thanks.

Mike

**Comment by charlierudolph** [comment]
@bigattichouse any update on this or can this be closed?

**Comment by bigattichouse** [comment]
One of the previous updates seems to have fixed it. I think it was due to a
resource being left open - particularly if you have more than one browser
(zombiejs) open, and don't explicity call close() first.

So, please. close.

**Comment by devinbhullar** [comment]
TypeError: this.After is not a function
