### ISSUE TITLE
Use Gherkin4

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#343]
Use [cucumber/gherkin3](https://github.com/cucumber/gherkin3) instead of [cucumber/gherkin](https://github.com/cucumber/gherkin).

**Comment by aslakhellesoy** [comment]
Hey @charlierudolph @jbpros - I've made some headway with a JS implementation of the compiler on the `test-case-compiler-take-2` branch in Gherkin3:

* https://github.com/cucumber/gherkin3/blob/test-case-compiler-take-2/javascript/lib/gherkin/compiler.js
* https://github.com/cucumber/gherkin3/tree/test-case-compiler-take-2/testdata/good (look at `*.testcase.json` files) 

/cc @tooky @mattwynne @brasmusson does this look like a design that would work with cucumber-ruby as well?

**Comment by charlierudolph** [comment]
Closed in a5fd8251918c278ab2e389226d165cedb44df14a
