### ISSUE TITLE
Multiple bindings for the same step

### ISSUE THREAD

**Issue by zs-zs** [cucumber/cucumber-js#346]
When I write Gherkins I'd like to use different phrasing for Given and When steps.

Let's see an example to demonstrate this use case:

    Given the document '1.pdf' has already been converted
    When I convert the document '2.pdf'

Both steps use the same step definition, just the phrasing (the regex pattern) is different.
Currently CucumberJS doesn't support this out of the box: you have to extract your step definition as a function every time you want to write a step with an alternative phrasing.

I suggest a nicer solution which is easy to implement:

    this.When([/^the document '(.*)' has already been converted$/,
                /^I convert the document '(.*)'$/], function (documentName, callback) {
              // ...
    });

If you want to try it out, I've already implemented a feature in my [cucumber-sweetener](https://github.com/zs-zs/cucumber-sweetener) project. (It's just not documented yet.)

**Comment by mattwynne** [comment]
I'd like this in Cucumber-Ruby too.

**Comment by zs-zs** [comment]
[SpecFlow](https://github.com/techtalk/SpecFlow/) supports this out of the box. If you use .NET, try it out, it's cool. :)

**Comment by jbpros** [comment]
@zs-zs this would be a nice addition! PR welcome :)

**Comment by dmeehan1968** [comment]
Any reason not to:

```
this.When(/^(?:the document '(.*)' has already been converted|I convert the document '(.*)')$/, function (documentName, callback) {
          // ...
});
```

Granted, slightly less readable, but functionally the same.

**Comment by charlierudolph** [comment]
The common logic can easily be extracted into another function. If they are exactly the same you can simply do the following:
```js
stepDefintions = function () {
  var convertDocument = function (document, callback) {
    // ...
  };

  this.Given(/^the document '(.*)' has already been converted$/, convertDocument);
  this.When(/^I convert the document '(.*)'$/, convertDocument);
}

module.exports = stepDefintions
```
Even if they aren't exactly the same the common logic can always just be extracted into a help function that each step definition call.s

**Comment by charlierudolph** [comment]
Closing. @zs-zs please reopen if you would like to discuss this further
