### ISSUE TITLE
Steps with no arguments will fail in v0.5.0

### ISSUE THREAD

**Issue by zs-zs** [cucumber/cucumber-js#347]
Hi guys,

I've just realized that the way you implemented promise support in v.0.5.0 will cause steps with no arguments fail.
So I cannot write steps like this anymore:

    When('..pattern...', function() {
        var firstArg = arguments[0];
        ....
    });

You make a check for code.length, the length of the argument list of the "code" function:

    +        if (code.length === parameters.length - 1 && result.then !== void 0) {
    +          result.then(onPromiseFulfilled, onPromiseRejected);
    +        }

I would just check for the existence of the then function instead. It would be enough in most cases.

The biggest disadvantage of the current solution is that it prevents the implementation of generic step definition APIs based on Cucumber-js. (like my small lib [cucumber-sweetener](https://github.com/zs-zs/cucumber-sweetener))

**Comment by jlin412** [comment]
make a PR?

**Comment by zs-zs** [comment]
Yeah, I will do it.

**Comment by jbpros** [comment]
I was aware of this when merging the PR but wanted to see if there were real use cases with step definitions with less than p-1 params. You just gave me one. I'll be happy to merge a PR to relax the callback check.

**Comment by jbpros** [comment]
Closed by b138589
