### ISSUE TITLE
Running a single scenario

### ISSUE THREAD

**Issue by zs-zs** [cucumber/cucumber-js#349]
Hi,

Maybe there is already some solution for doing this properly. Here is my use case: currently I'm using cucumber-js for automated smoke tests/end-to-end tests. These scenarios are not fast, it takes some minutes to execute all of them in a small project. When I'm starting to develop a new feature, I'd like to write some (failing) Cucumber scenarios and during the development, I'd like to run only some of them to check my implementation. 
Currently I'm using tags to achieve this behavior: I have a tag like "@inProgress" and have a Grunt task to run my scenarios marked with inProgress. This is a bit cumbersome, since I have to mark every scenarios with this tag and after my implementation task is done, I have to revert my changes manually because I don't want to commit them to Git. 
I see that you already have some plan to implement suites, maybe that feature would resolve this problem? 

Before I saw the suites issue I was just thinking about that we can expose the names of the scenarios to be executed to the CLI and make the scenarios to be "discoverable" for other tools. So I can write my own Cucumber-js test runner, which could display my scenarios on a nice UI where I can select which tests do I want to execute and I can execute them.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) channels for questions and discussions. This is a bug tracker.
