### ISSUE TITLE
Contribution readme is not applicable to Windows

### ISSUE THREAD

**Issue by zs-zs** [cucumber/cucumber-js#350]
Hi,

I'm trying to contribute some code but I have some problems with following the steps written in the readme file about contributing.
When you run `npm test` it executes the following:

      jshint bundler.js bin lib spec && jasmine-node spec && bin/cucumber.js -f progress -i

The problem with this is that the command `bin/cucumber.js` will work only from Linux/Unix. As far as I know Windows doesn't support shebangs.

So I would make another option to run the tests under Windows with the "Windows-version" of the command:

      jshint bundler.js bin lib spec && jasmine-node spec && node bin/cucumber.js -f progress -i

...assuming that node.js executable is on PATH.

I also don't know that these end-to-end cucumber scenarios are supposed to be passing or not. Currently I have 18 failing scenarios when I run the tests with the "Windows-version" of the command. This is strange because I haven't modified anything yet.

Maybe this is due to the environment problem?
Are the scenarios passing under Linux?

**Comment by jbpros** [comment]
Closed by 09964a1.
