### ISSUE TITLE
How do I get a reference to StatsJournal?

### ISSUE THREAD

**Issue by jhoguet** [cucumber/cucumber-js#355]
I am trying to get the failed count after all features and it seems like the [StatsJournal](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/listener/stats_journal.js#L189) is the thing to get me the count 

```js
module.exports = function(){
    this.registerHandler('AfterFeatures', function (event, callback) {
        var journal = ??
        var failedCount = journal.getFailedStepCount();
        callback();
    });
};
```

but I am struggling to figure out how to get the reference to the journal? 

thoughts?

**Comment by jhoguet** [comment]
I found a way... 

```js
var cucumber = require('cucumber'),
    journal = cucumber.Listener.StatsJournal();

module.exports = function(){
    this.addListener(journal);

    this.registerHandler('AfterFeatures', function (event, callback) {
        var failedCount = journal.getFailedStepCount();
        callback();
    });
};
```

I was expecting to be able to get a reference to the existing journal, but this is just as good.

**Comment by jbpros** [comment]
This is the way to go :) Just register as many listeners as you need, they're cheap.
