### ISSUE TITLE
Failing to run step with a Mongoose Call

### ISSUE THREAD

**Issue by chris31389** [cucumber/cucumber-js#356]
I'm setting up a background task, generating the step for it and changing the callback.pending() to callback() which passes.

```
    this.Given(/^that I have an empty person collection$/, function (callback) {
        callback();
    });
```

I add a require statement to my mongoose schema and then wrap the callback in this:

```
    var Product = require("../models/product);
    this.Given(/^that I have an empty person collection$/, function (callback) {
        Product.remove(function(err){
            callback();
        });
    });
```

this is the product.js file
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var ProductSchema = new Schema({
    name: String,
    price: String,
    description: String
});

module.exports = mongoose.model('Product', ProductSchema);
```
And when I run cucumber-js is just terminates.
When I go back and remove the remove function, it runs fine again.

I've even tried running it like this:
```
    this.Given(/^that I have an empty person collection$/, function (callback) {
        Product.remove().exec(callback);
    });
```

Any ideas what is causing this behaviour?

**Comment by dmeehan1968** [comment]
I would suspect that the completion function is not called, you could verify by putting some log output in there.  

```
Product.remove(function(err) {
  console.log('done', err);
  callback();
});
```

**Comment by jbpros** [comment]
Make sure the function you pass to `Product.remove()` is actually called. 

Note this is a support request and you're on a issue tracker here. Please use the [cukes group](https://groups.google.com/forum/#!forum/cukes) next time.
