### ISSUE TITLE
Merge/release policy for pull requests

### ISSUE THREAD

**Issue by dmeehan1968** [cucumber/cucumber-js#362]
Can one of the maintainers comment on what the merge/release policy is for pull requests. There seem to be a large number of passing PRs that could be merged.  Could at least the tags be updated to reflect which milestone they will be targeted at?

**Comment by jbpros** [comment]
Thanks for asking. I tidied the PRs, some were merged, the others are all assigned to milestones. I've set up a [waffle.io board](https://waffle.io/cucumber/cucumber-js) to make priorities clearer. I'm still sorting things out on it.
