### ISSUE TITLE
README World.js examples do not appear to work

### ISSUE THREAD

**Issue by renegare** [cucumber/cucumber-js#369]
As a new user of cucumber-js following the README example to setup World.js does not appear to work.

**Comment by jbpros** [comment]
Can you elaborate? What do you expect? What result/error do you get instead?

**Comment by renegare** [comment]
1. Both "world" examples have a syntax error, extra ```}``` (source: http://www.jslint.com/)
2. after fixing the syntax error and simplifying the code to:

```
function World(callback) {
    this.data = true;

    callback(); // tell Cucumber we're finished and to use 'this' as the world instance
}

module.exports.World = World;
```

I get the following stack trace:

```
$ ./node_modules/.bin/cucumber-js tests/features/

>>> OUTPUT START:

Feature: Health Check
  As a developer I would like a heathcheck endpoint
  so I can determine if the application is reachable

./node_modules/cucumber/lib/cucumber/support_code/library.js:109
      var world = new WorldConstructor(function (explicitWorld) {
                  ^
TypeError: object is not a function
  at Object.<anonymous> (./node_modules/cucumber/bin/cucumber.js:4:5)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

```
node: v0.12.6
os: macosx
```

**Comment by renegare** [comment]
I am confident the lib works, as a friend of mine has just managed to get it to work.

It would be nice if the README worked?

**Comment by sankargorthi** [comment]
Me too on this one.

    node: 0.12.7
    npm: 3.1.2
    os: maxosx

This is my code:

    // features/step_definitions/support/world.js
    var zombie = require('zombie');
    
    function World(callback) {
      this.browser = new zombie(); // this.browser will be available in step definitions
    
      this.visit = function (url, callback) {
        this.browser.visit(url, callback);
      };
    
      callback(); // tell Cucumber we're finished and to use 'this' as the world instance
    };
    
    module.exports.World = World;

and the step definitions:

    //features/step_definitions/basic.js
    module.exports = function () {
      this.World = require('../support/world');
    
      this.Given(/^I am managing users$/, function (callback) {
        this.visit('http://localhost:3000/users', callback);
      });
    
      this.Then(/^I should see a list of users$/, function (callback) {
        // Write code here that turns the phrase above into concrete actions
        var pageTitle = this.browser.text('title');
        if (title !== 'Users'){
          callback.fail('Wrong page');
        }
    
        callback.pending();
      });
    };


ran this with:

    $ node  --harmony ./node_modules/.bin/cucumber-js
    
    Feature: This should test out how scenarios and features will be tested
    
    
    /Users/sgorthi/.nvm/versions/node/v0.12.7/lib/node_modules/cucumber/lib/cucumber/support_code/library.js:109
          var world = new WorldConstructor(function (explicitWorld) {
                      ^
    TypeError: object is not a function
      at Object.<anonymous>     (/Users/sgorthi/.nvm/versions/node/v0.12.7/lib/node_modules/cucumber/bin/cucumber.js:4:5)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Function.Module.runMain (module.js:501:10)
      at startup (node.js:129:16)
      at node.js:814:3

**Comment by JamieKnight** [comment]
Hello, install instructions is not working for me either.

**Comment by charlierudolph** [comment]
@sankargorthi

The step definitions file needs to be
```diff
-  this.World = require('../support/world');
+  this.World = require('../support/world').World;
```
as it is in the README.

What I typically do instead is have the world file have the following content and remove the reference in the step definitions file.
```js
function World(callback) {
    this.data = true;

    callback(); // tell Cucumber we're finished and to use 'this' as the world instance
}

module.exports = function() {
  this.World = World;
}
```

@jbpros how do you feel about updating the README to that?

**Comment by sankargorthi** [comment]
@charlierudolph d'oh. Thanks!

**Comment by jbpros** [comment]
@charlierudolph yep, I like it better. Do it! :)
