### ISSUE TITLE
Error in parser.js when setting new prototype function for Array

### ISSUE THREAD

**Issue by lutzj82** [cucumber/cucumber-js#372]
I am using gulp-param within my gulpFile to assist with passing arguments. gulp-param adds a function to the Array prototype. This causes an issue in the parser.parse function as the for loop for featureSources is doing an iteration of the object, not the array.  There should be a check for hasOwnProperty within that loop.  As it stands now, in my gulpFile I have to delete the prototype definition.

**Comment by charlierudolph** [comment]
Fixed in 7474a2108f59d8e54622e8e7c6ae5fb67c392edb
