### ISSUE TITLE
Summary of failing scenarios shows the line number twice

### ISSUE THREAD

**Issue by karthiktv006** [cucumber/cucumber-js#376]
When line number of scenario is mentioned while running cucumber, the summary formatter generates the failed scenarios and the line number is shown twice.

Command to regenerate:
>node bin/cucumber.js features/cli.feature:6

Failing scenarios:
<p>/Users/viswankb/Project/cucumber-js-github/features/cli.feature:<b>6:6</b> # Scenario: run a single feature</p>

**Comment by jbpros** [comment]
Fixed by b964172
