### ISSUE TITLE
What is the proper way to fail from BeforeFeatures?

### ISSUE THREAD

**Issue by jhoguet** [cucumber/cucumber-js#378]
I have some "world" files that I use to stand up chromedriver and wdjs, both of which might fail... 

```js
this.registerHandler('BeforeFeatures', function(event, callback){
        q.when()
            .then(function(){
                return startBrowser(options)
                    .then(function(_browser){
                        browser = _browser;
                    });
            })
            .then(callback, function(error){
                console.log('failed to start selenium client');
                console.trace(error);
                process.exit(1)
            });
});
```

is there a better way to fail than `process.exit(1)`? 

I was hoping for something like callback.fail... but in this case the callback appears to be just a wrapper around iterate(). So if I call `callback()` then it moves on as if success, which is not desired. 

thanks for your hard work on cucumberjs - its been a pleasure working with it.

**Comment by charlierudolph** [comment]
`registerHandler` doesn't check if an error is returned. Its a hook into the runtime and is very different from step definitions and other hooks.

**Comment by jhoguet** [comment]
@charlierudolph thanks for the reply

Is there a better hook for doing something once  that might fail (better than BeforeFeatures)? If not, is there a better way of telling the runtime that I am not in a good state (better than process.exit)?

**Comment by charlierudolph** [comment]
I'd suggest just using a before hook and only start the browser if `_browser` is not defined. Be aware that at the moment, hooks do not support promises. See #401.

**Comment by jhoguet** [comment]
that should work - thanks for the help
