### ISSUE TITLE
test with async

### ISSUE THREAD

**Issue by zoraShi** [cucumber/cucumber-js#379]
```javascript
this.Then(/^show$/, function (callback) {
        var res = {};
        res.send = function (data) {
            if (data && data.ordering === 1 && 
                data.observationPoint === req.body.observationPoint) {

                callback();
            } else {
                callback.fail(new Error('err'));
            }
        };
        save(req, res);
    });
```

save(req, res)  is a async function of mongoose;
test it,cucumber-js is not finished,i must wait 60s,and see below
Cucumber process timed out after waiting 60 seconds for the node.js event loop t
o empty.  There may be a resource leak.  Have all resources like database connec
tions and network connections been closed properly?

thanks for your hard work on cucumberjs - its been a pleasure working with it.

**Comment by charlierudolph** [comment]
Not much more then that error message can really be said. 
Apparently some node process is still in the event loop. 

Waiting for the event loop to empty was removed 0.5.2 if you can upgrade.

**Comment by charlierudolph** [comment]
Closing as related to old behavior. Please reopen if this doesn't work as expected on 0.5.2 or later.
