### ISSUE TITLE
No access to world in before and after events

### ISSUE THREAD

**Issue by xcompass** [cucumber/cucumber-js#380]
It seems there is no access to world in before and after events. Well, in the readme, it says no access to world in after features, which make sense. However, I would like to access world in AfterStep. Is there any way to do it? 

And also is there a way to use tags in Before/AfterStep like the ones in this.Before/this.After? Thanks.

**Comment by charlierudolph** [comment]
So `registerListener` is hooked into the abstract tree walker and I believe was only exposed in order to facilitate multiple formatters (see #91). Thus `registerListener` should not be used for anything related to actually running the features. Thus similarly you tags cannot be used with it.
