### ISSUE TITLE
Format chai.js exceptions so to display a better diff

### ISSUE THREAD

**Issue by vcarel** [cucumber/cucumber-js#386]
I'm using [chai.js](https://github.com/chaijs/chai) to make assertions. Unfortunately, when I compare arrays, I have a poor result because Cucumber doesn't format Chai exceptions like other test runners such as [mocha.js](https://github.com/mochajs/mocha/blob/58e94445beb722372589cbd2a0372bf741e7f0b7/lib/reporters/base.js#L193) or [wallaby.js](https://github.com/wallabyjs/public/issues/186#issuecomment-120564448).

For instance, when I compare two big arrays:

```
actual_content.should.deep.equal(expected_content);
```

I get:

```
  AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
    at Assertion.assertEqual (/my_project/node_modules/chai/lib/chai/core/assertions.js:464:19)
    at Assertion.ctx.(anonymous function) [as equal] (/my_project/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
    ...
```

Mocha, in this case would produce something like:

```
  AssertionError: expected [ 1, 2 ] to equal [ 3, 4 ]
  + expected - actual

   [
  -  1
  -  2
  +  3
  +  4
   ]

  at Context.<anonymous> (client/test/test_misc.js:20:27)
```

To be honest, this is annoying for big arrays only, because otherwise Chai produce a better exception message; see issue https://github.com/chaijs/chai/issues/469.

**Comment by jbpros** [comment]
This is an annoying on-purpose issue in Chai. They decided to go for a flexible "DYI" solution with "nice short messages" by default but in the end it makes it pretty cumbersome to output complete error messages. It is particularly difficult to reconstruct the error message with the full array data in it.

#421 is an experimental approach to fix this.

**Comment by kieranbop** [comment]
hey @charlierudolph , I'm still seeing the same issue as linked above ^^
`expected [ Array(9) ] to deeply equal [ Array(9) ]`
I've looked through the release you did years back and I can't see anything that would show the diff of two arrays in this case in the output?

**Comment by charlierudolph** [comment]
Where exactly are you seeing that message? Most formatters (aside from json / event protocol) should be giving an error message with a diff

**Comment by kieranbop** [comment]
I'm seeing it within my cucumber report, or if I wrap the expect in a catch and log out that result.

my step definition function is as follows:
```
        function() {
            return this.getCurrentPage().getxxxData().getComparisonData()
                .then(expectedText => {
                    return this.getCurrentPage().scrapexxxData()
                        .then(actualText => {
                            return this.expect(expectedText).to.deep.equal(actualText);
                        });
                });
        });
```

I've tried using the same.members in chai too but they both return back the same result. Any thoughts? or could you point me towards an array comparison in the examples?
