### ISSUE TITLE
Support asynchronous world constructor

### ISSUE THREAD

**Issue by salikh** [cucumber/cucumber-js#39]
I am trying to use cucumber.js to test an express.js web application.
The test scenarios are creating new objects in MongoDb database,
and I need to clear it before running the tests.

Mongodb operations are asynchronous, so if I clear the database
from world constructor, then I have a race condition with test execution.

I came up with an idea how asynchronous initialization can be supported,
please see the fork at git://github.com/salikh/cucumber-js.git.

To request asynchronous initialization, the feature writer needs
to inherit from the EventEmitter by writing the following line:

```
this.__proto__ = new process.EventEmitter
```

Then the world constructor can indicate that it finished initialization
by firing an event on itself:

```
world.emit('init done')
```

The world initializer tests if the asynchronous initialization is
required by the following condition:

```
if (world.__proto__.constructor == process.EventEmitter)
```

and if the condition matches, it starts test execution asynchronously:

```
world.on('init done', function() {
cont()
})
```

**Comment by Izhaki** [comment]
This feature is no longer supported.

For people like me trying to see if World can be async, see [docs](https://github.com/cucumber/cucumber-js/tree/f43bea7196bce99d266f2bdfeb909a49c5a60a4b):

> **Breaking Change**: The World constructor is now strictly synchronous and does not receive a callback from Cucumber anymore... This is a breaking change that was introduced in release v0.8.0

**Comment by kAworu** [comment]
This is not supported anymore as correctly pointed out by @Izhaki,

Then, how or when should "async world setup code" run?

**Comment by jbpros** [comment]
@kAworu use a `Before` hook that calls a method on your world.
