### ISSUE TITLE
On Chai assertion error protractor exits with code 1

### ISSUE THREAD

**Issue by humphreyn** [cucumber/cucumber-js#390]
Hi,
I'm using Chai as promise as my assertion library. When any assertion fails the process always completes with with an exit code of 1. It does not end the process as other scenarios can and are executed but always ends with an exit code of 1 with no stack trace, see below:
```
1 scenario (1 failed)
2 steps (1 failed, 1 passed)
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
{ [Error: protractor exited with code 1]
  message: 'protractor exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function] } }
[13:03:53] Finished 'run-protractor-local' after 21 s

c:\RBI\gk-online\test\automation\gulpfile.js:54
      throw e;
            ^
Error: protractor exited with code 1

Process finished with exit code 1
```
Do you have any ideas what could be causing this?

Below is a copy of my package.json file with the versions of each package that are used:

```
{
  "version": "1.0.0",
  "name": "automation",
  "private": true,
  "devDependencies": {
    "chai": "^3.2.0",
    "chai-as-promised": "^5.1.0",
    "cucumber": "^0.5.2",
    "elementor": "^1.0.10",
    "gulp": "^3.9.0",
    "gulp-connect": "^2.2.0",
    "gulp-protractor": "^1.0.0",
    "gulp-protractor-cucumber-html-report": "^0.0.8",
    "mkdirp": "^0.5.1",
    "minimist": "^1.1.3",
    "mssql": "^2.1.8",
    "protractor": "^2.1.0",
    "protractor-html-screenshot-reporter": "^0.0.21",
    "protractor-screenshot-reporter": "^0.0.5",
    "q": "^1.4.1",
    "selenium-webdriver": "^2.46.1",
    "spawn-local-bin": "^0.1.4",
    "gherkin": "^3.1.0"
  }
}
```

**Comment by jlin412** [comment]
I am having problems with callback.  Try to use return last promise in a
step definition to see if it helps.

**Comment by humphreyn** [comment]
This is not an issue and can be closed. I have found out that protractor will exit with code '1' when 1 or more step definition assertion fails. Consequently when using gulp I have to use use gulp-plumber to catch on error with exit code 1  in order to run the cucumber reports afterwards.

**Comment by ahmedusa** [comment]
Could you please post little more information. How you have used gulp-plumber with protractor. Any example will be helpful. Appreciate your help.
