### ISSUE TITLE
Getting multiple features to work

### ISSUE THREAD

**Issue by lcbotha** [cucumber/cucumber-js#391]
The VolatileConfiguration object is the one used by the Cucumber constructor. Which in turn is the constructor one can invoke to quickly instantiate a Cucumber.js runner.

When looking at the implementation at https://github.com/mucsi96/nightwatch-cucumber, they are implementing it in this way:
```javascript
runtime = Cucumber(getFeatureSources(), getSupportCodeInitializer());

runtime.getFeatures().getFeatures().forEach(function(feature, next) {
    createTestFile(feature);
    feature.instructVisitorToVisitScenarios({
        visitScenario: function(scenario) {
            var steps = [];
            scenario.getSteps().forEach(function(step, next) {
                var stepExecutor = getStepExecutor(step);

                if (stepExecutor) {
                    steps.push(stepExecutor);
                }
                next();
            }, function() {
                discoverScenario(feature, scenario, steps);
            });
        }
    });
}, function() {});
```

No matter what I do I can't seem to get cucumber to execute all the features. It only executes the first test. I've tried passing in the options parameters to Cucumber with specific tags for my features but it still doesn't work. Somehow it keeps on executing only one feature instead of all of them.

**Comment by louiscbotha** [comment]
This issue was fixed in the https://github.com/mucsi96/nightwatch-cucumber repository.

**Comment by charlierudolph** [comment]
Closing as appears to be resolved. Please reopen if need be
