### ISSUE TITLE
Allow cucumber to use custom file extensions

### ISSUE THREAD

**Issue by mkusher** [cucumber/cucumber-js#393]
Proposal
=======

1. Passing file extensions as an additional argument to cucumber (e.g. in CLI `--extensions=ts,es6,pogo,coffee`) will make cucumber load support code files with these extensions. Developer will place necessary [transpilers' require hooks](https://babeljs.io/docs/usage/require/) in `support/env.js`.

2. Extract code snippets to external packages which will be required in `support/env.js` (e.g. `require("cucumber-coffeescript-snippets");`). Developer will choose the language for snippets using an argument (e.g. `--language=typescript`).
Code snippets packages should have an api like:
```javascript
var cucumber = require("cucumber"), 
      syntaxObject = require("./my-language-syntax")(cucumber.SupportCode.Syntax);
cucumber.addSnippet(langName, syntaxObject);
```
Where `cucumber.SupportCode.Syntax` is a Syntax object defined in `/lib/cucumber/support_code/step_definition_snippet_builder_syntax.js`

**Comment by cades** [comment]
Awesome! Want this +1

**Comment by jbpros** [comment]
This has been done through the recently added `--compiler` CLI flag. See https://github.com/cucumber/cucumber-js#transpilers.

The language-specific snippets aren't implemented and I'm not sure we really need them.

WDYT? Please reopen if necessary.

**Comment by charlierudolph** [comment]
I think the `--coffee` flag for coffeescript snippets should be removed. 

If there is still need to snippets in other languages, I think giving some interface for modules that implement step definitions snippets in other languages would be nice.
