### ISSUE TITLE
Error handling after Node update.

### ISSUE THREAD

**Issue by vilmysj** [cucumber/cucumber-js#394]
I am using cucumber-js with selenium-webdriver and after updating Node from v0.10.29 to v0.12.7 node process crash on second error
``` js
c:\Users\user\dev\tests\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
```
Do you have any ideas why this could happen?

**Comment by vilmysj** [comment]
It seams that `exception.js`
```js
domain.on('error', exceptionHandler);
``` 
does not handle second error from `selenium-webdriver` with Node v0.12.7

if I change error handling on process it works the same as before and catch all exceptions.
```js
process.on('uncaughtException', exceptionHandler);
```

for Node v0.10.29 handler on process does not work, so as workaround now I use both handlers

```js
    if (domain && domain.enter) {
      Debug.notice('entering domain ' + domain.id + '\n', 'Cucumber.Util.Exception', 5);
      domain.on('error', exceptionHandler);
    }
    if (process.on) {
      process.on('uncaughtException', exceptionHandler);
    } else if (typeof(window) !== 'undefined') {
      window.onerror = exceptionHandler;
    }
```

**Comment by jbpros** [comment]
Thanks for reporting this. It looks like we'll never get out of this exception mangling nightmare. :persevere:

**Comment by jlin412** [comment]
I got this issue as well but the fix does not work for me.  Here is the step definition that I have.
I call the step in two different scenario and second time fail and exit.

```
  this.When(/^I failed at the first promise when there are two protractor function calls$/, function () {
    $('bad_css_path').isDisplayed();
    return $('bab_css_path').isPresent();
  });
```

**Comment by vilmysj** [comment]
@jlin412 Yes it worked for me and I am still using it.

Also you can try to use https://github.com/creationix/nvm to switch node version when running tests. I have not tested it, but it should work too.

**Comment by jlin412** [comment]
@vilmysj  Do you use protractor?  Can you confirm if it is working for protractor as well?

**Comment by vilmysj** [comment]
@jlin412 I don't use protractor, but I could try it on Friday.

**Comment by jlin412** [comment]
appreciate that.

**Comment by vilmysj** [comment]
@jlin412 Protractor handles errors before the cucumber so my changes didn't work at first.

But if you go to `node_modules/protractor/lib/runner.js` and commented out line 162
`require('source-map-support').install();` cucumber starts to handle errors.

in `source-map-support.js` there is such line
`process.on('uncaughtException', handleUncaughtExceptions);`
which catches errors before cucumber.

However, I am not sure how this will affect Protractor, Cucumber still prints same/similar error.

**Comment by jlin412** [comment]
@vilmysj Thank for tracking down the problem.
@jbpros It seems to similar problem in https://github.com/angular/protractor/issues/876 again.
Because I can make protractor work again with the following line:
```
require('source-map-support').install({  
   handleUncaughtExceptions: false  
});
```
I am not sure why domain misbehave again in node 0.12.x and protractor 2.x.x combination.
@jbpros Do you think that you can look at this again?  I can help you unit test.

**Comment by jlin412** [comment]
@jbpros Sorry to bug you again.  It seems that there are various issues reported for exception handling in node 0.12.x in both protractor and cucumber.  Can we raise severity of this issue and get a fix for it?  Else, we will need to stay in 0.10.x as long as we are using cucumber.js.  I will be happy to help in any way I can.

**Comment by charlierudolph** [comment]
domains are unstable in node 0.12 and deprecated in node 4.0. 
I think we need to remove their usage and just use `process.on 'uncaughtException'`

**Comment by jlin412** [comment]
@charlierudolph Would you like to take a crack on error handling error for 0.12 and 4.0?

**Comment by jlin412** [comment]
@charlierudolph and @jbpros I tested with 6.0.0 with node 4.1.1 and problems still exists with latest protractor 2.3.0.
