### ISSUE TITLE
Extra closing bracket and semicolon in example.

### ISSUE THREAD

**Issue by georgerichmond** [cucumber/cucumber-js#395]
There is an extra closing bracket and semicolon in the documentation:

`
// features/support/world.js
var zombie = require('zombie');
function World(callback) {
    this.browser = new zombie(); // this.browser will be available in step definitions

    this.visit = function (url, callback) {
      this.browser.visit(url, callback);
    };

    callback(); // tell Cucumber we're finished and to use 'this' as the world instance
  }; // EXTRA CLOSING BRACKET AND SEMICOLON HERE
}
module.exports.World = World;

`

**Comment by jbpros** [comment]
Thanks. Closed by 343fa1a
