### ISSUE TITLE
Can registerHandler, before, after hooks return promises now?

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-js#396]
This is original syntax:
```
this.registerHandler('AfterStep', function (event, done) {  done() });
```
Can I do?
```
this.registerHandler('AfterStep', function (event) {  return promise; });
```
I seems to break the cucumber hook and exit right away.

**Comment by charlierudolph** [comment]
Handlers cannot be synchronous or return promises. Something I brought up in #388.

**Comment by jbpros** [comment]
@jlin412 Not yet. See #400 and #401. 

`registerHandler` and the handlers you pass it will not support promises anytime soon (see https://github.com/cucumber/cucumber-js/issues/388#issuecomment-136729080 for more info).
