### ISSUE TITLE
API for listing step definitions

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#4]
2011-05-30 #cucumber:
11:59 &lt;aslakhellesoy> jbpros: one thing that would be useful in cucumber.js is an API call to get all of the stepdefs
12:00 &lt;aslakhellesoy> following this spec: https://github.com/cucumber/gherkin/wiki/Code-Completion
12:00 &lt;aslakhellesoy> (see the json doc at the bottom for a quick example)
12:00 &lt;aslakhellesoy> if cucumber.js provides those we can feed them to gherkin-editor

**Comment by jbpros** [comment]
It's potentially still relevant but let's not worry about this until it becomes a real thing.

**Comment by machacz** [comment]
Would you consider implementing such API? We may forget about gherkin-editor as it's an ancient history, however without this I'm unable to write code completition for anything. For instance writing code completition for Brackets editor would take about 1 hr to me, but I can't get a list of supported steps, that makes my effort pointless. To be more specific, I was thinking about writing code completition plugin that would work with nightwatch-cucumber and brackets...
