### ISSUE TITLE
Document how to run in browser

### ISSUE THREAD

**Issue by henrify** [cucumber/cucumber-js#402]
The documentation / readme.md begins with claim: "runs on both Node.js and modern web browsers", but after that there doesn't seem to be any documentation at all how to actually do it... Or am i missing something?

Please provide documentation how to run in browser, or link to such documentation from the readme.md if it already exists.

**Comment by jbpros** [comment]
You're right it should be documented. Have a look at the `example` folder to learn more about it in the meantime.

**Comment by henrify** [comment]
Thanks for your reply.

The example worked perfectly, and I was able to integrate cucumber.js to our project in about 3 minutes..

But can you enlighten me, what is the file 'vendor/gherkin.en.js' used for in the example? It seems that the main library gets served from ../release, and on quick look I didn't even find where the gherkin.en.js file is loaded from, and the example seems to work without it?
