### ISSUE TITLE
Bug with version above 0.4.4 - HIGH SEVERITY

### ISSUE THREAD

**Issue by gkushang** [cucumber/cucumber-js#404]
We are facing issue with cucumberJS version above @0.4.4. It does not execute the @After hook if more than one scenarios are executed and each one fails when `element` is not found by WebDriver. It also does not print the JSON to the console.

Steps to Reproduce:
```
Install Cucumber version above 0.4.4
1. Run Two Scenarios (makes sure each one fails due to No Element Found by WebDriver)
2. Scenario 1 closes the browser (executes the @After hook)
3. Scenario 2 does not close the browser (does not execute @After hook(
4. Does not print JSON to the console
These steps are true if cucumber runs more than one scenarios.
```

Repeat above steps with Cucumber@0.4.4 version and it just works fine.

We are not able to generate Cucumber Report (and see the failures for our E2E) at all with cucumber version above 0.4.4. We have been forced to downgrade the version. We will appreciate any fix on this.

Thank you team,
Kushang

**Comment by jlin412** [comment]
Are you using node 0.12?
There is a bug using node 0.12.

**Comment by gkushang** [comment]
yes, I am using node v0.12.2. Did you mean cucumberJs is not fully functional with the node v0.12.2? What is the workaround?

**Comment by jlin412** [comment]
https://github.com/cucumber/cucumber-js/issues/394 that is issue tracked.  I will recommend to downgrade to node 0.10.x for now.  That is what I ask my whole team to do.

**Comment by gkushang** [comment]
thanks @jlin412 - I am looking forward for the fix. Meanwhile, let me downgrade the version.

**Comment by jbpros** [comment]
What about node 4.1.1, is it failing there as well?

@gkushang could you share a gist with the code to reproduce this?

**Comment by jbpros** [comment]
Dup of #394. @gkushang please follow that issue if you want to track the progress on this.

**Comment by aslakhellesoy** [comment]
The HIGH SEVERITY label reminds me of [Urgent](http://www.catb.org/esr/faqs/smart-questions.html#urgent).
