### ISSUE TITLE
Cucumber scenario execution is not showing execution time at the end when running cucumber test locally 

### ISSUE THREAD

**Issue by thivyae** [cucumber/cucumber-js#408]
Cucumber scenario execution is not showing execution time at the end when running cucumber test locally using cucumber.js --tags @feature
The execution completion only shows scenarios and steps which passed and failed but not the execution time.

It was showing previously some three weeks back.It might be broken in this release

**Comment by charlierudolph** [comment]
Don't believe this was ever implemented. Just opened a PR for it. #416

**Comment by jbpros** [comment]
Implemented in 67ebc8d577d821d2f63c092c9a95ca12015e6e3a
