### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by cajoy** [cucumber/cucumber-js#409]
After upgrade to 0.6.0 I don't see any colors in Git-Bash.

Previous version was ok.

**Comment by charlierudolph** [comment]
Does the node module [colors](https://github.com/marak/colors.js/) work on Git-Bash? We switched from a hand written colorizing to that library which appears to be the most popular npm cli colors library.

**Comment by cajoy** [comment]
Probably no as I don't see anything by default, can I enable it manually?

**Comment by jbpros** [comment]
Could it be the same upstream issue described on https://github.com/Marak/colors.js/issues/136?

**Comment by cajoy** [comment]
Appending  
```
 --color=true
```

seems like resolved issue - thanks

**Comment by charlierudolph** [comment]
Good to hear
