### ISSUE TITLE
Import removed scenarios from cucumber-tck

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#41]
Import those scenarios locally:

https://github.com/cucumber/cucumber-tck/commit/1288b20f464881e6428854cee6145e774b65248e#L1L63
https://github.com/cucumber/cucumber-tck/commit/1288b20f464881e6428854cee6145e774b65248e#L1L73

**Comment by charlierudolph** [comment]
Closing as these are currently [here](https://github.com/cucumber/cucumber-js/blob/8daf95b65557b85e74c4fa878cc8a6322b9855ca/features/step_definition_snippets.feature)
