### ISSUE TITLE
BUG: typo in lib/cucumber/cli/argument_parser.js

### ISSUE THREAD

**Issue by fustic** [cucumber/cucumber-js#418]
to set a short name of the profile options the `PROFILE_OPTION_FLAG_SHORT_NAME` key has been chosen:
```javascript
ArgumentParser.PROFILE_OPTION_FLAG_SHORT_NAME            = 'p';
```

but in `getShortenedOptionDefinitions` method a different key has been used `PROFILE_OPTION_SHORT_NAME` which is `undefined`.

Due to this issue the `nopt` returns unpredictable results of `options` object based on different variations of arguments.
```javascript
argsToOptions: function argsToOptions(args) {
      var knownOptionDefinitions     = self.getKnownOptionDefinitions();
      var shortenedOptionDefinitions = self.getShortenedOptionDefinitions();
      var options = nopt(knownOptionDefinitions,
                         shortenedOptionDefinitions,
                         args,
                         0);
      return options;
    }
```
Please use one or another.

**Comment by charlierudolph** [comment]
Good gahh. I dislike nopt. The fact that it supports "abbreviations", allowed this to work. I'll add a fix for this but I'm thinking of switching from nopt to commander.js

**Comment by fustic** [comment]
:+1: thank you
