### ISSUE TITLE
replace bespoke argument parsing with a lib

### ISSUE THREAD

**Issue by samccone** [cucumber/cucumber-js#433]
In 2015 there is no need to roll our own any more  

Let's :fire: `lib/cucumber/cli/argument_parser.js`

Replace with:
https://github.com/bcoe/yargs

**Comment by charlierudolph** [comment]
We aren't rolling our own but are actually using [nopt](https://github.com/npm/nopt). I think it does need to be replaced but my vote would be [commander](https://github.com/tj/commander.js)
