### ISSUE TITLE
--no-color does not disable color

### ISSUE THREAD

**Issue by karthiktv006** [cucumber/cucumber-js#435]
After the update to colors package, --no-color should disable color but thats not working

**Comment by charlierudolph** [comment]
We aren't using the "native" support of the colors package as that inspects the process.argv. This is because if we switch to a stricter cli parser (as proposed in #434), arguments wouldn't be specifically allowed in. Instead I think its better to support it by hand (as proposed in #432).

**Comment by karthiktv006** [comment]
I just now saw the PR for this issue. Thanks @charlierudolph

**Comment by charlierudolph** [comment]
fixed with b5947986e19c8c0d080e6104341e665c75a4c36b
