### ISSUE TITLE
Removal of callback.fail() - breaking API change

### ISSUE THREAD

**Issue by romanek-adam** [cucumber/cucumber-js#437]
Hi,

I'd like to report that the removal of callback.fail() which happened as part of #415 was in fact a breaking API change. It broke for example [cucumber-assert](https://github.com/djungowski/cucumber-assert/blob/master/index.js#L113) module and possibly some other modules and end user code and tests.

What was the rationale behind this change? Has it been properly documented / announced?

I'd expect the API to be reverted back and released as part of 0.7.1 or at least the change be mentioned on the 0.7.0 release page.

**Comment by charlierudolph** [comment]
> What was the rationale behind this change?

The removal of `callback.fail()` was just cleanup as we already support node style callbacks where you pass errors as the first argument and don't need two ways to do the same thin.

----

> Has it been properly documented / announced?

Our [History.md](https://github.com/cucumber/cucumber-js/blob/master/History.md) file documents the change though its not called out all that well. @jbpros are you okay with renaming `changed features` to `breaking changes` and putting them as the first section in each release? What do you think about also listing the changes on the [releases](https://github.com/cucumber/cucumber-js/releases) page?

---
We are not planning on reverting this change and were following semver.

Point 4 at <http://semver.org/> states: "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

If we introduce breaking changes, we are bumping the minor version, and only bumping the patch version if the changes are non-breaking. This works with the [carat operator of node-semver](https://github.com/npm/node-semver#caret-ranges-123-025-004) which npm uses when saving installed modules to your `package.json`.

For cucumber-assert, I would suggest setting a peer dependency to limit what versions of cucumber you are known to be compatible with.

**Comment by jbpros** [comment]
@charlierudolph ok for "breaking changes" and yes to better release descriptions. I've added a [requirement](https://github.com/cucumber/cucumber-js/commit/49801cfc65bdad87ef72666fda1bc42bf032d471) for that in CONTRIBUTING.

@romanek-adam I'm closing this as we'll not resurrect `callback.fail()`. Please reopen if you think this is wrong (and tell us why).

**Comment by romanek-adam** [comment]
Well for me the API may be left as is.

FYI a new release of cucumber-assert v1.0.2 is now compatible with cucumber-js v0.7.0.

**Comment by jbpros** [comment]
Good, thanks @romanek-adam
