### ISSUE TITLE
There are plans to support generators on the steps?

### ISSUE THREAD

**Issue by srh-work** [cucumber/cucumber-js#438]
Hi.

I recently started using "cucumber" and I love it. I'm using "WebdriverIO" in my tests and I would like to use generators. Like this:

```
this.Then(/^I should see "(.*)" as the page title$/, function*(title, next) {
    
        let result = yield this.driver
             .url( "http://localhost:3000" )
             .title();

        expect( result ).to.equal( title );
        next(); 
 });
```

So, there are plans to support generators on the steps?

Thanks.

**Comment by charlierudolph** [comment]
Looking at the idea behind for es6 generators, I believe support for generators is simply based on what version of node you are running. What happens when you run the given code? (I'm curious what would happen if you were to remove `next` as well)

**Comment by srh-work** [comment]
Ok, if I run something like this:
```
this.Then(/^I should see "(.*)" as the page title$/, function*(title) {
        
        let result = yield driver
            .execute(() => {
                return document.title;
            });

        console.log(result);
        
        yield driver
            .end();
});
```
The steps pass without open the browser. The stage is successful but does nothing, even the result variable never print.

And if I run something like this:
```
this.Then(/^I should see "(.*)" as the page title$/, function*(title, next) {
        
        let result = yield driver
            .execute(() => {
                return document.title;
            });

        console.log(result);
        
        yield driver
            .end()

        next();
});
```
The step exceed the timed out with any time I set.

I use Node v4.2.1 with generators support. 

So, I think "cucumber" does not support the flow generator. How to make do it exceeds my knowledge.

Thanks.

**Comment by charlierudolph** [comment]
Looks like we can use [is-generator](https://github.com/blakeembrey/is-generator) to check if the function supplied is a generator function and then use [co](https://github.com/tj/co) to run it.

I like the idea of supporting it. Personally don't have time to work on this at the moment and probably won't until we get to 1.0. Pull request welcome.
