### ISSUE TITLE
0.7 seems break saucelabs tests

### ISSUE THREAD

**Issue by xcompass** [cucumber/cucumber-js#439]
It was working fine until I updated 0.7. Here is the test log: https://travis-ci.org/ubc/acj-versus/jobs/86524837. Here is the related job on saucelabs: https://saucelabs.com/beta/tests/acab1764f3c5450892cae3d655cceb14/commands

If I revert to 0.6, tests work fine. I also tried to use selenium 2.47.1 on saucelabs (default is 2.44.0) The same result. Here is the successful tests with 0.6: https://travis-ci.org/ubc/acj-versus/jobs/86741133

**Comment by charlierudolph** [comment]
0.7 introduced timeouts with the default timeout being 5 seconds. Please see the README for how to configure the timeouts for your need.

**Comment by jbpros** [comment]
Yes, it looks like your successful tests take a while to run, you probably have steps running for more than 5 seconds.

Closing, please reopen this if needed.
