### ISSUE TITLE
Executing with line number does not work with individual scenario outline examples row

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-js#441]
In Ruby cucumber, we can select line number in any row in examples.
In cucumber.js, we can only select on scenario outline to execution all the rows right now.
There is already a PR to implement rerun formatter from @karthiktv006 
It will be extremely helpful to get this missing feature implemented so rerun formatter can be even more powerful.

**Comment by jbpros** [comment]
That's a missing bit of that feature indeed. Thanks for reporting it @jlin412.
