### ISSUE TITLE
update to Meteor 1.2.1, cucumber fails

### ISSUE THREAD

**Issue by drerichsu** [cucumber/cucumber-js#443]
I updated to 1.2.1 and now the mirror Chrome launches, but instead of opening the Meteor app URL, it shows "data:," in the url bar.

In the cucumber.log, I get
```
(::) failed steps (::)

TypeError: Cannot call method 'isExisting' of undefined
  at World.<anonymous> (features/NewUsers/step_definitions/NewUsers-steps.js:11:14)


Failing scenarios:
features/Students/students.feature:172 # Scenario: A student can manage account and use Back and Forward

1 scenario (1 failed)
32 steps (1 failed, 31 skipped)

[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
```

Even downgrading by running meteor --release 1.2.0.2 doesn't fix the issue.

The mirror is running:
```
=> Using velocity:METEOR@1.2.0.2_1 as requested (overriding Meteor 1.2.1)
```

**Comment by charlierudolph** [comment]
This doesn't look like a cucumber-js issue to me. It is reporting that you are trying got call isExisting on an undefined object in one of your step definitions.

**Comment by drerichsu** [comment]
Perhaps this is really an issue with velocity, the test runner I'm using.

**Comment by jbpros** [comment]
Please reopen if you think this is an issue in cucumber.
