### ISSUE TITLE
Relax argument count check for step definitions for optional data table

### ISSUE THREAD

**Issue by riaan53** [cucumber/cucumber-js#445]
Hi,

Some of my step definitions contains an optional data table. With the latest cucumber.js changes I get the following error if I left the data table out:
```
Error: step definition has 4 arguments, should have 2 (if synchronous or returning a promise) or 3 (if accepting a callback)
```

In the step definition self I check if a data table is given, if not then it must be the callback for async steps.

```
    if (typeof(table) !== 'object') cb = table;
```

Any way I can get around this argument check, or can you please add an optional data table argument to the count? 

Thank you.

Regards,
Riaan

**Comment by jbpros** [comment]
Mmm, this is interesting. We're not expecting step arguments to be optional (including data tables and multiline strings). Can you share examples of scenarios using such a step (one with and one without a table) please?

**Comment by riaan53** [comment]
For this test I am using cucumber to test/document an SOAP API.

I use the data table to build up the SOAP parameters, some messages have optional parameters and do not need a data table.

Im also using the same step definition to send all the SOAP messages from by using the SOAP method as the first parameter.

Example without data table:
```gherkin
When a "connect" message is sent to the green box
Then the green box should be connected
```

Example with data table:
```gherkin
When a "notify" message is sent to the green box
 |  type  | message                |
 |  error | The error message |

Then the green box should have received an error notification
```

**Comment by charlierudolph** [comment]
Hmm, that is an interesting case. I'd prefer to not support optional arguments.

I'd suggest changing to the step with the data table to
```cucumber
When a "notify" message is sent to the green box with the properties
 |  type  | message           |
 |  error | The error message |
```
I think that reads better anyway. The two steps can still share logic by each calling a helper function.

**Comment by jbpros** [comment]
Also, I usually recommend adding a `:` (column character) at the end of the sentence to give a hint a table/multiline string is expected with that step.
