### ISSUE TITLE
Cucumber does not support AsyncCode assertion properly

### ISSUE THREAD

**Issue by priyanshus** [cucumber/cucumber-js#447]
Having an `asyncCode` in assertion with `chai-as-promised` library. Cucumber always shows test as passed no matter what is actual result of test.

For example if you have test like this:
```
this.When(/^I test async code$/,function(callback) {
    expect(someAsyncCodeReturnsFalse()).to.be.true;  //It will pass even if async code returns false
    done();
});
```

It does not work well with `ChaiWebDriver` too.

ChaiWebDriver: http://chaijs.com/plugins/chai-webdriver

**Comment by charlierudolph** [comment]
cucumver-js supports steps that return promises.
When using chai-as-promised, you need to return the expectation (which is a promise)
```js
this.When(/^I test async code$/,function() {
    return expect(someAsyncCodeReturnsFalse()).to.be.true;
});
```

**Comment by priyanshus** [comment]
@charlierudolph Thanks, it supports `chai-as-promised` but what about `ChaiWebDriver`?

**Comment by jbpros** [comment]
@priyanshus same thing, you need to return the Chai/ChaiWebDriver/Whatnot promises from your step definitions.

Cucumber does not know anything about chai or ChaiWebDriver. All it cares about is to run your step definition function that is either synchronous or asynchronous (returning a promise or invoking a callback).

I think this is a support request. Please use the [cukes google group](https://groups.google.com/forum/#!forum/cukes) if you need any more help or reopen this issue if you think there's something wrong with Cucumber.
