### ISSUE TITLE
--format <TYPE:PATH> not working

### ISSUE THREAD

**Issue by fourpastmidnight** [cucumber/cucumber-js#460]
I'm running cucumber.js via a grunt task. Here's the command being executed by grunt:

    node node_modules/.bin/cucumber-js tests/e2e/features -f json:tests/e2e/reports/report-20151122-225937.json

Here's the output:

    Warning: Unknown formatter name "json:tests/e2e/reports/report-20151122-225937.json". Used --force, continuing.

So, how am I supposed to get the output? Am I doing something wrong? And, the README doesn't say, but is `PATH` relative to anything?

**Comment by charlierudolph** [comment]
I was unable to reproduce with version 0.9.2. What version are you using? Support for that way of specifying formatted was added in 0.8.0.

It appears everything you are doing is correct. If PATH is relative, it is resolved against [process.cwd()](https://nodejs.org/api/process.html#process_process_cwd). I'll add a note to the README.

**Comment by fourpastmidnight** [comment]
Thank you for replying. It seems that the package I included in node for running cucumber with grunt is using a _very old_ version of cucumber.js. Good to know the PATH is relative to `process.cwd()`.
