### ISSUE TITLE
Official Karma/Cucumber integration

### ISSUE THREAD

**Issue by jrobison153** [cucumber/cucumber-js#465]
Are there any plans to create a community supported plugin for Karma? I've been looking for a way to run cucumber tests in the browser and have really not found a viable solution that doesn't require a ton of hacking to get working, and even then 'working' is a very loose term. 

Karma is one of the most popular test runners and integration with cucumber would really help to bring the world of BDD to the client space. With the complexity of the Single Page Applications we are building, testing is more important than ever. We love using cucumber on our Node.js backends and want to bring the same discipline and benefits to our front end development.

I'd be willing to assist in working on this however I would need a push in the right direction.

**Comment by jrobison153** [comment]
anyone have any feedback on this? Has this been discussed before?

**Comment by charlierudolph** [comment]
I have tested single page applications by running cucumber in node and using selenium webdriver to control the browser. Why exactly do you want cucumber to run in the browser? The README has a sample of running cucumber in the browser.

**Comment by charlierudolph** [comment]
http://cucumber.github.io/cucumber-js/

**Comment by charlierudolph** [comment]
For the source code see the `example` directory.

**Comment by charlierudolph** [comment]
Closing due to age. Please reopen if needed
