### ISSUE TITLE
socket dont listen when I send a string

### ISSUE THREAD

**Issue by anasalinas** [cucumber/cucumber-js#470]
Hello!

I have created a socket with the following code in a  myfile.js file:

var PORT = 44444;
var HOST = '127.0.0.1'; 
var dgram = require('dgram');
var client = dgram.createSocket('udp4');
 buffer = new Buffer(this.result);
client.send(buffer, 0, buffer.length, PORT, HOST, function(err) { console.log(err);});

This Code is implemented in a js file called myfile.js, inside ../features/step_definitions directory  which has a step definitions for Gherkin language, because I want to send a string by  this socket,  then I execute the command from ../features
> 'cucumber.js  myfile.feature'
but when I type in a shell  
> 'nc -lu 44444'  I dont see anything, and I dont know why. I am using cucumber.js module, that module runs on Node.js, but it doesnt work !!

I have tried the code of this socket on Node.js and works perfectly in the same port.

Thanks in advanced !!
See you coders ! :)

**Comment by charlierudolph** [comment]
Can you lay out directory structure a bit more concretely? Does it look like this
```
project/
  features/
    myfile.feature
    step_definitions/
      myfile.js
```
Where you run `cucumber.js myfile.feature` from the features directory?

**Comment by anasalinas** [comment]
Yes I did it.
I run cucumber.js myfile.feature from   ../features

**Comment by charlierudolph** [comment]
Your `step_definitions` folder needs to be inside your `features` folder

**Comment by anasalinas** [comment]
Sorry, Yes, I have in that form, I have in that structure
I have:
/home/ana/features/step_definitions

**Comment by charlierudolph** [comment]
In your `myfile.js`, you have `buffer = new Buffer(this.result);`
Does `this.result` get initialized properly?

**Comment by anasalinas** [comment]
Yes, too !!
I have it!!
I think the problem is in other case.....
It´s something like cucumber.js ......
The way of cucumber launch those features, but I am just crazy ! hahahha!!
I´ve tried everything :)

**Comment by charlierudolph** [comment]
Sorry I'm confused. Is this resolved or do you still need help? All cucumber-js does is load all javascript files in the directory of your features or the sibling directories of your specified features. You can use the `--require` command line option to ensure specific files are loaded.

**Comment by anasalinas** [comment]
Finally, I have tried other option: I am using behave with Python for test my features files in Gherkin, and  when I type  'nc  -l MYPORT'  the port is listenning.

A socket in Python is better  ;)  and easier !

**Comment by charlierudolph** [comment]
Good to hear
