### ISSUE TITLE
There are plans to support es6 class to World Object?

### ISSUE THREAD

**Issue by AbraaoAlves** [cucumber/cucumber-js#471]
Hi.

I using "cucumber" and I love it. I'm recently start using es6-classes and I love it too.
But when using 'class' with World constructor, anyone protrotype method survive in the process, only internal declaration members.

``` javasscript
"use strict";

class World{
  constructor(){
    // visible in all steps definitions
    this.foo = function(){

    }
   }
   /* not visible in steps definitions*/
   visit(url){
      return browser.get(url)
   }
}
exports.World = World;
```

There any workaround to do this?

**Comment by charlierudolph** [comment]
I was able to get an example of this working. Note the exports needs to be
```js
exports = function() {
  this.World = World;
};
```

**Comment by AbraaoAlves** [comment]
@charlierudolph writing World in class style, you can access call 'visit' method in steps? If true, you can share a example for this?

**Comment by charlierudolph** [comment]
features/a.feature
```cucumber
Feature: a feature
  Scenario: a scenario
    When a step
```
features/step_definitions/my_steps.js
```js
var assert = require('assert');

module.exports = function () {
  this.When(/a step/, function() {
    assert.equal(this.foo, 1);
    assert.equal(this.bar(1), 2);
  });
};
```
features/support/world.js
```js
"use strict";

class World {
  constructor () {
    this.foo = 1;
  }
  bar (x) {
    return x + 1;
  }
}

module.exports = function () {
  this.World = World;
}
```
With cucumber-js 0.9.2 and node 4.2.2, when I run `cucumber-js` it passes.

**Comment by charlierudolph** [comment]
@AbraaoAlves please reopen if you more help
