### ISSUE TITLE
Scenario as step

### ISSUE THREAD

**Issue by senty** [cucumber/cucumber-js#473]
Hi,

is possible to use SCENARIO as STEP ?
Image SCENARIO which contains a lot of common logic. This logic is tested itself in own feature, but it is needed also in many others scenarios as "first step",

(example : several factor login)

Thank you very much

**Comment by charlierudolph** [comment]
Not at the moment. You should still be able to share the logic though, by extracting the common logic into functions.
```js
this.When(/login step 1/, function () {
  loginStep1();
})

this.When(/login step 2/, function () {
  loginStep2();
})

this.When(/login step 3/, function () {
  loginStep3();
})

this.When(/full login/, function () {
  loginStep1();
  loginStep2();
  loginStep3();
});
```




Cucumber ruby has the ability to run steps from within a step. For some reason, I remember seeing someone regretting that though. @mattwynne @aslakhellesoy can you chime in here?

**Comment by mattwynne** [comment]
You can see the amount of discussion there's been about this in the google group over the years here: https://groups.google.com/forum/#!searchin/cukes/nested$20steps

Essentially it comes down to people using Gherkin as a programming language, creating complexity in their step definitions by calling back to Gherkin, which in turn calls back to Ruby methods etc. It can get pretty gnarly. And as @diabolo never fails to point out (and you've explained above) - as long as you factor out nice com posable helper methods, you can re-use at that level.

I still think we leave a weakness though, where some non-technical people are interested in delving beneath that declarative "what" and knowing "how" the behaviour is implemented. I've proposed a solution here https://github.com/cucumber/gherkin/issues/178 that would bring us closer to other frameworks like Robot, but I've never seen that idea pick up much momentum.

**Comment by Virgomax** [comment]
I've created a package named [reuse-cucumber-scenarios](https://www.npmjs.com/package/reuse-cucumber-scenarios) for calling a scenario by doing:

```gherkin
Given the scenario "scenario_tag"
```
```gherkin
Given the scenario "scenario_tag" with parameters
"""
{
  "1": ["step1_param1", "step1_param2"],
  "2": ["step2_param1", "step2_param2", "step2_param3"],
  "3": ["step3_param1", "step3_param2", "step3_param3"],
}
"""
```

```gherkin
Given the variable "$variable_name" is equal to
"""
#JSON object
"""
```
```gherkin
Given the scenario "@$scenario_function_tag" where variable "$variable_name" is "value_to_replace"
```

and more...

**Comment by aslakhellesoy** [comment]
That’s a convoluted and roundabout way to reuse code. Extracting reusable functions/methods as Charlie described above is much, much better.

**Comment by Virgomax** [comment]
I first tried to do Charlie's solution, but then I found some difficulty when trying to use the same scenario logic but with different step parameters.

```Javascript
this.Given("login step 1 {string} {string}", function (step1_param1, step1_param2) {
  loginStep1(step1_param1, step1_param2);
})

this.When("login step 2 {string} {string}", function (step2_param1, step2_param2) {
  loginStep2(step2_param1, step2_param2);
})

this.Then("login step 3 {string} {string}", function (step3_param1, step3_param2) {
  loginStep3(step3_param1, step3_param2);
})

// Do I have to write code like this?...
this.When("full login {string}, {string}, {string}, {string}, {string}, {string}", function (step1_param1, step1_param2, step2_param1, step2_param2, step3_param1, step3_param2) {
  loginStep1(step1_param1, step1_param2);
  loginStep2(step2_param1, step2_param2);
  loginStep3(step3_param1, step3_param2);
});
```

Here you are creating a new step definition each time you want to reuse some scenarios and you are doing it manually. How would you reuse nested scenarios? (when you have a step that calls a scenario which in turn calls another scenario). I think managing nested scenarios is easier when using "scenario functions" (Implemented in [reuse-cucumber-scenarios](https://www.npmjs.com/package/reuse-cucumber-scenarios) library).

For developers, the fewer steps definitions you have, the easier to maintain the code.
For people without technical knowledge, I could manage to generate a text file where you have the composite steps(steps that call scenarios) expanded in their basic steps. That's my next task.
