### ISSUE TITLE
Tries to require() cucumber.js bash script if run from node_modules/.bin folder

### ISSUE THREAD

**Issue by kierenj** [cucumber/cucumber-js#477]
https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/cli/profiles_loader.js#L6

This will attempt to `require()` the file `cucumber.js` from the current path.  If the current path is `node_modules/.bin`, then this gives an error as the bash script isn't valid JS of course.

I'm sure I'm doing something crazy in the case where this is happening (in fact I'm on 0.7.0 and trying to get that working with webdriver-io), but I saw this code was still here in your master branch and so wanted to flag it up.

**Comment by charlierudolph** [comment]
I think this is too far of an edge case to be fixed. You should be running `cucumber-js` from your project directory, as that is where your `features` folder lives.

**Comment by kierenj** [comment]
That's fine of course. For ref, I was running wdio (webdriver) with a cwd of .bin, which was in turn invoking cucumber. It correctly passed in the feature folder path as an argument btw - but still this was checking for cucumber.js in the current directory. I'm new to cucumber but raised this to check it was correct behaviour to check the working directory and not feature folder for the .js.  Thanks for considering anyhoo !

**Comment by charlierudolph** [comment]
Yep that is the correct behavior. Sorry thought profiles were documented in the README but does appear so. I'll add some documentation about them

**Comment by charlierudolph** [comment]
Hmm, appears in cucumber-ruby the profiles files can be in a `config` folder, a `.config` folder, or the project directory. I like the idea of actually putting it in the features folder though. @jbpros @mattwynne thoughts on movings the profiles file to be in something `features/support/config.js`? That would just help keep all the cucumber related files in the features folder.
