### ISSUE TITLE
"AfterFeatures" hook does not wait for the callback to be called

### ISSUE THREAD

**Issue by kevgo** [cucumber/cucumber-js#487]
Problematic code 

```livescript
module.exports = ->

  @register-handler 'AfterFeatures', (event, done) ->
    console.log 'AFTER ALL'
```

Cucumber.js happily prints "AFTER ALL" and then exits right away. Ignoring such errors is not really user friendly, but encourages code that doesn't do what the developer thinks it does. Cucumber.js has a ton of asynchronous callbacks like those, I recommend using a systematic approach to make them all robust against
* not being called
* being called multiple times
* being called after already being timed out

If you don't want to re-invent the wheel here, https://github.com/Originate/robust-callbacks is a minimally invasive and well tested solution for this, and now stable.

**Comment by bmsoko** [comment]
+1

**Comment by benjamine** [comment]
+1 (I got bit by this more than once)
