### ISSUE TITLE
Not calling the asynchronous callback on "BeforeFeatures" causes the test suite to be skipped silently

### ISSUE THREAD

**Issue by kevgo** [cucumber/cucumber-js#488]
Related to #487 

How to reproduce (code in LiveScript):

```livescript
module.exports = ->

  @register-handler 'BeforeFeatures', (event, done) ->
    console.log 'BEFORE ALL'
```

Expected behavior:
* I see an error message telling me that I forgot to return from the "BeforeFeatures" hook.
* the test fails

Actual behavior: 
* it prints "BEFORE ALL"
* the test suite ends right there, no tests run
* the return code of the command is 0, indicating that the tests passed (which breaks CI servers)

**Comment by charlierudolph** [comment]
`registerHandler` was simply expsed and doesn't have any feature tests around it. I want to remove it, and started work on beforeAll and afterAll hooks in order to replace its primary uses.
