### ISSUE TITLE
Cucumber ignores errors passed to the BeforeFeatures handler

### ISSUE THREAD

**Issue by joniba** [cucumber/cucumber-js#490]
Calling callback(new Error()) is ignored and tests continue normally. I haven't checked the other handlers, they may have the same problems.

**Comment by charlierudolph** [comment]
registerHandler does not check for errors. I want to remove it in favor of beforeAll and afterAll hooks.

**Comment by kruczy** [comment]
I have the same problem if you add to step definitions:
cucumber version: 0.10.2
```
module.exports = function () {
	this.BeforeFeatures(function (data, callback) {
		return callback(new Error("wrong"));
	});
};
```

the test are ran though an error was passed in the callback

**Comment by kruczy** [comment]
throwing the error so it causes an unhandled exception is a temporary "fix" for me as it will kill the test runner with the desired message
