### ISSUE TITLE
Browser is not getting closed when Assertion/Error is met

### ISSUE THREAD

**Issue by bmsoko** [cucumber/cucumber-js#492]
Hello!!
I think there's an issue with CucumberJS and Protractor not sure which one is causing it, I believe that's cucumberJS since I tried same scenarios with Jasmine and this didn't happen, the problem here is that when test fails browser remains opened, and that's a problem with the CI server, since when it fails, it would leave a browser opened consuming memory! can you please take a look?

Here are my configurations:
```
"cucumber": "^0.9.2",
"gulp": "~3.9.0",
"gulp-protractor": "^2.1.0",
"protractor": "3.0.0",
"protractor-cucumber-framework": "^0.3.2",
"selenium-standalone": "4.8.0",
```
```
$ node --version
v5.3.0
$ npm --version
3.5.2
```

My gulp-protractor looks like:

    /**
     * run protractor
     */

    var args = require('yargs').argv;
    module.exports = function(gulp, plugins) {
        return function (done) {
            var protractorConfig = '',
                testConfig = '',
                environment = args.environment || 'devel',
                tag = args.tag || '@Sanity',
                baseUrl;
    
            if (!args.baseUrl) {
                baseUrl = 'http://test.me/frontend-build-tests/';
            } else if (args.baseUrl.match(/^(?:https?\:)?\/\//)) {
                baseUrl = args.baseUrl;
            } else {
                baseUrl = 'http://test.me/frontend-build-tests/' + args.baseUrl + '/';
            }
    
            switch(environment) {
                case 'devel' :
                    protractorConfig = 'e2e/protractor.config.devel.js';
                    testConfig = '../config/devel';
                break;
                case 'live'  :
                    protractorConfig = 'e2e/protractor.config.live.js';
                    testConfig = '../config/live';
                break;
                case 'remote' :
                    protractorConfig = 'e2e/protractor.config.remote.js';
                    testConfig = '../config/live';
                break;
                default:
                case 'build' :
                    protractorConfig = 'e2e/protractor.config.build.js';
                    testConfig = '../config/build';
                break;
            }
    
            gulp.src([
                'e2e/features/*.feature'
            ])
            .pipe(plugins.protractor.protractor({
                configFile: protractorConfig,
                args: [
                    '--verbose',
                    '--no-stackTrace',
                    '--params.test.config', testConfig,
                    '--baseUrl', baseUrl,
                    '--cucumberOpts.tags', tag
                ]
            }))
            //.on('end', function(){
            //        console.log('E2E Testing complete');
            //        process.exit();
            //    })
            .on('error', function() {
                done();
                    //protractor.driver.quit();
                    process.exit(1);
                    //var protractor = require("gulp-protractor").protractor;
                    //console.log("ON Error");
                    //protractor.browser.quit();
                    //throw e;
    
                });
        };
    };

And my `protractor.config` has:

    exports.config = {
        //seleniumServerJar: './node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar',
        seleniumAddress: 'http://localhost:4444/wd/hub',
        //directConnect: true,//To run test directly against Chrome/FFs
        specs: [
            'e2e/features/*.feature'
        ],
        multiCapabilities: [
            {
                'browserName': 'chrome',
                'chromeOptions': {
                    'args': ['show-fps-counter=true','enable-logging','v=1','net-log-level=0']
                }
            },
            // {
            //   'browserName': 'firefox'
            // },
            // {
            //   'browserName': 'safari'
            // },
            // {
            //   'browserName': 'phantomjs',
            //   'phantomjs.binary.path':'./node_modules/phantomjs/bin/phantomjs',
            //   'phantomjs.cli.args':'--debug=true --loglevel=DEBUG --webdriver --webdriver-loglevel=DEBUG'
            // }
        ],
        framework: 'custom',
        frameworkPath: require.resolve('protractor-cucumber-framework'),
        cucumberOpts: {
            require: 'features/step_definitions/**/*.js',
            format: 'json'
            //tags: "@Sanity"
    
        },
    
        resultJsonOutputFile: 'report.json',
        //count: 2,
        //shardTestFiles: true,
        //maxInstances:2,
    
        onPrepare: function () {
    
            browser.getCapabilities().then(function (capabilities) {
                browser.capabilities = capabilities;
            });
            browser.driver.manage().window().maximize();
    
            browser.ignoreSynchronization = true; //This is set for non-Angular apps
    
            browser.manage().timeouts().implicitlyWait(20000);
    
    
        }
        //,
        //onCleanUp: function(exitCode) {
        //    if (exitCode ==1){
        //        console.log("Getting out");
        //        browser.quit();
        //    };
        //},
    };

Is there anything I'm doing wrong? do you already have a workaround?

I tried running the same without `gulp-protractor` and I'm getting the same behavior, so... that's also why I tended to think that it was cucumberJS... 

Thanks!!

**Comment by charlierudolph** [comment]
I don't know enough about protractor in order to help here. If you need to perform some cleanup in a cucumber test suite you can use the AfterFeatures hook (see the README). Note: that interface will most likely be change soon (see #487, #488, #490)

**Comment by charlierudolph** [comment]
Closing due to age. Please reopen if you would like to discuss more
