### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by mijikim** [cucumber/cucumber-js#494]
Hello,

Cucumber-js requires cucumber-html as its dependency. Cucumber-html, however, has no license information which makes it difficult for cucumber-js to be used in an enterprise context.  Would it be possible for this to be looked at?  It seems like this was requested months back and still hasn't been looked into and the PR I opened didn't receive any response either.

Thank you!

**Comment by aslakhellesoy** [comment]
Thanks for the heads up. I added cucumber/cucumber-html@b5ea4c789b6a1887ddd5c935d24e4a535e51b6e6 and also merged cucumber/cucumber-html#34
