### ISSUE TITLE
BeforeFeatures handler does not pass in an event or callback in 0.9.2

### ISSUE THREAD

**Issue by grofit** [cucumber/cucumber-js#495]
I was just prototyping a quick cucumber script for someone and kept getting an issue where `callback();` in a `BeforeFeatures` handler kept throwing; `Unhandled rejection TypeError: object is not a function`.

After checking it seems that it has no arguments, so the below code doesnt have event or callback.

```
this.registerHandler('BeforeFeatures', function (event, callback) {
  // Arguments are null
});
```

So has this changed recently? I see mentions of moving towards `beforeAll` and `afterAll` which sounds great, but should this currently be working? if not what is the new approach for running logic before all features?

**Comment by charlierudolph** [comment]
This should not have changed. I never ran into this error and used beforeFeatures and afterFeatures frequently. Please try with 1.1.0 and reopen if this is still an issue
