### ISSUE TITLE
Cucumber can not find ES6 step_defenitions

### ISSUE THREAD

**Issue by artemjackson** [cucumber/cucumber-js#497]
I'm trying to write step_defentions on ES6 with option `js:babel-core/register`.
It works well with ES5 variant of `foo_steps.js`:
```
module.exports = function() {
    this.Given("foo", function(){});
}
```
But with ES6 variant of `foo_steps.js`:
```
export default function() {
    this.Given("foo", () => {});
}
```
It can not find step_defenitions:
```
You can implement step definitions for undefined steps with these snippets:

this.Given(/^foo$/, function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback.pending();
});
```
Tried with options:
```
format: "pretty",
require: "features/step_definitions/*.js",
compiler: "js:babel-core/register"
```

**Comment by charlierudolph** [comment]
So the problem appears to be that babel will make `foo_steps.js` export an object: `{ default: [Function] }`
and cucumber expects step definitions / support files to export a function.

**Comment by artemjackson** [comment]
Thank you for feedback.
Seems that [it should work](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=export%20default%20function()%20%7B%0A%20%20%20%20this.Given(%22foo%22%2C%20()%20%3D%3E%20%7B%7D)%3B%0A%7D) with Babel 5.
Can you suggest something how to make it work with Babel 6?

**Comment by artemjackson** [comment]
Seems that [this plugin](https://www.npmjs.com/package/babel-plugin-add-module-exports) can solve the issue.
Closed because issue is not related to cucumber itself.

**Comment by charlierudolph** [comment]
Glad to hear there is already a solution. I'm surprised babel 6 removed that behavior. Definitely breaks its interoperability with other js libraries.

**Comment by jeremyrajan** [comment]
Something similar is happening to me as well. I am using webdriver.io here. https://github.com/webdriverio/wdio-cucumber-framework/issues/11

**Comment by mkusher** [comment]
Actually, this plugin is a hack, because babel 6 tries to emulate real behavior of es6 modules. I think it is a good idea to add check for default in exports.
