### ISSUE TITLE
Rerun feature troubles

### ISSUE THREAD

**Issue by fdubost** [cucumber/cucumber-js#499]
Hi !
Thank you for this great library :smiley: 

I have some troubles with rerun feature :
* it seems that the `@` in the file name indicates to cucumber that we run a "rerun" file but we can't do this `cucumberjs tests/features/@rerun.txt`,
* when we run `cucumberjs @rerun.txt`, it run not only the rerun scenarios but also all the features in the current directory and its descendents.

Is these problems known ?

**Comment by charlierudolph** [comment]
> it seems that the @ in the file name indicates to cucumber that we run a "rerun" file but we can't do this cucumberjs tests/features/@rerun.txt

Good point, I'll make this work.

> when we run cucumberjs @rerun.txt, it run not only the rerun scenarios but also all the features in the current directory and its descendents.

Auhh, I see the bug. Thanks for the report.

**Comment by JasonSmiley208** [comment]
Hi!

I am having a similar error, except saying `cucumber-js @rerun.txt` gives me an error saying "no such file or directory, open '@rerun.txt'.

This seems like a bug...

**Comment by charlierudolph** [comment]
@JasonSmiley208  that should only be happening if you don't have the file `@rerun.txt` in your current working directory. Is that the case?

**Comment by JasonSmiley208** [comment]
well, my file is called "rerun.txt", not "@rerun.txt". Is this what you mean? (It is in the root directory)

**Comment by charlierudolph** [comment]
So cucumber-js will actually load the file whatever file path is passed. It does not strip the @ sign before loading a file. However, the fact that it starts with an @ sign causes cucumber-js to treat it differently.

Thus if you rename rerun.txt to @rerun.txt, it should work, though may run into the bug reported in this thread.

**Comment by JasonSmiley208** [comment]
That works for me. Thanks!

**Comment by charlierudolph** [comment]
@fdubost can you actually give more information for when `cucumber-js @rerun.txt` runs all the scenarios? I do have that happen when `@rerun.txt` (which I don't think is wrong), but not when there is anything in `@rerun.txt`

**Comment by charlierudolph** [comment]
Nevermind @fdubost got it.

**Comment by fdubost** [comment]
It works well, thank you :+1:

**Comment by spkjess** [comment]
It works for me to
1. create `@rerun.txt`
2. run `cucumber-js -f rerun --format rerun:@rerun.txt`
3. run `cucumber-js @rerun.txt`

**Comment by thangakumard** [comment]
@JasonSmiley208  @fdubost  @spkjess - Any one of you please help me on
1. How to generate rerun.txt
2. How to rerun the test cases in rerun.txt

currently I am using cucumberjs with Selenium-Webdriver. I am using the below command in package.json to run my test cases.  All my feature files are in 'src' folder.  Babel transformed dependent files are in 'dist' folder. 

`"test": "node_modules/.bin/cucumberjs src -r dist/steps -r dist/library -r dist/helper",`

Please help me to modify the command to capture the failed test cases and to rerun those cases

**Comment by charlierudolph** [comment]
@thangakumard Using the rerun formatter is two parts. First you generate the rerun file and then on the next run that is what you run.

* On the first run add the parameters `--format rerun:@rerun.txt`
* After a failed run, remove any arguments specifying the locations of feature files and add `@rerun.txt`

The `@` is the only important part of the filename as then cucumber parses it as rerun file. Otherwise you can name the file whatever you want. I'll add this short explanation to the docs

**Comment by thangakumard** [comment]
@charlierudolph - Thanks for your response. it is working fine :+1:  . Also I was using old version of cucumberjs. once I upgraded to latest version it is working as expected
