### ISSUE TITLE
Calling fs.mkdir does not invoke callback function

### ISSUE THREAD

**Issue by vsashidh** [cucumber/cucumber-js#504]
This issue occurs on the following setup:
platform: nodejs
OS : Windows 7 enterprise

Description: When executing cucumber-js, if a scenario invokes fs.mkdir, the callback function  for fs.mkdir never get executed.  

In the world constructor function, following statements should reveal the problem:

	var driver = require('../../lib/index.js');
	var xfs = require('fs');

	function World() {

		xfs.mkdir('C:\Users\vsashidharan\.config\browser-launcher2',511,function (er){
			console.log("Successfully called xfs.mkdir");
			if(er)
				console.log("Some error was encountered : " + er);
		});
	}

	module.exports = function() {
		this.World = World;
	};

**Comment by charlierudolph** [comment]
I cannot image cucumber somehow effects the node fs module. The world constructor function is synchronous, so you should probably use the synchronous mkdir, or if you want to use the asynchronous mkdir please use a before hook, so you can have cucumber actually wait for mkdir to complete.

**Comment by vsashidh** [comment]
Adding it to the before hook resolved the issue. thanks. You may close this issue.
