### ISSUE TITLE
Why to write such code " keyword:     'Background' " ???

### ISSUE THREAD

**Issue by olegdovger** [cucumber/cucumber-js#507]
https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/listener/json_formatter.js#L97
https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/listener/json_formatter.js#L99

Why it was neccessary to write such code?

How about

```
keyword:  background.getKeyword()
```

**Comment by charlierudolph** [comment]
line 99 is needed. You are correct about line 97 though.
