### ISSUE TITLE
Question: Can I get the current cucumber options inside of the After/Before hooks?

### ISSUE THREAD

**Issue by JasonSmiley208** [cucumber/cucumber-js#509]
Just wondering.

Basically, I want to see if the JSON format is being used and if it is, I want to know where its located so I can use the cucumber-html-report plugin to generate an HTML report.

**Comment by charlierudolph** [comment]
Currently no. The before/after hooks should only be dealing with actually running the scenario and shouldn't care about the output. I'd suggest using another script to convert the cucumber's json output to html using that plugin.

**Comment by JasonSmiley208** [comment]
Ok, thanks!
