### ISSUE TITLE
Whitespace at the end of keywords in JSON output

### ISSUE THREAD

**Issue by bricas** [cucumber/cucumber-js#512]
Although this is certainly non-fatal, it appears most keywords have an extra space in the string when using the JSON output format. e.g.:

          {
            "keyword": "Before ",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 4089243
            },
            "match": {}
          },

I've noticed the same for Given, Then, And and After -- Scenario appears unaffected.

**Comment by charlierudolph** [comment]
That step keyword (apart from Before/After) come from gherkin parsing the cucumber file. Before, After, Around were made to match though they can definitely have their extra space removed. 

@aslakhellesoy can you give some background as to why the keyword ends with a space?

**Comment by aslakhellesoy** [comment]
Because of translations like Chinese and Japanese.

Words don't have spaced between them in Chinese. So we put the space in the Gherkin keyword.
