### ISSUE TITLE
Background portion written to JSON output in its own section

### ISSUE THREAD

**Issue by bricas** [cucumber/cucumber-js#513]
If i have a "Background" section to my Gherkin file, it appears to be written to the JSON output in the same style as a regular scenario. The steps in the "Background" also appear along side each scenario as one would expect.

    "elements": [
      {
        "name": "Override Page Load Timeout",
        "keyword": "Background",
        "description": "",
        "type": "background",
        "line": 4,
        "steps": [
          {
            "name": "I set pageLoadTimeout to 30000",
            "line": 5,
            "keyword": "Given "
          }
        ]
      },

later on in a scenario...

          {
            "keyword": "Before ",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 844095
            },
            "match": {}
          },
          {
            "name": "I set pageLoadTimeout to 30000",
            "line": 5,
            "keyword": "Given ",
            "result": {
              "status": "passed",
              "duration": 6665066
            },
            "match": {}
          },

I'm unsure if this is the desired behaviour, but it definitely triggers the jenkins cucumber plugin to throw warnings.

**Comment by charlierudolph** [comment]
@jbpros the background section appears to have been added in the initial JSON formatter. Any reason for it to be there? 

Note: in my gherkin3 PR I removed the background elements from the json output.

**Comment by charlierudolph** [comment]
Looking at cucumber-ruby, they have a background element before each scenario element that it applies to (with the result of running the step). I prefer cucumber-js's output where the background steps simply appear in each scenario's steps.

**Comment by charlierudolph** [comment]
This was fixed with the 1.0 release as the background section no longer appears
