### ISSUE TITLE
When two newline characters are used in table then it is not taking the second new line character

### ISSUE THREAD

**Issue by Shilpi85** [cucumber/cucumber-js#518]
If I have a table which uses two newline character then it is not taking the next newline. See example below:

-----------------------------------------------------------------------
Given I have a table to verify
When I change status from `<statusFrom>` to `<statusTo>` with the condition `<condition>`
|   statusFrom |   statusTo   |  condition |
| In Review | Active | Warning: invalid Status\nWarning: missing Status\nWarning: invalid transition|

-----------------------------------------------------------------------

so when i run the above Scenario for the `<condition>,` it is reading the first \n with newline but for the second newline it is not reading it as a newline.

Any workaround for this will help!

**Comment by jbpros** [comment]
This is a bug in Gherkin2. We're in the process of [integrating Gherkin4](https://github.com/cucumber/cucumber-js/pull/450) which [doesn't display that bug](https://github.com/cucumber/gherkin/pull/206). 

#450 needs to be merged for this to be solved.

**Comment by charlierudolph** [comment]
Closed in a5fd8251918c278ab2e389226d165cedb44df14a
