### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by antalutrazvan** [cucumber/cucumber-js#519]
Running BDD tests in karma with PhantomJS browser cannot find the Error.captureStackTrace method.

This is the error I get:
TypeError: 'undefined' is not a function (evaluating 'Error.captureStackTrace(err, arguments.callee)')
at /resources/node_modules/cucumber/release/cucumber.js:11070

**Comment by charlierudolph** [comment]
Hmm, so the library we are currently using [callsite](https://github.com/tj/callsite/blob/5942832a8e22d05f6d9450c688e2bb76f3b5a333/index.js#L6) uses that method. We could try another library that doesn't use it like [callsites](https://github.com/sindresorhus/callsites/blob/9e7459877c0ed32c70f9e1e3e7cf29f5d1ff192d/index.js)

**Comment by charlierudolph** [comment]
I believe this was fixed in 1.2.1 where we switched from callsite to stacktrace-js. Please reopen if this is still an issue with the latest version
