### ISSUE TITLE
Please document datatable API

### ISSUE THREAD

**Issue by leegee** [cucumber/cucumber-js#520]
Issue #326 mentioned a desire to document the API for data tables -- has this ever been done?

It would be helpful to have an example of using `<this>` too.

**Comment by charlierudolph** [comment]
This is already in the [README](https://github.com/cucumber/cucumber-js#data-table) with a link to an example.

**Comment by leegee** [comment]
Sorry, so it is.  I'm new to Cucumber, and though a feature with <this> was part of a data table. It's not, I see — though it's not documented. I'd open a ticket for it, if I knew better the terminology....
