### ISSUE TITLE
Add --snippets [promise|callback] option

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#524]
Just like [Cucumber-JVM](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/resources/cucumber/api/cli/USAGE.txt#L21) it would be nice to tell Cucumber.js what kind of snippets you want.

I always want Promise-based ones ;-)

**Comment by charlierudolph** [comment]
Hardest part here is we need a way for pending promises, since the default step is suppose to pending. Currently we have
```js
Given(/a step/, function(callback) {
  callback.pending()
});
```
We could add support for pending steps in all types of cases if we move to
```js
// synchronous
Given(/a step/, function() {
  return 'pending';
});

// callback
Given(/a step/, function(callback) {
  callback(null, 'pending');
});

// promises (based on support)
Given(/a step/, function() {
  return Promise.resolve('pending');
});
```
