### ISSUE TITLE
Can step timeout be set inside the step itself?

### ISSUE THREAD

**Issue by pke** [cucumber/cucumber-js#528]
I am embracing the original cucumber idea of "outside-in". For that the default timeouts of steps stay in the way. Cucumber is not a tool to quickly test my app but to run it in an automated fashion and test its behavior. 

```
this.When(/^I use the app for (\d+|\w+) seconds$/, function (seconds, callback) {
  if (seconds == "some") {
    seconds = 1
  }
  console.log("Waiting for " + seconds + " seconds")
  setTimeout(callback, seconds * 1000)
})
```

This step could be used to wait for a notification to pop up 30 seconds after app start.

Is there a way to set the timeout of the step to `second*1000` from inside the step?

**Comment by gd46** [comment]
Are you using protractor to drive your tests? If so you can use the following: 

`browser.wait(function(){
 // You put your selector here and check for isDisplayed
}, 3000, 'Notification did not show after 30 seconds');`

**Comment by pke** [comment]
No idea what protractor is. Have to check out out

**Comment by pke** [comment]
Maybe this could be solved with a around hook, that sets the default global timeout before calling the scenario?

**Comment by gd46** [comment]
I would recommend looking into Protractor, although it isnt necessary to solve your problem. And maybe I misunderstood your original question. So it looks like your current implementation sets the timeout from the step, are you looking to do it dynamically from inside the step?

**Comment by pke** [comment]
The cucumber default timeout is 5000ms. And the only way I see to set it to a higher values is to set it globally. Or is there a way to define a step timeout?

**Comment by gd46** [comment]
Yes, you can either set it globally or you can do: 

// features/step_definitions/my_steps.js

var mySteps = function () {
  this.Given(/^a slow step$/, {timeout: 60 * 1000}, function(callback) {
    // Does some slow browser/filesystem/network actions
  });
};

module.exports = mySteps;

This is the example on the cucumberjs readme

**Comment by pke** [comment]
I knew that. That's not what I mean. The timeout should be specified by a step param. Please check my OP.

**Comment by charlierudolph** [comment]
Currently what you are asking for is not possible. setTimeout is called before the step definition is executed. In your example, maybe you could set the step timeout to the max seconds that step would be called with?

**Comment by gd46** [comment]
Sorry if I misunderstood your OP. But I don't think I understand your full tech stack. What are you using to drive your tests? Earlier I mentioned protractor, and you said no. Are you using selenium then? You need something that drives your tests to manipulate the browser. Usually in something like that you can do what your asking. I wouldn't recommend testing it through timing out cucumber steps because them if it errors out your error will be a step timeout instead of an assertion with a proper error message stating what the cause of the error was.

**Comment by pke** [comment]
I am not using a browser to run the tests. They run headless in nodejs. I think I have found a solution already that doesn't involve a timeout on cucumbers side. Will report back here eventually when I got it running.
