### ISSUE TITLE
Multiple promises in a step cause strange behavior

### ISSUE THREAD

**Issue by gd46** [cucumber/cucumber-js#532]
Tech Stack: 

Cucumber: 0.9.4
Angular: 1.5
Protractor: 2.5.1
Chai: ^2.2.0
Chai-As-Promised: ^5.1.0

I have recently started to see some strange behavior in my tests, and I was hoping to get this resolved whether it is something I am doing, or an issue somewhere in my tech stack. In my assertion steps sometimes I have a several assertions happening in which I use chai-as-promise, and I always return just the last assertion. Recently I am seeing depending on the scenarios I run and if the step passes that has a bulk of promises in it or a bulk of assertions in it that sometimes those promises are getting resolved later on in other scenarios and failing other scenarios with selectors that are coming from steps that were run scenarios before. My question is, is there something I can be doing different, or is this an issue in the tech stack, because I didnt seem to have these issues prior to Angular 1.4. So my thinking is somehow that upgrade doesnt work nicely with the cucumber. I would really like some clarification into this issue, so if you need more information or more example I would be happy to provide them. Thank you in advance. 

Some more info I found later today: [cucumber-chai-wd](https://github.com/sebsorin/cucumber-chai-wd) , I havent had the opportunity to try this yet. But I was wondering if this is absolutely necessary as I thought cucumber was handling this already?

**Comment by charlierudolph** [comment]
cucumber-js's promise support is very simple. If your step returns a promise, cucumber-js will wait for that promise to resolve/reject. 

If you have multiple promises that need to be waited on, you need to convert it into a single promise by either chaining them or waiting for them all to complete with something like node's `Promise.all`. 

I believe Protractor internally makes sure its promises are executed in the order you call them, so returning the final promise should be enough.

**Comment by gd46** [comment]
Thank you so much for the reply. That does work but we noticed that something in our stack updated recently I wasn't aware of before. We are going to be looking into that today. But it's more strict on how you return promises it seems. And going back looking at my steps I was also missing a couple returns.

**Comment by gd46** [comment]
Im seeing issues when I have a large amount of assertions in one step. Is there a limit to how many you can have in one step? 

The below seems to not finish in one step and fails later on in another step when it is no longer in view anymore: 

expect(directDepositObj.viewAccountCard.deleteBtn.isPresent(), 'Delete button should not be present').to.become(false);
    
    // Pending Icon
    expect(directDepositObj.viewAccountCard.pendingIcon.isDisplayed(), 'Pending icon is not displayed').to.become(true);
    
    // Account Name
    expect(directDepositObj.viewAccountCard.accountName.isDisplayed(), 'Account name is not displayed').to.become(true);
    expect(directDepositObj.viewAccountCard.accountName.getText(), 'Account name does not equal deleted account name').to.eventually.equal(pay.directDepositChoices.deletedAccount);
    
    // Pending Message
    expect(directDepositObj.viewAccountCard.pendingHandIcon.isDisplayed(), 'Pending Hand icon is not shown').to.become(true);
    expect(directDepositObj.viewAccountCard.pendingMessage.isDisplayed(), 'Pending message is not shown').to.become(true);
    expect(directDepositObj.viewAccountCard.pendingMessage.getText(), 'Pending message should have pending delete message').to.eventually.contain('Delete waiting for approval from');
    
    // Current Message
    expect(directDepositObj.viewAccountCard.currentHandIcon.isDisplayed(), 'Current Hand icon is not shown').to.become(true);
    expect(directDepositObj.viewAccountCard.currentMessage.isDisplayed(), 'Current message is not shown').to.become(true);
    expect(directDepositObj.viewAccountCard.currentMessage.getText(), 'Current message should equal: ').to.eventually.equal('Current until change approved');
    
    expect(directDepositObj.viewAccountCard.currentAccountNumberValue.isDisplayed(), 'Current account number is not displayed').to.become(true);
    expect(directDepositObj.viewAccountCard.currentAccountNumberValue.getText(), 'Current account number should equal current account number value').to.eventually.equal(pay.directDepositChoices.accountsArry[0].accountNumber);
    expect(directDepositObj.viewAccountCard.currentRoutingNumberValue.isDisplayed(), 'Current routing number is not displayed').to.become(true);
    expect(directDepositObj.viewAccountCard.currentRoutingNumberValue.getText(), 'Current account number should equal current routing number value').to.eventually.equal(pay.directDepositChoices.accountsArry[0].routingNumber);
    expect(directDepositObj.viewAccountCard.currentSpecifiedAmountValue.isDisplayed(), 'Current specified amount is not displayed').to.become(true);
    expect(directDepositObj.viewAccountCard.currentSpecifiedAmountValue.getText(), 'Current specified amount should equal current specified amount valuer').to.eventually.equal(pay.directDepositChoices.accountsArry[0].accountAmount);
    return expect(directDepositObj.viewAccountCard.cancelRequestBtn.isDisplayed(), 'Cancel request button should be shown').to.become(true);


But if I wrap it in a Q.all it seems to pass:

return Q.all([
      expect(directDepositObj.viewAccountCard.deleteBtn.isPresent(), 'Delete button should not be present').to.become(false),

      // Pending Icon
      expect(directDepositObj.viewAccountCard.pendingIcon.isDisplayed(), 'Pending icon is not displayed').to.become(true),

      // Account Name
      expect(directDepositObj.viewAccountCard.accountName.isDisplayed(), 'Account name is not displayed').to.become(true),
      expect(directDepositObj.viewAccountCard.accountName.getText(), 'Account name does not equal deleted account name').to.eventually.equal(pay.directDepositChoices.deletedAccount),

      // Pending Message
      expect(directDepositObj.viewAccountCard.pendingHandIcon.isDisplayed(), 'Pending Hand icon is not shown').to.become(true),
      expect(directDepositObj.viewAccountCard.pendingMessage.isDisplayed(), 'Pending message is not shown').to.become(true),
      expect(directDepositObj.viewAccountCard.pendingMessage.getText(), 'Pending message should have pending delete message').to.eventually.contain('Delete waiting for approval from'),

      // Current Message
      expect(directDepositObj.viewAccountCard.currentHandIcon.isDisplayed(), 'Current Hand icon is not shown').to.become(true),
      expect(directDepositObj.viewAccountCard.currentMessage.isDisplayed(), 'Current message is not shown').to.become(true),
      expect(directDepositObj.viewAccountCard.currentMessage.getText(), 'Current message should equal: ').to.eventually.equal('Current until change approved'),

      expect(directDepositObj.viewAccountCard.currentAccountNumberValue.isDisplayed(), 'Current account number is not displayed').to.become(true),
      expect(directDepositObj.viewAccountCard.currentAccountNumberValue.getText(), 'Current account number should equal current account number value').to.eventually.equal(pay.directDepositChoices.accountsArry[0].accountNumber),
      expect(directDepositObj.viewAccountCard.currentRoutingNumberValue.isDisplayed(), 'Current routing number is not displayed').to.become(true),
      expect(directDepositObj.viewAccountCard.currentRoutingNumberValue.getText(), 'Current account number should equal current routing number value').to.eventually.equal(pay.directDepositChoices.accountsArry[0].routingNumber),
      expect(directDepositObj.viewAccountCard.currentSpecifiedAmountValue.isDisplayed(), 'Current specified amount is not displayed').to.become(true),
      expect(directDepositObj.viewAccountCard.currentSpecifiedAmountValue.getText(), 'Current specified amount should equal current specified amount valuer').to.eventually.equal(pay.directDepositChoices.accountsArry[0].accountAmount),
      expect(directDepositObj.viewAccountCard.cancelRequestBtn.isDisplayed(), 'Cancel request button should be shown').to.become(true)
    ]);

But in some places I have a lot of assertions and it passes fine without Q.all. So Im wondering why isnt it waiting long enough for some steps and not others?

**Comment by charlierudolph** [comment]
> Im seeing issues when I have a large amount of assertions in one step. Is there a limit to how many you can have in one step?

There is no limit to how many assertions can appear in a single step. 

> But in some places I have a lot of assertions and it passes fine without Q.all. So Im wondering why isnt it waiting long enough for some steps and not others?

cucumber-js will only wait for whatever promise you pass to it. If you return just the last promise, cucumber-js will only wait on that one. If other promises fail, it may cause errors if they throw, but otherwise will simply be ignored because cucumber-js doesn't know about them

**Comment by gd46** [comment]
Thank you for the great response, how do you recommend returning multiple assertions so that cucumber know about it? Because we use a lot of steps that almost always have more than one assertion in the step, and they seemed to work ok until I have a lot of assertions. I just found today after some refactoring, that the scenario that was causing me issues, if I took the one step that has a lot of assertions and broke it up it worked fine. But I have a need for using multiple assertions in a single step. Advice?

**Comment by charlierudolph** [comment]
Q.all is probably your best bet as it creates a promise that resolves when all the promises resolve or rejects when any promise rejects.

**Comment by gd46** [comment]
Thank you for your advice, after making some changes and using Q.all on the two steps with a lot of promises it passes. I suppose my question is I don't understand why that is necessary if Im using cha-as-promised. Shouldn't all of the promises be resolved before the test moves to the next step? And I found this: https://github.com/sebsorin/cucumber-chai-wd I was looking into it and was wondering if I can get it to work if this is something that you would recommend or if this is something that would ever be built into cucumber itself?

**Comment by charlierudolph** [comment]
`chai-as-promised` just gives you expectations that work with and return promises. `protractor` and `cucumber-chai-wd` appear to chain promises based on their call order in an attempt to make things like Q.all unnecessary. 

Although this can be a cool idea that shortens your code, I don't like it because I believe it makes promises harder to understand by making them look synchronous. If you create a promise by some other means you may expect it to just work, but if the promise is left unknown to both the library that orchestrates promises and cucumber, it won't. 

I don't foresee `cucumber-chai-wd` ever bring built into cucumber as cucumber does not need to be used with a webdriver. Automating browsers test may be a popular use for cucumber, but its far from the only use.

**Comment by gd46** [comment]
Thank you so much for you help

**Comment by gd46** [comment]
After looking at the cucumber-chai-wd module I was hoping that would help my issue without having to add Q.all everywhere. But I get this error: Error: step definition has 0 arguments, should have 1 (if synchronous or returning a promise) or 2 (if accepting a callback). I am not too familiar with the World object, would you be able to explain how it works?

**Comment by charlierudolph** [comment]
That error comes from cucumber-js which is verifying that the step definition has the proper number of arguments.  wraps each step definition in a function with 0 arguments. 

In order for `cucumber-chai-wd` to be used with the current version of cucumber-js one of the two things need to happen:

* `cucumber-chai-wd` needs to be updated to wrap each step definition in a function with the same number of arguments (preferable as the error checking can stay in place)
* The option asked for in #514 is introduced, but I am leaning away from that at the moment

**Comment by gd46** [comment]
Thank you so much for clarifying this issue, any idea how I can update the wrapper function to wrap each step definition in a function with the same number of arguments? I greatly appreciate your help, I would ask the own of cucumber-chai-wd but their is no contact info. Again thanks in advance this would be a huge help in our testing efforts as it isnt ideal to add Q.all everywhere.

**Comment by gd46** [comment]
Hi I was wondering if you could help me understand the changes that would need to happen to cucumber-cha-wd for it to work with latest cucumber? I have t heard anything back from the owner of the repo and was looking to see if I can do it myself and see if this would help stablize my test suite. Thanks again in advance.

**Comment by charlierudolph** [comment]
Closing as it appears sebsorin/cucumber-chai-wd#1 has been resolved. Please reopen if needed.
