### ISSUE TITLE
Data tables diff support

### ISSUE THREAD

**Issue by lbud** [cucumber/cucumber-js#534]
Any plans to add a [diff](https://github.com/cucumber/cucumber-ruby/blob/34760f7286d6ce5c2f4291e09e29335e6dcb1e8c/lib/cucumber/multiline_argument/data_table.rb#L338) method to data tables? :ok_hand:

**Comment by ryanwmarsh** [comment]
I'll work on it if no one else wants too

**Comment by charlierudolph** [comment]
I think this would be awesome to have. @ryanwmarsh go for it, I doubt I would be able to get to this anytime soon

**Comment by ryanwmarsh** [comment]
@charlierudolph any chance my other PR could get some love first? #531 😉

**Comment by lbud** [comment]
@ryanwmarsh that would be awesome :bow:

**Comment by TheMarex** [comment]
What is the status here seeing that the milestone was removed? We currently need to work around this:

https://github.com/Project-OSRM/osrm-backend/blob/master/features/support/exception_classes.js#L81-L131

Of course I would very much prefer to have this code upstream.

**Comment by charlierudolph** [comment]
I don't believe this is being worked on. Would be awesome to have that code in.

**Comment by emiltin** [comment]
any news?

**Comment by charlierudolph** [comment]
Going to close this in favor of cucumber/cucumber#210
