### ISSUE TITLE
The example does not run propery on Firefox

### ISSUE THREAD

**Issue by horatiucherebetiu** [cucumber/cucumber-js#538]
When running  the example I get: "TypeError: Error.captureStackTrace is not a function" at line: "cucumber.js (line 245, col 121)"

**Comment by charlierudolph** [comment]
Hmm, may have to switch over to https://github.com/stacktracejs/stacktrace.js/ if we want stack traces to work in all browsers. The promise API makes this a bit harder to work with as we are currently using a lib that returns stacktraces synchronously.

**Comment by jairoGilC** [comment]
It can be very useful to add a clarification saying that browser support it next to link documentation
