### ISSUE TITLE
Lexing error references non-existent Wiki page

### ISSUE THREAD

**Issue by leegee** [cucumber/cucumber-js#540]
```
Error: Lexing error on line 32: 'and the row 1 <NAME> should display <NAME>'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
```

**Comment by charlierudolph** [comment]
Thanks for the report that does need to be fixed. In the short term, here is the webpage it was trying to point to: https://github.com/cucumber/gherkin2/wiki/lexingerror

**Comment by charlierudolph** [comment]
So this error came from gherkin2, which is no longer maintained. We will be updating from gherkin2 to gherkin3 in the next release which will resolve this issue.
