### ISSUE TITLE
rerun not working properly for windows

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-js#542]
when I try to rerun failed scenarios, it run all scenarios in a feature in Windows.
I am using 0.9.5 cucumber with protractor 2.5.1 with node 0.12 or 4.2.2

Also, when I try to validate by cucumber.js itself with rerun_formatter.feature example, I am getting 
```
    When I run cucumber.js                                               # featu
res\step_definitions\cli_steps.js:12
      Error: spawn UNKNOWN
          at exports._errnoException (util.js:874:11)
          at ChildProcess.spawn (internal/child_process.js:298:11)
          at exports.spawn (child_process.js:339:9)
          at exports.execFile (child_process.js:141:15)
          at World.<anonymous> (C:\Users\SSAuto\project\cucumber-js\features\ste
p_definitions\cli_steps.js:17:5)
          at doNTCallback0 (node.js:419:9)
```

**Comment by charlierudolph** [comment]
Hmm, lets resolve the spawn issue first. Node has some docs about [execFile](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows) which warns it may not work on windows. Do you think you could create a PR converting from `execFile` to `exec` or `spawn`? I think its more valuable if its done by someone with a windows machine, I use a Mac, who can verify it fixes the problem.

**Comment by jlin412** [comment]
If you point me where the code is, I can take a crack at it.

**Comment by charlierudolph** [comment]
Its actually in the stack trace you posted 
```
at World.<anonymous> (C:\Users\SSAuto\project\cucumber-js\features\step_definitions\cli_steps.js:17:5)
```
So relative to the project, it's in the file `features\step_definitions\cli_steps.js`, line 17, column 5.

**Comment by charlierudolph** [comment]
@jlin412 have you gotten a chance to look at this?

**Comment by jlin412** [comment]
@charlierudolph I spent some time this weekend to look at it.
It is a little more complicated than I thought.  I am not able to make it work with either exec or spawn yet.  I couldn't even get it work in mac version.  Perhaps, you could lend a hand.  I am also confused by 
https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows
Does it mean that I need to spawn a cmd.exe and use a bat file?

This is one of my try with exec and it has error of 
     Error:
     Error: Command failed: /bin/sh -c /Users/linj/cucumber-js/bin/cucumber.js@rerun.txt
     /bin/sh: /Users/linj/cucumber-js/bin/cucumber.js@rerun.txt: No such file or directory

```
var cliSteps = function cliSteps() {
  var colors = require('colors/safe');
  var exec = require('child_process').exec;
  var path = require('path');

  var helpers = require('../support/helpers');
  var normalizeText = helpers.normalizeText;
  var getAdditionalErrorText = helpers.getAdditionalErrorText;

  var executablePath = path.join(__dirname, '..', '..', 'bin', 'cucumber.js');

  this.When(/^I run cucumber.js(?: from the "([^"]*)" directory)?(?: with `(|.+)`)?$/, {timeout: 10000}, function(dir, args, callback) {
    args = args || '';
    var world = this;
    var cwd = dir ? path.join(this.tmpDir, dir) : this.tmpDir;

    exec(executablePath + args.split(' '), {cwd: cwd}, function (error, stdout, stderr) {
       world.lastRun = {
         error:  error,
         stdout: colors.strip(stdout),
         stderr: stderr
       };
       callback();
     });
  });
```

**Comment by charlierudolph** [comment]
Reading those docs again I'm uncertain if thats what really causing this issue, but I still thought it would be worth trying. 

I appears to me that error you're hitting is caused by a missing space between the arguments and the executablePath. Also since you are creating a string, you shouldn't be splitting the args anymore.
```js
exec(executablePath + args.split(' '), //...
// should be
exec(executablePath + ' ' + args, //...
```

**Comment by jlin412** [comment]
Ok, It worked for mac version.  When I tried in windows, it shows a different error now:

```
      Error:
      Error: Command failed: C:\Windows\system32\cmd.exe /s /c "cucumber-js "
      .
      stderr:

          at World.<anonymous> (C:\Users\SSAuto\project\cucumber-js\features\ste
p_definitions\cli_steps.js:54:13)
          at doNTCallback0 (node.js:419:9)
          at process._tickCallback (node.js:348:13)
```

I am not sure if it is error as expected.  When I tried running cucumber-js --format rerun:@rerun.txt, every scenario seems to be running.

``` javascript
var cliSteps = function cliSteps() {
  var colors = require('colors/safe');
  var exec = require('child_process').exec;
  var path = require('path');

  var helpers = require('../support/helpers');
  var normalizeText = helpers.normalizeText;
  var getAdditionalErrorText = helpers.getAdditionalErrorText;

  // var executablePath = path.join(__dirname, '..', '..', 'bin', 'cucumber-js');
  var executablePath = 'cucumber-js';

  this.When(/^I run cucumber.js(?: from the "([^"]*)" directory)?(?: with `(|.+)`)?$/, {timeout: 10000}, function(dir, args, callback) {
    args = args || '';
    var world = this;
    var cwd = dir ? path.join(this.tmpDir, dir) : this.tmpDir;

    exec(executablePath + ' ' + args, {cwd: cwd}, function (error, stdout, stderr) {
       world.lastRun = {
         error:  error,
         stdout: colors.strip(stdout),
         stderr: stderr
       };
       callback();
     });
  });
```

**Comment by charlierudolph** [comment]
I want to try and add windows ci to our build process. Will try and setup appveyor for this

**Comment by charlierudolph** [comment]
Just got appveyor setup and its passing on the current version for node 0.12, 4, and 6. Please reopen if there is anything else you'd like to discuss.
