### ISSUE TITLE
--focus flag

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#545]
@kevgo thoughts on the following to better support your workflow which may be disrupted by #521

Using the existing rerun functionality, but with a new `--focus` flag, it will run only the first feature your the rerun file. If the test passes, it is removed from the rerun file, otherwise the rerun file is left unchanged. 

Example:

```
> cucumber-js
Scenarios A, B, and C fail
Scenarios D, E, and F pass

> cucumber-js @rerun.txt
Only runs scenarios A, B, and C (which fail)

> cucumber-js --focus @rerun.txt
Only runs scenario A (which fails)

# Fix Failure A

> cucumber-js --focus @rerun.txt
Only runs scenario A (which passes)

> cucumber-js --focus @rerun.txt
Only runs scenario B (which fails)

# Fix Failure B

> cucumber-js --focus @rerun.txt
Only runs scenario B (which passes)

> cucumber-js --focus @rerun.txt
Only runs scenario C (which fails)

# Fix Failure C

> cucumber-js --focus @rerun.txt
Only runs scenario C (which passes)

> cucumber-js --focus @rerun.txt
Reruns the whole test suite because your @rerun.txt file is empty 
```

**Comment by aslakhellesoy** [comment]
I love this idea!

**Comment by kevgo** [comment]
Me too. This could be almost better than my old workflow (of copy-and-pasting the path to a failing scenario into a new terminal) in resolving one failure at a time!

What do you think about naming this command-line switch `--first`, as in "rerun the first failing scenario"?

**Comment by aslakhellesoy** [comment]
Or `--pop`

**Comment by jbpros** [comment]
`--first` sounds like a filter only. `cucumber-js --first @rerun.txt` sounds like "only run the first item in the rerun file", nothing about removing it if it passed.

`--pop` is confusing. On JS arrays, it'd (systematically) remove the latest item. 

Git stash's `pop` is also working on the latest item.

My preference goes to `--focus` as we can refer to the "focus(sed) rerun" in the docs without any ambiguities. The workflow this term encapsulates would be clear.

**Comment by kevgo** [comment]
If we take references from programming languages, `--shift` would correspond to the command for removing the first (instead of the last) element from an array in many languages (Ruby, JavaScript).

**Comment by kevgo** [comment]
Another possibility could be `--resolve`. Meaning this switch activates a behavior/workflow that helps the user resolve failing tests by making them pass one by one.

```
$ cucumber-js --resolve @rerun.txt
```

**Comment by aslakhellesoy** [comment]
It reminds me a little of the UI of `git rebase --continue`. Stop at the first error (conflict) and ask user to `--continue` when that's fixed. 

So maybe `--continue` ?

**Comment by mattwynne** [comment]
The idea is that this is like a preference - you put it in a profile somewhere, effectively saying "I'm someone who prefers to focus on one test at a time" and then cucumber acts according to that preference in a few different contexts, as described above by Charlie's examples.

**Comment by charlierudolph** [comment]
@aslakhellesoy @mattwynne @kevgo @jbpros 

In 2.0, I updated fail fast and rerun to work together better. When using the two, the rerun file contains the failure and all the skipped scenarios. Thus using `cucumber-js --fail-fast @rerun.txt` will run until the first failure if there is one. After fixing that scenario, it basically picks up where it left off. Inspired by #653.

What do you guys thing about that?

**Comment by charlierudolph** [comment]
`2.0.0-rc.1` is available with this if you'd like to try it out

**Comment by kevgo** [comment]
Sounds good to me!

**Comment by aslakhellesoy** [comment]
That's brilliant @charlierudolph. We can never get enough of usability improvements like that!

**Comment by mattwynne** [comment]
👏

**Comment by jbpros** [comment]
💯
