### ISSUE TITLE
No way to set timeout for Hooks

### ISSUE THREAD

**Issue by tebs1200** [cucumber/cucumber-js#547]
If you have some long running processes that need to execute in a hook (like setting up sessions in `Before`), there's no way to specify a specific timeout for the hook.

It would be useful if hooks had the same capability as test steps, and could take an optional argument that is an object containing a timeout.

**Comment by charlierudolph** [comment]
Yes they should. The fact that hooks already have an optional tags argument is probably why this wasn't implemented at the same time as steps. I'll merge the tags into the object as a part of this.
