### ISSUE TITLE
Tagged hooks error with multiple tags

### ISSUE THREAD

**Issue by smalldragonvt** [cucumber/cucumber-js#550]
Hi all,

I'm new to protractor. I'm trying to use Cucumber as framework instead of Jasmine. I have some concerns that need help.

Let's say I have 2 scenarios as below: 

Feature: Running Cucumber with Protractor

  @automation @scenario1
  Scenario: Click Learn Angular JS Button
    Given I go to page "https://www.angularjs.org"
    When I click learn angular js button
    Then I see a page with title "Shaping up with Angular.js"

  @automation @scenario2
  Scenario: Click View Github Button
    Given I go to page "https://www.angularjs.org"
    When I click view github button
    Then I see a new page with title "GitHub - angular/angular.js: HTML enhanced for web apps"

**1**) This is my config file: 
cucumberOpts: {
        require: ['Features/**/*.js', 'envConf.js'],
        //defaultTimeoutInterval: 30000,
        tags: ['@scenario1','@scenario2'],
        format: 'pretty',
        profile: false,
        'no-source': true
    }

I want to run 2 tags @scenario1 and @scenario2 for one execution but it does not run anything when I input like that.

**2**) I want to use Tagged hooks and I already followed the code from our homepage. 

var myHooks = function () {
  this.Before({tags: ["@scenario1", "@scenario2"]}, function (scenario) {
  });
};
module.exports = myHooks;

But when I use this, I have an exception:

[launcher] Error: TypeError: tagGroupString.split is not a function

**3**) Can I have 2 Before or more on my hook function as below:

var myHooks = function () {
  this.Before({tags: ["@scenario1"]}, function (scenario) {
// Do something 1
  });
this.Before({tags: ["@scenario2"]}, function (scenario) {
// Do something 2
  });
this.Before({tags: ["@automation"]}, function (scenario) {
// Do something 3
  });
};
module.exports = myHooks;

Can I applied this for After hook? 

**4**) I already worked with SpecFlow. It has ability to map 2 or more Regex onto 1 function as below:

[When(@"abc")]
[When(@"xyz")]
public void Dosomething()
{
}

Is there any way to do this with protractor-cucumber ? 

Could you please when explain my question above please give me the sample code based on my example ? It's hard for me to imagine without code sample.

Thank you very much.

**Comment by charlierudolph** [comment]
1) I believe you need to use `tags: ['@scenario1,@scenario2']` in order to run features tagged with `@scenario1` **OR** `@scenario2`. Your current config is acting as **AND**, if my assumptions about protractors config are correct

2) That interface is not released yet. Please see look at the README for the current release you are using. For example 0.9.5 can be seen [here](https://github.com/cucumber/cucumber-js/tree/v0.9.5). On the main page

**Comment by charlierudolph** [comment]
3) Yes thats fine

4) Thats not supported on cucumber-js.

**Comment by smalldragonvt** [comment]
Thank you very much. I'm waiting for Tagged hooks to be released in near feature.

**Comment by charlierudolph** [comment]
Tagged hooks are supported currently its just that the interface is being changed in the next release

**Comment by smalldragonvt** [comment]
I got it, thank you

**Comment by smalldragonvt** [comment]
Assume that I have two scenario use the step above. When I try to run the test via cmd with gulp, if the element not found or some exceptions happen, then the test will stop at that scenario and it will not run the remaining scenarios. This does not happen when I use Webstorm IDE to run. It will mark the current scenario which has exception is fail and run the remaining one. Could you please help me for this case ? 

This is the sample step and I assume that the element for this step is not found and there is exception:

this.When(/^I click learn angular js button$/, function (callback) {
        
        HomepageSteps.clickLearningButton().then(callback);
});
