### ISSUE TITLE
Fail message and stack no longer visible from default formatter

### ISSUE THREAD

**Issue by floribon** [cucumber/cucumber-js#553]
When a test fail, we used to see the reason and stack just below the red line in version `0.9.5`.

Now that I've updated to `0.10.1` the reason is only summarized at the end. That's great and nice, but it was very helpful to see the errors as they were appearing, so we don't need to wait for x minutes before we know what to work on.

Is there any work around that? Could it be an option, a formatter, etc.? Thanks

**Comment by boutils** [comment]
+1

**Comment by charlierudolph** [comment]
Currently there is no workaround. You can use `--fail-fast` to stop at the first error. Otherwise there is no formatter at the moment that does this. What you're asking for reminds me of the https://github.com/martinciu/fuubar-cucumber. We shouldn't be too far off from having custom formatters.

**Comment by floribon** [comment]
Indeed a custom formatter would probably do it, thanks.

**Comment by charlierudolph** [comment]
Closing as #624 and #516 I believe capture what is desired here
