### ISSUE TITLE
Feature with undefined Background: step errors with "TypeError: Cannot read property 'getUri' of undefined" in v0.10.1

### ISSUE THREAD

**Issue by deaks-kt** [cucumber/cucumber-js#554]
I recently updated to 0.10.1 and found that my cucumber scripts started to fail with an error.  Eventually narrowed it down to having a Background: section with an undefined step.

Using the following feature file (in the right directory this time \<ahem\>):

```
bash-3.2$ cat features/background.feature 
Feature: A funny old thing

Background:

    Given an undefined background step

Scenario: Bing bang bosh

    Given cucumber v0.10.1
    When used against this feature
    Then it tries to call getUri on an undefined var
```

Gives me the following error:

```
bash-3.2$ node_modules/.bin/cucumber.js 
Feature: A funny old thing

  Scenario: Bing bang bosh
    Given an undefined background step
    Given cucumber v0.10.1
    When used against this feature
    Then it tries to call getUri on an undefined var

/private/tmp/cuke0.10.1/node_modules/cucumber/lib/cucumber/listener/summary_formatter.js:151
    var scenarioLocation = path.relative(process.cwd(), scenario.getUri()) + ':' + scenario.getLine();
                                                                ^

TypeError: Cannot read property 'getUri' of undefined
    at Array.forEach (native)
```

This is fine under 0.9.5 and also works if I remove the step from the Background: section

**Comment by floribon** [comment]
+1, I'm seeing `TypeError: Cannot read property 'getUri' of undefined` very often since the update

**Comment by deaks-kt** [comment]
So, it seems to be due to the new format when logging which steps are missing.  It's trying to display the scenario associated with the step, but because it's in the Background: there is not one.

The new format looks like this:

```
Warnings:

1) Scenario: Bing bang bosh - features/background.feature:3
   Step: Given cucumber JS 0.10.1 - features/background.feature:5
   Message:
     Undefined. Implement with the following snippet:

       this.Given(/^cucumber JS (\d+)\.(\d+)\.(\d+)$/, function (arg1, arg2, arg3, callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });
```
 
Just putting a simple check around the output in `lib/cucumber/listener/summary_formatter.js` seems to work ok:

```
    if(scenario) {
        var scenarioLocation = path.relative(process.cwd(), scenario.getUri()) + ':' + scenario.getLine();
        var scenarioLine = 'Scenario: ' + colors.bold(scenario.getName()) + ' - ' + colors.location(scenarioLocation);
        lines.push(prefix + scenarioLine);
    }
```

Now I get the following (with the Scenario line missing):

```
bash-3.2$ node_modules/.bin/cucumber.js 
Feature: A funny old thing

  Scenario: Bing bang bosh
    Given a blank canvas
    Given cucumber v0.10.1
    When used against this feature
    Then it tries to call getUri on an undefined var

Warnings:

   Step: Given a blank canvas - features/background.feature:5
   Message:
     Undefined. Implement with the following snippet:

       this.Given(/^a blank canvas$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });
```

Is this going to affect anything else?

**Comment by deaks-kt** [comment]
It might be nice to be able to prefix the Step with Background, but I cannot see where this is defined in the step object under the debugger.  Any hints?

**Comment by deaks-kt** [comment]
Did a little more digging.  It seems this was not caught during testing because the features/step_definition_snippets.feature does not cover the scenario of a missing step definition in the Background: section.  I have updated the features file with another scenario that now causes the test to fail if it's of any help in fixing this properly.
