### ISSUE TITLE
Get step result in AfterStep event

### ISSUE THREAD

**Issue by tungla** [cucumber/cucumber-js#558]
Hi everyone,
I'm trying to get step result in AfterStep event but it didn't work. Here is my code

```
this.registerHandler('AfterStep', function (event, callback) { // Neu truyen vao callback thi phai goi callback o cuoi ham
        var stepResult = event.getPayloadItem('stepResult');
        writeStream.write(stepResult.getStatus());
        callback();
    });
```

I have no idea where the issue is. Anyone pls help

**Comment by szikszail** [comment]
Hi,
You should try `StepResult` event.

**Comment by charlierudolph** [comment]
@szikszail is correct. As a heads up, registerHandler is going to be removed soon. What are you using it for exactly?

**Comment by szikszail** [comment]
@charlierudolph can you tell more about this "registerHanlder is goind to be removed" thing? When you plan to do it? Will there be specific funtions, like Before/After?

**Comment by charlierudolph** [comment]
As far as I know `registerHandler` was introduced in order to give users the `AfterFeatures` event. It doesn't have error handling similar to hooks/step definitions and is basically just access to a cucumber internal. In order to remove it I am working on dedicated beforeAll, afterAll hooks. Coming soon after will be a custom formatters api.

Are your using registerHandler and if so for what?

**Comment by szikszail** [comment]
For formatters we use in our custom formatter the `handle*Event` functions. We indeed use `registerHandler` to hook some thing to `BeforeFeatures`, `AfterFeatures`, `BeforeFeature` and `AfterFeature` events. Will we have specific function for all of these events? (Or do we have and I just didn't know about them? :) )

**Comment by charlierudolph** [comment]
So I have plans to replace beforeFeatures / afterFeatures (which is basically a global before/after), but not beforeFeature / afterFeature. What do you those events for?

**Comment by szikszail** [comment]
I've made a connecter to a third party report portal and it shoild handle the start and finish of a feature. So, you want to get ride of before/afterFeature? :D

**Comment by charlierudolph** [comment]
I don't want to get rid of the events, I want to get of the interface `registerHandler`. Once we have global beforeAll/afterAll hooks, I don't think it needed for actually running tests. The event will still be available in custom formatters (#516).

**Comment by szikszail** [comment]
Ok, it looks very cool!

**Comment by charlierudolph** [comment]
@tungla as @szikszail pointed out, please use the 'StepResult' event.
