### ISSUE TITLE
Can't get simple example working

### ISSUE THREAD

**Issue by localgod** [cucumber/cucumber-js#561]
Given the following files:
```js
#./features/support/world.js
var zombie = require('zombie');
function World() {
	this.browser = new zombie(); 
	this.visit = function(url, callback) {
		this.browser.visit(url, callback);
	};
}

module.exports = function() {
	this.World = World;
};
```
```js
#./features/step-definitions/my_step_definitions.js
module.exports = function() {

	this.Given(/^the user is on the "([^"]*)" page$/, function(arg1, callback) {
			var url = 'https://example.com/#' + arg1;
			this.browser.visit(url, callback);
			this.browser.debug();
			this.browser.dump();
		});

	this.Given(/^a "([^"]*)" input field exists$/, function(arg1, callback) {
			var id = '#' + arg1;
			id = 'head';
			if (this.browser.assert.element(id)) {
				callback();
			} else {
				callback(new Error("Expected the field " + id));
			}
		});
};
```

```gherkin
#./features/logon.feature
Feature: Login to the application
  In order to perform any action in the application
  As an user
  I want to apply my credentials to login to the service

  Background: User is on the login page
    Given the user is on the "/login" page
    And a "username" input field exists
```
I end up with this output:

```bash
$ cucumber.js

Feature: Login to the application

  In order to perform any action in the application
  As an user
  I want to apply my credentials to login to the service


  Scenario Outline: User provide login credentials
Zombie: 4.2.1
URL:    https://example.com/#/login

History:
1: https://example.com/#/login

Cookies:

Storage:
Document:

Event loop: waiting for true events
  zombie GET https://example.com/ => 200 +0ms
  zombie Loaded document https://example.com/#/login +236ms
  zombie GET https://example.com/scripts/vendor.afd6db04.js => 200 +103ms
  zombie GET https://example.com/scripts/scripts.cdac3676.js => 200 +514ms
  zombie Fired setTimeout after 0ms delay +473ms
  zombie Fired setTimeout after 0ms delay +3ms
  zombie Event loop is empty +2ms
    Given the user is on the "/login" page
    And a "username" input field exists

  Scenario Outline: User provide login credentials
Zombie: 4.2.1
URL:    https://example.com/#/login

History:
1: https://example.com/#/login

Cookies:

Storage:
Document:

Failures:

1) Background:
   Step: And a "username" input field exists - features/logon.feature:9
   Step Definition: features/step_definitions/my_step_definitions.js:11
   Message:
     Error: Expected the field head
         at World.<anonymous> (./features/step_definitions/my_step_definitions.js:17:14)
         at doNTCallback0 (node.js:419:9)
         at process._tickCallback (node.js:348:13)
```

What is going wrong here! Why is the document empty?

**Comment by bdo** [comment]
This is not an issue with `cucumber.js`. I suggest you create an issue in the [zombie.js](https://github.com/assaf/zombie) project instead.

**Comment by davemackintosh** [comment]
Zombie.js has been abandoned. I suggest updating the readme to use a maintained project. I fell into the same hole having to put shims in left right and centre for features that have been specced for at least a year now.

**Comment by jhenriquez** [comment]
@davemackintosh I know that this maybe is not pertinent to this particular issue. But would you care to suggest a more up to date project? Phantom maybe? Phantom maybe? Just want to hear some thoughts on the matter for a greenfield project.

Again I apologize because this might not be pertinent to the issue at hand.

**Comment by davemackintosh** [comment]
@jhenriquez: https://github.com/dhamaniasad/HeadlessBrowsers

**Comment by charlierudolph** [comment]
I think we should update the example to `selenium` which is what I've pretty good success with.

**Comment by jhenriquez** [comment]
I've continued to use zombie. So far without any real inconveniences. Yet,
I'm not requiring much from the browser: navigating, clicking and filling
fields.

I also was also able to replace zombie with nightwatch, without any issues
either. I believe the current example is  clear and simple and fairly
succeeds at explaining how to setup cucumber and also implicitly
illustrates a good pattern to encapsulate the actual headless browser,
making it easily replaceable.

I believe that rewriting it only to use a more popular browser for testing
adds little value to the actual purpose. When adding some comments and
references might be more than enough.

@Dave never really got to thank you for the list, pretty awesome.
