### ISSUE TITLE
World object being constructed anew for each scenario

### ISSUE THREAD

**Issue by adamlacoste** [cucumber/cucumber-js#563]
It appears that the World object is being constructed anew for each scenario, instead of persisting throughout the entire cucumber execution.  The following is a stripped down example of my support/world.js file:

```
module.exports = function () {
    this.World = function () {
        // ...
        console.log("Constructing world");
        // ...
    };
};
```

I have tested this by running my entire feature suite (~6 feature files at this time) and by specifying a single feature file at the command line.  In either case, I can see that console message appear at the top of ever scenario's output:

```
Feature: Test World

Constructing world
  Scenario: test world 1
    (...)

Constructing world
  Scenario: test world 2
    (...)

2 scenarios (2 passed)
8 steps (8 passed)
```

This isn't a critical problem for me, it just results in some redundant work such as the creation and configuration of a webdriver builder object.  I'm not desperate to save a few processor cycles, but this does seem to run counter to the documented behavior of the World object and overlap redundantly with the Before hook feature.  I'm pretty sure cucumber-js didn't work this way when when I started using it in September 2015.

**Comment by charlierudolph** [comment]
As far as I know, cucumber has always created a new world instance for each scenario, and I the documentation does specify this.

**Comment by adamlacoste** [comment]
From the readme, right at the end of the section on World:
"If you need to perform operations before/after every scenario, use hooks."

**Comment by adamlacoste** [comment]
Perhaps I am wrong about it once having worked differently, but if so a change to the documentation might be in order.  In any case, if this is intended behavior then I withdraw the issue.  Thanks for the quick response!

**Comment by adamlacoste** [comment]
One more thing... looking through the documentation, I did find this:

"All step definitions will run with this set to what is known as the World in Cucumber. It's an object exposing useful methods, helpers and variables to your step definitions. A new instance of World is created before each scenario."

But it's under step definitions, not world.

**Comment by charlierudolph** [comment]
Yeah our documentation really needs some updates
