### ISSUE TITLE
Allow simplified hook parameters

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#568]
This currently doesn't work:

```javascript
this.After('@some-tag', function () {
  // stuff
})
```

The only allowed format is:

```javascript
this.After({tags: ['@some-tag']}, function () {
  // stuff
})
```

If the argument is a String - treat it as a tag. If it's a number, treat it like a timeout.

Alternatively, throw an error message saying something like "Did you mean {tags: ['@some-tag']}"

**Comment by charlierudolph** [comment]
Yeah I think we do need better error checking for parameters so its easier for users to see whats wrong. I'd be good with allowing the simplified versions for tags, but don't think we should also support the simplified timeout version.

**Comment by aslakhellesoy** [comment]
> but don't think we should also support the simplified timeout version.

I agree. It's not explicit/obvious what a number means. A tag is more self explanatory.
