### ISSUE TITLE
README.md unclear around 'World'?

### ISSUE THREAD

**Issue by leegee** [cucumber/cucumber-js#569]
> Those wrappers are run before executing the feature suite. this is an object holding important properties like the Given(), When() and Then() functions. Another notable property is World; it contains a default World constructor that can be either extended or replaced.

Then the next line reads:
 
> Step definitions are run when steps match their name. this is an instance of World.

That last is reinforced in the code sample a little further down:

> module.exports = function () {
>   this.Given(/^I am on the Cucumber.js GitHub repository$/, function (callback) {
>     // Express the regexp above with the code you wish you had. 
>     // `this` is set to a World instance. 
>     // i.e. you may use this.browser to execute the step: 

But when inside a `Given`, I `console.log(this)`, I see:
```

{ Around: [Function],
  Before: [Function],
  After: [Function],
  Given: [Function: defineStep],
  When: [Function: defineStep],
  Then: [Function: defineStep],
  defineStep: [Function: defineStep],
  registerListener: [Function: registerListener],
  registerHandler: [Function: registerHandler],
  setDefaultTimeout: [Function: setDefaultTimeout],
  World: [Function: World],
...
```

**Comment by charlierudolph** [comment]
Where is your console.log? from the output I believe your code is structured something like
```js
module.exports = funciton() {
  console.log(this);

  this.Given(/^I am on the Cucumber.js GitHub repository$/, function () {
    //...
  });
}
```
If you moved the console.log into the function passed to Given, you would get a very different value.

**Comment by leegee** [comment]
Spot on, thank you.
