### ISSUE TITLE
Runner hangs when a Promise is rejected with a custom Error type

### ISSUE THREAD

**Issue by thomasvanlankveld** [cucumber/cucumber-js#570]
To support my tests I have:

```javascript
export function InternalServerError(message) {
  Error.call(this);
  this.message = message;
}

util.inherits(InternalServerError, Error);
```

To distinguish between internal server errors and user errors.

```javascript
const failingPromise = new Promise((resolve, reject) => reject(new InternalServerError('boo')));
await expect(failingPromise).to.be.rejectedWith(InternalServerError);
```

Which works great!

However, this causes problems with my other tests, because when a step definition returns a promise that rejects with this custom error, the runner hangs:

```javascript
await failingPromise;
```

Rejecting with a regular `Error` or with a string works, but anything else seems to leave the runner hanging.

**Comment by efokschaner** [comment]
This might be related to https://github.com/cucumber/cucumber-js/issues/564. A fix for that just went in to master. Does your issue still happen with the latest code in master?

**Comment by charlierudolph** [comment]
Just release 0.10.3 with the fix

**Comment by thomasvanlankveld** [comment]
Solved, great!
