### ISSUE TITLE
Getting scenario outline examples

### ISSUE THREAD

**Issue by albertoTena** [cucumber/cucumber-js#572]
I'm trying to get this info from the current scenario but it isn't available. I've seen that scenarios outline are preprocessed from [convertScenarioOutlineToScenarios method](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/ast/feature.js#L62).

And it could be corrected in [buildScenario function](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/ast/scenario_outline.js#L15) where I made a small change:
```
  // @addon
  function updateScenarioInfoFromOutline (subScenario, example) {
    var clonedExample = _.cloneDeep(example);
    subScenario.getExamplesFromOutline = function () {
	    return clonedExample;
    };
    return subScenario;
  }

  function buildScenario(example, rowLine, examplesTags) {
    var newName = self.applyExampleRowToScenarioName(example, name);
    var newSteps = self.applyExampleRowToSteps(example, self.getSteps());
    var subScenario = Cucumber.Ast.Scenario(keyword, newName, description, uri, rowLine, line);
    newSteps.forEach(subScenario.addStep);
    subScenario.addTags(self.getTags());
    subScenario.addTags(examplesTags);
    return updateScenarioInfoFromOutline(subScenario, example); // @addon
  }
```
Fixed in [PR #573](https://github.com/cucumber/cucumber-js/pull/573)

**Comment by charlierudolph** [comment]
See the comment on the PR for why this has been closed
