### ISSUE TITLE
Can't set formatter output file on Windows

### ISSUE THREAD

**Issue by mucsi96** [cucumber/cucumber-js#577]
Hello,

Currently there is an option to configure an output file for a formatter.
```
format: ['pretty', 'json: logfile.json' ]
```
Using an absolute path on Windows causes a problem because of the colon syntax.
The problem is with using the split method as Windows machines have colon in the path. (C:\Users\...)
https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/cli/configuration.js#L46

So the following configuration will output to a file with name `C` :)
```
format: ['pretty', 'json: C:\Temp\log123.json' ]
```

Thanks
Igor

**Comment by jlin412** [comment]
I have the same issue.  My workaround is to use relative path.

**Comment by charlierudolph** [comment]
Auhh so we need to split on just the first colon. If we switch to lodash's `_.split`, we can set a limit.

**Comment by mucsi96** [comment]
Thanks for the fix! :)

**Comment by charlierudolph** [comment]
You're welcome. I'm going through some other issues today and there should be a release with this fix in the next couple days.
