### ISSUE TITLE
exclude particular step definition from CucumberOpts

### ISSUE THREAD

**Issue by igniteram** [cucumber/cucumber-js#593]
currently i have setup my tests with protractor and cucumber and i have the following cucumberOpts -
```
cucumberOpts: {

        monochrome: true
        , strict: true
        , plugin: ["pretty"]
        , require: ['../StepDefinitions/*.js', '../Support/*.js']
        , tags: '@AllureScenario,@Regression,@ProtractorScenario,~@DatabaseTest' 
    }
```
I have to exclude a particular step definition from require key, is there a way for it, i have searched various forums - SO, gitter but no help, if its a new feature request please consider it.

**Comment by charlierudolph** [comment]
cucumberOpts is specific to protractor. Please create an issue with the protractor library that support cucumber-js.
