### ISSUE TITLE
How to Run Reports / Living Documentation?

### ISSUE THREAD

**Issue by JimTheMan** [cucumber/cucumber-js#594]
BDD in general and the cucumber docs mention "Living Documentation", an HTML report that is generated by the gherkin code.

How do I view this report? Can we add instructions for this to the README?

**Comment by JimTheMan** [comment]
I see a very sparse "formatter" section. Not sure if this creates an html page or even how to run it and point it at a location where it should create a file. What does it mean by [:PATH]? Super confusing docs...

**Comment by JimTheMan** [comment]
I can see that cucumber-html module is a dependency for cucumber, and I can create a straight up json report from this:
`cucumberjs --format json > myfile.json`

I can't figure out out to get this json file to show in an html report. You know, the ones you always see with a pie chart and a list of accordions...

Is that what the cucumber-html module is for? Their docs are very short, and I can't figure out how to view a repot. : /

**Comment by VankOde** [comment]
Hi Jim,

I have also been working on a reporting system and the solution that I found was using the npm package "cucumber html report" 

https://www.npmjs.com/package/cucumber-html-report

It is pretty simple to use, although it doesn't have pie charts it is really good.

**Comment by JimTheMan** [comment]
Hey thanks @VankOde . :)

I wish that npm package had a live demo report like this one:
https://www.npmjs.com/package/cucumber-html-reporter

That's what I've been using the past few days.

**Comment by VankOde** [comment]
@JimTheMan If you need help configuring it let me know, more then welcome to give you a hand with that
