### ISSUE TITLE
Pretty format stdout prints weird characters

### ISSUE THREAD

**Issue by JimTheMan** [cucumber/cucumber-js#596]
Since there are no html reports, I create them like this:

`cucumber.js -f pretty > ./features/reports/first`

However, this create's terribly unreadable reports with [32m and and [39m everywhere:

> Feature: Title of my first Feature
> 
>       In order to perform any action in the app, login
> 
>       I want to apply my credentials
> 
>   Scenario: User is on th elogin page
>     [32mGiven the user iis on the login page[39m
>     [32mAnd cha cha cha[39m
>     [32mWhen I do somehitng[39m
>     [32mThen I should have something else[39m
> 
> 1 scenario ([32m1 passed[39m)
> 4 steps ([32m4 passed[39m)
> 0m00.006s
>

**Comment by charlierudolph** [comment]
Those are character sequences which produce color in the console/terminal. To remove them, add the CLI option  `--no-colors`

**Comment by JimTheMan** [comment]
Awesome. thanks.

**Comment by zadam** [comment]
As of version 3.1.0 parameter --no-colors doesn't exist, but the same behavior can be achieved by parameter:

~~~~
--format-options "{\"colorsEnabled\": false}"
~~~~
