### ISSUE TITLE
Travis Failing From Cucmber Dependencies

### ISSUE THREAD

**Issue by JimTheMan** [cucumber/cucumber-js#597]
My Travis CI pipline is failing and giving this error message:

npm ERR! peerinvalid The package karma@0.9.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-cucumber@0.0.1 wants karma@~0.9

I don't get it. Cucumber wants karma 0.9, but it has karma 0.9.8 so why is it complaining?

**Comment by charlierudolph** [comment]
This is not an issue with cucumber (which has no peer dependencies). Please create an issue on karma-cucumber
