### ISSUE TITLE
New "function accepts a callback and returns a promise" errors

### ISSUE THREAD

**Issue by mjhm** [cucumber/cucumber-js#599]
It looks like the latest updates (1.1.0) and (1.2.0) may have introduced a breaking change.  The `registerHandler` now prevents returning a promise and using a callback.  So coffeescript constructions such as
```
  @registerHandler 'AfterFeatures', (event, done) ->
    teardownDb()
    .then -> done()
```
will now break.  This is easily fixed by removing the last line or returning `null`.  However this broke our builds without warning since our package setting was `^1.0.0`.

Possibly this should be a deprecation warning instead of an error.

**Comment by charlierudolph** [comment]
I don't know if I want to rollback anything here. I consider it a bug that this wasn't throwing an error, as step definitions and hooks would.

**Comment by mjhm** [comment]
Fair enough.  Closing.
