### ISSUE TITLE
CucumberJS on Windows 10

### ISSUE THREAD

**Issue by im-fortech** [cucumber/cucumber-js#600]
Hello,

My Windows updated to Windows 10 and now I get this error:

'cucumber' is not recognized as an in operable program or batch file.

Any ideas ?

**Comment by WillSkates** [comment]
@im-fortech Sounds like your cmd prompt is looking for the executable but can't find it becase there is nothing called "cucumber" in your PATH. Did you install the package with "npm install -g cucumber" originally?

The Windows 10 section [https://java.com/en/download/help/path.xml](here) should show you how to check your PATH variable. You are looking to make sure it contains something like "C:\Users\YOUR_USERNAME_HERE\AppData\Roaming\npm".

**Comment by charlierudolph** [comment]
The executable is exposed as `cucumberjs`, `cucumber-js` and `cucumber.js`. I believe `cucumber.js` doesn't work on windows.

**Comment by charlierudolph** [comment]
@im-fortech any update on this?

**Comment by im-fortech** [comment]
cucumberjs works :)
