### ISSUE TITLE
Runtime.getSupportCodeLibrary returns a new instance

### ISSUE THREAD

**Issue by fpanwaskar** [cucumber/cucumber-js#603]
Requirement:
We are implementing a wrapper around cucumberjs to speedup the testing process across the company.  We have a requirement to allow for step definitions to call other step definitions as discussed [here](https://github.com/cucumber/cucumber-js/issues/11).  To support this we are dynamically adding new steps before the feature runs using the support code library defineStep(...).

Issue:
The runtime offers access to the support code library retrieving it from the configuration.  But each time it it is retrieved a new instance is returned.

I would expect this to be tied to the runtime instance so once it is retrieved we return the same instance.

Please let me know if this seems reasonable, I'm happy to make the change and test it.

**Comment by charlierudolph** [comment]
Sorry for the delay @fpanwaskar. This change sounds good to me. If you could make the changes with some tests that would be great!

**Comment by charlierudolph** [comment]
In `2.0.0-rc.1` the method in question was removed.
