### ISSUE TITLE
The pretty formatter should use symbols to show status

### ISSUE THREAD

**Issue by remss** [cucumber/cucumber-js#607]
Currenty the pretty formatter use only colors to show the status of a step (passed, failed, skipped, etc.)
But with option --no-colors option we cannot know the status any more.
Pretty formatter should use dedicated symbols like "✓"  "✖" "-" before each step log to avoid this problem. (like mochajs does for example)

**Comment by charlierudolph** [comment]
Sounds like a good idea. Any chance you would like to help implement this?

**Comment by charlierudolph** [comment]
@mattwynne @aslakhellesoy looking at tackling this week and wanted to get your thoughts on this.

**Comment by remss** [comment]
Good news because I have no time to do that right. Sorry.

**Comment by mattwynne** [comment]
Sounds good to me @charlierudolph. I've done something like that with the new [summary](https://github.com/cucumber/cucumber-ruby/pull/999) formatter in cucumber-ruby.
