### ISSUE TITLE
Multiple steps with the same name

### ISSUE THREAD

**Issue by dankelleher** [cucumber/cucumber-js#608]
Typically I have several steps with the same name, e.g this.When('I click next'...) .  Is it possible to specify which feature uses which step definition file, rather than artificially change the names to avoid conflicts?

**Comment by charlierudolph** [comment]
That is not currently possible and I doubt that would ever be added in. One possible solution is you could use the shared context of the scenario being run to choose the proper action.

**Comment by charlierudolph** [comment]
@dankelleher anything more you'd like to discuss here or can this be closed?

**Comment by dankelleher** [comment]
Hi Charlie,  I guess not. It would be great to see an example of this done neatly - maybe I'm alone but it seems like a very common use case to me. But I'm happy to close this issue.
