### ISSUE TITLE
Feature Request: Optional tag filtering

### ISSUE THREAD

**Issue by avivbeeri** [cucumber/cucumber-js#611]
When I am working on a specific scenario, I don't like to run the whole set of features, so i often tag my scenario with @dev and then tell cucumber to only execute the @dev tags.

I use cucumber as the test runner for testing using protractor, which means all the config comes from protractor.conf.js. I don't want to edit both that file and the scenario whenever I am using @dev tags.

What I would like is a way to specify that, if no scenarios are tagged with @dev, then the whole suite should run, rather than zero scenarios running.

**Comment by floribon** [comment]
@avivbeeri I'm using cucumberJS/Protractor and what I'm doing is use an environment variable called `TAGS` such that from the command line I run
```
TAGS=`@dev` make test
```

And in my makefile:
```
# Initialize tags
TAGS = ~@nothing
 
./node_modules/cucumber/bin/cucumber.js --tags ${TAGS}
```

**Comment by charlierudolph** [comment]
As @floribon pointer out you can run a scenario by name. I also really prefer the ability to run by file and line number. See the [README](https://github.com/cucumber/cucumber-js#running-specific-features)
