### ISSUE TITLE
Message undefined. implement with following snippet

### ISSUE THREAD

**Issue by kamran-pervaiz** [cucumber/cucumber-js#612]
Hi guys,

I have written a small angular 2 app and trying to write acceptance tests but it keeps failing. I am not sure if its a cucumber bug or protractor bug, please find below info and help me out in this one.

> $ npm -v
> 3.10.3
> 
> $ node -v
> v4.4.5
> 
> $ protractor --version
> Version 3.3.0
> 
> "cucumber": "0.9.5",
> "protractor-cucumber-framework": "0.3.4"

steps.js

```
var steps = function () {

    this.Given(/^I am on the homepage$/, function (callback) {
        // Write code here that turns the phrase above into concrete actions
        browser.get("http://localhost:5001/");
        callback(null, 'pending');
    });

    this.Then(/^I should see a "([^"]*)"$/, function (arg1, callback) {
        // Write code here that turns the phrase above into concrete actions
        callback(null, 'pending');
    });

};

module.exports = steps;
```

home.feature

```
Feature: Homepage 
  As a user
  I want to visit the homepage
  So that I can access the various features on offer

  Scenario: Visit Homepage
    Given I am on the homepage
    Then I should see a "app works!"
```
protractor.conf.js

```
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    framework: 'custom',
    frameworkPath: '../node_modules/protractor-cucumber-framework/',
    capabilities: {
        'browserName': 'chrome'
    },
    cucumberOpts: {
        format: "summary"
    },
    specs: ['../e2e/features/*.feature'],

    onPrepare: function () {
        browser.baseUrl = "http://localhost:5001/";
    }
};
```

when i run using protractor <path to config file> I get below output. I am not sure what i am doing wrong.

```
$ protractor config/protractor.conf.js
[15:05:25] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[15:05:25] I/launcher - Running 1 instances of WebDriver
cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
Warnings:

1) Scenario: Visit Homepage - e2e\features\homepage.feature:6
   Step: Given I am on the homepage - e2e\features\homepage.feature:7
   Message:
     Undefined. Implement with the following snippet:

       this.Given(/^I am on the homepage$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

2) Scenario: Visit Homepage - e2e\features\homepage.feature:6
   Step: Then I should see a "app works!" - e2e\features\homepage.feature:8
   Message:
     Undefined. Implement with the following snippet:

       this.Then(/^I should see a "([^"]*)"$/, function (arg1, callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

1 scenario (1 undefined)
2 steps (2 undefined)
0m00.000s
[15:05:28] I/launcher - 0 instance(s) of WebDriver still running
[15:05:28] I/launcher - chrome #01 passed
```

any help would be appreciated.

**Comment by avivbeeri** [comment]
In your cucumberOpts, I think you need to add:
`require: ["./path/to/steps.js"]`

**Comment by kamran-pervaiz** [comment]
thank you for your reply, I did add above and my updated protractor.config file is:

```
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    framework: 'custom',
    frameworkPath: '../node_modules/protractor-cucumber-framework/',
    capabilities: {
        'browserName': 'chrome'
    },
    cucumberOpts: {
        format: "summary"
    },
    specs: ['../e2e/features/*.feature'],
    require: ["./e2e/step_definitions/homepage/.steps.js"],

    onPrepare: function () {
        browser.baseUrl = "http://localhost:5001/";
    }
};
```
It's still giving me exactly the same error :( any other suggestion?

**Comment by avivbeeri** [comment]
Is your steps file named .steps.js?

You could just do "./e2e/step_definitions/homepage/*.js"

**Comment by kamran-pervaiz** [comment]
thank you for your reply, ah thats a typo here. I tried with *.steps.js and removed *.

I read somewhere that cucumber by default looks under steps_definition that is why you dont need to include steps.js file as require. I will double check in morning.

**Comment by avivbeeri** [comment]
I read that also, however, I did not find the behaviour to work when using the protractor-cucumber-framework, so you have to specify it manually.

**Comment by kamran-pervaiz** [comment]
thanks for reply, I tried your solution but same error. any other suggestion?

**Comment by thyagab** [comment]
@kamran-pervaiz You need to have your required inside cucumber options. Your protractor config should be something like this:
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    framework: 'custom',
    frameworkPath: '../node_modules/protractor-cucumber-framework/',
    capabilities: {
        'browserName': 'chrome'
    },
    cucumberOpts: {
  require: ["./e2e/step_definitions/homepage/.steps.js"],
        format: "summary"
    },
    specs: ['../e2e/features/*.feature'],
  
    onPrepare: function () {
        browser.baseUrl = "http://localhost:5001/";
    }
};
This should work. Let me know.

**Comment by kamran-pervaiz** [comment]
@thyagab  thanks buddy, it actually did the trick. I can now open the home page, means its working. there was another thing I found was the path missing **features** folder and "..". I am glad its working now :) cheers mate

**Comment by sneha-devadiga** [comment]
@kamran-pervaiz I am facing same issue and tried all possible things listed above, but the issue still exists. Can you please help

exports.config = {
		
		/*specs: ['features/*.feature'],  
	    baseURL: 'http://localhost:8080/',  
	    framework: 'jasmine',  */
		
		seleniumAddress: 'http://localhost:4444/wd/hub',
		  getPageTimeout: 60000,
		  allScriptsTimeout: 500000,
		  framework: 'custom',
		  // path relative to the current config file
		  frameworkPath: require.resolve('protractor-cucumber-framework'),
		  capabilities: {
		    'browserName': 'chrome'
		  },

		  // Spec patterns are relative to this directory.
		  specs: [
		    'features/*.feature'
		  ],

		  baseURL: 'http://localhost:8080/',

		  cucumberOpts: {
		    require: ['../features/step_definitions/step_definitions.js'],
		    tags: false,
		    format: 'pretty',
		    profile: false,
		    'no-source': true
		  }
	 
};	


cucumber - v : 1.2.0
