### ISSUE TITLE
Feature Hook not accepting tags

### ISSUE THREAD

**Issue by mceccaroli** [cucumber/cucumber-js#614]
In our test suite, we want to have to possibility to to run an hook once before (or after) a whole feature. The typical usage of it, is to be logged-in for the whole feature with the same user; but not for all the features. Also, we do not wish using several protractor.conf.js files.
We managed to find a work around with hooks: 
this.registerHandler('BeforeFeature', function (event) {
        self.featureName = event.getName();
        console.log(event);
    });

    this.BeforeFeature(/*{ tags: ['@featurehook'] }, */function () {
        console.log('Feature:  ' + self.featureName);
        if (self.featureName == 'Creating organizations') {
            loginPage.loginAsUser('admin@unit4.com', 'admin');
        }
    });

However, we are having 2 issues: 
 1 - registerHandle will not be available in the next version
 2 - Tags are not picked up so this hook is run before every single feature.

We tried to dig a bit in the framework and found that the features_runner.js do not run before and after hooks as the scenario_runner.js does.

Is this a planned feature for next release? Does anyone has insight on how to solve this issue (without using work out if possible :D)

We also forseen the problem conflict with current behavior: if a tag is applied to 'feature', at the moment it is propagatyed and applied to every single scenario contained by this feature. That is a nice shortcut. however, in our case, we would rather apply the tag to every scenario and have the feature tag that map to a hook that is triggered only once per feature.

Cheers :p

**Comment by charlierudolph** [comment]
@mceccaroli couple things. 

`registerHandler` is not currently planned on being removed. I know I mentioned that previously but now that it has better support, I am fine with leaving it in.

`this.BeforeFeature(fn)` is syntactic sugar for `this.registerHandler('BeforeFeature', fn)`. I am planning on removing `this.BeforeFeature(fn)` in 2.0 as its too easy to confuse with `this.Before`

I would suggest logging the user out / in on each scenario using a tagged hook. If you want to keep the user logged in you could do the following

```
this.Before({ tags: ['@featurehook'] }, function () {
  // log user in (if needed)
})

this.Before({ tags: ['~@featurehook'] }, function () {
  // log user out (if needed)
})
```
This way before any consecutive scenarios with that tag keep the user logged in and when starting a scenario with a different tag, you leave.

**Comment by tryangul** [comment]
>  I am planning on removing `this.BeforeFeature(fn)` in 2.0 as its too easy to confuse with `this.Before`

Too easy to confuse? Is there an issue opened somewhere about it being confusing? Because it seems pretty cut and dry to me. I am a big fan of cucumber but this seems like a step back.

**Comment by charlierudolph** [comment]
@mceccaroli any update?

**Comment by charlierudolph** [comment]
Closing due to age. @mceccaroli please reopen if there anything more your would like to discuss.
