### ISSUE TITLE
Reports Multiple step definitions match error for steps that start with same text

### ISSUE THREAD

**Issue by andypols** [cucumber/cucumber-js#615]
Upgrading from 0.9.5 to 1.2.1 I've started seeing this error when different steps start with the same text.  Here is an example

Multiple step definitions match:

       /^I get redirected back to the (.*)$/                           - features/step_definitions/authentication_steps.js:51
       /^I get redirected back to the (.*) to complete the task (.*)$/ - features/step_definitions/sign_up_flow_steps.js:90

**Comment by charlierudolph** [comment]
I don't believe this is related to the two steps starting with the same text but the fact that they can be ambiguous for specific steps.

```js
// Step
// I get redirected back to the A to complete the task B

// Matches step def 1
/^I get redirected back to the (.*)$/
// where the capture group is "A to complete the task B"

// Matches step def 2
/^I get redirected back to the (.*) to complete the task (.*)$/
// where the capture groups are "A" and "B"
```

I don't believe anything changed in regards to this with the versions mentioned but I would consider the fact that these weren't ambiguous in 0.9.5 as a bug.

**Comment by andypols** [comment]
That could be the case, but I am confused by how steps get matched.

The steps that are causing problems are used in Scenario Outlines:

One looks like this: 

`Then I get redirected back to the <Starting Page>`

while the other looks like this

`Then I get redirected back to the <Final Page> to complete the task <With Or Without Thanks Popup>
`

So does cucumber think `<Starting Page>` and `<Final Page> to complete the task <With Or Without Thanks Popup>` are ambiguous?  That feels stange.

**Comment by charlierudolph** [comment]
Yep. Thats just based on how regular expressions work. Its not cucumber specific. A lot of times I use `"([^"]*)"` instead of `(.*)` to limit the match. It calls out the parameters a bit more and helps prevent this sort of thing from happening

**Comment by charlierudolph** [comment]
@andypols please reopen if you there is anything more you would like to discuss

**Comment by Frankusky** [comment]
Sorry to bump, im having this same issue, I replaced the regex `([^"]*)"` with this regex:  `(<.*>)`, however it throws like the step is not defined. I use the tags in the same way as andypols

**Comment by Frankusky** [comment]
I just found that using `(\S+)` regex works perfectly, but still dont understand what should match the regex expression, if someone could explain me I will appreciate it

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
