### ISSUE TITLE
Configuration of Path Files

### ISSUE THREAD

**Issue by ccruz2886** [cucumber/cucumber-js#616]
Sorry, I don't know if this is the best way to get the information.

I would like to know, if there is a way to configure `cucumber.js` on custom path way. Basically what I want to do it is create my own custom path directories.

Thanks

**Comment by charlierudolph** [comment]
Sorry, but I do not understand what you are asking. How would you expect these "custom path directories" to effect `cucumber.js`?

**Comment by charlierudolph** [comment]
@ccruz2886 any updates?

**Comment by ccruz2886** [comment]
Basically what I want it is to have a convention to save the steps and the features on custom folders name.

i.e.
Features Files
/features/articles/ads.feature
/features/slideshow/slideshow.feature

Steps
/steps/artilces/articles-steps.js
/steps/slideshows/slideshows-steps.js


But now, the features are only finding its steps, if belong to the same path.

/features/
/features/steps

**Comment by ccruz2886** [comment]
Thanks for you quick answer. 😀

**Comment by charlierudolph** [comment]
The [readme](https://github.com/cucumber/cucumber-js#requiring-support-files) has some documentation on requiring support files. Are you looking for something beyond the current functionality?

**Comment by carlosfcocruz** [comment]
I think with that information, I will be able to get the steps, to run the features files. To have my own convention. The idea it is using the PageObject pattern to build my BDD on UI TESTS.

Thanks for answer my back :)... In fact I completely miss that line of the readme, to know exactly what it was refereeing too.

**Comment by carlosfcocruz** [comment]
I think this can be close... Just another question. Is there any link with Video Tutorials, tips, best practice or something like with this awesome framework?... I would like to contributor on this project too, if it possible.

**Comment by charlierudolph** [comment]
@carlosfcocruz thanks for offer. You can become a contributor to this project at any time. Just fork the repo and send a pull request. Before I give you write access to this repo, I'd like to work with you through a couple PRs.
