### ISSUE TITLE
Use Of World.Js (Question more so)

### ISSUE THREAD

**Issue by bhreinb** [cucumber/cucumber-js#617]
Hi there,

Please excuse me i'm a relative newbie to cucumber.js. I read from documentation that you put common helper properties to be used in step definitions. 

I also aware that the constructor is now strictly synchronous. I have questions around that. The World object (ie 'this' object) supports asynchronous calls in the steps body so how come that pattern is imposed? If you want to tag on extra functions on the this object they can't have any asynchronous calls within the method?

In addition I try to call this method from within my step definitions

this.BooleanCheckIfElementExistsAfterTimeout(YesPrefRadioButton, 10000).then(function(IsYesPrefShown)

which is implemented in world.js as follows

module.exports = function()
{

  this.World = function World()
  {

this.BooleanCheckIfElementExistsAfterTimeout = function (DomElement, Timeout)
	{
		
		return browser.wait( function() { return DomElement.isPresent().then( function(res) { return res; }); }, Timeout).then(null, function() { return false; });
		
	};
}
  
}

this throws a run time error

TypeError: this.BooleanCheckIfElementExistsAfterTimeout is not a function

I assume that happens because there is asynchronous calls in the function body? Please correct me if I'm wrong here.

If these common helper methods that have asynchronous calls within them shouldn't reside in world.js where should be stored then? Presumably a file with module exports that we import into the step definitions?

Thanks in advance as to any information regarding the above.

**Comment by charlierudolph** [comment]
The world constructor being synchronous does not change the ability to add asynchronous methods to it. The README has the following example
```js
// features/support/world.js
var zombie = require('zombie');
function World() {
  this.browser = new zombie(); // this.browser will be available in step definitions

  this.visit = function (url, callback) {
    this.browser.visit(url, callback);
  };
}

module.exports = function() {
  this.World = World;
};
```

In previous versions the world constructor was asynchronous and was passed a callback which needed to be called with the created world instance.

Your example appears to be fine. Can you please give your full step definition file?

**Comment by bhreinb** [comment]
Hi Charlie,

Many thanks for responding to my question. Ok so what is different that was introduced in v0.8.0 is the removal of the callback parameter from the constructor. Thanks for clarifying. Here is the full set of steps so.

world.js
--------

module.exports = function()
{

  this.World = function World()
  {
	
	this.RunNonAngular = function (Command)
	{
		
		var flow = protractor.promise.controlFlow();
        
        flow.execute(function ()
        {
        	
            browser.ignoreSynchronization = true;
        
        });
        
        flow.execute(Command);
        
        flow.execute(function ()
        {
        	
            browser.ignoreSynchronization = false;
        
        });
		
	};
	
	this.BooleanCheckIfElementExistsAfterTimeout = function (DomElement, Timeout)
	{
		
		return browser.wait( function() { return DomElement.isPresent().then( function(res) { return res; }); }, Timeout).then(null, function() { return false; });
		
	};
	
	this.WaitForUrlToChangeToRegexPattern = function (UrlRegex, Timeout)
	{
		
		var CurrentUrl;

	    return browser.getCurrentUrl().then(function storeCurrentUrl(url)
	    {

	    	CurrentUrl = url;

	    }
	    ).then(function waitForUrlToChangeTo()
	    {
	    
	            return browser.wait(function waitForUrlToChangeTo()
	            {
	            	
					return browser.getCurrentUrl().then(function compareCurrentUrl(url)
					{
						
						if (UrlRegex.test(url))
						{
							
							console.log('Full URL is the following: ' + url);
							
							return true;
							
						}
					
					});
	                
	            }, Timeout, "Browser Hasn't Navigated To Url Pattern '" + UrlRegex + "' Within Timeout '" + Timeout + "ms'");
	            
	    });
	    
	};
	
  }
  
}



steps
-----
this.When(/^A User Inputs A Valid (.+) And Logs In$/, function (PinNumber, next)
	{
		
		this.RunNonAngular(function()
		{
							
			var TxtPassword = element(by.id('txtPassword'));
					
			expect(TxtPassword.waitReady()).to.be.truthy;
			
			//1. Enter <PinNumber>
			TxtPassword.sendKeys(PinNumber);
			
			var submitButton = element(by.id('btnSubmit'));
			
			expect(submitButton.waitReady()).to.be.truthy;
			
			//2. Press Continue Button
			submitButton.click();
						      
		})
				
		next();

	});

this.Then(/^The Pop Up Frame Should Now Be Invisible And The Title Of The home Page Should Be (.+)$/, {timeout: 60 * 1000}, function (HomePage, next)
	{
		
		//Doesn't Throw An Exception Works As Expected!!!
		this.BooleanCheckIfElementExistsAfterTimeout(by.id('ucChngComp_rbRememberDevice_0'), 10000).then(function(IsYesPrefShown)
		{
				
					console.log(IsYesPrefShown)
				
		})
		
		this.RunNonAngular(function()
		{
									
			var YesPrefRadioButton = element(by.id('ucChngComp_rbRememberDevice_0'));
			
			var NoPrefRadioButton = element(by.id('ucChngComp_rbRememberDevice_1'));
			
			//Throws An Exception?							
			this.BooleanCheckIfElementExistsAfterTimeout(YesPrefRadioButton, 10000).then(function(IsYesPrefShown)
			{
					
				console.log("Yes I Plan To Use This Device To Access My Account In The Future Is Shown [" + IsYesPrefShown + "]");
					
				this.BooleanCheckIfElementExistsAfterTimeout(NoPrefRadioButton, 10000).then(function(IsNoPrefShown)
				{
								
					console.log("No This Is A Public Device Or One I Don't Plan On Using Often To Access My Account Is Shown [" + IsNoPrefShown + "]");
						
					if (IsYesPrefShown && IsNoPrefShown)
					{
						
						console.log("Both The Yes & No Remember Login Perferences Are Visible So We Need To Click These Away!!!");
						
						expect(NoPrefRadioButton.waitReady()).to.be.truthy;
						
						NoPrefRadioButton.click();
						
						var ContinueButton = element(by.id('ucChngComp_btnContinue'));
						
						expect(ContinueButton.waitReady()).to.be.truthy;
						
						ContinueButton.click();
					
					}
					else
					{
						
						console.log("The Yes & No Remember Perferences Are Invisible So Nothing To Do!!!");
						
					}
					
					browser.switchTo().defaultContent();
								
				})
					
			})
			
			this.WaitForUrlToChangeToRegexPattern(new RegExp('http://172.16.87.185:54810/aca/' + "#/configuration"), 10000).then(function(NewUrl)
			{
					
				var acaManagementLabel = element(by.css('h3'));

				expect(acaManagementLabel.getText()).to.eventually.equal(HomePage).and.notify(next);
					
			})
								      
		})
	    
	});

Some background I'm logging into the system under test. The system under test is angular but unfortunately as part of the process I have to send commands to an external component that is non-angular namely an iframe. Hence the need to switch context (using this.RunNonAngular). This all works when I source the file from lets say 

Common = require('../support/Common.js');

and I can change this.BooleanCheckIfElementExistsAfterTimeout to Common.BooleanCheckIfElementExistsAfterTimeout

but this never runs in this context in that it throws the following error

TypeError: this.BooleanCheckIfElementExistsAfterTimeout is not a function

I'd like to use world file to house common helper methods if that makes sense?

**Comment by bhreinb** [comment]
Any further thoughts on the above? Would you regard it to be an issue or am I using the functions when in world.js context incorrectly? Many thanks in advance.

**Comment by charlierudolph** [comment]
I don't believe this is an issue with cucumber-js but just a classic problem people have when writing javascript.

`this` is the context with which a function is called. Step definitions are called with the world as `this`. However when you create functions within the step definition, the `this` for those functions are not automatically the same context. You can assign `this` to a variable on the top level and use that within the functions created
```js
this.Then(/^The Pop Up Frame Should Now Be Invisible And The Title Of The home Page Should Be (.+)$/, {timeout: 60 * 1000}, function (HomePage, next) {
  //Doesn't Throw An Exception Works As Expected!!!
  this.BooleanCheckIfElementExistsAfterTimeout(by.id('ucChngComp_rbRememberDevice_0'), 10000).then(function(IsYesPrefShown) {
    console.log(IsYesPrefShown)
  })

  var world = this;
  this.RunNonAngular(function() {
    var YesPrefRadioButton = element(by.id('ucChngComp_rbRememberDevice_0'));
    var NoPrefRadioButton = element(by.id('ucChngComp_rbRememberDevice_1'));
    world.BooleanCheckIfElementExistsAfterTimeout(YesPrefRadioButton, 10000).then(function(IsYesPrefShown) {
    //...
```

Many javascript transpilers provide nice ways to retain the function context to make the variable unnecessary.

Also it appears you are using promises so I would suggest using the promise API for step definitions instead of the callback API.

**Comment by floribon** [comment]
Also if you're not targeting Internet Explorer you can use arrow functions to preserve the `this`:

```javascript
this.Then(/^The Pop Up Frame Should Now Be Invisible And The Title Of The home Page Should Be (.+)$/, {timeout: 60 * 1000}, function (HomePage, next) {
  this.BooleanCheckIfElementExistsAfterTimeout(by.id('ucChngComp_rbRememberDevice_0'), 10000).then((IsYesPrefShown) => {
    console.log(IsYesPrefShown)
  })

  this.RunNonAngular(() => {
    var YesPrefRadioButton = element(by.id('ucChngComp_rbRememberDevice_0'));
    var NoPrefRadioButton = element(by.id('ucChngComp_rbRememberDevice_1'));
    this.BooleanCheckIfElementExistsAfterTimeout(YesPrefRadioButton, 10000).then(function(IsYesPrefShown) {
    //...
```

**Comment by charlierudolph** [comment]
Auhh yeah forgot about native support. 

It appears safari also doesn't support arrow functions yet either. http://caniuse.com/#feat=arrow-functions

Granted for step definitions you should only be limited by where you are running your tests.
If you are running cucumber-js in your terminal with node, version 4.4.5 and above support arrow functions.

**Comment by bhreinb** [comment]
Hi Folks,

Many thanks for your responses. I wouldn't have caught that context switch easily so very much appreciate the feedback. I have one more question however

You mention that it is better practice to switch to promise API for step definitions instead of the callback API. So I changed all the methods to do that. Here is an example of three methods uplifted to that schema...

this.Given(/^A User Navigates To The (.+)$/, function (AcaExternalLoginPage)
	{

		//1. Navigate To Webpage
        this.StepRes = browser.get(AcaExternalLoginPage);

        return this.StepRes;
	    
	});
		  
	this.When(/^Employer Code (.+) Is Entered And User Logs On$/, function (EmployerCode)
	{

		//1. Enter <EmployerCode>
		element(by.id('employee-code')).sendKeys(EmployerCode);
		
		//2. Press Login In Button
        this.StepRes = element(by.buttonText('Login')).click();

        return this.StepRes;
		
	});
		
	this.Then(/^The Browser Title Should Equal (.+) And The Popup Frame Should Display (.+)$/, {timeout: 30 * 1000}, function (BrowserTitle, PopupFrameGreeting)
	{
		
		//1. Expect Browser Title To Equal Passed In Value
		expect(browser.getTitle()).to.eventually.equal(BrowserTitle);

        var World = this;

        this.RunNonAngular(function()
		{

			var iFrame = element(by.id('fbContent'));
			
			expect(iFrame.waitReady()).to.be.truthy;
			
			//Need to switch this way because of issue https://github.com/angular/protractor/issues/1846
			browser.switchTo().frame(iFrame.getWebElement());
			
			var Label = element(by.id('lblRequestActionText'));
			
			expect(Label.waitReady()).to.be.truthy;
			
			//2. Pop up Frame To Equal Passed In Value
            World.StepRes = expect(Label.getText()).to.eventually.equal(PopupFrameGreeting);
		      
		})

        return this.StepRes;

	});

All three of those steps return a promise at the end of the step definitions (per the following guide https://github.com/cucumber/cucumber-js#promises). However, the test time to run three scenarios are way off i.e.

Scenario:
    Given A User Navigates To The http://172.16.87.185:54810/aca/#/login
    When Employer Code 124445 Is Entered And User Logs On
    Then The Browser Title Should Equal Login - ACA Management And The Popup Frame Should Display Enter your User ID to log in.

  Scenario:
    Given Log In Popup Frame With User Id Empty
    When A User Inputs A Valid TestCustomerAdmin And Clicks Continue
    Then The Pop Up Frame Should Now Display Enter your PIN.

  Scenario:
    Given Log In Popup Frame With Pin Empty
    When A User Inputs A Valid qweASD123 And Logs In
    Then The Pop Up Frame Should Now Be Invisible And The Title Of The home Page Should Be ACA Management

3 scenarios (3 passed)
9 steps (9 passed)
0m06.785s

in that execution time is about 60 seconds at least. I was using the callback mechanism to give me more accurate test times & keep a step in pending state until it passed the step i.e.

expect(acaManagementLabel.getText()).to.eventually.equal(HomePage).and.notify(next);

how does one do that now using the the suggested approach? Thanks again.

**Comment by charlierudolph** [comment]
I believe your third step does not work as expected. You asynchronously set World.StepRes to a promise, but when you return it `this.StepRes` it has not yet been set. Thus you are returning undefined or `this.StepRes` from a previous step which is a promise that has already been resolved

**Comment by charlierudolph** [comment]
@bhreinb any updates?

**Comment by bhreinb** [comment]
Hey,

Yes the issue I was experiencing was exactly as you diagnosed. I solved it by changing the this.RunNonAngular method...which now looks like the following

this.RunNonAngular = function (Command)
{

        var flow = protractor.promise.controlFlow();
        
        flow.execute(function ()
        {
        	
            browser.ignoreSynchronization = true;
        
        });
        
        flow.execute(Command);

	var allPromise = protractor.promise.all(Command);
        
        flow.execute(function ()
        {
        	
            browser.ignoreSynchronization = false;
        
        });

	return allPromise;

};

and then the step definition becomes

this.Then(/^The Browser Title Should Equal (.+) And The Popup Frame Should Display (.+)$/, {timeout: 30 * 1000}, function (BrowserTitle, PopupFrameGreeting)
{

    //1. Expect Browser Title To Equal Passed In Value
    expect(browser.getTitle()).to.eventually.equal(BrowserTitle);

    var World = this;

    return this.RunNonAngular(function()
    {

        var iFrame = element(by.id('fbContent'));

        expect(iFrame.waitReady()).to.be.truthy;

        //Need to switch this way because of issue https://github.com/angular/protractor/issues/1846
        browser.switchTo().frame(iFrame.getWebElement());

        var Label = element(by.id('lblRequestActionText'));

        expect(Label.waitReady()).to.be.truthy;

        //2. Pop up Frame To Equal Passed In Value
        expect(Label.getText()).to.eventually.equal(PopupFrameGreeting);

    })

});

Thanks so much for the help :+1: .
