### ISSUE TITLE
Snippets too verbose

### ISSUE THREAD

**Issue by angeloklin** [cucumber/cucumber-js#618]
Hello,
  This is more like a question.
  What would be the configuration to have cucumber.js to return less verbose snippets, so it would be easier to cut&paste them.

  What I mean is, instead of:

```
Warnings:

1) Scenario: Visitor creates a widget - features/create-widget.feature:37
   Step: Given I am on the site - features/create-widget.feature:35
   Message:
     Undefined. Implement with the following snippet:

       this.Given(/^I am on the site$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

2) Scenario: Visitor creates a widget - features/create-widget.feature:37
   Step: When I name a widget "alpha" - features/create-widget.feature:38
   Message:
     Undefined. Implement with the following snippet:

       this.When(/^I name a widget "([^"]*)"$/, function (arg1, callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

```

just something like:

```
You can implement step definitions for undefined steps with these snippets:

this.Given(/^I have visited Google$/, function () {
  // Write the automation code here
  pending();
});

this.When(/^I search for "([^"]*)"$/, function (arg1) {
  // Write the automation code here
  pending();
});
```

```
$ cucumber.js --version
1.2.1
```

Thanks and regards,
Angelo Klin

**Comment by charlierudolph** [comment]
I believe a similar idea is captured in #586 where we were discussing having a separate formatter for this.

**Comment by charlierudolph** [comment]
@angeloklin does the solution in #586 sound good to you?

**Comment by angeloklin** [comment]
@charlierudolph. Thanks for the pointer. Sure sounds like a good idea.
I could/would disrupt people that have automated and created some scripts/filter, but I would say this should be the default behaviour. 1) It would be closer to cucumber, 2) filters are likely to work the same. It would be great for people that just cut&paste from the output of some CI.

So in short, I would prefer it to be the default, if not, that sure have the option to output just that.

Thanks
