### ISSUE TITLE
Hooks and Steps hang when returning a Babel Promise

### ISSUE THREAD

**Issue by sazzer** [cucumber/cucumber-js#619]
When I have Hooks or Steps that return an ES6 Promise instead of using the callbacks, the tests just hang immediately on calling them.

For example, I have the following Before hook that will be used to start my Express server before my tests run:
```es6
import freeport from 'freeport';

module.exports = function() {
  let serverPort;

  this.Before(function (scenario) {
    return new Promise((resolve, reject) => {
      freeport((err, port) => {
        if (err) {
          reject(err);
        } else {
          resolve(port);
        }
      })
    }).then((port) => {
      serverPort = port;
      console.log('Starting server on port: ' + serverPort);
    });
  });

  this.After(function(scenario, cb) {
    console.log('Stopping server on port: ' + serverPort);
    cb();
  });
};
```

Running the cucumber tests with this file as-is and it hangs after the "Starting server on port....." line is output. If I change it to accept a callback to the Before hook, and to call that when the Promise chain finishes then everything works.

I'm using Babel, and specifically babel-preset-es2015, to convert my ES6 code into ES5 code to be run. This includes all of the code for my cucumber tests. I'm not sure if this is actually relevant or not though, but given that the documentation all implies that what I'm doing is perfectly reasonable then I'm not sure what else it could be.

**Comment by charlierudolph** [comment]
What version of cucumber-js are you using? Can you expand on hang immediately? The hook should timeout after 5 seconds for any version greater than 0.7

It hanging after the "Starting server on port....." makes me think the problem isn't with the hook but with the next step that would be run.

Can you please provide an example feature file and some step definitions so I could reproduce?

**Comment by sazzer** [comment]
My package.json includes:
```json
"devDependencies": {
    "babel-preset-es2015": "^6.9.0",
    "cucumber": "^1.2.1",
    "freeport": "^1.0.5",
    "grunt": "^1.0.1",
    "grunt-babel": "^6.0.0",
    "grunt-cli": "^1.2.0",
    "grunt-cucumber": "^0.3.0",
  }
```

My feature file is:
```gherkin
Feature: Server is running
  Scenario: The web server is running
    When I load the index page
    Then the request responded OK
```

My support file is currently (I've moved from Before to BeforeFeatures, to start the server once for all of the tests instead of once per scenario):
```javascript
import freeport from 'freeport';

module.exports = function() {
  let _serverPort;

  this.registerHandler('BeforeFeatures', function(features) {
    return new Promise((resolve, reject) => {
      freeport((err, port) => {
        if (err) {
          reject(err);
        } else {
          resolve(port);
        }
      })
    }).then((port) => {
      _serverPort = port;
      console.log('Starting server on port: ' + _serverPort);
      return port;
    });
  });

  this.registerHandler('AfterFeatures', function(features, cb) {
    cb();
  });
};
```

My step definitions are:
```javascript
module.exports = function() {
  this.When('I load the index page', (cb) => {
    cb();
  });

this.Then('the request responded OK', (cb) => {
    cb();
  });
}
```

**Comment by sazzer** [comment]
Ok - I think I've worked it out. My mistake. It appears that grunt-cucumber has pulled in cucumber-js 0.4 instead of the 1.2.1 that it's meant to be using :(

**Comment by sazzer** [comment]
Yes, that's it. Sorry about that. I was using cucumber 0.4.9 instead of 1.2.1 like I thought :(
