### ISSUE TITLE
Enable autocomplete

### ISSUE THREAD

**Issue by BevanR** [cucumber/cucumber-js#620]
Are the tools to help IDEs and editors implement autocomplete suggestions for `.feature` files based on existing step definitions?  What editors are known to have this already?

**Comment by charlierudolph** [comment]
None that I know of at the moment. Its a bit hard with regexs as many actually map to many possible string definitions but I guess you could just use the string representation of the regex.

**Comment by BevanR** [comment]
Jetbrains has plugins for both Cucumber JS and Behat.

**Comment by jlin412** [comment]
I am using Webstorm which has autocomplete.
I just couldn't refactor step definition.

**Comment by charlierudolph** [comment]
Closing as this question has received some answers and doesn't appear to currently be associated with any requested change to this repo. Please reopen if needed.
