### ISSUE TITLE
CLI doesn't load '--require' files/directories in order specified

### ISSUE THREAD

**Issue by mjhm** [cucumber/cucumber-js#626]
For example with this command:

```
cucumberjs \
  --require node_modules/coffee-coverage/register-istanbul.js \
  --require $path_root/features \
  --compiler coffee:coffee-script/register $*
```

The apparent loading order is:
1. `$path_root/features/support/*` files
2. `node_modules/coffee-coverage/register-istanbul.js`
3. `$path_root/features/step_definition/*` files

Renaming the `support` directory to `hooks` seems to work around the problem acceptably.

**Comment by charlierudolph** [comment]
In `2.0.0-rc.1` the support directory is no longer loaded first.
