### ISSUE TITLE
spreading args with regex

### ISSUE THREAD

**Issue by jsnsimpson** [cucumber/cucumber-js#627]
We have a wrapper function which allows us to use the async/await feature as part of our tests.

so effectively what we pass to cucumbers steps is something like the following: 

```javascript
this.Then(/^I do(.+) on page (.+)$`/, function(...args){

  //do something with varying number of arguments - in our case we forward the args to the function which will actually do the testing
});
```

Currently this throws an error suggesting we are not catering for the number of args (in the case above it would be 3 (if returning promise or synchronous) and 4 (if using callbacks) required.

Is there a workaround for this use case? If not is there a way it can detect if we are catering for N arguments ?

**Comment by charlierudolph** [comment]
There currently is no workaround. Out of curiosity, what is your wrapper function and what language are you using? Is there any reason your wrapper function can't retain the length of the function its wrapping?

**Comment by charlierudolph** [comment]
@jsnsimpson any updates on this? I believe the argument guard is valuable and wrappers should be able to return the function length. We could add a option to disable the check, but I'm against that currently.

**Comment by charlierudolph** [comment]
@jsnsimpson closing due to lack of response. Please reopen if you'd like to discuss further

**Comment by leoselig** [comment]
I strongly believe this should be re-opened
I'm hitting the same issue with spread-args
Since they are super useful (especially for wrapping step functions in an idiomatic way) and ECMAScript-compliant I feel that cucumber-js should not prevent anyone from using language features

**Comment by aslakhellesoy** [comment]
Cucumber will raise an error if the function arity (number of parameters) is different from the number of regexp capture groups.

You could try to submit a pull request that preserves that behaviour - not sure if it's possible.

**Comment by artemave** [comment]
As cucumber user, I was surprised that
```javascript
Given('{actor}\'s app needs environment variables {string} and {string}', function (actor, ...envVars) {
```

Failed with

```
function has 1 arguments, should have 3 (if synchronous or returning a promise) or 4 (if accepting a callback)
```
