### ISSUE TITLE
Close window after all features

### ISSUE THREAD

**Issue by senty** [cucumber/cucumber-js#629]
Hi,

image simple **feature** :
`Feature: Example feature`
`Scenario: Reading documentation`
`When I open Google`

simple word.js :
`var webdriver = require('selenium-webdriver');`
`var platform = process.env.PLATFORM || "CHROME";`
`var buildChromeDriver = function() {`
`return new webdriver.Builder().`
`withCapabilities(webdriver.Capabilities.chrome()).`
`build();`
`};`
`var driver = buildChromeDriver();`
`var handlers = function () {`
`this.registerHandler('AfterFeatures', function (features, callback) {`
`driver.close()`
`callback()`
`});`
`}`
`var World = function World() {`
`var defaultTimeout = 20000;`
`this.webdriver = webdriver;`
`this.driver = driver;`
`};`
`module.exports = handlers`
`module.exports.World = World`

and simple step **implementation**
`module.exports = function() {`
`this.World = require('../support/world.js').World;`
`this.When(/^I open Google$/, function () {`
` return this.driver.get('https://www.google.com');`
`});`
`};`

Everythin works fine i just cannot close window (chrome) after all features are done. I have tried to use **AfterFeatures** handler - but **driver.close()** is not working.

Can someone please help ?

**Comment by charlierudolph** [comment]
`driver.close()` is asynchronous and returns a promise. Your current implementation does not have cucumber-js wait for the it to complete. The `AfterFeatures` can return a promise, so if you just remove the callback and `return driver.close()`, I believe it will work

**Comment by senty** [comment]
Thank you very much @charlierudolph - it works ! ;-)
