### ISSUE TITLE
Tagged hooks not working properly without {tags:[@yourtag]}

### ISSUE THREAD

**Issue by GeeChao** [cucumber/cucumber-js#630]
Following these instructions from the github instructions page
Tagged hooks
Hooks can be conditionally selected for execution based on the tags of the scenario.
// features/support/hooks.js (this path is just a suggestion)
**(Example A)**
var myHooks = function () {
  this.Before({tags: ["@foo", "@bar,@baz"]}, function (scenario) {
    // This hook will be executed before scenarios tagged with @foo and either
    // @bar or @baz.
    // ...
  });
**(Example B)**
  // You can use the following shorthand when specifying a single tag
  this.Before("@foo", function (scenario) {
    // This hook will be executed before scenarios tagged with @foo
    // ...
  });
};

Example B does not work, and is executed for ALL scenarios even when they're not tagged.

Using CucumberJS V 1.2.2

**Comment by bar** [comment]
@GeeChao mhh?

**Comment by charlierudolph** [comment]
Example B is in master but has yet to be released. I have plans for one more update and should be making a new release this weekend

**Comment by charlierudolph** [comment]
1.3.0 released with this feature

**Comment by GeeChao** [comment]
Great, thanks for the quick explanation @charlierudolph
