### ISSUE TITLE
Jasmine specs not running

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#632]
This is really odd. Jasmine seems to not do anything with our specs. When running it, it just exists with a 0 code. Our unit tests are not being run anymore.

I tried upgrading jasmine to the latest version to no avail.

**Comment by jbpros** [comment]
Bug in jasmine: https://github.com/jasmine/jasmine-npm/issues/88

**Comment by charlierudolph** [comment]
@jbpros in the future can you please try bumping it on a feature branch instead of committing directly to master. I think the proper thing to do is lock down to a version we know works. Based on the thread and running locally it appears 2.4.1 works. I'm going to try that.

**Comment by jbpros** [comment]
@charlierudolph sure thing. I was a bit impatient, I wanted to fix it quickly (I thought it'd be trivial) to do something else. Sorry!

Thanks for taking care of it.
