### ISSUE TITLE
Rename --snippet-interface to --snippets

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#636]
In Cucumber-JVM you can also tell Cucumber whether you want snippets with method names using [camelCase or snake_case](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/resources/cucumber/api/cli/USAGE.txt#L24)

For consistency between platforms, can you rename `--snippet-interface` to just `--snippets`?

**Comment by aslakhellesoy** [comment]
Or better - add `--snippets` and deprecate `--snippet-interface`

**Comment by charlierudolph** [comment]
@aslakhellesoy this was one thing I wanted to move into a `--formatter-option` (or in jvm a `--plugin-option` as its doesn't change how cucumber runs but just the output of a particular formatter. Also on cucumber-js we have both snippet interface (sync, callback, promise) and snippet syntax (for transpiled languages). I think --snippets is too vague.

**Comment by aslakhellesoy** [comment]
Oh right I remember now. Closing this.
