### ISSUE TITLE
Possible to get table cell strings with leading/trailing spaces?

### ISSUE THREAD

**Issue by emiltin** [cucumber/cucumber-js#640]
The OSRM route engine uses tables to define small 'maps' of node locations used in tests, ie:

```gherkin
            |   |   | a |   |   |
            |   |   | b |   |   |
            | d | c |   | g | h |
            |   |   | e |   |   |
            |   |   | f |   |   |
````

The horizontal and vertical position of nodes are translated to latitude and longitude. This might be a somewhat unusual use of tables, but it's very useful.

To make the maps easier to read I would like simplify the syntax to:

```gherkin
            |     a     |
            |     b     |
            | d c   g h |
            |     e     |
            |     f     |
````

However cucumber strips leading (and trailing) spaces from the cell strings, ie. "    a    " is returned as "a", which breaks the horizontal positions.

Is there any way to get the raw strings including the leading spaces?

I guess we could quote all lines, but this is awkward. I looked at transforms, but it seems cucumber js doesn't implement it, and anyways I'm not sure it would solve the problem?

Thanks!

**Comment by charlierudolph** [comment]
It appears that trimming of trailing and leading whitespace is done by [gherkin](https://github.com/cucumber/gherkin) and as far as I can tell there is no way to ask gherkin to preserve them. You could open an issue on gherkin if you would like.

I believe transforms are mostly for capture groups in regular expressions, though cucumber-ruby has data table transforms. That would start with the data gherkin parses though, so you would have already lost the leading and trailing spaces.

If all you want is the example you gave, you could try using doc strings.
```gherkin
Given my map
  """
      a     
      b     
  d c   g h 
      e    
      f    
  """
```

**Comment by emiltin** [comment]
thanks for the idea with doc strings. i will open a ticket with gherkin.

**Comment by enkessler** [comment]
@emiltin It looks like you've already gotten all of the relevant feedback that I would have given you:

1. The whitespace is lost when gherkin parses the cells
2. You can quote your cells or use doc strings as alternatives.

That's likely as simple as it's going to get.

**Comment by emiltin** [comment]
hi @enkessler thanks for the response. let's see what the gherkin folks say.

**Comment by enkessler** [comment]
@emiltin You mean gherkin people who are not me?

**Comment by emiltin** [comment]
Sorry, I didn't realise you we're involved in Gherkin. What do you think about https://github.com/cucumber/gherkin/issues/232? Question is of there's any way to ask Gherkin to preserve the whitespaces.

**Comment by charlierudolph** [comment]
Closing as the related gherkin issue was closed
