### ISSUE TITLE
Cucumber Appears to Ignore Sleep Promises

### ISSUE THREAD

**Issue by machineghost** [cucumber/cucumber-js#642]
I have a "pause" step:

    this.Then('I pause for $numSeconds', function(numSeconds) {
        return this.driver.sleep(numSeconds * 1000);
    });

But it doesn't work.  If I have that step and one after it:

    Then I pause for 20 seconds
    Then I log a message

I see the log from the second step immediately, not 20 seconds later:

    Then I pause for 20 seconds
    // no wait between the line above and the log message
    a message
    Then I log a message

Is there an alternate way to express "wait 20 seconds" in Cucumber, or is this a bug?

**Comment by charlierudolph** [comment]
It shouldn't be do anything special. In you example wouldn't `numSeconds` be the string `20 seconds`? In which case case `numSeconds * 1000` would be `NaN`, which I would expect make sleep to just resolve immediately

**Comment by machineghost** [comment]
Thanks for the suggestion, but I'm pretty certain I should be passing a number, not a string.  From the documentation:

>sleep(ms)
>
>Schedules a command to make the driver sleep for the given amount of time.
>
> Parameters
> msnumber
> The amount of time, in milliseconds, to sleep.

**Comment by machineghost** [comment]
Ah, thanks for catching that!  You'd think Selenium would throw an error when you pass `20 seconds` to a function that expects `20000`, but I guess not.
