### ISSUE TITLE
Issues with Protractor and `process.uncaughtException`

### ISSUE THREAD

**Issue by NickTomlin** [cucumber/cucumber-js#643]
Hi there,

> this is not quite an issue, more of a discussion. Please let me know if there's a more helpful venue for this

We've had some [issues](https://github.com/angular/protractor/issues/3553#issuecomment-248898275) on Protractor about removing our usage of [`process.on('uncaughtException')`](https://github.com/cnishina/protractor/blob/4b54ec8449a570459e51caf6cc6ccae4b5c16b12/lib/launcher.ts#L180) because it clobbers the cucumber [`uncaughtExceptionErrorHandler`](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/util/exception.js#L6). 

This is a bit of a difficult issue because both projects expect to be the "end of the line". This is similar with other frameworks like [mocha](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L824). Unfortunately, there seems to be a disconnect with handling certain types of exceptions in cucumber that does not present itself in Mocha. 

Is there a way we could work together to figure something out? Ideally both projects could play nicely without compromising the ability to safely recover from errors.

I'm happy to help and coordinate from the protractor side.

**Comment by NickTomlin** [comment]
Excellent; I'll try to get a quick example repo up that we can use to debug things (hopefully this weekend). Let me know if there's any additional data that I can add. I'll also try to get some folks that use Cucumber and Protractor to chime in here as well.

**Comment by NickTomlin** [comment]
After doing some more investigation, this seems to be an issue with the way that `protractor-cucumber-framework`'s use of `Cucumber.Cli` handles rejections in promises. I'm not sure if this is actually due to Cucumber itself (since it handles this just fine). 

I'm going to go ahead and close this for now and follow up with the `protractor-cucumber-framework` folks. I'll re-open and ping you if this does turn out to be something that needs changes in cucumber core.

Thanks!

**Comment by charlierudolph** [comment]
Sounds good! Best of luck.
