### ISSUE TITLE
Support glob pattern in --require 

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [cucumber/cucumber-js#645]
Hi, 

I'm actually using cucumber for unit test. Reusing steps are very useful. But I would really like more control over what is imported. It would really awesome if I could specify a glob pattern of which files need to be required in a directory

**Comment by charlierudolph** [comment]
Sounds like a great idea! This will definitely be something I add to 2.0. I'm uncertain if we can add support for this in a backward compatible way.

**Comment by charlierudolph** [comment]
I think backward compatibility is possible. Just need to give directories special treatment

**Comment by charlierudolph** [comment]
Can you please give more information about your use case? If you require a directory, it is currently turned into a recursive glob pattern for that folder searching for files with the `*.js` extension  and any other extensions added via `--compiler`. I realize this should probably be documented.

**Comment by charlierudolph** [comment]
@marthinus-engelbrecht bump. I'd like more information on your use case.

**Comment by marthinus-engelbrecht** [comment]
Sorry, things have been a bit hectic my side. Will give you some feedback soon.

**Comment by charlierudolph** [comment]
@marthinus-engelbrecht another bump. Otherwise I'm going to close this issue and you can reopen when you have time to provide more info

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed
