### ISSUE TITLE
demo issues

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#646]
It appears the demo has a few issues:
- uses two different red/green/yellow/cyan colors. The failures / warnings / step and scenario counts are using different colors from what the step are printed in.
- does not bold the scenario name / step name when reporting failures / warnings
- does not make the location gray when reporting failures / warnings

**Comment by jbpros** [comment]
Also, the Cucumber logo is a small-res PNG which renders poorly. We should use a [proper SVG](https://github.com/cucumber-ltd/brand/blob/master/images/svg/notm/cucumber-black.svg).

**Comment by charlierudolph** [comment]
Logo updated in 2027cfc5da1f14c61583352061c53ff6f377bb90. The rest of the demo issues appear to be due to the library we using for transforming the ansi color codes into html.
