### ISSUE TITLE
Failed assertions in the loops are marked as successful

### ISSUE THREAD

**Issue by kotvertolet** [cucumber/cucumber-js#648]
I have faced with the problem that assertions placed in the loop doesn't work properly, like in this case:

```
    this.Then("I see the total amount displayed", function () {
        transactionSteps.isTotalAmountDisplayed().each((element)=> {
            element.getText().then((text) => {
                this.expect(text).to.have.length.of.at.least(1);
            })
        })
    });`
```

> And the output of this:
> 
>  Scenario: Displaying transaction summary
>   ✓ Given I load the loginForm widget
>   ✓ And I am logged in as an admin with password admin
>   ✓ When I load the transaction widget
>   ✓ Then I see the transaction summary with transaction list displayed
>   ✓ And I see the transaction date displayed
>   ✓ And I see the transaction name displayed
>   ✓ **And I see the total amount displayed**
> 
> 1 scenario (1 passed)
> 7 steps (7 passed)
> 0m03.158s
> [11:39:25] E/launcher - expected '' to have a length at least 1 but got 0
> [11:39:25] E/launcher - AssertionError: expected '' to have a length at least 1 but got 0

As you see, scenario looks successful, but actually it's failed

**Comment by dfjones1981** [comment]
have you tried returning the whole thing? 
` this.Then("I see the total amount displayed", function () {
        return transactionSteps.isTotalAmountDisplayed().each((element)=> {
            element.getText().then((text) => {
                this.expect(text).to.have.length.of.at.least(1);
            })
        })
    });``

**Comment by kotvertolet** [comment]
Strange, it almost works. The last 3 steps are pretty the same, but works with different elements collections, so after I added the return statement to these 3 steps then only the last one (_And I see the total amount displayed_) fails (but actually they all should be failed), but if I run the test in debug mode (even without any breakpoints) it works properly and steps starting from _And I see the transaction date displayed_ are failed

**Comment by charlierudolph** [comment]
Promises typically need to be chained and thus often need to be returned. I think you also need another return inside the loop.
```js
this.Then("I see the total amount displayed", function () {
     return transactionSteps.isTotalAmountDisplayed().each((element)=> {
         return element.getText().then((text) => {
             this.expect(text).to.have.length.of.at.least(1);
         })
     })
 });
```
What promise library are you using by the way that you have a `.each` method?

**Comment by charlierudolph** [comment]
@kotvertolet any update?

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed
