### ISSUE TITLE
Timeout is not working

### ISSUE THREAD

**Issue by deepalitandel** [cucumber/cucumber-js#650]
I need to put delay in my After Scenario to do some operation. 

this.After({timeout: 60 \* 1000}, function(scenario, callback) {
   self.helper.myFunction()
      .then(function(data) {
        console.log('success');
        callback();
      })
      .catch(function(err) {
        console.log('error'+ err);
        callback();
      });
  });

I tried above. While running multiple scenario's it doesn't stop for 60 seconds after every scenario. I am using Promise style coding.

Please do needful ASAP.

**Comment by charlierudolph** [comment]
Hook timeouts don't introduce delays but just set the maximum time the hook is allowed to run for before it is considered to have failed.

Also cucumbe js allows you to use promises instead of callbacks by omitting the callback argument and returning a promis in your hook definition.

**Comment by charlierudolph** [comment]
@deepalitandel any update?

**Comment by charlierudolph** [comment]
Closing due to age. Please reopen if needed
