### ISSUE TITLE
this.AfterFeatures triggers after every feature 

### ISSUE THREAD

**Issue by Galileo1** [cucumber/cucumber-js#651]
Hey guys, 

I am using this.AfterFeature in the cucumberjs/protractor test project and seems like the afterfeatures (array of features) gets invoked after every feature rather than at end of the full test run(all features). Is this  existing feature or am I using the incorrect version??

cucumber =0.7
protractor =2.5.1

/\* code */
this.AfterFeatures(function (features, callback) {
        console.log("AfterFeatures trigger");  
        callback();
 });

Any feedback ??

P.S -Also I am running the test project parallel and I am trying to consolidate the entire report at end of the project.

**Comment by charlierudolph** [comment]
`this.AfterFeature` is suppose to trigger after each feature, whereas `this.AfterFeatures` is suppose to trigger only once (your issue appears to reference both). 

I've used the after features hook many times in the past and never ran into any issues. That said, I always used `this.registerHandler('AfterFeatures', code)` and never used the undocumented interface `this.AfterFeatures`.

Cucumber version 0.7 is a year old and quite different from the current version. Looking back at the  old code, I don't see any immediate issues. Any chance you can update to the latest version of cucumber?

**Comment by Galileo1** [comment]
@charlierudolph updating to latest version is not possible at the moment but this post http://stackoverflow.com/a/26171387 suggested that this.AfterFetaures can be used straight away and doesn't require this.registerHandler.I will give it a shot and will confirm the output.

**Comment by Galileo1** [comment]
@charlierudolph I tested that and it seems to be same behavior the AfterFeatures hook seems to be running after every feature when I run cucumber -protractor in parallel??

 this.registerHandler('AfterFeatures', function (features, callback) {
        console.log("AfterFeatures trigger");   
        callback();
    });

**Comment by charlierudolph** [comment]
The fact that you are running in parallel could make it run every time but I doubt its running after every feature. Can you try printing out the features object (which may actually be an event back in cucumber 0.7).

**Comment by charlierudolph** [comment]
@Galileo1 closing due to age. Please reopen if needed

**Comment by Galileo1** [comment]
@charlierudolph is there any other hook/feature that I can use to consolidate the results from parallel run?I am certain that parallel running triggers 'AfterFeature' hook after every feature.
