### ISSUE TITLE
setTimeout causing double step execution

### ISSUE THREAD

**Issue by Sawtaytoes** [cucumber/cucumber-js#654]
I was messing around with `setTimeout` at `0ms` to try testing promises and see if that would fix some issues I was having. When surrounding `next()` with `setTimeout`, I noticed some very strange behavior. It runs the test twice!

This is how you'd normally console log and then go to the next line.

``` js
this.When("Hello World!", next => {
    console.log('hi')
    next()
})
```

When `setTimeout` is used wrapping `next()`, then it double-fires this test. Very strange!

``` js
this.When("Hello World!", next => {
    console.log('hi')
    setTimeout(() => next(), 0)
})
```

I keep thinking maybe my JS is bad, but it's looking fine. I originally thought it had to do with promises, but it seems to do it with any timeout code. Console logging time differences, it's was obvious to me this is executing the test than once.

What's going on here?

**Comment by charlierudolph** [comment]
This shouldn't be happening. And I believe we have tests to ensure this isn't happening. What cucumber-js version are you using? Also can you please give a more complete but minimal reproducible example? (Feature file content, step definition file content, command run)

**Comment by Sawtaytoes** [comment]
I tried reproducing this with a test project using Gulp, no problem.

In the project I'm seeing the issue, it's running in a web browser and hooking into Cucumber somehow. I didn't setup the project so I'm not quite sure. The example code I gave you is all I need. So long as you have a promise or a timeout; something that doesn't immediately call `next()`, this issue of double-firing will occur.

I upgraded the Cucumber version in this setup to the latest last week and may have missed something as there were some deprecated and obsolete functions I had to change. Could you point me at what might be calling the tests so I can look around and see if there's something in the newer version that wasn't accounted for in this web runner code?

**Comment by Sawtaytoes** [comment]
I did some more testing and added some code to `console.log` on `setInterval` at 1ms.
With one scenario, this is what I saw:
```js
-------------------------
interval
2 interval
-------------------------
interval
2494 interval
-------------------------
```

The code I used:
```js
setInterval(() => console.log('interval'), 1)
```

Seems like it does the first one, waits for a couple milliseconds, then if it doesn't gets a `next()` it calls it again. Is it possible I'm calling `next()` wrong? In some code examples online, I saw something like `next().pending()`. Is there documentation on how to call it?

**Comment by charlierudolph** [comment]
Can you give the feature file content and your step definitions? Cucumber-js should not be calling a step a second time if next is not called and instead should be timing out the step. Can you please at least determine the cucumber-js version you are using as steps did not have timeouts built in until 0.7

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed
