### ISSUE TITLE
Timeout and Promise causing "Uncaught Error" in console

### ISSUE THREAD

**Issue by Sawtaytoes** [cucumber/cucumber-js#656]
I was unable to reproduce this issue in a command line project, but I was able to using the website HTML example: http://cucumber.github.io/cucumber-js/

I only changed the `When` part in the sample code, but it happens on `Given` and `Then` as well:

``` js
this.When(/^I increment the variable by (\d+)$/, function(number, next) {
  this.incrementBy(number);
  setTimeout(() => {
    throw 'this is an uncaught error'
    next()
  }, 1000)
});
```

Looking at the console when running the feature, I get the message:

```
Uncaught this is an uncaught error
```

It never goes to `next()`, so it take 5 seconds to finish. The same issue happens in `Promise.then` and also in `setInterval`. I also tested when returning a `Promise` and not passing `next`, but experienced the same issue.

I use Chai as my assertion library, and when I do `expect(true).to.be.false`, it throws and `Assertion Error` and normally; that gets picked up through Cucumber which properly fails the test. On the other hand, if I wrap this error in a `setTimeout`, `setInterval`, or `Promise`, then the `Uncaught` error message shows up in the console instead of Cucumber picking up on the error.

**Comment by davidrissato** [comment]
Sawtaytoes,

The way you did it will never work for sure and cucumber it is behaving exactly as expected.

When dealing with asynchronous code the way you did (using callbacks), you need to try...catch exceptions and pass it to next method, like that:

```javascript
this.When(/^I increment the variable by (\d+)$/, function(number, next) {
  this.incrementBy(number);
  setTimeout(() => {
    try {
        throw new Error('this is an uncaught error');
        next(); // just for the example, of course it will never be called
    } catch (err) {
       next(err);
    }
  }, 1000)
});
```

However, there are much better ways to deal with asynchronous code in Javascript. I strongly suggest you invest some time researching  "javascript promises" and also take a look in bluebird.js package (a nice Promise implementation). It will well worth your time investment and will strongly leverage your code quality.

Best

**Comment by Sawtaytoes** [comment]
That's the solution I ended up with. Seems sub-optimal because I have to try-catch it. I'm wondering if there's a way to extend Chai to handle this use case internally.

**Comment by charlierudolph** [comment]
I personally prefer promises, but this should work the same in the CLI versus in the browser. I believe this is just a bug in the browser version.

**Comment by davidrissato** [comment]
Yes, you are right. This solution is suboptimal.

But what you are looking for is not a Chai's or Cucumber's concern. You
probably haven't completely mastered the async nature of javascript yet.

You tried to solve this problem using callbacks, and although this is a
valid solution, you end up with a lot of trouble when dealing with
exceptions or even chains of sequential calls (look for "Callback Hell" to
understand what I'm talking about).

There are much better ways to solve this same problem. At a glance, I could
say you were better using one any of these:  Promises; Coroutines +
Generators; or ES2017 async await model. In fact, all those mentioned
solutions are based up on Promises foundational concepts, so this is why I
strongly recommend that you give a further read on Promises. Believe me,
your time will be very well invested.

For example, you could solve the problem this way using Bluebird's Promise
(the code below assumes you are using Node JS 5+ or any ES6 compatible JS
Engine):

```javascript
const Promise = require("bluebird");

this.When(/^I increment the variable by (\d+)$/, function(number) {

  return Promise
        .attempt(() => { this.incrementBy(number); })
        .delay(1000)
        .then(() => { throw new Error('this is an uncaught error'); })
       .then(() => console.log('this will never be executed, because
the Promise was rejected in the previous step.');

});```

And even if you insisted on using setTimeout, it could be done in a more
"extended version":

```javascript
const Promise = require("bluebird");

this.When(/^I increment the variable by (\d+)$/, function(number) {

  return Promise
        .attempt(() => { this.incrementBy(number); })
        .then(() => {
             return new Promise((resolve, reject) => setTimeout(resolve,1000));
        })
        .then( () => throw new Error('this is an uncaught error'));});

```

Best regards,
David


2016-10-21 5:08 GMT-02:00 Sawtaytoes <notifications@github.com>:

**Comment by charlierudolph** [comment]
This appears to be a bug in the exception handler which is suppose to catch uncaught exceptions. Able to fix that but due to browser security we merely get "Script Error' instead of a actual error. This should be specific to the online example as the browser security should be avoided in other test runners as the step definitions are loaded in statically instead of dynamically.
