### ISSUE TITLE
Features Outline?

### ISSUE THREAD

**Issue by echonox** [cucumber/cucumber-js#662]
So I have "Examples" with lots of variables and I want to loop the feature file with each variable in the "Examples", I know that I can use Scenario Outline for that but is there a way to have Feature Outline? and inside it to have multiple scenarios? So:

```
Feature: Creating Event
   Scenario: Login with <email>
      Given I visit page
      When I enter email: <email> and password: <password>
      And I click the login button
      Then I should be logged in

Scenario: Create event
      Given I am at calendar page
      And I click new event button
      When I enter title: <title>
      And set date to: <date>
      And I save event
      Then I should see the event in calendar


Examples:
| email | password | title | date |
| test@email.com | 123456 | Hello World | 26-10-2016 |
| test2@email.com | 123456 | Hello World 2 | 30-10-2016 |
```

And each data should loop each scenario, so it should:
1. Login with "test@email.com" and create event with title: "Hello World" and date: "26-10-2016", 
then it should:
2. Login with: "test2@email.com", create event with title: "Hello World 2" and date: "26-10-2016"

**Comment by charlierudolph** [comment]
This is an issue for the wider cucumber community. Please open an issue on https://github.com/cucumber/gherkin which is responsible for parsing the feature files and where such a change would need to originate.
