### ISSUE TITLE
getBackground gone?

### ISSUE THREAD

**Issue by borbe** [cucumber/cucumber-js#663]
CucumberJS - Is there a way to get feature background information ?

it seems that it was ripped from feature.js on this commit:

https://github.com/cucumber/cucumber-js/commit/a5fd8251918c278ab2e389226d165cedb44df14a#diff-5530e5c6e19e6191a22488fb10c9819b

@charlierudolph 
Is there another way to get the background information?

Right now it is merging all the background steps into the steps information but this is not practical if you need to know wether they are part of the background or not.

**Comment by charlierudolph** [comment]
Currently there is no way to get the background. The version of [gherkin](https://github.com/cucumber/gherkin) we are using deals with the background steps and adding them to each scenario.

Whats your use case for knowing whether or not a step is part of the background or not?

**Comment by borbe** [comment]
@charlierudolph, i connected my automated tests to testrail api, so im creating tests using the gherkin information.

In test management tools there is a "Preconditions" or sometimes "Setup".

And i wanted to plug in the Background into that section, but after that commit i mentioned, there is no way i can differentiate between background steps that run for all the features or if it is a step that is part of that test only.

**Comment by charlierudolph** [comment]
Okay. How are you accessing the background and what would be an ideal solution for you? 

The solution I'm thinking of at the moment would be to add an `isBackground` method to the step object.

**Comment by borbe** [comment]
I think that solution is pretty good since it is at the step level.

from my perspective, I think accessing the step and checking from there if it is a background step is the best solution actually.

so totally agreed with your proposal.

**Comment by charlierudolph** [comment]
In `2.0.0-rc.1`, steps now have an `isBackground` property. Do you need it in the JSON output?

**Comment by borbe** [comment]
Thank you very much for addressing this issue!

I believe that the JSON output should point that as well but if there is no other practical use for the background steps identification other than the use case i mentioned, the isBackground property suffice :)

Thanks again!
