### ISSUE TITLE
json formatter output cut off

### ISSUE THREAD

**Issue by dmatesic** [cucumber/cucumber-js#666]
When I use the json formatter the stdout output gets cut off (process exits before json finishes printing), however saving the json as a file works fine.

Here is a small project to reproduce the issue (clone and run `npm i && npm run stdout`): https://github.com/dmatesic/cucumber-js-stdout-bug

Mac OS 10.11.6
node 6.2.0
cucumber-js 1.3.1

**Comment by charlierudolph** [comment]
I believe this is specific to the node version. I can reproduce in 6.2.0 but am unable to reproduce in 6.3.0 and 6.9.2
