### ISSUE TITLE
Case insensitive capturing groups

### ISSUE THREAD

**Issue by libetl** [cucumber/cucumber-js#667]
Hello,

I am writing you to know if the support of case insensitive capturing groups is planned in cucumber js ?

like this one :

```
 this.Then(/^((?i)foo|bar)/, 
   function (foobar) { 
     if (foobar.toLowerCase () == "foo") {/*...*/}
     if (foobar.toLowerCase () == "bar") {/*...*/}
 );
```

This clause can support Foo, foo, foO, FOO, bar, Bar, BAR with a single capturing group.
(here is an example on regex101 : https://regex101.com/r/s3Sib5/1)

Thanks for your help,
Regards,
Lionel.

**Comment by charlierudolph** [comment]
Cucumber-js just uses native regular expressions. Thus the regular expression support depends on the environment you are running in whether that is the browser or node
