### ISSUE TITLE
exit code for pending and undefined tests

### ISSUE THREAD

**Issue by travi** [cucumber/cucumber-js#669]
when running tests from the cli, i've noticed that runs containing `pending` or `undefined` steps exit with `0`. i would expect these to be non-zero so that my CI build can fail based on exit code in these situations. 

i use a `@wip` tag to exclude incomplete tests from causing failures do to these step states.

some other tools require a flag to be set in order to enable this behavior, but i haven't found a mention of such a flag in the cli docs. am i overlooking it?

it there a way for me to enable these to cause a non-zero exit?

**Comment by charlierudolph** [comment]
This is exactly what the "--strict" flag is for. Sorry thus does not appear in the markdown docs but should appear if you view the cli help text.

**Comment by travi** [comment]
Thanks. That's exactly what I was after.

**Comment by lgufc** [comment]
> This is exactly what the "--strict" flag is for. Sorry thus does not appear in the markdown docs but should appear if you view the cli help text.

@charlierudolph is it still working this way? I've tried to use --dry-run --strict in case of ambiguous and undefined steps and each time I'm getting exit code 0, though ambiguous steps are red and mentioned in console log

Thanks in advance!
