### ISSUE TITLE
How to report on skipped/pending scenarios

### ISSUE THREAD

**Issue by dexster** [cucumber/cucumber-js#671]
How do I get pending or skipped scenarios to appear in any reports? I've tried using @pending and @ignore tags on the relevant scenarios but I do not see any count of these scenarios in test result output. Is there some extra config I need to add?

**Comment by charlierudolph** [comment]
Can you please provide a reproducible example of what you are seeing and what you expect / want to see?

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed

**Comment by cliffmeyers** [comment]
@charlierudolph We are interested in getting visibility into which features or scenarios were skipped via the "ignore operator" when applied against a tag name, (e.g. `~@ignore`). The "skipped tests" concept is pretty popular and supported in the JUnit XML format, Jenkins CI, etc.

Looking at the JSON formatter output, it seems that the element with `type: "scenario"` would be the best candidate for flagging as "skipped" in some way. I suppose it could also be applied to the top-level elements with `keyword: "Feature"` as well. 

Any thoughts as to the feasibility of this?

**Comment by cliffmeyers** [comment]
@charlierudolph ping for follow-up. Also, I realized that the reports do have a notion of "skipped" already: when a step fails, the following steps in the scenario are marked as skipped. Conceptually it's a little different than "ignored" but I think there's value in being able to report on both, and maybe the distinction isn't all that important. Any thoughts?

**Comment by goofballLogic** [comment]
Instead of excluding tags, you can instead handle those tags with a `Before` step, like so:

```
Before({ tags: "@TODO" }, function() {

    return "pending";

});
```

**Comment by charlierudolph** [comment]
@cliffmeyers if you use the event protocol formatter it has events for "pickle rejected"
