### ISSUE TITLE
How to control `maxBuffer` - Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by iongion** [cucumber/cucumber-js#673]
Recently `CucumberJS` throws this:
```
Error: stdout maxBuffer exceeded
```

**Comment by charlierudolph** [comment]
Can you please give more information?

What environment are you running in?
What cucumber-js version are you using? 
What formatter are you using?
Can you provide a minimal reproducible example?

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed
