### ISSUE TITLE
Support pendingReason

### ISSUE THREAD

**Issue by jookshub** [cucumber/cucumber-js#678]
Hello,

while the `self.storePendingStepResult` supports a `pendingReason` the `step_definition.js` does not provide a way to pass it through the `callback`. At least I could not find a way to do this.

So I adjusted the `finish` - Function of `step_definition.js` to this:

   
```
function finish(error, result, pendingReason) {
        var stepResultData = {
          step: step,
          stepDefinition: self,
          duration: durationInNanoseconds(start),
          attachments: scenario.getAttachments(),
        };

        if (result === 'pending') {
          stepResultData.status = Cucumber.Status.PENDING;

          // -> include pendingReason
          if (typeof pendingReason === 'string') {
              stepResultData.pendingReason = pendingReason;
          }

        } else if (error) {
          stepResultData.failureException = error;
          stepResultData.status = Cucumber.Status.FAILED;
        } else {
          stepResultData.status = Cucumber.Status.PASSED;
        }

        var stepResult = Cucumber.Runtime.StepResult(stepResultData);
        callback(stepResult);
      }

      var validCodeLengths = self.validCodeLengths(parameters);
      if (validCodeLengths.indexOf(code.length) === -1) {
        return finish(self.invalidCodeLengthMessage(parameters));
      }

      Cucumber.Util.run(code, world, parameters, timeoutInMilliseconds, finish);
    }
```

and also the `finish` Function of the `Util/run.js` to this:

```
function finish(error, result, pendingReason) {
    Cucumber.Util.Exception.unregisterUncaughtExceptionHandler(finish);
    if (timeoutId) {
      Cucumber.Util.RealTime.clearTimeout(timeoutId);
    }
    if (error && !(error instanceof Error)) {
      error = util.format(error);
    }
    callback(error, result, pendingReason);
    callback = function() {};
  }
```

Which made it possible to do steps definitions like this:

```
this.Given(/^a pending step$/, function (callback) {
        callback(null, 'pending', 'my pending reason');
    });
```

Now I've done this just to get a better understanding of how the steps are processed and to clean-up my console output. But this seems to be an easy additional feature and it is already ready to be reviewed and included.

I am a bit new to active merge contributions via gitHub, so I am putting this here for you Devs to decide.

**Comment by charlierudolph** [comment]
I personally don't like the idea of pending steps and don't think they should be committed into the codebase. To me they are just a temporary step in the development process. What is an example of a pending reason you wanted to give?

The pending reason you found in the summary formatter was a holdover from the previous interface and should be removed.

**Comment by floribon** [comment]
If that was ever added we would need an equivalent for promise interface (such as allowing a promise to resolve into something like `{status: 'pending', reason: 'because'}`).

But no production need personally.

**Comment by jookshub** [comment]
@charlierudolph without pending steps you would have to describe AND implement complete scenarios and could or should not commit a feature-file that is not fully implemented. My bet is, development will never be that clean. 

Situations like "I have this feature-file with X scenarios, let's implement those in a feature branch" will occur and generate commits with pending steps - and that would be ok for me.

I've wanted a _pendingReason_, because _pending_ is not an unambiguous term. So I've wanted the message to state "pending: to be implemented" in order to be precise.

But if _pendingReason_ is deprecated and _pending_ state is not used in other ways than "not implemented", I guess it is ok.

**Comment by charlierudolph** [comment]
Personally, I never commit incomplete features. I dislike pending steps because thats basically leaving a todo in the code which I would rather put in an issue tracker.

I think you can just leave the step undefined and thus it need to be implemented. Pending works as well but you can always get the pending snippet by running cucumber.
