### ISSUE TITLE
[2.0-rc1] Trying to extend frozen World

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#682]
The new attachment API is problematic for us. We have quite a strict test state management system in Cucumber Pro's feature suite where the World object is frozen after instantiation. This causes [step_runner.js:15](https://github.com/cucumber/cucumber-js/blob/master/src/runtime/step_runner.js#L15) to fail with `TypeError: Cannot define property:attach, object is not extensible.`.

I've been tempted several times to mess around with the World instances to expose helpers but always refrained from doing so because of potential name clashes and issues like the one we're running into now.

@charlierudolph would it be possible to revert back to a solution that does not involve touching the user-defined World object?

**Comment by charlierudolph** [comment]
Very interesting. I have never frozen my world instance before. I don't like the previous interface as it was only available in hooks and had to be saved in order to be used in steps. Definitely don't want to pass another argument to steps / hooks so I'm not certain what would be a good way to solve this. 

In your case could you work around it by moving the state management system to a property on World instead of freezing the World object?

**Comment by jbpros** [comment]
That's the whole point of our frozen world: it prevents state from being accidentally set on World instead of its `state` property which is our state management system. This has helped us a lot manage state in our complex tests.

I understand that you find the previous attachment interface cumbersome and I agree with you. 

However, I would really like to keep World free from any fiddling around from Cucumber to avoid name clashes and other issues based on bad assumptions (e.g. World is always extensible, we just don't know). Plus with more and more people going down the route of immutability, I would really like to avoid doing this.

And I don't think attachments are important enough to deserve being the rule-breaker here if there is another solution.

Here is a suggestion: we pass the `attach` function to the World constructor, as a second parameter. We could even expose the `attach` function as a method on the default World constructor that Cucumber provides. That would make it simple for beginners, as `attach` is readily available on the default World and it would all doors open to the the other who might not even need it:

    class DefaultWorld {
      constructor(params, attach) {
        this.attach = attach
      }
    }

    class MyWorld {
      constructor(params, attach) {
        this.attachFileToCucumberAndStayAwayFromMyMethods = attach
      }
    }

WDYT?

**Comment by jbpros** [comment]
Side note: in my suggestion, `attach` could be passed as a property of an object as second parameter to World. That way, we can expose more stuff to World constructors if we want to:

    constructor(params, { attach, getRunStatistics, getCurrentScenario }) {

**Comment by charlierudolph** [comment]
Awesome idea! I really like that. My only change would be passing the constructor a single object
```coffee
constructor({attach. params})
```

**Comment by jbpros** [comment]
Glad you like it!

I like the single object signature better too. Makes complete sense.

**Comment by charlierudolph** [comment]
2.0.0-rc.2 released with this fix
