### ISSUE TITLE
Skip features by tags

### ISSUE THREAD

**Issue by mucsi96** [cucumber/cucumber-js#683]
If I understand correctly from the new major release only scenarios could be filtered by tags. The problem is that features will be logged to the console and reports even if they contain no executed scenarios. The expected result would be that only features with executed scenarios are mentioned in the logs and reports. What do you think? 

Thanks. I really like the new refactored code. 👍

**Comment by charlierudolph** [comment]
Sorry that was an unintended change. Should be easy enough to go back to the original behavior

**Comment by mucsi96** [comment]
Thanks for so quick fix! Really appreciate that

**Comment by charlierudolph** [comment]
2.0.0-rc.2 released with this fix
