### ISSUE TITLE
Timeout handlers are always called

### ISSUE THREAD

**Issue by mucsi96** [cucumber/cucumber-js#686]
I found an issue with current implementation of `user_code_runner`. If I add a `console.log` statement to the timeout handlers  then I can see that the timeouts are not cleared if the step was successful. This is not visible because cucumber bin uses `process.exit` to force the exit. But if someone use Cucumber programatically and try to shutdown gracefully the node process will not exit until all timeouts finish. That was my case in https://github.com/mucsi96/nightwatch-cucumber when I tried to add cucumber 2 support. It was really hard to find why my node process is not exiting :)

`timeout was called` will be logged on every step.
```
const timeoutPromise = new Promise(function (resolve, reject) {
  clearTimeout = Time.setTimeout(function() {
    console.log('timeout was called');
    const timeoutMessage = 'function timed out after ' + timeoutInMilliseconds + ' milliseconds'
    reject(new Error(timeoutMessage))
  }, timeoutInMilliseconds)
})
racingPromises.push(timeoutPromise)
```

I wanted to submit a PR. But could not find a good way to test this :(
A solution whould be:
```
let timeoutId
const timeoutPromise = new Promise(function (resolve, reject) {
  timeoutId = Time.setTimeout(function() {
    const timeoutMessage = 'function timed out after ' + timeoutInMilliseconds + ' milliseconds'
    reject(new Error(timeoutMessage))
  }, timeoutInMilliseconds)
})
racingPromises.push(timeoutPromise)

let error, result
try {
  result = await Promise.race(racingPromises)
  timeoutId && Time.clearTimeout(timeoutId)
} catch (e) {
  timeoutId && Time.clearTimeout(timeoutId)
  if ((e instanceof Error)) {
    error = e
  } else if (e) {
    error = util.format(e)
  } else {
    error = 'Promise rejected without a reason'
  }
}
```

**Comment by charlierudolph** [comment]
2.0.0-rc.2 released with this fix
