### ISSUE TITLE
feature file must be under the features dir?

### ISSUE THREAD

**Issue by imzengyang** [cucumber/cucumber-js#690]
hi,  when my feature file is like "features/XXX/xx.feature", running the test will get all the step undefined.
![image](https://cloud.githubusercontent.com/assets/22312483/20879698/fb3d0514-bb0f-11e6-9830-b53e79c262ca.png)

Does feature file must be under the features dir?

thank you. :)

**Comment by charlierudolph** [comment]
To use the default configuration for requiring support files yes. See the docs [here]( https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#requiring-support-files). If you add some requires to your default profile, you should be able to nest your features. This has always annoyed me that the default require does not account for this very common case and I will update it to do so
