### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by eltoro** [cucumber/cucumber-js#692]
I'm using supertest to make a request to my API running in docker and I'm getting some strange behavior. If I run this with the callbacks, all of the requests err out with 'Error: socket hang up'. But I realized that for some reason the requests are delayed. When I remove the callbacks the first one still errs but the following requests are ok. I'm using a Scenario Outline with Examples so the request is made 4 times.

given.js:
```
const request = require('supertest');
module.exports = function givens() {
  this.Given(/^then system is active$/, function (callback) {
    this.request = request.agent('http://localhost:8787');
    callback();
  });
}
```

thens.js:

```
module.exports = function whens() {
  this.When(/^the client requests a list of questions with the parameters of "([^"]*)" and "([^"]*)" and "([^"]*)" and "([^"]*)" and "([^"]*)" and "([^"]*)"$/,
    function (companyId, state, propertyType, yearBuilt, floodZone, active, callback) {
      var json = {
        ...
      };

    this.request.post('/questions')
      .send(json)
      .set('Accept', 'application/json')
      .end((err, res) => {
        console.log(err);
        //return callback();
      });
  });
}
```

**Comment by charlierudolph** [comment]
I'm not seeing anything wrong with you code. As a note, cucumber-js supports synchronous steps so you don't always need the callback.

Can you please provide the two versions of your code you mention and what cucumber-js outputs for each.

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed.
