### ISSUE TITLE
setting environment variables

### ISSUE THREAD

**Issue by travi** [cucumber/cucumber-js#696]
is there a preferred approach for setting node environment variables for use in the system-under-test? 

i'm fairly sure that i used to be able to set them simply with `process.env.FOO = 'bar'` in a `Before` hook, but i fairly recently found myself needing to move that setup into the `World` constructor. with the new release candidates, i don't seem to be able to set them there either.

**Comment by charlierudolph** [comment]
Is your system-under-test being run in the same node process?

**Comment by travi** [comment]
yep. with no other changes, switching to any of the release candidates makes tests fail due to missing values that come from env vars currently defined in my `World` constructor. 

i'll admit that i haven't traced it very far because i wanted to confirm if there was some known limitation or recommended approach that i should be aware of. if you are suggesting that it should just work, as i would have expected, i can dig deeper. but, if you have any thoughts on things i should should focus on trying, i'm interested in those thoughts, too.

**Comment by charlierudolph** [comment]
The world constructor did change in the release candidates as to what is passed to it if you are using the `--world-parameters` CLI option. Otherwise I believe it should just work.

**Comment by travi** [comment]
my cli command is simply `cucumber.js test/integration --compiler js:babel-register --tags ~@wip --strict`, run as an npm script. i'll try to dig in deeper when i have a chance then

**Comment by travi** [comment]
i found some time to dig into this a bit and tracked it down to static import resolution. after the [shift to es6](https://github.com/cucumber/cucumber-js/blob/bef2f7e603d0a94a1727d3e4fe6bc0de998aa531/CHANGELOG.md#breaking-changes-3) in rc.0 (i guess i hadn't updated this particular project to any of the RCs after seeing tests fail), import resolution now happens statically. 

My setting of environment variables was happening in the test setup code, which now would have run after my app tried to start up because of the more eager import. 

Using a traditional `require` after populating the environment variables has resolved my issue.
