### ISSUE TITLE
Recommended approach for sharing state across step definitions

### ISSUE THREAD

**Issue by dueckes** [cucumber/cucumber-js#698]
A question re something that's not clear in the documentation:
If I choose to break-up my step definitions across a number of files, what is the recommended approach for sharing state across steps in these files?

For example, when I try the following:
_world.js_
```
module.exports = function World() {
  this.sharedState = null;
}
```

_step-defintion-a.js_
```
import World from '../support/world';

module.exports = function () {
  this.World = World;

  this.Given(/^some a step$/, function () {
    console.log(this.sharedState);
    this.sharedState = 'a';
  });

}
```

_step-defintion-b.js_
```
import World from '../support/world';

module.exports = function () {
  this.World = World;

  this.Given(/^some b step$/, function () {
    console.log(this.sharedState);
    this.sharedState = 'b';
  });

}
```

`this` changes independently per file -> i.e. step file 'a' never logs a sharedState of 'b' and vice-versa.

Perhaps I'm missing something here?

**Comment by charlierudolph** [comment]
Each steps file does not receive its own World instance. You should only set `this.World` once and that will be used by all step definitions / hooks

**Comment by charlierudolph** [comment]
You may not be getting anything output because uou are logging `this.state` and setting `this.sharedState`.

**Comment by dueckes** [comment]
@charlierudolph 

Re logging `this.state` - example was contrived - have updated now for clarity.

This problem was a false alarm, my step definitions had a mix of fat-arrow and conventional function definitions - converting all to fat-arrow solved the problem.

Regarding setting `this.World` once, I've actually taken it out of all step files and tests are still working - not sure why though.

**Comment by charlierudolph** [comment]
Your world constructor is so simple its not needed. The default world constructor works as you are just setting properties on the world instance.

**Comment by charlierudolph** [comment]
Also, step definitions can't use the fat arrow as that binds `this` preventing the world instance from being able to be set as this when executing the step definitions
