### ISSUE TITLE
Pass argument(s) to World constructor

### ISSUE THREAD

**Issue by egorse** [cucumber/cucumber-js#70]
Would it be safe to run cucumber-js with custom cli argument(s) and handle those in World constructor?

Example:
```
#cucumber-js --tag @reboot --target 192.168.1.10
```

So far it works but is that intentionally or is it a side effect?

**Comment by charlierudolph** [comment]
Thoughts on just adding [] to the variable name if you want it to be an array?
```
--param a=1 --param b[]=2 --param b[]=3
```
Would result in
```js
this.Given(/^some step$/, function (callback) {
  this.a.should.equal('1');
  this.b.should.be.an.instanceOf(Array);
  this.b.should.have.length(2);
  this.b[0].should.equal('2');
  this.b[1].should.equal('3');
  callback();
});
```
Even if there is a custom world constructor, the params can simply be set on the objects on the world constructor.

**Comment by appubinu** [comment]
can I pass a value through command line which I can access it in step_def? I am using cucumber@0.7.0. If I can, can you please give me an example?

**Comment by charlierudolph** [comment]
@appubinu: see this [comment](#issuecomment-6356177) if you are not on a windows machine for an available workaround. Otherwise no, it is not currently possible.

**Comment by charlierudolph** [comment]
I'd really prefer this to just be handled by using environment variables. Windows does appear to have the ability to set environment variables even though the syntax is a bit different.

**Comment by riaan53** [comment]
Hi,

Environmental variables is not always the best option.

To iterate tests over different environments using grunt or gulp it's nice
to just pass in the variables to the world object. And if we use concurrent
runs environmental vars won't work at all.

Regards,
Riaan

On Wednesday, 18 November 2015, Charlie Rudolph <notifications@github.com>
wrote:

> I'd really prefer this to just be handled by using environment variables.
> Windows does appear to have the ability to set environment variables even
> though the syntax is a bit different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cucumber/cucumber-js/issues/70#issuecomment-157768839>
> .
>


-- 
Riaan Jacobs
riaan53@gmail.com

**Comment by boltozavr** [comment]
PING[2]. I can't set environment variables (Windows 7)
node_modules\\.bin\\cucumber-js features --WORLD=demo --format=pretty
This doesn't cause any errors, but there is no process.env.WORLD variable :(

for example:
node_modules\\.bin\\cucumber-js features --profile=demo --format=pretty it works. But i am still need environment variables :(

**Comment by vsashidh** [comment]
I would like to launch the browser at an environment specific URL. So I was thinking of running my tests using the following command from the root directory where a features folder is located: 

`cucumber-js envName=DEV`

But I run into the following error:

`Error: ENOENT: no such file or directory, lstat 'C:\Workspace\parent\child\envName=DEV

I understand there might be a need to add `--param|--params` option to support this in windows through this open issue. But I was more curious of why not instead let custom parameters pass through so that custom code can be written to process these custom parameters. By custom code I mean nodejs's `process.argv` array.

**Comment by FastNinja** [comment]
Hi there. is there a way to pass Environment variables or parameters when we run Cucumber tests?
We have 3 different environments (DEV,SIT, PROD) and we would like to run tests on all of them - so tests need to know which URL to call .

**Comment by iurimatias** [comment]
is there any solution to this? have the same problem, need to support both linux and windows

**Comment by igorpupkinable** [comment]
@FastNinja there are few options/workarounds for this.
You can read environment variable (`process.env.ENV_VARIABLE`) in your step definition or in a hook.
If you use task runner then you can create enviroment specific task to set/export variable before running cucumber.
```
if(process.env.TEST_ENV == 'prod') {
  // do something
}
```

Also you can use cucumber's profile argument for workaround. For example after invoking `cucumber --profile prod` you can read profile value from `process.argv`. I do not have the code by the hand but I have used something like this in BeforeFeaturesHook to set some stuff:
```
const args = process.argv
const isProd = (args[args.indexOf('prod') - 1] == '--profile')

if(isProd) {
  // do something
}
```

**Comment by benfr1** [comment]
you can drive this using par exemple :
`Before(function ()  
{ 
  console.log  ( process.env.ENV.trim()  ) ;
    console.log  ( (process.env.location).trim()  ) ;}

and 

WINDOWS:
set location=windows & set ENV=PREPROD & "...node_modules\.bin\cucumber-js"

LINUX/Jenkins:
export ENV=PREPROD && export location=ubuntu  && ./node_modules/.bin/cucumber-js `
