### ISSUE TITLE
publish via CI

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#702]
Using travis, deploy on tags. Also update the browser example to only be updated on tags

**Comment by charlierudolph** [comment]
@jbpros I am going to set this up with my NPM account initially. Could you or @aslakhellesoy please create a dedicated cucumber account on npm (if one doesn't exist) and send me the email and auth token associated with the account?

**Comment by jbpros** [comment]
I'm on my phone now but I'll do it tomorrow.

**Comment by charlierudolph** [comment]
Thanks. This is now setup and we can switch out the credentials anytime.

**Comment by jbpros** [comment]
https://www.npmjs.com/~cucumber is currently taken. I've sent an email (Charlie, you're in CC) to ask the current owner if he'd be happy to give it to us.

I'll keep you posted!

**Comment by charlierudolph** [comment]
If he'd rather not cede the name, I think it'd be fine just using something like `cucumber-bot` ot `cucumber-ltd`

**Comment by jbpros** [comment]
Yeah I agree. It would be nice to have it though. Let's wait for a couple of weeks or so. I guess there is no urgency, right?

**Comment by charlierudolph** [comment]
Correct

**Comment by charlierudolph** [comment]
@jbpros any update on this? From the emails I believe we were unable to secure the `cucumber` user on npm and we could go with one of the alternative names

**Comment by charlierudolph** [comment]
Thanks you very much @jbpros

**Comment by jbpros** [comment]
About time, right? 🙈

**Comment by charlierudolph** [comment]
@jbpros from the latest attempt to publish it appears the auth token you gave me doesn't work.

https://travis-ci.org/cucumber/cucumber-js/jobs/262305173 - open the second deploy section

**Comment by jbpros** [comment]
what should I do @charlierudolph?

**Comment by charlierudolph** [comment]
The NPM_AUTH_TOKEN env variable on travis needs to be updated. Uncertain how to test it until our next release

**Comment by charlierudolph** [comment]
@jbpros bump. Did you get a chance to update the token?

**Comment by charlierudolph** [comment]
Closing this with the caveat that it is currently using my token. Will need to transition this if I leave the project.
