### ISSUE TITLE
Code snippets are no longer in a valid format 2.0.0-rc.5

### ISSUE THREAD

**Issue by john-mclean** [cucumber/cucumber-js#710]
The code snippets, and subsequently all step definition files, are no longer valid.

The CHANGELOG.md indicates this change happened with 2.0.0-rc.4:

> ### [2.0.0-rc.4](https://github.com/cucumber/cucumber-js/compare/v2.0.0-rc.3...v2.0.0-rc.4) (2016-12-19)
> 
> #### Breaking Changes
> 
> * update support code library interface - instead of exporting a function and calling methods on `this`, require the `cucumber` module and call `defineSupportCode` which passes an object as the first argument whch exposes the methods. Overriding the world constructor has changed from overriding the World property to calling `setWorldConstructor`.
>     ```js
>     // 1.3.1
>     module.exports = function () {
>       this.Given(/^a step$/, function() {});
>       this.World = CustomWorld
>     });
> 
>     // 2.0.0
>     var {defineSupportCode} = require('cucumber');
> 
>     defineSupportCode(function({Given, setWorldConstructor}) {
>       Given(/^a step$/, function() {});
>       setWorldConstructor(CustomWorld);
>     });
>     ```
> 

Uploading .feature files is not supported on github, so I have appended .txt to the feature file.
[test.feature.txt](https://github.com/cucumber/cucumber-js/files/677943/test.feature.txt)

Sample output:

$ ./node_modules/cucumber/bin/cucumber.js -v
2.0.0-rc.5

$ ./node_modules/cucumber/bin/cucumber.js
Feature: test cucumber

    As a test engineer
    I want cucumber to provide valid code snippets
    So that I can write valid step definitions

  Scenario: A simple test
  ? Given I have a test with no step definition
  ? When I execute the test
  ? Then I receive a valid code snippet

Warnings:

1) Scenario: A simple test - features/test.feature:8
   Step: Given I have a test with no step definition - features/test.feature:9
   Message:
     Undefined. Implement with the following snippet:

       this.Given('I have a test with no step definition', function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

2) Scenario: A simple test - features/test.feature:8
   Step: When I execute the test - features/test.feature:10
   Message:
     Undefined. Implement with the following snippet:

       this.When('I execute the test', function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

3) Scenario: A simple test - features/test.feature:8
   Step: Then I receive a valid code snippet - features/test.feature:11
   Message:
     Undefined. Implement with the following snippet:

       this.Then('I receive a valid code snippet', function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

1 scenario (1 undefined)
3 steps (3 undefined)
0m00.000s

**Comment by charlierudolph** [comment]
Thanks for reporting this!

**Comment by charlierudolph** [comment]
Released in 2.0.0-rc.6
