### ISSUE TITLE
Version 2.0.0 "Cannot call a class as a function" with Protractor and protractor-cucumber-framework

### ISSUE THREAD

**Issue by niekoost** [cucumber/cucumber-js#712]
Hi guys,

when I try Protractor with Cucumber version 1.3.1 it all works:

![no-error-cucumber-1 3 1](https://cloud.githubusercontent.com/assets/359593/21562525/c51db4ba-ce79-11e6-9139-37f6e67fc7db.png)

But with the 2.0.0 version, it does not.

![error-cucumber-2 0 0-rc 5](https://cloud.githubusercontent.com/assets/359593/21562554/10016bc0-ce7a-11e6-8da7-0acc80af1a08.png)

I am using Ubuntu 
Linux ... 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by charlierudolph** [comment]
I believe this is an issue for protractor-cucumber-framework. The cucumber-js internals changed with the 2.0 release candidates. It is a break change and `protractor-cucumber-framework` needs to update to those changes (but probably shouldn't until 2.0 is officially released).
