### ISSUE TITLE
Provide Cucumber Typescript definitions within this package

### ISSUE THREAD

**Issue by daspr2** [cucumber/cucumber-js#713]
As of right now, the cucumber-js [typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/cucumber) are defined in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

A typescript user that wants to use cucumber-js must have both cucumber and @types/cucumber in their dependencies. Providing the definitions within this package eliminate the need to install the @types/cucumber package. 

Also, it would be easier to track the changes needed in the typescript definitions when the cucumber-js API changes. Furthermore, since cucumber-js contributors know well the API, they could provide helpful advices to people that want to update/correct the typescript definitions.

There is currently an open issue on the DefinitelyTyped repo to remove packages that provides their own definitions (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13364), so I think this is a normal path to adopt.

**Comment by charlierudolph** [comment]
Sounds fine to me. I personally don't use Typescript, and I rather someone who does implement it. At the very least it will also need some tests to ensure it says up to date.

**Comment by daspr2** [comment]
I agree for the tests. However, I'm not sure what kind of tests we can create to ensure that the definitions are up to date. 

Could we define a feature and implement the step definitions in typescript? The step definitions could use the API elements that we want to watch for change. Then, we could have a special npm script that runs that feature with the --compiler ts:ts-node/register option. If the feature is successful, then we could assume that the definitions are up to date. 

Does that sound reasonable?

**Comment by jordanmorris** [comment]
This would be very helpful for ensuring they are up-to-date and are changed along with the API, just like the readme. The recent API changes in RC4 are currently not reflected in the typings, so as a typescript user, I'm currently stuck with RC3.

**Comment by daspr2** [comment]
As of right night, there are some [pending pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?utf8=%E2%9C%93&q=cucumber) for the cucumber-js definition types on the DefinitelyTyped repo.

I suggest to wait until all those pull requests are merged and closed. Then, the [definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/cucumber/index.d.ts) should be copied over in this repository. Tests should also be created to ensure that the definitions are accurate and up-to-date with the cucumber-js API.

Once everything is working and merged, the definitions on the DefinitelyTyped repo should be removed.

I can start working on this (once the cucumber pr are closed on DefinitelyTyped repo).

**Comment by daspr2** [comment]
@charlierudolph Hi Charlie. I've started to work on this issue. However, there are a few things that are blocking me, and other that I'm not sure on what is the best way to do it. 

Is this issue thread the best to discuss about those things? If not, what are other alternatives?

This is my first real GitHub contribution and I'm still not familiar with the whole procedure. Thanks for helping.

**Comment by charlierudolph** [comment]
If you don't have anything yet we can discuss here but if you have some changes already you can create a pull request and we can discuss there.

**Comment by charlierudolph** [comment]
Closing due to age. If anyone would like to work on this the PR should include some tests to ensure that the types are up to date.

**Comment by bruce-lindsay** [comment]
Added a v4 typings file to definitely typed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23241

If you want to move typings into the cucumber-js repository I can help out with that.
