### ISSUE TITLE
NodeJs Example fails on win 7

### ISSUE THREAD

**Issue by ochemerys** [cucumber/cucumber-js#714]
Hi,
I run NodeJs Example on win 7 with NodeJs v6.9.2 and NPM v 4.0.5
My package.json is
```
{
  "name": "cucumber-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chromedriver": "^2.25.1",
    "cucumber": "^2.0.0-rc.5",
    "selenium-webdriver": "^3.0.1"
  }
}
```
My project structure in root is
--- /features
      ---  /step_definitions
            --- browser_steps.js
            --- hooks.js
      --- /support
            --- world.js
      --- documentation.feature
--- /node_modules
--- package.json

All features files contain code from NodeJs Example
When I run 
`node_modules\.bin\cucumber-js.cmd`
I have
0 scenarios
0 steps
0m00.000s

Can anybody explain me why cucumber is not able to find feature and run steps?

**Comment by charlierudolph** [comment]
Can you please update you project structure to properly show which files are under which folders? The `documentation.feature` file needs to be under the `features` folder and I can't tell if it is.

**Comment by ochemerys** [comment]
Hi charlierudolph, this is my project file structure
/features
--- /step_definitions
--- --- browser_steps.js
--- --- hooks.js
--- /support
--- --- world.js
--- documentation.feature
/node_modules
package.json

image is attached:
![image](https://cloud.githubusercontent.com/assets/20651535/21595810/440cd112-d0ef-11e6-95a3-9c5c392223ea.png)

**Comment by ochemerys** [comment]
My apologies. Scenario was commented out. That's why I had 0 scenarios
Actual response 
Feature: Example feature

    As a user of Cucumber.js
    I want to have documentation on Cucumber
    So that I can concentrate on building awesome applications

  Scenario: Reading documentation
  × Given I am on the Cucumber.js GitHub repository
  - When I click on "CLI"
  - Then I should see "Running specific features"

Failures:

1) Scenario: Reading documentation - features\documentation.feature:7
   Step: Given I am on the Cucumber.js GitHub repository - features\documentation.feature:8
   Step Definition: features\step_definitions\browser_steps.js:6
   Message:
     Error: function timed out after 5000 milliseconds
         at Timeout.<anonymous> (D:\TRAINING\CUCUMBER\NodeJs_Example\node_modules\cucumber\lib\user_code_runner.js:51:28)
         at ontimeout (timers.js:365:14)
         at tryOnTimeout (timers.js:237:5)
         at Timer.listOnTimeout (timers.js:207:5)

2) Scenario: Reading documentation - features\documentation.feature:7
   Step: After
   Step Definition: features\step_definitions\hooks.js:5
   Message:
     Error: function timed out after 5000 milliseconds
         at Timeout.<anonymous> (D:\TRAINING\CUCUMBER\NodeJs_Example\node_modules\cucumber\lib\user_code_runner.js:51:28)
         at ontimeout (timers.js:365:14)
         at tryOnTimeout (timers.js:237:5)
         at Timer.listOnTimeout (timers.js:207:5)

1 scenario (1 failed)
3 steps (1 failed, 2 skipped)
0m10.027s

**Comment by ochemerys** [comment]
and Chrome browser is opened at the same time while i'm getting failed tests
![image](https://cloud.githubusercontent.com/assets/20651535/21596617/9e52d7c4-d0fa-11e6-98ab-420db9f3644c.png)

**Comment by charlierudolph** [comment]
That looks like an example where the browser didn't finish loading in time. Try upping the timeout to 10000 ms

**Comment by ochemerys** [comment]
Thanks a lot. I set wait time for 10000 ms and it starts working, amazingly after that I reduced wait time to 2000 ms and it works.
Thanks.

**Comment by natkrish** [comment]
@charlierudolph  where do I increase the timeout? I am getting this error when running protractor-cucumber-typescript tests 
 Error: function timed out after 5000 milliseconds
