### ISSUE TITLE
Can't generate steps to a file

### ISSUE THREAD

**Issue by chendachao** [cucumber/cucumber-js#717]
Is it possible to add a functionality which allow us to generate steps to a specified target file,

It could be something like this: `cucumber-js login.feature --step login.steps.js`, which could generate a `login.steps.js` file.

**Comment by charlierudolph** [comment]
You can get something close with 
```
cucumber-js login.feature --dry-run --format snippets:login.steps.js
```
Use the `--dry-run` flag to prevent it from running any defined steps.
Use the snippets formatter which prints just the snippets for undefined steps.

The outputted file will need a few updates to make it work but with all the different languages that transpile to javascript I think that the best we can get.

**Comment by chendachao** [comment]
Thanks @charlierudolph, I can get undefined steps in console, but still need to copy them to a file and modify something,

**Comment by charlierudolph** [comment]
@chendachao cucumber-js has output redirection so you should be able to get them to go straight to a file. 

https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats

As I mentioned in the previous comment, yes, currently you will still need to modify the file to make it work. I think this is good enough for now.

**Comment by charlierudolph** [comment]
@chendachao closing as I believe you question has been answered. Please reopen if there is more to discuss.
