### ISSUE TITLE
Output junit format

### ISSUE THREAD

**Issue by dsgill** [cucumber/cucumber-js#723]
It would be very helpful if cucumberjs supported output format of junit xml. This is a fairly standard output format for test packages but currently the best we can do is to output as json and convert the json to junit after the fact. The packages that allege to support this operation don't work well or at all (at least in my experience), so it would be great if cucumberjs were updated to produce this output like the other test packages do.

**Comment by charlierudolph** [comment]
The 2.0 release candidates support custom formatters and thus this can be implemented without being in this package.

**Comment by dsgill** [comment]
Are there any junit custom formatters available or would I need to write one myself? I have not found any.

**Comment by charlierudolph** [comment]
i don't believe any are available yet

**Comment by jxc876** [comment]
JUnit XML format in case anyone wants to write a formatter: http://stackoverflow.com/questions/4922867/junit-xml-format-specification-that-hudson-supports

**Comment by charlierudolph** [comment]
Going to close as this will hopefully become a custom formatter

**Comment by NHKK** [comment]
does this code works with the recent changes ?
`function MyFormatter(options) {
  var Cucumber = require('cucumber');

  if (!options)
    options = {};

  var self = Cucumber.Listener.Formatter(options);

  self.handleBeforeFeaturesEvent = function handleBeforeFeaturesEvent(event, callback) {
    var features = event.getPayloadItem('features');
    callback();
  };

  self.handleBeforeFeatureEvent = function handleBeforeFeatureEvent(event, callback) {
    var feature = event.getPayloadItem('feature');
    callback();
  };

  self.handleBeforeScenarioEvent = function handleBeforeScenarioEvent(event, callback) {
    var scenario = event.getPayloadItem('scenario');
    callback();
  };

  self.handleBeforeStepEvent = function handleBeforeStepEvent(event, callback) {
    var stepResult = event.getPayloadItem('step');
    callback();
  };

  self.handleStepResultEvent = function handleStepResultEvent(event, callback) {
    var stepResult = event.getPayloadItem('stepResult');
    callback();
  };

  self.handleAfterStepEvent = function handleAfterStepEvent(event, callback) {
    var step = event.getPayloadItem('step');
    callback();
  };

  self.handleAfterScenarioEvent = function handleAfterScenarioEvent(event, callback) {
    var scenario = event.getPayloadItem('scenario');
    callback();
  };

  self.handleAfterFeatureEvent = function handleAfterFeatureEvent(event, callback) {
    var feature = event.getPayloadItem('feature');
    callback();
  };

  self.handleAfterFeaturesEvent = function handleAfterFeaturesEvent(event, callback) {
    var features = event.getPayloadItem('features');
    self.finish(callback);
  };

  return self;
}

module.exports = MyFormatter;`

**Comment by charlierudolph** [comment]
No. Please see the documentation for custom formatters. There is a link on the readme.
