### ISSUE TITLE
How to access input parameters

### ISSUE THREAD

**Issue by dsgill** [cucumber/cucumber-js#725]
I've been learning about using world parameters with cucumber and I'm unclear about some things.

My need is to pass a JSON object into cucumber, process it once before any scenario runs, and have the resulting variables accessible to all scenario steps.

I know how to pass the parameter in to cucumber, but I'm not clear on how I can process it just once. Not once per scenario, but once for all scenarios. I've seen mention of an env.js file but when I try to print this.parameters, I get undefined.

So how can I access my parameters before any scenarios run and set up some vars that will be accessible by each scenario?

**Comment by charlierudolph** [comment]
> So how can I access my parameters before any scenarios run and set up some vars that will be accessible by each scenario?

The world parameters specified by the CLI are passed directly to the world constructor (which is called once per scenario) so thus there is no direct support for doing this. A possible workaround is to have your the world constructor call some function which does the necessary setup work only the first time its called and does nothing on subsequent calls.

**Comment by charlierudolph** [comment]
@dsgill please reopen if you have any more questions
