### ISSUE TITLE
Not generating new steps definition

### ISSUE THREAD

**Issue by johnlimpin** [cucumber/cucumber-js#729]
I created a new steps in my feature file, ran it, and it passes without actual testing codes in my step definitions. It should generate a methods in the terminal which I can copy then paste it in my list of step definitions. There's nothing wrong with my step since it worked for my other teammate's machine.

Version: 2.0.0-rc.6

**Comment by charlierudolph** [comment]
Can you please give step by step instructions in order to reproduce your error?

**Comment by johnlimpin** [comment]
Sorry, please close, didn't check thoroughly.
