### ISSUE TITLE
Localized spoken language support

### ISSUE THREAD

**Issue by jlous** [cucumber/cucumber-js#730]
Would like support for localised gherkin keywords, like in other cucumber implementations:
https://github.com/cucumber/cucumber/wiki/Spoken-languages

**Comment by aslakhellesoy** [comment]
Have you tried adding `# language: fr` (or whatever language you're using) at the top of your `.feature` files?

**Comment by jlous** [comment]
Aha, that works.  Is it in the docs?

**Comment by aslakhellesoy** [comment]
Yes, on the page you linked to.
