### ISSUE TITLE
New snippets output is string, and not regex like my existing tests

### ISSUE THREAD

**Issue by bigattichouse** [cucumber/cucumber-js#731]
How do I modify the snippet format so that it outputs as regex instead of a string?

Older version of cucumber:
this.Then(/^I see X$/,function (callback) {

New version of cucumber:
this.Then('I see X',function (callback) {

So, now it doesn't see any of my old test steps when I attempt to run cucumber

Did I miss a big change in how the test steps are implemented?

**Comment by charlierudolph** [comment]
Currently there is no option to have snippets output regex. With the 2.0 release candidates we introduced [cucumber-expressions](https://docs.cucumber.io/cucumber-expressions/). The default transformations available are documented [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#addtransformcapturegroupregexps-name-transformer)

**Comment by bigattichouse** [comment]
Any way to run tests in a compatability mode? Or do I need to build a tool to re-write all the old step headers?

**Comment by charlierudolph** [comment]
Hold on can you please explain this;

> So, now it doesn't see any of my old test steps when I attempt to run cucumber

Thats not related to snippets. Please see the [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes-1) for documentation about breaking changes

**Comment by bigattichouse** [comment]
1. I created my feature file
2. I generated files using the snippets, the use the "Regex" form
3. cucumber 0.10.3 I think - worked fine
4. Now, when I attempt to run cucumber, it shows snippets because I have regex form, and it is expecting the new "expressions" form: "Undefined. Implement with the following snippet:" because my step is Given(/^A logged in user$/...) and it wants Given('A logged in user'...)

So is it possible to tell it to run the regex form steps?

**Comment by charlierudolph** [comment]
The difference between string / regex is not causing this. Internally the string `'A logged in user'` will end up being converted to the regex `/^A logged in user$/`. See the link in my last comment as there was a breaking change in how to get support code loaded, you no longer just have support files export functions

**Comment by bigattichouse** [comment]
AAAAAAH... ok.  I think I got it. (after seeing the example in the changelog)

Thank you.
