### ISSUE TITLE
Generated step definition snippets are not found

### ISSUE THREAD

**Issue by temyers** [cucumber/cucumber-js#732]
I'm running `2.0.0-rc.6`

Given a feature file:
```
Scenario: In range shout is heard
    Given Lucy is at [0, 0]
    And Sean is at [0, 900]
    When Sean shouts
    Then Lucy should hear Sean
```

When I run cucumberjs, it outputs the following snippet:
```
Step: Given Lucy is at [0, 0] - features/hear_shout.feature:6
   Message:
     Undefined. Implement with the following snippet:

       Given('Lucy is at [{arg1:int}, {arg2:int}]', function (arg1, arg2, callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });
```

When I add the snippet in a step definitions file, the method is not called/found.  The same output above is produced.

But, re-writing the step definition to use regular expression:
```
Given(/^Lucy is at \[(\d+), (\d+)\]$/, function (x, y, callback) {
    callback(null, 'pending');
  });
```

Then step is found, and marked as pending (expected output)
```
Step: Given Lucy is at [0, 0] - features/hear_shout.feature:6
   Step Definition: features/step_definitions/shout_steps.js:10
   Message:
     Pending
```

**Comment by charlierudolph** [comment]
Thanks for the issue. My guess would be the brackets are not being escaped when the string is converted to a regex

**Comment by temyers** [comment]
Thanks.  I'll try and investigate.

@charlierudolph Can I default the snippet style to regex?

**Comment by charlierudolph** [comment]
@temyers the brackets not being escaped unfortunately is a an issue with one of cucumber-js dependencies (see the linked issue). For now, there is no way to switch back to regex for snippets. I don't think that would be too hard to build however. 

@aslakhellesoy any objection to adding in a switch to allow the snippet pattern format to be regex instead of cucumber expressions? The default will still be cucumber expressions

**Comment by charlierudolph** [comment]
This was fixed with the upgrade to cucumber-expressions@3.0.0. I'm going to break out the ability to change the default snippet style into its own story.
