### ISSUE TITLE
Tag issues with "newcomers"

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#733]
In order to attract newcomers to contribute, we should help them where to start.
Whenever you see a new issue, and you think it is a good fit for someone who isn't familiar with the codebase, tag it with `newcomers`.

All newcomers friendly issues in the cucumber org can be listed [here](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Acucumber+label%3Anewcomers+no%3Aassignee+) - we'll link to that from our yet-to-be-written "How to contribute" page on our website.

This is an ongoing effort, but what you can do right now is to have a scan at existing issues, tag a few of them. Then close this issue.

**Comment by charlierudolph** [comment]
Done.
