### ISSUE TITLE
Came not clear from docs how to use hook params

### ISSUE THREAD

**Issue by CyborTronik** [cucumber/cucumber-js#734]
Is not clear from docs how to implement an AfterStep hook and ability to check if was failed or passed

this one below doesn't work
```
 this.registerHandler('AfterStep', function(ev, callback) {
 ...
    if (ev.isFailed) { }
}
```

**Comment by charlierudolph** [comment]
The AfterStep hook is only passed in the Step object. You would need to use the StepResult hook in order to check if it failed or not. For a step result you would use the `isFailed()` method in order to check if it failed. 

I created another issue for updating the documentation,

**Comment by CyborTronik** [comment]
I've used even this one and did not helped at all.
Just scenario hook works about that:
```
 this.After(function (scenario, callback) {
    if (scenario.isFailed()) {
```

Consider please to reopen this bug.
