### ISSUE TITLE
There is no ability to attach a file just by its url, while you can attach buffer and stream

### ISSUE THREAD

**Issue by CyborTronik** [cucumber/cucumber-js#735]

**Comment by charlierudolph** [comment]
Can you give an example of what url you would pass?

**Comment by CyborTronik** [comment]
try to use relative one, ex: `../any.png`

**Comment by charlierudolph** [comment]
Auhh okay. For now, you can create a readable stream yourself to the file and pass that in. I don't see any reason cucumber needs to add support for passing a relative file path (I've never heard it called a URL before)

**Comment by charlierudolph** [comment]
@CyborTronik please reopen this if there anything more you'd like to discuss on this topic.
