### ISSUE TITLE
speed of delivery

### ISSUE THREAD

**Issue by westlakem** [cucumber/cucumber-js#736]
I'm coming from the ruby world where Cucumber 3 is in RC and there has been official Cucumber 2 support for almost 2 years.  Why is it CucumberJS is just now getting Cucumber 2 support?

**Comment by mattbrunetti** [comment]
It could be due to insufficient funding/resourcing... 

Perhaps an organization member can tell us how to help out with that?

**Comment by aslakhellesoy** [comment]
Hi - I'm the lead of the Cucumber project.

The different Cucumber implementations don't currently follow the same versioning scheme.

The current version of a particular implementation is a reflection of the age of the project, nothing else. The Ruby version started in 2008 and has been through more releases.

One implementation having a higher release number than another one doesn't mean it's "better" in any way.

Does that answer your question?

**Comment by charlierudolph** [comment]
@westlakem I believe @aslakhellesoy has answered your question. Please reopen if you have any more questions
