### ISSUE TITLE
Hooks are not works

### ISSUE THREAD

**Issue by lamartire** [cucumber/cucumber-js#740]
**node**: 7.4.0

**cucumber**: 1.3.1

Test script - `node node_modules/cucumber/bin/cucumber.js -f pretty -t ~@ignore`

Project structure:

![](http://i.imgur.com/BFs4Z96.png)

When my scenarios are finished, `After` hook is not fired.

**hooks.js**:

![](http://i.imgur.com/kQYZDVD.png)

What I do wrong?

**Comment by charlierudolph** [comment]
> When my scenarios are finished, After hook is not fired.
Just to clarify, the `After` hook runs after each scenario.

---

Nothing stands out as being wrong. How can you tell the `After` hook is not working? Also

**Comment by lamartire** [comment]
> Just to clarify, the After hook runs after each scenario.

I know, but `AfterFeatures` handler not fired :cry:
When I start tests and all features are finished, browser is no closed. This is the most important trouble in my issue.

**Comment by charlierudolph** [comment]
The `AfterFeatures` event handler (and all event handlers) do not have access to the "world" and thus I don't believe `this.driver` would be defined during your `AfterFeatures`.

**Comment by lamartire** [comment]
Then how to close driver after executing all tests?
When I try run driver on each test, I have error about session id, although I am execute `this.driver.quit()` in the end.

**Comment by charlierudolph** [comment]
I've handled this type of thing a couple ways in the past.
* Create / quit the driver in the Before / After hooks and thus have a separate driver per scenario
* Have the driver live outside of the cucumber world by creating a DriverManager that is called in Before hooks to get a driver and cache it to the world. On the first call it creates a driver and on all other calls it returns the same created driver. Then in the AfterFeatures hook use the driver manager to make the driver quit.

**Comment by lamartire** [comment]
@charlierudolph, I understand you, thanks.

> Create / quit the driver in the Before / After hooks and thus have a separate driver per scenario

I think this way is better in my case.
Have a nice day! :smiley_cat:
