### ISSUE TITLE
Can't make 'not' work in tags expression

### ISSUE THREAD

**Issue by dsgill** [cucumber/cucumber-js#741]
My understanding of the "not" symbol in a tag expression on the CLI is that if I execute "cucumberjs --tags=~@1.5" then any scenarios NOT tagged with @1.5 should run. That seems to be the way cucumber defines it. But when I try that, no scenarios are run although I have 3 scenarios not defined with @1.5. I would expect those 3 to all run. Can you explain how I can get this to work?

**Comment by dsgill** [comment]
Could I please get an answer to this question? tags don't appear to work they way your doc says. Is there a bug or is there a specific way to make it work?

**Comment by sankargorthi** [comment]
Piggybacking on this, I can't get to use combined tags to execute specific scenarios

```
@foo @bar
Scenario: Test Scenario
  ...
```

```
$ cucumber --tags @foo,@bar
0 scenarios
0 steps
0m00.000s
```

**Comment by charlierudolph** [comment]
What version of cucumber are you using? Those two syntaxes are for 1.3.1 whereas the 2.0 release candidates use [a new syntax](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#tags)

**Comment by charlierudolph** [comment]
I looked back at 1.3.1 and those syntaxes appear to be worked on that version

**Comment by charlierudolph** [comment]
Please reopen if there is more to discuss.
