### ISSUE TITLE
Demo does not work on FireFox: "ReferenceError: Cucumber is not defined"

### ISSUE THREAD

**Issue by jxc876** [cucumber/cucumber-js#742]
# Steps to Recreate

1. Navigate to the demo page from the READ ME : http://cucumber.github.io/cucumber-js/
2. Click 'Run Feature'

Output tab is displayed with `ReferenceError: Cucumber is not defined`
It seems to work fine in Chrome.

# Browser Details 

* Tested using: Firefox v 38.8.0 on MacOS Sierra (v 10.12.2)

**Comment by charlierudolph** [comment]
Works for me on Firefox v 51.0.1 (currently the latest version) on MacOS Sierra (v 10.12.2). Can't find an easy way to download that particular version of firefox (most browsers discourage using the old versions anyway). I'm going to close this as won't fix.
