### ISSUE TITLE
Error parsing Cucumber.js file after installation with Node.

### ISSUE THREAD

**Issue by charandeep18** [cucumber/cucumber-js#747]
I'm currently having problems with the cucumber library after installing it via npm into an HTML5/JS Application with Node.js in Netbeans. The command that I had used to install it was:

- npm install cucumber

My version of Node and npm are:
npm: 4.1.2
Node: v7.5.0

The error states that there are currently errors parsing the cucumber.js file. Any help would be much appreciated as I'm new to both Node and Cucumber.

**Comment by charlierudolph** [comment]
The browser based [example](http://cucumber.github.io/cucumber-js/) is using `dist/cucumber.js` from the latest release. Is there more information you can give?

**Comment by aslakhellesoy** [comment]
The full error message and the file contents of `cucumber.js` would probably be a good start.

**Comment by charandeep18** [comment]
Thanks both for taking the time out to reply, here are the contents of cucumber.js:
`
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../cucumber/bin/cucumber.js" "$@"
  ret=$?
else 
  node  "$basedir/../cucumber/bin/cucumber.js" "$@"
  ret=$?
fi
exit $ret
`

I'm not exactly sure how to provide the full error message, the only message I can see is "error parsing file" when hovering over the file in the projects tab.

**Comment by charlierudolph** [comment]
Auhh. Sorry @charandeep18 I was confused. The `cucumber.js` file in the directory you are running cucumber in has special meaning. See this [documentation](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#profiles). That file should probably be renamed to `cucumber_profiles.js` and possibly switch from `.js` to `.yml` to make it more clear its a configuration file

**Comment by charlierudolph** [comment]
@charandeep18 please reopen if you have any more questions
