### ISSUE TITLE
[Question] Should a failing hook count as a scenario failure?

### ISSUE THREAD

**Issue by sankargorthi** [cucumber/cucumber-js#749]
I have about 10 scenarios, with 4 that show the relevant step failing, so far; I hat not noticed an error I'd introduced into a hook:

```javascript
import {unlinkSync} from 'mz/fs';
import {defineSupportCode} from 'cucumber';

defineSupportCode(function ({After}) {
  After(function* () {
    yield unlinkSync('file.out');
    /**** This is an error as the sync function returns undefined ***/
  });
});
```

```bash
1) Scenario: Scenario name - features/main.feature:15
   Step: After
   Step Definition: features/support/hooks.js:13
   Message:
     TypeError: A value undefined was yielded that could not be treated as a promise
...

10 scenarios (5 failed, 5 passed)
60 steps (4 failed, 16 skipped, 40 passed)
1m36.625s
npm ERR! Test failed.  See above for more details.
```

The actual steps are not indicated as erroring out. Is this expected and normal behavior?

**Comment by charlierudolph** [comment]
Yes this is intended. If a hook failed, the scenario is marked as failed. Currently hooks are not reports in the `steps` count however. I'm not sure the original reason for that. Thats how it was before I started working on this project and it hasn't been discussed.

**Comment by sankargorthi** [comment]
That's fine by me. Thanks @charlierudolph
