### ISSUE TITLE
Node Example - CustomWorld returns undefined 

### ISSUE THREAD

**Issue by sarajayyy** [cucumber/cucumber-js#754]
I'm using the sample code from the [ NodeJS example ](https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md)

Similar to Error #668 in nodejs example, I receive a `TypeError: Cannot read property 'get' of undefined`. I've tried console.log `this` and `this.driver`, in my steps file and `this` returns an empty object.  

I found a similar issues posted in [Gitter](https://gitter.im/cucumber/cucumber-js), however it was never reported how it was resolved. 

Node - v6.9.2
"devDependencies": {
    "chromedriver": "^2.27.2",
    "cucumber": "^2.0.0-rc.7",
    "selenium-webdriver": "^3.0.1",
}

Help please!

**Comment by charlierudolph** [comment]
I just ran it locally and it passed for me. Please double check the instructions. Is there any more information can you give?

**Comment by ronniemara** [comment]
Im using babel I get this error:
`Step: After
   Step Definition: features/support/hooks.js:4
   Message:
     TypeError: Cannot read property 'driver' of undefined
         at CustomWorld.<anonymous>` even though when I debug I see the value of this = CustomWorld and this.driver = thenableWebDriverProxy
features/support/hooks.js
```js 
import {defineSupportCode} from 'cucumber';

export  default defineSupportCode(
    ({After}) =>After(() => {
        "use strict";
        debugger;
        this.driver.quit()
            .then(() => console.log('quit'))
    })
);
```
features/support/world.js
```js 
import  'chromedriver';
import seleniumWebdriver from 'selenium-webdriver';
import {defineSupportCode} from 'cucumber';

function CustomWorld() {
    this.driver = new seleniumWebdriver.Builder()
        .forBrowser('chrome')
        .build();
}

export default defineSupportCode(({setWorldConstructor}) => {setWorldConstructor(CustomWorld)});
```

**Comment by charlierudolph** [comment]
@ronniemara you don't need to export the return value or `defineSupportCode`. You just need to call it.


Arrow functions cannot be used for hooks / step definitions because they will be called with the `this` argument as the world instance and if the function is bound then that is ignored.
```js
default defineSupportCode(({After}) =>
   After(() => { // You cannot use an arrow function here
        "use strict";
        debugger;
        this.driver.quit()
            .then(() => console.log('quit'))
    })
);
```

**Comment by ronniemara** [comment]
@charlierudolph ok got it, this is not bound in arrow functions. Thanks!!!

**Comment by charlierudolph** [comment]
@ronniemara Sorry but I'm not clear on whether or not using non-arrow functions solved your issue. Can you please clarify?

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if necessary
