### ISSUE TITLE
Given and Then are ambiguous 

### ISSUE THREAD

**Issue by piotrkochan** [cucumber/cucumber-js#756]
I've similar Then and Given definitions and I'm getting ambiguous error. It is ok?
Morover there is no difference between Then and Given, I can define Then(..) and use it as Given in the feature.

```
let {defineSupportCode} = require('cucumber')

defineSupportCode(function ({Given}) {
  Given(..., function(data, callback) {
```

**Comment by piotrkochan** [comment]
Even in the example: http://cucumber.github.io/cucumber-js/

I just could change:
```
  Given(/^a variable set to (\d+)$/, function(number) {
    this.setTo(number);
  });
```

To:
```
  Then(/^a variable set to (\d+)$/, function(number) {
    this.setTo(number);
  });
```

And result is the same..

**Comment by leipert** [comment]
Yes this is wanted:
https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#definestepoptions-pattern-fn

**Comment by charlierudolph** [comment]
Yes this is intended. Its common across the cucumber projects
