### ISSUE TITLE
Setup on windows is not easy and not working after installing yarn

### ISSUE THREAD

**Issue by inspiraller** [cucumber/cucumber-js#757]
**prerequisites:**
windows 10, nvm installed node@6.9.5

**steps:**
1) $ cd c:\projects\me\
2) $ git clone https://github.com/cucumber/cucumber-js.git
3) $ cd cucumber-js
4) $ npm install
5) $ npm test
error - needs yarn
6) install chocolatey
Right click - open cmd as administrator
run this code
$ @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

success

7) npm install yarn -g
8) npm test

**error - 354 errors....**

one looks like this:

PERM: operation not permitted, symlink 'c:\projects\me\cucumber-js\.babelrc' -> 'C:\Users\Me\AppData\Local\Temp\tmp-15232Qbohc2FjrLio\.babelrc'

**Comment by charlierudolph** [comment]
We have [appveyor](https://ci.appveyor.com/project/charlierudolph/cucumber-js/history) setup to run the tests on a windows machine and its passing. 

That error is odd as I think the path `c:\projects\me\cucumber-js.babelrc` should be `c:\projects\me\cucumber-js\.babelrc`

**Comment by charlierudolph** [comment]
Closing due to lack of response. Sorry about this but I need someone who works on windows to help. I'll happy to offer what help I can.
