### ISSUE TITLE
Browser example in distro is missing files

### ISSUE THREAD

**Issue by murrah** [cucumber/cucumber-js#758]
Hi. Brand new to cucumber-js. The browser example in the distro seems to be broken. To make it work I needed to:
1. copy the \dist\cucumber.js file to \example
2. copy the \example\ansi-html folder from the online version at http://cucumber.github.io/cucumber-js/

FYI
Murray

**Comment by charlierudolph** [comment]
You can run the browser locally with `node scripts/server.js`. I'll make that more prominent in the contributing doc as it currently only appears in the release process checklist

**Comment by murrah** [comment]
Oh.. ok... yes, I didn't even see that! Thanks!
