### ISSUE TITLE
Suggestion -- "uncaughtExeception" labels on such errors.

### ISSUE THREAD

**Issue by mjhm** [cucumber/cucumber-js#759]
... just to distinguish them from errors generated and caught by steps.

**Comment by charlierudolph** [comment]
A wrinkle in this is that technically assertion errors are uncaught exceptions, since assertion libraries throw error. All we know is that an error was thrown while the step was running. Typically the stack trace will help you realize where the problem occurred but I don't know that labeling it with uncaught exception will give any real benefit

**Comment by mjhm** [comment]
Hmm... From the [code](https://github.com/cucumber/cucumber-js/blob/master/src/user_code_runner.js#L45) it looks like `uncaughtExceptions` are (properly) 
handled separately from the assertions that would trigger the normal `try...catch`, promise rejections, and callback exceptions. 

So wrapping the [`reject`](https://github.com/cucumber/cucumber-js/blob/master/src/user_code_runner.js#L42) function to prepend `"Uncaught Exception: "` to the error message seems doable to me  (as in I could give it a shot).

These `uncaughtException` bugs are nasty. They often happen from an unhandled async corner case in a dependency and they typically have thin, barely helpful stack traces.  Sometimes they're triggered from `Before` and  `After` hooks.  Having a hint that the error occurred outside step's control would indicate to the user (like me) that they (I) shouldn't waste time trying to catch the error in the step, and instead focus on tracking down the dangling async chain.

Also it's possible for a delayed `uncaughtException` to trigger an error in the wrong step. This can be an especially hair pulling situation, when there's no distinction between the source of the exceptions.  (BTW apparently mocha does some magic to tie its delayed uncaught exceptions to the correct test.)

I think trapping and labeling `unhandledRejection` might be too much, since there's a lot of sloppy but working programs that let unhandled rejections go.  So I'm dropping that from issue title.

**Comment by charlierudolph** [comment]
> From the code it looks like uncaughtExceptions are (properly)
handled separately from the assertions that would trigger the normal try...catch, promise rejections, and callback exceptions.

What about code that asynchronously throws an assertion error? (like one that makes a async request and verifies the response is successful). Granted we could also check if it is an `AssertionError` but I don't know how many assertion libraries throw an error of that class.

> These uncaughtException bugs are nasty. They often happen from an unhandled async corner case in a dependency and they typically have thin, barely helpful stack traces.

Yep these suck but I don't know if cucumber can really help track them down. I'm worried about false positives / confusion with labeling these as uncaught exceptions.

**Comment by mjhm** [comment]
Ah!  Right! I pretty much never use the callback interface anymore, so I'm good with throwing the legacy callback interface people under the bus. JK. Yeah this would be potentially confusing.

I know for a fact that chai defines it's own AssertionError class -- so filtering on the error class is surely more trouble than it's worth.

I'm going to close this for now, and probably come back with a concrete example and suggestions later.
