### ISSUE TITLE
After hook is "done" before callback is called

### ISSUE THREAD

**Issue by BorisKozo** [cucumber/cucumber-js#767]
I am using cucumber.js with a Gulp task. I want to process the report once cucumber is finished.
I have an After hook which takes a screenshot for each scenario and does other async operations. As far as I can tell from the examples the "After" hook takes a callback and is considered finished once I call the callback (like numerous other libraries e.g. Express middleware).

For example if I add the following hook (which simulates a long async operation):
````
 this.After((scenario, callback) => {
        setTimeout(() => {
            callback();
        }, 10000);
    });
````
Then the cucumber task returns even before the callback is called.

I tried using the Promises API but get the same result, my gulp task exits before all the "After" hooks are finished.

What can I do to make the After hooks to wait for all the callbacks to be called and only then move on?

**Comment by charlierudolph** [comment]
The async API of hooks are well tested, so I'm not sure whats going on. Can you please give a complete, but minimal, reproducible example?

**Comment by BorisKozo** [comment]
Thank you for taking a look at this.
I created a small repository which reproduces the issue:

https://github.com/BorisKozo/cucumber-test

It calls cucumber through gulp-cucumber but if you look at the code there (very short), it only delegates to cucumber and doesn't do anything special. I wanted to make it as close as possible to my use case.

**Comment by charlierudolph** [comment]
That rexample gave me the output:
```
Feature: test

  Scenario: do something that fails
  ✖ When this will fail

Failures:

1) Scenario: do something that fails - features/test.feature:2
   Step: When this will fail - features/test.feature:3
   Step Definition: steps/steps.js:3
   Message:
     Error

2) Scenario: do something that fails - features/test.feature:2
   Step: After 
   Step Definition: steps/hooks.js:4
   Message:
     function timed out after 5000 milliseconds

1 scenario (1 failed)
1 step (1 failed)
0m05.002s
```
The After hook timed out, which is expected. See the [docs](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md)

**Comment by BorisKozo** [comment]
Thanks, that solved my issue.
I added large timeout to the step and now the order seems ok.

````
 this.After({timeout:30000},function (scenario, callback) {
        setTimeout(() => {
            console.log('After hook is done');
            callback();
        }, 10000);
    });
````

For some reason {timeout:-1} didn't work.

Thanks again.

**Comment by charlierudolph** [comment]
gulp-cucumber is using cucumber 1, whereas the current docs are for the cucumber 2 release candidates.
