### ISSUE TITLE
Interface changes for support code

### ISSUE THREAD

**Issue by nicojs** [cucumber/cucumber-js#770]
I'm very happy with the interface changes done using issue #679 However, i still think its a little verbose and there is some room for improvement. I want to improve on that further. 

Right now, a step definition file looks like this:

```javascript
const {defineSupportCode} = require('cucumber');
defineSupportCode(({ Given, When, Then }) => {
    
    Given('something', function () {
         this.page = new SomethingPageObject();
    });

    Than('something should exit', function () {
         if(!this.page) {
              throw new Error('Something isn\'t there');
         }
    });
});
```

The way i see it, there are 2 things that could be better.

1. First there is some very specific boilerplate code needed with the `defineSupportCode`. This is illustrated best with the `({ Given, When, Then })` part. Its an eye sore. I understand you're using [parameter context matching](http://es6-features.org/#ParameterContextMatching) here, but it's not that well known as an ES feature.

2. Second, there is the `this` redirection for the world object. If i write my code examples with arrow functions instead of using the `function` keyword, bad things could happen because I'm leaking state. But this particular test will still succeed. This can be very confusing.

The first issue could be solved by requiring `Given`, `When` and `Then` directly form `'cucumber'`. Is there a reason for the `defineSupportCode` construct?

The second issue is a little bit harder to solve without much clutter. But i still would like to improve the api. Any thoughts on this?

Background: I give automated testing courses to testers and i see they have a some trouble understanding concepts like `this` redirection and functional programming. I would like to improve their lives with the 2.0 api.

**Comment by charlierudolph** [comment]
@nicojs sorry for the delayed response

> Is there a reason for the defineSupportCode construct?

This was an easy transition from the original 1.0 interface as it dealt with functions and just moved the functions from this to the first argument. I cared most about stopping the library from calling all exported functions.

> The first issue could be solved by requiring Given, When and Then directly form 'cucumber'

I'm okay with this if you'd like to take a stab. I believe the easiest way this could be implemented while retaining the current interface as well is

```js
const {Given} = require('cucumber');

Given(...)

// is basically syntactic sugar for

defineSupportCode(({Given}) => {
  Given(...)
})
```

> The second issue is a little bit harder to solve without much clutter. But i still would like to improve the api. Any thoughts on this?

See #745

**Comment by nicojs** [comment]
I've created a WIP PR, lets talk about it there #828 

> See #745

Thanks! Lets talk about it there.
