### ISSUE TITLE
World object is not the same in hooks and step-defs

### ISSUE THREAD

**Issue by cuongluu8** [cucumber/cucumber-js#771]
I'm trying to set a property on `this` (world) within a Before hook and using it in my step def.  However, after setting the property in the before hook, it doesn't seem to be available in the step def.
The world object does seem to be persisted across step defs though.

**Comment by charlierudolph** [comment]
Can you please provide a minimal but reproducible example?

**Comment by cuongluu8** [comment]
If you `console.log(this)` in a Before hook you can see it's NOT the world object.
With a little googling this issue has been raised before and was dismissed as a "won't-fix" I think as it would cause too many problems.
However it would be worth updating the README to outline this, as it clearly states the world object is exposed in the hooks and steps.

**Comment by charlierudolph** [comment]
What "hook" are using? `Before / After`, the only thing I think should be referred to as hooks, should have the world object, while event handlers added with `registerHandler` do not

**Comment by cuongluu8** [comment]
```
this.Before((scenario, callback) => {
    console.log('before hook', this);
});
```
will produce
```
before hook { Before: [Function],
  After: [Function],
  Given: [Function: defineStep],
  When: [Function: defineStep],
  Then: [Function: defineStep],
  defineStep: [Function: defineStep],
  registerListener: [Function: registerListener],
  registerHandler: [Function: registerHandler],
  setDefaultTimeout: [Function: setDefaultTimeout],
  World: [Function: World],
  BeforeFeatures: [Function],
  AfterFeatures: [Function],
  FeaturesResult: [Function],
  BeforeFeature: [Function],
  AfterFeature: [Function],
  BeforeScenario: [Function],
  AfterScenario: [Function],
  ScenarioResult: [Function],
  BeforeStep: [Function],
  AfterStep: [Function],
  StepResult: [Function],
  url: '/creditclub/login' }
```

which is not the world object.

**Comment by charlierudolph** [comment]
You cannot use arrow functions. That retains the current `this` of where the function is defined and prevents the ability of injecting a custom this argument. I don't believe there is anything we can do to support this

**Comment by cuongluu8** [comment]
Of course - missed that!  Perhaps this can be added to the docs?!  But thanks for clearing that up
