### ISSUE TITLE
Multiple scenarios that needs different worlds are not 

### ISSUE THREAD

**Issue by immccc** [cucumber/cucumber-js#772]
Hi,

I am facing problems when using multiple worlds in a system where are multiple scenarios.

Imagine a situation like 

`module.exports = function() {
    this.World = require('route/to/world/1/world1.js').world();

    this.Given("something given of scenario 1", function() {});
    this.When("something when of scenario 1", function() {
        console.log('THIS IS ', this);
        console.log(this.propertyOfWorld1.length);
    });
    this.Then("something then of scenario 1", function() {});

}`

`module.exports = function() {
    this.World = require('route/to/world/2/world2.js').world();

    this.Given("something given of scenario 2", function() {});
    this.When("something when of scenario 2", function() {
                console.log(this.propertyOfWorld2.length);
    });
    this.Then("something then of scenario 2", function() {});

}`

Tests are run with protractor (and as you can see, Webpack) and the log message "THIS IS" outputs the world of scenario 2, even when only scenario 1 is executed. Hence, this.propertyOfWorld1 is undefined and accessing length will throw an exception

Is there a way to isolate world in scenarios? Thanks in advance!

**Comment by charlierudolph** [comment]
There is not a way to currently accomplish this. The world constructor is shared between all scenarios.
