### ISSUE TITLE
How to use Cucumber Expressions

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber-js#773]
From what I can tell, you guys have added support for Cucumber Expressions. The question is, how do I use them? 

I've looked at the docs for them, which - while helpful - did not tell me what I needed to do to be able to add new Cucumber Expressions.

Can anyone shed some light on this?

**Comment by KyleFairns** [comment]
Figured out how to use them.

`When('I search for {searchTerm:stringInDoubleQuotes}', function (searchTerm) {` as an example.

Just 2 questions:

1. How can I add new "Transforms"?

 2. `When('I search for {searchTerm: stringInDoubleQuotes}', function (searchTerm) {` 
 Returns the error:  `No transform for type name " stringInDoubleQuotes".`
Surely you could do a `trim()` on the string that comes back to allow for a space here - it will add greatly to the readablilty.

**Comment by floribon** [comment]
@KyleFairns have a look at the doc about `addTransform`: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#addtransformcapturegroupregexps-typename-transformer

**Comment by KyleFairns** [comment]
Cheers, big help.

Tested with this, and it worked:

```
defineSupportCode(function({addTransform}){

    addTransform({
        captureGroupRegexps: ['\\d+(?:|\\.\\d{2})'],
        transformer: JSON.parse,
        typeName: 'money'
    });
});
```
