### ISSUE TITLE
Specify tags set per feature file 

### ISSUE THREAD

**Issue by DmitroPustovit** [cucumber/cucumber-js#776]
Hello 

I faced problem when I have feature in dependency and for each feature i should specify own  set of tags. 

I use nigthwatchJS with CucumberJS and I pass to cucumber next set of arguments : 

`  
 '--require', 'src/setupEnv.js',
        '--require', 'features/step_definitions',
        '--format', 'pretty',
        '--format', 'json:results/reports/cucumber.json',
        'features/generation',
        '--tags', '(@Both or @User) and not @Admin'
`

It's possible to run several feature and for each of them specify tags ? Smth like this : 
` 
  '--require', 'src/setupEnv.js',
        '--require', 'features/step_definitions',
        '--format', 'pretty',
        '--format', 'json:results/reports/cucumber.json',
        'features/generation',
        '--tags', '(@Both or @User) and not @Admin',
        'features/generation',
        '--tags', '(@Both or @Admin) and not @User'
`

Expectation what cucumber run all features twice - first time for `(@Both or @User) and not @Admin ` and second one for `(@Both or @Admin) and not @User`

Thanks,

**Comment by charlierudolph** [comment]
No that is not currently possible. You can run cucumber multiple times if you need to specify different tags.
