### ISSUE TITLE
Error: ansiHTML is not a function

### ISSUE THREAD

**Issue by MrBokeh** [cucumber/cucumber-js#777]
Hi there, I have received the following error when I try to run the example with 2.0 rc7:
VError: a handler errored, process exiting: PrettyFormatter::handleBeforeFeature: ansiHTML is not a function

**Comment by charlierudolph** [comment]
Did you also get an error in the browser about being unable to load the "ansi-html/index.js"? If so you need to install node modules first. Please see the `CONTRIBUTING.md`

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed
