### ISSUE TITLE
Extended World

### ISSUE THREAD

**Issue by manu7691** [cucumber/cucumber-js#778]
is it possible to extend default world with new functions on Cucumber2-JS? 

Or create a new one, without losing attach/parameters?

**Comment by charlierudolph** [comment]
Please see the [API reference](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#setworldconstructorconstructor). You can retain the attach / parameters by adding the same logic to your custom constructor.

**Comment by manu7691** [comment]
Thank you for your answer.

I realised cucumber types weren't set to consider this situation (Custom world with default world parameters), so I created a PR in order to solve it https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15066
