### ISSUE TITLE
[Question] Why the changes? 

### ISSUE THREAD

**Issue by NHKK** [cucumber/cucumber-js#779]
Hi I'm new to testing in general. I have been tinkering around with 0.9.1 cucumberjs. There's so many changes between 0.9.# and 2.0.#. Could someone please tell me what's the differences between these two versions beside bug fixes? Are there any new features that are available here that wasn't avaliable in 0.9.? I know you guys added the custom formatter but didn't provide any docs on how to implement the custom formatter or even call to the custom formatter.

**Comment by charlierudolph** [comment]
Please see the CHANGELOG.md

**Comment by charlierudolph** [comment]
And there is a link to the custom formatter documentation on the README

**Comment by NHKK** [comment]
thanks
