### ISSUE TITLE
Non Capture Group Transform

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber-js#784]
### The Need:

There are many cases in our step definitions where we have a varity of repeated groups that don't change the steps functionality, but does do quite a bit for readablilty in the feature files:

* "must"/"should"
* optional words like "the", "I" etc that would match `Given I fill in "Foo"` & `And fill in "Bar"`
* lists of interchangable words

### How I would implement it

Perhaps square brackets could be used for things that don't need to be captured, but still require the transformation, which would save time in having to re-write your captures for non-capture functionality.

```
Given('[pronoun] ha(ve|s) {int} child(|ren)', (children) => {
// Code
})
```
Could match

```gherkin
 Given I have 3 children
 Given he has 4 children
 Given she has 1 child
```

For simplification purposes, I think this would be great, as if you needed to add something to the non-capture transform (in the use-case above, adding "they", or "Jeff"), this could then be used across the board without having to edit all the step definitions that would use this transform.

What are your thoughts on both usefulness, and ease of actually making this a possibility?

**Comment by aslakhellesoy** [comment]
Hi @KyleFairns 

Cucumber Expressions 3.0.0 added support for [alternative text](https://docs.cucumber.io/cucumber-expressions/#alternative-text). Your example would be expressed as follows:

```javascript
Given('I/he/she/they have/has {int} child(ren)', (childCount) => {
  // Code
})
```

This was added in #764, which was merged yesterday and will be in the next release.

**Comment by KyleFairns** [comment]
Honestly that is pretty cool, and does add another dimension to the readability side of the framework (which has been my main focus while using cucumber-js).

But my point was not just about alternative text, it was about sharing the alternative text between step definitions for scalability purposes.

Say you have 30 steps that all share the same alternative text.

I was thinking that these alternative steps could be placed in some sort of non-capture transform that could then be used in these 30 steps to mean that, when it comes round to adding more alternatives (always a possibility), then instead of going through all 30 steps and adding the new alternatives, you could just change it in one place.

```javascript
Given('[pronoun] have/has {int} child(ren)', (childCount) => {
   // Code
});

When('[pronoun] picks up {stringInDoubleQuotes} from {stringInDoubleQuotes}', (child, place) => {
   // Code
});

Then('[pronoun] should have {int} child(ren) in [pronoun] care', (childCount) => {
  // Code
});
```
As an example on how it would change (with the Cucumber Expressions v3 features added)

As we write our steps in more of a declarative style: `Given I fill out the <formName> form` instead of `Given I fill "input[name='foo']" with "Bar"`, having a way of quickly editing across steps would be a wonderful addition, knowing that we could use this functionality, as could many others using the framework.

**Comment by aslakhellesoy** [comment]
Oh I see!

Well, you could do this:

```javascript
Given('{pronoun} have/has {int} child(ren)', (_, childCount) => {
   // Code
});
```

The only issue with that would be that you have a `_` that isn't used, and if you have multiple ones, you may have to call the 2nd something else. And then there are linters that don't like unused variables.

So yes, it's an interesting idea. Could you please add a ticket over at [cucumber/cucumber](https://github.com/cucumber/cucumber) and tag it with `cucumber-expressions`? Bonus points if you send a pull request.

And please add a link back to this issue so we have the full discussion history.

Thanks!
Aslak

**Comment by KyleFairns** [comment]
I've documented the issue [here](https://github.com/cucumber/cucumber/issues/131) on the cucumber repo, as requested.

I'll see what I can do on the pull request. I'll put on my scuba kit and go diving into the code during the next week or so.
