### ISSUE TITLE
Using Cucumber CLI programatically

### ISSUE THREAD

**Issue by jan-molak** [cucumber/cucumber-js#786]
Hey guys!

As part of my effort to make [Serenity/JS](http://serenity-js.org) play nice with Cucumber 2.0 (jan-molak/serenity-js#28) I'd like to invoke the Cucumber CLI programmatically from a Mocha test to avoid having to spawn a new process (which is over 20 times slower).

I appreciate that this use case is not fully compatible with the design goals of the CLI, but I think it shouldn't be difficult to make it work, not to mention that it would make my life much easier ;-). 

---

The (simplified) structure of the code looks more or less like this:

```typescript

import { clearSupportCodeFns } from 'cucumber';
const Cucumber = require('cucumber');

describe('When working with Cucumber 2.0', () => {
  afterEach(() => {
    clearSupportCodeFns();
    clearRequireCache();
  });

  it('should notify Serenity/JS of the scenario result', () => {
    const result = new Cucumber.Cli({ /* params */ }).run();

    // other assertions

    return expect(result).to.eventually.be.fulfilled;
  });

  it('should notify Serenity/JS of explicitly pending steps', () => {
    const result = new Cucumber.Cli({ /* params */ }).run();

    // other assertions

    return expect(result).to.eventually.be.fulfilled;    
  });

});

function clearRequireCache() {
  Object.keys(require.cache).forEach(key => delete require.cache[key])
}
```

As the CLI loads listeners, event handlers and step definitions, I'm invoking the `clearSupportCodeFns()` after each scenario to get rid of the support code loaded for that scenario. I'm also invoking the `clearRequireCache()` to remove the step definitions from the node require cache, so that the `defineSupportCode` function gets called again when the step defs file is loaded.

I _think_ (?) that this should be enough to clean up any side effects, but I'm observing a weird behaviour where:
- each scenario passes independently, but when running together only the first one does (indicating some leftover state)
- the error that's thrown by each of the remaining scenarios complains about `stacktrace-js` not being able to figure out the full stack trace in [`getDefinitionLineAndUri`](https://github.com/cucumber/cucumber-js/blob/37a20144176485f74a0fe922763b0018a114e810/src/support_code_library/helpers.js#L49). This is because the stack trace attached to the [artificially generated error](https://github.com/stacktracejs/stacktrace.js/blob/508ee216677e8dd2ebb7fd25352032f5b1667cf8/stacktrace.js#L90) only contains frames related to `stacktrace-js` itself, which then get [filtered out](https://github.com/stacktracejs/stacktrace.js/blob/5916c118be0c549f5b46dc0d26a30c7516ae2f6a/stacktrace.js#L92), leaving the list empty.

Because Cucumber receives an empty list, the `getDefinitionLineAndUri` function's [optimistic assumption](https://github.com/cucumber/cucumber-js/blob/37a20144176485f74a0fe922763b0018a114e810/src/support_code_library/helpers.js#L49) about the list containing at least one element fails.

This is manifested by the following error:

```
TypeError: Cannot read property 'getLineNumber' of undefined
      at getDefinitionLineAndUri (node_modules/cucumber/lib/support_code_library/helpers.js:98:24)
      at node_modules/cucumber/lib/support_code_library/helpers.js:113:34
      at src/notifier.ts:1:12564
      at node_modules/cucumber/lib/support_code_library/builder.js:82:12
      at Array.forEach (native)
      at Object.build (node_modules/cucumber/lib/support_code_library/builder.js:81:7)
      at Cli.getSupportCodeLibrary (node_modules/cucumber/lib/cli/index.js:142:32)
      at Cli.<anonymous> (node_modules/cucumber/lib/cli/index.js:149:39)
      at next (native)
      at undefined.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

----

I think the issue could be resolved by either:
1. making the `getDefinitionLineAndUri` slightly more defensive, so that it checks if the stack trace contains any frames
2. replacing the call to `stacktrace.getSync()` with `stacktrace.get()`, which provides a more sophisticated implementation which _I think_ should tackle the problem and also provide support for source maps. This however would have to be done at the expense of making the function call `async`.

I suppose the first option should be good enough (?) and easy to implement, but I'm not sure what should be the sensible defaults provided in the absence of the stack trace?

I see that it's fine for the `uri` to be set to [`unknown`](https://github.com/cucumber/cucumber-js/blob/37a20144176485f74a0fe922763b0018a114e810/src/support_code_library/helpers.js#L52) for example.

----

If my thinking makes sense and I didn't miss any official way of cleaning up the cucumber state, I'd be happy to submit a PR implementing the first of the suggested solutions.

Thoughts?

All the best,
Jan

**Comment by jbpros** [comment]
Hey Jan,

I'm glad you're doing this! Serenity is great!

I think you shouldn't use the CLI at all in your tests but rather [invoke the Runtime directly](https://github.com/cucumber/cucumber-js/blob/master/src/cli/index.js#L59).

Could you try it and report back if anything goes wrong again or am I missing some context that prevents your from doing that?

**Comment by jan-molak** [comment]
Hey @jbpros, thanks, the Runtime looks like a better alternative. It seems like I'd need to [invoke the `scenarioFilter` myself](https://github.com/cucumber/cucumber-js/blob/master/src/cli/index.js#L50-L52) and pass the filtered feature set on to the Runtime, but it seems doable.
I like the idea of being in control of the process output too, thanks for the hint :-)

I'll look into using the Runtime over the next couple of evenings. My gut feeling is though that this `stacktrace.getSync()` issue will come to bite me regardless...

Would you or @charlierudolph be able to see if my suggestion around defensive coding could work?

**Comment by charlierudolph** [comment]
I'm good with more defensive programming and/or trying to use the async version of stacktrace. Thoughts on first trying out the async version of stacktrace and then add the defensive programming only if needed after that?

**Comment by jan-molak** [comment]
I think this approach makes sense, according to [the manual](https://github.com/stacktracejs/stacktrace.js/#you-can-also-get-a-stack-trace-synchronously):

> HEADS UP: This method does not resolve source maps or guess anonymous function names.

Which is what _might_ be causing the problem...

In the meantime, I'll play around with using the Runtime directly as per @jbpros's suggestion

Thanks!

**Comment by charlierudolph** [comment]
@jan-molak any update here?

**Comment by jan-molak** [comment]
Hey @charlierudolph, I ended up [using the CLI directly](https://github.com/jan-molak/serenity-js/blob/master/packages/cucumber-2/src/cucumber_adapter.ts#L22). Should be ready for the community to use shortly.

**Comment by charlierudolph** [comment]
Okay. Can this issue be closed or is there more to be discussed?

**Comment by DavidGDD** [comment]
Hi guys! I've exactly the same problem as @jan-molak .

I was running my Node project programmatically with the Cucumber1 CLI and it always worked pretty well. Now, i'm trying to migrate to Cucumber2 and using the same code (adapting it to the new implementation) and it brokes at unit testing.

```
TypeError: Cannot read property 'getLineNumber' of undefined
    at getDefinitionLineAndUri (/node_modules/cucumber/lib/support_code_library/helpers.js:98:24)
    at Object.<anonymous> (/node_modules/cucumber/lib/support_code_library/helpers.js:81:34)
    at /node_modules/cucumber/lib/index.js:176:39
    at /node_modules/cucumber/lib/support_code_library/builder.js:77:12
    at Array.forEach (native)
    at Object.build (/node_modules/cucumber/lib/support_code_library/builder.js:76:7)
    at Cli.getSupportCodeLibrary (/node_modules/cucumber/lib/cli/index.js:137:32)
    at Cli.<anonymous> (/node_modules/cucumber/lib/cli/index.js:144:39)
    at next (native)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```
I'm doing something like this:

```javascript
const
	cucumberInfo = {
		argv: this.pluginArgs,
		cwd: process.cwd(),
		stdout: process.stdout
	},
	cucumberCli = new cucumber.Cli(cucumberInfo);

return cucumberCli.run()
	.then((succeeded) => {
                ...
	}).catch((error) => {
		...
	});
```
@jan-molak have you solved the problem running with the CLI?
if i use the Runtime as @jbpros suggested, Will the problem be avoided?

**Comment by jan-molak** [comment]
@DavidGDD - yeah, CLI seems to be working fine for me - [example here](https://github.com/jan-molak/serenity-js/blob/master/packages/cucumber-2/src/cucumber_adapter.ts#L22)

**Comment by DavidGDD** [comment]
But @jan-molak, what have you change from your first version to your last version to solve the problem? I read your solution before writing but i don't see the difference... or is it in the unit test?

**Comment by jan-molak** [comment]
I haven't changed anything between those two versions; My question was related to using Runtime class instead of the CLI; Runtime seemed cleaner but it had too many dependencies to get it to run so I settled on using the CLI class instead. Also, in my tests I'm starting a new cucumber process per test, so that might be what makes the difference.

**Comment by yaronassa** [comment]
Cucumber V1 API differs from V2.
You can't use CLI as a function anymore, you need to create a new CLI object, and pass an option argument to the constructor.

**V1**
```javascript
//CLI would just receive an array of argument
let cli = require('cucumber').Cli(runArgs); 

//CLI.run received a callback function
return new Promise(function (resolve) {
     return cli.run(function(result){
         let exitCode = (result === true) ? 0 : 1;
         return resolve(exitCode);
     });
```

**V2** 
```javascript
//CLI *Constructor* requires an options object with argv, cwd and stdout
let cli = new (require('cucumber').Cli)({argv: runArgs, cwd: process.cwd(), stdout: process.stdout});

//CLI.run returns a promise
return new Promise(function (resolve, reject) {
     try {
         return cli.run()
             .then(success => resolve((success === true) ? 0 : 1));
     } catch (e) {
         return reject(e);
     }
```

**Comment by DavidGDD** [comment]
@jan-molak one process per test it's the cleanest workaround to the issue reported by you. With the new version it's hard to run multiple Cucumber executions in the same process due to the Node require cache.

**Comment by DavidGDD** [comment]
@yaronassa i'm running cucumber as you propose without the try/catch block and the new Promise, because chaining a catch to the promises, a throw error will be managed.

**Comment by yaronassa** [comment]
@DavidGDD Yeah, there was an issue with unhandled rejections in BeforeFeatures that needed the try/catch (#792).
It's no longer an issue, but I never removed the wrapper. My bad for including it in the example.

**Comment by jan-molak** [comment]
@DavidGDD - Agreed, I'd much rather run several Cucumber executions per Node process as that would greatly speed up my integration tests. To be fair though, this use case might be slightly incompatible with Cucumber's design goal - 1 execution per process.

**Comment by DavidGDD** [comment]
Reading the features testing implementation, in the [World](https://github.com/cucumber/cucumber-js/blob/master/features/support/world.js) i see the test are running using the CLI programmatically as @jan-molak and me are trying. 

Executing the Cucumber features tests and logging the Stacktrace content, it always has traces, so never appears the problem with the stacktrace empty:
```
yarn run v0.27.5
$ yarn run lint-code && yarn run lint-dependencies
Done in 11.28s.
yarn run v0.27.5
$ mocha src


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․>>>>>>>> Stackframes:  [ { columnNumber: 34,
    lineNumber: 86,
    fileName: '/Users/digi/myStuff/gitHub/cucumber-js/src/support_code_library/helpers.js',
    functionName: 'getDefinitionLineAndUri',
    source: '    at getDefinitionLineAndUri (/Users/digi/myStuff/gitHub/cucumber-js/src/support_code_library/helpers.js:86:34)' },
  { columnNumber: 27,
    lineNumber: 22,
    fileName: '/Users/digi/myStuff/gitHub/cucumber-js/src/support_code_library/helpers.js',
    source: '    at /Users/digi/myStuff/gitHub/cucumber-js/src/support_code_library/helpers.js:22:27' },
...
```

In tests, the cucumber execution is running always with the ```--backtrace``` option enabled. Doing that in my case, the stackframes returned by Stacktracejs in stacktrace.getSync() is never empty and avoids the problem.

```javascript
const
	cucumberInfo = {
		argv: this.pluginArgs.concat(['--backtrace']),
		cwd: process.cwd(),
		stdout: process.stdout
	},
	cucumberCli = new cucumber.Cli(cucumberInfo);

return cucumberCli.run()
	.then((succeeded) => {
                ...
	}).catch((error) => {
		...
	});
```

**Comment by binarymist** [comment]
How are we clearing the cucumber state. First test run passes:
```
4 scenarios (4 passed)
12 steps (12 passed)
```
Second always fails with:

```
UUUUUUUUUUUU

Warnings:
```

```
4 scenarios (4 undefined)
12 steps (12 undefined)

```

**Comment by binarymist** [comment]
What exactly is the support code library @RalphSleighC4 ? I'm about to move to the next stage which at this stage is spinning up a container for each cucumber instance, as I need them running in parallel. Is what you're suggesting able to be run in parallel? Also how do you use what you're suggesting, is your code snippet a module that can be consumed and run many times via `run` sequentually and in parallel?

**Comment by RalphSleighC4** [comment]
It's the code for the step definitions and hooks cucumber uses to run your scenarios in the files you specify using the --require argument. If we write them in the typical style:

```
const { Given, When, Then } = require('cucumber')

Given('I sleep for 10 seconds', function () {
  return promise = new Promise((resolve, reject) => {
    setTimeout(resolve, 1*1000);
  })
});
```

Then the first time cucumber requires them, the Given function is executed, but subsequent calls to require will return a cached version of the files module.exports, so the steps are not recreated and the run fails as undefined. Hence the need to cache the support library from the first run if you want to use the ClI more than once.

This only applies to sequential runs inside the same process. If you are using containers to run tests in parallel you won't have this issue.

**Comment by binarymist** [comment]
Thanks @RalphSleighC4, I'm comming back to this soon, I'll have a play when I get there and provide my feedback.

**Comment by binarymist** [comment]
This doesn't work for my case. I use the same step definitions and hooks, but with different data applied.

**Comment by binarymist** [comment]
For anyone arriving here in the future looking for help:
I now have cucumber cli working in parallel. This works with different data applied to my steps, etc.

[runCuc.js](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/blob/d8191f6634e8c05a1011fadb3947ea06cc90befe/src/scripts/runCuc.js) wraps and modifies slightly the cli [run.js](https://github.com/cucumber/cucumber-js/blob/cfc9b4a1db5b97d95350ce41144ae69084096adc/src/cli/run.js). I need to also modify `stdout` for my application, as I'm logging locally to my parent process and also to a redis channel which ends up pushing messages via server sent events (SSE AKA eventsource) to my cli driving the SaaS.

I created a [bin file](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/blob/d8191f6634e8c05a1011fadb3947ea06cc90befe/bin/purpleteamParallelCucumber) similar to the [cucumber-js](https://github.com/cucumber/cucumber-js/blob/cfc9b4a1db5b97d95350ce41144ae69084096adc/bin/cucumber-js) bin file.

The whole commit is [here](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/commit/d8191f6634e8c05a1011fadb3947ea06cc90befe).

All of the above is run in parallel with my [app.parallel.js](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/blob/d8191f6634e8c05a1011fadb3947ea06cc90befe/src/api/app/models/app.parallel.js)

For testing (as working out what's going wrong with your steps can be tricky in parallel sometimes), I conditionally run in [parallel or sequence](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/blob/d8191f6634e8c05a1011fadb3947ea06cc90befe/src/api/app/models/app.js#L45-46) (sequence only runce one test session for me as noted in my previous comment)

Sequence looks like [this](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/blob/d8191f6634e8c05a1011fadb3947ea06cc90befe/src/api/app/models/app.sequential.js)

Hope this helps someone.
