### ISSUE TITLE
CompositeParserException: Parser Errors doesn't specify which feature file is failing

### ISSUE THREAD

**Issue by venkatteshb** [cucumber/cucumber-js#789]
## Observed:
Please see the error message below, I am getting this error message when trying to cucumber tests.

It doesn't specify which feature file it is failing on. 

```
E/launcher - Error: CompositeParserException: Parser errors:
(6:7): inconsistent cell count within the table
(14:5): inconsistent cell count within the table
path: C:\Users\user3\projects\Integration-Tests\node_modules\gherkin\testdata\bad\inconsistent_cell_count.feature
    at Function.Errors.CompositeParserException.create (C:\Users\user3\projects\Integration-Tests\node_modules\gherkin\lib\gherkin\errors.js:27:13)
    at Parser.parse (C:\Users\user3\projects\Integration-Tests\node_modules\gherkin\lib\gherkin\parser.js:79:45)
    at C:\Users\user3\projects\Integration-Tests\node_modules\cucumber\lib\cucumber\parser.js:18:36
    at Array.forEach (native)
    at Object.parse (C:\Users\user3\projects\Integration-Tests\node_modules\cucumber\lib\cucumber\parser.js:12:22)
    at Object.getFeatures (C:\Users\user3\projects\Integration-Tests\node_modules\cucumber\lib\cucumber\runtime.js:39:35)
    at Object.start (C:\Users\user3\projects\Integration-Tests\node_modules\cucumber\lib\cucumber\runtime.js:11:27)
    at Object.run (C:\Users\user3\projects\Integration-Tests\node_modules\cucumber\lib\cucumber\cli.js:75:15)
    at C:\Users\user3\projects\Integration-Tests\node_modules\protractor-cucumber-framework\index.js:31:34
    at Function.promise (C:\Users\user3\projects\Integration-Tests\node_modules\q\q.js:682:9)
```

Was on chat with @aslakhellesoy on gitter chat, where he asked me to raise this issue. 

## Expected:
To mention the failing feature file(s?) in the error log.

**Comment by charlierudolph** [comment]
It appears to mention the feature file on the fourth line
```
C:\Users\user3\projects\Integration-Tests\node_modules\gherkin\testdata\bad\inconsistent_cell_count.feature
```
I don't understand how you would end up executing a `gherkin` feature tests. What command did you run and from what folder?

**Comment by aslakhellesoy** [comment]
Also, the file it is failing on is an intentionally broken .feature file that is part of Gherkin's own test suite to verify that errors are reported as expected. Hence the name `/bad/` in the path.

**Comment by aslakhellesoy** [comment]
Closing this since the path is indeed reported.

**Comment by venkatteshb** [comment]
Sorry about the confusion, 
but to reply to @charlierudolph - I am running the tests from the project folder, underneath is the node_modules folder. It might not all be relevant, but leaving the information here, just in case. 
Think I should also mention that I only started seeing this problem after I deleted 'node_modules' folder and did a 'npm install' .

I am running the tests as 

'npm run e2e -- --cucumberOpts.tags=@tags' 

where e2e is a script in package.json(also underneath project folder) and e2e script reads like this

`"e2e": "protractor ./protractor.conf.js"`


and the content of the package.json below, 

'{
  "name": "web",
  "version": "0.0.0",
  "description": "web project",
  "main": "/",
  "repository": {
    "type": "git",
    "url": "https://tfsurl"
  },
  "scripts": {


    "e2e": "protractor ./protractor.conf.js",
    "postinstall": "webdriver-manager update --chrome",
    "postinstall": "webdriver-manager update --ie"

  },
  "author": "web",
  "license": "UNLICENSED",
  "dependencies": {
    "angular": "~1.6.2",
    "angular-messages": "~1.6.2",
    "angular-ui-bootstrap": "~2.5.0",
    "angular-ui-router": "~1.0.0-rc.1",
    "block-ui": "~2.70.1",
    "bootstrap": "~3.3.7",
    "bootstrap-switch": "~3.3.2",
    "datatables.net-bs": "~2.1.1",
    "font-awesome": "~4.7.0",
    "jquery": "~3.1.1",
    "jquery-slimscroll": "~1.3.8",
    "js-cookie": "~2.1.3",
    "lodash": "~4.17.4",
    "ng-table": "~3.0.1",
    "simple-line-icons": "~2.4.1",
    "chai": "~3.5.0",
    "chai-as-promised": "~6.0.0",
    "clean-webpack-plugin": "~0.1.15",
    "cucumber": "~1.3.1",
    "moment": "^2.14.1",
    "oracledb": "^1.10.1",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "^4.0.0",
    "protractor-cucumber-framework": "^0.6.0",
    "rga-dbhelper": "^1.0.6"
  },
  "devDependencies": {
 
    "chai": "~3.5.0",
    "chai-as-promised": "~6.0.0",
    "clean-webpack-plugin": "~0.1.15",
    "cucumber": "~1.3.1",
	"moment": "^2.14.1",
    "oracledb": "^1.10.1",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "^4.0.0",
    "protractor-cucumber-framework": "^0.6.0",
    "rga-dbhelper": "^1.0.6"
  }
}'

**Comment by charlierudolph** [comment]
> I am running the tests from the project folder

Do you mean `C:\Users\user3\projects\Integration-Tests`?

---

Cucumber-js by looks for feature files in the `features` folder or whatever folders / files are passed to it. I have never used protractor and this is the wrong place to ask protractor specific questions. Typically you want to avoid running any features that exist within the `node_modules` folder and ensuring that is true should prevent this from popping up

**Comment by venkatteshb** [comment]
Thanks Charlie, I was not asking Protractor related questions, but I'll take your suggestion to point to the specific folder where .feature files are located to pass to cucumber.

**Comment by venkatteshb** [comment]
@charlierudolph - an update, it worked with your suggestion. But I am still confused why this problem was not happening earlier. With the same settings it would automatically exclude the example features in the node_modules. But again not asking the question. 
Thanks much for your help.

**Comment by charlierudolph** [comment]
Very odd. Glad you got it working now. You're welcome

**Comment by aslakhellesoy** [comment]
The latest version of Gherkin (4.1.0) bundles its own feature files. Not intentionally, it just didn't occur to me to exclude them.

So it's probably been a latent problem that just surfaced.

**Comment by venkatteshb** [comment]
@aslakhellesoy - That explains it.

**Comment by kogratte** [comment]
That's not true to say that the parsed file is displayed. I juste have the same error, and there is no available information in stacktrace!

**Comment by aslakhellesoy** [comment]
@kogratte please share your stack trace

**Comment by kogratte** [comment]
With pleasure!

     Looking for feature files in C:\.....Web.Tests.E2E
[11:11:03] E/launcher - Error: CompositeParserException: Parser errors:
(6:7): inconsistent cell count within the table
(14:5): inconsistent cell count within the table
    at Function.Errors.CompositeParserException.create (C:\....Web.Tests.E2E\node_modules\gherkin\lib\gherkin\errors.js:27:13)
    at Parser.parse (C:\....Web.Tests.E2E\node_modules\gherkin\lib\gherkin\parser.js:76:45)
    at C:\....Web.Tests.E2E\node_modules\node-gherkin-runner\lib\gherkin-runner.js:21:25
    at Array.forEach (native)
    at Object.loadFeaturesFiles (C:\....Web.Tests.E2E\node_modules\node-gherkin-runner\lib\gherkin-runner.js:18:9)
    at C:\....Web.Tests.E2E\node_modules\node-gherkin-runner\lib\runner.js:9:16
    at Object.<anonymous> (C:\....Web.Tests.E2E\node_modules\node-gherkin-runner\lib\runner.js:11:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[11:11:03] E/launcher - Process exited with error code 100

**Comment by jorman28** [comment]
That happens because some of all the features of the Scenario Outline the Examples table is not complete

for example

Examples:
| user     | password | rememberAccount |
| user01 |

absolutely all pipelines ( | ) must be completed:

Examples:
| user     | password | rememberAccount |
| user01 |                 |                                |
