### ISSUE TITLE
Can't use attach in step definition

### ISSUE THREAD

**Issue by tedkirby** [cucumber/cucumber-js#790]
I get: 
```
this = {}
TypeError: this.attach is not a function
```

I am trying to do https://github.com/cucumber/cucumber-js/blob/master/features/attachments.feature#L110-L124

with `2.0.0-rc.9`

```
Feature: A simple test

Scenario: A simple passing test
    Given Something exists
```
```
'use strict';
const util = require('util');
const {defineSupportCode} = require('cucumber');

defineSupportCode(({Given}) => {

    Given('Something exists', () => {
        console.log(`this = ${util.inspect(this)}`);
        this.attach('Some text');
    });
});
```

**Comment by tedkirby** [comment]
I also tried adding:

```
function CustomWorld({attach, parameters}) {
    console.log(`this cw arguments = ${util.inspect(arguments)}`);
    this.attach = attach;
    console.log(`this.attach cw = ${util.inspect(this.attach)}`);
    this.parameters = parameters;
    this.attach('Some text init');
    this.howDone = 'init';
    console.log(`this cw = ${util.inspect(this)}`);
}
defineSupportCode(({setWorldConstructor, Given, When, Then}) => {

    setWorldConstructor(CustomWorld);
```
The attach from `function CustomWorld` worked, but failed as before from `Given`, and `this = {}`.

**Comment by charlierudolph** [comment]
You cannot use arrow functions for step definitions. I just added an [FAQ](https://github.com/cucumber/cucumber-js/blob/dfbfed94e2cee4fd6b1f91299f7b450b271f9145/docs/faq.md) doc as this has come up quite often

**Comment by tedkirby** [comment]
Thanks!!  

This works for me:
```
defineSupportCode(function ({Given, When, Then}) {

    Given('Something exists', function () {
        console.log(`this Given = ${util.inspect(this)}`);
        this.attach('Some Given text');
    });
```

"**The world instance isn't available in my hooks or step definitions.**

This has frequently been caused by the use of ES6 arrow functions. You cannot use ES6 arrow functions for step definitions or hooks because they bind this to the current context which prevents the world instance from being injected."
