### ISSUE TITLE
[question] windows running cucumber js

### ISSUE THREAD

**Issue by NHKK** [cucumber/cucumber-js#791]
I tired "./node_modules/.bin/cucumber.js" on windows and I've also tried "./node_modules/.bin/cucumber-js" on windows both of which does NOT WORK!!! However, if you were to add "./node_modules/.bin/cucumber-js" to package.json at scripts:{test: "./node_modules/.bin/cucumber-js"} then it would work when running npm test. Could this be added to the documentation because it was NOT clear.

**Comment by NHKK** [comment]
Oh also when I run the test with just a feature file for some reason cucumber js doesn't correct me any more and on top of this error 
![error](https://cloud.githubusercontent.com/assets/18389319/24098127/5bc107c4-0d3f-11e7-8bce-ea3ee039dbb8.jpg)

**Comment by KyleFairns** [comment]
I'm running on Windows 7.

My input on this is that the actual command you are using is wrong.

The following commands worked absolutely fine for me:
```cmd 
 .\node_modules\.bin\cucumberjs --tags @example
.\node_modules\.bin\cucumber-js --tags @example
.\node_modules\.bin\cucumberjs.cmd --tags @example
.\node_modules\.bin\cucumber-js.cmd --tags @example
node_modules\.bin\cucumberjs --tags @example
node_modules\.bin\cucumber-js --tags @example
node_modules\.bin\cucumberjs.cmd --tags @example
node_modules\.bin\cucumber-js.cmd --tags @example
```
The problem being that the windows terminal/command line does not run javascript.

**Comment by charlierudolph** [comment]
The [cli doc](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#cli) has a note for windows users about using `cucumber.js`. I don't see how running `./node_modules/.bin/cucumber-js` is any different from using a `package.json` script that has the same value. Does windows needs to update the backslash instead of the forwardslash in the relative path (as KyleFairns appears to be using)?

The PrettyFormatter error you mentioned has been resolved in 1.3.2 and 2.0.0-rc.9

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed

**Comment by abarriosh** [comment]
I have problems running cucumber on Windows 7 64bit. I installed cucumber globally and set the variable NODE_PATH. I verify with node -> require('cucumber') and the result confirms that 'cucumber' is setted up OK. But when i execute "cucumber-js" in the command line the following error is present: 

C:\protractor-test>cucumber-js
Error: Cannot find module 'cucumber' from 'C:\protractor-test'
    at C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_modules\r
esolve\lib\async.js:48:31
    at processDirs (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\n
ode_modules\resolve\lib\async.js:182:39)
    at ondir (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_mo
dules\resolve\lib\async.js:197:13)
    at load (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_mod
ules\resolve\lib\async.js:80:43)
    at onex (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_mod
ules\resolve\lib\async.js:105:17)
    at C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_modules\r
esolve\lib\async.js:26:73
    at FSReqWrap.oncomplete (fs.js:123:15)

Any idea? Thanks
