### ISSUE TITLE
defineSupportCode is not a function: Possible Regression of NPM Module to 1.x standards

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber-js#796]
## The Problem ##
When I use the function `defineSupportCode`, an error message appears stating:

`TypeError: defineSupportCode is not a function`

## Background ##
I updated cucumberjs this morning to find that the `defineSupportCode` function had been removed when you do a require on cucumber (using parameter context matching), and I was wondering what the replacement for this is?

Here's how it used to be:
```javascript
const {defineSupportCode} = require('cucumber');

defineSupportCode(({addTransform}) => {
   // Some Transforms Here
});
```

It's currently not in the docs (from what I can see), and it means that both my addTransform functions are not working, and neither are my steps.

What has changed? Is there something I'm missing?

**Comment by floribon** [comment]
@KyleFairns which version of cucumberjs are you using? `defineSupportCode` has bee introduced by `2.0` afaik, so check that you haven't downgraded to the stable `1.x`.

(I confirm it still works fine for me, using `2.0.0-rc.9)`

**Comment by KyleFairns** [comment]
Using npm's "cucumber" module, it's set to "latest", which is coming back as 1.3.2 over there.

However, it was working perfectly fine just yesterday.

**Comment by KyleFairns** [comment]
It does seem as though the npm cucumber module has regressed back to 1.x standards, as I could see the items relating to Cucumber Expressions prior to the update.

If a 2.x release could be made, that would be great.

This will mean that those who are using:

`"cucumber", "^1.3.1"` (or other variants) in their package.json won't be affected by issues relating to the new 2.x standard, but those using "latest" or "^2.0.0" will have access to the new 2.x standard

**Comment by floribon** [comment]
Indeed on npm we can see that the published version is `1.3.2`
https://www.npmjs.com/package/cucumber

I guess the behavior of something like `*` (latest) on package.json has been affected by that.
I'd suggest you fix the major version number in your package.json to force version 1 or 2 and not be subject to breaking changes.

**Comment by charlierudolph** [comment]
1.3.2 is the most recent release as a fix was back-ported to the 1.x line. Please follow @floribon's advice.

**Comment by gforceg** [comment]
Hi. I can't get my old tests to work and my new tests get this same error. How exactly do I install cucumberjs 2.x????
