### ISSUE TITLE
undefined defineSupportCode 

### ISSUE THREAD

**Issue by schoettler** [cucumber/cucumber-js#799]
A couple of days ago, I could use cucumber.defineSupportCode, seems to be returning undefined now, did the API change?

**Comment by charlierudolph** [comment]
What cucumber version are you using? We recently released "1.3.2" in order to backport a bugfix to the 1.0 branch and npm's version of "latest" is most recently published instead of newest version.

**Comment by schoettler** [comment]
Yes, after checking https://github.com/cucumber/cucumber-js/releases noticed this, thanks!
