### ISSUE TITLE
running cukes from -g module works, local module errors on formatLocation 

### ISSUE THREAD

**Issue by s9tpepper** [cucumber/cucumber-js#800]
Running cukes from globally installed cucumberjs works as expected.

Running cukes from locally installed cucumberjs errors when trying to output test results summary.

Example output and project in github repo: https://github.com/s9tpepper/cucumber_example

**Comment by charlierudolph** [comment]
What is your local/global version? We recently released 1.3.2 and 2.0.0-rc.9 to fix that exact issue.

**Comment by s9tpepper** [comment]
Both were 2.0.0-rc7, I just did `npm install cucumber` but got rc7 instead of 9, I'll try again today

**Comment by s9tpepper** [comment]
Awesome, rc9 cleared my issue. Weird that it installed rc7 instead of 9 but whatever, thanks!
