### ISSUE TITLE
defineSupportCode is not a function

### ISSUE THREAD

**Issue by JoeTradeIX** [cucumber/cucumber-js#806]
Running 1.3 on Windows. 

I get this message when I try var {defineSupportCode} = require('cucumber');

I can't see it exported anywhere in the node package.

**Comment by charlierudolph** [comment]
`defineSupportCode` is 2.0 specific. Please see [here](https://github.com/cucumber/cucumber-js/tree/1.x) for `1.x` documentation. I'll add a link tot the readme
