### ISSUE TITLE
VError: a handler errored, process exiting: PrettyFormatter::handleFeaturesResult: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by sugo1980** [cucumber/cucumber-js#809]
I am getting the above error while running the cucumber test in nodejs. I have already gone through this forum and the suggestion was to use gherkin version 4.0.0. But my cucumber's package.json file already has this version, still i am not able to identify what could be the issue. Please let me know your thoughts....

**Comment by charlierudolph** [comment]
We released 1.3.2 and 2.0.0-rc.9 to fix that issue.

**Comment by sugo1980** [comment]
What are all those versions for?  Is that cucumber version to be used in package.json file?  FYI, I am currently using cucumber version 2.0.0-rc.6

**Comment by charlierudolph** [comment]
If you use either of those versions the issue should be fixed. Yes, typically you update your package.json file although a lot of times you don't need to do that by hand as the npm/yarn command does that for you

**Comment by sugo1980** [comment]
Issues are resolved, Thanks for your response :-)
