### ISSUE TITLE
Cannot use "/" in step definition

### ISSUE THREAD

**Issue by yamatoman** [cucumber/cucumber-js#811]
I upgraded rc.6 to rc.9 and one of my steps was reported Undefined. I tried it also on rc.8. The step read "Given UPC, TI/HI and quantity information". When I removed the "/", it worked correctly.

**Comment by charlierudolph** [comment]
In rc.8 we updated a dependency to fix an issue where regexp special character were not properly being escaped. The `/` character is a regexp special character. What is your step definition pattern that worked in rc.6 and what is the suggested step definition pattern in rc.9?

**Comment by yamatoman** [comment]
The step read `Given('UPC, TI/HI and quantity information', function(callback) {` as suggested by Cucumber.
I've changed it to `Given('UPC, TIHI and quantity information', function(callback) {` and it works now. I removed the "/" as a guess.
If it's the expected behavior, I'll just make sure to watch for it in the tests.

**Comment by charlierudolph** [comment]
It appears in `rc.8` the latest update to cucumber-expressions made `/` a special character in cucumber expressions. [Docs](https://docs.cucumber.io/cucumber-expressions/#alternative-text). There currently isn't a nice way to escape it.

**Comment by yamatoman** [comment]
Good enough. I'll make sure I don't use it in my steps. Thanks!
