### ISSUE TITLE
JSON formatter in 2.x dropped 'type' property - by design?

### ISSUE THREAD

**Issue by Litee** [cucumber/cucumber-js#813]
Hi,

I have noticed that JSON files generated in Cucumber 2.0RC9 do not have type:'scenario' property for scenarios - see https://github.com/cucumber/cucumber-js/blob/1.x/lib/cucumber/listener/json_formatter.js#L41 for comparison. It broke report generation tool I use and is not mentioned in breaking changes, so I wonder whether it was intentional?

**Comment by gpichot** [comment]
@Litee We had the same issue on our side. We fixed it with this commit: https://github.com/sutoiku/cucumber-js/commit/b3a7a10f8b1de63f615ac91e739ba5d9907b4091

Our report generator is now properly displaying scenarios statistics.

cc @floribon

**Comment by charlierudolph** [comment]
It was intentional as there is not other type of object that is output by the JSON formatter

**Comment by gpichot** [comment]
@charlierudolph Will these changes (deletion of the type property, change of the duration unit from ns to ms) also be observed for the JSON formatters of the others implementations of cucumber? Or is it specific to cucumber-js?

**Comment by charlierudolph** [comment]
Created cucumber/cucumber#187 to start a discussion about a shared JSON schema that all cucumber implementations could follow. Going to close this for now
