### ISSUE TITLE
Improve documentation about common step definition scoping patterns & 'use strict'

### ISSUE THREAD

**Issue by cbrunnkvist** [cucumber/cucumber-js#814]
As of now, if you happen enable _strict mode_ in a step definitions, nothing seems to work as expected, irrespective of whether or not you declare the `defineSupportCode` callback with a fatarrow or not.

Perhaps it could be a wee bit better explained exactly _what_ is being passed in to the `defineSupportCode` callback and how you may get a good tradeoff between sane amount of boilerplate code and step definition readability.

I also think we should keep in mind that some users might still not be able to use late ES6 features such object destructuring assignment of function parameters and/or will add `'strict mode'` out of habit / editor snippets.

**Comment by charlierudolph** [comment]
Can you please give an example about how strict mode effects things?

---

>  irrespective of whether or not you declare the `defineSupportCode` callback with a fatarrow or not.

Whether or not you use a fat arrow with the `defineSupportCode` callback shouldn't matter. However, you cannot use a fat arrow when defining steps within the defineSupportCode callback. This is documented in the [FAQ](https://github.com/cucumber/cucumber-js/blob/master/docs/faq.md)

---

> Perhaps it could be a wee bit better explained exactly what is being passed in to the `defineSupportCode` callback

That is [documented](https://github.com/cucumber/cucumber-js/blob/v2.0.0-rc.9/docs/support_files/api_reference.md)

---

> how you may get a good tradeoff between sane amount of boilerplate code and step definition readability.

Can you please give some more detail examples about what you mean by this. What about the current API do you think you would like changed?

---

> I also think we should keep in mind that some users might still not be able to use late ES6 features such object destructuring assignment of function parameters

Destructing isn't necessary. You could just do the following
```js
defineSupportCode(function(methods) {
  methods.Given(/*...*/); 
});
```
This isn't far from the 1.x version which used
```js
module.exports = function() {
  this.Given(/*...*/); 
};
```
In 2.0 we only moved the methods from being exposed via `this` of the function to the first argument.

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed
