### ISSUE TITLE
Document lack of arrow function support in step definitions

### ISSUE THREAD

**Issue by artemave** [cucumber/cucumber-js#817]
It's common these days to use es6 arrow functions by default. However, in step definitions they break the concept of `world` being stored in `this`. Which is fair enough, but perhaps this fact deserves a line in a readme to save newcomers some head scratching.

**Comment by charlierudolph** [comment]
Already in the [FAQ](https://github.com/cucumber/cucumber-js/blob/52d0e328729f1f9d2ae05d72426a3377a1aae9cc/docs/faq.md) which is linked to from the README
