### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by johnny-shrewd** [cucumber/cucumber-js#819]
I am creating an end to end testing environment and i want to be able to create HTML reports of the scenarios that I test.

I used the example from gulp-chimp 

but when i run the gulp this gulp command 

```
return chimp({
        features: './features',
        browser: 'phantomjs',
        singleRun: true,
        debug: false,
        output: {
            screenshotsPath: './screenshots',
            jsonOutput: './cucumber.json',
        },
        htmlReport: {
            enable: true,
            jsonFile: './e2e_output/cucumber.json',
            output: './e2e_output/report/cucumber.html',
            reportSuiteAsScenarios: true,
            launchReport: true,
        }
```
`
i am getting :  
```
Cannot read property 'length' of null on the node_modules/chimp/dist/lib/cucumberjs/cucumber.js:101
          if (_this.options.jsonOutput && JSON.parse(jsonResults).length) {
```
Keep in mind that i am just learning how to use this and you can consider me an newbie for asking this but i really don't know how to solve the issue

**Comment by charlierudolph** [comment]
Based on the path in the stack trace: `node_modules/chimp/dist/lib/cucumberjs/cucumber.js` that error is coming from chimp, not cucumber. Please open an issue there.
