### ISSUE TITLE
Error on /event_broadcaster.js:30 since 1.3.3 cucumber version

### ISSUE THREAD

**Issue by camgimenez** [cucumber/cucumber-js#820]
Hi everyone, 
 I'm getting an error on my results of Cucumber circle ci tests since the last version of cucumber (1.3.3) 

```
/home/ubuntu/project/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            process.nextTick(function(){ throw error; }); // prevent swallow by unhandled rejection
```

This is making me have an `exit code 1`while running my tests

```
node ./cucumber --parallel $CIRCLE_NODE_INDEX/$CIRCLE_NODE_TOTAL $CUCUMBER_ARGS returned exit code 1 
```

Any idea what could possibly happening? 

Im using 

```
os.name: 'Linux' os.arch: 'amd64', os.version: '3.13.0-116-generic'
node : 5.12.0
chrome: 58.0.3029.81-1
chrome driver: 2.27-x64-chromedriver
selenium: selenium-server-standalone-2.53.1

```

Thanks in advance!

**Comment by charlierudolph** [comment]
What error is being thrown? That change was added as the comment states to `prevent swallow by unhandled rejection`. I would guess a error was not being reported previously and it is now

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if necessary

**Comment by Nautigsam** [comment]
Hi, I'm having the same issue, here is the whole output I get :
```
/var/jenkins/smc/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            process.nextTick(function(){ throw error; }); // prevent swallow by unhandled rejection
                                         ^
webserver/test/webserver/support/hooks.js:79 function timed out after 35000 milliseconds
```

**Comment by Nautigsam** [comment]
Hi, I got the same error and that was because I was using the wrong display (default X11 instead of Xvfb in my case). I think it was unable to start firefox and that's why it was in timeout.
Then I set `export DISPLAY=:10` and it worked again.
