### ISSUE TITLE
Regex string not a word

### ISSUE THREAD

**Issue by kariasbolster** [cucumber/cucumber-js#822]
Hi,

I have this feature

```
 Scenario: Upload a valid file
		  Given that the user uploads a valid test file
		  Then the user should see an upload success indicator

Scenario: Upload an invalid file
		 Given that the user uploads a file name error test file
		 Then the user should see an upload error message
```

As you can see, both thens are just the same except for the string after upload. I would like to write my then to have a regex after upload. So I wrote my then in this way

```
this.Then(/^that the user uploads [\s\S]+/, ( options ) => {
    console.log( options );
});
```

However the console.log displays [Function: finish]. Is there a way that I can get the string after upload?

I know this is not the right place to ask this but my stackoverflow question yielded no answer and I am quite in a hurry so I need answers ASAP. Please help me.

**Comment by charlierudolph** [comment]
You need to use regular expression capture groups in order to pull anything out of the matched step.
```
/^that the user uploads ([\s\S]+)/

**Comment by kariasbolster** [comment]
Thank you very much.
