### ISSUE TITLE
docs outdated? No defineSupportCode

### ISSUE THREAD

**Issue by nwwells** [cucumber/cucumber-js#824]
https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md

This article states that I can use the function `defineSupportCode` to register hooks, among other things. However, in version 1.3.2, that function doesn't exist. How do I do that? I'll submit a PR to update the docs once I get it working.

**Comment by charlierudolph** [comment]
`defineSupportCode` was added in 2.0. The readme states the master documentation are for 2.x and gives a link to accessing the 1.x documentation.

**Comment by nwwells** [comment]
Ah, sorry about that! Thanks for an great project!
