### ISSUE TITLE
Cannot read property 'transform' of undefined' when defining a new type

### ISSUE THREAD

**Issue by shivanth** [cucumber/cucumber-js#825]
I get an error 'TypeError: Cannot read property 'transform' of undefined' when defining a new type.

Here's my new type defined in transform.js

```
import {defineSupportCode} from 'cucumber';
import log from 'winston';

defineSupportCode(({defineParameterType}) => {
    defineParameterType({
        regexp: /\[(.+)\]/,
        transformer: s => {
            log.info("1");
            return s;
        },
        typeName: 'list'
    })
})
```
Running cucumber using this throws an error 

```
TypeError: Cannot read property 'transform' of undefined
         at Argument.get (/Users/xxx/tests/node_modules/cucumber-expressions/dist/argument.js:29:33)
```

The `log.info("1")` does get printed.
I'm using babel to transpile the scripts and my StepDef looks like this

```
When('Expect response to have fields {list}',  async function(array){
        log.info("array " + list);
    })
```

**Comment by aslakhellesoy** [comment]
What `cucumber` version are you on? And what version of `cucumber-expressions`? Look in `node_modules/cucumber/package.json` and `node_modules/cucumber-expressions/package.json`

**Comment by charlierudolph** [comment]
@aslakhellesoy I ran into this error in the case of nested capture groups where one is not escaped.
```js
/^a user( named (\d+))?$/ // => causes the same error
 
// a workaround is to make the outer non capturing 

/^a user(?: named (\d+))?$/ // => works
```
Was able to write a failing test on cucumber-expressions. I'll open an issue on the cucumber repo to discuss a solution

**Comment by charlierudolph** [comment]
@shivanth for your example, remove the capture group from the regexp. Whatever matches the regexp is what gets captured. 
```js
defineParameterType({
  regexp: /\[(.+)\]/,
  //..
})

// becomes

defineParameterType({
  regexp: /\[.+\]/,
  //..
})
```

**Comment by shivanth** [comment]
SO I will have to manually remove the square brackets within my step defs ?

**Comment by charlierudolph** [comment]
You can remove them in the transform function of `defineParameterType` in order to only do it in one place.

**Comment by shivanth** [comment]
It worked.

**Comment by charlierudolph** [comment]
Good to hear. Going to close this in favor of the linked issue on the cucumber repo.

**Comment by jugglinmike** [comment]
I'm experiencing the same error whenever any sort of capturing group is in use,
i.e.

    defineParameterType({
      regexp: /(.*)/,
      typeName: 'itemList'
    });

    Given('I have a list with {itemList}', function(items) {
      console.log(items);
    });

Version info:

    $ node --version
    v6.10.3
    $ npm --version
    3.10.10
    $ npm ls | grep cucumber
    ├─┬ cucumber@2.3.1
    │ ├── cucumber-expressions@3.0.0
    │ ├── cucumber-tag-expressions@1.0.1

**Comment by charlierudolph** [comment]
@jugglinmike remove the capture group from the parameter type. The fix for this issue so we throw a proper error is in cucumber-expression@4.0.0 and cucumber-js should include in the next major release (coming soon)

**Comment by jugglinmike** [comment]
Got it. The above discussion made me think this was limited to nested capturing groups, but it sounds like capturing groups of any type are not supported. An explicit error message will make this restriction much more obvious. Thanks!
