### ISSUE TITLE
I failed to find any solution to ignore certain files extensions from transpilation, while using cucucmber-cli

### ISSUE THREAD

**Issue by wysocz** [cucumber/cucumber-js#830]
Hello. 

In my case: `"cucumberjs --compiler js:babel-register",` was throwing an error, because we are using [css-modules](https://github.com/css-modules/css-modules) - this makes babel-register fail, unless there is a way to exclude the css files from transpilation. 

I was able to implement some solution, and will be glad to hear from you what you think about it.

https://github.com/cucumber/cucumber-js/pull/829

**Comment by charlierudolph** [comment]
See #829 for comment. I don't think this is something cucumber-js should be responsible for.
