### ISSUE TITLE
How do I achieve a hook which will be executed after all features?

### ISSUE THREAD

**Issue by pnakhat** [cucumber/cucumber-js#834]
I tried doing below 

        this.registerHandler('AfterFeatures', function (event, callback) {
            reporter.generate(options);
            callback();
        });

however, it gives an error that registerError is not a function. Any help will be much appreciated

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by charlierudolph** [comment]
Thanks @aslakhellesoy. Added this to the [issue template](https://github.com/cucumber/cucumber-js/commit/95be6815139fd6d245d1cc70bc5651327036c499)
