### ISSUE TITLE
RegularExpression constructor is not filtering non-capturing groups

### ISSUE THREAD

**Issue by Jordyderuijter** [cucumber/cucumber-js#837]
Hi there,

It seems like there is a bug in the RegularExpression class in the cucumber-expressions dependency.
The regex in this constructor looks for capturing groups when processing steps using the regex:

 `/\(([^(]+)\)/g`

This regex finds everything between braces (a.k.a. capturing groups), but it also accepts non-capturing groups. This causes the constructor to generate parameter types for the non capturing groups (instead of the capturing groups only). 

These parameter types are used in the buildArguments function, but are only applied to capturing groups, since the given step regex filters out the non-capturing groups correctly.

I would expect the RegularExpression constructor to filter out these capturing groups correctly.

The step and step definitions I used to reproduce the issue are:

Step:
`I can cancel the 1st slide upload`

Step definition:
`(\S+) ?(can|cannot)? (?:delete|cancel) the (\d+)(?:st|nd|rd|th) (attachment|slide) ?(?:upload)?`

In this case 7 parameter types are being generated by the constructor, while it should only create 4, since 3 of them are non-capturing groups. As a result, the parameter type that belongs to (\d+) is being applied to (attachment|slide), treating it as an integer. This results into a NaN value that is being passed to my step definition.

Version info:

- Cucumberjs: 2.1.0
- Node: v6.9.1
- Npm: 3.10.8

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#211
