### ISSUE TITLE
Feature request: Add a SystemJs module loader option

### ISSUE THREAD

**Issue by jfstephe** [cucumber/cucumber-js#839]
Use case:
Green field project. BDD all the way! Yey! Ok, cool.... so, cucumberjs has been chosen to help out (ignore any BDD theory discussions here please). We have js being used on both the client and server side. On the client side, we have (View/ViewModel/Model etc) separation of concerns in our classes all done nicely (using typescript but that's irrelevant) and systemJs as our module loader (used by aurelia in this case).

I don't want to jump into 'use jasmine etc' for unit tests and cucumber for e2e tests, as I think this is looking at it the wrong way around. I want to start with cucumber for everything and only if I feel there's a need, use jasmine etc for specific purposes. Aside, I've seen far too many projects with a 'definition' in feature files and a different 'definition' written in jasmine specs.

-- 

AFAIK this isn't possible, as node loads the cucumber step definitions and that's that. Can this be changed so that systemJs could load the modules?

To be explicit: On a test-by-test basis I want to have a test case in a feature file and decide to check it in the browser (traditional e2e cucumber-protractor testing), or in node (more akin to unit testing). This is made possible by testing non-browser dependent features and would commonly test ViewModels/DomainModels etc.

I appreciate that this would require running cucumber twice with the different configurations but that is ok by me, and I expect to tag the scenarios with 'ui' in, for example, browser tests, of which I hope to have very few.

Is this easy to do? Likely to be done soon? I'm happy to look at creating a PR if you can point me in the right direction.

Thanks,
John

**Comment by charlierudolph** [comment]
I have not heard of SystemJs and don't know what is involved. 

> I appreciate that this would require running cucumber twice with the different configurations but that is ok by me, and I expect to tag the scenarios with 'ui' in, for example, browser tests, of which I hope to have very few.

Isn't this currently possible by running cucumber twice with a different configuration each time?

**Comment by jfstephe** [comment]
Information on SystemJs is available [here](https://github.com/systemjs/systemjs). It's one of the top module loaders for client side js, and works server side too.
ATM cucumberJs can only load js modules via nodeJs standard mechanism. I was wondering if it would be possible to open it up to others too?
I'm trying to get the karma-cucumberJs guy to upgrade to your latest version and then I can see if I can get his plugin working with karam-jspm (a systemJs plugin for Karma). For now this is possibly something to just be aware of, while there are better suited potential solutions out there. I'll report back if I think this *needs* a cucumberjs change.

**Comment by charlierudolph** [comment]
Okay. I'm going to close this issue for now then. Please comment on it again if cucumber-js needs a change and we can reopen

**Comment by Nagendracv** [comment]
SystemJS support is a super important feature. Wondering if we have support by now. Currently all Typescript compilations using SystemJS dont run with Cucumber directly, unless I'm missing something..

**Comment by Nagendracv** [comment]
To verify, add this compiler option in tsconfig.js
"compilerOptions": {
    "module": "system",
    "target": "es5",
    "allowJs": true
}
