### ISSUE TITLE
Enhance test run error when data table is missing and step expects it

### ISSUE THREAD

**Issue by lashchev** [cucumber/cucumber-js#844]
node v6.10.3 on win 10 x64 v1703
cucumber v2.2.0

```
Scenario: Log table data
    When Provided data table below:
    # | k | v |
```

and step implementation like this

```
When('Provided data table below:', function (table, callback) {
    // logic that expects table in the input
    callback();
});

```
Test run returns this error:
```
function has 2 arguments, should have 0 (if synchronous or returning a promise) or 1 (if accepting a callback)
```
In 99% of the cases the actual problem is that step in the scenario definition is missing data table and error should tell feature file owner to fix it, something like this:
Step implementation expects table in the input. Provide it in the feature file or update step implementation to not expect table in the input.

**Comment by charlierudolph** [comment]
I don't believe there is any way to tell that a step implementation expects a table as in input. The argument name is table but that can be changed to anything. The snippet cucumber-js suggests should only include `table` as the first argument if the feature file had a table.

**Comment by lashchev** [comment]
My point the error message is highly technical and targeted at step developers.

Step developer and QA (who owns the feature files and runs the tests and reads test run error messages) are typically different people in non-trivial size teams.

Current message sounds like step developer did something wrong and QA people won't get it at all. But the actual error was most likely done in the feature file and QA should be advised to look at the feature file first.

**Comment by charlierudolph** [comment]
I understand the problem but I don't see a chain of logic we can use reliably in order to produce the desired error message.

**Comment by lashchev** [comment]
Sorry, if my request is not clear. I am not saying that there should be logic or implementation change at all. I understand that it is not possible to know for sure what step implementation expects in the input.

My request is to just literally change "function has 2 arguments, should have 0 (if synchronous or returning a promise) or 1 (if accepting a callback)" to "Either step implementation function is expecting data table that was not provided in the step or step implementation function has 2 arguments, should have 0 (if synchronous or returning a promise) or 1 (if accepting a callback)". 

My point is that first people that read errors are QAs that run the tests, not developers. QAs are confused with highly technical implementation details in the error messages and blindly pass broken build alone to developers even when the problem was on their side in the feature file.

By the way to avoid such problems step implementation functions instead of processing parameters by position and count could've accept something like

`function(input [, callback])
`
where "input" could've been parsed input and other context in form something like:
input.table
input.table.rawtable
...
input.params
input.params.myNamedParamParsedFromPhrase = myValue

This would make the approach open to extension, closed to modification :-)
Just a thought....
