### ISSUE TITLE
data tables: use parameter types to transform values

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#845]
discussed in #752. @aslakhellesoy to explain vision

**Comment by osher** [comment]
@aslakhellesoy  - what's up?

**Comment by charlierudolph** [comment]
@aslakhellesoy you had mentioned moving data tables into https://github.com/cucumber/cucumber. Is that still desired? And for using parameter types, could we do something like: if the table cell value matches one of the parameter types, transform that table cell.

**Comment by aslakhellesoy** [comment]
Yes, https://github.com/cucumber/cucumber/issues/210 is still desired. I'd prefer to continue the discussion there. FYI I'll be unavailable for a couple of weeks

**Comment by charlierudolph** [comment]
Closing then in favor of cucumber/cucumber#210

**Comment by osher** [comment]
I'm afraid  cucumber/cucumber#210 is answering a different use-case

**Comment by osher** [comment]
woups. not that. sorry for the noise
