### ISSUE TITLE
Support code aliases break step definition stacktrace (v2.3.0)

### ISSUE THREAD

**Issue by pittgoose** [cucumber/cucumber-js#846]
I'm using the JSON formatter to report on my tests.
I just upgraded to cucumber 2.3.0 and I changed some step definition files to use the new aliases to define my steps as such:
```
let {When, Then} = require('cucumber');

When(/^I define a step here$/, () => {
...
});
```
This results in the json file looking like this:
```
"steps": [
          {
           "arguments": [],
            "keyword": "When ",
            "name": "I define a step here",
            "result": {
              "status": "passed",
              "duration": 4156
            },
            "line": 16,
            "match": {
              "location": "C:\\<project-root>\\node_modules\\cucumber\\lib\\index.js:176"
            }
          }
...
]
```
But if I change my SD file to use `defineSupportCode` like this:
```

let {defineSupportCode} = require('cucumber');
defineSupportCode(({When}) => {
    When(/^I define a step here$/, () => {
        ...
    });
})
```
I get the proper references to my step location:
```
"steps": [
          {
           "arguments": [],
            "keyword": "When ",
            "name": "I define a step here",
            "result": {
              "status": "passed",
              "duration": 4156
            },
            "line": 16,
            "match": {
              "location": "C:\\<project-root>\\e2e\\step_definitions\\common-steps.ts:12"
            }
          }
...
]
```

@charlierudolph This is something you just worked on. Could we collab on a solution?

**Comment by charlierudolph** [comment]
Danget. Yep thats an error caused by the recent changes. Should be easy to add a feature test for this.

The [code](https://github.com/cucumber/cucumber-js/blob/deffdcf6ac35c074bd3914c6c3dc75ca95ebfa1a/src/support_code_library/helpers.js#L47) currently assumes the user is calling `defineSupportCode` and thus looking a specific number of stackframes back. We could update it to search for the first stackframe that does not include `/node_nodules/cucumber`

**Comment by pittgoose** [comment]
@charlierudolph I sent you a message on Gitter (don't know if you use it). I'd like to PR this but I'm getting stuck.

**Comment by charlierudolph** [comment]
@pittgoose sorry I'm not reliably on gitter. You can open a work in progress PR and I can help out there
