### ISSUE TITLE
tagExpressions ignored by scenario_filter

### ISSUE THREAD

**Issue by lgandecki** [cucumber/cucumber-js#851]
Hey guys

I can see that in scenario_filter_spec you test things like:
```javascript
          this.scenarioFilter = new ScenarioFilter({
            cwd: this.projectPath,
            featurePaths: ['b.feature:1:2'],
            names: ['nameA'],
            tagExpressions: ['tagA']
          })

```
but the scenarioFilter constructor itself only takes those arguments:

```javascript
  constructor({cwd, featurePaths, names, tagExpression}) {}
```
when I try to pass tagExpressions, it is ignored, tagExpression works but it only takes one argument, so I can't pass in an array of tags. I also don't see a logic for working with tagExpressions inside at all, so it wouldn't be as easy as changing the constructor definition.

I'm a bit confused, is this how it's supposed to be? 
I dive in and fix this, but maybe I'm missing something

Thanks!

**Comment by charlierudolph** [comment]
Sorry looks like some tests are out of date. It should be `tagExpression` and be a string. Other tests appear to be passing it in properly.

**Comment by lgandecki** [comment]
Oh, I see..
There are two that do pass values with tagExpressions, and a bunch that just send an empty array using that.
So.. if I wanted to filter with multiple tags, what do I do? I can't attach multiple filters, can I?

**Comment by charlierudolph** [comment]
A tag expressions can include multiple tags. See this [test](https://github.com/cucumber/cucumber-js/blob/b4960c8a4d238ede3e918f6c51e5bcd5a76bfac7/src/scenario_filter_spec.js#L207) and this [documentation](https://docs.cucumber.io/tag-expressions/)

**Comment by lgandecki** [comment]
cool, thanks!
