### ISSUE TITLE
Using Protractor to execute Cucumberjs specifying tags returns error

### ISSUE THREAD

**Issue by edgarechm** [cucumber/cucumber-js#852]
After the update to Cucumber2.0, the syntax for Tags changed.

I use a _package.json_ to execute my scripts using "npm test" command.

This was the "old" syntax I had in _package.json_, that used to work:
`protractor ./FM_IntTest_UI_conf.js --cucumberOpts.tags ~@ignore --cucumberOpts.tags @smoke,@rt
`

Based on what Cucumberjs2.0 doc says...

> Old Cucumber was This: `--cucumberOpts.tags ~@ignore --cucumberOpts.tags @smoke,@rt`
> With Cucumber2.0 should be: `--cucumberOpts.tags 'not @ignore and (@smoke or @rt)'`

So I tried:
`protractor ./FM_IntTest_UI_conf.js --cucumberOpts.tags 'not @ignore and (@smoke or @rt)'`

AND to be consistent with the documentation, I also tried...

`protractor ./FM_IntTest_UI_conf.js --tags 'not @ignore and (@smoke or @rt)'`

**Neither Worked**. For both I got the following error:

> ' was unexpected at this time.
> 
> 
> C:\workspace>  "C:\workspace\node_modules\.bin\\node.exe"  "C:\workspace\node_modules\.bin\\..\protractor\bin\protractor" ./FM_IntTest_UI_conf.js --tags 'not @ignore and (@smoke or @rt)'
> npm ERR! Test failed.  See above for more details.

**What is now the correct syntax?**

**Comment by charlierudolph** [comment]
This is the wrong place to post an issue you are running into using `protractor` as I do not know much about that project. I have only used `cucumber-js` directly and not through other frameworks.

Based on you error message `' was unexpected at this time.` Did you try using double quotes instead of single quotes?

**Comment by edgarechm** [comment]
With double quotes works directly from the prompt.

However, as I mentioned I use a _package.json_ to run the scripts. So, if I place the statement in double quotes, would mean that I would place **_Double Quotes_ inside _Double Quotes_** :

`"test": "protractor ./FM_IntTest_UI_conf.js --cucumberOpts.tags "not @ignore and (@smoke or @me)""`
 AS YOU CAN SEE ----------------HERE DOUBLE DOUBLE QUOTES----^--------AND HERE TOO----------^

**Thus, ERROR:**
C:\workspace>npm test
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! file C:\workspace\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'o' at 6:165
npm ERR! --cucumberOpts.tags "not @ignore
npm ERR! --------------------------^
npm ERR! File: C:\workspace\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\npm-debug.log

**Comment by edgarechm** [comment]
Yes, double quotes... and scape char. Thanks! I leave the note here if useful for someone:
"protractor ./FM_IntTest_UI_conf.js --cucumberOpts.tags \"not @ignore and (@smoke or @me)\""
