### ISSUE TITLE
Tags order affects which scenarios are filtered

### ISSUE THREAD

**Issue by redi-wadash** [cucumber/cucumber-js#876]
I could reproduce with cucumber 2.3.1 as well as 2.2.0. I couldn't see anything about order of tags in [the documentation](https://github.com/cucumber/cucumber/wiki/Tags), so I believe this is a bug.

Here is the minimum steps to reproduce:

1. Create the following feature file:
    ```gherkin
    @both
    Feature: Foo

      @a
      Scenario: a
        Given it is a test

      Scenario: b
        Given it is a test
    ```
2. Execute `./node_modules/.bin/cucumberjs --tags @both --tags @a`
    - This executes only scenario "a", which is expected.
3. Execute `./node_modules/.bin/cucumberjs --tags @a --tags @both`
    - This executes both scenario "a" and "b", although scenario "b" doesn't have the tag `@a`.

**Comment by charlierudolph** [comment]
The documentation you are referencing does not apply to cucumber-js. That is how tags used to work. They now use https://docs.cucumber.io/tag-expressions/. This is documented in the [cucumber-js docs](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#tags)

**Comment by charlierudolph** [comment]
@aslakhellesoy @mattwynne should the docs at https://github.com/cucumber/cucumber/wiki have a disclaimer added to them. I don't know what they were originally documenting or who is currently maintaining them (if anyone)

**Comment by mattwynne** [comment]
@charlierudolph yes. We have a project underway to migrate everything into https://github.com/cucumber/docs.cucumber.io and then start cleaning it up. I think a disclaimer in the mean time is a good idea.

cc @plaindocs

**Comment by redi-wadash** [comment]
Ah, that worked beautifully.

I thought I saw Cucumber.js documentation saying `--tags @a --tags @b` does "and" operation, but I cannot find one now. Maybe I was seeing outdated documentation.

Thanks!
