### ISSUE TITLE
Docker image to run cucumber - js

### ISSUE THREAD

**Issue by aescarcha** [cucumber/cucumber-js#882]
Hi, I'm Alvaro, from EpicLabs.

We've build a **docker image** to run cucumber with protractor, selenium and chrome headless, it's really simple to get it up and running. We've thought it could help some developers if you linked it as a resource from the README, what do you think?

The image is [here](https://hub.docker.com/r/epiclabs/e2e-test-runner/), and the [github repository](https://github.com/epiclabs-io/docker-cucumber-protractor-chrome) includes two executable tests, (one of them from your website).

Best regards!

**Comment by charlierudolph** [comment]
What is the reasoning behind using a docker image?

**Comment by aslakhellesoy** [comment]
If you're running Cucumber in docker you're most likely using it for testing, and not for *Behaviour Driven Development* (BDD).

I don't think we should promote Cucumber as a testing tool...

**Comment by aescarcha** [comment]
The reasoning behind using a docker image is that:

- It makes it way easier to integrate cucumber in our CI flow, launching the scenarios automatically every time a commit is done.
- People can check cucumber (in non graph mode) really easily without the need to install dependencies, and in any platform.

So what we do is BDD with our dev envs, which have the full installation to make it easier for development, and then we launch the tests with the image in our CI flow.

**Comment by charlierudolph** [comment]
Closing due to age. I don't see enough benefit from this. If we get some comments from others that think this would be useful to stick on the readme, we can add it.

**Comment by Srutherford2407** [comment]
As a QA Automation Engineer this would be every useful when teaching other members of the QA that lack any sort of coding experience. We use Cucumber from the beginning in our storying writing processes. When then take theses Cucumber/Gherkin written stories to build out our tests ensuring our tests are covering the behavior discussed from the beginning. 

Being able to add cucumber to docker with different headless versions of selenium would truly speed up the process of testing these stories over multiple browsers and OS's when you have a small QA team of people managing an application. 

I also agree in regards to the CI flow, and in the event of failed tests our developers have instant feedback as to the Behavior they have broken with their updated code merge.

**Comment by Carmot** [comment]
Hi Álvaro,

In our company we have also created our internal Docker image with cucumber for our BDD.
Docker image make our development team spread across the world to use exactly the same version and integrate it in our cloud development environment. We've just to create the .feature file and run our CI/CD tool to execute this step.

I really don't understand why having it inside a Docker image makes people think you aren't doing BDD... It is just the same but encapsulated into Docker image instead of having all the modules locally.

For us it is very useful using our own Docker image for running cucumber testing.

**Comment by Srutherford2407** [comment]
@aslakhellesoy  Any more thoughts on this after the most recent comments?

**Comment by fahimbinkhair** [comment]
fahimu@fahimu-HP-ProBook-430-G5:~/Documents/optimus$ docker run epiclabs/e2e-test-runner
webdriver-manager: using local installed version 12.0.6
[19:12:40] I/update - chromedriver: unzipping chromedriver_2.46.zip
[19:12:40] I/update - chromedriver: setting permissions to 0755 for /src/node_modules/webdriver-manager/selenium/chromedriver_2.46
[19:12:44] I/update - geckodriver: unzipping geckodriver-v0.25.0.tar.gz
[19:12:44] I/update - geckodriver: setting permissions to 0755 for /src/node_modules/webdriver-manager/selenium/geckodriver-v0.25.0
Waiting for selenium on 127.0.0.1
webdriver-manager: using local installed version 12.0.6
[19:12:45] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/src/node_modules/webdriver-manager/selenium/chromedriver_2.46 -Dwebdriver.gecko.driver=/src/node_modules/webdriver-manager/selenium/geckodriver-v0.25.0 -jar /src/node_modules/webdriver-manager/selenium/selenium-server-standalone-4.0.0-alpha-2.zip.jar -port 4444
[19:12:45] I/start - seleniumProcess.pid: 26
[19:12:45] I/start - Selenium Standalone has exited with code 1
Waiting for selenium on 127.0.0.1
Waiting for selenium on 127.0.0.1
Waiting for selenium on 127.0.0.1
Waiting for selenium on 127.0.0.1

And it keep going on forever. ANy Advice plese
