### ISSUE TITLE
Undefined steps found

### ISSUE THREAD

**Issue by vinodkpasi** [cucumber/cucumber-js#883]
I have written script Using protractor/protractor-cucumber-framework.js/cucumber.js
I used below commands: 
npm install protractor
npm install cucumber
npm install protractor-cucumber-framework

While running the script I am getting the error message.
![image](https://user-images.githubusercontent.com/25478920/28701999-c5050f98-7377-11e7-813c-e381fc3a078f.png)

Note: If use below commands to install cucumber/protractor-cucumber-framework everything is working file.
           npm install cucumber@0.10.2
           npm install protractor-cucumber-framework@0.5.0

These are project files:
**test.feature**
Feature: Sample Test
Scenario: Protractor and Cucumber Test
Given I go to the application

**mystep.js**
var myStepDefinitionsWrapper = function () {
    this.Given('I go to the application', function (callback) {
        callback();
    });
}
module.exports = myStepDefinitionsWrapper;

**Config.js**
//protractor.conf.js
//require.resolve('protractor-cucumber-framework')
exports.config = {
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    directConnect:true,
    capabilities: {
        'browserName': 'chrome'
    },

    // Spec patterns are relative to this directory.
    specs: [
        'test.feature'
    ],

    baseURL: 'http://localhost:8080/',

    cucumberOpts: {
       require: 'mysteps.js'
    }
};

**Comment by charlierudolph** [comment]
Did you open an issue on `protractor-cucumber-framewor` first? I don't have an experience with that framework and thus am unlikely to be able to help

**Comment by vinodkpasi** [comment]
Thanks for your reply. I posted on **protractor-cucumber-framework** and got the solution.
Below is posted url.
https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/90
