### ISSUE TITLE
Cucumber Expressions: transforms uniqueness

### ISSUE THREAD

**Issue by rober710** [cucumber/cucumber-js#884]
Hi,
I'm trying to implement a step like this (using Nightwatch.js):

```
    Given(/^I set the browser size to {wsize}x{wsize} px/i, (width, height) => {
        console.log(`  Resizing window to ${width} x ${height}...`);
        browser.resizeWindow(width, height);
    });
```
And I have a transform like this:
```
defineSupportCode(({defineParameterType}) => {
    defineParameterType({
        regexp: /\d+/,
        transformer: s => {
            console.log(s);
            return parseInt(s);
        },
        typeName: 'wsize'
    });
});
```
However, when I try to run the test I get this error:
`Error: There is already a parameter with regexp \d+`

Is there a way to implement this? I mean, a way to have multiple parameters of the same type in the same step definition?

I read this [issue](https://github.com/cucumber/cucumber/issues/132), but it seems that is not my use case.

My environment:

cucumber: 2.3.1
nightwatch: 0.9.16
nightwatch-cucumber: 7.1.10

**Comment by charlierudolph** [comment]
Not currently. Support for this is being added in #869

**Comment by charlierudolph** [comment]
closing as #869 has been merged
