### ISSUE TITLE
BeforeAll isn't passed to defineSupportCode

### ISSUE THREAD

**Issue by caiges** [cucumber/cucumber-js#885]
Following the docs, it appears you should be able to register a before all hook via `defineSupportCode`. However, on the latest release of cucumber (`2.3.1`), this is what is passed to the callback:

```js
{
  addTransform: [Function: deprecated],
  defineParameterType: [Function], 
  After: [Function], 
  Before: [Function], 
  defineStep: [Function], 
  registerHandler: [Function], 
  registerListener: [Function: registerListener], 
  setDefaultTimeout: [Function: setDefaultTimeout], 
  setDefinitionFunctionWrapper: [Function: setDefinitionFunctionWrapper], 
  setWorldConstructor: [Function: setWorldConstructor], 
  Then: [Function], 
  When: [Function], 
  Given: [Function] 
}
```

**Comment by charlierudolph** [comment]
Sorry for the confusion but `BeforeAll` / `AfterAll` is unreleased and will be released in 3.x which is waiting on a couple PRs to go in. I updated the CHANGELOG to reflect this
