### ISSUE TITLE
404 on Event handler page

### ISSUE THREAD

**Issue by arjunjh10** [cucumber/cucumber-js#888]
Hello,
I was browsing through the repo this morning to check something and found that Event handlers page does not exist anymore.
https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/event_handlers.md

![screen shot 2017-08-03 at 12 02 17 pm](https://user-images.githubusercontent.com/7624561/28900210-bdd51a80-7843-11e7-8c64-2fa398759895.png)

If the plan is to deprecate them, what should be used in case anyone's already using a handler like e.g. `AfterFeature`
Thanks in advance

**Comment by charlierudolph** [comment]
Thanks for reporting this. The README has been updated
