### ISSUE TITLE
3.0.0 - BeforeAll, AfterAll hooks - "this" is equal to null

### ISSUE THREAD

**Issue by tom3k** [cucumber/cucumber-js#896]
Hi,

I noticed that "this" keyword is equal to null in new BeforeAll and AfterAll hooks

```
'use strict';

const {defineSupportCode} = require('cucumber');

defineSupportCode(function ({BeforeAll, AfterAll}) {
    BeforeAll(function () {
        this.someVariableInWord = 1;
    });

    AfterAll(function () {
        console.log(this.someVariableInWord);
    });
});
```

Error in console:
`VError: a BeforeAll hook errored, process exiting: steps/common/hooks.js:6: Cannot set property 'someVariableInWord' of null`

I think I should have access to this like in other hooks.

Thanks,
Tom

**Comment by charlierudolph** [comment]
A new world instance is created for each test case (analogous to a scenario). BeforeAll / AfterAll run before / after all test cases and thus there is no world instance that can be injected. I'll update the documentation to mention this

**Comment by charlierudolph** [comment]
Documentation updated: https://github.com/cucumber/cucumber-js/blob/bc4099581d5413ef62acd74fbc6371321c092360/docs/support_files/hooks.md
