### ISSUE TITLE
[Docs][README] Shouldn't the README.md indicate the use of --save-dev?

### ISSUE THREAD

**Issue by JoaoGFarias** [cucumber/cucumber-js#897]
Since Cucumber.js is a testing tool, it will be used only during development.
I think indicating `npm install cucumber --save-dev` in the README.md would avoid beginner/unaware users to send the dependency to production.
What do you guys think?

**Comment by charlierudolph** [comment]
There are some tools that build on top of cucumber and thus would save it as a dependency. The vast majority of cases will use it as a development tool though. We don't have the `--save` on the README so I don't see how it encourages people saving it as a production dependency.
