### ISSUE TITLE
writing output to a file with an absolute path prevented in v3.0.0

### ISSUE THREAD

**Issue by travi** [cucumber/cucumber-js#900]
because of the [`path.join` with `this.cwd` passed to `fs.open` when preparing to write to a file](https://github.com/cucumber/cucumber-js/blob/f11e30f437d2a4faea78ec5ffa351ad18c306f03/src/cli/index.js#L38), an absolute path is handled as relative to the project path instead of the root of the system when starting with a leading `/`. 

in my case this is breaking the ability for [circle-ci to process the cucumber report](https://circleci.com/docs/1.0/test-metadata/#cucumber) since `$CIRCLE_TEST_REPORTS=/tmp/circle-junit.aLqT5ZY` (or similar), but cucumber tries to write to `/home/ubuntu/<project-name>/tmp/circle-junit.aLqT5ZY/cucumber/tests.cucumber` instead of `/tmp/circle-junit.aLqT5ZY/cucumber/tests.cucumber`, as defined by the environment variable.

**Comment by charlierudolph** [comment]
I believe if we switch `path.join` to `path.resolve` that will fix the issue. We should add a feature test for this where it supplies an absolute path into a temp directory.

**Comment by travi** [comment]
Thanks @charlierudolph and @darrinholst !
