### ISSUE TITLE
Would you be willing to consider a watch mode PR?

### ISSUE THREAD

**Issue by lgandecki** [cucumber/cucumber-js#901]
Hey guys,

Would you be willing to consider a watch mode in cucumber? 
How I see it - 
rerunning .feature file when it changes ( easy )
rerunning a feature when its support code changes is more complex, but would be possible, we need to save the information about which .feature was connected to which .js files, when the .feature files first run. We start watching all js files that were used for the initial run, and then just look through that mapping structure whenever we change one of the js files. 

Do you have any insights into that? 

I would be willing to spent on it some hours, unless you think cucumber shouldn't have this feature, or unless you think it will be harder than I imagine :)

Thanks!

**Comment by aslakhellesoy** [comment]
I think this would be great, as a standalone tool, bit not as part of the Cucumber codebase.

**Comment by samhatoum** [comment]
@aslakhellesoy do you know of any trickery that allows us to get the scenario > step def mapping? 

I found that `--dry-run --format usage-json` is close but it doesn't show the implementing step

**Comment by lgandecki** [comment]
right... it seems that cucumber does the hard work of matching .feature files -> .js files already, standalone tool would have to do the parsing itself, which is a lot of duplication of quite complex code. Having some way of cucumber to tell the external tool about the connections (like @samhatoum suggests) would be great

**Comment by charlierudolph** [comment]
What is usage-json missing exactly?

**Comment by charlierudolph** [comment]
Bump what is missing from the current usage-json that you would like added?

**Comment by charlierudolph** [comment]
Closing due to age. I agree I think this should be a standalone tool
