### ISSUE TITLE
_.size always returns 0 for attachments in JSON formatter

### ISSUE THREAD

**Issue by INRIX-Jonny-Sooter** [cucumber/cucumber-js#902]
Attaching data to the attachments property of a StepResult works, and the stepResult.attachments property is filled in json_formatter.js. However, this size check returns 0 regardless of the length of the attachments array:
![screen shot 2017-08-15 at 1 15 17 pm](https://user-images.githubusercontent.com/29552158/29339075-64e9f772-81cd-11e7-9738-013e5bc3be44.png)

To reproduce, manually add two properties to currentStep when it's initialized. Then, attach a simple string to any step.

Repro example:
![screen shot 2017-08-15 at 1 15 31 pm](https://user-images.githubusercontent.com/29552158/29339069-5daac5e0-81cd-11e7-92ad-301a8f0ef4b5.png)

JSON Output:
![screen shot 2017-08-15 at 3 25 21 pm](https://user-images.githubusercontent.com/29552158/29339188-010d1c06-81ce-11e7-80ab-22e5ba3a41e0.png)

Cuke version: 2.3.1 and 3.0.0
Node: v6.9.5
Browser: Chrome Driver 2.3.1

**Comment by charlierudolph** [comment]
I'm totally lost. We have feature tests on both versions that verify this works in node.

* https://github.com/cucumber/cucumber-js/blob/2.x/features/attachments.feature
* https://github.com/cucumber/cucumber-js/blob/v3.0.0/features/attachments.feature
