### ISSUE TITLE
Cannot find module 'cucumber' on Windows 7 64 bits

### ISSUE THREAD

**Issue by abarriosh** [cucumber/cucumber-js#908]
I have problems running cucumber on Windows 7 64bit. I installed cucumber globally and set the variable NODE_PATH. I verify with node -> require('cucumber') and the result confirms that 'cucumber' is setted up OK. But when i execute "cucumber-js" in the command line the following error is present:

C:\protractor-test>cucumber-js
Error: Cannot find module 'cucumber' from 'C:\protractor-test'
at C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_modules\r
esolve\lib\async.js:48:31
at processDirs (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\n
ode_modules\resolve\lib\async.js:182:39)
at ondir (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_mo
dules\resolve\lib\async.js:197:13)
at load (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_mod
ules\resolve\lib\async.js:80:43)
at onex (C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_mod
ules\resolve\lib\async.js:105:17)
at C:\Users\Usuario\AppData\Roaming\npm\node_modules\cucumber\node_modules\r
esolve\lib\async.js:26:73
at FSReqWrap.oncomplete (fs.js:123:15)

Any idea? Thanks

**Comment by charlierudolph** [comment]
Cucumber cannot be used globally. It needs to be required in your step definitions, and this requires a local install. It appears we need to update the error message when you do not have cucumber installed locally.
