### ISSUE TITLE
Multiple formatters

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#91]
Allow for multiple formatters in a single run. This is already easy to accomplish in non-CLI environments.

**Comment by cades** [comment]
+1

**Comment by charlierudolph** [comment]
My suggestion for the CLI from #389
```
# equivalent
--format pretty 
--format pretty:stdout

--format json:/path/to/output
```

**Comment by kmckee** [comment]
I'd **love** to see this feature.  

I'm running cucumberjs on a ci server.  I want pretty output sent to stdout and junit output to a file so that Jenkins can parse it.

**Comment by bricas** [comment]
+1

**Comment by yaworsw** [comment]
+1

**Comment by mohlsen** [comment]
+1

**Comment by kmckee** [comment]
Awesome!  Thank you!
