### ISSUE TITLE
Can't define steps using "{string}" type notation

### ISSUE THREAD

**Issue by Marclev78** [cucumber/cucumber-js#913]
I have the following step in my scenario:

`And I submit the add-salad command with caesar-salad, which costs 7`

Using Cucumber.js 2.31, I defined the following step definition and it worked fine:

`When("I submit the add-salad command with {string}, which costs {int}", function (saladName, amount) {`

However, after upgrading to Cucumber.js 3.0, this no longer works and I get the following error:

```
And I submit the add-salad command with caesar-salad, which costs 7
       Undefined. Implement with the following snippet:

         When('I submit the add-salad command with caesar-salad, which costs {int}', function (int, callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });

```

According to the documentation at https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md, I see no issue with my syntax and the fact that this worked fine before 3.0 leads me to believe that it is an issue in the latest version of Cucumber.

If I write the step definition as:

`When(/^I submit the add-salad command with (.*), which costs (\d*)$/, function (saladName, amount) {`

It works, however this is not an acceptable workaround for me as it interprets the type of the `amount` parameter as being a string, not a number.

**Comment by aslakhellesoy** [comment]
A `{string}` matches quoted strings, for example `"caesar-salad"` or `'caesar-salad'`, but not `caesar-salad`. Either add quotes around your `caesar-salad`, or leave it unquoted, but change your type from `{string}` to `{word}`, which doesn't require quotes.

**Comment by Marclev78** [comment]
I can see from the Cucumber 3.0 release notes (now that I'm looking for it), that {stringInDoubleQuotes} has been replaced by {string}. 

I would suggest the release notes should include the reference to the {word} type as being a workaround for this breaking change.

**Comment by aslakhellesoy** [comment]
What exactly are you suggesting we add? The [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#300-2017-08-08) already has:

> `{stringInDoubleQuotes}` is now `{string}` which works for strings in single or double quotes

and

> Add built in `{word}` parameter type which is equivalent to `[A-Za-z0-9_]+`
