### ISSUE TITLE
Is there anything like witnessStepResult in V3?

### ISSUE THREAD

**Issue by yaronassa** [cucumber/cucumber-js#920]
In V2, I used the ability to augment scenario objects with extra steps via `ScenarioResult.witnessStepResult`.
Is there any parallel ability in V3?
More specifically, can I, at the end of the run, add steps to previous scenarios (assuming I retain their cucumber object / some unique ID method)?

I could manipulate the outputted JSON results after the run, but then I would lose the entire state of my infrastructure.

Thanks

**Comment by charlierudolph** [comment]
Why are you adding steps? There is nothing like that in v3

**Comment by yaronassa** [comment]
Thanks, I'll do it though post-run result manipulations.

For completion, this is my usage scenario (I know it's out of the ordinary):
I have several scenarios that test offline long-running processes. In order to optimize the tests runtime, these scenarios have "a-sync" steps.
These steps immediately return a success status, and add a "pending task" that slowly executes the real business process in the background (any following steps in the scenario are also treated as async in this manner).

After the run has finished, I wait for the queue to drain, and then add the real results to the scenario object (which is saved in the queue as part of the task context).

This way I compress what would be a 4-5 hours long test-run to a ~30 minutes one.

Thanks for the prompt reply.
