### ISSUE TITLE
Control Load and Execution .features files

### ISSUE THREAD

**Issue by rpereira15** [cucumber/cucumber-js#922]
Hi!
Like you can see [here](https://github.com/mucsi96/nightwatch-cucumber/issues/277), i use the nigthwatch-cucumber and need to control the order os my .features files.
So i changed this project and request the new feature.
Feedback of project owner was the this feature are responsability of cucumber-js project.
So i ask, can i do this here?
Thanks

**Comment by charlierudolph** [comment]
Currently, you can control the order by passing in the paths in the order you want to run them.
```
cucumber-js features/dir2 features/dir1
```

---

From your linked post:

> Cucumber uploads all .features files in alphabetical order. This behavior limits our control over tests of runs and forces to write the whole scenario into a unic .feature file.

I don't understand why this is limiting.

> With this control behavior, we will write much less .feature files. Since we can reuse between one test and another, just set the order.
In addition, the testing project will be much more organized. We can apply concepts like single responsibility and others.

How does having this control allow you to write less .feature files?

**Comment by rpereira15** [comment]
> I don't understand why this is limiting.

So, look this scenario.
In a test, i need sigin on system, chose a menu and create a product.

My .feature file will be like that:
-scenario for loggin
-scenario for access menu
-scenario for create product

Every each scenario own your data table.

In other test, i need sigin on system, chose a menu and create a new user
I must need create another .feature file with same structure, but the last scenario are for create user
-scenario for loggin
-scenario for chose menu
-scenario for create a user


I need do this, because cucumber load all .features files in alphabetic order and make a run queue. So, if i maintain all scenarios in same file, i controll execution of tests.
If i split in a .fetaures files with single responsibilty, cucumber behavior will try execute first the  accessMenu.feature before the sigin.feature for example.
What i did with nightwatch was controll the order load of .features files.
See the project example on original issue link.

If someday the way of chosing menu be modify, i'll need change every single .feature file who gets this scenario
With the another behavior,  will more simple do maintenence on my tests because i need writing just one time .feature file for your purpose.

> Currently, you can control the order by passing in the paths in the order you want to run them.

If my test has more than 10 scenarios, passing as a parameter on terminal or npm run is impracticable and a nightmare to update if i desired run another scenario.

**Comment by charlierudolph** [comment]
Cucumber has the philosophy that scenarios should not be connected. Each should be independent from each other (which is why each scenario gets a new world instance).

Needing to control the load execution is against that goal that philosophy. Cucumber-ruby actually has something that directly contradicts this which is the ability to run the scenarios in a random order to validate that they are not connected
