### ISSUE TITLE
defineParameterType still requires typeName over name

### ISSUE THREAD

**Issue by gd46** [cucumber/cucumber-js#927]
I was defining a custom parameter type and noticed that the example says to use name and when I checked cucumber source i see that typeName should be deprecated. However when I run the below example using cucumbers 3.0.1 It cant find my custom type unless I use typeName, I never get the warning its deprecated, and if I use name instead I get undefined. 

This is in support/transforms.js 
```javascript
let {defineSupportCode} = require('cucumber');
let Promise = require('bluebird');

defineSupportCode(({defineParameterType}) => {
	defineParameterType({
	      regexp: /belly/,
	      transformer: s => Promise.resolve(s.toUpperCase()),
	      typeName: 'belly'
	})
})

```

This is my step definition
```javascript
Given('I have {int} cucumbers in my {belly}', function(int, belly) {
  	this.expect(belly).to.equal('BELLY');
    return this.expect(int).to.equal(42);
  });
```

This is my feature file

```
Feature: example

  Scenario: Custom Transform
  	Given I have 42 cucumbers in my belly
```

Also as a continuation question, is there a difference from making the transforming resolve a promise vs not? I saw that both worked for my current step definition example without having to make any changes. Just wondering what the benefit is from using Promise in transform.

**Comment by gd46** [comment]
I think it was a minor version difference. I have updated cucumber again, and Im on: 

cucumber@3.0.2

And I now see the expected behavior.

**Comment by charlierudolph** [comment]
Yep. Sorry I had started writing a response about that the documentation had been updated for master and not released. Got distracted trying to figure out how to deal with that in the future (didn't come up with a good solution) but went ahead an released.

**Comment by gd46** [comment]
No worries thanks!
