### ISSUE TITLE
With shardTestFiles browser windows are not being closed after tests are finished

### ISSUE THREAD

**Issue by natalya-semenova** [cucumber/cucumber-js#928]
With shardTestFiles: true browser windows are not being closed after tests are finished. Launcher says 'X instance(s) of WebDriver still running' and test run never completes.

Node Version: v8.4.0
Protractor Version: 5.1.2
Angular Version: 1.6.5
Browser(s): Chrome
Operating System and Version Linux (Fedora release 26) x86_64
Please find the protractor configuration file, relevant example test, output from running the test, steps to reproduce here: https://github.com/natalya-semenova/issues

The original issue was opened here: angular/protractor#4480

**Comment by wswebcreation** [comment]
Hi @natalya-semenova ,

CucumberJS has no knowledge of Protractor, so it should be filed in protractor-cucumber-framework I think ;-)
