### ISSUE TITLE
Add the -L / --language CLI option

### ISSUE THREAD

**Issue by RomkeVdMeulen** [cucumber/cucumber-js#929]
The `-L` / `--language` CLI option can be used with Cucumber to [set the default language for feature files](https://github.com/cucumber/cucumber/wiki/Spoken-languages#selecting-a-language-from-the-command-line), so you don't have to add an override to each and every file.

Could this also be added to Cucumber.js?

**Comment by charlierudolph** [comment]
Sounds good to me. Not certain if this is possible at the moment as a dependency does the gherkin parsing. Opened an issue there

**Comment by RomkeVdMeulen** [comment]
Awesome! Thank you.
