### ISSUE TITLE
Dynamically change the scenario name after scenario is executed

### ISSUE THREAD

**Issue by venkataramkishore** [cucumber/cucumber-js#931]
Hi All,

This is not an issue. but i am trying to figure out the way to update Scenario name after the execution of Scenario. Dynamically add some value to the Scenario name.
Lets say: 
Scenario: Upload a file 
...

this.After((scenario, cb)=>{
//here i can access only the getName to fetch scenario name
// at this situation i want to update Scenario as below
scenario.setName(`${scenario.getName()} performed in ${inTime}`);
})

And i am expecting this update in report generated html.

I have searched for and help but could not find. If this is possible please guide me. Is this some thing interested to add as feature?
Thank you.

**Comment by charlierudolph** [comment]
This is not possible at the moment and not something I think we should implement. Why do you want to update the scenario name? The timing information is available for each step and the html formatter could roll that up to display the time the scenario took.

**Comment by venkataramkishore** [comment]
Time value represent the entire step completion, inside which we can also have expect conditions available. i want to test only the upload functionality to test with time difference before and after the hit on button. As you suggest if step itself gives me actual time then i can use that.

Thanks for the response, i will use the same step def time for now.
