### ISSUE TITLE
format:json cucumberOpts causes browser to close immediately

### ISSUE THREAD

**Issue by doe-d** [cucumber/cucumber-js#933]
I am running a Protractor cucumber test and trying to generate report using protractor-multiple-cucumber-html-reporter-plugin.

But when I am using format:json:result.json in the config file the browser(chrome) immediately closes as soon as the test starts running and it shows all the test cases passed in the report.

But I wrote the scenarios in such a way that some test cases should fail.This only happens when I using format:json:result.json in cucumberOpts.

When I am using format:'pretty', browser works fine and it shows running of all the test cases and also it shows correct number of test cases passed and failed.

Please find my config file
const path = require('path');

exports.config = {
directConnect: true,
framework: 'custom',
frameworkPath: require.resolve('protractor-cucumber-framework'),
cucumberOpts: {
require: [
'maths.js',
],
// Tell CucumberJS to save the JSON report
format: 'json:.tmp/results.json',
strict: true
},

specs: [
    '*.feature'
],

multiCapabilities: [{
    browserName: 'chrome',
    shardTestFiles: true,
    maxInstances: 2,
    chromeOptions: {
        args: ['disable-infobars']
    }
}],

// Here the magic happens
plugins: [{
    package: 'protractor-multiple-cucumber-html-reporter-plugin',
    options:{
    	 automaticallyGenerateReport: true,
         removeExistingJsonReportFile: true
    }
}]
};

package.json

{
"name": "protractor-cucumber-example",
"description": "Example of using Protractor with Cucumber and Page Objects",
"repository": "https://github.com/mlev/protractor-cucumber-example",
"license": "Apache-2.0",
"devDependencies": {
"chai": "~3.5.0",
"chai-as-promised": "~6.0.0",
"cucumber": "~1.3.2",
"multiple-cucumber-html-reporter": "^1.0.1",
"protractor": "^5.1.1",
"protractor-beautiful-reporter": "^0.5.0",
"protractor-cucumber-framework": "^3.0.0",
"protractor-multiple-cucumber-html-reporter-plugin": "^1.1.0",
"protractor-pretty-html-reporter": "0.0.14"
},
"scripts": {
"prestart-webdriver": "webdriver-manager update",
"start-webdriver": "webdriver-manager start",
"protractor": "protractor protractor.conf.js"
},
"dependencies": {
"pretty": "^2.0.0"
}
}

**Comment by doe-d** [comment]
Console log
[13:52:22] I/launcher - Running 1 instances of WebDriver
[13:52:22] I/direct - Using ChromeDriver directly...
Feature: test page

Scenario: Verify tilte contains Angular Js
√ Given I visit angularjs.org
√ When I check the title
√ Then I title contains angularjs

1 scenario (1 passed)
3 steps (3 passed)
0m00.004s

===============================================================================

Multiple Cucumber HTML report generated in:

C:\Users\user\eclipse-workspace\test_7\.tmp\report\index.html

Tnx for using Multiple Cucumber HTML report

Grtz wswebcreation
===============================================================================

[13:52:35] I/launcher - 0 instance(s) of WebDriver still running
[13:52:35] I/launcher - chrome #1 passed

Please find below the config file

conf.js

// An example configuration file.

exports.config = {
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.


  // Framework to use. Jasmine is recommended.
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['angular.feature'],

   cucumberOpts: {
   
      require: [
          'angular_steps.js',
      
            ],
    
       format: 'json:.tmp/results.json',
        strict: true
      },
  multiCapabilities: [{
      browserName: 'chrome',
      shardTestFiles: true,
      maxInstances: 2,
      chromeOptions: {
          args: ['disable-infobars']
      }
  }],

 
  plugins: [{
      package: 'protractor-multiple-cucumber-html-reporter-plugin',
      options:{
       	 automaticallyGenerateReport: true,
           removeExistingJsonReportFile: true,
           openReportInBrowser: true
      }
  }]
};

**Comment by charlierudolph** [comment]
Did you open an issue on `'protractor-cucumber-framework'` first?
I have no experience with protractor, so I believe you have a better chance of getting help there.
I don't believe this is an issue with cucumber as it does not have a browser built in
