### ISSUE TITLE
Latest release is failing tests on node 4 and 6

### ISSUE THREAD

**Issue by veliancreate** [cucumber/cucumber-js#935]

**Comment by wswebcreation** [comment]
@veliancreate 

Can you clarify this / provide more info? Because based on Travis-CI Cucumber should be working on 4 / 6 / 8

![image](https://user-images.githubusercontent.com/11979740/30854167-352f1698-a2b1-11e7-9a23-848f19fb0032.png)

**Comment by veliancreate** [comment]
@wswebcreation it appears to be failing the AppVeyor tests, but looks like an upstream branching issue...

<img width="545" alt="screen shot 2017-09-26 at 10 46 39" src="https://user-images.githubusercontent.com/7488209/30854475-a59cac22-a2a9-11e7-948d-c4f5dd9729e9.png">

<img width="1056" alt="screen shot 2017-09-26 at 10 52 43" src="https://user-images.githubusercontent.com/7488209/30854480-ad086ffa-a2a9-11e7-9821-f0e8818220f6.png">

We were getting a previously unseen issue when updating, but it may be unrelated...

**Comment by wswebcreation** [comment]
Sorry, missed that part, but when I look at the latest build in AppVeyor it's also green. So or I'm missing something, or I need new glasses ;-)

**Comment by veliancreate** [comment]
Yeah closing...
