### ISSUE TITLE
World does not exit inside setDefinitionFunctionWrapper in Cucumber 3

### ISSUE THREAD

**Issue by koprivica** [cucumber/cucumber-js#937]
Hi all,
I am using Cucumber 3.0.3 and Node.js 8.5. 
I am trying to attach screenshot after each step by using setDefinitionFunctionWrapper, but it looks like world does not exist in it !

Here is my code:
```
import { browser } from 'protractor';
import {defineSupportCode} from 'cucumber';

defineSupportCode (({setDefinitionFunctionWrapper}) => {

 setDefinitionFunctionWrapper(function (fn) {

    (async () => {
      const screenShot = await browser.takeScreenshot();
      this.attach(screenShot, 'image/png');
    }) ();
    
   return fn;
  });
```

And here is log:
```
(node:4669) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'attach' of undefined
```

Anyone pls help.

**Comment by wswebcreation** [comment]
Hi @koprivica 

You are using a arrow function which has no `this` scope. I think that's the problem. 

This should do the trick (sorry for the IT-joke ;-))

```js
import { browser } from 'protractor';
import {defineSupportCode} from 'cucumber';

defineSupportCode (({setDefinitionFunctionWrapper}) => {

    (async function () {
      const screenShot = await browser.takeScreenshot();
      this.attach(screenShot, 'image/png');
    }) ();
    
   return fn;
  });
```

**Comment by koprivica** [comment]
Hi @wswebcreation
Thank you for your reply, but issue still remains. 

I tried with:
```
import { browser } from 'protractor';
import {defineSupportCode} from 'cucumber';

defineSupportCode (function (consumer: any) {

consumer.setDefinitionFunctionWrapper(function (fn) {
    (async function () {
      const screenShot = await browser.takeScreenshot();
      this.attach(screenShot, 'image/png');
    }) ();
    
   return fn;
  });
``` 
and got the same:
`(node:14846) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'attach' of undefined`

**Comment by wswebcreation** [comment]
Hmm,

You are using cucumber i.c.m. with Protractor. When do you want to attach the screenshot? This is for example my implementation and it works as a charm

https://github.com/wswebcreation/protractor-cucumber-typescript-boilerplate/blob/master/e2e-tests/config/helpers/after.scenario.ts

It attaches the screenshot to the report and saves the image to the filesystem (the last can be removed). In my case I only save a screenshot in an `After`-hook which still has the `world` (`this`) context and only when it is failed. 

Personally I never worked with the `setDefinitionFunctionWrapper`, but based on the docs I can't find that it has it's own `World`, see [here](https://github.com/cucumber/cucumber-js/blob/fd1f7a099f0d5b17c887f081c63bfc9a5752d592/docs/support_files/step_definitions.md#definition-function-wrapper)

**Comment by gd46** [comment]
I think because your trying to access this.attach within a  closure. I believe the reference to this is different and won't have access to world. You need to rewrite to remove closure.

**Comment by charlierudolph** [comment]
`setDefinitionFunctionWrapper` was added in order to deal with steps defined as generators (in order to wrap them in something that can properly run them). I would not suggest using it for attaching a screenshot after each step. I think we need a new API if you want to do something after each step.

**Comment by wandroll** [comment]
Steps Hooks would have been convenient for this use case. Too bad we removed them.

**Comment by charlierudolph** [comment]
Closing in favor of #997 as I'm good adding the step hooks back in. They can be built as first class citizens instead of being dependent on a library internal
