### ISSUE TITLE
Require not found

### ISSUE THREAD

**Issue by apichick** [cucumber/cucumber-js#938]
I have the following folder structure

common
|-- features
|---- step_definitions
|------init.js
project1
|-- node_modules
|-- package.json
|-- features
|---- step_definitions
|------project1.js
project2
|-- node_modules
|-- package.json
|-- features
|---- step_definitions
|------project2.js

When I want to run the tests for project 1 one i do

$ cd project1
$ ./node_modules/.bin/cucumber-js --require ../common/features/step_definitions --require features/step_definitions features

In the first line of common/features/step_definitions/init.js I am requiring a module x (const x = require('x');) that is present in project1/package.json as a dev dependency and has been installed, so it is available inside project1/node_modules, but I am getting an error saying "Error: Cannot find x".

This was working fine when using cucumber 1.3.1.

Any ideas how might be going wrong here?

Thanks,

M

**Comment by charlierudolph** [comment]
That doesn't have anything to do with cucumber-js. Node modules are resolved from the file they are required from (and search the current directory and its parents). For reference: https://nodejs.org/api/modules.html#modules_all_together

The common folder should have its own package.json and node_modules for required within it

**Comment by apichick** [comment]
Why was it then working with cucumber 1.3.1?

**Comment by charlierudolph** [comment]
No idea. I don't understand why it was.
