### ISSUE TITLE
Add HTML formatter to CLI

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#94]

**Comment by RootMale** [comment]
Its planned for next releases? Because its most wanted feature.

Also i know about https://github.com/cucumber/cucumber-html and author claims that its works with cucumber-js but no any instructions about it.

Also i see that cucumber-js are depends on it but not use it as formatter.

Can someone make some clarification about it?

**Comment by grumblerchester** [comment]
+1

**Comment by bailejl** [comment]
+1

**Comment by shepely** [comment]
+1

**Comment by bmsoko** [comment]
+1

**Comment by hyperstyle** [comment]
+1

**Comment by paulitto** [comment]
+1

**Comment by jlin412** [comment]
@charlierudolph this will be great feature to have before 1.0.
Another issue tracked same thing is https://github.com/cucumber/cucumber-js/issues/28

**Comment by ijese** [comment]
+1

**Comment by floverdevel** [comment]
+1

**Comment by igniteram** [comment]
+1

**Comment by albertoTena** [comment]
+1

**Comment by JimTheMan** [comment]
how the **** is this not already a feature in this project...

**Comment by gkushang** [comment]
Hi Guys, checkout the [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) for HTML reporting. Converts JSON to HTML reports. Here is the snapshot of it's bootstrap theme,

![screen shot 2016-06-27 at 11 19 12 am](https://cloud.githubusercontent.com/assets/3663389/16391556/b427306e-3c75-11e6-93b1-2add653b6cba.png)

**Comment by JimTheMan** [comment]
@gkushang Nice, I like this cucumber reporting a lot. Especially the pie charts. :)

**Comment by igniteram** [comment]
@gkushang Awesome dude, I can't wait to try it out! 👍

**Comment by charlierudolph** [comment]
Closing in favor of [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) and the future [cucumber html formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter)
