### ISSUE TITLE
Appium + wdio + cucumberjs multiscenaries = not working

### ISSUE THREAD

**Issue by tastafur** [cucumber/cucumber-js#941]
Good Afternoon!

I am trying do test with appium android + wdio + cucumberjs.
Each scenary have a isolate context or this defined in world. 
How could I have the same context for all scenarios to be able to have the same open session while running all scenarios in cucumberjs?

https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/world.md
Thanks

**Comment by charlierudolph** [comment]
> How could I have the same context for all scenarios to be able to have the same open session while running all scenarios in cucumberjs?

There is no built in way to do that in cucumber as that is something discouraged as it can make scenarios dependent on each other. You have to manage that outside of cucumber.

**Comment by christian-bromann** [comment]
@tastafur I recommend to have a look at https://github.com/webdriverio/cucumber-boilerplate

**Comment by tastafur** [comment]
@christian-bromann this is web not mobile native, I have seen all the examples and I have done thousands of tryings

**Comment by christian-bromann** [comment]
> this is web not mobile native

Just change the capabilities of your wdio.config and you get a mobile native session. Setting up Appium might require some work but there are a lot of tutorials on the internet. Generally speaking I don't think this is an issue of cucumber.js. WebdriverIO has a support channel [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to help out with questions like this.
