### ISSUE TITLE
How to use Puppeteer and Headless Chrome with Cucumber-js

### ISSUE THREAD

**Issue by iowyncrox** [cucumber/cucumber-js#944]
Hi, I need a example to run cucumber-js with puppeteer and headless chrome.
Here is the link to a demo github repo which results in errors. You can clone the github repo and run `npm test`

https://github.com/iowyncrox/cucumberpuppeteer

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
