### ISSUE TITLE
Expressions being parsed incorrectly on 6.11.x

### ISSUE THREAD

**Issue by AlexBHarley** [cucumber/cucumber-js#945]
Given the following step

```
When client A queues an event "emit_event" with data { "x": "my_data" }
```

And matching step definition

```
When(/^(.+) queues? (?:an|the|"(\d+)") events? "([^"]*)"(?: with data ("[^"]*"|\d+|\{.*\}))?$/, (clientExpression, numEvents, eventName, rawData) => {
  console.log(clientExpression, numEvents, eventName, rawData)
  // client A, NaN, emit_event, { "x": "my_data" }
})
```

We expect the following to be printed

```
// client A, undefined, emit_event, { "x": "my_data" }
```

I have seen other issues regarding this but they seem to now be resolved. I also looked at your commit history and can see that you're only testing on node 8 now? Our tests run correctly on node 8 but fail on 6.

I have managed to get this to pass by manually setting the cucumber-expressions version to 4.0.1. 

node: 6.11.x
cucumber: 3.0.4
cucumber-expressions: 4.0.4 & 4.0.3
os: Mac OS X 10.12.6 and whatever the default Linux machine Travis-CI use

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#281
