### ISSUE TITLE
Failed step passes but assertion error occurs in After step

### ISSUE THREAD

**Issue by paul-phillips-ark** [cucumber/cucumber-js#946]
Scenario checks default column names.

Feature file:

Scenario: Default Columns Invia Prestazioni
	Given I am on the Invia Prestazioni tab
	Then the Invia Storia table contains column "ID Flusso"
	And the Invia Storia table contains column "Descrizione"
	And the Invia Storia table contains column "User"
	And the Invia Storia table contains column "Data Caricamento"
	And the Invia Storia table contains column "Commoadity"
	And the Invia Storia table contains column "Prestazione"
	And the Invia Storia table contains column "Caricamento"
	And the Invia Storia table contains column "Invio Distributore"
	And the Invia Storia table contains column "Esito 100" 
	And the Invia Storia table contains column "Esito 150"

Cucumber js file:

```
const selenium = require('selenium-webdriver');
const By = selenium.By;
const fs = require('fs');
const sleep = require('system-sleep');
const seleniumTimeOut = 15 * 1000;
const { defineSupportCode } = require('cucumber');
const assert = require('assert');
const request = require('request-promise');

let i = 0;

defineSupportCode(function ({ Then, Given }) {

  Given('I am on the Invia Prestazioni tab', function() {
    driver.findElement(By.css('#app > div > div > div > div.col-xs-offset-2.col-xs-10 > div > div > div:nth-child(1) > ul > li.active.mainTabs'))
    .getAttribute('class').then(function(className) {
      return assert.equal(className, 'active  mainTabs');
    })
  })

  Then('the Invia Storia table contains column {stringInDoubleQuotes}', function (string) {
    driver.findElement(By.css('#app > div > div > div > div.col-xs-offset-2.col-xs-10 > div > div > div:nth-child(4) > div > div > div.react-bs-table.react-bs-table-bordered'))
    .findElements(By.tagName('th'))
    .then(function(thCollection){
      thCollection[i].getText()
      .then(function (val) {
        i++;
        return assert.equal(val, string);
      })
    })
  });

})
```

Command line results:

√ Given I am on the Invia Prestazioni tab
  √ Then the Invia Storia table contains column "ID Flusso"
  √ And the Invia Storia table contains column "Descrizione"
  √ And the Invia Storia table contains column "User"
  √ And the Invia Storia table contains column "Data Caricamento"
  √ And the Invia Storia table contains column "Commoadity"
  √ And the Invia Storia table contains column "Prestazione"
  √ And the Invia Storia table contains column "Caricamento"
  √ And the Invia Storia table contains column "Invio Distributore"
  √ And the Invia Storia table contains column "Esito 100"
  √ And the Invia Storia table contains column "Esito 150"

Failures:

1) Scenario: Default Columns Invia Prestazioni - features\UI.feature:26
   Step: After
   Step Definition: features\support\hooks.js:23
   Message:
     AssertionError: 'Commodity' == 'Commoadity'
         + expected - actual

         -Commodity
         +Commoadity

I inserted an incorrect spelling of commodity to trigger a failure but, as you can see above, it passes the test step but fails in the After step. Any ideas why this might be happening?

**Comment by charlierudolph** [comment]
Your step needs to return the promise of you want cucumber to wait for it to resolve / reject

**Comment by paul-phillips-ark** [comment]
Apologies, but what qualifies as a promise in the above step?

**Comment by charlierudolph** [comment]
Based on your use of `.then` and my prior experience with the selenium webdriver API, I was guessing you are using [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). 

In your first step ('I am on the Invia Prestazioni tab'), I believe the call to `driver.findElement(By.css('...')) .getAttribute('class')` returns a promise. You then call `.then` on it to create a new promise.

If your step is asynchronous, you need to let cucumber know by making use of the callback or promise API: [docs](https://github.com/cucumber/cucumber-js/blob/v3.0.4/docs/support_files/step_definitions.md)

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed
