### ISSUE TITLE
Exception is missing when result is failed

### ISSUE THREAD

**Issue by manu7691** [cucumber/cucumber-js#949]
I ran the node example and I noticed that:
- */runtime/step_runner.js is returning {status: 'failed', exception, duration}: testStepResult, however on */runtime/test_case_runner.js only {status: 'failed', duration} is being returned.

![image](https://user-images.githubusercontent.com/1011682/31483287-fefaf52e-af2b-11e7-809b-e23d736ef4ff.png)

Thanks in advance

**Comment by gd46** [comment]
I believe this PR should fix the issue. Although Im still getting familiar with the code base so Im trying to see how to test it out, and where to add the test cases for it.

**Comment by charlierudolph** [comment]
Resolved in #952, released in 3.2.0
