### ISSUE TITLE
Cucumber Cannot find Step Definitons Please help

### ISSUE THREAD

**Issue by prasannarhegde2015** [cucumber/cucumber-js#950]
Protractor Version : 5.1.2
Cucumber Version latest (installed using npm install -g cucumber)
let me know how to check version of cucumber cucumber --version throws error

Environment: Windows 10
Protractor is not able to execute cucumber steps it cant find steps definitions
Few days back was working fine on same system
not sure what changed after which it stopped working
Searched google a lot did not get it working after trying workarounds suggested

Let me know how to trouble shoot issue

**Comment by charlierudolph** [comment]
Please create an issue on [protractor-cucumber-framework](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework) as that is what is responsible for making protactor and cucumber work together
