### ISSUE TITLE
formatter and formatter output gets confused by windows absolute paths

### ISSUE THREAD

**Issue by darrinholst** [cucumber/cucumber-js#953]
The cli parses `-f C:/custom/formatter:C:/formatter/output` as `C` for the formatter and `/custom/formatter:C:/formatter/output` for the formatter output due to not taking in account that a `:` could appear in a windows path.

**Comment by asmahler** [comment]
Awesome! Was just dealing with this issue this morning! 

Thanks

**Comment by charlierudolph** [comment]
resolved in #954

**Comment by undeadcat** [comment]
Any chance of back-porting this to the 2.x branch and making a 2.x.x release with this fix?

We're working on improving support for cucumber.js in WebStorm and other IntelliJ IDEA-based IDEs as part of [WEB-26185](https://youtrack.jetbrains.com/issue/WEB-26185) and related issues.
We pass a custom formatter to report test results in the UI and hit this when testing on Windows.

There's obviously a workaround possible, but I thought I'd try to ask first...

**Comment by undeadcat** [comment]
Any chance of a back-port to 2.x?
//cc @charlierudolph maybe?
