### ISSUE TITLE
registerHandler is not a function

### ISSUE THREAD

**Issue by NikitaTanwani** [cucumber/cucumber-js#963]
After running the cucumber setup script (rimraf cucumber_report && mkdir cucumber_report && touch cucumber_report/cucumber_report.json)
, on running:
 node_modules/.bin/cucumber.js --compiler es6:babel-core/register -f json:cucumber_report/cucumber_report.json

I get the error: registerHandler is not a function

How to resolve this?

Using versions:
          "cucumber": "^3.0.6",
          "cucumber-html-reporter": "^3.0.4"
          "selenium-webdriver": "^3.3.0"

**Comment by wswebcreation** [comment]
@NikitaTanwani 

Please see the [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes)

You are using version 3, so there are some breaking changes.

**Comment by paulohfcanuto** [comment]
@NikitaTanwani 
The registerHandler function was removed in version 3.x, you can use the BeforeAll / AfterAll functions
