### ISSUE TITLE
TypeError: Cannot read property 'eventBroadcaster' of undefined

### ISSUE THREAD

**Issue by shekss** [cucumber/cucumber-js#964]
I am getting the below error when I am trying to generate cucumberjs report.
I am on Mac Sierra 10.12.6
My cucumberjs file to generate json report is 

```javascript
module.exports = {
    'default': '--format pretty --format json:reports/cucumber_report.json'
}
```

the actual error i am getting in console.

`
TypeError: Cannot read property 'eventBroadcaster' of undefined
    at new JsonFormatter (/Users/raja/cucumberjs/node_modules/cucumber/lib/formatter/json_formatter.js:55:12)
    at /Users/raja/cucumberjs/features/support/hooks.js:62:27
    at defineSupportCode (/Users/raja/cucumberjs/node_modules/cucumber/lib/support_code_library_builder/index.js:43:9)
    at Object.<anonymous> (/Users/raja/cucumberjs/features/support/hooks.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/raja/cucumberjs/node_modules/cucumber/lib/cli/index.js:153:16
    at Array.forEach (native)
    at Cli.getSupportCodeLibrary (/Users/raja/cucumberjs/node_modules/cucumber/lib/cli/index.js:152:24)
    at Cli.<anonymous> (/Users/raja/cucumberjs/node_modules/cucumber/lib/cli/index.js:171:39)
    at Generator.next (<anonymous>)
`
my node version
```node -v
v7.10.0
```
my package.json , cucumber version 3.1.0
```json
 "devDependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "cucumber": "^3.1.0",
    "cucumber-html-reporter": "^3.0.4",
    "selenium-webdriver": "^3.6.0"
  },
```

my code to generate the reports
```javascript
const outputDir = './reports/'
const targetJson = outputDir + 'cucumber_report.json'
const JsonFormatter = require('cucumber').JsonFormatter
const fse = require('fs-extra')
const reporter = require('cucumber-html-reporter')
const {defineSupportCode} = require('cucumber')

defineSupportCode(function ({After, registerListener,AfterAll}) {
         const createHtmlReport = function (sourceJson) {
        const options = {
            theme: 'bootstrap',
            jsonFile: sourceJson,
            output: outputDir + 'cucumber_report.html',
            reportSuiteAsScenarios: true,
            launchReport: false
        }
        reporter.generate(options)
    }
    const jsonFormatter = new JsonFormatter()
    jsonFormatter.log = function (string) {
        if (!fse.existsSync(outputDir)) {
            fse.mkdirSync(outputDir)
        }
        fse.writeFile(targetJson, string, function (err) {
            if (err) {
                console.log('Failed to save cucumber test results to json file.')
                console.log(err)
            } else {
                createHtmlReport(targetJson)
            }
        })
    }
    registerListener(jsonFormatter)
})
```

the code is throwing an error at line `const jsonFormatter = new JsonFormatter()`

I see this issue is related to issue https://github.com/cucumber/cucumber-js/issues/854 but the work around works for cucumber version until 2.0, not for version 3 onwards. please help and many thanks.
raja.

**Comment by gd46** [comment]
I see your passing format as pretty. As of cucumber 3 the pretty format is the default format of each formatter and the pretty format itself no longer exists.

**Comment by charlierudolph** [comment]
Seen this a couple times. `registerListener` was removed in 3.0. Please use the CLI option in order to output the JSON format and if you need to do extra processing of the JSON results please do that in a separate process after cucumber has finished running.  Related #910

**Comment by ludmilanesvitiy** [comment]
@charlierudolph Do you have an example how to `use the CLI option in order to output the JSON format` ?
I'm updating to cucumber 3.1.0 and get error _TypeError: Cannot read property 'on' of undefined_
After adding  eventBroadcaster to my hooks file, this issue fixes, but reports didn't generates and i got this:
![screenshot from 2017-11-07 19-15-53](https://user-images.githubusercontent.com/18209841/32507726-f54401b8-c3f0-11e7-9e72-d554473a480e.png)
