### ISSUE TITLE
BeforeAll/AfterAll are not available.

### ISSUE THREAD

**Issue by kacpe-r** [cucumber/cucumber-js#965]
I'm trying to use AfterAll hook in my hooks file.
There's an usage sample in a documentation [https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md].
Unfortunately, BeforeAll and AfterAll hooks seems not to be available.
I've got an error message: `TS2459:Type 'StepDefinitions & Hooks' has no property 'AfterAll' and no string index signature.`.

![cucucmber](https://user-images.githubusercontent.com/22658209/32161155-d5745916-bd54-11e7-969b-ff53475a2369.png)

My cucucmber version: 3.1.0
Rgs,
Kacper

**Comment by charlierudolph** [comment]
The typescript definitions are not housed in this repo. There was a PR to move them here once but it was closed due to age. Please move this issue to wherever the typescript definitions live
