### ISSUE TITLE
When running all tests scope by npm-run-all if one test dropped - the subsequent tests are skipped

### ISSUE THREAD

**Issue by IvanNaumenko** [cucumber/cucumber-js#967]
[ x] bug report

Hello

I have the next problem
When I run tests by npm-run-all, if one test dropped - the subsequent tests are skipped. I experemented with
end_session_on_fail: true,
skip_testcases_on_fail: true,

and it hasn't helped too.

All test writted by Scenario. 4-5 scenarios in one feature file
When scenario has the success result - all fine: session closed, and another scenario is running. Next scenario starts on the previous dropped page, only page updated after started the new one. New scenario is beginning from start step **on the dropped page**, doesn't find it and dropped, and so on. That behavior I got only with fail tests. I need when scenario is dropped - it should be close browser and next scenario will start.
It's very critical moment.

I run by script npm run test

"test": "npm-run-all start report --continue-on-error"
"start": "nightwatch",
"report": "node reporter.js"

**"cucumber": "^3.1.0",**
"nightwatch": "^0.9.16",
"nightwatch-cucumber": "^8.2.8"

abortOnAssertionFailure: false,

Please, any advise or fixes...anything will help.

![hooks](https://user-images.githubusercontent.com/32741530/32224327-aba1da96-be49-11e7-838b-c831dcfcae4a.jpg)

**Comment by charlierudolph** [comment]
Please move this issue to nightwatch-cucumber / nightwatch. I've never heard of the options you list which i believe are specific to those tools. Cucumber-js is a more generic tool which has no browser dependency.
