### ISSUE TITLE
Getting the step keyword (Given, When, Then) in the After hook

### ISSUE THREAD

**Issue by aaronclong** [cucumber/cucumber-js#969]
In the update from Cucumberjs 2 to 3 the after result no longer contains the step's keyword. Unfortunately for a reporting requirement I need this information to be available. I am wondering if there is anyway to add this back or a new way to receive this information?

**Comment by charlierudolph** [comment]
Are you talking about the step keyword for the failed step? (I didn't even know that was available) The event protocol / json formatters gives more complete information and could be used instead

**Comment by aaronclong** [comment]
@charlierudolph I can't find to what you are referring to in the documentation.
It was possible in version 2, and I am currently keeping my test on version 2 to retain this feature.

**Comment by charlierudolph** [comment]
Format docs: https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats

**Comment by aaronclong** [comment]
@charlierudolph Is there anyway to send commands back to the cucumberjs to trigger a screen capture or anything? That is another use case that is very important to the standards I have to follow.

**Comment by aaronclong** [comment]
I think I found it: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md

**Comment by charlierudolph** [comment]
Closing as this appears to be addressed. Please reopen if needed

**Comment by aaronclong** [comment]
@charlierudolph Can you please reopen this issue. 
I still can't get cucumberjs to output correctly to a file. Even though I am using the formatting option.
- `--format=json:file.txt`
- `--format=json  --format=file.txt`
