### ISSUE TITLE
Add afterAll hooks

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#97]
From https://github.com/cucumber/cucumber-js/issues/84#issuecomment-9942141.

**Comment by charlierudolph** [comment]
Closing as registerHandler now has full support and the passed function can use any of the available interfaces that steps/hooks use and when passed an error it will throw it and kill the test run.

**Comment by jwbuitenhuis** [comment]
In which version is that enhancement? I've tried it in 0.10.4 but it doesn't seem to respond to callback(new Error('foo')).

**Comment by charlierudolph** [comment]
In the future please see the changelog. Searching through it, it appears it was added in 1.1.0

**Comment by alayor** [comment]
@charlierudolph Could you tell me how I can use **registerHandler** using *defineSupportCode*?
```
var {defineSupportCode} = require('cucumber');
```

**Comment by charlierudolph** [comment]
Please see the docs for "Event Handlers". There is a link on the README

**Comment by kyleian** [comment]
Hate to pull this one out of the grave again, but per @charlierudolph's [comment](https://github.com/cucumber/cucumber-js/issues/97#issuecomment-228261085), can you clarify the expectation is that passing an error to the registerHandler callback should infact kill the entire test run? 

In my use case/need, I'd like to fail exclusively the scenario if an error is raised during the AfterScenario hook, but continue the suite after marking that scenario as failed; is this achievable with 1.3.1+? My example usecase would be in the event of failing to tear down mocks generated during the scenario.
