### ISSUE TITLE
Cucumber versions

### ISSUE THREAD

**Issue by NikitaTanwani** [cucumber/cucumber-js#971]
So I'm facing an amusing issue. Two weeks ago when I installed cucumber I got the versions below:

"cucumber": "^3.0.6",
"cucumber-html-reporter": "^3.0.4"

I faced the 'registerHandler issue ' and reported it here - [https://github.com/cucumber/cucumber-js/issues/963]

Now today, I installed cucumber for a new branch and the version getting installed is 2.3.1 although I am aware that v3 is out. So has there been a roll back? I want to be using the latest stable version to avoid any migration problems later on. Can someone clarify why I'm getting v2 now?

Also, there is no documentation for v3 out yet. When will that be available?

Thanks alot.

**Comment by charlierudolph** [comment]
The latest version is 3.1.0, npm reflects that (`npm view cucumber` and look at the 'dist-tags'). I don't see how you would get cucumber 2.3.1 on a new install and am unable to reproduce.

> Also, there is no documentation for v3 out yet

The documentation on master is for the latest version (3.x). Is there some type of documentation you are looking for?

**Comment by NikitaTanwani** [comment]
Yes we are looking for documentation by which we can start using this for our automation in javascript web application. Is there anything that could be helpful regarding that?

Thanks

**Comment by gd46** [comment]
I have this test framework setup that demonstrates an automation framework in javascript.

https://github.com/gd46/dibellag-automation-framework

**Comment by charlierudolph** [comment]
@NikitaTanwani this repo does not contain documentation on that as cucumber-js can be used for many more things than automating browser tests, you need to look elsewhere for this.
