### ISSUE TITLE
Example with browser

### ISSUE THREAD

**Issue by dmitrika** [cucumber/cucumber-js#975]
Hello!

It's a little bit confusing, but I do not see any examples or suggestions how to use cucumber-js within e2e tests.

I see that there was node-js example https://github.com/cucumber/cucumber-js/issues/959, but it was broken (I confirm issue report) and it was changed to non-browser case.

So, I'm wondering what should I do if I want to use cucumber.js and real browser to test my application?

**Upd**. I worked out how to run up puppeteer with cucumber-js and can provide such example, like puppeteer have with google search (https://github.com/GoogleChrome/puppeteer/blob/master/examples/search.js)

**Comment by charlierudolph** [comment]
Cucumber is not tied to a browser. It is only a framework for connecting the language in a feature file to underlying step definitions. The step definitions can drive a browser, but they can also test a cli or node library (like cucumber's own feature tests).

The main point is that what you can use it for is open ended and maintaining a browser based example has been quite annoying in the past.

**Comment by dmitrika** [comment]
I got the point, thanks
