### ISSUE TITLE
Step definitions written to console only for failing scenarios

### ISSUE THREAD

**Issue by merland** [cucumber/cucumber-js#977]
After upgrading to cucumber 3.0.3, the step definitions of my successful BDD scenarios are not output to the console anymore!
However, for failing scenarios I get the full output. Including the successful steps.

How can I fix this? Or analyze it further?

**Comment by Odravison** [comment]
Sadly, it's because the format `pretty` was take off as a option to `format:` parameter.
This behavior was very helpful.

**Comment by charlierudolph** [comment]
Why was this the `pretty` format behavior helpful? In my experience it only caused way too much output for developers. If you want something nice to look at, I'd suggest this: https://github.com/gkushang/cucumber-html-reporter

**Comment by Odravison** [comment]
I'm already using an interface reporter: https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin
It was helpful because was a "human output readable" and the developer knew which step the code had a problem, just in reading the steps.

**Comment by merland** [comment]
Thanks for your input guys. 
We don't have the need for full html reports, is there a simple way to re-enable these console outputs?

**Comment by kozhevnikov** [comment]
Try [cucumber-pretty](https://www.npmjs.com/package/cucumber-pretty)

**Comment by charlierudolph** [comment]
Please use the custom formatter by @kozhevnikov if you want this functionality.
