### ISSUE TITLE
Embed mime type JSON change breaking downstream consumers

### ISSUE THREAD

**Issue by achingbrain** [cucumber/cucumber-js#978]
As part of [this commit](https://github.com/cucumber/cucumber-js/pull/879/files) (I think, there's quite a lot in there) the representation of attachments in the JSON reports changed from:

```json
            "embeddings": [
              {
                "data": "iVBORw0KGgoA...",
                "mime_type": "image/png"
              }
            ],
```

to:

```json
            "embeddings": [
              {
                "data": "iVBORw0KGgoA...",
                "media": {
                  "type": "image/png"
                }
              }
            ]
```

This has [broken](https://github.com/jenkinsci/cucumber-reports-plugin/issues/193) the Jenkins cucumber-report-plugin when used with (for example) attached screenshots.  I've submitted a [PR](https://github.com/damianszczepanik/cucumber-reporting/pull/694) to the underlying library that fixes the problem but the maintainer seems unwilling to merge it, instead preferring that this library revert to the existing JSON report format that is used by other cucumber implementations.

Is there any chance of that happening?

I can submit a PR here too if it helps and is likely to be merged.

**Comment by stefankruijt** [comment]
I would like to see this fixed too. I would prefer to not have to downgrade cucumber-js to a previous version.

**Comment by charlierudolph** [comment]
Looking at the PR in `cucumber-report-plugin` I don't see any language that the maintainer doesn't want to merge it. Tools built off of cucumber need to update as cucumber changes (otherwise cucumber would never be able to change). 

The change to the JSON formatter was to move to a more generic attachment object and one that is shared between other cucumber implementations.

**Comment by achingbrain** [comment]
> Looking at the PR in cucumber-report-plugin I don't see any language that the maintainer doesn't want to merge it.

His comments on that PR came after I opened this ticket.  I was referring to this sort of thing on jenkinsci/cucumber-reports-plugin#193:

> what I can recommend is to push cucumber-js team to fix the problem and not ask to fix all other dependent libraries team to apply workaround

To me, that reads like he'd rather the problem was fixed here and not in a PR to `cucumber-report-plugin`.

**Comment by achingbrain** [comment]
I may be looking in the wrong place but I can't see any other cucumber implementations that use `media.type` - looks like the Java and Ruby ones at least still use `mime_type`.  Is it a new standard for cucumber in the future?

**Comment by charlierudolph** [comment]
The new structure was introduced in the event protocol formatter and I thought it made the most sense to carry that over to the JSON formatter. https://github.com/cucumber/cucumber/pull/172. cucumber-js uses a new event that cucumber-ruby does not so I think it is the first cucumber implementation to do this.

@aslakhellesoy @mattwynne @jbpros what do you all think about keeping this change in the json formatter or do you think it is worth reverting?

**Comment by innocentiv** [comment]
Is my understanding that the JSON formatter is being phased out. I think it would be better to uniform the formatter behaviour between existing implementations and to use the new structure in the event-protocol formatter only.

We should not ask tools maintainers to update upon changes on a deprecated format with no official specification.

**Comment by stefankruijt** [comment]
Is it already known whether this change with the JSON format will be reverted at some point? I'm trying to decide whether it's worth it to revert back to cucumber-js 2 for now, or whether there will be a fix at some point that will make cucumber-js 3 work again with the Jenkins-plugin.

**Comment by charlierudolph** [comment]
I'll revert the change putting it back to the previous version

**Comment by ali-himindz** [comment]
@charlierudolph Any update on this? Are you going to revert it soon? 
(Happy New Year !)
