### ISSUE TITLE
Attach a feature to a specific step definition

### ISSUE THREAD

**Issue by Odravison** [cucumber/cucumber-js#981]
Hello, folks.
I hope that you're all fine.

I'm implementing many tests with protractor and cucumber and I want a way to load only a specific step defenition when run a specific feature, and unload the specific step definition when feature scenarios over.
My concern for this behavior is to guarantee a unique match step loaded for the specific feature, to avoid duplicated matches.

I learned about hooks and tag, and they are (in my conception) the most acceptable way to do that, but I came here to see other ways from the more experts than I.

Do anyone know some other way applying the best practices?

Thanks in advanced.

**Comment by charlierudolph** [comment]
> I'm implementing many tests with protractor and cucumber and I want a way to load only a specific step defenition when run a specific feature, and unload the specific step definition when feature scenarios over.

There is no way to do this and I don't think we should implement a way to do this.

> My concern for this behavior is to guarantee a unique match step loaded for the specific feature, to avoid duplicated matches.

So does you codebase have multiple step definitions for a single step and you want each to be applied only for specific features? My first suggestion is to make them be different steps and otherwise you have one statement doing different things based on the context which I think is confusing. Another suggestion would be to use a single step definition which selects the proper actions based on the context (ie something saved to the world object)

**Comment by Odravison** [comment]
> There is no way to do this and I don't think we should implement a way to do this.

Ok. It's sad read this.

> So does you codebase have multiple step definitions for a single step and you want each to be applied only for specific features? My first suggestion is to make them be different steps and otherwise you have one statement doing different things based on the context which I think is confusing. Another suggestion would be to use a single step definition which selects the proper actions based on the context (ie something saved to the world object)

I agree with your, but I think that you don't get my situation. If I'm wrong, I'm sorry for the explanation below. 

I have a step that is assigned and defined, respectively, as:

**some-file.feature**
```
Context:
[...]
Then see a success message.
```

**some-step.step.js**
```
Then('see a success message.', function (callback) {
	var alertMessage = browser.driver.findElement(by.css('div[type="success"]'));
	alertMessage.getText().then(function (text) {
		expect(text).to.contain('Notificações de Penalidade Geradas com Sucesso.');
	}).then(callback);
		
});
```

Look that's a simple step assign and I should be able to use this in other places into my tests. And I can't because the `cucumber.conf` requires `*.step.js` for each `.feature` that is ran. Would be nice to have a way to attach a specific `.step.js` to a specific `.feature`.

**Comment by charlierudolph** [comment]
> Look that's a simple step assign and I should be able to use this in other places into my tests

What exactly do you mean? If you want to use the same step definition in another feature, I expect that to already be possible. If you want to replace the step definition with another, that is not possible. I would guess by looking at it that you want the validated text to change from other contexts. I think my suggestion `use a single step definition which selects the proper actions based on the context (ie something saved to the world object)` would work in that case

> And I can't because the `cucumber.conf` requires `*.step.js` for each `.feature` that is ran 

`cucumber.conf` is specific to the protractor cucumber framework (a tool which I don't use or know very well) and thus doesn't mean anything to me. 

> Would be nice to have a way to attach a specific `.step.js` to a specific `.feature.`

With the current setup that would require multiple runs of cucumber-js. Cucumber loads all the feature files and all the step definitions at once (I don't know if this is what the protractor plugin does as well). This makes step sharing easy as the same step can be used across multiple features. This is at odds with the idea of having separate step definitions per feature file.

**Comment by Odravison** [comment]
> If you want to replace the step definition with another, that is not possible.

That's I wanted. Sadly cannot.

> This is at odds with the idea of having separate step definitions per feature file.

I saw this while was writing the previous comment, would be nice to have a mechanism to load in run time a step that was write specific to a feature, as well load previously the all generic step (i.e. navigation of a menu system).

Thanks @charlierudolph , for been patient and enlightening.
