### ISSUE TITLE
deprecate defineSupportCode

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#986]
Suggest importing the specific functions Given/When/Then etc instead.

**Comment by jshifflet** [comment]
@charlierudolph this already seems to work. 

For this ticket do the features/step_definitions need to be moved over to not using defineSupportCode?

Is there anything else besides documentation updates that needs done for this ticket?

Thanks.

**Comment by charlierudolph** [comment]
Mainly documentation updates and updating cucumber's own features. Also using `util.deprecate` on defineSupportCode so users know it will removed at the next major version.

**Comment by jbool24** [comment]
@charlierudolph trying to test version 3.2 for server-side only API behavior. Did the placement of files change in this version? Adding files to directories according to [node_example](https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md) but have no access to world functions on "this" inside steps. Is the doc out of sync?

**Comment by charlierudolph** [comment]
@jbool24 that doesn't sound related to this issue. Please check the FAQ linked on the readme or ask in a support channel

**Comment by jbool24** [comment]
@charlierudolph cheers mate
