### ISSUE TITLE
Dots representing the progress instead checked scenarios description

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#988]
_From @Odravison on November 22, 2017 13:16_

Hey Folks,

Earlier I got this versions of protractor and framework:
```
    ...
    "cucumber": "3.0.2",
    "protractor-cucumber-framework": "4.0.7",
    "protractor-jasmine2-screenshot-reporter": "0.3.2",
    ...
```
now when I run `proctractor:cucumber` task, the output is dots and letters that represents result of each test instead checked scenario descriptions like before the update.

My question is: Is possible use some configuration or flag (in CLI) to use scenario descriptions instead dots?

_Copied from original issue: cucumber/cucumber#302_

**Comment by charlierudolph** [comment]
No there currently is no formatter for that. You can search for a custom formatter or create your own: https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md

**Comment by Odravison** [comment]
If anyone have the same issue: https://www.npmjs.com/package/cucumber-pretty
