### ISSUE TITLE
how to know when the report has been generated?

### ISSUE THREAD

**Issue by edento** [cucumber/cucumber-js#989]
### Final goal
Generating an HTML report. I try to use cucumber json file report to generate a HTML report.

### Details (may try skip to the questions)
I am using the last version of cucumber, and interested in generating an HTML report. I tried using your [documentation](https://cucumber.io/docs/reference#reports) but couldn't figure it out.

Therefore I have installed the package [cucumber-html-reporter](https://github.com/gkushang/cucumber-html-reporter). I added it as a separate file and loaded it in hooks.js the following way:

`const reportsHelper = require("../../helpers/reports-helper");`

And the actual use:
`    
AfterAll(function () {
        reportsHelper.generateHTMLReport(); <<<<<< ------- this      
        return globalNameSpace.shared.browser.quit();
    });
`

when I run cucumber, I run this:
`cucumber.js tests/features -f json:tests/report/cucumber_report.json`

The JSON file is being generated, but the HTML reported throws an error:

**Unable to parse cucumberjs output into json: 'tests/report/cucumber_report.json' SyntaxError: tests/report/cucumber_report.json: Unexpected end of JSON input**

My guess is that the writing of the JSON has not been completed by the time the html reporter started reading it.

### Questions:
1. How can I know **when** does the cucumber package finishes writing the JSON report?
2. Can I somehow 'ask' cucumber to generate the report with a config file? rather than a flag?
3. Is there any built in way to get this done in the latest version of cucumber?

Thanks!!!

### System
node 7.6
cucumber 3.2.0
Mac OS 10.12.6

**Comment by charlierudolph** [comment]
> 1. How can I know when does the cucumber package finishes writing the JSON report? 

Wait for the process to end. Process the JSON in a separate node process that runs after cucumber finishes. 

> 2. Can I somehow 'ask' cucumber to generate the report with a config file? rather than a flag?

There is a profile file but I that is limited to cucumber cli options and I think you report generation is a step beyond it: https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#profiles

> 3. Is there any built in way to get this done in the latest version of cucumber?

See answer for 1

**Comment by edento** [comment]
@charlierudolph thank you for your fast reply!

> 3. Is there any built in way to get this done in the latest version of cucumber?
I mean generate the HTML reports, ad it looks like it does exist in your project 
https://cucumber.io/docs/reference#html

If it doesnt, I will have to create another node process, like you said.

thanks again

**Comment by charlierudolph** [comment]
Correct there is no html formatter in cucumber-js. I think that is best as a separate project.
Note cucumber-html-formatter has on its readme that it should be run in a separate process after cucumber-js finishes executing as well.
