### ISSUE TITLE
Access step inside a step in cucumberjs-Protractor

### ISSUE THREAD

**Issue by narayanasamyramaiah** [cucumber/cucumber-js#990]
Hi guys,

Scenario Outline:check numeric behavior
        Given User lands Screen
        When Input Forecast for Attrition level group Month Dec and input <forecastInput>
        Then Verify the input for numeric condition

        Examples:
            | forecastInput    |
            | -14              |
            | 0.99             |
            | 0.9              |

Stepdefinition:

Then(/^Verify the input for numeric condition$/,async()=>{
       Access the step 
       When Input Forecast for (.*) group Month Dec and input <forecastInput>
});

or 

Then(/^Verify the input for numeric condition$/,async()=>{
       Access the step 
       When Input Forecast for  (.*) group Month Dec and input <forecastInput>
        to get the level and forecastInput details for the verification

});

kindly guide.

Thankls

**Comment by charlierudolph** [comment]
Its not possible and will not be implemented in cucumber-js. See #11
