### ISSUE TITLE
Observed 0 scenarios/steps when trying to rerun the failed scenarios

### ISSUE THREAD

**Issue by srbachi** [cucumber/cucumber-js#991]
Observed  0 scenarios/steps when trying to rerun the failed scenarios

My @rerun.txt file has following failed scenarios:
features/test1.feature:136
features/test2.feature:48
features/test3.feature:29:40:46:51
features/test4.feature:12:62:118

Output:
cucumber.js @rerun.txt

0 scenarios
0 steps
0m00.000s

Environment:
cucumber.js version - 3.2.0
Os : Mac and Windows 10

**Comment by charlierudolph** [comment]
Do the file name / line numbers point to scenarios? If not, that would result in no scenarios being run. We have this [test](https://github.com/cucumber/cucumber-js/blob/37b4a679a6f29a2a30999213e5b0e59017f92156/features/rerun_formatter.feature) to verify that functionality.

**Comment by srbachi** [comment]
Yes, they are pointing to the scenario in feature file. This is inconsistent though, out of 5 runs rerun worked only 1 or 2 times.

**Comment by charlierudolph** [comment]
Can you create a share a more complete reproducible example or write a failing feature test? Given our passing test, I don't know how to investigate this further

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if necessary
