### ISSUE TITLE
Sharing custom formatters

### ISSUE THREAD

**Issue by kbrandwijk** [cucumber/cucumber-js#992]
I have built a custom formatter (for TAP output), and now I want to share this formatter. However, I can only specify a file name for a custom formatter. That means I need to point to `node_modules/[myformatter]/dist/tap-formatter.js`, which is not really nice.

Do you have any plans to support pointing to a package? For example by extending the `cucumber.js` configuration file, so I can put something in there like:
```json
{
  "formatters": {
    "tap": "my-package-name"
  }
}
```
So I can use `-f tap`.

**Comment by charlierudolph** [comment]
If `[myformatter]` has `"main": "dist/tap-formatter.js"` in its `package.json` then you would be able to do `-f node_modules/[myformatter]`.

We could still create this formatter alias block so it can be applied with a nicer name, but the user shouldn't need to specify the path within the node module in most cases

**Comment by kbrandwijk** [comment]
@charlierudolph That's a proper intermediate solution. Thanks.

**Comment by charlierudolph** [comment]
Closing and will add a comment to #751
