### ISSUE TITLE
Different way to specify configuration settings

### ISSUE THREAD

**Issue by kbrandwijk** [cucumber/cucumber-js#993]
Currently, the only way to reuse configuration options is by exporting an object from a `cucumber.js` file. Are there any plans to follow a more 'standard' way of defining configuration, for example with a key in `package.json` or a seperate `.cucumber.yml` or something?

This would be similar to what how a lot of other packages work (nyc, tsc, etc.)

Related to #992

**Comment by charlierudolph** [comment]
I think a yml file would be best as I think its easier to read and write than json. See #751 for a somewhat related discussion. Related to #992 we could update it so the profiles are nested under a `profiles` key which would open it up so we can add other data in there as well.

**Comment by charlierudolph** [comment]
closing in favor of #751, commented the important new ideas there
