### ISSUE TITLE
How to prevent console output when writing to file

### ISSUE THREAD

**Issue by kbrandwijk** [cucumber/cucumber-js#994]
When I use a formatter, I get the desired output to the console. Now, if I specify a file name for that formatter, the results get saved correctly, but a summary output is also sent to console (even though I haven't specified that formatter).

I would like the output to adhere to what I specify. If I only specify file outputs on my formatters, there should be no output to console.

**Comment by charlierudolph** [comment]
This can be achieved by redirecting stdout output to a file: `cucumber-js > output.txt`. Currently the rule is that stdout most always have a formatter and you can have multiple outputs by specifying formats that go to other files

**Comment by kbrandwijk** [comment]
Okay, so if I only want to use 1 formatter and write to file, I would do `cucumber-js -f myFormat > output.txt` instead of `cucumber-js -f myFormat:output.txt`. It great that it's possible, but if I want to write 2 different file formats, I need to redirect one, and `:` the other, like `cucumber-js -f firstFormat:first.txt -f secondFormat > second.txt`.

What is the reason for requiring a stdout formatter instead of just using whatever I specify?

**Comment by charlierudolph** [comment]
I believe that is just a matter of defaults. 

The current default is the progress formatter to stdout. You can override the stdout format. Stdout can then be redirected to a file using your shell. Cucumber also provided a functionality so you can get additional outputs (which are output directly to files).

Here are some example given that default
```bash
# progress => stdout
cucumber-js

# json => stdout
cucumber-js -f json

# json => file1
cucumber-js -f json > file1

# json => file1, progress to stdout
cucumber-js -f json:file1

# json => file1, usage => file2
cucumber-js -f json:file1 -f usage > file2 

# json => file1, usage => file2, progress => stdout
cucumber-js -f json:file1 -f usage:file2
```

It appears you want it so if you specify any format then all formats become manual. Here are some examples using your default

```bash
# progress => stdout
cucumber-js

# json => stdout
cucumber-js -f json

# json => file1
cucumber-js -f json > file1
cucumber-js -f json:file1

# json => file1, progress to stdout
cucumber-js -f json:file1 -f progress

# json => file1, usage => file2
cucumber-js -f json:file1 -f usage > file2 
cucumber-js -f json:file1 -f usage:file2 

# json => file1, usage => file2, progress => stdout
cucumber-js -f json:file1 -f usage:file2 -f progress
```

An interesting part here is it gives multiple ways to accomplish the same thing. I typically prefer one way to do something as its less to maintain. 

Defaults can be changed but it mainly depends on what you think is the proper default for the majority of people. 

I'm hesitant suppressing output to stdout as that is how people get status updates on any CLI tool. Also something extra outputting to stdout isn't a problem and I think is more often a benefit as you get feedback quicker then having to wait for the program to end.

**Comment by kbrandwijk** [comment]
You are right that it is mainly a matter of defaults. The reason I noticed it, is because I always use it together with `nyc` for code coverage, and `nyc` uses a different default, which is: if you don't specify a reporter, it outputs the default summary to stdout. If you specify a reporter, it uses that only. So if I specify `lcovonly`, it creates a file, but doesn't output to console. The confusing thing with `nyc` on the other hand is, that some reporters output to file _and_ stdout, and others only to file. On that point, `cucumber` does a better job in my opinion.

As this is just a matter of defaults, as you said, let's leave it at that for now. It's not a limitation, and I can definitely achieve the result I'm after using your suggestions, so all in all, it's not really an issue anymore for me.

Thank you for your feedback.
