### ISSUE TITLE
Include scenario status in the json output?

### ISSUE THREAD

**Issue by kevinkuszyk** [cucumber/cucumber-js#999]
Unless I've missed something, I don't see the scenario status in the json report:

``` json
{
    "id": "a-mock-feature;a-passing-test",
    "keyword": "Scenario",
    "line": 8,
    "name": "A passing test",
    "tags": [  ],
    "type": "scenario",
    "steps": [  ]
}
```

But I do see it for each step:

``` json
{
    "keyword": "Before",
    "hidden": true,
    "match": {
        "location": " ... \\define_helpers.js:137"
    },
    "result": {
        "status": "passed",
        "duration": 1
    }
},
```

If this is indeed a missing feature, I'd be happy to start working on a PR.

**Comment by charlierudolph** [comment]
That was never implemented. The JSON formatter is essentially deprecated in favor of the event protocol formatter which does have a status on the scenario level (scenarios become test-cases in the event protocol formatter)

**Comment by kevinkuszyk** [comment]
> The JSON formatter is essentially deprecated in favor of the event protocol formatter which does have a status on the scenario level

@charlierudolph oh.  I didn't see that in the docs anywhere.  I think there will be a lot of downstream libs that will be broken if you drop support for JSON file output (we're using a couple here).  Is there an alternative way to get JSON file showing the results instead?

> scenarios become test-cases in the event protocol formatter

Great, I'm trying to get each scenario to show up as a test in Team City.  At the moment we're using @oledid-js's [cucumber-json-to-teamcity](https://github.com/oledid-js/cucumber-json-to-teamcity) lib which needs some changes to map scenarios to tests.
